const pptxgen = require('pptxgenjs');
const pres = new pptxgen();
pres.layout = 'LAYOUT_WIDE';
const RED='8C1D2B', DARK='2B2B2B', GREY='6B6B6B', TINT='F7EEEF', GOLD='C9A227', WHITE='FFFFFF', NOTE='FBEBD0';
const HF='Cambria', BF='Calibri';
const IMG={fig4_1:[1417,1043],fig4_2:[1322,1192],fig4_3:[1279,1649],fig4_4:[1348,587],tab4_1a:[1302,1075],tab4_2:[1298,1379],tab4_3:[1301,886],tab4_4:[1298,1142],cap4_1:[1334,859]};
let n=0;
function fit(s,key,x,y,maxW,maxH){const [w,h]=IMG[key];const r=Math.min(maxW/w,maxH/h);const W=w*r,H=h*r;s.addImage({path:key+'.png',x:x+(maxW-W)/2,y:y,w:W,h:H});return H;}
function base(kicker,title,src,notes){
  n++; const s=pres.addSlide(); s.background={color:WHITE};
  if(kicker) s.addText(kicker,{x:0.6,y:0.22,w:11,h:0.3,fontFace:BF,fontSize:11,bold:true,color:RED,charSpacing:2,margin:0,isTextBox:true});
  s.addText(title,{x:0.6,y:0.48,w:12.1,h:0.95,fontFace:HF,fontSize:23,bold:true,color:DARK,margin:0,isTextBox:true,valign:'top'});
  if(src) s.addText('Sumber: '+src,{x:0.6,y:7.0,w:11.5,h:0.3,fontFace:BF,fontSize:9,color:GREY,margin:0,isTextBox:true});
  s.addText(String(n),{x:12.5,y:7.0,w:0.4,h:0.3,fontFace:BF,fontSize:9,color:GREY,align:'right',margin:0,isTextBox:true});
  if(notes) s.addNotes(notes);
  return s;
}
function circle(s,num,x,y,d=0.5){s.addShape(pres.shapes.OVAL,{x,y,w:d,h:d,fill:{color:RED},line:{color:RED}});s.addText(String(num),{x,y,w:d,h:d,fontFace:HF,fontSize:d>0.45?14:11,bold:true,color:WHITE,align:'center',valign:'middle',margin:0,isTextBox:true});}
function card(s,x,y,w,h,head,body,o={}){
  s.addShape(pres.shapes.ROUNDED_RECTANGLE,{x,y,w,h,fill:{color:o.fill||TINT},line:{color:o.fill||TINT},rectRadius:0.08});
  if(head) s.addText(head,{x:x+0.15,y:y+0.1,w:w-0.3,h:0.35,fontFace:BF,fontSize:o.hs||13,bold:true,color:o.hc||RED,margin:0,isTextBox:true,valign:'top'});
  if(body) s.addText(body,{x:x+0.15,y:y+(head?0.45:0.12),w:w-0.3,h:h-(head?0.55:0.24),fontFace:BF,fontSize:o.bs||12,color:DARK,margin:0,isTextBox:true,valign:'top',paraSpaceAfter:3});
}
function para(s,t,x,y,w,h,fs=13,color=DARK,bold=false){s.addText(t,{x,y,w,h,fontFace:BF,fontSize:fs,color,bold,margin:0,isTextBox:true,valign:'top'});}
function big(s,val,label,x,y,w,h){card(s,x,y,w,h,null,null);s.addText(val,{x:x+0.15,y:y+0.08,w:w-0.3,h:0.75,fontFace:HF,fontSize:30,bold:true,color:RED,margin:0,isTextBox:true});para(s,label,x+0.15,y+0.9,w-0.3,h-1.0,11.5);}
function section(kicker,title,sub,notes){n++;const s=pres.addSlide();s.background={color:RED};
  s.addText(kicker,{x:0.8,y:2.3,w:11,h:0.4,fontFace:BF,fontSize:13,bold:true,color:GOLD,charSpacing:3,margin:0,isTextBox:true});
  s.addText(title,{x:0.8,y:2.8,w:11.5,h:1.4,fontFace:HF,fontSize:38,bold:true,color:WHITE,margin:0,isTextBox:true,valign:'top'});
  if(sub) s.addText(sub,{x:0.8,y:4.3,w:11,h:1.6,fontFace:BF,fontSize:15,color:'F3DCDF',margin:0,isTextBox:true,valign:'top'});
  s.addText(String(n),{x:12.5,y:7.0,w:0.4,h:0.3,fontFace:BF,fontSize:9,color:'F3DCDF',align:'right',margin:0,isTextBox:true});if(notes)s.addNotes(notes);return s;}
const BOOK='Thompson, Peteraf, Gamble & Strickland (2024), Crafting & Executing Strategy, ed. 24, Chapter 4';
const CASE='Grant (2010), Case 6 "Manchester United: Preparing for Life without Ferguson"';

// 1 Title
{n++;const s=pres.addSlide();s.background={color:RED};
 s.addText('STRATEGIC MANAGEMENT · MAN 5422 · SESI 5',{x:0.8,y:0.8,w:11,h:0.4,fontFace:BF,fontSize:13,bold:true,color:GOLD,charSpacing:3,margin:0,isTextBox:true});
 s.addText('Chapter 4\nEvaluating a Company’s Resources, Capabilities, and Competitiveness',{x:0.8,y:1.4,w:11.5,h:2.0,fontFace:HF,fontSize:36,bold:true,color:WHITE,margin:0,isTextBox:true,valign:'top'});
 s.addText('Studi kasus: Manchester United, Preparing for Life without Ferguson (Grant, 2010). Situasi kasus: Juli 2009.',{x:0.8,y:3.6,w:11.5,h:0.6,fontFace:BF,fontSize:16,color:'F3DCDF',margin:0,isTextBox:true});
 s.addShape(pres.shapes.ROUNDED_RECTANGLE,{x:0.8,y:4.6,w:5.6,h:2.1,fill:{color:'A3303E'},line:{color:'A3303E'},rectRadius:0.08});
 s.addText([{text:'KELOMPOK 4',options:{bold:true,color:GOLD,breakLine:true,fontSize:11}},{text:'Fitra Aidila · Aulia Sisca Rahmadiyanti · Bagaskoro · Imam Prayudha · Tegar Awanto',options:{color:WHITE,fontSize:14}}],{x:1.0,y:4.75,w:5.2,h:1.8,fontFace:BF,margin:0,isTextBox:true,valign:'top',paraSpaceAfter:6});
 s.addShape(pres.shapes.ROUNDED_RECTANGLE,{x:6.8,y:4.6,w:5.7,h:2.1,fill:{color:'A3303E'},line:{color:'A3303E'},rectRadius:0.08});
 s.addText([{text:'DOSEN PENGAMPU',options:{bold:true,color:GOLD,breakLine:true,fontSize:11}},{text:'Dr. Rangga Almahendra, S.T., M.M.',options:{color:WHITE,fontSize:14,breakLine:true}},{text:'MM UGM Jakarta · SEMBA · 2 Oktober 2026',options:{color:'F3DCDF',fontSize:12}}],{x:7.0,y:4.75,w:5.3,h:1.8,fontFace:BF,margin:0,isTextBox:true,valign:'top',paraSpaceAfter:6});
 s.addNotes('Selamat pagi Bapak dan teman-teman. Kami Kelompok 4 akan membahas Chapter 4, yaitu cara menilai kekuatan perusahaan dari dalam: resource, capability, dan daya saingnya. Setelah teori, kami terapkan pada kasus Manchester United tahun 2009, saat klub bersiap kehilangan Sir Alex Ferguson.');
}
// 2 Agenda
{const s=base('ALUR PRESENTASI','Teori dulu, lalu kasus, lalu keputusan','Urutan analisis kasus mengikuti Appendix 3 silabus: Problem, Alternatives, Issues, Conclusion.',
 'Presentasi ini ada empat bagian. Pertama teori Chapter 4: enam pertanyaan dan alat untuk menjawabnya. Kedua, kami terapkan alat itu pada Manchester United. Ketiga, kami ambil keputusan dengan pola analisis kasus dari silabus. Keempat, sumber data dan diskusi.');
 const items=[['01','Teori Chapter 4','Enam pertanyaan untuk menilai perusahaan dari dalam, dan alat untuk menjawab tiap pertanyaan. Gambar diambil langsung dari buku.','Slide 3–16'],['02','Kasus Manchester United','Kinerja, SWOT, resource dan capability, VRIN test, value chain, benchmarking, competitive strength assessment, priority list.','Slide 18–31'],['03','Keputusan','Masalah, tiga alternatif, isu sebagai pertanyaan, argumen tandingan, simpulan, rencana implementasi.','Slide 33–38'],['04','Sumber dan diskusi','Dari mana setiap angka berasal, lalu tanya jawab.','Slide 39–40']];
 items.forEach((it,i)=>{const x=0.6+i*3.1;card(s,x,1.8,2.9,4.6,null,null);circle(s,it[0],x+0.2,2.0,0.6);s.addText(it[1],{x:x+0.2,y:2.8,w:2.5,h:0.9,fontFace:HF,fontSize:16,bold:true,color:DARK,margin:0,isTextBox:true,valign:'top'});para(s,it[2],x+0.2,3.7,2.5,1.9,12);para(s,it[3],x+0.2,5.8,2.5,0.4,11,RED,true);});
}
// 3 Six questions
{const s=base('BAGIAN A · TEORI CHAPTER 4','Enam pertanyaan untuk menilai perusahaan dari dalam',BOOK+', hlm. 88–89.',
 'Chapter 4 disusun sebagai enam pertanyaan yang berurutan. Pertanyaan 1 mengukur hasil. Pertanyaan 2 mencari sebabnya secara garis besar. Pertanyaan 3 dan 4 menggali sebab itu lebih dalam. Pertanyaan 5 membandingkan dengan pesaing. Pertanyaan 6 menyusun daftar isu yang harus ditangani. Jawaban tiap pertanyaan menjadi bahan untuk pertanyaan berikutnya.');
 para(s,'Chapter 3 menilai industri dari luar. Chapter 4 menilai perusahaan dari dalam. Caranya dengan enam pertanyaan. Jawaban satu pertanyaan menjadi bahan untuk pertanyaan berikutnya.',0.6,1.45,12,0.7,13,GREY);
 const q=[['Seberapa baik strategi yang sekarang bekerja?','Indikator kinerja dan rasio keuangan (Table 4.1)'],['Apa kekuatan dan kelemahan kita, dibandingkan peluang dan ancaman?','SWOT analysis (Table 4.2, Figure 4.2)'],['Resource dan capability apa yang paling penting, dan apakah tahan lama?','Table 4.3, VRIN test, dynamic capability'],['Bagaimana aktivitas di value chain memengaruhi biaya dan nilai?','Value chain (Figure 4.3, 4.4), benchmarking'],['Kita lebih kuat atau lebih lemah dari pesaing utama?','Competitive strength assessment (Table 4.4)'],['Isu apa yang harus ditangani lebih dulu?','Priority list']];
 q.forEach((it,i)=>{const col=i%3,row=Math.floor(i/3);const x=0.6+col*4.1,y=2.3+row*2.3;card(s,x,y,3.9,2.1,null,null);circle(s,i+1,x+0.2,y+0.2,0.5);s.addText(it[0],{x:x+0.85,y:y+0.15,w:2.9,h:1.1,fontFace:BF,fontSize:13,bold:true,color:DARK,margin:0,isTextBox:true,valign:'top'});para(s,it[1],x+0.85,y+1.35,2.9,0.6,11.5,RED);});
}
// 4 Q1 Figure 4.1
{const s=base('PERTANYAAN 1','Kenali dulu strategi yang sedang dijalankan (Figure 4.1)',BOOK+', Figure 4.1 hlm. 90; indikator kinerja hlm. 91.',
 'Sebelum menilai apakah strategi berhasil, kita harus tahu dulu strateginya apa. Figure 4.1 membantu. Di tengah ada business strategy, yaitu rencana bersaing perusahaan. Di sekelilingnya ada strategi tiap fungsi: produksi, pemasaran, keuangan, SDM, dan lainnya. Cara pakainya sederhana: isi tiap kotak dengan tindakan nyata perusahaan, lalu lihat apakah semua tindakan itu searah. Setelah itu baru kinerjanya diukur: tren penjualan dan laba, harga saham, kekuatan keuangan, retensi pelanggan, dan perbaikan proses internal.');
 fit(s,'fig4_1',0.6,1.5,6.6,5.3);
 card(s,7.5,1.5,5.2,2.2,'Apa isi gambar ini','Di tengah: business strategy, yaitu rencana perusahaan untuk bersaing. Di sekelilingnya: strategi tiap fungsi (produksi, pemasaran, keuangan, SDM, dan lainnya). Kotak-kotak luar: tindakan untuk merespons perubahan, membangun keunggulan, memperluas pasar, dan bermitra.');
 card(s,7.5,3.85,5.2,1.35,'Cara memakainya','Isi setiap kotak dengan tindakan nyata perusahaan. Lalu periksa: apakah semua tindakan itu searah dan saling mendukung?');
 card(s,7.5,5.35,5.2,1.45,'Setelah itu, ukur kinerjanya','Tren penjualan dan laba, harga saham, kekuatan keuangan, pelanggan yang bertahan dan pelanggan baru, perbaikan proses internal. Kinerja lesu hampir selalu berarti strategi lemah, pelaksanaan lemah, atau keduanya.');
}
// 5 Q1 Table 4.1
{const s=base('PERTANYAAN 1 · TABLE 4.1','Rasio keuangan: alat mengukur kinerja dengan angka',BOOK+', Table 4.1 hlm. 91–93.',
 'Kinerja strategi harus dibuktikan dengan angka, bukan kesan. Table 4.1 memberi daftar rasio yang biasa dipakai. Yang ditampilkan di sini bagian profitabilitas: gross margin, operating margin, net margin, return on assets, return on equity, dan return on invested capital. Buku juga menyebut rasio likuiditas, leverage, aktivitas, dan ukuran lain seperti free cash flow. Untuk klub sepak bola, rasio paling penting justru tidak ada di tabel ini: rasio gaji terhadap pendapatan. Kasus Manchester United menyediakan angkanya.');
 fit(s,'tab4_1a',0.6,1.5,6.6,5.3);
 card(s,7.5,1.5,5.2,2.55,'Apa isi tabel ini','Rasio profitabilitas: seberapa besar laba yang dihasilkan dari penjualan, aset, dan modal. Contoh: net profit margin adalah laba bersih dibagi pendapatan. Return on equity yang wajar menurut buku sekitar 12 sampai 15 persen.');
 card(s,7.5,4.2,5.2,1.3,'Kelompok rasio lain di buku','Likuiditas (mampu bayar utang jangka pendek?), leverage (seberapa berat utang?), aktivitas (seberapa efisien aset dipakai?), dan free cash flow.');
 card(s,7.5,5.65,5.2,1.15,'Untuk klub sepak bola','Rasio yang paling menjelaskan adalah gaji dibagi pendapatan. Rasio ini tidak ada di tabel, tetapi ada di kasus.',{fill:NOTE});
}
// 6 Q2 SWOT
{const s=base('PERTANYAAN 2 · SWOT ANALYSIS','SWOT: kekuatan, kelemahan, peluang, ancaman (Table 4.2)',BOOK+', hlm. 94–96; Table 4.2 hlm. 96.',
 'Pertanyaan 1 memberi tahu apakah strategi berhasil. Pertanyaan 2 mencari sebabnya dengan SWOT. Table 4.2 adalah daftar periksa: apa saja yang bisa disebut kekuatan, kelemahan, peluang, dan ancaman. Sebelum mengisi daftar, buku membedakan tiga tingkat kemampuan: competence, distinctive competence, dan core competence. Menyebut sesuatu sebagai kekuatan belum cukup; kita harus tahu ada di tingkat mana.');
 fit(s,'tab4_2',0.6,1.5,6.0,5.3);
 card(s,6.9,1.5,5.8,1.6,'Apa isi tabel ini','Daftar periksa untuk mengisi empat kotak SWOT. Contoh kekuatan: merek kuat, core competence, biaya rendah. Contoh kelemahan: utang terlalu tinggi, tidak ada arah strategi.');
 card(s,6.9,3.25,5.8,2.0,'Tiga tingkat kemampuan','Competence: sudah bisa dikerjakan dengan baik.\nDistinctive competence: dikerjakan lebih baik daripada pesaing.\nCore competence: dikerjakan dengan baik dan menjadi inti strategi. Contoh buku: manajemen merek di Procter & Gamble.');
 card(s,6.9,5.4,5.8,1.4,'Empat pertanyaan yang harus dijawab SWOT','Apakah kekuatan cukup menutup kelemahan? Apakah strategi memakai kekuatan itu? Apakah kekuatan kita melebihi pesaing? Apakah strategi berhasil menahan ancaman?');
}
// 7 Q2 Figure 4.2
{const s=base('PERTANYAAN 2 · FIGURE 4.2','SWOT tidak berhenti pada empat daftar',BOOK+', Figure 4.2 hlm. 97.',
 'Ini bagian SWOT yang paling sering dilupakan. Figure 4.2 menunjukkan tiga langkah. Langkah satu, susun empat daftar. Langkah dua, tarik kesimpulan: kenapa strategi berhasil atau gagal, dan apa yang paling menarik serta paling mengkhawatirkan. Langkah tiga, ubah kesimpulan menjadi tindakan. Yang dinilai bukan daftarnya, tetapi kesimpulan dan tindakannya.');
 fit(s,'fig4_2',0.6,1.5,6.4,5.3);
 const steps=[['Langkah 1: susun daftar','Isi empat kotak berdasarkan bukti, bukan pendapat. Table 4.2 jadi pemandu.'],['Langkah 2: tarik kesimpulan','Kenapa strategi berhasil atau gagal? Apa yang paling menarik, apa yang paling mengkhawatirkan?'],['Langkah 3: ubah jadi tindakan','Pakai kekuatan sebagai dasar, perbaiki kelemahan yang mengganggu, kejar peluang yang paling cocok, tahan ancaman.']];
 steps.forEach((st,i)=>{const y=1.5+i*1.55;circle(s,i+1,7.3,y+0.1,0.5);card(s,7.95,y,4.75,1.4,st[0],st[1]);});
 card(s,7.3,6.2,5.4,0.6,null,'Yang dinilai bukan daftarnya, tetapi kesimpulan dan tindakannya.',{fill:NOTE});
}
// 8 Q3 Table 4.3
{const s=base('PERTANYAAN 3 · TABLE 4.3','Resource dan capability adalah dua hal yang berbeda',BOOK+', hlm. 98–100; Table 4.3 hlm. 99.',
 'Resource adalah apa yang dimiliki perusahaan. Capability adalah apa yang bisa dikerjakan perusahaan. Table 4.3 membagi resource menjadi dua: tangible, yang bisa disentuh atau dihitung, seperti pabrik, kas, dan paten; dan intangible, yang tidak berwujud, seperti merek, pengetahuan orang, hubungan, dan budaya. Buku sengaja menaruh sumber daya manusia di kelompok intangible, karena nilainya ada pada keterampilan, bukan pada jumlah orang.');
 fit(s,'tab4_3',0.6,1.5,7.0,4.8);
 card(s,7.9,1.5,4.8,1.5,'Resource','Apa yang dimiliki atau dikendalikan perusahaan. Contoh: merek, stadion, kas, kontrak, jaringan pemasok.');
 card(s,7.9,3.15,4.8,1.5,'Capability','Apa yang bisa dikerjakan perusahaan dengan baik. Dibangun dengan memakai resource. Contoh: kemampuan melatih pemain muda.');
 card(s,7.9,4.8,4.8,2.0,'Apa isi tabel ini','Tangible: fisik, keuangan, teknologi, organisasi. Intangible: orang dan pengetahuannya, merek dan reputasi, hubungan, budaya. Sumber daya manusia masuk intangible karena nilainya ada pada keterampilan, bukan jumlah orang.');
}
// 9 Q3 finding capabilities + bundle
{const s=base('PERTANYAAN 3 · LANJUTAN','Cara menemukan capability, dan apa itu resource bundle',BOOK+', hlm. 100–101.',
 'Capability lebih sulit dilihat daripada resource. Buku memberi dua cara. Cara pertama, mulai dari daftar resource lalu tanya kemampuan apa yang tumbuh darinya. Cara kedua, telusuri tiap fungsi perusahaan. Kelemahan cara kedua: kemampuan terpenting sering lintas fungsi. Kumpulan aset yang saling terkait di sekitar kemampuan lintas fungsi itu disebut resource bundle. Ini penting karena bundle bisa lolos VRIN test walaupun bagian-bagiannya sendiri tidak. Untuk Manchester United, sistem Ferguson adalah resource bundle.');
 card(s,0.6,1.5,6.0,2.3,'Cara 1: mulai dari resource','Lihat daftar resource, lalu tanya: kemampuan apa yang tumbuh dari sini? Contoh: armada truk dan gudang otomatis menandakan kemampuan logistik.');
 card(s,6.75,1.5,6.0,2.3,'Cara 2: mulai dari fungsi','Telusuri tiap bagian: produksi, penjualan, riset. Kelemahannya: kemampuan terpenting sering lahir dari kerja sama antarbagian, seperti desain Warby Parker yang lahir dari desainer, riset pasar, dan pemasok.');
 card(s,0.6,4.0,12.15,2.8,'Resource bundle','Kumpulan aset yang saling terkait erat di sekitar satu kemampuan lintas fungsi. Bundle bisa lolos VRIN test walaupun bagian-bagiannya sendiri tidak lolos. Contoh buku: gabungan desain, riset pasar, dukungan atlet, merek, dan manajemen membuat Nike nomor satu lebih dari 20 tahun.\n\nUntuk Manchester United: pemandu bakat, akademi, disiplin latihan, rotasi skuad, dan kebijakan transfer masing-masing bisa ditiru. Gabungannya sebagai satu sistem yang sulit ditiru.',{bs:13});
}
// 10 VRIN
{const s=base('PERTANYAAN 3 · VRIN TEST','Empat saringan untuk keunggulan yang bertahan',BOOK+', hlm. 101–103. Definisi tes N dikutip persis dari buku.',
 'Punya resource belum berarti unggul. VRIN test memeriksa empat hal. Valuable: apakah relevan dengan strategi. Rare: apakah pesaing tidak punya. Inimitable: apakah sulit ditiru. Nonsubstitutable: apakah pesaing tidak bisa mendapat hasil yang sama dengan cara lain. Dua tes pertama menentukan apakah ada keunggulan. Dua tes terakhir menentukan apakah keunggulan itu bertahan. Hati-hati pada tes N: kalau tidak ada penggantinya, artinya lolos, bukan gagal.');
 const v=[['V','Valuable','Apakah bernilai untuk bersaing? Harus langsung menopang strategi. Contoh gagal: Google Wallet, walaupun memakai teknologi Google.'],['R','Rare','Apakah langka, tidak dimiliki pesaing? Kalau semua punya, itu syarat ikut main, bukan pembeda. Merek Oreo langka; kemampuan pemasaran produsen sereal tidak.'],['I','Inimitable','Apakah sulit ditiru? Sulit ditiru kalau unik, dibangun bertahun-tahun, mahal, atau rumit secara sosial sehingga pesaing tidak tahu apa yang harus ditiru (causal ambiguity).'],['N','Nonsubstitutable','Buku: "is it invulnerable to the threat of substitution from different types of resources and capabilities?" Lolos kalau pesaing tidak bisa mendapat hasil sama lewat cara lain. Contoh gagal: otomasi dikalahkan tenaga kerja murah.']];
 v.forEach((it,i)=>{const x=0.6+i*3.08;card(s,x,1.5,2.9,4.5,null,null);s.addText(it[0],{x:x+0.15,y:1.6,w:0.9,h:0.9,fontFace:HF,fontSize:44,bold:true,color:RED,margin:0,isTextBox:true});s.addText(it[1],{x:x+0.15,y:2.45,w:2.6,h:0.4,fontFace:BF,fontSize:14,bold:true,color:DARK,margin:0,isTextBox:true});para(s,it[2],x+0.15,2.9,2.6,3.05,11);});
 card(s,0.6,6.15,12.15,0.7,null,'V dan R menentukan apakah ada keunggulan. I dan N menentukan apakah keunggulan itu bertahan. Kebanyakan perusahaan hanya punya satu atau dua aset yang lolos semua.',{fill:NOTE,bs:12.5});
}
// 11 Dynamic capability
{const s=base('PERTANYAAN 3 · DYNAMIC CAPABILITY','Resource harus terus diperbarui',BOOK+', hlm. 103–104.',
 'Lolos VRIN hari ini tidak berarti aman selamanya. Ada tiga ancaman: pesaing menyusul, aset menyusut kalau dibiarkan, dan pasar berubah. Karena itu perusahaan butuh dynamic capability, yaitu kemampuan memperbarui resource secara rutin. Dua jalurnya: memperbaiki yang ada sedikit demi sedikit, atau menambah yang baru lewat aliansi dan akuisisi. Pertanyaan untuk kasus nanti: kemampuan Manchester United membangun ulang skuad tiga kali, milik klub atau milik Ferguson?');
 const t=[['Pesaing menyusul','Yang awalnya tidak bisa meniru, lama-lama menemukan cara.'],['Aset menyusut sendiri','Resource yang dibiarkan akan berkurang nilainya, seperti mesin yang tidak dirawat.'],['Pasar berubah','Teknologi, selera, atau jalur distribusi berubah. Buku: aset bisa berubah "dari berlian jadi karat".']];
 t.forEach((it,i)=>card(s,0.6+i*4.1,1.5,3.9,1.6,it[0],it[1]));
 card(s,0.6,3.3,12.15,3.5,'Dynamic capability','Kemampuan memperbarui resource dan capability secara rutin, bukan sekali-sekali. Kalau memperbarui sudah jadi kebiasaan manajemen, kemampuan itu sendiri menjadi capability.\n\nDua jalurnya:\n• Memperbaiki yang ada sedikit demi sedikit. Contoh: Toyota terus menyempurnakan sistem produksinya.\n• Menambah yang baru lewat aliansi atau akuisisi. Contoh: GM bermitra dengan LG untuk mobil listrik.\n\nPertanyaan untuk kasus: Manchester United membangun ulang skuad tiga kali tanpa berhenti juara. Kemampuan itu milik klub, atau milik Ferguson?',{bs:13});
}
// 12 Q4 value chain
{const s=base('PERTANYAAN 4 · VALUE CHAIN','Value chain: memecah perusahaan menjadi aktivitas (Figure 4.3)',BOOK+', hlm. 104–107; Figure 4.3 hlm. 106; Illustration Capsule 4.1 hlm. 107.',
 'Value chain memecah perusahaan menjadi aktivitas-aktivitas, supaya biaya dan nilai bisa dilihat satu per satu. Di atas ada primary activities: rantai pasok, operasi, distribusi, penjualan, layanan. Di bawah ada support activities: riset, SDM, administrasi. Di ujung ada profit margin. Capsule 4.1 memberi contoh angka: sepasang jeans Everlane biaya total 19,60 dolar, dijual 88 dolar. Satu catatan penting: daftar aktivitas di gambar hanya contoh. Tiap bisnis harus menyusun aktivitasnya sendiri. Rantai pasok penting bagi Boeing, tetapi tidak ada di Goldman Sachs.');
 fit(s,'fig4_3',0.6,1.5,4.3,5.3);
 fit(s,'cap4_1',5.1,1.5,4.6,3.0);
 card(s,5.1,4.65,4.6,2.15,'Contoh angka (Capsule 4.1)','Sepasang jeans Everlane: biaya total $19,60, dijual $88, margin $68,40. Peritel biasa menjual $103. Inilah cara menghitung biaya per aktivitas.',{bs:11.5});
 card(s,9.9,1.5,2.8,5.3,'Apa isi gambar ini','Primary activities: kegiatan utama pencipta nilai, dari beli bahan sampai layanan pelanggan.\n\nSupport activities: kegiatan pendukung seperti riset, SDM, administrasi.\n\nTiga selisih: customer value proposition (nilai dikurangi harga), profit formula (harga dikurangi biaya), total economic value (nilai dikurangi biaya).\n\nDaftar ini hanya contoh. Tiap bisnis menyusun aktivitasnya sendiri.',{bs:11});
}
// 13 Q4 Figure 4.4 + benchmarking
{const s=base('PERTANYAAN 4 · VALUE CHAIN SYSTEM DAN BENCHMARKING','Melihat seluruh rantai, lalu membandingkan dengan yang terbaik',BOOK+', Figure 4.4 hlm. 109; benchmarking hlm. 109–111; Illustration Capsule 4.3 hlm. 111.',
 'Figure 4.4 mengingatkan bahwa biaya dan mutu yang sampai ke pembeli ditentukan seluruh rantai: pemasok, perusahaan, mitra hilir, sampai pengguna akhir. Lalu benchmarking: membandingkan cara perusahaan lain mengerjakan aktivitas yang sama, dan meniru yang terbaik. Contoh terkenal: Toyota meniru cara supermarket mengisi rak, Southwest meniru kru pit balap. Ada etikanya: jangan bicara biaya langsung dengan pesaing. Pakai laporan publik atau pihak ketiga.');
 fit(s,'fig4_4',0.6,1.5,7.2,3.2);
 card(s,0.6,4.85,7.2,1.95,'Apa isi gambar ini','Empat mata rantai: pemasok, perusahaan sendiri, mitra hilir (distributor, dealer), dan pembeli akhir. Kalau biaya kita kalah, perbaikannya bisa di ketiga mata rantai, bukan hanya di dalam perusahaan.');
 card(s,8.0,1.5,4.7,3.1,'Benchmarking','Membandingkan cara perusahaan lain mengerjakan aktivitas yang sama, lalu meniru cara terbaiknya. Boleh dengan pesaing, boleh dengan industri lain.\n\nContoh: Toyota meniru cara supermarket mengisi rak; Southwest meniru kru pit balap mobil untuk mempercepat pesawat berputar.',{bs:11.5});
 card(s,8.0,4.75,4.7,2.05,'Etika benchmarking (Capsule 4.3)','Jangan membicarakan biaya langsung dengan pesaing. Pakai laporan publik, asosiasi, kunjungan lapangan, atau konsultan yang menyamarkan nama perusahaan.',{bs:11.5});
}
// 14 Q4 remedies
{const s=base('PERTANYAAN 4 · TINDAKAN','Kalau biaya atau nilai kalah, ini pilihan perbaikannya',BOOK+', hlm. 112–114.',
 'Kalau value chain dan benchmarking menunjukkan kita kalah, buku memberi tiga tempat perbaikan. Di dalam perusahaan sendiri, di pemasok, dan di mitra hilir. Semua pilihan ini akan kita pakai sebagai gudang alternatif saat menyusun rekomendasi. Ada dua cara mengubah kerja value chain menjadi keunggulan: lebih murah dari pesaing, atau berbeda sehingga pelanggan mau bayar lebih.');
 card(s,0.6,1.5,3.95,4.3,'1. Di dalam perusahaan','• Tiru best practice di aktivitas yang mahal\n• Hapus aktivitas yang tidak perlu\n• Pindahkan ke wilayah berbiaya rendah\n• Serahkan ke pihak luar kalau lebih murah\n• Investasi teknologi penghemat biaya\n• Cari jalan lain menghindari biaya mahal\n• Rancang ulang produk\n• Untuk nilai: perbaiki desain, mutu, layanan, merek');
 card(s,4.7,1.5,3.95,4.3,'2. Di pemasok','• Tekan harga beli\n• Ganti bahan dengan yang lebih murah\n• Kerja sama mencari penghematan bersama\n• Produksi sendiri kalau lebih murah\n• Untuk nilai: pilih pemasok bermutu, libatkan sejak desain');
 card(s,8.8,1.5,3.9,4.3,'3. Di mitra hilir','• Tekan biaya distributor\n• Kerja sama yang menguntungkan dua pihak\n• Ubah jalur, misalnya jual langsung lewat internet\n• Buka gerai sendiri\n• Untuk nilai: iklan bersama, perjanjian eksklusif, latih mitra');
 card(s,0.6,6.0,12.1,0.85,null,'Dua cara mengubah kerja value chain menjadi keunggulan: lebih murah dari pesaing (Ryanair, Nucor), atau berbeda sehingga pelanggan mau bayar lebih (Rolex, FedEx).',{fill:NOTE,bs:12});
}
// 15 Q5 Table 4.4
{const s=base('PERTANYAAN 5 · COMPETITIVE STRENGTH ASSESSMENT','Mengubah penilaian menjadi angka (Table 4.4)',BOOK+', hlm. 115–118; Table 4.4 hlm. 116.',
 'Competitive strength assessment mengubah penilaian yang kualitatif menjadi satu angka. Lima langkah: daftar key success factor industri, beri bobot yang jumlahnya satu, beri rating satu sampai sepuluh untuk tiap pesaing, kalikan dan jumlahkan, lalu tarik kesimpulan. Table 4.4 memberi contoh: perusahaan ABC dapat 5,95, pesaing satu 7,70. Angka ini memberi tahu di mana kita harus menyerang dan di mana harus bertahan.');
 fit(s,'tab4_4',0.6,1.5,6.3,5.3);
 const st=[['Daftar key success factor','Apa saja yang menentukan sukses di industri ini? Biasanya 6 sampai 10 faktor.'],['Beri bobot','Faktor yang lebih penting dapat bobot lebih besar. Jumlah bobot harus 1,00.'],['Beri rating','Skala 1 sampai 10 untuk kita dan tiap pesaing.'],['Kalikan dan jumlahkan','Rating dikali bobot, lalu dijumlahkan per perusahaan.'],['Tarik kesimpulan','Siapa yang unggul, seberapa besar, dan di faktor mana.']];
 st.forEach((it,i)=>{const y=1.5+i*0.9;circle(s,i+1,7.2,y+0.15,0.45);s.addText([{text:it[0]+'. ',options:{bold:true,color:RED}},{text:it[1]}],{x:7.8,y:y,w:4.9,h:0.8,fontFace:BF,fontSize:12.5,color:DARK,margin:0,isTextBox:true,valign:'top'});});
 card(s,7.2,6.05,5.5,0.8,null,'Serang di faktor tempat kita kuat dan pesaing lemah. Bertahan di faktor tempat pesaing kuat dan kita lemah.',{fill:NOTE,bs:12});
}
// 16 Q6
{const s=base('PERTANYAAN 6 · PRIORITY LIST','Isu apa yang harus ditangani lebih dulu?',BOOK+', hlm. 118.',
 'Langkah terakhir dan paling penting: menyusun priority list, yaitu daftar isu yang harus dituntaskan manajemen. Isinya selalu berbentuk pertanyaan: bagaimana caranya, apa yang harus dilakukan, apakah perlu. Dua hal yang sering keliru. Pertama, daftar ini berisi isu, belum solusi. Kedua, isi daftar menunjukkan kondisi strategi: kalau isunya ringan, strategi cukup disempurnakan; kalau berat, perlu strategi baru.');
 card(s,0.6,1.5,6.0,5.3,'Priority list','Daftar isu yang harus dituntaskan manajemen supaya perusahaan lebih berhasil.\n\nIsinya selalu berbentuk pertanyaan: "bagaimana caranya…", "apa yang harus dilakukan soal…", "apakah perlu…".\n\nMenggabungkan hasil pertanyaan 1 sampai 5 dengan analisis industri dari Chapter 3.',{bs:13.5});
 card(s,6.75,1.5,6.0,2.5,'Keliru 1: mengisi daftar dengan solusi','Daftar ini berisi isu, belum jawaban. Jawabannya disusun belakangan saat memilih strategi. Karena itu kami memisahkan priority list (slide 31) dari alternatif dan simpulan (slide 33 sampai 37).',{bs:12.5});
 card(s,6.75,4.15,6.0,2.65,'Keliru 2: mengabaikan isi daftar','Kalau isunya ringan, strategi sekarang cukup disempurnakan. Kalau isunya berat, menyusun strategi baru harus jadi agenda utama. Strategi yang baik harus menjawab semua isu dalam daftar.',{bs:12.5});
}
// 17 Section B
section('BAGIAN B · STUDI KASUS','Manchester United: Preparing for Life without Ferguson','Ditulis Robert M. Grant (2010). Kasus ini berasal dari luar buku Thompson. Kami analisis dengan enam pertanyaan Chapter 4, urut dari pertanyaan 1 sampai 6.',
 'Sekarang kita masuk ke kasus. Manchester United tahun 2009. Kami pakai enam pertanyaan tadi, urut dari satu sampai enam.');
// 18 Case situation
{const s=base('KASUS · SITUASI','Juli 2009: keputusan yang dihadapi David Gill',CASE+', hlm. 573 dan 588.',
 'Juli 2009, Manchester United sedang tur Asia. David Gill, chief executive klub, memikirkan satu hal: Sir Alex Ferguson akan berusia 68 pada akhir 2009 dan diperkirakan pensiun akhir musim. Dilemanya: kalau pilih orang dalam, sistem Ferguson tetap jalan, tetapi mereka diragukan berwibawa di depan pemain bintang. Kalau pilih orang luar seperti Mourinho, kasus mengatakan hampir seluruh sistem Ferguson akan dibongkar dan dibangun ulang. Di balik dilema ini ada pertanyaan Chapter 4: aset mana yang milik klub, dan aset mana yang milik satu orang?');
 card(s,0.6,1.5,3.95,2.4,'Waktu','Juli 2009, tur pramusim ke Malaysia, Indonesia, Korea, dan China. Skuad pulang 28 Juli 2009.');
 card(s,4.7,1.5,3.95,2.4,'Pengambil keputusan','David Gill, Chief Executive Manchester United Football Club Limited.');
 card(s,8.8,1.5,3.9,2.4,'Keputusan','Menyiapkan pengganti Sir Alex Ferguson. Kasus: "at the end of 2009 Ferguson would be 68 years old". Gill memperkirakan ia pensiun akhir musim 2009–10.');
 card(s,0.6,4.1,12.1,2.7,'Dilema inti (kasus hlm. 588)','Pilih orang dalam (Queiroz, Phelan, Solskjær, McClair): sistem latihan, pemanduan bakat, dan pengembangan tim tetap jalan. Tetapi apakah mereka cukup berwibawa di depan pemain bintang?\n\nPilih orang luar berwibawa seperti Mourinho: kasus menyebut ini "a revolutionary change in coaching strategy in which much of Ferguson’s infrastructure would be taken down and rebuilt".\n\nPertanyaan Chapter 4 di baliknya: aset mana yang milik klub, dan aset mana yang milik satu orang?',{bs:13});
}
// 19 Industry context
{const s=base('KONTEKS INDUSTRI','Sepak bola Eropa: uangnya besar, labanya langka',CASE+', hlm. 577–580; Table 6.5 dan 6.6.',
 'Sebelum menilai klub, kita lihat industrinya. Premier League adalah liga terkaya di Eropa, 2,4 miliar euro. Tetapi dari sepuluh klub besar, enam merugi selama 2000 sampai 2006. Biaya terbesar adalah gaji: rata-rata 62 persen pendapatan di Premier League, Chelsea sampai 81 persen, Manchester United sekitar 50 persen. Ada tiga sumber pendapatan: tiket, hak siar, dan komersial. Dan harga pemain terus naik karena pemilik kaya seperti di Chelsea dan Manchester City.');
 big(s,'€2,4 M','Pendapatan Premier League 2007–08, terbesar di Eropa. Serie A, La Liga, dan Bundesliga masing-masing sekitar €1,4 miliar.',0.6,1.5,3.9,2.2);
 big(s,'6 dari 10','Klub besar Eropa merugi selama 2000–2006 (Table 6.6). Menurut kasus hanya MU, Arsenal, dan Bayern yang labanya berarti.',4.7,1.5,3.9,2.2);
 big(s,'62%','Gaji dibagi pendapatan di Premier League. Serie A 68%, La Liga 63%. Chelsea 81%. MU dan Arsenal sekitar 50%.',8.8,1.5,3.9,2.2);
 card(s,0.6,3.9,5.9,2.9,'Tiga sumber pendapatan klub, 2007–08','Matchday £554 juta: tiket dan hospitality, dibatasi kapasitas stadion.\nBroadcasting £931 juta, naik 43%: kontrak 2006 £2,7 miliar, rata-rata £45 juta per klub per tahun. UEFA membayar lebih dari €30 juta ke tiap klub besar Liga Champions 2008–09.\nCommercial £447 juta: sponsor dan merchandise, terpusat di sedikit klub.');
 card(s,6.7,3.9,6.0,2.9,'Aturan main dan akibatnya','Empat teratas Premier League lolos Liga Champions. Sejak 1992 jurang keuangan antara empat klub teratas dan sisanya makin lebar.\nHarga pemain naik terus, bahkan saat resesi 2009. Pendorongnya Real Madrid, lalu Chelsea, lalu Manchester City (£185 juta dalam satu musim).\nPemilik kaya: Abramovich di Chelsea, Sheikh Mansour di Manchester City. MU dan Liverpool dibeli dengan utang, jadi tidak dapat suntikan kas seperti itu.');
}
// 20 Q1 on pitch
{const s=base('PERTANYAAN 1 · DITERAPKAN','Di lapangan: jelas di atas rata-rata',CASE+', Table 6.1, 6.2; hlm. 583–584.',
 'Pertanyaan 1: apakah strategi Manchester United bekerja? Di lapangan, jawabannya jelas. Poin performa Eropa 2000 sampai 2009 tertinggi, 1.460, di atas Barcelona dan Real Madrid. Sebelas gelar liga sejak 1993, termasuk tiga beruntun. Juara Liga Champions 2008. Kasus menyebut strategi klub: mengembangkan pemain muda berbakat dan memadukannya dengan pemain senior berpengalaman.');
 big(s,'1.460','Poin performa Eropa 2000–2009, tertinggi (Table 6.2). Barcelona 1.411, Real Madrid dan Bayern 1.314, Arsenal 1.310, Chelsea 1.276.',0.6,1.5,3.9,2.4);
 big(s,'11','Gelar liga Inggris 1993–2009 (Table 6.1), termasuk tiga beruntun: 2007, 2008, 2009.',4.7,1.5,3.9,2.4);
 big(s,'2008','Juara Liga Champions. Gelar Eropa kedua era Ferguson setelah 1999.',8.8,1.5,3.9,2.4);
 s.addChart(pres.charts.BAR,[{name:'Poin Eropa 2000–09',labels:['Man United','Barcelona','Real Madrid','Bayern','Arsenal','Chelsea'],values:[1460,1411,1314,1314,1310,1276]}],{x:0.6,y:4.1,w:7.4,h:2.8,barDir:'bar',chartColors:[RED],showValue:true,dataLabelPosition:'outEnd',dataLabelFontSize:10,catAxisLabelFontSize:10,valAxisLabelFontSize:9,valAxisMinVal:1200,valAxisMaxVal:1500,showLegend:false,showTitle:true,title:'Poin performa Eropa 2000–2009 (Table 6.2)',titleFontSize:11,titleColor:DARK,valGridLine:{color:'E6E6E6',size:0.5},catGridLine:{style:'none'}});
 card(s,8.2,4.1,4.5,2.8,'Strateginya apa?','Kasus (hlm. 583): MU "emphasized the development of outstanding young talent and blending it with mature, highly experienced players". Artinya: kembangkan pemain muda sendiri, padukan dengan pemain senior.',{bs:12});
}
// 21 Q1 finance
{const s=base('PERTANYAAN 1 · DITERAPKAN','Di keuangan: paling untung di Eropa, tetapi punya utang besar',CASE+', Appendix laporan keuangan 2000–2008; Table 6.5 (Forbes 2009); Table 6.6.',
 'Di keuangan juga kuat. Pendapatan naik dari 116 juta pound tahun 2000 menjadi 257 juta tahun 2008. Net profit margin 2008 sebesar 18,2 persen. Return on sales 2000 sampai 2006 sebesar 12,6 persen, tertinggi dari sepuluh klub. EBITDA tertinggi di Eropa. Tetapi ada catatan besar: utang 616 juta pound, warisan pembelian klub oleh keluarga Glazer tahun 2005 yang dibiayai pinjaman.');
 s.addChart(pres.charts.BAR,[{name:'Pendapatan (£ juta)',labels:['2000','2001','2002','2003','2004','2005','2006','2007','2008'],values:[116.0,129.6,146.1,173.0,169.1,157.2,167.8,212.2,257.1]}],{x:0.6,y:1.5,w:7.4,h:3.4,chartColors:[RED],showValue:true,dataLabelPosition:'outEnd',dataLabelFontSize:9,catAxisLabelFontSize:10,valAxisLabelFontSize:9,showLegend:false,showTitle:true,title:'Pendapatan Manchester United, £ juta (Appendix kasus)',titleFontSize:11,titleColor:DARK,valGridLine:{color:'E6E6E6',size:0.5},catGridLine:{style:'none'}});
 para(s,'2000–2004: Manchester United plc, 12 bulan sampai 31 Juli. 2005–2008: Manchester United Limited, 11 bulan sampai 30 Juni. Kasus menyebut kedua periode tidak sepenuhnya sebanding.',0.6,4.95,7.4,0.6,10,GREY);
 const st=[['18,2%','Net profit margin 2008: laba £46,8 juta dari pendapatan £257,1 juta (Appendix).'],['12,6%','Return on sales 2000–2006 (Table 6.6), tertinggi dari 10 klub. Arsenal 5,6%, Bayern 4,7%, Real Madrid 0,4%.'],['€101,9 jt','EBITDA menurut Forbes 2009 (Table 6.5), tertinggi di Eropa. Margin 31,4%; Barcelona 22,3%; Real Madrid 14,1%.'],['£616 jt','Utang (Table 6.5), tertinggi kedua setelah Arsenal £896 juta. Berasal dari pembelian klub oleh Glazer 2005 yang dibiayai pinjaman (hlm. 579, 584).']];
 st.forEach((it,i)=>{const y=1.5+i*1.35;card(s,8.2,y,4.5,1.2,null,null);s.addText(it[0],{x:8.35,y:y+0.08,w:1.6,h:0.5,fontFace:HF,fontSize:20,bold:true,color:RED,margin:0,isTextBox:true});para(s,it[1],10.0,y+0.1,2.6,1.05,10.5);});
 card(s,0.6,5.7,7.4,1.15,null,'Ekuitas £294 juta (2008). Laba penjualan pemain £21,8 juta pada 2008. Amortisasi kontrak pemain naik dari £13,1 juta (2000) ke £35,5 juta (2008).',{fill:NOTE,bs:11.5});
}
// 22 Q1 conclusion
{const s=base('PERTANYAAN 1 · KESIMPULAN','Juara dengan belanja transfer yang hemat',CASE+', hlm. 580 dan 586; angka belanja bersih 2003–2009 dari Table 6.7 kasus.',
 'Kesimpulan pertanyaan 1. Manchester United juara, tetapi belanja transfer bersihnya hanya 100 juta pound selama 2003 sampai 2009. Real Madrid 438 juta, Chelsea 430 juta, dengan hasil lebih rendah. Kasus sendiri menyebut belanja bersih MU relatif moderat dibanding klub besar lain. Jadi strategi bekerja sangat baik. Pertanyaan berikutnya: apa penyebabnya, dan apakah penyebab itu tetap ada tanpa Ferguson?');
 s.addChart(pres.charts.BAR,[{name:'Belanja transfer bersih 2003–09 (£ juta)',labels:['Real Madrid','Chelsea','Barcelona','Liverpool','Bayern','Man United','Arsenal'],values:[438,430,249,157,122,100,22]}],{x:0.6,y:1.5,w:7.0,h:5.2,barDir:'bar',chartColors:[RED],showValue:true,dataLabelPosition:'outEnd',dataLabelFontSize:10,catAxisLabelFontSize:10,valAxisLabelFontSize:9,showLegend:false,showTitle:true,title:'Belanja transfer bersih 2003–2009, £ juta (Table 6.7)',titleFontSize:11,titleColor:DARK,valGridLine:{color:'E6E6E6',size:0.5},catGridLine:{style:'none'}});
 card(s,7.8,1.5,4.9,2.4,'Apa kata kasus','"Manchester United’s net expenditure on player transfers has been relatively modest compared to other leading European clubs" (hlm. 586). Real Madrid dan Chelsea "were distinguished by their massive expenditures on star players" (hlm. 580).',{bs:12});
 card(s,7.8,4.05,4.9,2.75,'Jawaban pertanyaan 1','Strategi MU bekerja sangat baik. Juara di lapangan, untung di keuangan, di industri yang kebanyakan pelakunya merugi. Real Madrid belanja sekitar 4,4 kali lipat MU, tetapi poin Eropanya lebih rendah.\n\nPertanyaan berikutnya: apa penyebabnya, dan apakah penyebab itu tetap ada tanpa Ferguson?',{bs:12});
}
// 23 SWOT MU
{const s=base('PERTANYAAN 2 · DITERAPKAN','SWOT Manchester United, Juli 2009',CASE+', hlm. 573, 579, 584–587; Table 6.3, 6.5, 6.6.',
 'SWOT Manchester United. Kekuatan: merek global dengan 80 juta pendukung di Asia, laba tertinggi di Eropa, akademi dan pemandu bakat, disiplin menjual pemain di harga puncak. Kelemahan: utang 616 juta pound, sistem bergantung pada Ferguson, belum ada pengganti, dan dewan hanya berisi enam anak Glazer. Peluang: Asia terutama India dan China, sponsor per negara, hak siar naik. Ancaman: harga pemain meledak, pemilik kaya di klub lain, dan Ronaldo baru saja dijual. Kesimpulannya: kekuatan cukup untuk peluang komersial, tetapi tidak cukup menutup ketergantungan pada Ferguson, karena kekuatan itu sendiri hasil kerjanya.');
 const q=[['S','Strengths','• Merek global: 80 juta pendukung di Asia; 1,2 juta pemegang kartu kredit MU di Korea Selatan\n• Laba tertinggi di Eropa: EBITDA €101,9 juta; return on sales 12,6%\n• Akademi dan lebih dari 20 pemandu bakat\n• Disiplin transfer: menjual di harga puncak (Ronaldo £80 juta)'],['W','Weaknesses','• Utang £616 juta dari pembelian klub oleh Glazer 2005\n• Sistem olahraga bergantung pada Ferguson, 68 tahun pada akhir 2009\n• Belum ada pengganti; Ferguson belum mengumumkan pensiun\n• Dewan hanya berisi enam anak Glazer (hlm. 584)'],['O','Opportunities','• Aon: "Asia, particularly India and China, are prime targets"\n• Sponsor per negara bisa ditambah (contoh: Tri Indonesia, Bharti Airtel)\n• Hak siar Premier League naik 43% dalam setahun\n• Kanal sendiri: MUTV, MU Mobile, toko daring'],['T','Threats','• Harga pemain meledak; Manchester City belanja £185 juta\n• Pemilik sangat kaya di Chelsea dan Manchester City\n• Beban bunga membatasi daya beli\n• Ronaldo, satu-satunya pemain MU di peringkat FIFA (Table 6.3), sudah dijual']];
 q.forEach((it,i)=>{const col=i%2,row=Math.floor(i/2);const x=0.6+col*6.15,y=1.5+row*2.35;card(s,x,y,6.0,2.2,null,null);s.addText(it[0],{x:x+0.15,y:y+0.1,w:0.6,h:0.6,fontFace:HF,fontSize:26,bold:true,color:RED,margin:0,isTextBox:true});s.addText(it[1],{x:x+0.75,y:y+0.22,w:2,h:0.4,fontFace:BF,fontSize:13,bold:true,color:DARK,margin:0,isTextBox:true});para(s,it[2],x+0.15,y+0.7,5.7,1.5,10.5);});
 card(s,0.6,6.25,12.15,0.6,null,'Kesimpulan (langkah 2 Figure 4.2): kekuatan cukup untuk menangkap peluang di Asia, tetapi tidak cukup menutup ketergantungan pada Ferguson, karena kekuatan itu sendiri sebagian besar hasil kerjanya.',{fill:NOTE,bs:11.5});
}
// 24 Resources MU
{const s=base('PERTANYAAN 3 · DITERAPKAN','Daftar resource Manchester United (tipologi Table 4.3)',CASE+', hlm. 573, 584–587; Appendix.',
 'Sekarang daftar resource klub dengan tipologi Table 4.3. Tangible: uang, stadion Old Trafford, struktur organisasi yang memisahkan urusan tim dan komersial, dan kontrak-kontrak. Intangible: merek dan sub-mereknya, 80 juta pendukung di Asia, Ferguson dan jaringan pemandu bakat, serta reputasi yang membuat Aon membayar mahal. Perhatikan: aset paling berharga hampir semua intangible, dan sebagian melekat pada orang yang bisa pergi.');
 card(s,0.6,1.5,6.0,5.3,'Tangible (berwujud)','Keuangan: EBITDA €101,9 juta; laba bersih £46,8 juta; ekuitas £294 juta; kas £80 juta dari penjualan Ronaldo.\n\nFisik: Old Trafford, ditambah 7.500 kursi pada 2006; museum, tur stadion, ruang yang disewakan.\n\nOrganisasi: urusan tim (Ferguson) dipisah dari urusan komersial (Gill, Arnold); anak usaha Manchester United International sejak 1998.\n\nKontrak: kontrak pemain; sponsor (Nike, Aon mulai 2010, Budweiser, Audi, Hublot, dan lainnya).',{bs:12.5});
 card(s,6.75,1.5,6.0,5.3,'Intangible (tak berwujud)','Merek: "We’re not just a sports club, we are an international brand" (Andy Anson). Sub-merek Fred the Red, MUFC, Red Devil.\n\nPendukung: 80 juta di Asia; 1,2 juta pemegang kartu kredit MU di Korea Selatan.\n\nOrang: Ferguson sejak 1986; lebih dari 20 pemandu bakat; dua pemandu tetap di Brasil sejak 2008.\n\nReputasi: Aon menyebut MU "has no equal in sports when it comes to global brand awareness". AIG naik ke peringkat 47 merek dunia dalam setahun.\n\nCatatan: aset paling berharga hampir semua tak berwujud, dan sebagian melekat pada orang yang bisa pergi.',{bs:12.5});
}
// 25 Capabilities MU
{const s=base('PERTANYAAN 3 · DITERAPKAN','Capability MU: core, distinctive, atau biasa',CASE+', hlm. 584–587.',
 'Dari resource ke capability. Tiga core competence: mengenali dan mengembangkan bakat, membentuk tim bukan kumpulan bintang, dan mengubah merek jadi uang. Dua distinctive competence: disiplin di pasar transfer, dan rotasi skuad. Satu competence biasa: tata kelola. Yang penting: empat dari enam kemampuan ini bergantung pada orang yang sama, Ferguson. Hanya kemampuan komersial yang tidak.');
 const c=[['CORE COMPETENCE','Mengenali dan mengembangkan bakat','Pemandu bakat dari 5 jadi lebih dari 20. Youth Academy disebut "the finest youth coaching program in the country". Generasi 1992: Giggs, Beckham, Scholes, Neville.'],['CORE COMPETENCE','Membentuk tim, bukan kumpulan bintang','"The best teams stand out because they are teams". Prinsip: tidak ada pemain yang lebih besar dari klub.'],['CORE COMPETENCE','Mengubah merek jadi uang','Sponsor per negara, sub-merek per usia, MU Finance, MU Mobile, MUTV, Soccer Schools, tur Asia.'],['DISTINCTIVE COMPETENCE','Disiplin di pasar transfer','Menjual di harga puncak: Beckham, Verón, van Nistelrooy, Ronaldo (£80 juta). Belanja bersih hemat.'],['DISTINCTIVE COMPETENCE','Rotasi skuad','Kasus menyebut Ferguson "a pioneering exponent of squad rotation".'],['COMPETENCE','Tata kelola dan pembagian peran','Glazer memilih peran pasif; Ferguson dan Gill diberi kebebasan. Berjalan baik, tetapi bukan pembeda dari pesaing.']];
 c.forEach((it,i)=>{const col=i%3,row=Math.floor(i/3);const x=0.6+col*4.1,y=1.5+row*2.45;card(s,x,y,3.9,2.3,null,null);s.addText(it[0],{x:x+0.15,y:y+0.1,w:3.6,h:0.3,fontFace:BF,fontSize:9.5,bold:true,color:it[0].startsWith('CORE')?RED:(it[0].startsWith('DIST')?GOLD:GREY),charSpacing:1,margin:0,isTextBox:true});s.addText(it[1],{x:x+0.15,y:y+0.4,w:3.6,h:0.55,fontFace:BF,fontSize:13,bold:true,color:DARK,margin:0,isTextBox:true,valign:'top'});para(s,it[2],x+0.15,y+1.0,3.6,1.25,10.5);});
 para(s,'Empat dari enam kemampuan (bakat, membentuk tim, disiplin transfer, rotasi) bergantung pada orang yang sama. Hanya kemampuan komersial yang tidak bergantung pada Ferguson.',0.6,6.45,12.1,0.45,12,RED,true);
}
// 26 VRIN MU
{const s=base('PERTANYAAN 3 · VRIN TEST','Dua keunggulan diuji: lolos, tetapi risikonya berbeda',CASE+', hlm. 582–583, 586; Table 6.8. Definisi tes: '+BOOK+', hlm. 101–102. Istilah transferability dari buku teks Grant, Contemporary Strategy Analysis.',
 'Kami uji dua hal dengan VRIN test: sistem Ferguson dan merek. Keduanya lolos empat tes. Yang menarik ada di tes N untuk sistem Ferguson. Real Madrid dan Chelsea sudah mencoba menggantinya dengan uang, membeli bintang, dan kasus bilang hasilnya gagal. Jadi tidak ada penggantinya, artinya lolos. Lalu di mana risikonya? Bukan di substitusi, tetapi di transferability: sistem itu melekat pada satu orang. Klub memperlakukannya seperti resource yang dimiliki, padahal harus jadi capability milik klub.');
 const rows=[[{text:'Tes',options:{bold:true,color:WHITE,fill:{color:RED}}},{text:'Sistem Ferguson (resource bundle)',options:{bold:true,color:WHITE,fill:{color:RED}}},{text:'Merek dan mesin komersial',options:{bold:true,color:WHITE,fill:{color:RED}}}],
 [{text:'Valuable',options:{bold:true}},'LOLOS. Poin Eropa tertinggi, tiga gelar beruntun, Liga Champions 2008, laba tertinggi di Eropa.','LOLOS. Aon £80 juta per 4 tahun (£20 juta per tahun), tertinggi di antara klub Inggris yang disebut kasus. Arsenal–Emirates £100 juta per 15 tahun; Chelsea–Samsung £50 juta per 5 tahun.'],
 [{text:'Rare',options:{bold:true}},'LOLOS. Table 6.8 hanya memuat sedikit pelatih paling dihormati dunia; Ferguson yang paling lama di satu klub.','LOLOS. 80 juta pendukung di Asia. Kasus: hanya Real Madrid yang setara dalam memanfaatkan merek global.'],
 [{text:'Inimitable',options:{bold:true}},'LOLOS. Kasus: penentu performa tim "remained a mystery … defies analysis". Dibangun 23 tahun; rumit secara sosial.','LOLOS. Dibangun puluhan tahun lewat prestasi dan siaran. Chelsea dan Manchester City dengan uang lebih banyak belum menyamainya.'],
 [{text:'Nonsubstitutable',options:{bold:true}},'LOLOS. Pesaing mencoba mengganti sistem dengan uang: "Real Madrid and Chelsea’s lavishing of vast sums of money … has yielded teams that have failed to achieve greatness" (hlm. 583).','LOLOS. Tidak ada pengganti bagi loyalitas pendukung. Sponsor membeli akses ke pendukung, bukan ke stadion atau pemain tertentu.']];
 s.addTable(rows,{x:0.6,y:1.5,w:12.1,colW:[1.8,5.15,5.15],fontFace:BF,fontSize:10.5,color:DARK,border:{type:'solid',pt:0.5,color:'D9C6C8'},valign:'top'});
 card(s,0.6,5.75,12.1,1.1,'Kesimpulan pertanyaan 3','Sistem Ferguson lolos empat tes, jadi ia keunggulan yang bertahan terhadap pesaing. Risikonya bukan substitusi, tetapi transferability: sistem itu melekat pada satu orang. Klub memperlakukannya seperti resource yang dimiliki, padahal harus menjadi capability milik klub.',{bs:11.5,fill:NOTE});
}
// 27 Dynamic capability MU
{const s=base('PERTANYAAN 3 · DYNAMIC CAPABILITY','Tiga kali membangun ulang tim juara',CASE+', hlm. 583–584.',
 'Manchester United punya dynamic capability: tiga kali membongkar dan menyusun ulang skuad, dan tetap juara. 1986 sampai 1993 membangun fondasi. 1994 sampai 2003 generasi akademi, puncaknya 1999. 2003 sampai 2008 regenerasi kedua, puncaknya Liga Champions 2008. Pertanyaan besarnya: kemampuan ini milik klub atau milik Ferguson? Sejarah memberi peringatan: setelah Busby pensiun 1969, klub tidak juara liga 18 tahun sampai Ferguson datang.');
 const t=[['1986–1993','Membangun fondasi','Ferguson menyingkirkan pemain yang kurang berbakat atau kurang berkomitmen, mempertahankan Bryan Robson, mendatangkan Hughes, Ince, Cantona, Keane. Disiplin latihan ditegakkan, alkohol dilarang.','FA Cup 1990 · Cup Winners’ Cup 1991 · gelar liga 1993'],['1994–2003','Generasi akademi','Juara liga junior 1990 menghasilkan Giggs, Beckham, Butt, Gary dan Phil Neville, Scholes. Mereka menjadi inti tim yang menguasai Inggris.','Puncak 1999: liga, FA Cup, European Cup, Intercontinental Cup'],['2003–2008','Regenerasi kedua','Beckham, Keane, Schmeichel, Cole, Sheringham, Stam dijual. Pengganti: Ferdinand, Ronaldo, Rooney, van der Sar, Evra, Vidić, Carrick.','Liga Champions 2008 · tiga gelar liga beruntun 2007–2009']];
 t.forEach((it,i)=>{const x=0.6+i*4.1;card(s,x,1.5,3.9,4.4,null,null);s.addText(it[0],{x:x+0.15,y:1.6,w:3.6,h:0.5,fontFace:HF,fontSize:20,bold:true,color:RED,margin:0,isTextBox:true});s.addText(it[1],{x:x+0.15,y:2.15,w:3.6,h:0.5,fontFace:BF,fontSize:13,bold:true,color:DARK,margin:0,isTextBox:true});para(s,it[2],x+0.15,2.7,3.6,2.1,11);para(s,it[3],x+0.15,4.9,3.6,0.9,10.5,RED,true);});
 card(s,0.6,6.05,12.1,0.8,null,'Pertanyaan utama kasus: kemampuan memperbarui diri ini milik Ferguson atau milik klub? Setelah Matt Busby pensiun 1969, MU tidak juara liga selama 18 tahun sampai Ferguson datang (hlm. 583).',{fill:NOTE,bs:12});
}
// 28 Value chain MU
{const s=base('PERTANYAAN 4 · VALUE CHAIN DITERAPKAN','Value chain klub sepak bola: keunggulan biaya MU ada di hulu',CASE+', hlm. 578, 585–587; Appendix. Aktivitas disusun ulang sesuai anjuran buku hlm. 105.',
 'Value chain klub sepak bola kami susun sendiri, sesuai anjuran buku. Lima aktivitas utama: mendapatkan pemain, latihan dan bertanding, menyalurkan tontonan, menjual merek, melayani pendukung. Keunggulan biaya MU ada di aktivitas pertama. Akademi memasok pemain tanpa biaya transfer, dan klub menjual pemain di harga puncak. Hasilnya gaji hanya 50 persen pendapatan, dibanding Chelsea 81 persen. Nilainya berbeda untuk dua pihak: pendukung membeli prestasi dan pengalaman, sponsor membeli akses ke 80 juta pendukung Asia.');
 const acts=[['Mendapatkan pemain','Akademi, 20+ pemandu bakat, pasar transfer'],['Latihan dan bertanding','Disiplin latihan, rotasi skuad, kontrol lini tengah'],['Menyalurkan tontonan','Hak siar liga dan UEFA, MUTV, Old Trafford'],['Menjual merek','Aon, Nike, sponsor per negara, tur Asia'],['Melayani pendukung','Superstore, museum, Soccer Schools, MU Mobile']];
 acts.forEach((it,i)=>{const x=0.6+i*2.45;card(s,x,1.5,2.35,1.75,null,null,{fill:i===0?'F2DADD':TINT});circle(s,i+1,x+0.15,1.62,0.4);s.addText(it[0],{x:x+0.65,y:1.58,w:1.6,h:0.55,fontFace:BF,fontSize:11,bold:true,color:DARK,margin:0,isTextBox:true,valign:'top'});para(s,it[1],x+0.15,2.2,2.05,1.0,9.5,GREY);});
 para(s,'Aktivitas pendukung: metode akademi dan rotasi skuad (riset); rekrutmen, struktur gaji, disiplin (SDM); pembagian peran Gill dan Ferguson, MU International (administrasi).',0.6,3.35,12.1,0.5,11,GREY);
 card(s,0.6,3.9,5.9,2.9,'Di mana keunggulan biayanya','Gaji sekitar 50% pendapatan. Rata-rata Premier League 62%, Serie A 68%, Chelsea 81% (hlm. 578).\nAkademi memasok pemain tanpa biaya transfer; belanja bersih hemat.\nMenjual di harga puncak: Ronaldo £80 juta (rekor dunia); laba penjualan pemain £21,8 juta pada 2008.\nCatatan: amortisasi pemain naik dari £13,1 juta (2000) ke £35,5 juta (2008).',{bs:12});
 card(s,6.7,3.9,6.0,2.9,'Nilai bagi dua pihak yang berbeda','Bagi pendukung: prestasi, sejarah, dan pengalaman Old Trafford.\nBagi sponsor: akses ke 80 juta pendukung Asia. Buktinya AIG "came from nowhere on the list of the world’s top 100 brands to 47th" dalam setahun (hlm. 573).\n\nKeunggulan biaya di pertandingan berasal dari aktivitas hulu, sama seperti keunggulan biaya AirAsia di penerbangan berasal dari pemakaian pesawat yang tinggi.',{bs:12});
}
// 29 Benchmarking MU
{const s=base('PERTANYAAN 4 · BENCHMARKING DITERAPKAN','Yang harus dibandingkan bukan pendapatan, tetapi margin',CASE+', Table 6.5 (Forbes 2009) dan Table 6.6; margin dihitung dari EBITDA dibagi pendapatan.',
 'Benchmarking dengan klub lain. Kalau dilihat pendapatan, Real Madrid lebih besar. Tetapi kalau dilihat margin EBITDA, Manchester United 31 persen, Real Madrid hanya 14 persen, Chelsea negatif. Ada tiga cara klub mendapat pemain: membeli bintang seperti Real Madrid dan Chelsea, mengembangkan sendiri seperti Barcelona dan Arsenal, atau gabungan seperti MU. Return on sales di Table 6.6 membuktikan mana yang paling untung. Benchmarking mengubah dugaan VRIN menjadi bukti.');
 s.addChart(pres.charts.BAR,[{name:'Margin EBITDA (%)',labels:['Man United','Barcelona','Arsenal','AC Milan','Juventus','Liverpool','Real Madrid','Bayern','Inter','Chelsea'],values:[31.4,22.3,19.3,17.6,17.5,15.8,14.1,12.7,9.9,-3.1]}],{x:0.6,y:1.5,w:7.2,h:5.3,barDir:'bar',chartColors:[RED],showValue:true,dataLabelPosition:'outEnd',dataLabelFontSize:9.5,catAxisLabelFontSize:10,valAxisLabelFontSize:9,showLegend:false,showTitle:true,title:'Margin EBITDA klub Eropa, % (dihitung dari Table 6.5)',titleFontSize:11,titleColor:DARK,catAxisLabelPos:'low',valAxisMinVal:-5,valAxisMaxVal:35,valGridLine:{color:'E6E6E6',size:0.5},catGridLine:{style:'none'}});
 card(s,8.0,1.5,4.7,2.6,'Tiga cara mendapat pemain','Membeli bintang: Real Madrid, Chelsea. Pendapatan tinggi, laba rendah atau rugi.\nMengembangkan sendiri: Barcelona, Arsenal, Bayern. Laba positif dengan pendapatan lebih rendah.\nGabungan: MU membeli bintang, lalu menjual saat klub lain menilai lebih tinggi (hlm. 580, 583).',{bs:11.5});
 card(s,8.0,4.25,4.7,2.55,'Bukti mana yang paling untung','Return on sales 2000–2006 (Table 6.6): MU 12,6%, Arsenal 5,6%, Bayern 4,7%, Real Madrid 0,4%, Chelsea −60,4%, Inter −78,4%.\n\nBenchmarking mengubah dugaan VRIN menjadi bukti: sistem pengembangan dan penjualan pemain memang lebih unggul.',{bs:11.5});
}
// 30 Competitive strength assessment MU
{const s=base('PERTANYAAN 5 · COMPETITIVE STRENGTH ASSESSMENT','Unggul tipis, dan bertumpu pada satu baris','Bobot dan rating disusun kelompok dari Table 6.2, 6.3, 6.5, 6.6, 6.7 kasus. Isi sel: rating (1–10) / skor tertimbang. Jumlah bobot 1,00.',
 'Competitive strength assessment. Sembilan key success factor dengan bobot total satu. Hasilnya MU 8,65, Barcelona 8,40, Real Madrid 7,15, Arsenal 6,55, Chelsea 5,55. MU unggul, tetapi hanya 0,25 poin, dan itu bertumpu pada baris kemampuan manajer. Kalau rating manajer turun dari 10 ke 5 karena ganti pelatih, skor MU jadi 7,90, di bawah Barcelona. Pengganti Ferguson harus dapat rating minimal 8,3 supaya MU sejajar Barcelona. Ini uji skenario yang diminta silabus.');
 const H=(t)=>({text:t,options:{bold:true,color:WHITE,fill:{color:RED},align:'center'}});
 const rows=[[H('Key success factor'),H('Bobot'),H('Man United'),H('Real Madrid'),H('Barcelona'),H('Chelsea'),H('Arsenal')],
 ['Kualitas skuad','0,15','6 / 0,90','9 / 1,35','10 / 1,50','9 / 1,35','6 / 0,90'],
 ['Kemampuan manajer','0,15','10 / 1,50','5 / 0,75','8 / 1,20','6 / 0,90','8 / 1,20'],
 ['Akademi dan pemandu bakat','0,10','9 / 0,90','3 / 0,30','9 / 0,90','3 / 0,30','8 / 0,80'],
 ['Merek dan basis pendukung','0,15','10 / 1,50','9 / 1,35','7 / 1,05','5 / 0,75','6 / 0,90'],
 ['Kemampuan komersial','0,10','10 / 1,00','9 / 0,90','7 / 0,70','5 / 0,50','6 / 0,60'],
 ['Profitabilitas','0,10','10 / 1,00','5 / 0,50','7 / 0,70','1 / 0,10','6 / 0,60'],
 ['Keleluasaan keuangan (utang)','0,10','4 / 0,40','7 / 0,70','9 / 0,90','5 / 0,50','2 / 0,20'],
 ['Stadion dan matchday','0,05','9 / 0,45','8 / 0,40','9 / 0,45','5 / 0,25','9 / 0,45'],
 ['Rekam jejak prestasi','0,10','10 / 1,00','9 / 0,90','10 / 1,00','9 / 0,90','9 / 0,90'],
 [{text:'Total skor tertimbang',options:{bold:true}},{text:'1,00',options:{bold:true}},{text:'8,65',options:{bold:true,color:RED}},{text:'7,15',options:{bold:true}},{text:'8,40',options:{bold:true}},{text:'5,55',options:{bold:true}},{text:'6,55',options:{bold:true}}]];
 s.addTable(rows,{x:0.6,y:1.45,w:8.3,colW:[2.6,0.8,1.0,1.0,0.95,0.95,1.0],fontFace:BF,fontSize:10,color:DARK,border:{type:'solid',pt:0.5,color:'D9C6C8'},rowH:0.42,valign:'middle',align:'center'});
 const st=[['+0,25','MU 8,65 vs Barcelona 8,40. Selisihnya tipis dan bertumpu pada baris kemampuan manajer.'],['7,90','Skor MU kalau rating manajer turun dari 10 ke 5 karena ganti pelatih. Di bawah Barcelona.'],['≥ 8,3','Rating minimal pengganti Ferguson supaya MU sejajar Barcelona (8,65 − 1,50 + 0,15x ≥ 8,40).']];
 st.forEach((it,i)=>{const y=1.45+i*1.8;card(s,9.1,y,3.6,1.65,null,null);s.addText(it[0],{x:9.25,y:y+0.08,w:3.3,h:0.55,fontFace:HF,fontSize:22,bold:true,color:RED,margin:0,isTextBox:true});para(s,it[1],9.25,y+0.65,3.3,0.95,10.5);});
 para(s,'Ini uji skenario ("risk/scenario logic") yang diminta silabus. Baris terlemah MU: keleluasaan keuangan. Keunggulan MU bergantung pada keberhasilan mengganti Ferguson.',0.6,6.4,8.3,0.5,11,GREY);
}
// 31 Priority list MU
{const s=base('PERTANYAAN 6 · PRIORITY LIST DITERAPKAN','Enam isu untuk David Gill, ditulis sebagai pertanyaan','Rumusan mengikuti buku hlm. 118. Bukti dari '+CASE+'.',
 'Priority list untuk David Gill, enam isu berbentuk pertanyaan. Satu, bagaimana mengganti Ferguson tanpa merusak sistemnya. Dua, apa yang harus dilakukan soal utang. Tiga, bagaimana menambal skuad setelah Ronaldo pergi. Empat, apakah perlu membangun penyangga organisasi. Lima, bagaimana menjaga pendapatan kalau prestasi turun. Enam, apakah tata kelola aman tanpa Ferguson dan Gill. Isu satu dan empat serius dan butuh strategi baru. Sisanya bisa ditangani dengan menyempurnakan strategi yang ada.');
 const p=[['Bagaimana mengganti Ferguson tanpa merusak sistemnya?','Gill belum memutuskan; Ferguson belum mengumumkan pensiun (hlm. 573, 588).'],['Apa yang harus dilakukan soal utang £616 juta?','Utang membatasi daya beli, justru saat Manchester City belanja £185 juta (hlm. 579).'],['Bagaimana menambal skuad setelah Ronaldo pergi?','Tidak ada lagi pemain MU di peringkat FIFA Table 6.3. Media menunggu apakah kas Ronaldo dipakai membeli Ribery (hlm. 588).'],['Apakah perlu membangun penyangga organisasi?','Kasus: seluruh sistem pemanduan, latihan, dan taktik dibangun oleh satu orang (hlm. 573).'],['Bagaimana menjaga pendapatan komersial kalau prestasi turun?','Gill: "So long as the team kept winning games … the commercial revenues … would continue to flow" (hlm. 573).'],['Apakah tata kelola tetap aman tanpa Ferguson dan Gill?','Dewan hanya berisi enam anak Glazer; peran pasif pemilik berjalan karena dua orang ini diberi kebebasan (hlm. 584).']];
 p.forEach((it,i)=>{const col=i%2,row=Math.floor(i/2);const x=0.6+col*6.15,y=1.5+row*1.75;card(s,x,y,6.0,1.6,null,null);circle(s,i+1,x+0.15,y+0.15,0.45);s.addText(it[0],{x:x+0.75,y:y+0.1,w:5.1,h:0.6,fontFace:BF,fontSize:12.5,bold:true,color:DARK,margin:0,isTextBox:true,valign:'top'});para(s,it[1],x+0.75,y+0.75,5.1,0.8,10.5,GREY);});
 para(s,'Isu 1 dan 4 serius dan butuh strategi baru. Isu 2, 3, 5, 6 bisa ditangani dengan menyempurnakan strategi yang ada.',0.6,6.8,12.1,0.3,11,RED,true);
}
// 32 Section C
section('BAGIAN C · KEPUTUSAN','Dari priority list ke keputusan','Mengikuti Appendix 3 silabus: masalah (tujuan dan penghalang), alternatif berjudul tanpa pro-kontra, isu sebagai pertanyaan, simpulan yang ditarik dari isu dengan angka, lalu rencana implementasi.',
 'Bagian terakhir: keputusan. Kami ikuti pola analisis kasus dari silabus. Masalah dulu, lalu alternatif, lalu isu, lalu simpulan, lalu rencana pelaksanaan.');
// 33 Problem
{const s=base('LANGKAH 1 · MASALAH','Tujuan yang ingin dicapai dan penghalangnya','Appendix 3 silabus: "The key words here are goals and barrier." Bukti dari '+CASE+'.',
 'Masalah dirumuskan sebagai tujuan dan penghalang. Tiga tujuan: tetap di empat besar supaya uang Liga Champions dan sponsor terjaga, tetap untung dengan gaji sekitar 50 persen pendapatan, dan mempertahankan sistem yang lolos VRIN. Tiga penghalang: Ferguson 68 tahun dan sistem berpusat padanya, utang 616 juta pound, dan harga pemain yang meledak. Inti masalahnya: bagaimana memindahkan kemampuan yang melekat pada satu orang menjadi kemampuan milik klub, sebelum orang itu pergi.');
 card(s,0.6,1.5,5.9,4.6,'Tiga tujuan','1. Tetap di empat besar Premier League setiap musim, supaya pendapatan Liga Champions (lebih dari €30 juta dari UEFA per musim) dan daya tarik sponsor terjaga.\n\n2. Tetap untung: gaji sekitar 50% pendapatan, margin EBITDA 31,4%.\n\n3. Mempertahankan sistem pengembangan bakat dan pembentukan tim yang lolos VRIN test.',{bs:12.5});
 card(s,6.7,1.5,6.0,4.6,'Tiga penghalang','1. Ferguson berusia 68 pada akhir 2009, dan sistem berpusat padanya. Kasus: penentu performa tim "defies analysis", jadi sulit diwariskan.\n\n2. Utang £616 juta membatasi ruang untuk menutup kesalahan dengan belanja. MU "had not received the influx of cash" seperti Chelsea dan Manchester City.\n\n3. Harga pemain meledak karena pemilik kaya. Kalau sistem internal gagal, menggantinya dengan membeli pemain akan sangat mahal.',{bs:12.5});
 card(s,0.6,6.25,12.1,0.6,null,'Inti masalah: bagaimana memindahkan kemampuan yang melekat pada satu orang menjadi kemampuan milik klub, sebelum orang itu pergi.',{fill:NOTE,bs:12});
}
// 34 Alternatives
{const s=base('LANGKAH 2 · ALTERNATIF','Tiga alternatif berjudul, tanpa pro dan kontra','Appendix 3 silabus: "Strategies may be usefully given titles … Arguments pro or con … should NOT be included" pada tahap ini. Kandidat dari '+CASE+', hlm. 588.',
 'Tiga alternatif. A, Kesinambungan Internal: angkat asisten Ferguson, sistem dipertahankan apa adanya. B, Pemimpin Terbukti dari Luar: angkat manajer berwibawa seperti Mourinho dan terima bahwa sistem akan dibangun ulang. C, Pelembagaan Sistem sebelum Suksesi: pecah sistem Ferguson menjadi beberapa jabatan yang dipegang orang berbeda, lalu angkat manajer yang bekerja di dalam struktur itu. Sesuai silabus, di tahap ini belum ada pro dan kontra.');
 const a=[['A','Kesinambungan Internal','Mengangkat salah satu asisten Ferguson (Queiroz, Phelan, Solskjær, atau McClair) sebagai manajer dengan tugas mempertahankan sistem pemanduan bakat, akademi, dan rotasi skuad apa adanya. Ferguson mendampingi sebagai mentor pada musim pertama.'],['B','Pemimpin Terbukti dari Luar','Mengangkat manajer berwibawa dengan rekam jejak, misalnya Mourinho, dan menerima bahwa sistem kepelatihan akan dibongkar dan dibangun ulang menurut caranya. Belanja pemain didukung kas Ronaldo £80 juta.'],['C','Pelembagaan Sistem sebelum Suksesi','Memecah sistem Ferguson menjadi beberapa jabatan yang dipegang orang berbeda: direktur pemanduan bakat, direktur akademi, direktur sepak bola yang menetapkan filosofi permainan dan kebijakan transfer. Lalu mengangkat manajer tim, dari dalam atau luar, yang bekerja di dalam struktur itu dengan batas gaji 50% pendapatan.']];
 a.forEach((it,i)=>{const x=0.6+i*4.1;card(s,x,1.5,3.9,5.3,null,null);s.addText(it[0],{x:x+0.15,y:1.6,w:0.8,h:0.8,fontFace:HF,fontSize:40,bold:true,color:RED,margin:0,isTextBox:true});s.addText(it[1],{x:x+0.95,y:1.75,w:2.8,h:0.9,fontFace:BF,fontSize:15,bold:true,color:DARK,margin:0,isTextBox:true,valign:'top'});para(s,it[2],x+0.15,2.7,3.6,4.0,12);});
}
// 35 Issues
{const s=base('LANGKAH 3 · ISU','Tiga isu sebagai pertanyaan, dijawab dari analisis Bagian B','Appendix 3 silabus: "Issues may be usefully conceived as explicit questions." Bukti dari '+CASE+'.',
 'Tiga isu berbentuk pertanyaan. Satu, apakah sistem Ferguson bisa dipisahkan dari Ferguson? VRIN test bilang sistem itu resource bundle dengan bagian yang bisa dikenali, jadi sebagian besar bisa dilembagakan. Dua, apakah orang dalam cukup berwibawa? Kasus sendiri ragu. Tiga, apakah keuangan sanggup menanggung perombakan total? Benchmarking bilang tidak: model membeli pemain menghasilkan rugi di Real Madrid dan Chelsea. Jadi B gugur, A lemah, C didukung.');
 const is=[['Apakah sistem Ferguson bisa dipisahkan dari Ferguson?','VRIN test (slide 26): sistem itu resource bundle dengan bagian yang bisa dikenali: pemandu bakat, akademi, disiplin latihan, filosofi permainan, kebijakan transfer. Sebagian besar bisa dilembagakan. Kemampuan mengendalikan bintang mungkin tidak.','Mendukung C; membatasi A.'],['Apakah orang dalam cukup berwibawa di depan bintang?','Kasus ragu: apakah asisten "could have the presence and strength of personality needed to exert leadership and authority over Manchester United’s high profile soccer stars" (hlm. 588). Prinsip tidak ada pemain lebih besar dari klub butuh wibawa itu.','Melemahkan A.'],['Apakah keuangan sanggup menanggung perombakan total?','Benchmarking (slide 29): model membeli pemain menghasilkan return on sales 0,4% di Real Madrid dan −60,4% di Chelsea. Dengan utang £616 juta dan tanpa suntikan kas pemilik, MU tidak bisa meniru model itu.','Menggugurkan B.']];
 is.forEach((it,i)=>{const y=1.5+i*1.75;circle(s,i+1,0.6,y+0.1,0.5);card(s,1.25,y,7.6,1.6,it[0],it[1],{bs:10.5});card(s,9.0,y,3.7,1.6,'Akibatnya',it[2],{bs:12});});
}
// 36 Counter-argument
{const s=base('ARGUMEN TANDINGAN','Membela alternatif B sekuat mungkin, lalu mengujinya','Rubrik nilai A silabus: "conflicting arguments, perspectives or problem-solving approaches". Bukti dari '+CASE+', hlm. 582–583, 588; Table 6.6, 6.8.',
 'Supaya adil, kami bela dulu alternatif B sekuat mungkin. Kasus sendiri bilang pelatih adalah orang yang paling menentukan sukses tim. Mourinho sukses di tiga klub berbeda. Setelah Busby pensiun, orang dalam gagal 18 tahun, dan yang menyelamatkan adalah orang luar, Ferguson. Uang 80 juta pound tersedia. Lalu kenapa tidak cukup? Kasus juga bilang pelatih sukses di satu tim sering gagal di tim lain. Ferguson sendiri butuh tujuh tahun membangun sistem sebelum juara liga. Real Madrid yang bergonta-ganti pelatih ternama hanya untung 0,4 persen. Dan 80 juta pound hanya cukup untuk satu pemain, sementara setiap pembelian menaikkan rasio gaji.');
 card(s,0.6,1.5,5.9,5.3,'Argumen terkuat untuk B (Pemimpin dari Luar)','• Kasus menyebut pelatih "the single person most responsible for its success", dan sukses berkelanjutan "is almost always associated with a single coach" (hlm. 582).\n• Table 6.8: Mourinho sukses di tiga klub berbeda (Porto, Chelsea, Inter).\n• Setelah Busby pensiun, orang dalam gagal: 18 tahun tanpa gelar liga, sampai orang luar (Ferguson dari Aberdeen) datang (hlm. 583).\n• Kas £80 juta dari Ronaldo tersedia untuk membangun ulang.',{bs:12});
 card(s,6.7,1.5,6.0,5.3,'Kenapa argumen itu tidak cukup','• Kasus juga bilang: "coaches that achieve outstanding success with one team are often dismal failures with another" (hlm. 582). Wibawa tidak otomatis ikut pindah.\n• Ferguson tidak membawa bintang pada 1986; ia membangun sistem dari bawah. Hasil pertama 1990, gelar liga baru 1993. Orang luar yang membongkar sistem mengulang tujuh tahun itu tanpa jaminan.\n• Real Madrid bergonta-ganti pelatih ternama (Capello 1996–97 dan 2006–07, Hiddink 1998–99, Del Bosque 1999–2003, Sacchi 2004; Table 6.8) dan hanya untung 0,4%, dengan poin Eropa di bawah MU.\n• £80 juta setara satu pemain rekor dunia, bukan satu tim. Setiap pembelian menaikkan rasio gaji dari 50% ke arah 81% Chelsea.',{bs:12});
}
// 37 Conclusion
{const s=base('LANGKAH 4 · SIMPULAN','Alternatif C dipilih: ditarik dari tiga isu, dengan angka','Appendix 3 silabus: simpulan "deduces the best alternative from facts" dan "should use them to build quantitative arguments". Angka dari '+CASE+' dan slide 30.',
 'Simpulan kami: alternatif C. Alasannya berurutan. Satu, yang lolos VRIN adalah sistem, bukan orang, jadi sistem yang harus dilindungi. Dua, sistem itu bisa dipecah, jadi bisa dilembagakan. Tiga, keuangan tidak sanggup model membeli, jadi B gugur. Empat, wibawa adalah bagian yang paling sulit dilembagakan, jadi manajer dipilih atas wibawa tetapi diikat struktur, sehingga A saja tidak cukup. Angkanya: lebih dari 30 juta euro hilang kalau gagal ke Liga Champions; pengganti harus dapat rating 8,3; dan gaji harus tetap di bawah 50 persen pendapatan.');
 const pr=[['Alasan 1','Yang lolos VRIN test adalah sistem, bukan orang. Jadi sistem yang harus dilindungi.'],['Alasan 2','Sistem itu resource bundle yang bagian-bagiannya bisa dipisahkan. Jadi bisa dilembagakan.'],['Alasan 3','Keuangan tidak sanggup model membeli pemain. Jadi perombakan total (B) gugur.'],['Alasan 4','Wibawa di depan bintang adalah bagian yang paling sulit dilembagakan. Jadi manajer dipilih atas wibawa, tetapi diikat struktur supaya tidak membongkar sistem. A saja tidak cukup.']];
 pr.forEach((it,i)=>{const y=1.5+i*1.05;card(s,0.6,y,6.6,0.95,null,null);s.addText([{text:it[0]+'. ',options:{bold:true,color:RED}},{text:it[1]}],{x:0.75,y:y+0.1,w:6.3,h:0.8,fontFace:BF,fontSize:11.5,color:DARK,margin:0,isTextBox:true,valign:'top'});});
 card(s,0.6,5.75,6.6,1.1,null,'Karena itu: lembagakan sistem dulu (C), lalu pilih manajer berwibawa yang bekerja di dalamnya. C memuat kekuatan A tanpa kelemahannya, dan menutup risiko B.',{fill:NOTE,bs:12});
 const st=[['> €30 jt','Pendapatan UEFA per musim yang hilang kalau gagal lolos Liga Champions (hlm. 577), belum termasuk tiket dan sponsor.'],['8,3','Rating manajer minimal supaya skor MU sejajar Barcelona. Tanpa struktur, kegagalan satu orang menurunkan skor ke 7,90.'],['50%','Batas gaji terhadap pendapatan yang menjaga margin 31,4%. Melewati 62% berarti kembali ke rata-rata liga yang merugi.']];
 st.forEach((it,i)=>{const y=1.5+i*1.8;card(s,7.4,y,5.3,1.65,null,null);s.addText(it[0],{x:7.55,y:y+0.08,w:5,h:0.55,fontFace:HF,fontSize:22,bold:true,color:RED,margin:0,isTextBox:true});para(s,it[1],7.55,y+0.65,5.0,0.95,10.5);});
}
// 38 Implementation plan
{const s=base('RENCANA IMPLEMENTASI','KPI, jadwal, penanggung jawab, sumber daya, risiko','Sesuai CO2 silabus: "actionable implementation plans with KPIs, timelines, ownership, resources, and risk mitigation". Nama dan angka dasar dari '+CASE+'; target adalah usulan kelompok.',
 'Rencana pelaksanaan alternatif C dalam lima tindakan. Pertama, tuliskan dan pecah sistem Ferguson menjadi tiga jabatan direktur, selagi Ferguson masih ada. Kedua, pilih manajer yang kontraknya memuat batas gaji dan berbagi kewenangan transfer. Ketiga, belanjakan kas Ronaldo untuk beberapa pemain muda, bukan satu bintang. Keempat, amankan pendapatan Asia selagi prestasi tinggi. Kelima, evaluasi tiap akhir musim dengan mengulang competitive strength assessment. Semua target di sini adalah usulan kelompok.');
 const H=(t)=>({text:t,options:{bold:true,color:WHITE,fill:{color:RED}}});
 const rows=[[H('Tindakan'),H('KPI'),H('Jadwal'),H('Penanggung jawab'),H('Sumber daya'),H('Risiko dan cara mengatasinya')],
 ['Tuliskan dan pecah sistem menjadi direktur pemanduan bakat, akademi, dan sepak bola','Tiga jabatan terisi; kebijakan transfer dan filosofi permainan tertulis, disetujui dewan','Musim 2009–10, selagi Ferguson masih menjabat','David Gill bersama Ferguson','Tiga jabatan direktur; biayanya jauh di bawah gaji satu pemain bintang','Ferguson menolak berbagi kewenangan: posisikan sebagai warisan, bukan pengurangan peran'],
 ['Pilih manajer tim yang bekerja di dalam struktur','Kontrak memuat batas gaji 50% pendapatan dan kewenangan transfer bersama direktur sepak bola','Diumumkan sebelum akhir musim 2009–10','Dewan, atas usulan Gill','Anggaran kompensasi manajer','Kandidat berwibawa menolak batasan: siapkan kandidat internal yang dilatih selama transisi'],
 ['Belanjakan kas Ronaldo sesuai sistem, bukan untuk satu bintang','Belanja bersih di bawah £30 juta per musim; dua lulusan akademi masuk tim utama tiap musim','Jendela transfer 2009 dan 2010','Direktur sepak bola dan manajer','Kas £80 juta','Tekanan media dan pendukung: jelaskan rencana sejak awal'],
 ['Amankan pendapatan komersial Asia selagi prestasi tinggi','Pendapatan komersial dari Asia naik 20% per tahun; dua sponsor baru per negara di India dan China','2009–2012','Direktur komersial Richard Arnold','Tim komersial London; tur Asia','Prestasi turun selama transisi: kunci kontrak jangka panjang sekarang'],
 ['Evaluasi tiap akhir musim','Ulangi competitive strength assessment (slide 30): rating sistem kepelatihan tetap di atas 7; posisi empat besar; rasio gaji di bawah 55%','Setiap Juni, mulai 2010','Dewan','Data internal','Rating turun di bawah 6 padahal struktur terisi: ganti manajer, jangan bongkar struktur']];
 s.addTable(rows,{x:0.6,y:1.45,w:12.1,colW:[2.3,2.4,1.5,1.6,1.7,2.6],fontFace:BF,fontSize:9,color:DARK,border:{type:'solid',pt:0.5,color:'D9C6C8'},valign:'top'});
}
// 39 Sources
{const s=base('SUMBER DAN CATATAN','Setiap angka bisa ditelusuri ke kasus','Buku: Thompson, Peteraf, Gamble & Strickland (2024). Kasus: Grant (2010), Contemporary Strategy Analysis, ed. 7, Case 6. Silabus: RPKPS MAN 5422 2026.',
 'Slide ini memetakan asal setiap angka: tabel mana, halaman berapa. Kami juga menyatakan mana yang penilaian kelompok sendiri: bobot dan rating matriks, margin EBITDA yang kami hitung, dan target rencana pelaksanaan. Kasus berhenti di Juli 2009, dan kami tidak memakai informasi setelah itu.');
 card(s,0.6,1.5,5.9,5.3,'Asal data kasus','Table 6.1: gelar liga 1980–2009.\nTable 6.2: poin performa Eropa 2000–2009.\nTable 6.3: peringkat pemain FIFA 2008–09.\nTable 6.4: transfer termahal.\nTable 6.5: pendapatan, EBITDA, nilai klub, utang (Forbes 2009).\nTable 6.6: return on sales 2000–2006.\nTable 6.7: belanja transfer (dirujuk kasus hlm. 580).\nTable 6.8: pelatih paling dihormati 1990–2007.\nAppendix: laporan keuangan MU 2000–2008.\nHlm. 573: tur Asia, Aon, 80 juta pendukung. Hlm. 577–579: pendapatan liga, gaji, pemilik. Hlm. 582–588: pelatih, era Ferguson, kepemilikan, komersial, kandidat pengganti.',{bs:11.5});
 card(s,6.7,1.5,6.0,5.3,'Mana yang penilaian kelompok','• Bobot dan rating competitive strength assessment (slide 30) serta semua target rencana implementasi (slide 38) adalah penilaian kelompok, bukan data kasus.\n• Margin EBITDA (slide 29) dihitung kelompok dari Table 6.5.\n• Istilah transferability (slide 26) dari buku teks Grant, bukan dari teks kasus.\n• Kasus berhenti pada Juli 2009. Tidak ada informasi setelah itu yang dipakai.\n• Gambar Figure 4.1–4.4, Table 4.1–4.4, dan Capsule 4.1 diambil langsung dari PDF buku.',{bs:11.5});
}
// 40 Thank you
{n++;const s=pres.addSlide();s.background={color:RED};
 s.addText('Terima kasih',{x:0.8,y:2.3,w:11,h:1.0,fontFace:HF,fontSize:44,bold:true,color:WHITE,margin:0,isTextBox:true});
 s.addText('Kami membuka sesi tanya jawab. Pertanyaan yang paling kami harapkan: bagian mana dari sistem Ferguson yang menurut Anda tidak bisa dilembagakan, dan apa buktinya?',{x:0.8,y:3.4,w:11.5,h:1.2,fontFace:BF,fontSize:16,color:'F3DCDF',margin:0,isTextBox:true});
 s.addText('Kelompok 4 · Fitra Aidila · Aulia Sisca Rahmadiyanti · Bagaskoro · Imam Prayudha · Tegar Awanto\nStrategic Management MAN 5422 · Dr. Rangga Almahendra, S.T., M.M.',{x:0.8,y:5.4,w:11.5,h:1.0,fontFace:BF,fontSize:12,color:'F3DCDF',margin:0,isTextBox:true});
 s.addText(String(n),{x:12.5,y:7.0,w:0.4,h:0.3,fontFace:BF,fontSize:9,color:'F3DCDF',align:'right',margin:0,isTextBox:true});
 s.addNotes('Terima kasih. Kami membuka diskusi. Pertanyaan yang paling kami harapkan: bagian mana dari sistem Ferguson yang menurut teman-teman tidak bisa dilembagakan, dan apa buktinya di kasus?');
}
pres.writeFile({fileName:'SMJKT_Group 4_Case Manchester United.pptx'}).then(()=>console.log('slides',n));
