window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[11] = {
  bab: 11,
  judul: "BAB 11 PEMERINTAH, REGULASI DAN ETIKA BISNIS",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 11",
  lo: [
    "LO1 Menjelaskan kedudukan pemerintah sebagai pemangku kepentingan bisnis serta sifat hubungan saling ketergantungan antara bisnis dan pemerintah.",
    "LO2 Mengidentifikasi isu-isu etis utama dalam hubungan bisnis dan pemerintah, khususnya lobi, pendanaan partai politik, konflik kepentingan dan penangkapan negara (state capture).",
    "LO3 Menganalisis dampak globalisasi terhadap keseimbangan kekuasaan antara korporasi multinasional dan negara, termasuk fenomena kompetisi regulasi dan race to the bottom.",
    "LO4 Mengevaluasi peran bisnis sebagai aktor dalam proses regulasi melalui swaregulasi, regulasi masyarakat sipil dan inisiatif multi pemangku kepentingan.",
    "LO5 Menilai implikasi hubungan bisnis dan pemerintah terhadap agenda keberlanjutan serta merumuskan implikasi manajerial bagi perusahaan yang beroperasi di Indonesia."
  ],
  sections: [
    {
      no: "11.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membahas hubungan antara bisnis dan pemerintah dari sudut pandang etika bisnis. Pemerintah merupakan pemangku kepentingan yang unik karena memiliki kewenangan untuk menetapkan aturan main yang mengikat seluruh pelaku usaha, sementara pada saat yang sama pemerintah juga bergantung pada bisnis sebagai sumber penerimaan pajak, lapangan kerja dan pertumbuhan ekonomi. Hubungan saling ketergantungan tersebut menimbulkan berbagai persoalan etis yang jarang muncul dalam hubungan perusahaan dengan pemangku kepentingan lain, misalnya pertanyaan mengenai batas kewajaran pengaruh korporasi terhadap proses pembuatan kebijakan publik (Crane dan Matten, 2019). Setelah menyelesaikan sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p>Pertama, mahasiswa mampu menjelaskan kedudukan pemerintah sebagai pemangku kepentingan bisnis beserta peran gandanya sebagai wakil kepentingan warga negara dan sebagai aktor yang memiliki kepentingan sendiri. Kedua, mahasiswa mampu mengidentifikasi isu etis dalam hubungan bisnis dan pemerintah, meliputi lobi, pendanaan partai politik, konflik kepentingan, pintu putar (<em>revolving door</em>) dan <em>state capture</em>. Ketiga, mahasiswa mampu menganalisis pengaruh globalisasi terhadap kapasitas regulasi negara serta munculnya kompetisi regulasi antarnegara. Keempat, mahasiswa mampu mengevaluasi peran baru bisnis sebagai aktor regulasi melalui swaregulasi dan regulasi masyarakat sipil. Kelima, mahasiswa mampu menilai keterkaitan hubungan bisnis dan pemerintah dengan agenda keberlanjutan serta menarik implikasi manajerial yang relevan bagi konteks Indonesia.</p>`
    },
    {
      no: "11.2",
      title: "Pemerintah sebagai Pemangku Kepentingan Bisnis",
      body: `<p>Pembahasan mengenai etika dalam hubungan bisnis dan pemerintah perlu diawali dengan pemahaman yang tepat mengenai apa yang dimaksud dengan pemerintah dan regulasi. Dalam percakapan sehari-hari, pemerintah sering dipahami secara sempit sebagai presiden dan para menteri. Namun, dalam kajian etika bisnis, pengertian pemerintah jauh lebih luas dan mencakup beragam aktor serta institusi yang saling berinteraksi dengan dunia usaha pada berbagai tingkatan.</p>
<h5>11.2.1 Definisi Pemerintah dan Regulasi</h5>
<p>Menurut Crane dan Matten (2019), pemerintah dapat dipahami sebagai kumpulan aktor dan institusi yang memiliki kewenangan sah untuk menetapkan hukum serta aturan yang mengikat bagi pihak-pihak yang berada dalam wilayah yurisdiksinya. Pengertian ini menegaskan bahwa pemerintah bukan entitas tunggal, melainkan terdiri atas lembaga legislatif yang membuat undang-undang, lembaga eksekutif beserta birokrasi yang menjalankannya, lembaga yudikatif yang menegakkannya, serta berbagai badan dan komisi regulator yang mengawasi sektor tertentu. Adapun regulasi didefinisikan sebagai perangkat aturan yang diterbitkan oleh pemerintah untuk mengarahkan perilaku aktor-aktor dalam masyarakat, termasuk perusahaan (Crane dan Matten, 2019). Dari definisi tersebut dapat disimpulkan bahwa regulasi merupakan instrumen utama yang menghubungkan pemerintah dengan bisnis, karena melalui regulasi itulah pemerintah menetapkan batas antara praktik bisnis yang diperbolehkan dan yang dilarang.</p>
<p>Selain itu, penting dipahami bahwa aktor pemerintah beroperasi pada berbagai tingkatan, yaitu tingkat lokal atau daerah, tingkat nasional, tingkat regional seperti Uni Eropa atau ASEAN, dan tingkat global seperti Organisasi Perdagangan Dunia (WTO) dan Organisasi Perburuhan Internasional (ILO). Bagi manajer, konsekuensi praktisnya adalah bahwa perusahaan berhadapan dengan lapisan regulasi yang berjenjang dan kadang tidak konsisten satu sama lain. Perusahaan multinasional yang beroperasi di Indonesia, misalnya, tunduk pada peraturan daerah, undang-undang nasional, komitmen Indonesia dalam ASEAN, serta ketentuan perdagangan internasional secara bersamaan.</p>
<h5>11.2.2 Peran Ganda Pemerintah dalam Hubungannya dengan Bisnis</h5>
<p>Crane dan Matten (2019) menekankan bahwa pemerintah menjalankan peran ganda dalam hubungannya dengan bisnis. Di satu sisi, pemerintah, khususnya dalam sistem demokrasi, merupakan wakil dari kepentingan warga negara. Ketika pemerintah menetapkan aturan upah minimum, standar keselamatan produk atau baku mutu lingkungan, pada hakikatnya pemerintah sedang memperjuangkan kepentingan masyarakat yang memilihnya. Di sisi lain, pemerintah juga merupakan aktor yang memiliki kepentingan sendiri, misalnya kepentingan politisi untuk terpilih kembali, kepentingan birokrasi untuk mempertahankan anggaran dan kewenangan, serta kepentingan negara untuk meningkatkan penerimaan pajak dan daya saing ekonomi. Peran ganda inilah yang menjadikan hubungan bisnis dan pemerintah rentan terhadap persoalan etis, karena kepentingan pribadi aktor pemerintah dapat bertabrakan dengan kepentingan publik yang seharusnya mereka wakili.</p>
<p>Hubungan bisnis dan pemerintah juga bersifat saling bergantung. Bisnis membutuhkan pemerintah untuk menyediakan kepastian hukum, infrastruktur, pendidikan tenaga kerja dan perlindungan hak milik. Sebaliknya, pemerintah membutuhkan bisnis sebagai sumber pajak, pencipta lapangan kerja dan motor pertumbuhan. Oleh karena itu, keduanya memiliki insentif kuat untuk saling memengaruhi. Dengan demikian, pertanyaan etis yang mendasar dalam bab ini bukanlah apakah bisnis boleh berhubungan dengan pemerintah, melainkan bagaimana bentuk dan batas pengaruh yang dapat dibenarkan secara moral.</p>
<h5>11.2.3 Regulasi, Deregulasi dan Privatisasi</h5>
<p>Intensitas peran pemerintah terhadap bisnis tidak bersifat tetap, melainkan berubah mengikuti ideologi ekonomi yang dominan. Sejak dekade 1980-an, banyak negara melakukan deregulasi, yaitu pengurangan aturan yang membebani dunia usaha, serta privatisasi, yaitu pengalihan kepemilikan atau pengelolaan layanan publik dari negara kepada swasta (Crane dan Matten, 2019). Kedua kebijakan tersebut menimbulkan pertanyaan etis tersendiri, karena layanan yang semula diselenggarakan atas dasar kepentingan publik kemudian dikelola atas dasar motif laba. Di Indonesia, perdebatan serupa muncul dalam pengelolaan air minum, jalan tol dan pelayanan kesehatan yang melibatkan swasta. Implikasi manajerialnya adalah bahwa perusahaan yang mengambil alih fungsi layanan publik memikul tanggung jawab moral yang lebih besar daripada perusahaan biasa, karena kegagalannya berdampak langsung pada pemenuhan kebutuhan dasar masyarakat.</p>`
    },
    {
      no: "11.3",
      title: "Isu Etis dalam Hubungan Bisnis dan Pemerintah",
      body: `<p>Isu etis paling mendasar dalam hubungan bisnis dan pemerintah berkaitan dengan legitimasi pengaruh korporasi terhadap proses politik. Dalam sistem demokrasi, kebijakan publik seharusnya mencerminkan kehendak warga negara yang masing-masing memiliki satu suara. Namun, korporasi memiliki sumber daya finansial, informasi dan akses yang jauh melampaui warga negara biasa, sehingga muncul kekhawatiran bahwa kebijakan publik lebih mencerminkan kepentingan pemilik modal daripada kepentingan masyarakat luas (Crane dan Matten, 2019). Persoalan ini menjadi semakin serius karena pengaruh bisnis terhadap pemerintah sering berlangsung secara tertutup dan sulit diawasi oleh publik.</p>
<table class="bk-table">
<caption>Tabel 11.1 Bentuk Pengaruh Bisnis terhadap Pemerintah dan Isu Etisnya</caption>
<thead><tr><th>Bentuk Pengaruh</th><th>Mekanisme</th><th>Isu Etis Utama</th></tr></thead>
<tbody>
<tr><td>Lobi</td><td>Penyampaian informasi dan argumen kepada pembuat kebijakan secara langsung atau melalui asosiasi dan konsultan</td><td>Ketimpangan akses, rendahnya transparansi, potensi informasi yang menyesatkan</td></tr>
<tr><td>Pendanaan politik</td><td>Sumbangan kepada partai, kandidat atau kampanye pemilihan umum</td><td>Kecurigaan balas jasa kebijakan, ketergantungan politisi pada donor besar</td></tr>
<tr><td>Pintu putar (revolving door)</td><td>Perpindahan personel antara jabatan publik dan jabatan korporasi</td><td>Konflik kepentingan, penyalahgunaan informasi dan jejaring jabatan</td></tr>
<tr><td>Rangkap jabatan</td><td>Pejabat publik yang sekaligus memiliki atau mengelola bisnis</td><td>Pembauran kepentingan publik dan kepentingan pribadi</td></tr>
<tr><td>State capture</td><td>Pembelian pengaruh untuk membentuk isi aturan sejak awal, umumnya melalui suap</td><td>Perusakan sistem demokrasi dan persaingan yang sehat</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
</table>
<h5>11.3.1 Lobi</h5>
<p>Lobi merupakan bentuk pengaruh bisnis terhadap pemerintah yang paling umum. Menurut Crane dan Matten (2019), lobi dapat dipahami sebagai upaya terorganisasi untuk memengaruhi pembuat kebijakan melalui penyampaian informasi, argumen dan preferensi mengenai suatu kebijakan tertentu. Lobi dapat dilakukan secara langsung oleh eksekutif perusahaan, melalui asosiasi industri, atau dengan menyewa konsultan dan firma lobi profesional. Pada dasarnya lobi tidak selalu tercela, karena pembuat kebijakan memang membutuhkan informasi teknis dari pelaku industri agar regulasi yang dihasilkan realistis dan dapat dilaksanakan. Organisasi untuk Kerja Sama dan Pembangunan Ekonomi bahkan menegaskan bahwa lobi yang transparan dapat memperbaiki kualitas kebijakan publik (OECD, 2013).</p>
<p>Namun, lobi menimbulkan setidaknya tiga persoalan etis. Pertama, terdapat ketimpangan akses, karena korporasi besar mampu membiayai lobi secara intensif sementara kelompok masyarakat yang terdampak kebijakan sering tidak memiliki sumber daya serupa. Kedua, lobi kerap berlangsung tanpa transparansi, sehingga publik tidak mengetahui siapa memengaruhi apa dan dengan argumen seperti apa. Ketiga, lobi dapat berubah menjadi penyampaian informasi yang bias atau menyesatkan demi kepentingan sempit perusahaan, misalnya ketika industri tertentu mendanai kajian yang meragukan bukti ilmiah tentang bahaya produknya. Oleh karena itu, banyak negara mengatur lobi melalui daftar pelobi terdaftar dan kewajiban pelaporan, meskipun efektivitasnya masih diperdebatkan.</p>
<h5>11.3.2 Pendanaan Partai dan Kampanye Politik</h5>
<p>Bentuk pengaruh kedua adalah sumbangan finansial kepada partai politik dan kandidat. Kampanye politik modern membutuhkan biaya besar, sehingga politisi cenderung bergantung pada donor korporasi dan individu kaya. Ketergantungan tersebut menimbulkan kecurigaan adanya hubungan balas jasa, yaitu kebijakan atau proyek pemerintah diberikan sebagai imbalan atas sumbangan kampanye (Crane dan Matten, 2019). Sekalipun tidak ada kesepakatan eksplisit, sumbangan besar tetap menciptakan akses istimewa dan rasa berutang budi yang dapat membelokkan pertimbangan pejabat publik. Di Indonesia, mahalnya biaya pencalonan kepala daerah sering dikaitkan dengan praktik ijon politik, yaitu pengusaha membiayai kandidat dengan harapan memperoleh konsesi, izin tambang atau proyek pengadaan setelah kandidat tersebut menjabat. Dengan demikian, perusahaan yang berpartisipasi dalam pendanaan politik perlu menimbang bukan hanya legalitas sumbangan, tetapi juga dampaknya terhadap integritas proses demokrasi.</p>
<h5>11.3.3 Konflik Kepentingan, Pintu Putar dan Rangkap Jabatan</h5>
<p>Isu etis berikutnya bersumber dari perpindahan orang antara ranah publik dan ranah bisnis. Fenomena <em>revolving door</em> atau pintu putar merujuk pada praktik mantan pejabat pemerintah yang menjadi eksekutif, komisaris atau pelobi di perusahaan yang dahulu mereka atur, dan sebaliknya eksekutif bisnis yang diangkat menduduki jabatan publik yang mengatur industrinya sendiri (Crane dan Matten, 2019). Praktik ini menimbulkan konflik kepentingan karena pejabat yang masih menjabat dapat bersikap lunak terhadap industri demi peluang karier setelah pensiun, sedangkan mantan pejabat dapat memanfaatkan informasi rahasia dan jejaring lamanya untuk kepentingan perusahaan. Selain itu, terdapat persoalan rangkap jabatan ketika politisi atau pejabat aktif sekaligus memiliki bisnis yang terpengaruh oleh kebijakan yang mereka buat. Di Indonesia, pengangkatan tokoh politik sebagai komisaris badan usaha milik negara kerap dikritik publik karena berpotensi mencampurkan pertimbangan profesional dengan balas jasa politik. Implikasi manajerialnya, perusahaan perlu menetapkan masa jeda (<em>cooling off period</em>) dan uji tuntas integritas sebelum merekrut mantan pejabat publik.</p>
<h5>11.3.4 State Capture dan Korupsi Kebijakan</h5>
<p>Bentuk pengaruh yang paling merusak adalah <em>state capture</em>, yaitu kondisi ketika perusahaan atau kelompok bisnis berhasil membentuk isi hukum, peraturan dan kebijakan negara demi kepentingannya sendiri, umumnya melalui suap, gratifikasi atau relasi kolusif dengan pejabat (Crane dan Matten, 2019). Berbeda dengan korupsi administratif yang menyimpangkan pelaksanaan aturan, <em>state capture</em> menyimpangkan pembuatan aturan itu sendiri, sehingga praktik yang merugikan publik justru menjadi legal. Kasus korupsi proyek KTP elektronik yang melibatkan anggota legislatif, birokrat dan rekanan swasta menunjukkan bagaimana proses anggaran dan pengadaan di Indonesia dapat dibajak oleh jejaring kepentingan bisnis dan politik. Konsekuensi jangka panjang <em>state capture</em> sangat serius, karena persaingan usaha tidak lagi ditentukan oleh efisiensi dan inovasi, melainkan oleh kedekatan dengan kekuasaan. Oleh karena itu, keterlibatan dalam praktik semacam ini tidak dapat dibenarkan dari sudut pandang teori etika mana pun dan sekaligus melanggar hukum antikorupsi di hampir semua yurisdiksi.</p>`
    },
    {
      no: "11.4",
      title: "Globalisasi dan Pergeseran Relasi Bisnis dengan Pemerintah",
      body: `<p>Globalisasi mengubah secara mendasar keseimbangan kekuasaan antara korporasi dan negara. Regulasi pada dasarnya bersifat teritorial, artinya hanya mengikat di dalam wilayah yurisdiksi suatu negara, sedangkan korporasi multinasional beroperasi lintas batas dan dapat memindahkan modal, produksi serta laba dari satu negara ke negara lain dengan relatif mudah (Crane dan Matten, 2019). Akibatnya, kapasitas negara untuk mengatur perilaku korporasi melemah, karena perusahaan dapat menghindari regulasi yang dianggap memberatkan dengan berpindah ke yurisdiksi yang lebih longgar. Fenomena ini melahirkan apa yang disebut kesenjangan tata kelola, yaitu ruang kegiatan bisnis global yang tidak tersentuh oleh regulasi negara mana pun secara efektif.</p>
<h5>11.4.1 Kompetisi Regulasi dan Race to the Bottom</h5>
<p>Mobilitas modal mendorong negara-negara bersaing menarik investasi dengan menawarkan lingkungan regulasi yang paling menguntungkan bagi bisnis. Kompetisi regulasi semacam ini dapat berbentuk penurunan tarif pajak korporasi, pelonggaran standar perburuhan atau pengenduran ketentuan lingkungan hidup. Apabila setiap negara terus menurunkan standarnya agar tidak kalah menarik dibandingkan negara lain, terjadilah <em>race to the bottom</em>, yaitu perlombaan menuju standar terendah yang pada akhirnya merugikan pekerja, konsumen dan lingkungan di semua negara (Crane dan Matten, 2019). Persaingan Indonesia dengan Vietnam dan Thailand dalam menarik relokasi pabrik melalui insentif <em>tax holiday</em> dan penyederhanaan perizinan menggambarkan dinamika tersebut. Di sisi lain, sebagian ahli menunjukkan bahwa perlombaan menuju puncak juga mungkin terjadi, misalnya ketika standar lingkungan Uni Eropa yang ketat memaksa eksportir di negara berkembang menaikkan standarnya agar tetap dapat mengakses pasar Eropa.</p>
<h5>11.4.2 Peran Lembaga Supranasional</h5>
<p>Sebagai jawaban atas melemahnya regulasi nasional, peran lembaga regional dan global semakin penting. WTO mengatur perdagangan internasional, ILO menetapkan standar perburuhan, dan berbagai perjanjian multilateral seperti Persetujuan Paris mengatur agenda iklim. Namun, sebagian besar instrumen internasional tersebut memiliki daya paksa yang terbatas terhadap korporasi, karena subjek hukum internasional pada umumnya adalah negara, bukan perusahaan (Crane dan Matten, 2019). Dengan demikian, tetap terdapat ruang kosong regulasi yang kemudian diisi oleh bentuk-bentuk pengaturan baru yang melibatkan bisnis dan masyarakat sipil, sebagaimana dibahas pada sub-bab berikutnya. Bagi manajer perusahaan multinasional, pelajaran pentingnya adalah bahwa kepatuhan terhadap hukum nasional yang longgar tidak serta merta membebaskan perusahaan dari tanggung jawab moral, karena ekspektasi pemangku kepentingan global sering lebih tinggi daripada tuntutan hukum setempat.</p>`
    },
    {
      no: "11.5",
      title: "Bisnis sebagai Aktor dalam Regulasi",
      body: `<p>Perkembangan paling menarik dalam relasi bisnis dan pemerintah pada era globalisasi adalah berubahnya posisi bisnis dari sekadar objek regulasi menjadi salah satu aktor yang turut membuat regulasi. Ketika kapasitas negara terbatas, muncul berbagai bentuk pengaturan privat dan hibrida yang melibatkan perusahaan, asosiasi industri dan organisasi masyarakat sipil. Crane dan Matten (2019) menempatkan fenomena ini dalam kerangka kewarganegaraan korporasi (<em>corporate citizenship</em>), yaitu pandangan bahwa korporasi kini menjalankan sebagian fungsi yang secara tradisional dijalankan pemerintah, termasuk fungsi penyediaan barang publik dan fungsi pembuatan aturan.</p>
<h5>11.5.1 Swaregulasi dan Kode Etik Industri</h5>
<p>Swaregulasi (<em>self-regulation</em>) adalah pengaturan perilaku bisnis yang dirancang, disepakati dan ditegakkan oleh pelaku industri sendiri, biasanya melalui asosiasi, tanpa paksaan langsung dari negara. Contohnya meliputi kode etik periklanan, standar teknis industri dan mekanisme pengaduan konsumen yang dikelola asosiasi. Keunggulan swaregulasi terletak pada fleksibilitas, kecepatan penyesuaian dan pemanfaatan keahlian teknis pelaku industri yang sering tidak dimiliki regulator (Crane dan Matten, 2019). Namun, kelemahannya juga nyata, yaitu lemahnya penegakan karena sanksi terberat biasanya hanya pengeluaran dari keanggotaan asosiasi, serta risiko bahwa aturan disusun demi melindungi kepentingan industri, bukan kepentingan publik. Kritik semacam ini sering diibaratkan menyerahkan penjagaan kandang ayam kepada rubah. Oleh karena itu, swaregulasi umumnya lebih kredibel apabila disertai pemantauan pihak ketiga yang independen.</p>
<h5>11.5.2 Regulasi Masyarakat Sipil dan Inisiatif Multi Pemangku Kepentingan</h5>
<p>Selain swaregulasi, berkembang pula regulasi masyarakat sipil (<em>civil regulation</em>), yaitu pengaturan perilaku bisnis yang digerakkan oleh organisasi nonpemerintah melalui kampanye, pemeringkatan dan skema sertifikasi. Standar seperti Forest Stewardship Council untuk produk kayu dan Fairtrade untuk komoditas pertanian merupakan contoh aturan privat yang dipatuhi perusahaan bukan karena kewajiban hukum, melainkan karena tekanan pasar dan reputasi (Crane dan Matten, 2019). Bentuk yang lebih maju adalah inisiatif multi pemangku kepentingan yang mempertemukan perusahaan, LSM dan kadang pemerintah dalam satu lembaga penetap standar. Dalam konteks Indonesia, Roundtable on Sustainable Palm Oil (RSPO) merupakan contoh yang sangat relevan, karena produsen minyak sawit Indonesia bersertifikat RSPO tunduk pada standar privat internasional, sementara pemerintah Indonesia menerbitkan standar wajib Indonesian Sustainable Palm Oil (ISPO) sebagai respons kedaulatan regulasi. Interaksi antara standar privat global dan regulasi nasional tersebut memperlihatkan lapisan tata kelola baru yang harus dikelola perusahaan secara simultan.</p>
<h5>11.5.3 Persoalan Akuntabilitas Regulasi Privat</h5>
<p>Meskipun regulasi privat mengisi kekosongan yang ditinggalkan negara, ia menimbulkan persoalan akuntabilitas demokratis. Pemerintah memperoleh legitimasinya dari pemilihan umum, sedangkan perusahaan dan LSM yang menyusun standar privat tidak dipilih oleh siapa pun dan tidak dapat diberhentikan oleh publik (Crane dan Matten, 2019). Selain itu, cakupan regulasi privat bersifat sukarela sehingga pelaku usaha yang paling bermasalah justru dapat memilih untuk tidak ikut serta. Dari definisi dan uraian tersebut dapat disimpulkan bahwa regulasi privat sebaiknya dipandang sebagai pelengkap, bukan pengganti, regulasi negara. Implikasi manajerialnya, perusahaan yang terlibat dalam penyusunan standar privat perlu memastikan proses yang inklusif, transparan dan dapat diverifikasi agar standar tersebut memperoleh legitimasi di mata pemangku kepentingan.</p>
<table class="bk-table">
<caption>Tabel 11.2 Perbandingan Tiga Moda Pengaturan Perilaku Bisnis</caption>
<thead><tr><th>Aspek</th><th>Regulasi Pemerintah</th><th>Swaregulasi Industri</th><th>Regulasi Masyarakat Sipil</th></tr></thead>
<tbody>
<tr><td>Pembuat aturan</td><td>Legislatif, eksekutif dan badan regulator</td><td>Asosiasi dan pelaku industri</td><td>LSM, lembaga sertifikasi, forum multi pemangku kepentingan</td></tr>
<tr><td>Dasar kepatuhan</td><td>Kewajiban hukum dan sanksi negara</td><td>Kesepakatan anggota dan tekanan sesama pelaku</td><td>Tekanan pasar, reputasi dan preferensi konsumen</td></tr>
<tr><td>Kekuatan utama</td><td>Daya paksa dan cakupan menyeluruh</td><td>Keahlian teknis dan fleksibilitas</td><td>Legitimasi moral dan jangkauan lintas negara</td></tr>
<tr><td>Kelemahan utama</td><td>Lambat, terbatas pada wilayah yurisdiksi</td><td>Penegakan lemah, rawan kepentingan sempit</td><td>Sukarela, akuntabilitas demokratis terbatas</td></tr>
<tr><td>Contoh</td><td>Undang-undang perlindungan konsumen, ISPO</td><td>Kode etik periklanan, standar asosiasi</td><td>FSC, Fairtrade, RSPO</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
</table>`
    },
    {
      no: "11.6",
      title: "Regulasi, Bisnis dan Keberlanjutan",
      body: `<p>Hubungan bisnis dan pemerintah memiliki arti khusus bagi agenda keberlanjutan. Banyak persoalan keberlanjutan, seperti perubahan iklim, pencemaran lintas batas dan penipisan sumber daya, merupakan masalah barang publik yang tidak dapat diselesaikan oleh mekanisme pasar semata, sehingga peran regulasi pemerintah menjadi sangat menentukan (Crane dan Matten, 2019). Dalam konteks ini, sikap bisnis terhadap regulasi keberlanjutan menjadi ukuran penting integritas etisnya. Perusahaan dapat memilih menjadi penghambat, misalnya dengan melobi pelemahan aturan emisi atau mendanai keraguan ilmiah terhadap perubahan iklim, atau menjadi pendukung, misalnya dengan mendorong kepastian regulasi karbon yang justru dibutuhkan untuk berinvestasi dalam teknologi bersih.</p>
<p>Fenomena lobi iklim memperlihatkan bahwa pengaruh politik korporasi dapat menghasilkan kerugian sosial yang jauh melampaui dampak operasional perusahaan itu sendiri. Sebuah perusahaan yang mengurangi emisi di pabriknya namun secara bersamaan melobi penundaan kebijakan energi terbarukan pada dasarnya bersikap tidak konsisten secara etis. Oleh karena itu, transparansi posisi kebijakan publik perusahaan, termasuk keselarasan antara pernyataan keberlanjutan dan aktivitas lobi asosiasi industrinya, kini menjadi tuntutan investor dan lembaga pemeringkat keberlanjutan. Di Indonesia, dinamika serupa tampak dalam perumusan kebijakan nilai ekonomi karbon dan moratorium sawit, ketika asosiasi industri aktif memengaruhi rancangan aturan yang akan membebani anggotanya.</p>
<p>Selain itu, agenda keberlanjutan menuntut kolaborasi, bukan sekadar relasi pengaruh satu arah. Pencapaian Tujuan Pembangunan Berkelanjutan (SDGs) secara eksplisit menempatkan kemitraan pemerintah, bisnis dan masyarakat sipil sebagai prasyarat keberhasilan (Crane dan Matten, 2019). Dengan demikian, kematangan etis sebuah perusahaan tidak hanya diukur dari kepatuhannya terhadap regulasi yang ada, tetapi juga dari kontribusinya dalam membentuk regulasi yang lebih baik bagi kepentingan bersama.</p>`
    },
    {
      no: "11.7",
      title: "Konteks Indonesia dan Implikasi Manajerial",
      body: `<p>Kerangka analitis bab ini sangat relevan bagi praktik bisnis di Indonesia. Struktur ekonomi Indonesia dicirikan oleh peran negara yang besar melalui badan usaha milik negara, sistem perizinan yang kompleks, serta desentralisasi yang memberikan kewenangan regulasi signifikan kepada pemerintah daerah. Kondisi tersebut memperbanyak titik temu antara pelaku usaha dan pejabat publik, sehingga memperbesar peluang sekaligus risiko etis dalam hubungan bisnis dan pemerintah. Berbagai kasus yang ditangani Komisi Pemberantasan Korupsi, mulai dari suap perizinan tambang hingga korupsi pengadaan barang dan jasa, memperlihatkan bahwa bentuk pengaruh ilegitim yang dibahas Crane dan Matten (2019) bukan persoalan teoretis semata, melainkan risiko operasional yang nyata bagi perusahaan di Indonesia.</p>
<p>Dari uraian bab ini dapat dirumuskan beberapa implikasi manajerial. Pertama, perusahaan perlu membangun kebijakan keterlibatan politik yang eksplisit, mencakup aturan mengenai lobi, sumbangan politik, gratifikasi dan interaksi dengan pejabat publik, serta memublikasikannya sebagai bagian dari tata kelola perusahaan. Kedua, fungsi hubungan pemerintah (<em>government relations</em>) sebaiknya dijalankan oleh profesional yang terlatih dalam kepatuhan antikorupsi, dengan dokumentasi pertemuan dan posisi kebijakan yang dapat diaudit. Ketiga, perusahaan perlu menerapkan uji tuntas integritas ketika merekrut mantan pejabat publik, termasuk masa jeda untuk jabatan yang berisiko konflik kepentingan. Keempat, keikutsertaan dalam standar privat seperti RSPO atau inisiatif multi pemangku kepentingan lainnya sebaiknya dipandang sebagai investasi legitimasi jangka panjang, bukan sekadar biaya kepatuhan. Kelima, posisi lobi perusahaan dan asosiasinya harus diselaraskan dengan komitmen keberlanjutan yang dinyatakan secara publik agar perusahaan terhindar dari tuduhan kemunafikan kebijakan. Dengan menjalankan kelima langkah tersebut, perusahaan dapat mempertahankan akses yang sah terhadap proses kebijakan tanpa mengorbankan integritas dan reputasinya.</p>`
    },
    {
      no: "11.8",
      title: "Rangkuman",
      body: `<p>Bab ini menunjukkan bahwa pemerintah merupakan pemangku kepentingan bisnis yang bersifat khas karena memegang kewenangan menetapkan aturan main sekaligus bergantung pada bisnis untuk mencapai tujuan ekonominya. Peran ganda pemerintah sebagai wakil kepentingan warga dan sebagai aktor berkepentingan sendiri menjadikan hubungan bisnis dan pemerintah rawan penyimpangan etis. Bentuk-bentuk pengaruh bisnis terhadap pemerintah membentang dari lobi yang sah namun perlu transparan, pendanaan politik yang menimbulkan kecurigaan balas jasa, konflik kepentingan melalui pintu putar dan rangkap jabatan, hingga <em>state capture</em> yang merusak sendi demokrasi dan persaingan sehat.</p>
<p>Globalisasi memperlemah kapasitas regulasi negara karena korporasi multinasional dapat berpindah yurisdiksi, sehingga muncul kompetisi regulasi antarnegara yang berisiko menimbulkan <em>race to the bottom</em>. Kekosongan tata kelola yang timbul kemudian diisi oleh bentuk pengaturan baru, yaitu swaregulasi industri, regulasi masyarakat sipil dan inisiatif multi pemangku kepentingan, yang masing-masing memiliki kekuatan dan kelemahan dalam hal daya paksa, keahlian dan akuntabilitas. Dalam kerangka kewarganegaraan korporasi, bisnis kini menjadi aktor politik yang turut membuat aturan, dan karena itu memikul tuntutan akuntabilitas yang lebih besar.</p>
<p>Akhirnya, hubungan bisnis dan pemerintah menentukan keberhasilan agenda keberlanjutan, karena persoalan seperti perubahan iklim hanya dapat diatasi melalui regulasi yang efektif dan kolaborasi lintas sektor. Bagi manajer di Indonesia, pesan utama bab ini adalah perlunya mengelola keterlibatan politik perusahaan secara transparan, patuh pada hukum antikorupsi dan selaras dengan komitmen keberlanjutan, sehingga pengaruh perusahaan terhadap kebijakan publik memperoleh legitimasi etis di mata seluruh pemangku kepentingan.</p>`
    },
    {
      no: "11.9",
      title: "Daftar Pustaka",
      body: `<p>Crane, A. dan Matten, D. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford University Press.</p>
<p>OECD. (2013). <em>Transparency and Integrity in Lobbying</em>. OECD Publishing.</p>`
    }
  ]
};
