window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[10] = {
  bab: 10,
  judul: "BAB 10 MASYARAKAT SIPIL DAN ETIKA BISNIS",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 10",
  lo: [
    "LO1 Menjelaskan konsep masyarakat sipil serta kedudukan organisasi masyarakat sipil sebagai sektor ketiga di samping negara dan pasar.",
    "LO2 Mengidentifikasi ragam jenis organisasi masyarakat sipil dan menganalisis sifat kepentingan (stake) yang mereka miliki terhadap korporasi.",
    "LO3 Menganalisis isu etis dalam hubungan antara bisnis dan organisasi masyarakat sipil, termasuk taktik kampanye, boikot, dan persoalan akuntabilitas organisasi masyarakat sipil.",
    "LO4 Mengevaluasi dampak globalisasi terhadap peran dan jangkauan masyarakat sipil dalam mengawasi perilaku korporasi.",
    "LO5 Menjelaskan bentuk kolaborasi bisnis dengan organisasi masyarakat sipil serta konsep regulasi sipil dalam kerangka kewargaan korporat.",
    "LO6 Menilai kontribusi masyarakat sipil terhadap pencapaian agenda keberlanjutan dan implikasinya bagi pengelolaan perusahaan."
  ],
  sections: [
    {
      no: "10.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membahas kelompok pemangku kepentingan yang dalam beberapa dekade terakhir tumbuh menjadi salah satu kekuatan paling berpengaruh dalam membentuk perilaku etis perusahaan, yaitu masyarakat sipil beserta organisasi yang mewakilinya. Apabila bab sebelumnya menempatkan pemerintah sebagai regulator formal aktivitas bisnis, bab ini menunjukkan bahwa terdapat aktor ketiga di luar negara dan pasar yang turut menetapkan batas moral bagi korporasi melalui kampanye, tekanan publik, kemitraan, dan bahkan pembentukan standar sukarela. Pemahaman terhadap dinamika hubungan antara bisnis dan masyarakat sipil menjadi kompetensi penting bagi mahasiswa program magister manajemen karena kegagalan mengelola hubungan tersebut dapat berujung pada krisis reputasi yang serius.</p>
      <p>Setelah menyelesaikan sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <p>1) Menjelaskan konsep masyarakat sipil dan kedudukan organisasi masyarakat sipil sebagai sektor ketiga; 2) Mengidentifikasi jenis organisasi masyarakat sipil dan sifat kepentingannya terhadap korporasi; 3) Menganalisis isu etis dalam hubungan bisnis dengan organisasi masyarakat sipil, termasuk taktik kampanye, boikot, dan akuntabilitas organisasi tersebut; 4) Mengevaluasi pengaruh globalisasi terhadap peran masyarakat sipil; 5) Menjelaskan bentuk kolaborasi bisnis dengan organisasi masyarakat sipil serta konsep regulasi sipil; dan 6) Menilai kontribusi masyarakat sipil terhadap agenda keberlanjutan.</p>`
    },
    {
      no: "10.2",
      title: "Konsep Masyarakat Sipil dan Organisasi Masyarakat Sipil",
      body: `<p>Kehidupan sosial modern lazim dipetakan ke dalam tiga sektor besar, yaitu sektor pertama berupa negara atau pemerintah, sektor kedua berupa pasar atau dunia usaha, dan sektor ketiga berupa masyarakat sipil. Masyarakat sipil atau <em>civil society</em> merujuk pada arena kehidupan kolektif yang berada di luar lingkup negara, pasar, dan keluarga, tempat warga secara sukarela berhimpun untuk memperjuangkan nilai, kepentingan, atau tujuan bersama (Crane dan Matten, 2019). Arena ini mencakup beragam wadah seperti organisasi nirlaba, lembaga swadaya masyarakat, kelompok keagamaan, perkumpulan profesi, komunitas lokal, hingga gerakan sosial yang longgar strukturnya. Dengan demikian, masyarakat sipil bukanlah satu entitas tunggal, melainkan mosaik kepentingan dan nilai yang sangat beragam dan kadang saling bertentangan.</p>
      <p>Aktor yang paling relevan bagi etika bisnis dari arena tersebut adalah organisasi masyarakat sipil atau <em>civil society organization</em> (OMS). Menurut Crane dan Matten (2019), OMS mencakup seluruh organisasi terlembaga yang mewadahi kepentingan warga di luar struktur negara dan korporasi, sehingga istilah ini lebih luas daripada istilah <em>non-governmental organization</em> (NGO) yang umumnya hanya menunjuk lembaga advokasi profesional. Sementara itu, literatur sektor nirlaba mendefinisikan sektor ketiga sebagai kumpulan organisasi yang bersifat formal, privat, tidak membagikan laba, mandiri, dan sukarela (Salamon dan Anheier, 1997). Dari kedua definisi tersebut dapat disimpulkan bahwa OMS adalah organisasi sukarela dan nirlaba yang dibentuk warga untuk memperjuangkan kepentingan atau nilai tertentu, yang keberadaannya tidak dikendalikan oleh pemerintah maupun motif laba. Ciri nirlaba inilah yang memberi OMS legitimasi moral di mata publik ketika berhadapan dengan korporasi.</p>
      <h5>10.2.1 Tipologi Organisasi Masyarakat Sipil</h5>
      <p>Keragaman OMS dapat dipetakan berdasarkan siapa yang kepentingannya diperjuangkan. Kelompok pertama disebut kelompok seksional (<em>sectional group</em>), yaitu organisasi yang memperjuangkan kepentingan anggotanya sendiri, misalnya serikat pekerja, asosiasi konsumen, perhimpunan profesi, dan kelompok masyarakat adat. Kelompok kedua disebut kelompok promosional (<em>promotional group</em>) atau kelompok kausa, yaitu organisasi yang memperjuangkan suatu isu atau nilai yang manfaatnya melampaui anggotanya, misalnya organisasi lingkungan hidup, lembaga hak asasi manusia, dan gerakan antikorupsi (Crane dan Matten, 2019). Pembedaan ini penting bagi manajer karena logika tuntutan keduanya berbeda; kelompok seksional menuntut perbaikan kondisi konkret bagi konstituennya, sedangkan kelompok promosional menuntut perubahan kebijakan perusahaan atas nama kepentingan publik yang lebih luas.</p>
      <p>Selain berdasarkan orientasi kepentingan, OMS juga dapat dibedakan menurut lingkup geografis, mulai dari kelompok akar rumput di tingkat desa, organisasi nasional, hingga jaringan internasional seperti Greenpeace, Oxfam, dan Amnesty International. OMS juga bervariasi dalam hal taktik, dari yang kooperatif dan berorientasi kemitraan sampai yang konfrontatif dan berorientasi kampanye tekanan. Dalam konteks Indonesia, spektrum tersebut terlihat jelas, misalnya Wahana Lingkungan Hidup Indonesia (WALHI) yang bergerak sebagai kelompok promosional di bidang lingkungan, Yayasan Lembaga Konsumen Indonesia (YLKI) yang mewakili kepentingan konsumen, serta lembaga filantropi keagamaan seperti Dompet Dhuafa dan LazisMu yang menyalurkan dana sosial masyarakat. Oleh karena itu, manajer tidak dapat memperlakukan seluruh OMS dengan satu pendekatan seragam, melainkan perlu memahami karakter, konstituen, dan agenda masing-masing organisasi.</p>`
    },
    {
      no: "10.3",
      title: "Organisasi Masyarakat Sipil sebagai Pemangku Kepentingan",
      body: `<p>Kedudukan OMS dalam teori pemangku kepentingan bersifat khas karena umumnya OMS tidak memiliki hubungan transaksional langsung dengan perusahaan sebagaimana karyawan, konsumen, atau pemasok. Kepentingan OMS terhadap korporasi lazimnya bersifat tidak langsung, yaitu sebagai wakil atau penyalur kepentingan pihak lain yang terdampak aktivitas perusahaan (Crane dan Matten, 2019). Pihak yang diwakili tersebut dapat berupa individu atau kelompok yang lemah posisinya, misalnya buruh di rantai pasok global atau masyarakat sekitar lokasi tambang, dan dapat pula berupa kepentingan yang tidak mampu bersuara sama sekali, misalnya lingkungan hidup, satwa, dan generasi mendatang. Dengan demikian, OMS berfungsi sebagai saluran artikulasi bagi klaim moral yang tanpa kehadiran mereka mungkin tidak pernah sampai ke meja manajemen.</p>
      <p>Sifat perwakilan tersebut menimbulkan pertanyaan mengenai legitimasi klaim OMS terhadap perusahaan. Di satu sisi, OMS dapat dipandang memiliki legitimasi moral karena memperjuangkan pihak yang dirugikan; di sisi lain, perusahaan dapat mempertanyakan sejauh mana OMS benar-benar mewakili pihak yang diklaimnya, mengingat OMS tidak dipilih melalui mekanisme elektoral. Apabila dianalisis dengan kerangka saliensi pemangku kepentingan yang menimbang kekuasaan, legitimasi, dan urgensi (Mitchell, Agle dan Wood, 1997), banyak OMS pada awalnya lemah dalam kekuasaan formal, namun mampu membangun kekuasaan de facto melalui mobilisasi opini publik, media, dan konsumen. Kampanye yang berhasil dapat mengubah OMS dari pemangku kepentingan laten menjadi pemangku kepentingan definitif yang tuntutannya mendesak untuk direspons.</p>
      <p>Implikasi manajerialnya, perusahaan perlu memasukkan OMS ke dalam pemetaan pemangku kepentingan secara sistematis, bukan hanya ketika konflik telah meletus. Manajer sebaiknya mengidentifikasi OMS mana yang relevan dengan isu material perusahaan, memahami basis legitimasi dan konstituennya, serta membangun kanal dialog sejak dini. Pengalaman berbagai perusahaan multinasional menunjukkan bahwa biaya mengabaikan OMS jauh lebih besar daripada biaya melibatkan mereka, karena kampanye negatif dapat merusak reputasi, memicu boikot, dan mengundang regulasi yang lebih ketat. Dengan demikian, hubungan dengan masyarakat sipil selayaknya dikelola sebagai bagian dari manajemen risiko strategis sekaligus sumber pembelajaran etis bagi organisasi.</p>`
    },
    {
      no: "10.4",
      title: "Isu Etis dalam Hubungan antara Bisnis dan Organisasi Masyarakat Sipil",
      body: `<p>Hubungan antara bisnis dan OMS sarat dengan persoalan etis dari dua arah. Dari arah perusahaan, isu utamanya adalah sejauh mana perusahaan mengakui dan menghormati kepentingan yang disuarakan OMS. Dari arah OMS, isu utamanya adalah sejauh mana taktik yang digunakan untuk menekan perusahaan dapat dibenarkan secara moral, serta kepada siapa OMS sendiri mempertanggungjawabkan tindakannya (Crane dan Matten, 2019). Kedua arah tersebut dibahas berturut-turut pada sub-sub-bab berikut.</p>
      <h5>10.4.1 Pengakuan terhadap Kepentingan Organisasi Masyarakat Sipil</h5>
      <p>Persoalan pertama adalah pengakuan (<em>recognition</em>). Perusahaan kerap menolak berdialog dengan OMS dengan alasan organisasi tersebut bukan pemangku kepentingan yang sah karena tidak memiliki hubungan kontraktual dengan perusahaan. Penolakan semacam ini berisiko secara etis maupun strategis, sebab klaim yang dibawa OMS umumnya berakar pada kepentingan pihak yang nyata terdampak. Namun, pengakuan tanpa seleksi juga tidak realistis karena jumlah OMS sangat besar dan tuntutannya dapat saling bertentangan. Oleh karena itu, perusahaan perlu mengembangkan kriteria keterlibatan yang adil, misalnya menimbang keterwakilan konstituen, kualitas bukti yang diajukan, dan kesediaan berdialog secara konstruktif, sehingga keputusan untuk melibatkan atau tidak melibatkan suatu OMS dapat dipertanggungjawabkan.</p>
      <h5>10.4.2 Taktik Organisasi Masyarakat Sipil</h5>
      <p>Taktik OMS dalam memengaruhi perusahaan dapat dibedakan menjadi aksi tidak langsung dan aksi langsung. Aksi tidak langsung ditujukan untuk mengubah opini dan kebijakan melalui pihak lain, misalnya riset dan publikasi laporan, lobi kepada pembuat kebijakan, kampanye media dan surat terbuka, serta pemeringkatan kinerja sosial perusahaan. Aksi langsung ditujukan kepada perusahaan itu sendiri, misalnya demonstrasi, boikot konsumen, okupasi lokasi, aktivisme pemegang saham dalam rapat umum, hingga sabotase (Crane dan Matten, 2019). Secara etis, taktik tanpa kekerasan yang berbasis informasi akurat umumnya mudah dibenarkan sebagai bagian dari kebebasan berekspresi, sedangkan taktik yang merusak properti, membahayakan keselamatan, atau menyebarkan informasi menyesatkan sulit dibenarkan meskipun tujuannya mulia, karena melanggar prinsip bahwa cara yang buruk tidak dapat disucikan oleh tujuan yang baik.</p>
      <h5>10.4.3 Boikot Konsumen</h5>
      <p>Boikot merupakan taktik aksi langsung yang paling banyak dikaji karena memanfaatkan kekuatan pasar itu sendiri untuk menghukum perusahaan. Boikot dapat dipahami sebagai upaya terorganisasi mengajak konsumen menahan pembelian produk tertentu guna memaksa perubahan perilaku perusahaan sasaran. Berdasarkan tujuannya, boikot dapat dibedakan ke dalam beberapa jenis yang dirangkum pada Tabel 10.1.</p>
      <table class="bk-table"><caption>Tabel 10.1 Jenis Boikot Berdasarkan Tujuannya</caption>
      <thead><tr><th>Jenis Boikot</th><th>Tujuan Utama</th><th>Ilustrasi</th></tr></thead>
      <tbody>
      <tr><td>Boikot instrumental</td><td>Memaksa perusahaan mengubah kebijakan atau praktik tertentu yang spesifik</td><td>Boikot terhadap merek pakaian untuk menuntut perbaikan upah buruh di pabrik pemasok</td></tr>
      <tr><td>Boikot katalitik atau ekspresif</td><td>Menarik perhatian publik terhadap suatu isu dan menyatakan kemarahan moral</td><td>Seruan boikot produk tertentu di media sosial sebagai pernyataan sikap atas isu politik atau kemanusiaan</td></tr>
      <tr><td>Boikot punitif</td><td>Menghukum perusahaan atas kesalahan yang telah terjadi tanpa tuntutan perubahan yang spesifik</td><td>Penolakan berkelanjutan terhadap merek yang dianggap bertanggung jawab atas bencana lingkungan</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019) dan Friedman (1999)</td></tr></tfoot></table>
      <p>Efektivitas boikot bergantung pada beberapa kondisi, yaitu tingkat kesadaran publik atas isu, ketersediaan produk substitusi yang mudah dijangkau, visibilitas merek sasaran, dan liputan media yang berkelanjutan. Namun, boikot juga menyimpan persoalan etis tersendiri. Pertama, sasaran boikot dapat keliru atau terlalu luas sehingga menghukum pihak yang tidak bersalah, misalnya pekerja dan pemasok kecil yang kehilangan pendapatan ketika penjualan merosot. Kedua, boikot yang digerakkan oleh informasi yang tidak akurat dapat menimbulkan kerugian yang tidak proporsional. Di Indonesia, gelombang boikot terhadap produk yang diasosiasikan dengan konflik internasional pada tahun 2023 sampai 2024 menunjukkan kedua sisi tersebut, karena selain menekan merek global, dampaknya turut dirasakan oleh karyawan lokal dan pewaralaba domestik yang justru berkewarganegaraan Indonesia. Oleh karena itu, baik penggagas boikot maupun manajer perusahaan sasaran perlu menimbang dampak ikutan tersebut dalam merumuskan respons yang etis.</p>
      <h5>10.4.4 Akuntabilitas Organisasi Masyarakat Sipil</h5>
      <p>Isu etis berikutnya justru menyasar OMS itu sendiri. Ketika OMS memperoleh kekuasaan besar dalam membentuk opini publik, muncul pertanyaan mengenai kepada siapa mereka bertanggung jawab, mengingat OMS tidak dipilih oleh publik dan tidak diawasi pasar sebagaimana perusahaan. Crane dan Matten (2019) mencatat bahwa akuntabilitas OMS setidaknya harus diarahkan kepada donor yang mendanai, anggota yang menjadi basis legitimasi, serta penerima manfaat yang diatasnamakan. Kritik terhadap OMS umumnya mencakup eksagerasi fakta demi dramatisasi kampanye, klaim keterwakilan yang lemah, ketergantungan pada agenda donor asing, dan tata kelola internal yang tidak transparan. Kasus klasik kampanye penenggelaman anjungan minyak Brent Spar pada tahun 1995 memperlihatkan bahwa klaim ilmiah organisasi kampanye pun dapat keliru, sehingga kredibilitas menjadi taruhan utama OMS. Dengan demikian, standar etika yang dituntut OMS dari perusahaan, seperti transparansi dan kejujuran informasi, selayaknya juga diterapkan pada diri mereka sendiri.</p>`
    },
    {
      no: "10.5",
      title: "Globalisasi dan Masyarakat Sipil",
      body: `<p>Globalisasi mengubah secara mendasar lanskap hubungan antara bisnis dan masyarakat sipil. Ketika korporasi beroperasi lintas negara, dampak sosial dan lingkungannya turut melintasi batas yurisdiksi, sementara kapasitas pemerintah nasional untuk mengawasinya melemah. Kekosongan tata kelola tersebut sebagian diisi oleh masyarakat sipil global, yaitu jaringan OMS lintas negara yang memantau, mengungkap, dan menekan praktik korporasi di mana pun praktik itu terjadi (Crane dan Matten, 2019). Kampanye terhadap kondisi kerja di pabrik pemasok Nike pada era 1990-an menjadi contoh awal bagaimana OMS di negara maju mampu mengangkat persoalan buruh di negara berkembang menjadi krisis reputasi global yang memaksa perubahan kebijakan rantai pasok.</p>
      <p>Bagi perusahaan multinasional, globalisasi berarti keharusan berhadapan dengan OMS luar negeri yang karakternya dapat sangat berbeda dari organisasi di negara asal. Perbedaan tersebut mencakup agenda, gaya advokasi, dan basis legitimasi; OMS di negara maju cenderung menekankan isu lingkungan global dan hak asasi manusia, sedangkan OMS di negara berkembang kerap memprioritaskan penghidupan, lahan, dan keadilan distributif bagi komunitas lokal. Ketegangan antara agenda utara dan selatan ini menuntut kepekaan manajer agar tidak menganggap suara satu OMS internasional otomatis mewakili aspirasi masyarakat lokal di lokasi operasi. Selain itu, perkembangan teknologi digital dan media sosial mempercepat siklus kampanye secara dramatis, sehingga isu lokal dapat menjadi viral dan mendunia dalam hitungan jam tanpa memerlukan struktur organisasi formal.</p>
      <p>Konteks Indonesia memberikan ilustrasi yang kuat mengenai dinamika ini. Kampanye Greenpeace terhadap industri minyak sawit dan pulp nasional sepanjang dekade 2010-an, termasuk kampanye kreatif yang menyasar merek global pembeli minyak sawit, berhasil menekan perusahaan seperti Golden Agri-Resources dan Asia Pulp and Paper untuk mengadopsi kebijakan tanpa deforestasi dalam rantai pasoknya. Tekanan tersebut tidak datang dari regulator Indonesia, melainkan dari jaringan masyarakat sipil global yang memengaruhi pembeli internasional. Dari kasus ini dapat disimpulkan bahwa dalam ekonomi global, lisensi sosial perusahaan tidak lagi ditentukan semata oleh kepatuhan hukum domestik, melainkan juga oleh penilaian masyarakat sipil transnasional. Implikasi manajerialnya, perusahaan berorientasi ekspor perlu memantau standar dan ekspektasi OMS global sedini mungkin karena ekspektasi tersebut sering mendahului regulasi formal.</p>`
    },
    {
      no: "10.6",
      title: "Kewargaan Korporat, Kolaborasi Bisnis dengan OMS, dan Regulasi Sipil",
      body: `<p>Perkembangan penting dalam hubungan bisnis dan masyarakat sipil adalah pergeseran dari pola konfrontasi menuju pola kolaborasi. Semula perusahaan memandang OMS sebagai ancaman dan OMS memandang perusahaan sebagai lawan, namun kedua pihak lambat laun menyadari adanya saling ketergantungan; perusahaan membutuhkan legitimasi, pengetahuan lokal, dan kredibilitas yang dimiliki OMS, sedangkan OMS membutuhkan sumber daya, jangkauan pasar, dan kapasitas implementasi yang dimiliki perusahaan (Crane dan Matten, 2019). Pergeseran ini sejalan dengan perspektif kewargaan korporat yang menempatkan perusahaan sebagai aktor yang turut mengelola hak-hak warga bersama negara dan masyarakat sipil.</p>
      <h5>10.6.1 Bentuk Kolaborasi Bisnis dengan Organisasi Masyarakat Sipil</h5>
      <p>Kolaborasi antara bisnis dan OMS berlangsung dalam spektrum intensitas yang bertingkat. Bentuk yang paling sederhana adalah filantropi berupa donasi dana atau barang kepada OMS. Tingkat berikutnya mencakup sponsor kegiatan, pemasaran berbasis kausa (<em>cause-related marketing</em>) yang mengaitkan penjualan produk dengan sumbangan, serta program kesukarelawanan karyawan. Bentuk yang paling intensif adalah kemitraan strategis atau aliansi sosial, yaitu kerja sama jangka panjang dengan tujuan, sumber daya, dan pengambilan keputusan bersama, misalnya kemitraan perusahaan dengan OMS konservasi untuk merancang rantai pasok lestari. Ringkasan bentuk kolaborasi tersebut disajikan pada Tabel 10.2.</p>
      <table class="bk-table"><caption>Tabel 10.2 Spektrum Kolaborasi Bisnis dengan Organisasi Masyarakat Sipil</caption>
      <thead><tr><th>Bentuk</th><th>Karakteristik</th><th>Contoh</th></tr></thead>
      <tbody>
      <tr><td>Filantropi</td><td>Transfer sumber daya satu arah, keterlibatan rendah</td><td>Donasi perusahaan kepada lembaga kemanusiaan saat bencana</td></tr>
      <tr><td>Sponsor dan pemasaran berbasis kausa</td><td>Pertukaran manfaat, horizon jangka pendek sampai menengah</td><td>Sebagian hasil penjualan produk disumbangkan untuk program pendidikan</td></tr>
      <tr><td>Kesukarelawanan karyawan</td><td>Kontribusi waktu dan keahlian karyawan kepada program OMS</td><td>Karyawan bank menjadi mentor literasi keuangan bagi UMKM binaan OMS</td></tr>
      <tr><td>Dialog pemangku kepentingan</td><td>Pertukaran informasi dan konsultasi kebijakan perusahaan</td><td>Forum konsultasi perusahaan tambang dengan OMS lingkungan dan masyarakat adat</td></tr>
      <tr><td>Kemitraan strategis</td><td>Tujuan bersama, sumber daya bersama, tata kelola bersama, jangka panjang</td><td>Kemitraan produsen barang konsumsi dengan OMS konservasi untuk sertifikasi bahan baku lestari</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>
      <p>Meskipun menjanjikan, kolaborasi menyimpan sejumlah risiko etis yang perlu diantisipasi kedua pihak. Bagi OMS, risiko terbesar adalah kooptasi, yaitu hilangnya independensi dan daya kritis karena ketergantungan finansial pada mitra korporat, yang pada gilirannya menggerus kredibilitas di mata konstituen. Bagi perusahaan, kemitraan yang bersifat kosmetik dapat dituduh sebagai <em>greenwashing</em>, yaitu penggunaan citra OMS untuk menutupi praktik inti yang bermasalah. Risiko lain mencakup ketimpangan kekuasaan dalam tata kelola kemitraan, benturan budaya organisasi antara logika bisnis dan logika aktivisme, serta perbedaan horizon waktu. Oleh karena itu, kemitraan yang sehat memerlukan kejelasan tujuan, pembagian peran yang seimbang, mekanisme keluar yang disepakati, dan keberanian kedua pihak untuk saling mengkritik secara terbuka.</p>
      <h5>10.6.2 Regulasi Sipil</h5>
      <p>Kontribusi masyarakat sipil yang paling jauh jangkauannya terhadap tata kelola bisnis adalah regulasi sipil (<em>civil regulation</em>), yaitu penetapan standar perilaku korporasi oleh aktor masyarakat sipil di luar mekanisme hukum negara (Vogel, 2010). Mekanismenya berjalan melalui standar sukarela, sertifikasi oleh pihak ketiga, pemantauan kepatuhan, dan sanksi berbasis pasar berupa hilangnya akses kepada pembeli atau konsumen yang mensyaratkan sertifikasi. Contoh yang mapan antara lain Forest Stewardship Council untuk produk kayu, Marine Stewardship Council untuk perikanan, sertifikasi Fairtrade untuk komoditas pertanian, dan Roundtable on Sustainable Palm Oil (RSPO) untuk minyak sawit yang sangat relevan bagi Indonesia sebagai produsen terbesar dunia. Dalam skema semacam ini OMS berperan sekaligus sebagai perumus standar, pengawas, dan sumber legitimasi, sehingga menjalankan fungsi yang menyerupai regulator tanpa mandat negara.</p>
      <p>Regulasi sipil memiliki kekuatan sekaligus keterbatasan. Kekuatannya terletak pada kelenturan lintas batas negara dan kecepatan adaptasi terhadap isu baru dibandingkan regulasi formal. Keterbatasannya mencakup sifat kepesertaan yang sukarela sehingga perusahaan yang paling bermasalah justru dapat memilih tidak ikut, biaya sertifikasi yang membebani produsen kecil seperti petani sawit swadaya di Indonesia, serta persaingan antarstandar yang membingungkan konsumen. Dari sudut pandang kewargaan korporat, regulasi sipil menunjukkan bahwa masyarakat sipil telah menjadi arena tempat hak dan kewajiban warga dinegosiasikan ulang bersama perusahaan, dan manajer perlu memutuskan secara sadar posisi perusahaannya dalam arena tersebut, apakah sebagai peserta pasif, pengadopsi awal, atau turut membentuk standar.</p>`
    },
    {
      no: "10.7",
      title: "Masyarakat Sipil, Bisnis, dan Keberlanjutan",
      body: `<p>Dalam agenda keberlanjutan, masyarakat sipil memainkan setidaknya tiga peran yang saling melengkapi. Pertama, peran pengawas (<em>watchdog</em>) yang memantau dan mengungkap praktik perusahaan yang merusak lingkungan atau melanggar hak sosial, sebagaimana dilakukan WALHI dan Auriga di Indonesia terhadap industri ekstraktif. Kedua, peran advokasi yang mendorong perubahan kebijakan publik dan standar industri ke arah yang lebih lestari. Ketiga, peran mitra solusi yang bekerja bersama perusahaan dan pemerintah merancang praktik berkelanjutan di lapangan, misalnya pendampingan petani untuk memenuhi standar sertifikasi (Crane dan Matten, 2019). Kombinasi ketiga peran tersebut menjadikan masyarakat sipil sebagai penyeimbang yang menjaga agar wacana keberlanjutan tidak direduksi menjadi retorika pemasaran belaka.</p>
      <p>Kompleksitas persoalan keberlanjutan, sebagaimana tercermin dalam Tujuan Pembangunan Berkelanjutan (SDGs), melampaui kapasitas satu sektor mana pun sehingga mendorong lahirnya kemitraan tiga sektor antara pemerintah, bisnis, dan masyarakat sipil. Dalam kemitraan semacam ini, setiap sektor menyumbangkan keunggulan khasnya; pemerintah menyediakan kerangka kebijakan, bisnis menyediakan modal dan kapasitas operasional, sedangkan OMS menyediakan kepercayaan komunitas dan pengetahuan lokal. Di Indonesia, pola tersebut terlihat pada koperasi kopi Gayo bersertifikat Fairtrade yang menghubungkan petani, eksportir, dan lembaga sertifikasi internasional, serta pada kolaborasi pengelolaan sampah antara pemerintah daerah, produsen barang konsumsi, dan wirausaha sosial seperti Waste4Change. Fenomena wirausaha sosial itu sendiri menunjukkan kaburnya batas antarsektor, karena organisasi hibrida semacam ini mengejar misi sosial masyarakat sipil dengan instrumen pasar.</p>
      <p>Bagi manajer, pelajaran utamanya adalah bahwa keberlanjutan tidak dapat dicapai perusahaan secara sepihak. Perusahaan yang serius dengan agenda keberlanjutan perlu memandang OMS bukan sebagai hambatan hubungan masyarakat, melainkan sebagai sumber kecerdasan sosial yang membantu perusahaan mengenali risiko dan peluang lebih awal. Selain itu, keterlibatan masyarakat sipil dalam pemantauan kinerja keberlanjutan meningkatkan kredibilitas laporan perusahaan di mata investor dan konsumen. Dengan demikian, kapabilitas membangun dan memelihara hubungan yang jujur dengan masyarakat sipil selayaknya diperlakukan sebagai kompetensi strategis, setara dengan kapabilitas operasional dan finansial.</p>`
    },
    {
      no: "10.8",
      title: "Rangkuman",
      body: `<p>Bab ini menempatkan masyarakat sipil sebagai sektor ketiga yang melengkapi negara dan pasar dalam membentuk perilaku etis korporasi. Organisasi masyarakat sipil merupakan organisasi sukarela dan nirlaba yang memperjuangkan kepentingan anggotanya sendiri sebagai kelompok seksional atau memperjuangkan kausa publik sebagai kelompok promosional. Sebagai pemangku kepentingan, OMS memiliki kedudukan khas karena kepentingannya bersifat tidak langsung, yaitu mewakili pihak lain yang terdampak aktivitas perusahaan, termasuk lingkungan hidup dan generasi mendatang yang tidak mampu bersuara sendiri. Kekhasan tersebut menuntut perusahaan menilai legitimasi klaim OMS secara cermat sekaligus membuka ruang dialog yang tulus.</p>
      <p>Isu etis dalam hubungan bisnis dan OMS berjalan dua arah. Perusahaan dituntut mengakui kepentingan yang disuarakan OMS, sementara OMS dituntut menggunakan taktik yang jujur dan proporsional serta menjaga akuntabilitasnya kepada donor, anggota, dan penerima manfaat. Boikot sebagai taktik aksi langsung dapat bersifat instrumental, katalitik, atau punitif, dan efektivitasnya bergantung pada kesadaran publik, substitusi produk, dan liputan media, namun boikot juga dapat merugikan pihak yang tidak bersalah. Globalisasi memperluas jangkauan masyarakat sipil menjadi kekuatan transnasional yang mengisi kekosongan tata kelola, sebagaimana tampak pada kampanye internasional terhadap industri sawit dan pulp Indonesia yang mendorong kebijakan tanpa deforestasi.</p>
      <p>Perkembangan mutakhir memperlihatkan pergeseran dari konfrontasi menuju kolaborasi melalui spektrum kemitraan yang berjenjang dari filantropi hingga aliansi strategis, dengan risiko kooptasi dan <em>greenwashing</em> yang harus dikelola kedua pihak. Melalui regulasi sipil seperti FSC, Fairtrade, dan RSPO, masyarakat sipil bahkan menjalankan fungsi penetapan standar yang menyerupai regulator. Pada akhirnya, dalam agenda keberlanjutan, masyarakat sipil berperan sebagai pengawas, advokat, dan mitra solusi, sehingga kemampuan perusahaan membangun hubungan yang sehat dengan masyarakat sipil merupakan kompetensi strategis bagi manajer masa kini.</p>`
    },
    {
      no: "10.9",
      title: "Daftar Pustaka",
      body: `<p>Crane, A., Matten, D., Glozer, S. dan Spence, L. J. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford University Press.</p>
      <p>Friedman, M. (1999). <em>Consumer Boycotts: Effecting Change through the Marketplace and the Media</em>. Edisi ke-1. Routledge.</p>
      <p>Mitchell, R. K., Agle, B. R. dan Wood, D. J. (1997). Toward a Theory of Stakeholder Identification and Salience. <em>Academy of Management Review</em>, 22(4), 853-886.</p>
      <p>Salamon, L. M. dan Anheier, H. K. (1997). <em>Defining the Nonprofit Sector: A Cross-National Analysis</em>. Edisi ke-1. Manchester University Press.</p>
      <p>Vogel, D. (2010). The Private Regulation of Global Corporate Conduct. <em>Business and Society</em>, 49(1), 68-87.</p>`
    }
  ]
};
