window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[5] = {
  bab: 5,
  judul: "BAB 5 MANAJEMEN ETIKA BISNIS",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 5",
  lo: [
    "LO1 Menjelaskan pengertian manajemen etika bisnis serta mengidentifikasi komponen-komponen utamanya dalam praktik perusahaan.",
    "LO2 Menganalisis motivasi perusahaan dalam mengelola etika serta membedakan orientasi kepatuhan dan orientasi nilai dalam program etika.",
    "LO3 Menguraikan jenis, isi, dan faktor penentu efektivitas kode etik, termasuk tantangan penerapan kode etik global lintas budaya.",
    "LO4 Menerapkan kerangka penilaian arti penting pemangku kepentingan serta merancang bentuk keterlibatan dan kemitraan pemangku kepentingan.",
    "LO5 Menjelaskan perkembangan akuntansi, audit, dan pelaporan sosial serta mengevaluasi kriteria kualitas pelaporan kinerja etis.",
    "LO6 Membandingkan pendekatan formal dan informal dalam mengorganisasikan manajemen etika bisnis, termasuk peran budaya organisasi dan kepemimpinan etis."
  ],
  sections: [
    {
      no: "5.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab-bab sebelumnya telah membahas landasan konseptual mengenai moralitas dalam bisnis, teori etika normatif, serta proses pengambilan keputusan etis pada tingkat individu. Bab ini beralih dari tataran konseptual menuju tataran praktik manajerial, yaitu bagaimana perusahaan secara sengaja dan sistematis mengelola persoalan etika melalui kebijakan, program, dan struktur organisasi. Pergeseran ini penting karena keputusan etis di dalam organisasi tidak hanya ditentukan oleh karakter moral individu, melainkan juga oleh konteks organisasi tempat individu tersebut bekerja (Crane dan Matten, 2019).</p>
<p>Setelah mengikuti sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p>Pertama, menjelaskan pengertian dan komponen manajemen etika bisnis. Kedua, menganalisis alasan perusahaan mengelola etika serta membedakan orientasi kepatuhan dan orientasi nilai. Ketiga, mengevaluasi peran kode etik sebagai instrumen penetapan standar perilaku. Keempat, menerapkan kerangka analisis arti penting pemangku kepentingan dan merancang keterlibatan pemangku kepentingan. Kelima, menilai praktik akuntansi dan pelaporan sosial. Keenam, membandingkan pendekatan formal dan informal dalam mengorganisasikan etika bisnis, termasuk peran budaya organisasi dan kepemimpinan etis.</p>`
    },
    {
      no: "5.2",
      title: "Konsep dan Komponen Manajemen Etika Bisnis",
      body: `<p>Perkembangan skandal korporasi, tekanan regulasi, serta meningkatnya perhatian publik terhadap tanggung jawab perusahaan telah mendorong organisasi untuk tidak lagi memperlakukan etika sebagai urusan pribadi karyawan semata. Etika kini dikelola sebagaimana fungsi manajemen lainnya, dengan kebijakan, anggaran, struktur, dan pengukuran kinerja tersendiri. Fenomena inilah yang oleh literatur disebut sebagai manajemen etika bisnis atau <em>business ethics management</em>.</p>
<p>Menurut Crane dan Matten (2019), manajemen etika bisnis merupakan upaya langsung untuk mengelola isu atau masalah etika melalui kebijakan, praktik, dan program tertentu, baik secara formal maupun informal. Definisi tersebut mengandung dua unsur penting. Unsur pertama adalah kesengajaan, artinya perusahaan secara sadar merancang intervensi untuk memengaruhi perilaku etis, bukan sekadar berharap karyawan berperilaku baik. Unsur kedua adalah keragaman bentuk, artinya pengelolaan etika dapat berwujud instrumen formal seperti kode etik tertulis, maupun mekanisme informal seperti keteladanan pemimpin dan norma budaya organisasi. Dari definisi tersebut dapat disimpulkan bahwa manajemen etika bisnis adalah keseluruhan usaha terencana organisasi untuk menetapkan, mengomunikasikan, memantau, dan menegakkan standar perilaku etis di lingkungan bisnisnya.</p>
<p>Crane dan Matten (2019) mengidentifikasi sejumlah komponen utama manajemen etika bisnis yang lazim dijumpai pada perusahaan modern, yaitu:</p>
<p>1) Pernyataan misi dan nilai (<em>mission and values statements</em>) yang mengartikulasikan tujuan serta keyakinan dasar organisasi; 2) kode etik (<em>codes of ethics</em>) yang menetapkan standar perilaku; 3) saluran pelaporan dan konsultasi (<em>reporting and advice channels</em>) seperti <em>whistleblowing hotline</em> untuk mengungkap pelanggaran; 4) manajer, komite, dan konsultan etika yang bertanggung jawab atas program etika; 5) analisis dan manajemen risiko etika; 6) pendidikan dan pelatihan etika bagi karyawan; 7) konsultasi, dialog, dan program kemitraan dengan pemangku kepentingan; serta 8) audit, akuntansi, dan pelaporan sosial untuk mengukur serta mengomunikasikan kinerja etis.</p>
<table class="bk-table">
<caption>Tabel 5.1 Komponen Manajemen Etika Bisnis dan Fungsinya</caption>
<thead><tr><th>Komponen</th><th>Fungsi Utama</th><th>Contoh Praktik</th></tr></thead>
<tbody>
<tr><td>Pernyataan misi dan nilai</td><td>Mengartikulasikan arah dan keyakinan dasar organisasi</td><td>Nilai inti AKHLAK pada BUMN Indonesia</td></tr>
<tr><td>Kode etik</td><td>Menetapkan standar perilaku yang diharapkan</td><td>Pedoman perilaku (<em>code of conduct</em>) perusahaan</td></tr>
<tr><td>Saluran pelaporan dan konsultasi</td><td>Mendeteksi pelanggaran dan memberi nasihat etis</td><td><em>Whistleblowing system</em> daring</td></tr>
<tr><td>Manajer dan komite etika</td><td>Mengoordinasikan dan mengawasi program etika</td><td><em>Chief ethics and compliance officer</em></td></tr>
<tr><td>Manajemen risiko etika</td><td>Mengidentifikasi dan memitigasi paparan risiko etis</td><td>Penilaian risiko korupsi pada rantai pasok</td></tr>
<tr><td>Pendidikan dan pelatihan etika</td><td>Membangun kesadaran dan kompetensi moral karyawan</td><td>Pelatihan antisuap tahunan</td></tr>
<tr><td>Dialog dan kemitraan pemangku kepentingan</td><td>Menyerap aspirasi dan membangun legitimasi</td><td>Forum konsultasi masyarakat sekitar tambang</td></tr>
<tr><td>Audit dan pelaporan sosial</td><td>Mengukur dan mengomunikasikan kinerja etis</td><td>Laporan keberlanjutan berbasis GRI</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
</table>
<p>Implikasi manajerial dari kerangka komponen tersebut adalah bahwa program etika yang efektif bersifat sistemik, bukan parsial. Perusahaan yang hanya menerbitkan kode etik tanpa pelatihan, saluran pelaporan, dan penegakan yang konsisten cenderung menghasilkan kepatuhan simbolis semata. Oleh karena itu, manajer perlu memandang komponen-komponen tersebut sebagai satu arsitektur yang saling menguatkan, mulai dari penetapan standar, sosialisasi, pemantauan, hingga evaluasi kinerja etis.</p>`
    },
    {
      no: "5.3",
      title: "Motivasi Pengelolaan Etika serta Orientasi Kepatuhan dan Nilai",
      body: `<p>Pertanyaan mendasar sebelum merancang program etika adalah alasan perusahaan bersedia mengalokasikan sumber daya untuk mengelola etika. Crane dan Matten (2019) menjelaskan bahwa motivasi tersebut beragam, mulai dari kepentingan melindungi serta meningkatkan reputasi perusahaan, memenuhi tuntutan regulasi dan menghindari sanksi hukum, mengelola risiko bisnis, memenuhi ekspektasi pemangku kepentingan seperti investor dan konsumen, hingga komitmen moral yang tulus dari pemilik atau manajemen puncak. Dalam praktiknya, motivasi instrumental dan motivasi moral sering berjalan berdampingan sehingga sulit dipisahkan secara tegas.</p>
<p>Perbedaan motivasi tersebut juga tercermin dalam variasi antarnegara. Di Amerika Serikat, perkembangan program etika sangat dipengaruhi oleh kerangka hukum seperti <em>Federal Sentencing Guidelines</em> dan <em>Sarbanes-Oxley Act</em> yang memberikan keringanan sanksi bagi perusahaan yang memiliki program kepatuhan efektif, sehingga pendekatannya cenderung legalistik dan terformalisasi. Di Eropa, pengelolaan etika lebih banyak diwarnai oleh dialog dengan pemangku kepentingan, konsensus sosial, dan regulasi negara, sehingga instrumen formal seperti kode etik berkembang lebih lambat meskipun kini semakin meluas (Crane dan Matten, 2019). Kesadaran atas perbedaan konteks kelembagaan ini penting bagi perusahaan multinasional yang harus merancang program etika lintas yurisdiksi.</p>
<p>Kerangka analitis yang paling berpengaruh untuk memetakan pendekatan program etika adalah pembedaan antara orientasi kepatuhan dan orientasi integritas yang dikemukakan oleh Paine (1994). Orientasi kepatuhan (<em>compliance orientation</em>) menekankan pencegahan, pendeteksian, dan penghukuman pelanggaran terhadap hukum serta peraturan. Standar perilakunya bersumber dari hukum, metodenya berupa pengawasan dan pengendalian, dan asumsi perilakunya memandang manusia sebagai makhluk yang digerakkan oleh kepentingan diri. Sebaliknya, orientasi integritas atau orientasi nilai (<em>values orientation</em>) menekankan pembentukan komitmen terhadap nilai-nilai bersama, memberi ruang bagi pertimbangan moral karyawan, dan memandang manusia sebagai makhluk sosial yang dibimbing oleh nilai serta ideal tertentu. Dari perbandingan tersebut dapat disimpulkan bahwa orientasi kepatuhan berupaya mengendalikan perilaku dari luar, sedangkan orientasi nilai berupaya menumbuhkan perilaku etis dari dalam.</p>
<table class="bk-table">
<caption>Tabel 5.2 Perbandingan Orientasi Kepatuhan dan Orientasi Nilai dalam Program Etika</caption>
<thead><tr><th>Dimensi</th><th>Orientasi Kepatuhan</th><th>Orientasi Nilai (Integritas)</th></tr></thead>
<tbody>
<tr><td>Tujuan utama</td><td>Mencegah dan menghukum pelanggaran hukum</td><td>Memampukan perilaku bertanggung jawab berbasis nilai</td></tr>
<tr><td>Sumber standar</td><td>Hukum dan peraturan eksternal</td><td>Nilai, aspirasi, dan komitmen organisasi</td></tr>
<tr><td>Metode dominan</td><td>Audit, pengawasan, sanksi</td><td>Kepemimpinan, pendidikan, dialog, keteladanan</td></tr>
<tr><td>Asumsi perilaku manusia</td><td>Digerakkan kepentingan diri</td><td>Dibimbing nilai dan ideal sosial</td></tr>
<tr><td>Ukuran keberhasilan</td><td>Tidak adanya pelanggaran</td><td>Terinternalisasinya nilai dalam keputusan sehari-hari</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Paine (1994) serta Crane dan Matten (2019)</td></tr></tfoot>
</table>
<p>Implikasi manajerialnya, kedua orientasi tersebut sebaiknya dipandang saling melengkapi, bukan saling meniadakan. Program yang murni berorientasi kepatuhan berisiko menghasilkan mentalitas legalistik, yaitu karyawan hanya menghindari hal yang dilarang secara eksplisit tanpa mempertimbangkan kepatutan moral. Di sisi lain, program yang hanya mengandalkan nilai tanpa mekanisme pengendalian rentan terhadap penyalahgunaan. Dengan demikian, manajer perlu merancang bauran yang tepat antara pengendalian formal dan pembinaan nilai sesuai profil risiko serta budaya organisasinya.</p>`
    },
    {
      no: "5.4",
      title: "Menetapkan Standar Perilaku Etis melalui Kode Etik",
      body: `<p>Instrumen manajemen etika yang paling banyak digunakan di seluruh dunia adalah kode etik. Kode etik merupakan dokumen sukarela yang berisi pernyataan eksplisit mengenai nilai, prinsip, dan aturan perilaku yang diharapkan dipatuhi oleh anggota organisasi dalam menjalankan aktivitas bisnis (Crane dan Matten, 2019). Kehadiran kode etik menandai upaya perusahaan mengkodifikasi ekspektasi moral yang semula bersifat implisit menjadi standar tertulis yang dapat dikomunikasikan, diajarkan, dan ditegakkan.</p>
<h5>5.4.1 Jenis Kode Etik</h5>
<p>Crane dan Matten (2019) membedakan empat jenis kode etik menurut lingkup penerbitnya, yaitu:</p>
<p>1) Kode etik organisasi (<em>organizational codes</em>) yang diterbitkan oleh satu perusahaan untuk karyawannya sendiri; 2) kode etik profesi (<em>professional codes</em>) yang mengikat anggota profesi tertentu seperti akuntan, dokter, atau advokat; 3) kode etik industri (<em>industry codes</em>) yang disepakati oleh perusahaan-perusahaan dalam satu sektor, misalnya kode pemasaran pada industri makanan; serta 4) kode etik program atau kelompok (<em>programme or group codes</em>) yang diterbitkan oleh koalisi lintas organisasi, seperti <em>United Nations Global Compact</em> dan <em>Ethical Trading Initiative</em>. Keempat jenis tersebut dapat berlaku sekaligus bagi seorang karyawan, misalnya seorang akuntan pada perusahaan tambang terikat pada kode profesinya, kode perusahaannya, dan kode industri pertambangan secara bersamaan.</p>
<h5>5.4.2 Isi dan Efektivitas Kode Etik</h5>
<p>Dari sisi isi, kode etik umumnya memuat kombinasi antara pernyataan nilai dan prinsip umum, ketentuan mengenai isu spesifik seperti benturan kepentingan, suap, penerimaan hadiah, perlindungan informasi rahasia, kesetaraan kesempatan kerja, serta prosedur pelaporan pelanggaran dan sanksi. Penelitian yang dirujuk Crane dan Matten (2019) menunjukkan bahwa isi kode cenderung lebih banyak melindungi kepentingan perusahaan dari perilaku menyimpang karyawan dibandingkan mengatur tanggung jawab perusahaan kepada pemangku kepentingan eksternal. Ketimpangan tersebut menjadi salah satu kritik utama terhadap praktik kode etik.</p>
<p>Persoalan yang lebih mendasar adalah efektivitas kode etik dalam mengubah perilaku. Bukti empiris menunjukkan hasil yang beragam, sebab keberadaan kode etik itu sendiri tidak serta-merta menurunkan pelanggaran. Efektivitas kode sangat ditentukan oleh proses implementasinya, antara lain keterlibatan karyawan dalam penyusunan, sosialisasi dan pelatihan yang berkelanjutan, konsistensi penegakan termasuk terhadap manajemen puncak, keselarasan kode dengan sistem imbalan, serta keteladanan pemimpin (Crane dan Matten, 2019). Kasus manipulasi laporan keuangan pada beberapa perusahaan besar yang sesungguhnya memiliki kode etik komprehensif memperlihatkan bahwa kode yang tidak dihidupi oleh budaya organisasi hanya menjadi dokumen kosmetik. Di Indonesia, kasus korupsi yang menimpa sejumlah badan usaha milik negara yang telah memiliki pedoman perilaku dan sistem pelaporan pelanggaran menegaskan hal serupa, yaitu bahwa dokumen formal tidak menggantikan integritas kepemimpinan dan penegakan yang konsisten.</p>
<h5>5.4.3 Kode Etik Global dan Tantangan Lintas Budaya</h5>
<p>Bagi perusahaan multinasional, penyusunan kode etik global menghadirkan dilema antara standardisasi dan adaptasi lokal. Standar yang seragam menjamin konsistensi dan memudahkan penegakan, namun berpotensi mengabaikan perbedaan norma budaya, misalnya praktik pemberian hadiah yang di suatu budaya dianggap kesopanan sedangkan di budaya lain dianggap suap. Sebaliknya, adaptasi penuh terhadap norma lokal berisiko menjerumuskan perusahaan pada relativisme moral. Crane dan Matten (2019) menyarankan pendekatan yang menetapkan prinsip universal sebagai batas minimum, misalnya larangan korupsi dan penghormatan hak asasi manusia, disertai fleksibilitas penerapan pada isu yang benar-benar bersifat konvensi lokal. Implikasi manajerialnya, perancang kode global perlu melibatkan perwakilan berbagai negara operasi, menyediakan panduan kasus yang kontekstual, dan membangun mekanisme konsultasi bagi karyawan yang menghadapi dilema penerapan.</p>`
    },
    {
      no: "5.5",
      title: "Mengelola Hubungan dengan Pemangku Kepentingan",
      body: `<p>Komponen kedua yang menonjol dalam manajemen etika bisnis adalah pengelolaan hubungan dengan pemangku kepentingan. Sebagaimana dibahas pada sesi sebelumnya, pemangku kepentingan adalah pihak yang memengaruhi atau dipengaruhi oleh pencapaian tujuan perusahaan. Tantangan manajerialnya adalah bahwa perhatian dan sumber daya perusahaan terbatas, sedangkan klaim pemangku kepentingan sangat banyak dan sering saling bertentangan. Oleh karena itu, diperlukan kerangka untuk menilai pihak mana yang menuntut prioritas perhatian manajemen.</p>
<h5>5.5.1 Menilai Arti Penting Pemangku Kepentingan</h5>
<p>Kerangka yang paling banyak dirujuk adalah teori arti penting pemangku kepentingan (<em>stakeholder salience</em>) dari Mitchell, Agle dan Wood (1997). Menurut kerangka tersebut, arti penting suatu pemangku kepentingan di mata manajer ditentukan oleh kepemilikan atas tiga atribut, yaitu:</p>
<p>1) Kekuasaan (<em>power</em>), yakni kemampuan pihak tersebut memaksakan kehendaknya terhadap perusahaan; 2) legitimasi (<em>legitimacy</em>), yakni keabsahan sosial atas klaim atau hubungan pihak tersebut dengan perusahaan; dan 3) urgensi (<em>urgency</em>), yakni tingkat kemendesakan klaim yang menuntut tanggapan segera. Cara menggunakan kerangka ini adalah dengan memetakan setiap pemangku kepentingan menurut jumlah atribut yang dimilikinya. Pihak yang memiliki satu atribut disebut pemangku kepentingan laten dengan prioritas rendah, pihak dengan dua atribut disebut pemangku kepentingan ekspektan dengan prioritas sedang, dan pihak yang memiliki ketiga atribut sekaligus disebut pemangku kepentingan definitif yang menuntut prioritas tertinggi. Pemetaan tersebut bersifat dinamis karena atribut dapat berubah, misalnya kelompok masyarakat yang semula hanya memiliki legitimasi dapat memperoleh kekuasaan ketika didukung media sosial dan organisasi nonpemerintah.</p>
<table class="bk-table">
<caption>Tabel 5.3 Klasifikasi Pemangku Kepentingan Berdasarkan Atribut Arti Penting</caption>
<thead><tr><th>Kelas</th><th>Atribut yang Dimiliki</th><th>Tipe</th><th>Prioritas Manajerial</th></tr></thead>
<tbody>
<tr><td>Laten</td><td>Hanya kekuasaan</td><td>Dorman</td><td>Rendah, dipantau</td></tr>
<tr><td>Laten</td><td>Hanya legitimasi</td><td>Diskresioner</td><td>Rendah, dipantau</td></tr>
<tr><td>Laten</td><td>Hanya urgensi</td><td>Menuntut</td><td>Rendah, dipantau</td></tr>
<tr><td>Ekspektan</td><td>Kekuasaan dan legitimasi</td><td>Dominan</td><td>Sedang, dilibatkan</td></tr>
<tr><td>Ekspektan</td><td>Kekuasaan dan urgensi</td><td>Berbahaya</td><td>Sedang, diwaspadai</td></tr>
<tr><td>Ekspektan</td><td>Legitimasi dan urgensi</td><td>Bergantung</td><td>Sedang, diadvokasi</td></tr>
<tr><td>Definitif</td><td>Ketiga atribut</td><td>Definitif</td><td>Tinggi, ditanggapi segera</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Mitchell, Agle dan Wood (1997)</td></tr></tfoot>
</table>
<h5>5.5.2 Bentuk Keterlibatan dan Kemitraan Pemangku Kepentingan</h5>
<p>Setelah pemetaan dilakukan, perusahaan perlu menentukan bentuk keterlibatan yang sesuai. Crane dan Matten (2019) menggambarkan keterlibatan pemangku kepentingan sebagai suatu spektrum yang bergerak dari sekadar pemberian informasi satu arah, konsultasi dua arah, dialog yang setara, hingga kemitraan formal dalam program bersama. Dialog pemangku kepentingan (<em>stakeholder dialogue</em>) merupakan komunikasi dua arah yang bertujuan saling memahami kepentingan dan mencari solusi bersama, sedangkan kemitraan (<em>partnership</em>) melibatkan kolaborasi jangka panjang antara perusahaan dengan organisasi masyarakat sipil atau pemerintah untuk menangani masalah sosial tertentu. Sebagai contoh di Indonesia, perusahaan pertambangan dan perkebunan besar lazim membentuk forum konsultasi masyarakat serta bermitra dengan lembaga swadaya masyarakat dalam program pengembangan masyarakat di sekitar wilayah operasi, sebagaimana juga didorong oleh kewajiban tanggung jawab sosial dan lingkungan dalam Undang-Undang Perseroan Terbatas Nomor 40 Tahun 2007.</p>
<p>Namun, keterlibatan pemangku kepentingan bukan tanpa masalah. Crane dan Matten (2019) mencatat sejumlah kritik, antara lain risiko kooptasi organisasi masyarakat sipil oleh kepentingan perusahaan, ketimpangan sumber daya dan informasi di antara para pihak, kelelahan konsultasi ketika dialog tidak menghasilkan perubahan nyata, serta penggunaan dialog sebagai alat hubungan masyarakat semata. Implikasi manajerialnya, keterlibatan yang bermakna menuntut kejelasan tujuan, transparansi proses, kesediaan mengubah keputusan berdasarkan masukan, dan mekanisme umpan balik yang dapat diverifikasi. Tanpa syarat tersebut, keterlibatan pemangku kepentingan justru dapat merusak kepercayaan yang hendak dibangun.</p>`
    },
    {
      no: "5.6",
      title: "Menilai Kinerja Etis: Akuntansi, Audit, dan Pelaporan Sosial",
      body: `<p>Prinsip manajemen yang menyatakan bahwa sesuatu yang tidak diukur akan sulit dikelola juga berlaku pada etika bisnis. Oleh karena itu, komponen penting berikutnya adalah penilaian kinerja etis melalui akuntansi sosial. Menurut Crane dan Matten (2019), akuntansi sosial atau <em>social accounting</em> adalah proses ketika organisasi mengukur, mengomunikasikan, dan mempertanggungjawabkan dampak sosial, etis, dan lingkungan dari aktivitasnya kepada para pemangku kepentingan. Istilah lain yang sering digunakan secara bergantian adalah audit sosial, pelaporan keberlanjutan, serta pelaporan nonkeuangan.</p>
<p>Terdapat beberapa alasan perusahaan melakukan akuntansi sosial. Pertama, sebagai wujud akuntabilitas kepada pemangku kepentingan yang memiliki hak untuk mengetahui dampak perusahaan. Kedua, sebagai instrumen manajemen internal untuk mengidentifikasi risiko, menetapkan target perbaikan, dan memantau kemajuan. Ketiga, sebagai sarana membangun kepercayaan dan legitimasi di mata investor, regulator, dan masyarakat. Keempat, sebagai respons terhadap tekanan eksternal, termasuk pemeringkatan investasi berkelanjutan dan regulasi. Di Indonesia, dorongan regulasi tampak nyata melalui Peraturan Otoritas Jasa Keuangan Nomor 51/POJK.03/2017 yang mewajibkan lembaga jasa keuangan, emiten, dan perusahaan publik menyusun laporan keberlanjutan, sehingga pelaporan sosial telah bergeser dari praktik sukarela menjadi kewajiban regulatif.</p>
<p>Dalam praktiknya, perusahaan dapat merujuk pada berbagai standar dan inisiatif internasional, antara lain <em>Global Reporting Initiative</em> (GRI) untuk kerangka pelaporan keberlanjutan, AA1000 untuk prinsip akuntabilitas dan penjaminan, SA8000 untuk standar kondisi kerja, ISO 26000 untuk panduan tanggung jawab sosial, serta kerangka pelaporan terintegrasi yang menggabungkan informasi keuangan dan nonkeuangan. Keragaman standar tersebut di satu sisi memberikan fleksibilitas, namun di sisi lain menimbulkan persoalan keterbandingan antarlaporan sehingga pembaca perlu memahami basis penyusunan setiap laporan.</p>
<p>Karena akuntansi sosial sebagian besar bersifat sukarela dalam hal kedalaman isinya, kualitas laporan menjadi isu sentral. Crane dan Matten (2019), dengan merujuk pada karya Zadek, Pruzan dan Evans (1997), mengemukakan kriteria kualitas akuntansi sosial yang baik, yaitu:</p>
<p>1) Inklusivitas (<em>inclusivity</em>), artinya mencerminkan pandangan seluruh pemangku kepentingan utama, bukan hanya pemegang saham; 2) keterbandingan (<em>comparability</em>), artinya memungkinkan perbandingan antarperiode dan antarorganisasi; 3) kelengkapan (<em>completeness</em>), artinya mencakup seluruh aktivitas perusahaan tanpa memilih hanya area yang menguntungkan citra; 4) evolusi (<em>evolution</em>), artinya menunjukkan komitmen belajar dan perbaikan dari waktu ke waktu; 5) dukungan kebijakan dan sistem manajemen, artinya terhubung dengan proses manajemen nyata; 6) pengungkapan (<em>disclosure</em>) kepada publik; 7) verifikasi eksternal oleh pihak independen; dan 8) perbaikan berkelanjutan (<em>continuous improvement</em>). Kriteria tersebut dapat digunakan manajer maupun analis sebagai daftar uji untuk menilai apakah suatu laporan keberlanjutan merupakan alat akuntabilitas sejati atau sekadar sarana pemolesan citra (<em>greenwashing</em>).</p>
<p>Implikasi manajerialnya, fungsi pelaporan sosial sebaiknya tidak ditempatkan semata pada unit komunikasi korporat, melainkan diintegrasikan dengan sistem pengendalian manajemen, manajemen risiko, dan penetapan target kinerja eksekutif. Dengan demikian, laporan menjadi keluaran dari proses pengelolaan yang sesungguhnya, bukan dokumen yang disusun mundur dari kebutuhan pencitraan.</p>`
    },
    {
      no: "5.7",
      title: "Mengorganisasikan Manajemen Etika Bisnis: Struktur, Budaya, dan Kepemimpinan",
      body: `<p>Pertanyaan terakhir dalam bab ini adalah bagaimana keseluruhan upaya pengelolaan etika diorganisasikan di dalam perusahaan. Crane dan Matten (2019) membedakan dua pendekatan besar, yaitu pendekatan formal dan pendekatan informal. Pendekatan formal mengandalkan struktur serta sistem resmi, seperti kode etik, komite etika, jabatan <em>ethics officer</em>, prosedur pelaporan pelanggaran, dan program pelatihan terjadwal. Pendekatan informal mengandalkan mekanisme yang tidak tertulis, seperti norma kelompok, keteladanan pemimpin, cerita dan simbol organisasi, serta iklim etis yang dirasakan karyawan sehari-hari.</p>
<p>Kedua pendekatan tersebut bermuara pada konsep budaya etis organisasi. Budaya organisasi merupakan pola asumsi, nilai, dan norma bersama yang mengarahkan cara anggota organisasi berpikir dan bertindak. Penelitian perilaku organisasi yang dirujuk Crane dan Matten (2019) menunjukkan bahwa konteks organisasi sering kali lebih menentukan perilaku etis karyawan dibandingkan karakter moral individu, sebab tekanan atasan, target kinerja, dan norma kelompok dapat mendorong orang baik melakukan hal yang menyimpang. Oleh karena itu, upaya mengelola etika pada hakikatnya adalah upaya membentuk budaya, dan instrumen formal hanya akan efektif apabila selaras dengan pesan informal yang diterima karyawan. Apabila kode etik melarang manipulasi angka penjualan sementara atasan secara informal menuntut pencapaian target dengan segala cara, karyawan akan mengikuti pesan informal tersebut.</p>
<p>Unsur penentu yang paling kuat dalam pembentukan budaya etis adalah kepemimpinan etis. Pemimpin etis menjalankan dua peran sekaligus, yaitu sebagai pribadi bermoral (<em>moral person</em>) yang jujur, adil, dan dapat dipercaya, serta sebagai manajer moral (<em>moral manager</em>) yang secara aktif mengomunikasikan standar etika, menjadikan etika kriteria dalam pengambilan keputusan, memberi imbalan pada perilaku etis, dan menindak pelanggaran secara konsisten. Nada dari puncak (<em>tone at the top</em>) yang ditunjukkan direksi dan komisaris akan diperkuat oleh nada dari tengah yang ditunjukkan para manajer lini, sehingga pengembangan kepemimpinan etis perlu dilakukan pada seluruh jenjang organisasi. Dalam konteks Indonesia, penerapan nilai inti AKHLAK di lingkungan badan usaha milik negara sejak tahun 2020 dapat dibaca sebagai upaya membentuk budaya etis secara terpusat, meskipun efektivitasnya tetap bergantung pada keteladanan pimpinan masing-masing perusahaan.</p>
<p>Selain itu, perkembangan mutakhir menunjukkan meluasnya profesi manajemen etika, ditandai oleh kehadiran asosiasi profesional pejabat etika dan kepatuhan, konsultan etika, serta standar sistem manajemen antisuap seperti ISO 37001 yang juga telah diadopsi sejumlah perusahaan Indonesia. Implikasi manajerialnya, perusahaan perlu menempatkan fungsi etika pada posisi struktural yang memiliki akses langsung kepada direksi dan komite audit, membekalinya dengan sumber daya memadai, serta mengukur keberhasilannya bukan hanya dari jumlah pelatihan yang diselenggarakan melainkan dari indikator budaya seperti kesediaan karyawan melaporkan pelanggaran tanpa takut pembalasan.</p>`
    },
    {
      no: "5.8",
      title: "Rangkuman",
      body: `<p>Bab ini menjelaskan bahwa manajemen etika bisnis merupakan upaya sengaja perusahaan untuk mengelola isu etika melalui kebijakan, praktik, dan program, baik formal maupun informal. Komponen utamanya meliputi pernyataan misi dan nilai, kode etik, saluran pelaporan dan konsultasi, manajer serta komite etika, manajemen risiko etika, pelatihan, dialog pemangku kepentingan, dan akuntansi sosial. Motivasi perusahaan mengelola etika beragam, mulai dari perlindungan reputasi dan kepatuhan hukum hingga komitmen moral, dan pendekatannya dapat dipetakan pada spektrum antara orientasi kepatuhan yang menekankan pengendalian eksternal dan orientasi nilai yang menekankan internalisasi komitmen (Paine, 1994).</p>
<p>Kode etik merupakan instrumen penetapan standar yang paling luas digunakan, tersedia dalam bentuk kode organisasi, profesi, industri, dan program lintas organisasi. Efektivitas kode tidak ditentukan oleh keberadaannya, melainkan oleh kualitas implementasi, penegakan yang konsisten, dan keselarasannya dengan budaya organisasi. Pengelolaan hubungan pemangku kepentingan memerlukan pemetaan arti penting berdasarkan atribut kekuasaan, legitimasi, dan urgensi (Mitchell, Agle dan Wood, 1997), yang kemudian ditindaklanjuti dengan bentuk keterlibatan yang tepat, dari pemberian informasi hingga kemitraan, dengan tetap mewaspadai risiko kooptasi dan dialog yang bersifat kosmetik.</p>
<p>Selanjutnya, kinerja etis perlu diukur dan dipertanggungjawabkan melalui akuntansi, audit, dan pelaporan sosial yang berkualitas, dengan kriteria seperti inklusivitas, kelengkapan, keterbandingan, dan verifikasi eksternal. Pada akhirnya, seluruh instrumen tersebut hanya akan berfungsi apabila diorganisasikan dalam budaya etis yang didukung kepemimpinan etis pada semua jenjang. Dengan demikian, tugas manajer bukan sekadar menyusun dokumen etika, melainkan membangun sistem dan budaya yang menjadikan perilaku etis sebagai cara kerja normal organisasi.</p>`
    },
    {
      no: "5.9",
      title: "Daftar Pustaka",
      body: `<p>Crane, A. dan Matten, D. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford University Press.</p>
<p>Mitchell, R. K., Agle, B. R. dan Wood, D. J. (1997). Toward a Theory of Stakeholder Identification and Salience: Defining the Principle of Who and What Really Counts. <em>Academy of Management Review</em>, 22(4).</p>
<p>Paine, L. S. (1994). Managing for Organizational Integrity. <em>Harvard Business Review</em>, 72(2).</p>
<p>Trevino, L. K. dan Nelson, K. A. (2021). <em>Managing Business Ethics: Straight Talk about How to Do It Right</em>. Edisi ke-8. Wiley.</p>
<p>Zadek, S., Pruzan, P. dan Evans, R. (1997). <em>Building Corporate AccountAbility: Emerging Practices in Social and Ethical Accounting, Auditing and Reporting</em>. Earthscan.</p>`
    }
  ]
};
