window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[1] = {
  bab: 1,
  judul: "BAB 1 PENGANTAR ETIKA BISNIS",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 1",
  lo: [
    "LO1 Menjelaskan pengertian etika bisnis serta membedakan konsep moralitas, etika, dan teori etika.",
    "LO2 Menguraikan hubungan antara etika bisnis dan hukum, termasuk keberadaan wilayah abu-abu yang tidak diatur oleh keduanya secara tegas.",
    "LO3 Menganalisis alasan pentingnya etika bisnis bagi organisasi, pemangku kepentingan, dan masyarakat luas.",
    "LO4 Membandingkan penerapan etika bisnis pada berbagai konteks organisasi, yaitu korporasi besar, usaha kecil dan menengah, organisasi masyarakat sipil, serta organisasi sektor publik.",
    "LO5 Menjelaskan globalisasi sebagai konteks kunci etika bisnis beserta implikasi budaya, hukum, dan akuntabilitasnya, termasuk perbedaan perspektif regional.",
    "LO6 Menjelaskan keberlanjutan sebagai tujuan kunci etika bisnis melalui kerangka triple bottom line."
  ],
  sections: [
    {
      no: "1.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini merupakan pintu masuk bagi mahasiswa untuk memahami bidang kajian etika bisnis secara menyeluruh. Pembahasan diawali dengan penelusuran definisi etika bisnis dan pembedaan istilah yang sering dipertukarkan, yaitu moralitas, etika, dan teori etika, kemudian dilanjutkan dengan hubungan antara etika bisnis dan hukum. Selanjutnya, bab ini menguraikan alasan mengapa etika bisnis menjadi semakin penting dipelajari, penerapannya pada berbagai jenis organisasi, serta dua tema besar yang membingkai keseluruhan kajian, yaitu globalisasi sebagai konteks kunci dan keberlanjutan sebagai tujuan kunci. Dengan demikian, mahasiswa memperoleh peta konseptual yang menjadi fondasi bagi sesi-sesi berikutnya.</p>
<p>Setelah mempelajari materi pada bab ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p><strong>1.</strong> Menjelaskan pengertian etika bisnis serta membedakan konsep moralitas, etika, dan teori etika. <strong>2.</strong> Menguraikan hubungan antara etika bisnis dan hukum. <strong>3.</strong> Menganalisis alasan pentingnya etika bisnis bagi organisasi dan masyarakat. <strong>4.</strong> Membandingkan penerapan etika bisnis pada berbagai konteks organisasi. <strong>5.</strong> Menjelaskan globalisasi sebagai konteks kunci etika bisnis beserta implikasinya. <strong>6.</strong> Menjelaskan keberlanjutan sebagai tujuan kunci etika bisnis melalui kerangka <em>triple bottom line</em>.</p>`
    },
    {
      no: "1.2",
      title: "Definisi dan Ruang Lingkup Etika Bisnis",
      body: `<p>Perkembangan dunia usaha yang semakin kompleks menempatkan pelaku bisnis pada berbagai situasi yang tidak hanya menuntut pertimbangan komersial, tetapi juga pertimbangan tentang benar dan salah. Skandal korporasi yang terjadi di berbagai negara, mulai dari manipulasi laporan keuangan, suap dalam pengadaan, hingga kerusakan lingkungan, menunjukkan bahwa keputusan bisnis memiliki dimensi moral yang tidak dapat diabaikan. Oleh karena itu, diperlukan suatu bidang kajian yang secara khusus menelaah dimensi moral dari aktivitas bisnis, yang dikenal sebagai etika bisnis.</p>
<p>Menurut Crane dan Matten (2019), etika bisnis adalah studi tentang situasi, aktivitas, dan keputusan bisnis yang di dalamnya persoalan mengenai benar dan salah menjadi pokok perhatian. Pengertian benar dan salah dalam definisi tersebut merujuk pada benar dan salah secara moral, bukan sekadar benar dan salah secara komersial, strategis, atau finansial. Sebuah keputusan dapat saja menguntungkan secara komersial, misalnya menekan biaya produksi dengan mengabaikan keselamatan kerja, tetapi keputusan tersebut tetap salah secara moral. Dari definisi tersebut dapat disimpulkan bahwa etika bisnis merupakan kajian sistematis atas dimensi moral dari keputusan bisnis, yang cakupannya tidak terbatas pada perusahaan komersial semata, melainkan meliputi seluruh bentuk transaksi dan aktivitas keorganisasian yang melibatkan pertukaran barang dan jasa.</p>
<p>Ruang lingkup etika bisnis juga perlu dipahami secara luas. Istilah bisnis dalam konteks ini tidak hanya merujuk pada korporasi berorientasi laba, tetapi juga mencakup usaha kecil, koperasi, organisasi nirlaba, hingga lembaga pemerintah yang melakukan aktivitas ekonomi. Selain itu, persoalan etika bisnis muncul pada semua fungsi manajemen, mulai dari pemasaran, keuangan, manajemen sumber daya manusia, operasi, hingga teknologi informasi. Dengan demikian, setiap manajer pada level dan fungsi apa pun berpotensi menghadapi dilema etis dan memerlukan kerangka berpikir yang memadai untuk menyelesaikannya.</p>
<h5>1.2.1 Etika Bisnis dan Hukum</h5>
<p>Pertanyaan yang sering muncul dalam kajian etika bisnis adalah mengapa etika masih diperlukan apabila telah tersedia perangkat hukum yang mengatur perilaku bisnis. Hukum dapat dipahami sebagai kodifikasi standar perilaku minimum yang diterima masyarakat dan ditegakkan oleh negara, sedangkan etika berbicara tentang standar perilaku yang lebih luas daripada sekadar kepatuhan formal. Crane dan Matten (2019) menggambarkan hubungan keduanya sebagai dua lingkaran yang saling beririsan; sebagian persoalan diatur oleh hukum sekaligus dinilai oleh etika, tetapi terdapat wilayah etika yang tidak tersentuh hukum, dan sebaliknya terdapat aturan hukum yang relatif netral secara moral, misalnya ketentuan sisi jalan untuk berkendara.</p>
<p>Wilayah yang paling relevan bagi kajian etika bisnis adalah wilayah abu-abu (<em>grey area</em>), yaitu situasi ketika hukum belum mengatur, aturannya ambigu, atau penegakannya lemah, sehingga keputusan sepenuhnya bergantung pada pertimbangan moral pengambil keputusan. Contohnya adalah pemanfaatan data pribadi konsumen oleh platform digital sebelum peraturan perlindungan data diberlakukan, atau praktik penghindaran pajak yang legal tetapi dipertanyakan kepatutannya. Di Indonesia, praktik pemberian gratifikasi dalam relasi bisnis dengan pejabat publik lama berada pada wilayah abu-abu semacam ini sebelum diatur tegas dalam peraturan perundang-undangan antikorupsi. Oleh karena itu, dapat dikatakan bahwa etika bisnis pada dasarnya bermula ketika hukum berakhir, yakni pada persoalan yang belum atau tidak dapat diselesaikan oleh perangkat hukum semata. Implikasi manajerialnya adalah bahwa kepatuhan hukum merupakan syarat minimum, bukan tujuan akhir, sehingga manajer tetap dituntut membangun kapasitas penalaran moral di luar kerangka regulasi.</p>
<h5>1.2.2 Moralitas, Etika, dan Teori Etika</h5>
<p>Untuk memahami etika bisnis secara tepat, perlu dibedakan tiga istilah yang sering dipertukarkan, yaitu moralitas, etika, dan teori etika. Menurut Crane dan Matten (2019), moralitas berkaitan dengan norma, nilai, dan keyakinan yang tertanam dalam proses sosial suatu masyarakat dan menentukan apa yang dianggap benar dan salah bagi individu maupun komunitas. Moralitas bersifat given dalam arti telah hidup dan dipraktikkan dalam masyarakat, misalnya keyakinan masyarakat Indonesia bahwa menepati janji dagang merupakan kewajiban dan mengambil hak orang lain merupakan perbuatan tercela.</p>
<p>Sementara itu, etika didefinisikan sebagai studi tentang moralitas, yaitu upaya sistematis untuk menelaah, merasionalisasi, dan menilai norma moral yang berlaku. Hasil dari kegiatan menelaah tersebut kemudian dirumuskan menjadi teori etika, yakni kodifikasi aturan dan prinsip yang menentukan benar dan salah dalam situasi tertentu, misalnya teori utilitarianisme atau etika kewajiban yang akan dibahas pada sesi berikutnya. Dari ketiga pengertian tersebut dapat disimpulkan bahwa hubungan ketiganya bersifat berjenjang; etika merasionalisasi moralitas untuk menghasilkan teori etika, dan teori etika selanjutnya dapat diterapkan kembali untuk memecahkan persoalan moral konkret dalam bisnis. Dengan demikian, mempelajari etika bisnis bukan berarti mengajarkan moral dalam pengertian menggurui, melainkan membekali mahasiswa dengan perangkat analitis untuk menilai dan memutuskan persoalan moral secara sistematis.</p>`
    },
    {
      no: "1.3",
      title: "Urgensi Etika Bisnis",
      body: `<p>Pertanyaan mendasar yang perlu dijawab pada awal perkuliahan adalah mengapa etika bisnis penting untuk dipelajari, khususnya oleh mahasiswa magister manajemen yang kelak menduduki posisi pengambil keputusan. Crane dan Matten (2019) mengemukakan sejumlah alasan yang menunjukkan bahwa etika bisnis bukan sekadar pelengkap kurikulum, melainkan kompetensi inti manajerial. Alasan-alasan tersebut dapat diuraikan sebagai berikut.</p>
<p>Pertama, kekuatan dan pengaruh bisnis dalam masyarakat semakin besar dibandingkan periode mana pun dalam sejarah. Korporasi multinasional saat ini memiliki pendapatan yang melampaui produk domestik bruto banyak negara, sehingga keputusan bisnis berdampak luas terhadap kehidupan publik. Kedua, bisnis berpotensi memberikan kontribusi besar bagi masyarakat melalui penyediaan lapangan kerja, barang dan jasa, pembayaran pajak, serta inovasi; potensi kontribusi tersebut hanya terwujud secara optimal apabila aktivitas bisnis dijalankan secara etis. Ketiga, pada saat yang sama, malapraktik bisnis mampu menimbulkan kerugian yang sangat besar bagi karyawan, konsumen, komunitas, dan lingkungan, sebagaimana ditunjukkan oleh berbagai skandal korporasi global maupun kasus di Indonesia seperti manipulasi laporan keuangan pada beberapa badan usaha milik negara dan kerusakan lingkungan akibat kebakaran lahan konsesi.</p>
<p>Keempat, tuntutan pemangku kepentingan (<em>stakeholders</em>) terhadap perilaku etis perusahaan terus meningkat. Konsumen, investor, karyawan, media, dan organisasi masyarakat sipil kini lebih kritis dan memiliki akses informasi yang luas untuk mengawasi perusahaan, termasuk melalui media sosial yang mempercepat penyebaran isu. Kelima, masih sedikit pelaku bisnis yang memperoleh pendidikan formal mengenai etika bisnis, sehingga banyak manajer mengelola dilema moral hanya berdasarkan intuisi tanpa kerangka analitis yang memadai. Keenam, pelanggaran etika terus saja terjadi meskipun kesadaran publik meningkat, yang menandakan bahwa persoalan ini belum terselesaikan dan tetap relevan untuk dikaji. Ketujuh, etika bisnis membekali kemampuan untuk menilai secara kritis manfaat dan keterbatasan berbagai pendekatan pengelolaan etika di perusahaan, misalnya kode etik, pelatihan, dan audit sosial, sehingga manajer tidak terjebak pada praktik yang bersifat kosmetik semata.</p>
<p>Perlu ditegaskan pula bahwa mempelajari etika bisnis tidak dimaksudkan untuk menjadikan seseorang bermoral baik secara otomatis, sebagaimana mempelajari ilmu keuangan tidak otomatis menjadikan seseorang kaya. Tujuan pembelajaran adalah meningkatkan kemampuan mengenali persoalan etis, menganalisisnya dari berbagai sudut pandang teori, dan mengambil keputusan yang dapat dipertanggungjawabkan. Dengan demikian, implikasi manajerial dari urgensi ini adalah bahwa kompetensi etis perlu diperlakukan setara dengan kompetensi teknis dalam pengembangan karier manajerial, karena kegagalan etis terbukti mampu menghancurkan nilai perusahaan yang dibangun puluhan tahun dalam waktu singkat.</p>`
    },
    {
      no: "1.4",
      title: "Etika Bisnis dalam Berbagai Konteks Organisasi",
      body: `<p>Kajian etika bisnis sering diasosiasikan hanya dengan korporasi besar, padahal persoalan etika muncul pada semua jenis organisasi dengan karakteristik yang berbeda-beda. Crane dan Matten (2019) mengidentifikasi empat konteks organisasi utama, yaitu korporasi besar, usaha kecil dan menengah, organisasi masyarakat sipil, serta organisasi sektor publik. Pemahaman atas perbedaan konteks tersebut penting agar analisis etika tidak diseragamkan secara keliru.</p>
<p>Pada korporasi besar, persoalan etika umumnya berkaitan dengan pemisahan kepemilikan dan pengelolaan, akuntabilitas kepada pemegang saham dan pemangku kepentingan lain, tata kelola perusahaan, serta dampak sosial dan lingkungan yang berskala luas. Di sisi lain, usaha kecil dan menengah menghadapi persoalan etika yang lebih personal karena pemilik biasanya sekaligus pengelola; isu yang menonjol antara lain perlakuan terhadap karyawan yang sering berbasis hubungan kekeluargaan, persaingan dengan sesama usaha kecil, ketergantungan pada pelanggan atau pemasok besar, serta keterbatasan sumber daya untuk membangun sistem etika formal. Dalam konteks Indonesia, usaha mikro, kecil, dan menengah menyumbang porsi terbesar lapangan kerja nasional, sehingga praktik etis pada segmen ini, misalnya kejujuran takaran dan mutu produk pada sentra industri batik dan pangan olahan, memiliki dampak sosial yang sangat luas meskipun jarang menjadi sorotan media.</p>
<p>Organisasi masyarakat sipil (<em>civil society organizations</em>), yang mencakup lembaga swadaya masyarakat dan organisasi nirlaba, juga tidak bebas dari persoalan etika. Isu yang khas pada konteks ini antara lain akuntabilitas penggunaan dana donatur, transparansi kepada publik, legitimasi dalam mengklaim mewakili kepentingan masyarakat, serta taktik kampanye yang digunakan dalam menekan perusahaan. Sementara itu, organisasi sektor publik dan badan usaha milik negara menghadapi isu etika berupa konflik kepentingan, korupsi dan suap, penyalahgunaan wewenang, serta ketegangan antara misi pelayanan publik dan tuntutan efisiensi komersial, khususnya ketika layanan publik diprivatisasi atau dikelola dengan logika pasar. Kasus penyimpangan pengelolaan dana investasi pada perusahaan asuransi milik negara di Indonesia memperlihatkan bahwa persoalan etika pada sektor publik dapat merugikan jutaan nasabah dan menggerus kepercayaan masyarakat terhadap institusi negara.</p>
<table class="bk-table"><caption>Tabel 1.1 Perbandingan Isu Etika pada Berbagai Konteks Organisasi</caption>
<thead><tr><th>Konteks Organisasi</th><th>Karakteristik Utama</th><th>Isu Etika yang Menonjol</th></tr></thead>
<tbody>
<tr><td>Korporasi besar</td><td>Kepemilikan terpisah dari pengelolaan; dampak berskala luas</td><td>Tata kelola, akuntabilitas pemangku kepentingan, dampak sosial dan lingkungan</td></tr>
<tr><td>Usaha kecil dan menengah</td><td>Pemilik merangkap pengelola; sumber daya terbatas</td><td>Relasi personal dengan karyawan, kejujuran terhadap pelanggan, ketergantungan pada mitra besar</td></tr>
<tr><td>Organisasi masyarakat sipil</td><td>Berbasis misi sosial; bergantung pada donatur</td><td>Akuntabilitas dana, legitimasi representasi, etika taktik kampanye</td></tr>
<tr><td>Organisasi sektor publik</td><td>Misi pelayanan publik; kewenangan regulatif</td><td>Korupsi dan suap, konflik kepentingan, ketegangan misi publik dan logika komersial</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>
<p>Implikasi manajerial dari pemetaan konteks tersebut adalah bahwa desain pengelolaan etika harus disesuaikan dengan karakteristik organisasi. Kode etik formal dan fungsi kepatuhan yang lazim pada korporasi besar belum tentu layak diterapkan pada usaha kecil yang lebih mengandalkan keteladanan pemilik, sedangkan organisasi nirlaba dan sektor publik memerlukan mekanisme akuntabilitas yang menekankan kepercayaan publik. Oleh karena itu, manajer perlu terlebih dahulu memahami konteks organisasinya sebelum memilih instrumen pengelolaan etika yang tepat.</p>`
    },
    {
      no: "1.5",
      title: "Globalisasi sebagai Konteks Kunci Etika Bisnis",
      body: `<p>Globalisasi merupakan salah satu kata yang paling sering digunakan dalam wacana bisnis kontemporer, tetapi pengertiannya kerap kabur. Dalam kajian etika bisnis, globalisasi ditempatkan sebagai konteks kunci karena mengubah secara mendasar lanskap tempat keputusan etis diambil. Perusahaan yang beroperasi lintas negara berhadapan dengan keragaman nilai, sistem hukum, dan ekspektasi masyarakat yang tidak lagi dapat diselesaikan dengan satu standar tunggal dari negara asal.</p>
<h5>1.5.1 Pengertian Globalisasi</h5>
<p>Crane dan Matten (2019), dengan merujuk pada pemikiran Scholte, mendefinisikan globalisasi sebagai proses deteritorialisasi, yaitu berkurangnya peran wilayah geografis sebagai penentu aktivitas sosial dan ekonomi. Dalam pengertian ini, globalisasi bukan sekadar meningkatnya perdagangan internasional, melainkan munculnya ruang aktivitas ekonomi, komunikasi, dan keuangan yang melampaui batas teritorial negara, misalnya pasar modal global yang bergerak dua puluh empat jam dan platform digital yang melayani konsumen lintas negara tanpa kehadiran fisik. Dari definisi tersebut dapat disimpulkan bahwa inti globalisasi bagi etika bisnis adalah melemahnya keterkaitan antara aktivitas bisnis dan kontrol sosial berbasis wilayah, sehingga muncul kesenjangan antara jangkauan operasi perusahaan dan jangkauan aturan yang mengikatnya.</p>
<h5>1.5.2 Implikasi Globalisasi bagi Etika Bisnis</h5>
<p>Relevansi globalisasi bagi etika bisnis dapat diuraikan ke dalam tiga implikasi utama, yaitu implikasi budaya, hukum, dan akuntabilitas. Pertama, dari sisi budaya, perusahaan global berhadapan dengan nilai dan norma moral yang berbeda antarnegara; praktik yang dianggap wajar di satu negara, misalnya pemberian hadiah kepada mitra bisnis, dapat dipandang sebagai suap di negara lain. Kedua, dari sisi hukum, semakin jauh perusahaan beroperasi dari negara asalnya, semakin besar kemungkinan aktivitasnya berada di luar kerangka hukum yang selama ini menjadi acuan, sehingga persoalan yang semula diselesaikan oleh hukum kembali menjadi persoalan etika; contohnya adalah standar ketenagakerjaan pada rantai pasok di negara berkembang yang regulasinya lebih longgar. Ketiga, dari sisi akuntabilitas, korporasi global semakin kuat secara ekonomi tetapi tidak dipilih secara demokratis dan tidak sepenuhnya tunduk pada satu otoritas nasional mana pun, sehingga timbul pertanyaan mengenai kepada siapa dan melalui mekanisme apa perusahaan tersebut mempertanggungjawabkan dampak keputusannya.</p>
<p>Bagi Indonesia, ketiga implikasi tersebut sangat nyata. Perusahaan multinasional yang beroperasi di Indonesia perlu menyesuaikan diri dengan norma lokal seperti kepatutan sosial dan keagamaan dalam pemasaran, sementara perusahaan Indonesia yang mengekspor produk, misalnya minyak sawit, dituntut memenuhi standar keberlanjutan pembeli global yang lebih ketat daripada regulasi domestik. Oleh karena itu, manajer di Indonesia perlu mengembangkan kepekaan lintas budaya sekaligus kemampuan memenuhi standar transnasional agar tetap kompetitif di pasar global.</p>
<h5>1.5.3 Perbedaan Perspektif Regional atas Etika Bisnis</h5>
<p>Globalisasi tidak serta-merta menyeragamkan cara pandang terhadap etika bisnis. Crane dan Matten (2019) menunjukkan bahwa terdapat perbedaan perspektif yang cukup sistematis antara Eropa, Amerika Utara, dan Asia mengenai siapa yang dianggap bertanggung jawab atas perilaku etis, pedoman utama yang digunakan, serta isu yang menonjol. Di Amerika Utara, tanggung jawab etis cenderung diletakkan pada individu dan korporasi dengan pedoman utama berupa kode etik perusahaan, sedangkan di Eropa peran negara dan kerangka hukum kolektif lebih dominan dalam mengatur isu etika bisnis. Di Asia, termasuk Indonesia, tanggung jawab etis lebih banyak dibingkai oleh manajemen puncak, relasi komunal, dan nilai keagamaan, dengan penekanan pada harmoni dan kewajiban terhadap pemangku kepentingan yang dekat seperti karyawan dan komunitas.</p>
<table class="bk-table"><caption>Tabel 1.2 Perbandingan Perspektif Regional atas Etika Bisnis</caption>
<thead><tr><th>Aspek</th><th>Amerika Utara</th><th>Eropa</th><th>Asia</th></tr></thead>
<tbody>
<tr><td>Pihak yang dipandang bertanggung jawab</td><td>Individu dan korporasi</td><td>Kontrol sosial oleh kolektif, terutama negara</td><td>Manajemen puncak dan korporasi dalam relasi komunal</td></tr>
<tr><td>Pedoman utama perilaku etis</td><td>Kode etik korporasi</td><td>Kerangka hukum dan negosiasi antarpemangku kepentingan</td><td>Keteladanan pimpinan, nilai budaya dan keagamaan</td></tr>
<tr><td>Isu yang menonjol</td><td>Malapraktik individu, kejahatan korporasi</td><td>Isu sosial dalam pengorganisasian kerangka bisnis</td><td>Tata kelola korporasi, korupsi, akuntabilitas kelompok usaha</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>
<p>Perbedaan regional tersebut membawa implikasi manajerial yang penting. Manajer yang memimpin operasi lintas negara tidak dapat memindahkan begitu saja instrumen etika dari satu kawasan ke kawasan lain tanpa penyesuaian, karena efektivitas instrumen sangat dipengaruhi oleh ekspektasi kelembagaan setempat. Namun, penyesuaian tersebut juga tidak boleh terjerumus pada relativisme total yang membenarkan segala praktik lokal; keseimbangan antara kepekaan lokal dan prinsip universal akan menjadi tema perdebatan pada sesi mengenai teori etika.</p>`
    },
    {
      no: "1.6",
      title: "Keberlanjutan sebagai Tujuan Kunci Etika Bisnis",
      body: `<p>Apabila globalisasi merupakan konteks yang membingkai etika bisnis, maka keberlanjutan (<em>sustainability</em>) ditempatkan sebagai tujuan yang hendak dicapai. Konsep keberlanjutan berakar pada keprihatinan terhadap pola pembangunan yang menguras sumber daya alam dan membebani generasi mendatang. Konsep ini kemudian berkembang menjadi kerangka normatif yang paling banyak digunakan untuk menilai kontribusi bisnis terhadap masyarakat dalam jangka panjang.</p>
<p>Titik tolak konseptual keberlanjutan adalah definisi pembangunan berkelanjutan dari Komisi Brundtland tahun 1987, yaitu "pembangunan yang memenuhi kebutuhan masa kini tanpa mengorbankan kemampuan generasi mendatang untuk memenuhi kebutuhan mereka sendiri" (Crane dan Matten, 2019). Definisi tersebut mengandung dua gagasan inti, yaitu keadilan antargenerasi dan pengakuan atas keterbatasan daya dukung bumi. Dari definisi tersebut dapat disimpulkan bahwa keberlanjutan menuntut perusahaan memperhitungkan dampak jangka panjang keputusannya, bukan hanya kinerja finansial periode berjalan.</p>
<p>Dalam perkembangannya, keberlanjutan dioperasionalkan ke dalam tiga komponen yang saling terkait, yaitu komponen lingkungan, ekonomi, dan sosial. Komponen lingkungan menekankan pengelolaan sumber daya alam dan ekosistem agar tetap lestari, misalnya pengendalian emisi, efisiensi energi, dan pencegahan pencemaran. Komponen ekonomi menekankan kelangsungan ekonomi jangka panjang, yang tidak hanya berarti profitabilitas perusahaan, tetapi juga kontribusi terhadap kesejahteraan ekonomi masyarakat luas serta penolakan terhadap keuntungan yang diperoleh melalui cara yang merusak, seperti korupsi dan kartel. Komponen sosial menekankan keadilan dan pemerataan, termasuk penghormatan terhadap hak asasi manusia, kesejahteraan pekerja, dan pembangunan komunitas. Ketiga komponen tersebut harus dikelola secara seimbang, karena keunggulan pada satu komponen tidak dapat menutupi kegagalan pada komponen lainnya.</p>
<p>Gagasan tiga komponen tersebut dipopulerkan dalam dunia bisnis oleh Elkington melalui kerangka <em>triple bottom line</em>, yang menyatakan bahwa kinerja perusahaan seharusnya diukur pada tiga garis dasar, yaitu <em>profit</em>, <em>people</em>, dan <em>planet</em> (Crane dan Matten, 2019). Cara menggunakan kerangka ini dalam praktik manajerial adalah dengan menetapkan indikator, target, dan pelaporan untuk ketiga dimensi secara bersamaan, misalnya laba dan nilai ekonomi yang didistribusikan untuk dimensi ekonomi, jejak karbon dan volume limbah untuk dimensi lingkungan, serta tingkat kecelakaan kerja dan investasi komunitas untuk dimensi sosial. Sejumlah perusahaan Indonesia telah mengadopsi logika ini melalui laporan keberlanjutan yang diwajibkan otoritas jasa keuangan bagi emiten, dan praktik seperti program kemitraan petani plasma pada industri sawit menunjukkan upaya menyeimbangkan tujuan ekonomi dan sosial, meskipun efektivitasnya masih menjadi perdebatan publik.</p>
<table class="bk-table"><caption>Tabel 1.3 Tiga Komponen Keberlanjutan dan Contoh Indikatornya</caption>
<thead><tr><th>Komponen</th><th>Fokus Utama</th><th>Contoh Indikator Perusahaan</th></tr></thead>
<tbody>
<tr><td>Lingkungan (<em>planet</em>)</td><td>Kelestarian sumber daya alam dan ekosistem</td><td>Emisi karbon, konsumsi energi dan air, volume limbah</td></tr>
<tr><td>Ekonomi (<em>profit</em>)</td><td>Kelangsungan ekonomi jangka panjang dan integritas pasar</td><td>Laba berkelanjutan, nilai ekonomi terdistribusi, bebas korupsi</td></tr>
<tr><td>Sosial (<em>people</em>)</td><td>Keadilan sosial dan kesejahteraan pemangku kepentingan</td><td>Keselamatan kerja, keberagaman, investasi komunitas</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>
<p>Implikasi manajerial dari penempatan keberlanjutan sebagai tujuan kunci adalah pergeseran ukuran keberhasilan manajemen. Manajer tidak lagi cukup dinilai dari pencapaian target finansial, tetapi juga dari kemampuannya menciptakan nilai jangka panjang bagi pemangku kepentingan yang lebih luas. Namun, perlu disadari bahwa penerapan <em>triple bottom line</em> menghadapi tantangan nyata, antara lain kesulitan mengukur kinerja sosial dan lingkungan secara sebanding dengan kinerja finansial serta risiko pelaporan yang bersifat kosmetik (<em>greenwashing</em>). Oleh karena itu, kerangka ini harus digunakan dengan komitmen substantif, bukan sekadar formalitas pelaporan.</p>`
    },
    {
      no: "1.7",
      title: "Rangkuman",
      body: `<p>Bab ini telah meletakkan fondasi konseptual kajian etika bisnis. Etika bisnis didefinisikan sebagai studi tentang situasi, aktivitas, dan keputusan bisnis yang mempersoalkan benar dan salah secara moral. Kajian ini dibedakan dari hukum karena hukum hanya menetapkan standar minimum, sedangkan banyak persoalan bisnis berada pada wilayah abu-abu yang menuntut penalaran moral mandiri. Pembedaan antara moralitas sebagai norma yang hidup di masyarakat, etika sebagai studi atas moralitas, dan teori etika sebagai kodifikasi prinsip memberikan kejelasan posisi keilmuan bidang ini.</p>
<p>Urgensi etika bisnis bersumber dari besarnya kekuatan bisnis dalam masyarakat, potensi kontribusi sekaligus potensi kerugian yang ditimbulkannya, meningkatnya tuntutan pemangku kepentingan, serta berulangnya pelanggaran etika di berbagai negara termasuk Indonesia. Persoalan etika muncul pada semua konteks organisasi, yaitu korporasi besar, usaha kecil dan menengah, organisasi masyarakat sipil, dan sektor publik, dengan karakteristik isu yang berbeda sehingga pengelolaannya harus disesuaikan dengan konteks masing-masing.</p>
<p>Akhirnya, bab ini menempatkan dua tema besar yang membingkai keseluruhan mata kuliah. Globalisasi sebagai proses deteritorialisasi merupakan konteks kunci yang menimbulkan implikasi budaya, hukum, dan akuntabilitas bagi keputusan bisnis, dengan perspektif regional yang berbeda antara Amerika Utara, Eropa, dan Asia. Keberlanjutan merupakan tujuan kunci yang menuntut keseimbangan kinerja lingkungan, ekonomi, dan sosial melalui kerangka <em>triple bottom line</em>. Dengan demikian, mahasiswa diharapkan memandang etika bukan sebagai hambatan bisnis, melainkan sebagai kerangka berpikir untuk menciptakan nilai jangka panjang yang dapat dipertanggungjawabkan kepada seluruh pemangku kepentingan.</p>`
    },
    {
      no: "1.8",
      title: "Daftar Pustaka",
      body: `<p>Crane, A., Matten, D., Glozer, S. dan Spence, L. J. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford University Press.</p>
<p>Elkington, J. (1997). <em>Cannibals with Forks: The Triple Bottom Line of 21st Century Business</em>. Edisi ke-1. Capstone Publishing.</p>
<p>World Commission on Environment and Development. (1987). <em>Our Common Future</em>. Edisi ke-1. Oxford University Press.</p>`
    }
  ]
};
