window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[2] = {
  bab: 2,
  judul: "BAB 2 MEMBINGKAI ETIKA BISNIS: CSR, PEMANGKU KEPENTINGAN, DAN KEWARGAAN KORPORASI",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 2",
  lo: [
    "LO1 Menjelaskan mengapa korporasi menjadi aktor utama dalam kajian etika bisnis serta sejauh mana korporasi dapat dianggap memiliki tanggung jawab moral.",
    "LO2 Menguraikan argumen yang mendukung dan menentang tanggung jawab sosial perusahaan serta menjelaskan hakikat tanggung jawab tersebut melalui model piramida Carroll dalam berbagai konteks nasional.",
    "LO3 Menjelaskan konsep CSR strategis, meliputi daya tanggap sosial korporasi, kinerja sosial korporasi, dan penciptaan nilai bersama beserta kritik terhadapnya.",
    "LO4 Mengartikulasikan teori pemangku kepentingan sebagai model alternatif tentang perusahaan serta membedakan bentuk normatif, deskriptif, dan instrumentalnya.",
    "LO5 Mendiskusikan konsep akuntabilitas dan transparansi korporasi dalam kaitannya dengan peran politik perusahaan di masyarakat.",
    "LO6 Membedakan berbagai pengertian kewargaan korporasi, termasuk pandangan terbatas, pandangan setara, dan pandangan yang diperluas."
  ],
  sections: [
    {
      no: "2.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membangun kerangka konseptual yang membingkai kajian etika bisnis dengan menempatkan korporasi sebagai unit analisis utama. Setelah pada bab sebelumnya dibahas pengertian dan urgensi etika bisnis, bab ini menjawab pertanyaan yang lebih mendasar, yaitu kepada siapa korporasi bertanggung jawab, seberapa luas tanggung jawab tersebut, dan bagaimana tanggung jawab itu dikonsepkan dalam literatur. Tiga kerangka besar yang dibahas adalah <em>corporate social responsibility</em> (CSR), teori pemangku kepentingan (<em>stakeholder theory</em>), dan kewargaan korporasi (<em>corporate citizenship</em>), yang masing-masing menawarkan cara pandang berbeda namun saling melengkapi mengenai relasi antara bisnis dan masyarakat (Crane dan Matten, 2019).</p>
<p>Setelah mempelajari materi pada bab ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p>Pertama, menjelaskan mengapa korporasi menjadi aktor utama dalam etika bisnis serta menilai secara kritis apakah korporasi dapat memikul tanggung jawab moral sebagaimana individu. Kedua, menguraikan argumen yang mendukung dan menentang CSR serta menjelaskan empat lapis tanggung jawab dalam piramida Carroll beserta variasinya di berbagai konteks nasional, termasuk Indonesia. Ketiga, menjelaskan perkembangan CSR ke arah strategis melalui konsep daya tanggap sosial, kinerja sosial korporasi, dan penciptaan nilai bersama. Keempat, mengartikulasikan teori pemangku kepentingan beserta tiga bentuknya menurut Donaldson dan Preston. Kelima, mendiskusikan akuntabilitas dan transparansi korporasi sebagai konsekuensi peran politik perusahaan. Keenam, membedakan tiga pandangan mengenai kewargaan korporasi dan implikasinya bagi praktik manajemen.</p>`
    },
    {
      no: "2.2",
      title: "Korporasi sebagai Aktor Utama Etika Bisnis",
      body: `<p>Kajian etika bisnis pada prinsipnya dapat diterapkan pada berbagai bentuk organisasi, mulai dari usaha kecil, koperasi, hingga badan usaha milik negara. Namun, literatur etika bisnis menempatkan korporasi sebagai fokus utama karena korporasi merupakan bentuk organisasi bisnis yang paling dominan dalam perekonomian modern serta memiliki dampak sosial, ekonomi, dan lingkungan yang paling luas (Crane dan Matten, 2019). Keputusan yang diambil korporasi multinasional besar dapat memengaruhi kehidupan jutaan orang, baik sebagai karyawan, konsumen, pemasok, maupun warga masyarakat di sekitar wilayah operasinya. Oleh karena itu, pemahaman mengenai hakikat korporasi menjadi prasyarat sebelum membahas tanggung jawab yang melekat padanya.</p>
<h5>2.2.1 Hakikat dan Status Hukum Korporasi</h5>
<p>Korporasi secara hukum didefinisikan sebagai badan hukum (<em>legal person</em>) yang keberadaannya terpisah dari orang-orang yang mendirikan, memiliki, atau bekerja di dalamnya. Menurut Crane dan Matten (2019), terdapat tiga ciri utama korporasi yang relevan bagi analisis etika. Pertama, korporasi merupakan entitas hukum mandiri sehingga dapat memiliki aset, mengadakan kontrak, menggugat, dan digugat atas namanya sendiri. Kedua, kekayaan korporasi secara nominal dimiliki para pemegang saham, namun eksistensinya tidak bergantung pada pemegang saham tertentu karena saham dapat berpindah tangan tanpa membubarkan perusahaan. Ketiga, berlaku prinsip tanggung jawab terbatas (<em>limited liability</em>), yaitu pemegang saham hanya menanggung kerugian sebesar modal yang disetorkan, sedangkan manajer pada umumnya tidak menanggung secara pribadi akibat hukum dari tindakan perusahaan. Dari ciri-ciri tersebut dapat disimpulkan bahwa korporasi memiliki keleluasaan bertindak yang sangat besar, sementara mekanisme pertanggungjawaban personalnya justru terbatas, dan kesenjangan inilah yang menjadikan pertanyaan etis mengenai korporasi begitu penting.</p>
<p>Ciri lain yang perlu dicermati adalah bahwa korporasi pada dasarnya diciptakan dan diakui oleh masyarakat melalui negara. Izin berdiri dan beroperasinya perusahaan bersumber dari kerangka hukum yang dibuat publik, sehingga muncul gagasan bahwa korporasi terikat semacam kontrak sosial dengan masyarakat yang memberinya legitimasi. Dengan demikian, klaim bahwa perusahaan hanya berurusan dengan pemiliknya sulit dipertahankan secara konseptual, karena keberadaan perusahaan itu sendiri bergantung pada penerimaan masyarakat luas.</p>
<h5>2.2.2 Dapatkah Korporasi Memiliki Tanggung Jawab Moral</h5>
<p>Pertanyaan klasik dalam kajian ini adalah apakah tanggung jawab moral dapat dilekatkan pada korporasi sebagai entitas, ataukah hanya pada individu-individu di dalamnya. Satu kubu berpendapat bahwa hanya manusia yang memiliki niat, kesadaran, dan kehendak bebas sehingga hanya manusia yang dapat disalahkan secara moral. Kubu lain, yang diwakili antara lain oleh Peter French, berpendapat bahwa korporasi memiliki struktur pengambilan keputusan internal (<em>corporate internal decision structure</em>) yang memungkinkan tindakan perusahaan dirunut pada tujuan dan kebijakan korporat, bukan sekadar pada preferensi pribadi individu (Crane dan Matten, 2019). Selain itu, korporasi memiliki budaya organisasi berupa keyakinan dan nilai bersama yang membentuk cara anggota organisasi bertindak, sehingga perilaku etis atau tidak etis sering kali merupakan produk sistem, bukan semata-mata pilihan perorangan.</p>
<p>Dari perdebatan tersebut dapat disimpulkan bahwa korporasi dapat dipandang memiliki tanggung jawab moral dalam derajat tertentu, meskipun tidak identik dengan tanggung jawab moral manusia. Implikasi manajerialnya cukup nyata, yaitu bahwa upaya membangun perilaku etis tidak cukup dilakukan dengan menyeleksi individu yang berintegritas, melainkan harus menyentuh struktur insentif, prosedur pengambilan keputusan, dan budaya organisasi secara keseluruhan. Kasus kecelakaan industri besar, misalnya, jarang disebabkan oleh satu orang yang jahat, namun lebih sering oleh sistem yang menoleransi pengabaian keselamatan demi target biaya.</p>
<h5>2.2.3 Kepada Siapa Korporasi Bertanggung Jawab</h5>
<p>Persoalan berikutnya adalah arah pertanggungjawaban korporasi. Pandangan tradisional menyatakan bahwa manajer adalah agen dari pemegang saham sehingga tanggung jawab utamanya adalah memaksimalkan kekayaan pemilik. Namun, pemisahan antara kepemilikan dan pengendalian pada korporasi publik modern menimbulkan masalah keagenan, karena manajer dapat mengejar kepentingan sendiri, sementara pemegang saham yang tersebar luas kerap tidak berdaya mengawasinya. Di sisi lain, aktivitas perusahaan menimbulkan dampak eksternal (<em>externalities</em>) yang ditanggung pihak ketiga, misalnya pencemaran yang dirasakan masyarakat sekitar pabrik. Oleh karena itu, argumen bahwa korporasi hanya bertanggung jawab kepada pemegang saham semakin sulit dipertahankan, dan pertanyaan mengenai tanggung jawab sosial perusahaan menjadi agenda yang tidak terhindarkan.</p>`
    },
    {
      no: "2.3",
      title: "Tanggung Jawab Sosial Perusahaan (Corporate Social Responsibility)",
      body: `<p><em>Corporate social responsibility</em> (CSR) merupakan konsep tertua dan paling mapan dalam upaya membingkai relasi bisnis dan masyarakat. Secara umum CSR menunjuk pada tanggung jawab perusahaan yang melampaui kewajiban ekonomi dan hukum semata, yang dijalankan secara sukarela demi kebaikan masyarakat luas. Perdebatan mengenai CSR berpusat pada dua pertanyaan, yaitu mengapa perusahaan memiliki tanggung jawab sosial dan apa saja hakikat tanggung jawab tersebut (Crane dan Matten, 2019).</p>
<h5>2.3.1 Argumen Menentang dan Mendukung CSR</h5>
<p>Penentang CSR yang paling berpengaruh adalah Milton Friedman melalui artikelnya pada tahun 1970 yang berjudul "The social responsibility of business is to increase its profits" (Friedman, 1970, dikutip dalam Crane dan Matten, 2019). Friedman mengajukan tiga argumen utama. Pertama, hanya manusia yang memiliki tanggung jawab moral, sedangkan perusahaan bukanlah pribadi yang dapat memikul kewajiban moral. Kedua, manajer adalah agen pemegang saham sehingga satu-satunya kewajibannya adalah bertindak demi kepentingan pemilik, yaitu memperoleh laba, dan penggunaan dana perusahaan untuk tujuan sosial sama saja dengan memungut pajak tanpa mandat. Ketiga, masalah sosial merupakan ranah negara, bukan ranah manajer korporat yang tidak dipilih secara demokratis dan tidak memiliki keahlian menangani persoalan publik.</p>
<p>Terhadap argumen tersebut, para pendukung CSR mengajukan bantahan yang bersifat moral maupun ekonomis. Secara moral, korporasi menimbulkan dampak eksternal bagi masyarakat sehingga wajar dituntut ikut menanggung akibat perbuatannya; korporasi juga memiliki kekuasaan besar yang menuntut tanggung jawab setimpal; dan korporasi bergantung pada kontribusi banyak kelompok, bukan hanya pemegang saham. Secara ekonomis, dikenal argumen kepentingan diri yang tercerahkan (<em>enlightened self-interest</em>), yaitu bahwa CSR pada akhirnya menguntungkan perusahaan sendiri melalui reputasi yang lebih baik, kemampuan menarik dan mempertahankan karyawan bermutu, hubungan yang harmonis dengan masyarakat dan regulator, serta pencegahan regulasi yang lebih ketat di masa depan (Crane dan Matten, 2019). Dari kedua kelompok argumen tersebut dapat disimpulkan bahwa alasan perusahaan menjalankan CSR merentang dari pertimbangan normatif tentang kewajiban moral hingga pertimbangan bisnis tentang keberlanjutan laba jangka panjang, dan dalam praktik keduanya sering berjalan beriringan.</p>
<h5>2.3.2 Piramida CSR Carroll</h5>
<p>Untuk menjawab pertanyaan mengenai hakikat tanggung jawab sosial, model yang paling banyak dirujuk adalah piramida empat bagian dari Archie Carroll. Menurut Carroll (1991), sebagaimana diuraikan Crane dan Matten (2019), tanggung jawab sosial perusahaan tersusun atas empat lapis yang harus dipenuhi secara bersamaan. Lapis dasar adalah tanggung jawab ekonomi, yaitu kewajiban menghasilkan barang dan jasa yang dibutuhkan masyarakat secara efisien dan menguntungkan, karena tanpa kelangsungan ekonomi seluruh tanggung jawab lain tidak mungkin dijalankan. Lapis kedua adalah tanggung jawab hukum, yaitu kewajiban menaati peraturan sebagai kodifikasi aturan main yang ditetapkan masyarakat. Lapis ketiga adalah tanggung jawab etis, yaitu kewajiban melakukan apa yang benar, adil, dan patut menurut harapan masyarakat meskipun tidak diwajibkan hukum. Lapis puncak adalah tanggung jawab filantropis, yaitu keinginan berkontribusi memperbaiki kualitas hidup masyarakat melalui donasi, dukungan pendidikan, seni, dan kegiatan kemasyarakatan. Carroll menyebut dua lapis pertama sebagai tanggung jawab yang diwajibkan (<em>required</em>), lapis ketiga sebagai yang diharapkan (<em>expected</em>), dan lapis keempat sebagai yang diinginkan (<em>desired</em>) oleh masyarakat.</p>
<table class="bk-table">
<caption>Tabel 2.1 Empat Lapis Tanggung Jawab Sosial Perusahaan menurut Carroll</caption>
<thead><tr><th>Lapis</th><th>Inti Kewajiban</th><th>Status Tuntutan Masyarakat</th><th>Contoh Praktik</th></tr></thead>
<tbody>
<tr><td>Ekonomi</td><td>Menghasilkan laba, menyediakan barang dan jasa, membuka lapangan kerja</td><td>Diwajibkan</td><td>Efisiensi operasi, imbal hasil wajar bagi investor</td></tr>
<tr><td>Hukum</td><td>Menaati seluruh peraturan perundang-undangan</td><td>Diwajibkan</td><td>Kepatuhan pajak, standar keselamatan kerja, izin lingkungan</td></tr>
<tr><td>Etis</td><td>Bertindak benar dan adil melampaui tuntutan hukum</td><td>Diharapkan</td><td>Upah layak melebihi upah minimum, kejujuran pemasaran</td></tr>
<tr><td>Filantropis</td><td>Berkontribusi sukarela bagi kualitas hidup masyarakat</td><td>Diinginkan</td><td>Beasiswa, donasi bencana, program pengembangan komunitas</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
</table>
<p>Cara menggunakan kerangka ini dalam praktik manajerial adalah dengan memetakan setiap kebijakan atau program perusahaan ke dalam keempat lapis, kemudian memastikan tidak ada lapis dasar yang dikorbankan demi lapis di atasnya. Program filantropi yang megah tidak akan memiliki legitimasi apabila perusahaan pada saat yang sama menghindari pajak atau melanggar hak pekerja, karena piramida menuntut pemenuhan seluruh lapis secara simultan, bukan berurutan.</p>
<h5>2.3.3 CSR dalam Konteks Internasional dan Indonesia</h5>
<p>Crane dan Matten (2019) menegaskan bahwa bobot relatif keempat lapis piramida berbeda antarnegara. Di Amerika Serikat, tanggung jawab etis dan filantropis lebih banyak diserahkan pada kebijakan sukarela perusahaan, sedangkan di Eropa banyak persoalan seperti jaminan kesehatan dan hak pekerja telah diserap ke dalam kerangka hukum sehingga tanggung jawab hukum menjadi lebih dominan. Di negara berkembang, Visser mengusulkan urutan prioritas yang berbeda, yaitu tanggung jawab ekonomi tetap menjadi dasar, namun filantropi menempati posisi kedua karena besarnya kebutuhan sosial, disusul tanggung jawab hukum dan etis (Crane dan Matten, 2019). Kondisi Indonesia memperlihatkan kekhasan lain, karena melalui Pasal 74 Undang-Undang Nomor 40 Tahun 2007 tentang Perseroan Terbatas, tanggung jawab sosial dan lingkungan justru diwajibkan secara hukum bagi perseroan yang bergerak di bidang atau berkaitan dengan sumber daya alam. Dengan demikian, di Indonesia sebagian wilayah yang dalam teori bersifat sukarela telah bergeser menjadi kewajiban hukum, dan manajer perlu memahami bahwa kepatuhan formal terhadap regulasi CSR belum tentu memenuhi harapan etis masyarakat lokal. Praktik kemitraan Danone-Aqua dengan masyarakat sekitar daerah resapan air serta program penilaian kinerja lingkungan PROPER dari Kementerian Lingkungan Hidup merupakan contoh bagaimana lapis hukum, etis, dan filantropis saling berkelindan dalam konteks Indonesia.</p>`
    },
    {
      no: "2.4",
      title: "CSR Strategis: Daya Tanggap, Kinerja Sosial, dan Nilai Bersama",
      body: `<p>Perkembangan mutakhir literatur CSR bergeser dari pertanyaan filosofis mengenai alasan bertanggung jawab menuju pertanyaan strategis mengenai cara mengelola tanggung jawab tersebut agar selaras dengan strategi perusahaan. Tiga konsep kunci dalam pergeseran ini adalah daya tanggap sosial korporasi, kinerja sosial korporasi, dan penciptaan nilai bersama (Crane dan Matten, 2019).</p>
<h5>2.4.1 Daya Tanggap Sosial Korporasi</h5>
<p>Konsep <em>corporate social responsiveness</em> menekankan kapasitas perusahaan untuk menanggapi tekanan sosial secara aktif, bukan sekadar memiliki kewajiban abstrak. Carroll mengidentifikasi empat filosofi tanggapan yang membentuk kontinum, yaitu reaksi (<em>reaction</em>) ketika perusahaan menyangkal tanggung jawab dan melawan tuntutan, pertahanan (<em>defence</em>) ketika perusahaan mengakui tanggung jawab namun melakukan seminimal mungkin, akomodasi (<em>accommodation</em>) ketika perusahaan menerima tanggung jawab dan melakukan apa yang dituntut pemangku kepentingan, serta proaksi (<em>proaction</em>) ketika perusahaan berinisiatif melampaui tuntutan sebelum tekanan muncul (Crane dan Matten, 2019). Kerangka ini kemudian dioperasionalkan sebagai skala RDAP oleh Clarkson. Cara memakainya adalah dengan menilai posisi perusahaan terhadap suatu isu tertentu, misalnya emisi karbon atau kesejahteraan pekerja rantai pasok, lalu merumuskan langkah untuk bergerak menuju posisi yang lebih proaktif apabila isu tersebut material bagi legitimasi perusahaan.</p>
<h5>2.4.2 Kinerja Sosial Korporasi</h5>
<p>Konsep <em>corporate social performance</em> (CSP) yang dirumuskan Donna Wood mengintegrasikan berbagai untaian pemikiran CSR ke dalam satu model yang dapat diamati dan diukur. Model ini terdiri atas tiga komponen, yaitu prinsip tanggung jawab sosial pada tingkat institusi, organisasi, dan individu; proses daya tanggap sosial yang mencakup pemantauan lingkungan, manajemen pemangku kepentingan, dan manajemen isu; serta keluaran (<em>outcomes</em>) berupa kebijakan sosial, program sosial, dan dampak sosial yang nyata (Crane dan Matten, 2019). Kontribusi utama model ini bagi manajer adalah penegasan bahwa CSR harus dinilai dari hasil yang dapat diverifikasi, bukan dari niat atau pernyataan kebijakan semata. Selain itu, model CSP membuka jalan bagi riset empiris mengenai hubungan antara kinerja sosial dan kinerja keuangan perusahaan, yang secara umum menemukan hubungan positif moderat meskipun arah kausalitasnya masih diperdebatkan.</p>
<h5>2.4.3 Penciptaan Nilai Bersama dan Kritiknya</h5>
<p>Konsep paling mutakhir dalam arus CSR strategis adalah <em>creating shared value</em> (CSV) yang dipopulerkan Porter dan Kramer. Menurut Porter dan Kramer (2011), sebagaimana dibahas Crane dan Matten (2019), perusahaan seharusnya berhenti memperlakukan isu sosial sebagai aktivitas pinggiran dan mulai menciptakan nilai ekonomi dengan cara yang sekaligus menciptakan nilai bagi masyarakat. Terdapat tiga jalur penciptaan nilai bersama, yaitu merancang ulang produk dan pasar untuk melayani kebutuhan sosial yang belum terpenuhi, meredefinisi produktivitas dalam rantai nilai misalnya melalui efisiensi energi dan pengembangan pemasok lokal, serta membangun klaster industri pendukung di lokasi operasi perusahaan. Program pembinaan petani kakao oleh perusahaan pengolah cokelat di Sulawesi serta kemitraan inti-plasma pada industri kelapa sawit dapat dibaca sebagai upaya penerapan jalur kedua dan ketiga di Indonesia, meskipun keberhasilannya bervariasi.</p>
<p>Namun, CSV menuai kritik tajam dari kalangan akademisi. Crane dan Matten (2019) mencatat bahwa konsep ini tidak sepenuhnya orisinal karena mengulang gagasan lama CSR strategis, mengabaikan ketegangan hakiki antara tujuan ekonomi dan sosial yang tidak selalu dapat didamaikan, naif terhadap tantangan kepatuhan bisnis, serta bertumpu pada pandangan dangkal mengenai peran korporasi dalam masyarakat. Oleh karena itu, manajer sebaiknya memperlakukan CSV sebagai alat mencari titik temu antara laba dan manfaat sosial, sambil tetap menyadari bahwa akan selalu ada situasi ketika kepentingan masyarakat menuntut pengorbanan laba yang tidak dapat dibingkai sebagai peluang bisnis.</p>`
    },
    {
      no: "2.5",
      title: "Teori Pemangku Kepentingan tentang Perusahaan",
      body: `<p>Apabila CSR menjawab pertanyaan mengenai luas tanggung jawab perusahaan, teori pemangku kepentingan menjawab pertanyaan mengenai kepada siapa tanggung jawab itu ditujukan. Teori ini dikembangkan terutama oleh R. Edward Freeman pada tahun 1984 dan telah menjadi salah satu kerangka paling berpengaruh dalam etika bisnis maupun manajemen strategis (Crane dan Matten, 2019).</p>
<h5>2.5.1 Definisi dan Model Pemangku Kepentingan</h5>
<p>Menurut Freeman (1984), pemangku kepentingan adalah "setiap kelompok atau individu yang dapat memengaruhi atau dipengaruhi oleh pencapaian tujuan organisasi" (Freeman, 1984, dikutip dalam Crane dan Matten, 2019). Definisi tersebut mencakup dua arah relasi, yaitu pihak yang terkena dampak perusahaan dan pihak yang mampu memengaruhi perusahaan. Crane dan Matten (2019) mempertajam definisi ini dari sudut etika dengan menekankan pemangku kepentingan sebagai individu atau kelompok yang dirugikan atau diuntungkan oleh korporasi, atau yang haknya dilanggar atau dihormati oleh korporasi. Dari kedua definisi tersebut dapat disimpulkan bahwa kepemilikan saham bukanlah satu-satunya dasar klaim terhadap perusahaan, karena karyawan, konsumen, pemasok, masyarakat lokal, pemerintah, dan kelompok masyarakat sipil juga memiliki taruhan (<em>stake</em>) yang sah atas keputusan perusahaan.</p>
<p>Secara model, teori ini menggantikan gambaran tradisional perusahaan sebagai poros hubungan dua arah antara manajer dan pemegang saham dengan gambaran jejaring, yaitu perusahaan berada di tengah serangkaian relasi dua arah dengan banyak kelompok sekaligus. Konsekuensi manajerialnya adalah tugas manajemen berubah dari sekadar memaksimalkan satu fungsi tujuan menjadi menyeimbangkan beragam kepentingan yang sebagian saling bertentangan.</p>
<h5>2.5.2 Alasan Pentingnya Pemangku Kepentingan</h5>
<p>Terdapat dua kelompok alasan mengapa perusahaan wajib memperhatikan pemangku kepentingan di luar pemegang saham. Alasan hukum menunjuk pada kenyataan bahwa relasi perusahaan dengan banyak pihak telah diikat oleh jejaring kontrak dan regulasi, misalnya perjanjian kerja, jaminan produk, dan ketentuan lingkungan hidup, sehingga secara faktual perusahaan memang tidak hanya melayani pemilik. Alasan ekonomi menunjuk pada dampak eksternal yang tidak terselesaikan oleh mekanisme pasar serta pada masalah keagenan yang menunjukkan bahwa manajer pun tidak selalu setia pada pemegang saham (Crane dan Matten, 2019). Kasus lumpur Lapindo di Sidoarjo merupakan ilustrasi Indonesia yang jelas mengenai eksternalitas, karena kerugian terbesar justru ditanggung warga yang tidak memiliki hubungan kontraktual apa pun dengan perusahaan pengebor.</p>
<h5>2.5.3 Tiga Bentuk Teori Pemangku Kepentingan</h5>
<p>Donaldson dan Preston (1995), sebagaimana diuraikan Crane dan Matten (2019), membedakan tiga bentuk teori pemangku kepentingan. Bentuk normatif menyatakan alasan moral mengapa kepentingan seluruh pemangku kepentingan patut diperhatikan demi kepentingan mereka sendiri. Bentuk deskriptif menyatakan bahwa teori ini menggambarkan secara akurat bagaimana perusahaan pada kenyataannya beroperasi. Bentuk instrumental menyatakan bahwa memperhatikan pemangku kepentingan bermanfaat bagi kinerja perusahaan. Ketiganya dapat dirangkum dalam tabel berikut.</p>
<table class="bk-table">
<caption>Tabel 2.2 Tiga Bentuk Teori Pemangku Kepentingan menurut Donaldson dan Preston</caption>
<thead><tr><th>Bentuk</th><th>Pertanyaan Inti</th><th>Sifat Klaim</th><th>Implikasi Manajerial</th></tr></thead>
<tbody>
<tr><td>Normatif</td><td>Mengapa kepentingan pemangku kepentingan harus dihormati</td><td>Klaim moral tentang apa yang seharusnya</td><td>Kepentingan setiap kelompok bernilai intrinsik, bukan alat</td></tr>
<tr><td>Deskriptif</td><td>Apakah perusahaan nyatanya mengelola pemangku kepentingan</td><td>Klaim empiris tentang praktik aktual</td><td>Pemetaan pemangku kepentingan menjadi bagian analisis strategis</td></tr>
<tr><td>Instrumental</td><td>Apakah manajemen pemangku kepentingan meningkatkan kinerja</td><td>Klaim hubungan sarana dan tujuan</td><td>Relasi baik dengan pemangku kepentingan sebagai sumber keunggulan</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
</table>
<h5>2.5.4 Permasalahan dalam Penerapan</h5>
<p>Penerapan teori ini menghadapi sejumlah persoalan praktis. Pertama, identifikasi pemangku kepentingan yang relevan tidak selalu jelas, misalnya apakah generasi mendatang atau lingkungan alam termasuk pemangku kepentingan. Kedua, kepentingan antarkelompok sering bertentangan, misalnya efisiensi yang diinginkan konsumen dapat menekan kesejahteraan pekerja pemasok, sehingga manajer memerlukan kriteria untuk menimbang klaim yang bersaing, antara lain berdasarkan kekuatan, legitimasi, dan urgensi klaim tersebut. Ketiga, terdapat risiko bahwa retorika pemangku kepentingan digunakan sekadar sebagai alat hubungan masyarakat tanpa perubahan substansi keputusan. Oleh karena itu, manajemen pemangku kepentingan yang autentik menuntut mekanisme dialog yang melembaga, misalnya forum konsultasi masyarakat lingkar tambang yang dijalankan perusahaan pertambangan di Indonesia sebelum memperluas wilayah operasinya.</p>`
    },
    {
      no: "2.6",
      title: "Akuntabilitas dan Transparansi Korporasi",
      body: `<p>Perluasan tanggung jawab perusahaan menimbulkan pertanyaan lanjutan mengenai mekanisme pertanggungjawabannya. Konsep akuntabilitas korporasi (<em>corporate accountability</em>) menunjuk pada kewajiban perusahaan untuk dapat dimintai pertanggungjawaban atas konsekuensi tindakannya oleh pihak-pihak yang terdampak, bukan hanya oleh pemegang saham melalui rapat umum (Crane dan Matten, 2019). Isu ini menguat seiring bergesernya peran korporasi menjadi aktor yang bersifat politis, karena banyak korporasi kini turut menjalankan fungsi yang dahulu melekat pada negara, misalnya menyediakan layanan publik melalui privatisasi, mengatur standar industri secara swaregulasi, dan memengaruhi kebijakan melalui lobi. Ketika kekuasaan korporasi meluas ke wilayah publik, tuntutan wajar yang mengikutinya adalah agar korporasi tunduk pada pengawasan publik sebagaimana lembaga politik.</p>
<p>Instrumen utama akuntabilitas adalah transparansi (<em>transparency</em>), yaitu derajat keterbukaan informasi mengenai keputusan, kebijakan, dan dampak korporasi kepada pihak luar. Transparansi diwujudkan antara lain melalui pelaporan nonkeuangan seperti laporan keberlanjutan, audit sosial, serta keterbukaan rantai pasok. Di Indonesia, kewajiban penyampaian laporan keberlanjutan bagi lembaga jasa keuangan dan perusahaan terbuka melalui Peraturan Otoritas Jasa Keuangan Nomor 51 Tahun 2017 merupakan contoh pelembagaan transparansi tersebut. Namun, transparansi memiliki keterbatasan, karena pengungkapan yang selektif dapat berubah menjadi sarana pencitraan, misalnya praktik <em>greenwashing</em> yang menonjolkan capaian lingkungan kecil untuk menutupi dampak besar. Dengan demikian, akuntabilitas yang bermakna menuntut kombinasi antara keterbukaan informasi, verifikasi independen, dan saluran bagi pemangku kepentingan untuk menindaklanjuti informasi tersebut. Implikasi manajerialnya adalah bahwa fungsi pelaporan keberlanjutan sebaiknya diperlakukan sebagai bagian dari tata kelola dan manajemen risiko, bukan sekadar fungsi komunikasi pemasaran.</p>`
    },
    {
      no: "2.7",
      title: "Kewargaan Korporasi (Corporate Citizenship)",
      body: `<p>Kerangka ketiga yang membingkai relasi bisnis dan masyarakat adalah kewargaan korporasi. Istilah ini semula berkembang dari praktik bisnis, khususnya di Amerika Serikat, sebelum kemudian dielaborasi secara akademis. Crane dan Matten (2019) membedakan tiga pandangan mengenai kewargaan korporasi yang berbeda cakupannya.</p>
<h5>2.7.1 Pandangan Terbatas dan Pandangan Setara</h5>
<p>Pandangan terbatas (<em>limited view</em>) menyamakan kewargaan korporasi dengan filantropi strategis, yaitu kegiatan amal dan investasi sosial yang dilakukan perusahaan demi kepentingan masyarakat lokal sekaligus kepentingan bisnisnya sendiri. Dalam pandangan ini korporasi digambarkan sebagai warga yang baik yang memberi kembali kepada komunitasnya. Pandangan setara (<em>equivalent view</em>) memperlakukan kewargaan korporasi sekadar sebagai label baru bagi CSR, sebagaimana tampak pada rumusan Carroll yang mendefinisikan kewargaan korporasi dengan empat lapis tanggung jawab yang sama persis dengan piramida CSR miliknya (Crane dan Matten, 2019). Kedua pandangan tersebut dinilai tidak menambahkan substansi konseptual baru, karena hanya mengganti nama bagi gagasan yang telah ada.</p>
<h5>2.7.2 Pandangan yang Diperluas</h5>
<p>Kontribusi konseptual yang sesungguhnya terletak pada pandangan yang diperluas (<em>extended view</em>) yang dikembangkan Matten dan Crane. Pandangan ini bertolak dari teori kewargaan liberal yang membedakan tiga jenis hak warga negara, yaitu hak sosial berupa hak atas pendidikan, kesehatan, dan kesejahteraan; hak sipil berupa kebebasan dari campur tangan seperti hak milik dan kebebasan berpendapat; serta hak politik berupa hak berpartisipasi dalam pemerintahan. Dalam pandangan yang diperluas, korporasi bukanlah warga negara, melainkan aktor yang turut mengelola pemenuhan hak-hak kewargaan individu ketika pemerintah berhenti, belum, atau tidak mampu menjalankan fungsi tersebut (Crane dan Matten, 2019). Terhadap hak sosial korporasi berperan sebagai penyedia, misalnya perusahaan yang membangun sekolah dan fasilitas kesehatan di wilayah terpencil; terhadap hak sipil korporasi berperan sebagai pemungkin atau penghalang, misalnya perusahaan media sosial yang memfasilitasi atau membatasi kebebasan berekspresi; dan terhadap hak politik korporasi berperan sebagai kanal, karena warga kian menyalurkan aspirasi politiknya melalui tekanan terhadap perusahaan, misalnya melalui boikot konsumen. Peran perusahaan tambang dan perkebunan besar di kawasan timur Indonesia yang secara de facto menyediakan infrastruktur, listrik, dan layanan kesehatan bagi masyarakat sekitar merupakan contoh nyata korporasi yang mengambil alih sebagian fungsi pemenuhan hak sosial warga.</p>
<table class="bk-table">
<caption>Tabel 2.3 Tiga Pandangan mengenai Kewargaan Korporasi</caption>
<thead><tr><th>Pandangan</th><th>Inti Gagasan</th><th>Peran Korporasi</th><th>Kebaruan Konseptual</th></tr></thead>
<tbody>
<tr><td>Terbatas</td><td>Kewargaan sebagai filantropi strategis bagi komunitas lokal</td><td>Donatur dan tetangga yang baik</td><td>Rendah, setara filantropi</td></tr>
<tr><td>Setara</td><td>Kewargaan sebagai nama lain dari CSR</td><td>Pemikul empat lapis tanggung jawab Carroll</td><td>Rendah, pergantian label</td></tr>
<tr><td>Diperluas</td><td>Korporasi turut mengelola hak sosial, sipil, dan politik warga</td><td>Penyedia, pemungkin, dan kanal hak kewargaan</td><td>Tinggi, peran politik korporasi diakui</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
</table>
<h5>2.7.3 Penilaian atas Konsep Kewargaan Korporasi</h5>
<p>Pandangan yang diperluas memberi kosakata baru untuk memahami fenomena nyata, yaitu masuknya korporasi ke wilayah yang semula menjadi tanggung jawab negara akibat globalisasi dan menyusutnya kapasitas pemerintah. Namun, konsep ini juga mengundang kegelisahan normatif, karena korporasi menjalankan fungsi kuasi-pemerintahan tanpa mandat demokratis dan tanpa mekanisme akuntabilitas publik yang setara dengan negara. Oleh karena itu, pembahasan kewargaan korporasi kembali menegaskan pentingnya akuntabilitas dan transparansi yang dibahas pada sub-bab sebelumnya. Bagi manajer, implikasinya adalah kesadaran bahwa keputusan perusahaan di wilayah layanan publik, misalnya penetapan standar keamanan data pengguna oleh platform digital seperti Gojek atau Tokopedia, memiliki dimensi politik yang menuntut kehati-hatian, konsultasi publik, dan kesediaan diawasi melebihi kelaziman keputusan bisnis biasa.</p>`
    },
    {
      no: "2.8",
      title: "Rangkuman",
      body: `<p>Bab ini membingkai etika bisnis melalui tiga kerangka besar yang menjelaskan relasi antara korporasi dan masyarakat. Titik tolaknya adalah pemahaman mengenai korporasi sebagai badan hukum mandiri dengan tanggung jawab terbatas, yang melalui struktur pengambilan keputusan internal dan budaya organisasinya dapat dipandang memikul tanggung jawab moral dalam derajat tertentu. Kerangka pertama, CSR, menjawab pertanyaan mengenai luas tanggung jawab perusahaan. Meskipun ditentang Friedman dengan argumen keagenan dan pembagian peran negara dan pasar, CSR memperoleh justifikasi moral maupun ekonomis, dan hakikatnya dirumuskan Carroll dalam empat lapis tanggung jawab ekonomi, hukum, etis, dan filantropis yang bobotnya bervariasi antarnegara, termasuk di Indonesia yang mewajibkan CSR tertentu melalui undang-undang.</p>
<p>Kerangka kedua, teori pemangku kepentingan, menjawab pertanyaan mengenai arah tanggung jawab dengan menegaskan bahwa setiap kelompok yang memengaruhi atau dipengaruhi perusahaan memiliki klaim yang sah, dan teori ini dapat dibaca secara normatif, deskriptif, maupun instrumental. Perkembangan CSR strategis melalui daya tanggap sosial, kinerja sosial korporasi, dan penciptaan nilai bersama menunjukkan upaya mengintegrasikan tanggung jawab ke dalam strategi, meskipun kritik terhadap CSV mengingatkan bahwa ketegangan antara laba dan kepentingan sosial tidak selalu dapat didamaikan. Kerangka ketiga, kewargaan korporasi dalam pandangan yang diperluas, menangkap kenyataan bahwa korporasi kini turut mengelola hak sosial, sipil, dan politik warga ketika negara tidak hadir, sehingga menuntut akuntabilitas dan transparansi yang lebih tinggi. Dengan demikian, ketiga kerangka tersebut bukan pilihan yang saling meniadakan, melainkan lapisan analisis yang bersama-sama membekali manajer untuk memahami posisi perusahaan dalam masyarakat dan mengambil keputusan yang dapat dipertanggungjawabkan.</p>`
    },
    {
      no: "2.9",
      title: "Daftar Pustaka",
      body: `<p>Crane, A. dan Matten, D. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford University Press.</p>
<p>Carroll, A. B. (1991). The Pyramid of Corporate Social Responsibility: Toward the Moral Management of Organizational Stakeholders. <em>Business Horizons</em>, 34(4), 39-48. Dikutip dalam Crane dan Matten (2019).</p>
<p>Donaldson, T. dan Preston, L. E. (1995). The Stakeholder Theory of the Corporation: Concepts, Evidence, and Implications. <em>Academy of Management Review</em>, 20(1), 65-91. Dikutip dalam Crane dan Matten (2019).</p>
<p>Freeman, R. E. (1984). <em>Strategic Management: A Stakeholder Approach</em>. Pitman. Dikutip dalam Crane dan Matten (2019).</p>
<p>Friedman, M. (1970). The Social Responsibility of Business Is to Increase Its Profits. <em>The New York Times Magazine</em>, 13 September 1970. Dikutip dalam Crane dan Matten (2019).</p>
<p>Porter, M. E. dan Kramer, M. R. (2011). Creating Shared Value. <em>Harvard Business Review</em>, 89(1/2), 62-77. Dikutip dalam Crane dan Matten (2019).</p>
<p>Republik Indonesia. (2007). <em>Undang-Undang Nomor 40 Tahun 2007 tentang Perseroan Terbatas</em>. Sekretariat Negara.</p>`
    }
  ]
};
