window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[6] = {
  bab: 6,
  judul: "BAB 6 PEMEGANG SAHAM DAN ETIKA BISNIS",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 6",
  lo: [
    "LO1 Menjelaskan kedudukan pemegang saham sebagai pemangku kepentingan korporasi serta hakikat hubungan antara pemegang saham dan perusahaan.",
    "LO2 Menguraikan konsep tata kelola perusahaan (corporate governance), masalah keagenan, dan perbedaan rezim tata kelola antarnegara.",
    "LO3 Menganalisis isu-isu etika utama dalam tata kelola perusahaan, meliputi akuntabilitas eksekutif, remunerasi eksekutif, merger dan akuisisi, serta praktik perdagangan orang dalam.",
    "LO4 Mengevaluasi dampak globalisasi pasar keuangan terhadap akuntabilitas korporasi dan tantangan pengaturannya.",
    "LO5 Menilai peran pemegang saham sebagai warga korporasi melalui demokrasi pemegang saham, aktivisme pemegang saham, dan investasi etis.",
    "LO6 Menjelaskan kontribusi kepemilikan saham dan pasar keuangan terhadap agenda keberlanjutan, termasuk investasi berdampak, keuangan mikro, dan urun dana."
  ],
  sections: [
    {
      no: "6.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membahas kelompok pemangku kepentingan yang secara tradisional dianggap paling utama dalam perusahaan, yaitu pemegang saham. Dalam pandangan klasik, perusahaan dijalankan semata-mata untuk kepentingan pemiliknya, sehingga hubungan antara manajemen dan pemegang saham sering diperlakukan sebagai persoalan hukum dan keuangan, bukan persoalan etika. Crane dan Matten (2019) menunjukkan bahwa pandangan tersebut perlu ditinjau ulang karena hubungan pemegang saham dengan korporasi sesungguhnya sarat dengan pertimbangan moral, mulai dari akuntabilitas manajemen, keadilan remunerasi eksekutif, hingga tanggung jawab investor atas dampak sosial dari dana yang mereka tanamkan. Oleh karena itu, bab ini menempatkan pemegang saham bukan sebagai pihak yang berdiri di atas pemangku kepentingan lain, melainkan sebagai salah satu pemangku kepentingan yang hak dan kewajibannya harus dianalisis secara kritis.</p>
      <p>Setelah mempelajari materi pada sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <p>Pertama, menjelaskan kedudukan pemegang saham sebagai pemangku kepentingan dan hakikat kepemilikan saham atas korporasi. Kedua, menguraikan konsep tata kelola perusahaan, masalah keagenan, serta perbandingan rezim tata kelola Anglo-Amerika dan Eropa Kontinental. Ketiga, menganalisis isu etika dalam tata kelola perusahaan seperti akuntabilitas eksekutif, remunerasi eksekutif, merger dan akuisisi, serta <em>insider trading</em>. Keempat, mengevaluasi implikasi etis globalisasi pasar keuangan. Kelima, menilai peran aktif pemegang saham melalui demokrasi pemegang saham, aktivisme, dan investasi etis. Keenam, menjelaskan bagaimana kepemilikan saham dapat diarahkan untuk mendukung keberlanjutan.</p>`
    },
    {
      no: "6.2",
      title: "Pemegang Saham sebagai Pemangku Kepentingan Korporasi",
      body: `<p>Pemegang saham (<em>shareholders</em>) adalah pihak yang menyediakan modal ekuitas bagi perusahaan dan sebagai imbalannya memperoleh hak-hak tertentu atas perusahaan tersebut. Menurut Crane dan Matten (2019), hak-hak pemegang saham pada umumnya meliputi hak untuk menjual saham yang dimiliki, hak atas dividen apabila diputuskan pembagian laba, hak memperoleh informasi tertentu mengenai perusahaan, hak memberikan suara dalam rapat umum pemegang saham, serta hak menuntut manajemen apabila terjadi pelanggaran kewajiban. Di sisi lain, pemegang saham juga menanggung kewajiban dan risiko, terutama risiko kehilangan nilai investasi apabila perusahaan mengalami kerugian atau kebangkrutan. Dengan demikian, hubungan pemegang saham dan korporasi merupakan hubungan timbal balik yang dibingkai oleh hak dan tanggung jawab, bukan sekadar hubungan kepemilikan satu arah.</p>
      <p>Satu hal yang penting dipahami adalah bahwa kepemilikan saham berbeda secara mendasar dari kepemilikan atas barang pribadi. Pemegang saham tidak memiliki gedung, mesin, atau kas perusahaan secara langsung, melainkan memiliki klaim residual atas nilai perusahaan sebagai badan hukum yang mandiri. Korporasi modern adalah subjek hukum tersendiri yang eksistensinya terpisah dari para pemiliknya, sehingga pemegang saham tidak dapat memperlakukan aset perusahaan sesuka hati sebagaimana ia memperlakukan miliknya pribadi (Crane dan Matten, 2019). Dari karakteristik tersebut dapat disimpulkan bahwa klaim moral pemegang saham atas perusahaan bersifat terbatas dan harus disandingkan dengan klaim sah pemangku kepentingan lain seperti karyawan, konsumen, dan masyarakat.</p>
      <p>Kedudukan istimewa pemegang saham lazim dijustifikasi melalui doktrin tanggung jawab fidusia (<em>fiduciary responsibility</em>), yaitu kewajiban manajemen untuk bertindak demi kepentingan terbaik pemegang saham dengan itikad baik dan kehati-hatian. Pandangan ini berakar pada argumen Milton Friedman bahwa tanggung jawab sosial utama bisnis adalah meningkatkan laba bagi pemiliknya sepanjang dilakukan dalam aturan main yang berlaku (Friedman, 1970). Namun, perspektif pemangku kepentingan menegaskan bahwa kewajiban fidusia kepada pemegang saham tidak meniadakan kewajiban moral kepada pihak lain yang turut menanggung dampak keputusan perusahaan. Oleh karena itu, persoalan sentral bab ini adalah bagaimana kepentingan pemegang saham dikelola secara etis melalui mekanisme tata kelola perusahaan, dan sebaliknya bagaimana pemegang saham sendiri dapat bertindak etis dalam menggunakan kekuatan modalnya.</p>
      <p>Dalam konteks Indonesia, isu ini sangat relevan karena struktur kepemilikan perusahaan publik umumnya terkonsentrasi pada pemegang saham pengendali, baik keluarga pendiri maupun negara pada badan usaha milik negara. Konsentrasi kepemilikan semacam ini menggeser masalah etika dari konflik antara manajer dan pemegang saham menjadi konflik antara pemegang saham pengendali dan pemegang saham minoritas, misalnya melalui transaksi afiliasi yang merugikan minoritas. Dengan demikian, perlindungan pemegang saham minoritas menjadi salah satu agenda etika tata kelola yang menonjol di pasar modal Indonesia.</p>`
    },
    {
      no: "6.3",
      title: "Tata Kelola Perusahaan dan Masalah Keagenan",
      body: `<p>Ciri utama korporasi publik modern adalah pemisahan antara kepemilikan dan pengendalian (<em>separation of ownership and control</em>). Pemegang saham sebagai pemilik modal tidak menjalankan perusahaan sehari-hari, melainkan mempercayakannya kepada manajer profesional. Pemisahan ini melahirkan hubungan keagenan, yaitu hubungan antara prinsipal yang memberikan mandat dan agen yang menjalankan mandat tersebut. Jensen dan Meckling (1976) menjelaskan bahwa hubungan keagenan menimbulkan masalah ketika kepentingan agen tidak sejalan dengan kepentingan prinsipal dan prinsipal tidak dapat mengawasi agen secara sempurna karena adanya asimetri informasi. Manajer mengetahui kondisi perusahaan jauh lebih baik daripada pemegang saham, sehingga terbuka peluang bagi manajer untuk mengejar kepentingan pribadi, misalnya membesarkan ukuran perusahaan demi prestise, menikmati fasilitas berlebihan, atau mengamankan posisi jabatan.</p>
      <p>Tata kelola perusahaan (<em>corporate governance</em>) hadir sebagai jawaban atas masalah keagenan tersebut. Secara umum, tata kelola perusahaan dapat didefinisikan sebagai keseluruhan proses, struktur, dan aturan yang menata hubungan antara berbagai pihak dalam menentukan arah dan kinerja korporasi, khususnya hubungan antara pemegang saham, dewan, dan manajemen (Crane dan Matten, 2019). Mekanisme tata kelola mencakup antara lain dewan komisaris atau direktur independen yang mengawasi eksekutif, komite audit, auditor eksternal, keterbukaan informasi kepada publik, sistem remunerasi berbasis kinerja, serta pasar untuk pengendalian korporasi yang mendisiplinkan manajer berkinerja buruk melalui ancaman pengambilalihan. Dari definisi tersebut dapat disimpulkan bahwa tata kelola perusahaan pada hakikatnya adalah persoalan etika terapan, karena inti permasalahannya adalah kepercayaan, akuntabilitas, dan keadilan dalam pengelolaan dana pihak lain.</p>
      <h5>6.3.1 Perbandingan Rezim Tata Kelola Antarnegara</h5>
      <p>Crane dan Matten (2019) menekankan bahwa model tata kelola tidak seragam di seluruh dunia. Model Anglo-Amerika yang berlaku di Amerika Serikat dan Inggris bercirikan kepemilikan saham yang tersebar, pasar modal yang sangat likuid, orientasi kuat pada maksimalisasi nilai pemegang saham, serta struktur dewan satu tingkat (<em>one-tier board</em>) yang menggabungkan fungsi eksekutif dan pengawasan. Sebaliknya, model Eropa Kontinental atau model Rhineland yang berlaku di Jerman dan sebagian besar Eropa daratan bercirikan kepemilikan terkonsentrasi pada bank, keluarga, atau negara, pendanaan yang lebih mengandalkan perbankan, orientasi pada kepentingan pemangku kepentingan yang lebih luas, serta struktur dewan dua tingkat (<em>two-tier board</em>) yang memisahkan dewan pengawas dari dewan manajemen. Model Asia, termasuk jaringan <em>keiretsu</em> di Jepang dan konglomerasi keluarga di Asia Tenggara, menampilkan varian lain dengan peran kuat relasi bisnis jangka panjang dan kepemilikan silang.</p>
      <table class="bk-table"><caption>Tabel 6.1 Perbandingan Rezim Tata Kelola Anglo-Amerika dan Eropa Kontinental</caption>
      <thead><tr><th>Dimensi</th><th>Model Anglo-Amerika</th><th>Model Eropa Kontinental</th></tr></thead>
      <tbody>
      <tr><td>Struktur kepemilikan</td><td>Tersebar pada banyak investor publik</td><td>Terkonsentrasi pada bank, keluarga, atau negara</td></tr>
      <tr><td>Sumber pendanaan utama</td><td>Pasar modal</td><td>Kredit perbankan dan investor jangka panjang</td></tr>
      <tr><td>Orientasi tujuan</td><td>Maksimalisasi nilai pemegang saham</td><td>Keseimbangan kepentingan pemangku kepentingan</td></tr>
      <tr><td>Struktur dewan</td><td>Satu tingkat, eksekutif dan pengawas dalam satu dewan</td><td>Dua tingkat, dewan pengawas terpisah dari dewan manajemen</td></tr>
      <tr><td>Mekanisme disiplin utama</td><td>Pasar pengendalian korporasi dan ancaman akuisisi</td><td>Pengawasan internal oleh pemilik besar dan bank</td></tr>
      <tr><td>Isu etika yang menonjol</td><td>Orientasi jangka pendek dan remunerasi eksekutif berlebihan</td><td>Perlindungan minoritas dan transparansi kelompok usaha</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>
      <p>Indonesia menganut struktur dewan dua tingkat melalui pemisahan Dewan Komisaris sebagai organ pengawas dan Direksi sebagai organ pengurus, sebagaimana diatur dalam Undang-Undang Perseroan Terbatas. Selain itu, Otoritas Jasa Keuangan menerbitkan pedoman tata kelola bagi perusahaan terbuka yang mewajibkan antara lain keberadaan komisaris independen dan komite audit. Namun, keberadaan struktur formal tidak dengan sendirinya menjamin substansi tata kelola yang baik. Kasus manipulasi laporan keuangan pada Garuda Indonesia tahun 2019, ketika pendapatan dari perjanjian yang belum diterima kasnya diakui sebagai laba, menunjukkan bahwa fungsi pengawasan dapat gagal walaupun struktur dua tingkat telah tersedia. Implikasi manajerialnya adalah bahwa efektivitas tata kelola bergantung pada integritas dan independensi orang-orang yang menjalankannya, bukan sekadar kepatuhan formal terhadap regulasi.</p>`
    },
    {
      no: "6.4",
      title: "Isu-Isu Etika dalam Tata Kelola Perusahaan",
      body: `<p>Berdasarkan kerangka Crane dan Matten (2019), terdapat sejumlah wilayah keputusan dalam tata kelola perusahaan yang secara khusus menimbulkan persoalan etika, yaitu akuntabilitas dan pengendalian eksekutif, remunerasi eksekutif, merger dan akuisisi, serta peran pasar keuangan termasuk praktik perdagangan orang dalam. Keempat wilayah tersebut diuraikan pada sub-sub-bab berikut.</p>
      <h5>6.4.1 Akuntabilitas dan Pengendalian Eksekutif</h5>
      <p>Isu pertama menyangkut sejauh mana dewan mampu mengawasi eksekutif secara efektif demi kepentingan pemegang saham. Persoalan etisnya muncul karena anggota dewan sering kali tidak sepenuhnya independen dari manajemen yang seharusnya mereka awasi. Direktur non-eksekutif dapat berasal dari lingkaran pertemanan direktur utama, menerima honor yang ditentukan oleh manajemen, atau saling menduduki kursi dewan di perusahaan masing-masing sehingga terjadi saling ketergantungan. Selain itu, terdapat konflik kepentingan pada pihak-pihak penunjang seperti auditor eksternal yang sekaligus menjual jasa konsultasi kepada klien auditnya, sebagaimana terungkap dalam skandal Enron dan runtuhnya kantor akuntan Arthur Andersen (Crane dan Matten, 2019). Oleh karena itu, berbagai kode tata kelola menekankan independensi dewan, pemisahan jabatan ketua dewan dari direktur utama, rotasi auditor, dan penguatan komite audit sebagai prasyarat akuntabilitas yang sesungguhnya.</p>
      <h5>6.4.2 Remunerasi Eksekutif</h5>
      <p>Isu kedua adalah keadilan besaran dan struktur imbalan bagi eksekutif puncak. Gaji, bonus, dan opsi saham eksekutif di banyak negara meningkat jauh lebih cepat daripada upah pekerja biasa, sehingga rasio gaji direktur utama terhadap pekerja rata-rata melebar hingga ratusan kali lipat di sejumlah korporasi besar. Pembelaan atas remunerasi tinggi biasanya merujuk pada pasar tenaga kerja eksekutif yang kompetitif dan perlunya menyelaraskan insentif manajer dengan kepentingan pemegang saham. Namun, kritik etis menunjukkan tiga persoalan, yaitu besaran yang sulit dibenarkan dari sisi keadilan distributif, lemahnya kaitan antara imbalan dan kinerja ketika bonus tetap dibayarkan pada saat perusahaan merugi, serta proses penetapan yang rawan konflik kepentingan karena komite remunerasi kerap dipengaruhi eksekutif itu sendiri (Crane dan Matten, 2019). Sebagai respons, berkembang mekanisme <em>say on pay</em> yang memberikan hak suara kepada pemegang saham atas kebijakan remunerasi, serta kewajiban pengungkapan rasio gaji. Implikasi manajerialnya, perusahaan perlu merancang remunerasi yang berbasis kinerja jangka panjang, transparan, dan dapat dipertanggungjawabkan secara publik.</p>
      <h5>6.4.3 Etika dalam Merger dan Akuisisi</h5>
      <p>Isu ketiga menyangkut transaksi penggabungan dan pengambilalihan perusahaan. Dari perspektif pasar, akuisisi merupakan mekanisme disiplin karena manajemen yang buruk membuat harga saham murah dan perusahaan menjadi sasaran pengambilalihan. Namun, terdapat sejumlah persoalan etika yang menyertainya. Pertama, motif transaksi tidak selalu demi nilai pemegang saham, melainkan dapat didorong ambisi pribadi eksekutif untuk membangun imperium bisnis. Kedua, pengambilalihan secara paksa (<em>hostile takeover</em>) sering diikuti restrukturisasi yang mengorbankan karyawan dan komunitas lokal demi keuntungan jangka pendek pihak pengakuisisi. Ketiga, taktik pertahanan manajemen seperti <em>poison pill</em> atau pembayaran <em>greenmail</em> dapat melindungi kepentingan manajer alih-alih kepentingan pemegang saham (Crane dan Matten, 2019). Dengan demikian, evaluasi etis atas merger dan akuisisi harus menimbang bukan hanya premi harga bagi pemegang saham, melainkan juga dampaknya terhadap pemangku kepentingan yang tidak ikut menikmati premi tersebut.</p>
      <h5>6.4.4 Peran Pasar Keuangan dan Perdagangan Orang Dalam</h5>
      <p>Isu keempat berkaitan dengan integritas pasar keuangan tempat saham diperdagangkan. Pasar modal mengandaikan informasi yang wajar dan setara bagi seluruh pelaku, sehingga praktik yang merusak kesetaraan informasi dinilai tidak etis. Perdagangan orang dalam (<em>insider trading</em>) adalah jual beli efek dengan memanfaatkan informasi material yang belum tersedia bagi publik, misalnya rencana akuisisi atau laporan keuangan yang belum diumumkan. Praktik ini dinilai salah karena melanggar keadilan akses informasi, menyalahgunakan informasi yang bukan milik pribadi pelaku, dan mengikis kepercayaan investor terhadap pasar secara keseluruhan (Crane dan Matten, 2019). Selain itu, bab ini menyoroti persoalan spekulasi berlebihan melalui instrumen derivatif yang menjauhkan pasar keuangan dari ekonomi riil, serta konflik kepentingan lembaga pemeringkat kredit yang dibayar oleh pihak yang produknya mereka nilai, sebagaimana terbukti berkontribusi pada krisis keuangan global tahun 2008. Di Indonesia, larangan perdagangan orang dalam diatur dalam Undang-Undang Pasar Modal dan diawasi oleh Otoritas Jasa Keuangan, sementara kasus Jiwasraya dan Asabri memperlihatkan bagaimana pengelolaan portofolio investasi yang sarat benturan kepentingan dan manipulasi harga saham dapat merugikan pemegang polis serta keuangan negara dalam jumlah sangat besar.</p>`
    },
    {
      no: "6.5",
      title: "Pemegang Saham dan Globalisasi Pasar Keuangan",
      body: `<p>Globalisasi mengubah hubungan antara pemegang saham dan korporasi secara mendasar. Modal kini bergerak lintas negara dengan sangat cepat, perusahaan dapat mencatatkan sahamnya di beberapa bursa sekaligus, dan investor institusional global menguasai porsi besar kepemilikan korporasi di berbagai negara. Menurut Crane dan Matten (2019), perkembangan tersebut menimbulkan kesenjangan tata kelola karena pasar keuangan telah menjadi global sementara regulasinya sebagian besar masih bersifat nasional. Akibatnya, pelaku pasar dapat melakukan arbitrase regulasi dengan memindahkan aktivitas ke yurisdiksi yang aturannya paling longgar, termasuk memanfaatkan negara suaka pajak untuk meminimalkan kewajiban pajak dan menyamarkan kepemilikan.</p>
      <p>Krisis keuangan global tahun 2008 menjadi ilustrasi paling nyata dari risiko etis pasar keuangan global yang kurang terkendali. Penjualan produk sekuritisasi berbasis kredit perumahan berisiko tinggi, pemeringkatan yang terlalu murah hati, dan insentif bonus jangka pendek bagi para bankir menciptakan rantai pengalihan risiko yang pada akhirnya ditanggung masyarakat luas melalui resesi dan dana talangan pemerintah. Fenomena ini memperlihatkan masalah moral berupa privatisasi keuntungan dan sosialisasi kerugian, ketika pihak yang menikmati laba pada masa ekspansi bukanlah pihak yang menanggung beban pada masa krisis. Selain itu, kehadiran aktor-aktor baru seperti dana kekayaan negara (<em>sovereign wealth funds</em>) dan dana lindung nilai menimbulkan pertanyaan tentang transparansi dan motif politik di balik kepemilikan lintas negara.</p>
      <p>Bagi negara berkembang seperti Indonesia, globalisasi pasar keuangan membawa manfaat sekaligus kerentanan. Arus masuk modal asing memperdalam pasar modal domestik dan menurunkan biaya pendanaan, sebagaimana tampak dari peran besar investor asing di Bursa Efek Indonesia. Namun, arus modal jangka pendek yang mudah berbalik arah membuat nilai tukar dan harga aset domestik rentan terhadap gejolak global, sebagaimana dialami Indonesia pada krisis 1997 hingga 1998. Oleh karena itu, implikasi manajerial dan kebijakan dari bab ini adalah pentingnya kerja sama regulasi internasional, penguatan pengawasan makroprudensial, serta tanggung jawab moral korporasi untuk tidak mengeksploitasi celah regulasi antarnegara semata-mata demi keuntungan pemegang saham.</p>`
    },
    {
      no: "6.6",
      title: "Pemegang Saham sebagai Warga Korporasi",
      body: `<p>Selain menjadi objek perlindungan tata kelola, pemegang saham juga dapat dipandang sebagai warga korporasi yang memikul tanggung jawab atas perilaku perusahaan yang mereka miliki. Crane dan Matten (2019) menggunakan gagasan kewarganegaraan untuk menjelaskan bahwa pemegang saham memiliki semacam hak politik di dalam korporasi, yaitu hak untuk bersuara, memilih, dan meminta pertanggungjawaban pengurus. Konsekuensinya, pemegang saham tidak dapat sepenuhnya berlepas tangan dari tindakan perusahaan, karena modal merekalah yang memungkinkan tindakan tersebut terjadi. Pandangan ini melahirkan tiga arena praktik, yaitu demokrasi pemegang saham, aktivisme pemegang saham, dan investasi etis.</p>
      <h5>6.6.1 Demokrasi Pemegang Saham</h5>
      <p>Demokrasi pemegang saham merujuk pada gagasan bahwa pemegang saham selayaknya dapat memengaruhi keputusan penting perusahaan secara proporsional melalui mekanisme rapat umum dan pemungutan suara. Dalam praktiknya, demokrasi ini menghadapi berbagai kendala, antara lain apati pemegang saham kecil yang merasa suaranya tidak menentukan, dominasi investor institusional yang tidak selalu menggunakan hak suaranya secara aktif, serta struktur saham dengan hak suara berbeda yang memberi pendiri kendali melebihi porsi ekonominya. Kendala tersebut menimbulkan persoalan legitimasi, karena keputusan besar korporasi dapat dikendalikan segelintir pihak tanpa kontrol efektif dari mayoritas pemilik. Oleh karena itu, penguatan hak suara, kemudahan pemberian suara secara elektronik, dan transparansi agenda rapat menjadi agenda reformasi tata kelola di banyak negara, termasuk di Indonesia melalui platform pemungutan suara elektronik yang difasilitasi Kustodian Sentral Efek Indonesia.</p>
      <h5>6.6.2 Aktivisme Pemegang Saham</h5>
      <p>Aktivisme pemegang saham adalah penggunaan hak-hak kepemilikan secara aktif untuk mengubah perilaku perusahaan, baik dalam isu tata kelola maupun isu sosial dan lingkungan. Bentuknya beragam, mulai dari dialog privat dengan manajemen, pengajuan resolusi dalam rapat umum pemegang saham, kampanye publik, hingga pembelian saham secara sengaja oleh organisasi masyarakat sipil agar memperoleh akses bersuara di rapat pemegang saham. Crane dan Matten (2019) mencatat bahwa aktivisme semacam ini telah memaksa banyak korporasi multinasional menanggapi isu iklim, hak asasi manusia, dan rantai pasok. Contoh yang sering dirujuk adalah keberhasilan investor aktivis kecil Engine No. 1 pada tahun 2021 menempatkan komisaris beraliran transisi energi di dewan ExxonMobil dengan dukungan investor institusional besar. Implikasi manajerialnya, perusahaan perlu membangun kapasitas keterlibatan investor yang tulus dan responsif, karena mengabaikan aktivisme dapat berujung pada kekalahan dalam pemungutan suara dan kerusakan reputasi.</p>
      <h5>6.6.3 Investasi Etis dan Bertanggung Jawab Sosial</h5>
      <p>Investasi etis atau <em>socially responsible investment</em> adalah praktik menanamkan modal dengan mempertimbangkan kriteria moral, sosial, dan lingkungan di samping kriteria imbal hasil keuangan. Strategi utamanya mencakup penapisan negatif yang menghindari sektor tertentu seperti senjata, tembakau, dan perjudian, penapisan positif yang memilih perusahaan berkinerja sosial dan lingkungan terbaik di kelasnya, serta pendekatan keterlibatan aktif yang menggunakan kepemilikan untuk mendorong perbaikan. Perkembangan mutakhir dari gagasan ini adalah integrasi faktor lingkungan, sosial, dan tata kelola (<em>environmental, social, and governance</em>) ke dalam analisis investasi arus utama serta munculnya investasi berdampak yang secara sengaja mengejar dampak sosial terukur. Di Indonesia, praktik ini tercermin pada indeks SRI-KEHATI dan indeks IDX ESG Leaders di Bursa Efek Indonesia, serta pada pertumbuhan reksa dana syariah yang menerapkan penapisan berbasis prinsip keuangan Islam. Dari uraian tersebut dapat disimpulkan bahwa investasi etis mengubah pertanyaan klasik dari sekadar berapa imbal hasil yang diperoleh menjadi bagaimana imbal hasil tersebut dihasilkan.</p>
      <table class="bk-table"><caption>Tabel 6.2 Strategi Investasi Etis dan Mekanismenya</caption>
      <thead><tr><th>Strategi</th><th>Mekanisme</th><th>Contoh Penerapan</th></tr></thead>
      <tbody>
      <tr><td>Penapisan negatif</td><td>Mengecualikan sektor atau perusahaan yang dinilai merugikan masyarakat</td><td>Menghindari saham produsen senjata, tembakau, dan perjudian</td></tr>
      <tr><td>Penapisan positif</td><td>Memilih perusahaan dengan kinerja sosial dan lingkungan terbaik di kelasnya</td><td>Indeks SRI-KEHATI dan IDX ESG Leaders di Bursa Efek Indonesia</td></tr>
      <tr><td>Integrasi ESG</td><td>Memasukkan faktor lingkungan, sosial, dan tata kelola ke dalam analisis fundamental</td><td>Penilaian risiko iklim dalam valuasi emiten energi</td></tr>
      <tr><td>Keterlibatan dan aktivisme</td><td>Menggunakan hak suara dan dialog untuk mengubah perilaku emiten</td><td>Resolusi iklim investor institusional pada rapat umum pemegang saham</td></tr>
      <tr><td>Investasi berdampak</td><td>Mendanai usaha yang dampak sosialnya diukur secara eksplisit</td><td>Pendanaan keuangan mikro dan energi terbarukan</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>`
    },
    {
      no: "6.7",
      title: "Kepemilikan Saham untuk Keberlanjutan",
      body: `<p>Bagian akhir kerangka bab ini membahas bagaimana pasar modal dan kepemilikan saham dapat diarahkan untuk mendukung keberlanjutan, bukan sekadar menghindari kerugian sosial. Crane dan Matten (2019) berargumen bahwa orientasi jangka pendek pasar keuangan merupakan hambatan struktural bagi keberlanjutan, karena tekanan laba kuartalan mendorong manajemen menunda investasi lingkungan dan sosial yang manfaatnya baru terasa dalam jangka panjang. Oleh karena itu, diperlukan model kepemilikan dan pendanaan alternatif yang menyelaraskan horizon waktu investor dengan horizon waktu pembangunan berkelanjutan, misalnya kepemilikan keluarga dan yayasan yang sabar, obligasi hijau, serta dana pensiun yang menempatkan keberlanjutan sebagai bagian dari kewajiban fidusianya kepada peserta lintas generasi.</p>
      <p>Salah satu inovasi yang dibahas adalah keuangan mikro (<em>microfinance</em>), yaitu penyediaan jasa keuangan berskala kecil bagi masyarakat berpendapatan rendah yang tidak terlayani perbankan konvensional. Model Grameen Bank yang dirintis Muhammad Yunus di Bangladesh membuktikan bahwa kaum miskin, khususnya perempuan, dapat menjadi debitur yang layak dipercaya melalui mekanisme tanggung renteng kelompok. Namun, komersialisasi keuangan mikro juga menimbulkan dilema etis ketika suku bunga tinggi dan penagihan agresif justru menjerat nasabah dalam utang. Di Indonesia, semangat serupa diwujudkan melalui lembaga seperti PNM Mekaar yang melayani jutaan perempuan prasejahtera, koperasi simpan pinjam, serta platform teknologi finansial peer to peer lending seperti Amartha yang menghubungkan investor perkotaan dengan usaha mikro perempuan di pedesaan. Contoh tersebut menunjukkan bahwa penyediaan modal dapat menjadi instrumen pemberdayaan apabila dirancang dengan tata kelola dan perlindungan konsumen yang memadai.</p>
      <p>Inovasi lain adalah urun dana (<em>crowdfunding</em>), yaitu penghimpunan dana dari banyak orang dalam jumlah kecil melalui platform digital, baik dalam bentuk donasi, imbalan, pinjaman, maupun kepemilikan saham. Urun dana saham memperluas akses usaha kecil terhadap modal ekuitas sekaligus mendemokratisasi kesempatan berinvestasi yang semula terbatas pada investor besar. Otoritas Jasa Keuangan telah mengatur layanan urun dana berbasis teknologi informasi (<em>securities crowdfunding</em>) sehingga usaha kecil dan menengah Indonesia dapat menerbitkan saham atau sukuk kepada publik secara daring. Dengan demikian, perkembangan ini memperlihatkan bahwa relasi antara pemilik modal dan perusahaan terus berevolusi, dan evolusi tersebut membuka ruang bagi model kepemilikan yang lebih inklusif dan berorientasi jangka panjang. Implikasi manajerialnya, pemimpin bisnis perlu memandang struktur kepemilikan dan basis investor sebagai pilihan strategis yang menentukan kemampuan perusahaan menjalankan agenda keberlanjutannya.</p>`
    },
    {
      no: "6.8",
      title: "Rangkuman",
      body: `<p>Bab ini menegaskan bahwa hubungan antara pemegang saham dan korporasi merupakan wilayah etika bisnis yang penting, bukan sekadar persoalan teknis hukum dan keuangan. Pemegang saham memiliki hak-hak khusus atas perusahaan, namun kepemilikan saham berbeda dari kepemilikan barang pribadi sehingga klaim pemegang saham harus ditimbang bersama klaim pemangku kepentingan lain. Pemisahan kepemilikan dan pengendalian melahirkan masalah keagenan yang dijawab melalui tata kelola perusahaan, dan rezim tata kelola berbeda antarnegara sebagaimana tampak pada perbandingan model Anglo-Amerika yang berorientasi pasar dengan model Eropa Kontinental yang berorientasi jaringan pemangku kepentingan. Indonesia mengadopsi struktur dewan dua tingkat dengan tantangan khas berupa konsentrasi kepemilikan dan perlindungan pemegang saham minoritas.</p>
      <p>Isu-isu etika utama dalam tata kelola meliputi independensi dan akuntabilitas dewan terhadap eksekutif, keadilan remunerasi eksekutif, motif dan dampak sosial merger dan akuisisi, serta integritas pasar keuangan yang dirusak oleh perdagangan orang dalam, spekulasi berlebihan, dan konflik kepentingan lembaga penunjang pasar. Globalisasi memperbesar taruhannya karena pasar keuangan yang mendunia belum diimbangi regulasi global yang setara, sebagaimana diperlihatkan krisis keuangan tahun 2008 dan praktik pemanfaatan suaka pajak.</p>
      <p>Di sisi lain, pemegang saham juga dapat menjadi kekuatan perbaikan. Melalui demokrasi pemegang saham, aktivisme, dan investasi etis, pemilik modal mampu menuntut akuntabilitas dan mengarahkan korporasi pada perilaku yang lebih bertanggung jawab. Perkembangan integrasi ESG, keuangan mikro, dan urun dana menunjukkan bahwa pasar modal dapat direkayasa untuk melayani keberlanjutan. Dengan demikian, pesan utama bab ini bagi manajer dan investor adalah bahwa modal selalu membawa tanggung jawab, dan kualitas etika sebuah perekonomian sangat ditentukan oleh cara para pemilik modal menggunakan hak-haknya.</p>`
    },
    {
      no: "6.9",
      title: "Daftar Pustaka",
      body: `<p>Crane, A., Matten, D., Glozer, S. dan Spence, L. J. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford University Press.</p>
      <p>Friedman, M. (1970). The Social Responsibility of Business is to Increase its Profits. <em>The New York Times Magazine</em>, 13 September 1970.</p>
      <p>Jensen, M. C. dan Meckling, W. H. (1976). Theory of the Firm: Managerial Behavior, Agency Costs and Ownership Structure. <em>Journal of Financial Economics</em>, 3(4), 305-360.</p>
      <p>Komite Nasional Kebijakan Governansi (2021). <em>Pedoman Umum Governansi Korporat Indonesia</em>. KNKG.</p>
      <p>Otoritas Jasa Keuangan (2015). <em>Peraturan OJK Nomor 21/POJK.04/2015 tentang Penerapan Pedoman Tata Kelola Perusahaan Terbuka</em>. OJK.</p>`
    }
  ]
};
