window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[8] = {
  bab: 8,
  judul: "BAB 8 KONSUMEN DAN ETIKA BISNIS",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 8",
  lo: [
    "LO1 Menjelaskan kedudukan konsumen sebagai pemangku kepentingan perusahaan beserta hak-hak konsumen yang melekat pada hubungan pertukaran.",
    "LO2 Mengidentifikasi isu-isu etika dalam manajemen pemasaran, meliputi kebijakan produk, komunikasi pemasaran, penetapan harga, dan praktik distribusi serta penjualan.",
    "LO3 Menganalisis isu etika dalam strategi pemasaran dan riset pasar, khususnya penargetan konsumen rentan, eksklusi konsumen, dan perlindungan privasi.",
    "LO4 Menilai dampak globalisasi terhadap hubungan perusahaan dengan konsumen di pasar internasional.",
    "LO5 Menerapkan kerangka uji kedaulatan konsumen (consumer sovereignty test) untuk mengevaluasi praktik pemasaran.",
    "LO6 Menjelaskan fenomena konsumsi etis (ethical consumption) beserta keterbatasannya, termasuk peran boikot konsumen.",
    "LO7 Menguraikan konsep konsumsi berkelanjutan (sustainable consumption) dan langkah-langkah bisnis untuk mewujudkannya."
  ],
  sections: [
    {
      no: "8.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membahas hubungan antara perusahaan dengan salah satu pemangku kepentingan yang paling menentukan kelangsungan hidupnya, yaitu konsumen. Tanpa kesediaan konsumen untuk membeli produk dan jasa, tidak ada perusahaan yang mampu bertahan, sehingga hubungan dengan konsumen sering dianggap sebagai hubungan yang paling mendasar dalam bisnis. Namun, hubungan tersebut tidak selalu berjalan seimbang karena perusahaan pada umumnya menguasai informasi, sumber daya, dan keahlian pemasaran yang jauh melebihi konsumen individual. Ketimpangan inilah yang melahirkan berbagai persoalan etika yang dibahas dalam bab ini, mulai dari keamanan produk, kejujuran iklan, kewajaran harga, sampai dengan tanggung jawab bersama atas konsumsi yang berkelanjutan.</p>
      <p>Setelah mengikuti sesi ini, mahasiswa diharapkan memiliki capaian pembelajaran sebagai berikut:</p>
      <ul>
        <li>Menjelaskan kedudukan konsumen sebagai pemangku kepentingan dan hak-hak konsumen yang melekat pada hubungan pertukaran.</li>
        <li>Mengidentifikasi isu etika dalam manajemen pemasaran pada dimensi produk, komunikasi, harga, dan distribusi.</li>
        <li>Menganalisis isu etika dalam strategi pemasaran dan riset pasar, termasuk penargetan konsumen rentan dan privasi data.</li>
        <li>Menilai tantangan etika yang muncul dari globalisasi pasar konsumen.</li>
        <li>Menerapkan uji kedaulatan konsumen sebagai kerangka evaluasi praktik pemasaran.</li>
        <li>Menjelaskan konsumsi etis, boikot konsumen, serta keterbatasan keduanya.</li>
        <li>Menguraikan konsep dan strategi bisnis menuju konsumsi berkelanjutan.</li>
      </ul>`
    },
    {
      no: "8.2",
      title: "Konsumen sebagai Pemangku Kepentingan",
      body: `<p>Dalam teori pemangku kepentingan, konsumen menempati posisi istimewa karena merupakan sumber pendapatan yang menjadi alasan keberadaan perusahaan. Menurut Crane dan Matten (2019), konsumen memiliki <em>stake</em> atau kepentingan yang sah terhadap perusahaan karena mereka menyerahkan uang dan menaruh kepercayaan bahwa produk yang dibeli akan memberikan manfaat sebagaimana dijanjikan. Retorika manajemen modern juga menempatkan konsumen pada posisi terhormat melalui slogan seperti kepuasan pelanggan dan orientasi pasar. Namun, praktik bisnis sehari-hari menunjukkan bahwa kepentingan konsumen sering dikorbankan demi target penjualan, sehingga diperlukan telaah etis yang sistematis atas hubungan perusahaan dengan konsumen.</p>
      <p>Secara historis, hubungan perusahaan dengan konsumen lama diatur oleh prinsip <em>caveat emptor</em>, yang berarti pembeli harus berhati-hati dan menanggung sendiri risiko pembeliannya. Prinsip ini berangkat dari asumsi bahwa penjual dan pembeli memiliki kedudukan tawar yang setara sehingga pasar akan menghukum penjual yang curang. Namun, asumsi tersebut semakin tidak realistis dalam ekonomi modern karena produk semakin kompleks, informasi semakin asimetris, dan konsumen individual hampir tidak mungkin menilai sendiri keamanan produk seperti obat, kendaraan, atau layanan keuangan. Oleh karena itu, perkembangan pemikiran etika dan regulasi bergeser ke arah pengakuan hak-hak konsumen yang wajib dihormati oleh pelaku usaha.</p>
      <p>Gagasan hak konsumen modern umumnya dirujuk pada pidato Presiden John F. Kennedy tahun 1962 yang merumuskan empat hak dasar, yaitu hak atas produk yang aman, hak untuk memperoleh informasi yang benar, hak untuk memilih, dan hak untuk didengar. Crane dan Matten (2019) menegaskan bahwa hak konsumen berfungsi sebagai batas moral bagi praktik pemasaran karena hak tersebut tidak boleh ditukar begitu saja dengan pertimbangan keuntungan. Dalam konteks Indonesia, pengakuan tersebut diwujudkan melalui Undang-Undang Nomor 8 Tahun 1999 tentang Perlindungan Konsumen yang memuat hak atas kenyamanan, keamanan, dan keselamatan, hak atas informasi yang benar, jelas, dan jujur, serta hak untuk didengar melalui lembaga seperti Badan Penyelesaian Sengketa Konsumen. Dengan demikian, penghormatan terhadap hak konsumen bukan hanya kewajiban moral, melainkan juga kewajiban hukum bagi manajer di Indonesia.</p>
      <table class="bk-table">
        <caption>Tabel 8.1 Hak-Hak Konsumen dan Contoh Pelanggarannya</caption>
        <thead><tr><th>Hak konsumen</th><th>Makna pokok</th><th>Contoh pelanggaran</th></tr></thead>
        <tbody>
          <tr><td>Hak atas produk yang aman</td><td>Produk tidak membahayakan kesehatan dan keselamatan bila digunakan secara wajar</td><td>Menjual pangan mengandung bahan berbahaya atau kendaraan dengan cacat desain</td></tr>
          <tr><td>Hak atas informasi</td><td>Informasi produk benar, lengkap, dan tidak menyesatkan</td><td>Iklan yang melebih-lebihkan khasiat atau label yang menyembunyikan kandungan</td></tr>
          <tr><td>Hak untuk memilih</td><td>Tersedia alternatif pada harga yang kompetitif</td><td>Kartel harga atau praktik mengikat yang menutup pilihan konsumen</td></tr>
          <tr><td>Hak untuk didengar</td><td>Keluhan konsumen ditanggapi secara adil</td><td>Mengabaikan komplain dan mempersulit mekanisme ganti rugi</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
      </table>
      <p>Implikasi manajerialnya adalah bahwa perusahaan perlu memandang perlindungan konsumen sebagai investasi reputasi jangka panjang, bukan sebagai beban kepatuhan semata. Perusahaan yang secara konsisten menghormati hak konsumen akan membangun kepercayaan yang menjadi dasar loyalitas pelanggan. Di sisi lain, pelanggaran hak konsumen yang terungkap ke publik dapat menimbulkan krisis reputasi, sanksi hukum, dan boikot yang biayanya jauh melampaui keuntungan jangka pendek dari praktik yang tidak etis.</p>`
    },
    {
      no: "8.3",
      title: "Isu Etika dalam Manajemen Pemasaran",
      body: `<p>Sebagian besar persoalan etika dalam hubungan perusahaan dengan konsumen muncul dari keputusan sehari-hari manajemen pemasaran. Crane dan Matten (2019) memetakan isu tersebut mengikuti elemen bauran pemasaran, yaitu kebijakan produk, komunikasi pemasaran, penetapan harga, serta praktik distribusi dan penjualan. Pemetaan ini bermanfaat bagi manajer karena menunjukkan bahwa pertimbangan etis harus melekat pada setiap keputusan fungsional, bukan hanya pada kebijakan perusahaan di tingkat atas.</p>
      <h5>8.3.1 Kebijakan Produk dan Keamanan Produk</h5>
      <p>Isu etika paling mendasar pada dimensi produk adalah keamanan dan kesesuaian produk dengan tujuan penggunaannya. Konsumen berhak mengharapkan bahwa produk berfungsi sebagaimana dijanjikan dan tidak menimbulkan bahaya yang tidak wajar. Dalam literatur etika bisnis dikenal tiga pandangan mengenai tanggung jawab produsen atas keamanan produk. Pertama, pandangan kontrak (<em>contract view</em>) yang menyatakan tanggung jawab produsen terbatas pada apa yang dijanjikan secara eksplisit maupun implisit dalam transaksi. Kedua, pandangan kehati-hatian (<em>due care</em>) yang menuntut produsen mengambil semua langkah yang wajar untuk mencegah bahaya karena produsen memiliki pengetahuan dan keahlian yang jauh melebihi konsumen. Ketiga, pandangan biaya sosial (<em>social costs view</em>) yang membebankan seluruh biaya kerugian akibat produk kepada produsen sekalipun produsen telah berhati-hati, dengan alasan produsen adalah pihak yang paling mampu menanggung dan mencegah biaya tersebut.</p>
      <p>Dari ketiga pandangan tersebut dapat disimpulkan bahwa standar tanggung jawab produsen bergerak dari yang paling sempit menuju yang paling luas, dan praktik regulasi modern pada umumnya berada di antara pandangan kedua dan ketiga. Persoalannya, keamanan mutlak tidak pernah ada sehingga manajer harus menentukan tingkat risiko yang dapat diterima (<em>acceptable risk</em>) dengan mempertimbangkan probabilitas bahaya, tingkat keparahan, dan kemampuan konsumen memahami risiko tersebut. Sebagai contoh di Indonesia, kasus penarikan produk pangan yang tercemar dan pengawasan Badan Pengawas Obat dan Makanan atas kandungan berbahaya menunjukkan bahwa kelalaian pada tahap desain dan produksi dapat berujung pada penarikan produk secara massal. Oleh karena itu, manajer operasional dan pemasaran perlu membangun sistem manajemen mutu dan mekanisme penarikan produk yang cepat sebagai wujud prinsip kehati-hatian.</p>
      <h5>8.3.2 Komunikasi Pemasaran</h5>
      <p>Isu etika dalam komunikasi pemasaran dapat dianalisis pada dua tingkat, yaitu tingkat individual dan tingkat sosial (Crane dan Matten, 2019). Pada tingkat individual, persoalan utamanya adalah praktik yang menyesatkan dan memperdaya konsumen tertentu. Iklan dikatakan menipu apabila secara sengaja menciptakan keyakinan yang keliru di benak konsumen, misalnya melalui klaim yang tidak dapat dibuktikan, perbandingan yang tidak jujur, penyembunyian informasi penting, atau kesaksian palsu. Batas antara bujukan yang sah dengan manipulasi memang tidak selalu tegas karena sebagian besar iklan mengandung unsur melebih-lebihkan yang oleh masyarakat sudah dipahami sebagai gaya bahasa. Namun, ukuran etis yang lazim digunakan adalah apakah praktik tersebut merusak kemampuan konsumen mengambil keputusan secara rasional dan bebas.</p>
      <p>Pada tingkat sosial, kritik diarahkan pada dampak agregat industri periklanan terhadap masyarakat. Para pengkritik berpendapat bahwa periklanan secara kolektif menumbuhkan materialisme, menciptakan keinginan semu (<em>artificial wants</em>) sebagaimana dikemukakan Galbraith, memelihara ketidakpuasan permanen agar konsumen terus membeli, serta melanggengkan stereotip gender dan citra tubuh yang tidak realistis. Pembela industri menjawab bahwa iklan hanya mencerminkan nilai yang sudah ada di masyarakat dan konsumen tetap bebas menolak pesan iklan. Dengan demikian, perdebatan ini pada dasarnya adalah perdebatan tentang sejauh mana kedaulatan konsumen benar-benar bekerja. Implikasi manajerialnya, perusahaan perlu menetapkan pedoman etika komunikasi, misalnya kejujuran klaim, kehati-hatian dalam beriklan kepada anak-anak, dan penghormatan terhadap keberagaman, termasuk dalam pemasaran melalui media sosial dan pemengaruh yang wajib mengungkapkan konten berbayar.</p>
      <h5>8.3.3 Penetapan Harga</h5>
      <p>Harga merupakan titik pertemuan paling nyata antara kepentingan perusahaan dan konsumen sehingga menjadi wilayah yang sarat isu etika. Hak untuk memilih pada dasarnya mengandaikan harga yang terbentuk secara wajar melalui persaingan. Crane dan Matten (2019) mengidentifikasi empat jenis persoalan harga yang secara etis bermasalah, yaitu harga berlebihan, persekongkolan harga, harga predatoris, dan harga yang menyesatkan. Keempat praktik tersebut merugikan konsumen dengan cara yang berbeda, baik melalui pengalihan surplus konsumen secara tidak adil maupun melalui perusakan mekanisme persaingan itu sendiri.</p>
      <table class="bk-table">
        <caption>Tabel 8.2 Empat Persoalan Etika dalam Penetapan Harga</caption>
        <thead><tr><th>Jenis praktik</th><th>Uraian</th><th>Ilustrasi</th></tr></thead>
        <tbody>
          <tr><td>Harga berlebihan (<em>excessive pricing</em>)</td><td>Menetapkan harga jauh di atas nilai wajar dengan memanfaatkan posisi dominan atau kondisi darurat</td><td>Melambungkan harga masker dan obat pada masa pandemi</td></tr>
          <tr><td>Persekongkolan harga (<em>price fixing</em>)</td><td>Kesepakatan antarpesaing untuk mengatur harga sehingga meniadakan persaingan</td><td>Kartel tarif yang pernah ditindak Komisi Pengawas Persaingan Usaha di Indonesia</td></tr>
          <tr><td>Harga predatoris (<em>predatory pricing</em>)</td><td>Menjual di bawah biaya untuk menyingkirkan pesaing, lalu menaikkan harga setelah pasar dikuasai</td><td>Subsidi harga agresif untuk mematikan pelaku usaha kecil</td></tr>
          <tr><td>Harga menyesatkan (<em>deceptive pricing</em>)</td><td>Menampilkan harga yang menimbulkan persepsi keliru tentang nilai transaksi</td><td>Harga coret semu dan biaya tersembunyi pada penjualan daring</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
      </table>
      <p>Perkembangan teknologi menambah kompleksitas persoalan harga melalui praktik harga dinamis dan harga terpersonalisasi yang dihitung dari data perilaku konsumen. Praktik semacam ini efisien secara ekonomi, tetapi menimbulkan pertanyaan keadilan apabila konsumen yang lebih terdesak atau kurang melek digital justru dikenai harga lebih tinggi. Sebagai contoh, fenomena harga coret dan gimik diskon besar pada festival belanja daring di Indonesia telah mendorong pengawasan yang lebih ketat terhadap kejujuran harga acuan. Oleh karena itu, manajer perlu memastikan bahwa algoritme penetapan harga diuji secara berkala agar tidak menghasilkan diskriminasi yang tidak dapat dipertanggungjawabkan.</p>
      <h5>8.3.4 Praktik Distribusi, Penjualan, dan Hubungan Pasca Pembelian</h5>
      <p>Isu etika juga muncul pada saluran distribusi dan praktik penjualan. Dalam hubungan dengan peritel, produsen dapat menghadapi permintaan biaya penempatan produk (<em>slotting fees</em>) yang memberatkan pemasok kecil dan pada akhirnya mempersempit pilihan konsumen. Dalam penjualan langsung, teknik penjualan bertekanan tinggi, janji berlebihan tenaga penjual, dan skema piramida yang menyamar sebagai pemasaran berjenjang merupakan praktik yang mengeksploitasi ketidaktahuan konsumen. Selain itu, tanggung jawab perusahaan tidak berhenti pada saat transaksi karena layanan purnajual, garansi, dan penanganan keluhan merupakan perwujudan hak konsumen untuk didengar. Dengan demikian, evaluasi etis harus mencakup keseluruhan perjalanan konsumen mulai dari sebelum membeli sampai setelah produk digunakan.</p>`
    },
    {
      no: "8.4",
      title: "Isu Etika dalam Strategi Pemasaran dan Riset Pasar",
      body: `<p>Apabila sub-bab sebelumnya membahas keputusan taktis bauran pemasaran, sub-bab ini membahas persoalan etika pada tingkat strategi, yaitu keputusan tentang pasar mana yang dilayani dan bagaimana informasi tentang konsumen dikumpulkan. Keputusan strategis semacam ini menentukan siapa yang memperoleh manfaat dan siapa yang menanggung risiko dari aktivitas pemasaran, sehingga muatan etisnya justru lebih besar daripada keputusan taktis.</p>
      <h5>8.4.1 Penargetan Konsumen Rentan</h5>
      <p>Segmentasi dan penargetan merupakan praktik yang sah, tetapi menjadi bermasalah secara etis ketika sasarannya adalah kelompok konsumen yang rentan. Menurut Crane dan Matten (2019), kerentanan konsumen dapat bersumber dari beberapa kondisi, yaitu keterbatasan kapasitas kognitif seperti pada anak-anak, kondisi lanjut usia, kesulitan memahami informasi karena pendidikan atau bahasa, kondisi emosional seperti duka atau sakit, serta keterdesakan ekonomi. Konsumen dalam kondisi tersebut tidak sepenuhnya mampu mengambil keputusan yang rasional dan bebas, sehingga memasarkan produk secara agresif kepada mereka berarti mengeksploitasi kelemahan, bukan melayani kebutuhan. Contoh klasiknya adalah iklan makanan tidak sehat yang membidik anak-anak serta produk kredit berbunga tinggi yang membidik rumah tangga berpendapatan rendah.</p>
      <p>Fenomena pinjaman daring ilegal di Indonesia merupakan ilustrasi yang relevan karena penyedia pinjaman membidik masyarakat yang terdesak kebutuhan tunai dengan proses persetujuan instan, kemudian mengenakan bunga sangat tinggi dan menagih secara intimidatif. Kasus tersebut menunjukkan bahwa penargetan konsumen rentan dapat menimbulkan kerugian finansial sekaligus tekanan psikologis yang berat. Oleh karena itu, Otoritas Jasa Keuangan mewajibkan penilaian kelayakan dan pembatasan bunga bagi penyelenggara resmi. Implikasi manajerialnya, perusahaan perlu menelaah profil segmen sasaran dan menahan diri dari strategi yang keuntungannya bergantung pada ketidakmampuan konsumen memahami atau menolak tawaran.</p>
      <h5>8.4.2 Eksklusi Konsumen</h5>
      <p>Sisi lain dari penargetan adalah pengabaian, yaitu ketika kelompok konsumen tertentu tidak dilayani karena dianggap tidak menguntungkan. Eksklusi konsumen menjadi persoalan etika ketika produk yang bersangkutan merupakan kebutuhan dasar seperti layanan keuangan, asuransi, energi, atau konektivitas. Kelompok miskin dan penduduk wilayah terpencil sering harus membayar lebih mahal per unit layanan atau sama sekali tidak memperoleh akses. Namun, eksklusi juga membuka peluang inovasi model bisnis inklusif, sebagaimana ditunjukkan oleh perkembangan layanan keuangan digital dan agen laku pandai di Indonesia yang memperluas akses perbankan hingga ke desa. Dengan demikian, manajer dapat memandang kelompok yang terpinggirkan bukan sebagai beban, melainkan sebagai pasar yang membutuhkan rancangan produk dan saluran yang berbeda.</p>
      <h5>8.4.3 Privasi Konsumen dan Etika Riset Pasar</h5>
      <p>Riset pasar dan pemasaran berbasis data menimbulkan isu etika yang semakin penting pada era digital, yaitu perlindungan privasi. Privasi dapat dipahami sebagai hak individu untuk mengendalikan informasi tentang dirinya serta untuk bebas dari pengamatan yang tidak dikehendaki. Praktik pengumpulan jejak digital, pelacakan lintas aplikasi, dan pembuatan profil perilaku memungkinkan perusahaan mengenali konsumen secara sangat rinci, sering kali tanpa kesadaran penuh konsumen yang hanya menyetujui syarat layanan secara formalitas. Persoalan menjadi semakin serius ketika data digunakan untuk manipulasi perilaku atau bocor kepada pihak ketiga, sebagaimana terjadi pada sejumlah kebocoran data pelanggan platform digital di Indonesia yang mendorong lahirnya Undang-Undang Nomor 27 Tahun 2022 tentang Pelindungan Data Pribadi. Oleh karena itu, prinsip etis yang harus dipegang manajer meliputi persetujuan yang diberikan secara sadar, pembatasan pengumpulan data pada yang benar-benar diperlukan, transparansi tujuan penggunaan, dan keamanan penyimpanan data.</p>`
    },
    {
      no: "8.5",
      title: "Globalisasi dan Konsumen",
      body: `<p>Globalisasi memperluas hubungan perusahaan dengan konsumen melampaui batas negara dan dengan demikian melipatgandakan persoalan etikanya. Sebagaimana dibahas pada bab-bab awal, globalisasi menimbulkan ruang yang tidak sepenuhnya terjangkau oleh hukum nasional, sehingga perusahaan multinasional kerap menghadapi standar perlindungan konsumen yang berbeda-beda antarnegara. Pertanyaan etisnya adalah apakah perusahaan boleh menerapkan standar yang lebih rendah di negara yang regulasinya longgar. Praktik yang banyak dikritik antara lain menjual produk yang sudah dilarang di negara asal ke negara berkembang, memasarkan produk berisiko seperti rokok secara agresif di pasar yang pengawasannya lemah, serta menerapkan standar keamanan dan label yang tidak setara. Dari perspektif etika hak, standar ganda semacam ini sulit dibenarkan karena hak konsumen atas keamanan dan informasi tidak berkurang hanya karena yurisdiksinya berbeda.</p>
      <p>Isu kedua menyangkut penyebaran budaya konsumsi global itu sendiri. Ekspansi merek global sering dituduh melakukan homogenisasi budaya dan mendorong gaya hidup konsumtif pada masyarakat yang daya belinya terbatas, misalnya pergeseran pola makan ke makanan cepat saji yang berdampak pada kesehatan masyarakat. Di sisi lain, pembela globalisasi menunjuk manfaat berupa perluasan pilihan, penurunan harga, dan transfer standar mutu yang lebih tinggi ke pasar lokal. Bagi manajer perusahaan multinasional maupun perusahaan Indonesia yang berekspansi ke luar negeri, implikasinya adalah perlunya kebijakan global yang menetapkan standar minimum perlindungan konsumen yang berlaku di semua pasar, disertai kepekaan terhadap konteks budaya lokal dalam komunikasi pemasaran.</p>`
    },
    {
      no: "8.6",
      title: "Kedaulatan Konsumen dan Politik Pembelian",
      body: `<p>Gagasan yang mendasari pembelaan terhadap pasar bebas adalah kedaulatan konsumen (<em>consumer sovereignty</em>), yaitu keyakinan bahwa konsumenlah yang pada akhirnya mengendalikan pasar karena produsen hanya akan bertahan bila memenuhi keinginan konsumen. Apabila kedaulatan tersebut benar-benar bekerja, campur tangan etika dan regulasi dianggap tidak terlalu diperlukan. Namun, uraian pada sub-bab sebelumnya menunjukkan bahwa kedaulatan konsumen sering kali tidak terpenuhi karena adanya kerentanan, ketimpangan informasi, dan keterbatasan pilihan. Oleh karena itu, kedaulatan konsumen lebih tepat diperlakukan sebagai kondisi yang harus diuji, bukan sebagai asumsi yang diterima begitu saja.</p>
      <h5>8.6.1 Uji Kedaulatan Konsumen</h5>
      <p>Crane dan Matten (2019) mengetengahkan kerangka uji kedaulatan konsumen yang dikembangkan oleh Smith untuk menilai apakah suatu praktik pemasaran secara etis dapat diterima. Kerangka ini menilai tiga dimensi, yaitu kapabilitas konsumen, ketersediaan informasi, dan keleluasaan memilih. Cara menggunakannya adalah dengan mengajukan pertanyaan kunci pada setiap dimensi terhadap praktik yang dievaluasi; semakin lengkap ketiga dimensi terpenuhi, semakin besar keyakinan bahwa transaksi terjadi atas kehendak bebas konsumen yang tercerahkan, sehingga praktik tersebut dapat dinilai etis.</p>
      <table class="bk-table">
        <caption>Tabel 8.3 Uji Kedaulatan Konsumen</caption>
        <thead><tr><th>Dimensi</th><th>Maksud</th><th>Pertanyaan evaluatif</th></tr></thead>
        <tbody>
          <tr><td>Kapabilitas (<em>capability</em>)</td><td>Konsumen bebas dari keterbatasan yang mengganggu rasionalitas keputusan</td><td>Apakah sasaran pemasaran mengandung kelompok rentan seperti anak-anak atau orang yang terdesak?</td></tr>
          <tr><td>Informasi (<em>information</em>)</td><td>Tersedia informasi yang cukup dan benar untuk menilai apakah produk sesuai harapan</td><td>Apakah konsumen memperoleh informasi yang jujur, lengkap, dan dapat dipahami?</td></tr>
          <tr><td>Pilihan (<em>choice</em>)</td><td>Konsumen dapat berpindah ke alternatif lain tanpa hambatan yang tidak wajar</td><td>Apakah terdapat persaingan yang sehat dan biaya berpindah yang wajar?</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
      </table>
      <p>Sebagai ilustrasi penggunaan, tawaran pinjaman daring instan kepada masyarakat berpendapatan rendah dapat diuji sebagai berikut. Pada dimensi kapabilitas, sasaran berada dalam keterdesakan ekonomi sehingga kapabilitasnya rendah. Pada dimensi informasi, bunga efektif dan denda sering tidak diungkapkan secara jelas. Pada dimensi pilihan, konsumen yang ditolak lembaga formal nyaris tidak memiliki alternatif. Karena ketiga dimensi tidak terpenuhi, praktik tersebut gagal dalam uji kedaulatan konsumen dan patut dinilai tidak etis. Kerangka yang sama dapat digunakan manajer secara proaktif untuk menapis rencana kampanye pemasaran sebelum diluncurkan.</p>
      <h5>8.6.2 Konsumsi Etis dan Boikot Konsumen</h5>
      <p>Perkembangan penting dalam beberapa dekade terakhir adalah munculnya konsumen yang menggunakan keputusan belanjanya sebagai sarana menyatakan nilai moral dan politik. Konsumsi etis dapat didefinisikan sebagai pilihan konsumsi yang dilakukan secara sadar dan disengaja atas dasar keyakinan dan nilai pribadi yang bersifat moral (Crane dan Matten, 2019). Wujudnya beragam, mulai dari membeli produk ramah lingkungan, produk perdagangan yang adil, dan produk halal, sampai dengan menghindari produk perusahaan yang dinilai melanggar norma. Bentuk paling tegas dari politik pembelian adalah boikot, yaitu penolakan kolektif untuk membeli produk suatu perusahaan atau negara guna menekan perubahan perilaku. Boikot dapat bertujuan instrumental untuk memaksa perubahan kebijakan tertentu, tetapi dapat pula bersifat ekspresif sebagai pernyataan sikap moral. Pengalaman berbagai gerakan boikot di Indonesia menunjukkan bahwa dampaknya nyata terhadap penjualan dan reputasi merek, sekalipun intensitasnya sering menurun seiring waktu.</p>
      <p>Meskipun demikian, kekuatan konsumsi etis memiliki keterbatasan yang dikenal sebagai kesenjangan sikap dan perilaku (<em>attitude behaviour gap</em>), yaitu gejala bahwa konsumen yang menyatakan peduli pada etika tidak selalu mewujudkannya dalam pembelian nyata karena pertimbangan harga, kenyamanan, kebiasaan, dan keterbatasan informasi. Selain itu, kemampuan membeli secara etis tidak merata karena produk etis sering lebih mahal, sehingga muncul kritik bahwa politik pembelian memberikan suara lebih besar kepada konsumen kaya. Implikasi manajerialnya bersifat ganda, yaitu perusahaan tidak dapat mengandalkan klaim etis semata untuk memenangkan pasar, tetapi juga tidak dapat mengabaikan risiko sanksi sosial dari konsumen yang semakin kritis dan terhubung melalui media sosial.</p>`
    },
    {
      no: "8.7",
      title: "Konsumsi Berkelanjutan",
      body: `<p>Pembahasan etika konsumen pada akhirnya bermuara pada pertanyaan yang lebih mendasar, yaitu apakah tingkat dan pola konsumsi masyarakat modern dapat dipertahankan oleh daya dukung bumi. Konsumsi berkelanjutan secara umum dipahami sebagai penggunaan barang dan jasa yang memenuhi kebutuhan dasar dan meningkatkan kualitas hidup dengan meminimalkan pemakaian sumber daya alam, bahan beracun, serta emisi dan limbah sepanjang daur hidup, sehingga tidak membahayakan kebutuhan generasi mendatang. Definisi tersebut menegaskan dua hal, yaitu bahwa persoalannya bukan hanya cara memproduksi melainkan juga jumlah yang dikonsumsi, dan bahwa tanggung jawabnya dipikul bersama oleh produsen, konsumen, dan pemerintah. Bagi dunia bisnis, gagasan ini menantang logika pertumbuhan penjualan yang selama ini menjadi ukuran keberhasilan pemasaran.</p>
      <p>Tantangan konsumsi berkelanjutan sangat besar karena berhadapan dengan budaya konsumerisme yang justru diperkuat oleh pemasaran itu sendiri. Terdapat pula gejala paradoks efisiensi, yaitu perbaikan efisiensi per unit produk yang tertelan oleh kenaikan volume konsumsi total, misalnya kendaraan yang semakin hemat bahan bakar tetapi jumlah kendaraan dan jarak tempuh terus bertambah. Oleh karena itu, pendekatan yang hanya mengandalkan produk hijau tidak memadai dan diperlukan perubahan model bisnis yang lebih mendasar.</p>
      <p>Crane dan Matten (2019) menguraikan beberapa langkah bisnis menuju konsumsi berkelanjutan yang dapat dirangkum sebagai berikut:</p>
      <ul>
        <li>Penarikan kembali produk (<em>product recapture</em>), yaitu merancang sistem pengambilan kembali produk bekas untuk digunakan ulang, diproduksi ulang, atau didaur ulang sehingga tercipta lingkaran material tertutup.</li>
        <li>Penggantian produk dengan jasa, yaitu menjual fungsi atau hasil yang dibutuhkan konsumen alih-alih kepemilikan barang, misalnya menjual jasa pencahayaan atau jam pemakaian mesin.</li>
        <li>Berbagi produk (<em>product sharing</em>), yaitu meningkatkan intensitas pemakaian aset yang sama oleh banyak pengguna sebagaimana pada layanan kendaraan bersama.</li>
        <li>Pengurangan permintaan (<em>demarketing</em>), yaitu upaya sengaja untuk memoderasi konsumsi, misalnya mendorong pelanggan memperbaiki produk lama daripada membeli baru.</li>
      </ul>
      <p>Praktik di Indonesia memberikan sejumlah contoh yang relevan. Sistem galon guna ulang pada industri air minum dalam kemasan merupakan bentuk penarikan kembali kemasan yang telah berlangsung lama, sementara program penukaran limbah elektronik oleh produsen telepon seluler dan gerakan bank sampah memperluas praktik daur ulang. Selain itu, pertumbuhan layanan transportasi daring berbasis berbagi kendaraan dan penyewaan perangkat menunjukkan pergeseran dari kepemilikan menuju akses. Dengan demikian, manajer pemasaran masa depan dituntut mengukur keberhasilan bukan semata dari volume penjualan, melainkan dari nilai yang diciptakan bagi pelanggan dengan jejak sumber daya yang semakin kecil.</p>`
    },
    {
      no: "8.8",
      title: "Rangkuman",
      body: `<p>Bab ini menunjukkan bahwa konsumen merupakan pemangku kepentingan yang mendasar sekaligus rentan dalam hubungannya dengan perusahaan. Prinsip lama <em>caveat emptor</em> telah digantikan oleh pengakuan atas hak-hak konsumen, yaitu hak atas keamanan, informasi, pilihan, dan hak untuk didengar, yang di Indonesia dikukuhkan melalui Undang-Undang Perlindungan Konsumen. Isu etika muncul pada seluruh elemen manajemen pemasaran, mulai dari keamanan produk dengan tiga pandangan tanggung jawab produsen, kejujuran komunikasi pemasaran pada tingkat individual dan sosial, empat persoalan penetapan harga, sampai dengan praktik distribusi dan penjualan. Pada tingkat strategi, penargetan konsumen rentan, eksklusi konsumen dari layanan dasar, dan pelanggaran privasi data merupakan persoalan yang semakin menonjol pada era digital.</p>
      <p>Kerangka uji kedaulatan konsumen yang menilai kapabilitas, informasi, dan pilihan memberikan alat praktis bagi manajer untuk mengevaluasi apakah suatu praktik pemasaran menghormati otonomi konsumen. Di sisi lain, konsumen sendiri semakin aktif menggunakan kekuatan belanjanya melalui konsumsi etis dan boikot, meskipun efektivitasnya dibatasi oleh kesenjangan antara sikap dan perilaku. Globalisasi menuntut perusahaan menerapkan standar perlindungan konsumen yang konsisten lintas negara dan tidak memanfaatkan kelonggaran regulasi di pasar berkembang.</p>
      <p>Akhirnya, agenda konsumsi berkelanjutan menantang paradigma pemasaran yang berorientasi pada pertumbuhan volume. Melalui penarikan kembali produk, penggantian produk dengan jasa, berbagi produk, dan pengurangan permintaan, perusahaan dapat berperan aktif membentuk pola konsumsi yang selaras dengan daya dukung lingkungan. Dengan demikian, etika hubungan dengan konsumen tidak berhenti pada larangan menipu atau membahayakan, melainkan berkembang menjadi tanggung jawab bersama untuk membangun sistem konsumsi yang adil dan lestari.</p>`
    },
    {
      no: "8.9",
      title: "Daftar Pustaka",
      body: `<p>Crane, A., Matten, D., Glozer, S. dan Spence, L. J. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford University Press.</p>
      <p>Smith, N. C. (1995). Marketing Strategies for the Ethics Era. <em>Sloan Management Review</em>, 36(4), 85-97.</p>
      <p>Republik Indonesia. (1999). <em>Undang-Undang Nomor 8 Tahun 1999 tentang Perlindungan Konsumen</em>. Sekretariat Negara.</p>
      <p>Republik Indonesia. (2022). <em>Undang-Undang Nomor 27 Tahun 2022 tentang Pelindungan Data Pribadi</em>. Sekretariat Negara.</p>`
    }
  ]
};
