window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[3] = {
  bab: 3,
  judul: "BAB 3 EVALUATING BUSINESS ETHICS: TEORI ETIKA NORMATIF",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 3",
  lo: [
    "LO1 Menjelaskan peran teori etika normatif dalam mengevaluasi keputusan bisnis serta membedakan posisi absolutisme etis, relativisme etis, dan pluralisme etis.",
    "LO2 Memetakan teori etika modernis Barat ke dalam kelompok konsekuensialis dan non-konsekuensialis beserta asumsi dasar masing-masing.",
    "LO3 Menerapkan egoisme dan utilitarianisme dalam analisis situasi bisnis serta mengidentifikasi keterbatasannya.",
    "LO4 Menerapkan etika kewajiban Kant serta etika hak dan keadilan, termasuk kerangka keadilan Rawls, pada persoalan bisnis.",
    "LO5 Menguraikan perspektif alternatif berupa etika kebajikan, etika feminis, etika diskursus, dan etika postmodern sebagai pelengkap teori tradisional.",
    "LO6 Menggunakan berbagai teori etika secara pragmatis dan pluralistis sebagai kumpulan lensa analisis dalam pengambilan keputusan manajerial."
  ],
  sections: [
    {
      no: "3.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membahas perangkat konseptual yang digunakan untuk menilai apakah suatu keputusan bisnis dapat dikategorikan benar atau salah secara moral. Apabila bab-bab sebelumnya menjelaskan mengapa etika bisnis penting dan bagaimana konteks perusahaan membingkai persoalan moral, bab ini menyediakan alat evaluasinya, yaitu teori etika normatif. Teori etika normatif merupakan teori yang berupaya merumuskan aturan dan prinsip yang menentukan tindakan yang benar dan yang salah bagi pengambil keputusan (Crane dan Matten, 2019). Dengan demikian, teori-teori dalam bab ini tidak sekadar mendeskripsikan perilaku manusia, melainkan memberikan standar penilaian yang dapat dipertanggungjawabkan secara rasional.</p>
      <p>Setelah mempelajari materi pada sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <p>Pertama, menjelaskan peran teori etika dalam evaluasi keputusan bisnis serta mengkritisi posisi absolutisme dan relativisme etis untuk kemudian memahami posisi pluralisme etis. Kedua, memetakan teori etika modernis Barat ke dalam kelompok konsekuensialis dan non-konsekuensialis. Ketiga, menerapkan egoisme, utilitarianisme, etika kewajiban, serta etika hak dan keadilan pada situasi bisnis nyata, termasuk konteks Indonesia. Keempat, menguraikan perspektif alternatif berupa etika kebajikan, etika feminis, etika diskursus, dan etika postmodern. Kelima, menggunakan seluruh teori tersebut secara pragmatis sebagai kumpulan lensa yang saling melengkapi dalam pengambilan keputusan manajerial.</p>`
    },
    {
      no: "3.2",
      title: "Peran Teori Etika: Absolutisme, Relativisme, dan Pluralisme",
      body: `<p>Sebelum membahas teori satu per satu, perlu dipahami terlebih dahulu untuk apa teori etika digunakan dalam bisnis. Dalam praktik, manajer jarang mengambil keputusan moral dengan membuka buku filsafat. Namun, setiap argumen yang dipakai manajer untuk membenarkan keputusannya, misalnya alasan bahwa suatu kebijakan memberikan manfaat terbesar bagi perusahaan dan masyarakat, sesungguhnya merupakan cerminan dari teori etika tertentu. Oleh karena itu, penguasaan teori etika normatif membantu manajer menyadari asumsi moral di balik argumennya sendiri, menguji konsistensi argumen tersebut, dan mengomunikasikan pertimbangan moral secara lebih sistematis kepada pemangku kepentingan.</p>
      <p>Terdapat dua posisi ekstrem mengenai status teori etika. Posisi pertama adalah <em>ethical absolutism</em>, yaitu pandangan bahwa terdapat prinsip moral yang berlaku abadi dan universal sehingga benar dan salah merupakan kualitas objektif yang dapat ditentukan secara rasional tanpa memandang konteks (Crane dan Matten, 2019). Teori-teori modernis tradisional pada umumnya berdiri pada posisi ini karena masing-masing mengklaim satu prinsip tunggal yang berlaku untuk semua situasi. Posisi kedua adalah <em>ethical relativism</em>, yaitu pandangan bahwa moralitas bergantung pada konteks dan subjektif sifatnya, sehingga tidak ada standar universal yang dapat dipakai untuk menilai moralitas orang lain atau budaya lain. Relativisme sering muncul dalam bisnis internasional melalui ungkapan bahwa praktik lokal harus diikuti di tempat praktik itu berlaku. Namun, relativisme yang konsisten akan berujung pada ketidakmampuan mengkritik praktik apa pun, termasuk korupsi atau pekerja anak, selama praktik tersebut diterima secara lokal.</p>
      <p>Crane dan Matten (2019) menawarkan jalan tengah berupa <em>ethical pluralism</em>. Pluralisme menerima bahwa terdapat lebih dari satu sudut pandang moral yang masuk akal, sekaligus menegaskan bahwa tetap ada konsensus mengenai sejumlah prinsip dasar sehingga tidak semua pandangan sama benarnya. Dari uraian tersebut dapat disimpulkan bahwa pluralisme memandang teori-teori etika bukan sebagai mesin kebenaran tunggal, melainkan sebagai sekumpulan lensa yang masing-masing menyoroti aspek berbeda dari suatu masalah moral. Selain itu, perlu dicatat bahwa sumber pertimbangan moral tidak hanya berasal dari filsafat sekuler Barat. Ajaran agama, termasuk etika bisnis Islam yang sangat relevan di Indonesia, serta tradisi etika Timur, juga menyediakan prinsip normatif bagi pelaku bisnis, meskipun fokus bab ini adalah teori modernis Barat yang paling banyak dipakai dalam literatur etika bisnis internasional.</p>
      <p>Implikasi manajerial dari posisi pluralis cukup jelas. Manajer multinasional yang beroperasi di Indonesia, misalnya, tidak dapat berlindung di balik relativisme dengan alasan bahwa gratifikasi merupakan kebiasaan setempat, karena prinsip antikorupsi telah menjadi konsensus lintas budaya yang dikukuhkan dalam regulasi seperti Undang-Undang Tindak Pidana Korupsi. Di sisi lain, manajer juga tidak perlu memaksakan satu kerangka moral kantor pusat secara kaku tanpa mempertimbangkan kearifan lokal. Dengan demikian, kematangan moral manajerial terletak pada kemampuan menimbang berbagai perspektif secara terbuka dan tetap berpegang pada prinsip dasar yang disepakati bersama.</p>`
    },
    {
      no: "3.3",
      title: "Peta Teori Etika Modernis Barat",
      body: `<p>Teori etika modernis Barat dapat dikelompokkan berdasarkan dasar penilaian moralnya. Kelompok pertama adalah teori <em>consequentialist</em>, yang menilai benar salahnya tindakan dari akibat atau hasil yang ditimbulkannya. Kelompok ini sering disebut teleologis, dari kata Yunani <em>telos</em> yang berarti tujuan. Kelompok kedua adalah teori <em>non-consequentialist</em>, yang menilai moralitas tindakan dari sifat tindakan itu sendiri serta prinsip yang mendasarinya, terlepas dari akibatnya. Kelompok ini sering disebut deontologis, dari kata Yunani <em>deon</em> yang berarti kewajiban (Crane dan Matten, 2019). Perbedaan mendasar ini menentukan pertanyaan yang diajukan setiap teori: teori konsekuensialis bertanya mengenai hasil apa yang dihasilkan suatu keputusan, sedangkan teori non-konsekuensialis bertanya mengenai motif dan prinsip apa yang mendasari keputusan tersebut.</p>
      <p>Dalam kelompok konsekuensialis terdapat dua teori utama, yaitu egoisme yang berfokus pada akibat bagi pengambil keputusan sendiri, dan utilitarianisme yang berfokus pada akibat bagi semua pihak yang terkena dampak. Dalam kelompok non-konsekuensialis terdapat etika kewajiban yang dikembangkan Immanuel Kant serta etika hak dan keadilan yang berakar pada pemikiran John Locke dan dikembangkan antara lain oleh John Rawls. Untuk memudahkan pemahaman, peta keempat teori tersebut disajikan pada Tabel 3.1 berikut.</p>
      <table class="bk-table"><caption>Tabel 3.1 Peta Teori Etika Modernis Barat</caption>
      <thead><tr><th>Aspek</th><th>Egoisme</th><th>Utilitarianisme</th><th>Etika Kewajiban</th><th>Etika Hak dan Keadilan</th></tr></thead>
      <tbody>
      <tr><td>Kelompok</td><td>Konsekuensialis</td><td>Konsekuensialis</td><td>Non-konsekuensialis</td><td>Non-konsekuensialis</td></tr>
      <tr><td>Fokus penilaian</td><td>Akibat bagi pengambil keputusan</td><td>Akibat agregat bagi seluruh pihak</td><td>Motif dan prinsip universal</td><td>Hak dasar individu dan distribusi yang adil</td></tr>
      <tr><td>Tokoh utama</td><td>Adam Smith</td><td>Jeremy Bentham, John Stuart Mill</td><td>Immanuel Kant</td><td>John Locke, John Rawls</td></tr>
      <tr><td>Pertanyaan kunci</td><td>Apakah tindakan ini memajukan kepentingan jangka panjang saya</td><td>Apakah tindakan ini memaksimalkan manfaat bersih bagi masyarakat</td><td>Apakah prinsip tindakan ini dapat diuniversalkan dan menghormati martabat manusia</td><td>Apakah hak semua pihak dihormati dan prosedur serta hasilnya adil</td></tr>
      <tr><td>Konsep manusia</td><td>Manusia dengan kehendak bebas mengejar kepentingan diri</td><td>Manusia hedonis penimbang manfaat dan biaya</td><td>Aktor rasional yang bermoral karena kewajiban</td><td>Manusia sebagai pemegang hak kodrati</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>
      <p>Perlu ditekankan bahwa keempat teori tersebut lahir dari periode pencerahan Eropa yang mengedepankan rasionalitas dan pencarian aturan yang berlaku umum. Oleh karena itu, keempatnya berbagi ciri khas modernisme, yaitu keyakinan bahwa masalah moral dapat diselesaikan melalui penerapan prinsip abstrak yang objektif. Ciri inilah yang kelak dikritik oleh perspektif alternatif yang dibahas pada Sub-bab 3.6, yang menilai bahwa moralitas juga menyangkut karakter, relasi, proses komunikasi, dan intuisi moral yang tidak selalu tertangkap oleh aturan abstrak.</p>`
    },
    {
      no: "3.4",
      title: "Teori Konsekuensialis: Egoisme dan Utilitarianisme",
      body: `<h5>3.4.1 Egoisme</h5>
      <p>Egoisme merupakan teori tertua dalam tradisi konsekuensialis. Menurut teori ini, suatu tindakan dapat diterima secara moral apabila pengambil keputusan secara bebas memutuskan tindakan tersebut untuk mengejar kepentingan dirinya sendiri, baik berupa keinginan jangka pendek maupun kepentingan jangka panjang yang dipertimbangkan secara tercerahkan (Crane dan Matten, 2019). Landasan ekonomi egoisme dapat ditelusuri pada pemikiran Adam Smith mengenai <em>invisible hand</em>, yaitu gagasan bahwa pengejaran kepentingan diri oleh masing-masing pelaku pasar, dalam kerangka persaingan yang sehat, justru menghasilkan kesejahteraan kolektif tanpa harus diniatkan. Dalam versi yang lebih halus, egoisme tercerahkan atau <em>enlightened egoism</em> mengakui bahwa kepentingan jangka panjang perusahaan sering kali menuntut perilaku yang tampak altruistik, misalnya menjaga reputasi, membina hubungan baik dengan masyarakat, dan mematuhi hukum.</p>
      <p>Mekanisme penilaian egoisme sederhana: manajer cukup bertanya apakah suatu tindakan memajukan kepentingan dirinya atau perusahaannya. Contohnya, perusahaan rintisan di Indonesia yang memberikan subsidi besar kepada konsumen dapat dibenarkan secara egoistik karena strategi tersebut membangun pangsa pasar jangka panjang. Namun, kelemahan egoisme juga nyata. Pertama, mekanisme pasar sebagai penyeimbang kepentingan diri hanya bekerja bila pasar berfungsi sempurna, padahal eksternalitas seperti pencemaran lingkungan tidak terinternalisasi oleh pasar. Kasus pencemaran sungai oleh limbah industri tekstil di beberapa daerah aliran sungai di Jawa menunjukkan bahwa pengejaran laba tanpa koreksi dapat merugikan pihak yang tidak ikut bertransaksi. Kedua, egoisme sulit membedakan kepentingan diri yang sah dari keserakahan yang merusak, sebagaimana tampak pada berbagai skandal keuangan korporasi. Oleh karena itu, egoisme lebih tepat dipandang sebagai penjelasan atas perilaku bisnis daripada pembenaran moral yang memadai.</p>
      <h5>3.4.2 Utilitarianisme</h5>
      <p>Utilitarianisme yang dikembangkan Jeremy Bentham dan John Stuart Mill menilai moralitas tindakan dari akibatnya bagi seluruh pihak yang terkena dampak, bukan hanya bagi pelakunya. Prinsip dasarnya dikenal sebagai <em>greatest happiness principle</em>, yaitu bahwa tindakan yang benar secara moral adalah tindakan yang menghasilkan jumlah kebahagiaan terbesar bagi jumlah orang terbanyak (Crane dan Matten, 2019). Terdapat dua tafsir mengenai isi utilitas: pandangan hedonistik menekankan kesenangan dan ketiadaan penderitaan, sedangkan pandangan eudaimonistik yang lebih luas memasukkan kebahagiaan dan kesejahteraan hidup secara menyeluruh. Dalam praktik bisnis, utilitarianisme mewujud dalam analisis biaya manfaat atau <em>cost-benefit analysis</em> yang lazim digunakan untuk mengevaluasi proyek dan kebijakan publik.</p>
      <p>Cara menggunakan kerangka utilitarian dapat dirumuskan dalam empat langkah, yaitu: pertama, mengidentifikasi seluruh pihak yang terkena dampak keputusan; kedua, memperkirakan manfaat atau kesenangan yang diterima setiap pihak; ketiga, memperkirakan biaya atau penderitaan yang ditanggung setiap pihak; keempat, menjumlahkan seluruh manfaat dan biaya lalu memilih alternatif dengan utilitas bersih terbesar. Sebagai ilustrasi, keputusan relokasi pabrik dari Jabodetabek ke Jawa Tengah untuk menekan biaya tenaga kerja dapat dianalisis dengan menimbang penderitaan karyawan yang terkena pemutusan hubungan kerja terhadap manfaat bagi pemegang saham, konsumen yang menikmati harga lebih murah, dan masyarakat lokasi baru yang memperoleh lapangan kerja. Analisis semacam ini memaksa manajer memperhitungkan pihak yang sering terabaikan, dan itulah kekuatan utama utilitarianisme.</p>
      <p>Namun, utilitarianisme mengandung sejumlah masalah mendasar. Pertama adalah masalah subjektivitas, karena penilaian atas kesenangan dan penderitaan bergantung pada sudut pandang penilai. Kedua adalah masalah kuantifikasi, karena banyak biaya dan manfaat, misalnya kesehatan, martabat, atau kelestarian budaya, sulit diberi nilai moneter. Ketiga adalah masalah distribusi utilitas, karena fokus pada utilitas agregat dapat membenarkan pengorbanan minoritas demi kepentingan mayoritas. Untuk menjawab kritik tersebut dikembangkan pembedaan antara <em>act utilitarianism</em> yang menilai setiap tindakan tunggal berdasarkan akibatnya, dan <em>rule utilitarianism</em> yang menilai apakah suatu aturan umum, bila diikuti secara konsisten, menghasilkan utilitas terbesar bagi masyarakat (Crane dan Matten, 2019). Utilitarianisme aturan lebih dekat dengan praktik manajerial karena perusahaan bekerja dengan kebijakan dan kode etik, bukan keputusan kasus per kasus semata. Dengan demikian, manajer yang menggunakan lensa utilitarian tetap perlu melengkapi analisisnya dengan pertimbangan hak dan keadilan agar kelompok rentan tidak dikorbankan atas nama manfaat agregat.</p>`
    },
    {
      no: "3.5",
      title: "Teori Non-Konsekuensialis: Etika Kewajiban serta Etika Hak dan Keadilan",
      body: `<h5>3.5.1 Etika Kewajiban Immanuel Kant</h5>
      <p>Etika kewajiban berangkat dari keyakinan Immanuel Kant bahwa moralitas tidak boleh digantungkan pada akibat yang tidak pasti, melainkan pada prinsip yang dapat dipegang oleh setiap makhluk rasional. Menurut Kant, manusia adalah aktor rasional yang mampu menentukan prinsip moralnya sendiri, sehingga moralitas bersumber dari kewajiban yang ditetapkan akal budi, bukan dari perintah eksternal atau perhitungan untung rugi (Crane dan Matten, 2019). Kant merumuskan kerangka ujinya dalam <em>categorical imperative</em>, yaitu perintah moral tanpa syarat yang berlaku bagi semua orang dalam semua situasi.</p>
      <p>Imperatif kategoris terdiri atas tiga rumusan pokok yang dapat digunakan manajer sebagai uji tiga langkah. Rumusan pertama adalah uji konsistensi atau universalisasi: bertindaklah hanya menurut prinsip yang secara konsisten dapat diangkat menjadi hukum universal. Praktik menyuap pejabat untuk memenangkan tender, misalnya, gagal dalam uji ini karena apabila semua peserta tender menyuap, mekanisme tender itu sendiri kehilangan makna. Rumusan kedua adalah uji martabat manusia: perlakukan kemanusiaan, baik pada diri sendiri maupun orang lain, selalu sebagai tujuan pada dirinya dan tidak pernah semata-mata sebagai alat. Praktik mempekerjakan buruh dengan upah di bawah ketentuan minimum dan jam kerja berlebihan memperlakukan manusia sekadar sebagai faktor produksi sehingga melanggar rumusan ini. Rumusan ketiga adalah uji universalitas atau publisitas: prinsip tindakan harus dapat diterima oleh setiap makhluk rasional, yang secara praktis dapat diuji dengan pertanyaan apakah manajer bersedia keputusannya diberitakan secara terbuka di media massa. Uji ketiga ini sering disebut <em>New York Times test</em> dalam praktik manajemen, dan dalam konteks Indonesia dapat dibayangkan sebagai kesediaan manajer melihat keputusannya menjadi tajuk berita nasional.</p>
      <p>Kekuatan etika Kant terletak pada penghormatan tanpa kompromi terhadap martabat manusia serta kejelasan prosedur pengujiannya. Namun, teori ini juga menuai kritik. Pertama, Kant dinilai terlalu optimistis terhadap kemampuan rasional manusia dalam situasi nyata yang penuh tekanan. Kedua, pengabaian total terhadap akibat dapat menghasilkan keputusan yang kaku, misalnya kewajiban berkata jujur meskipun kejujuran itu mendatangkan bahaya besar. Ketiga, penerapan tiga rumusan pada kasus bisnis yang kompleks sering menimbulkan ambiguitas mengenai prinsip mana yang sedang diuji. Meskipun demikian, bagi manajer, kerangka Kant tetap menjadi penyeimbang penting terhadap dominasi logika biaya manfaat.</p>
      <h5>3.5.2 Etika Hak</h5>
      <p>Etika hak berakar pada gagasan John Locke mengenai hak kodrati, yaitu hak atas hidup, kebebasan, dan kepemilikan yang melekat pada setiap manusia sejak lahir. Dalam perkembangannya, gagasan ini menjelma menjadi konsep hak asasi manusia yang diakui secara internasional melalui Deklarasi Universal Hak Asasi Manusia. Berbeda dengan etika kewajiban yang berangkat dari kewajiban pelaku, etika hak berangkat dari klaim sah pihak lain: hak seseorang menimbulkan kewajiban pada pihak lain untuk menghormatinya (Crane dan Matten, 2019). Dari kedua sudut pandang tersebut dapat disimpulkan bahwa hak dan kewajiban merupakan dua sisi dari mata uang yang sama.</p>
      <p>Dalam konteks bisnis, etika hak mewujud dalam isu hak pekerja atas kondisi kerja yang layak, hak konsumen atas keamanan produk dan privasi data, serta hak masyarakat lokal atas lingkungan hidup yang sehat. Contoh Indonesia yang relevan adalah perdebatan mengenai status dan perlindungan sosial pengemudi ojek daring, yang menyangkut hak atas penghidupan layak di tengah model kemitraan platform digital. Selain itu, ekspansi industri ekstraktif seperti pertambangan nikel di kawasan timur Indonesia menghadirkan ketegangan antara manfaat ekonomi nasional dan hak masyarakat adat atas tanah serta lingkungan hidupnya. Lensa hak menuntut manajer menetapkan batas yang tidak boleh dilanggar sekalipun pelanggarannya menjanjikan manfaat agregat yang besar.</p>
      <h5>3.5.3 Etika Keadilan dan Kerangka Rawls</h5>
      <p>Keadilan berkaitan dengan perlakuan yang setara dan distribusi beban serta manfaat yang wajar di antara para pihak. Literatur membedakan dua wajah keadilan, yaitu <em>procedural justice</em> yang menilai kewajaran proses pengambilan keputusan, dan <em>distributive justice</em> yang menilai kewajaran hasil akhirnya. Pandangan mengenai distribusi yang adil beragam: kaum egalitarian menekankan pembagian yang merata, kaum libertarian seperti Robert Nozick menekankan keabsahan proses perolehan sehingga ketimpangan hasil pasar yang bebas dianggap adil, sedangkan pandangan berbasis kebutuhan dan jasa menimbang kondisi serta kontribusi masing-masing pihak.</p>
      <p>Kontribusi paling berpengaruh datang dari John Rawls melalui teori keadilan sebagai kewajaran atau <em>justice as fairness</em>. Rawls mengajukan eksperimen pikiran berupa <em>veil of ignorance</em>: prinsip keadilan yang sahih adalah prinsip yang akan disepakati orang-orang rasional apabila mereka tidak mengetahui posisi sosial, kekayaan, dan bakat yang kelak mereka miliki. Dari posisi asali tersebut, Rawls menurunkan dua prinsip. Prinsip pertama menyatakan bahwa setiap orang berhak atas kebebasan dasar seluas mungkin yang setara bagi semua. Prinsip kedua menyatakan bahwa ketimpangan sosial dan ekonomi hanya dapat dibenarkan apabila melekat pada posisi yang terbuka bagi semua orang dalam kesetaraan kesempatan yang adil, dan apabila ketimpangan tersebut memberikan manfaat terbesar bagi anggota masyarakat yang paling tidak beruntung, yang dikenal sebagai <em>difference principle</em> (Crane dan Matten, 2019). Cara memakai kerangka ini dalam bisnis cukup praktis: manajer menguji suatu kebijakan, misalnya struktur remunerasi eksekutif atau skema kemitraan pemasok kecil, dengan bertanya apakah kebijakan itu akan tetap disetujui seandainya perancangnya tidak tahu akan berada di posisi mana. Dengan demikian, kerangka Rawls menyediakan penangkal terhadap bias kepentingan yang hampir selalu hadir dalam perumusan kebijakan perusahaan.</p>`
    },
    {
      no: "3.6",
      title: "Perspektif Alternatif terhadap Teori Etika Tradisional",
      body: `<p>Teori-teori modernis pada Sub-bab 3.4 dan 3.5 memiliki keterbatasan bersama, yaitu terlalu abstrak, terlalu menyederhanakan masalah moral ke dalam satu prinsip tunggal, terlalu objektif dan elitis karena mengabaikan pertimbangan pelaku di lapangan, serta terlalu impersonal karena mengabaikan relasi dan karakter (Crane dan Matten, 2019). Keterbatasan tersebut mendorong lahirnya sejumlah perspektif alternatif yang menempatkan pelaku, relasi, dan proses sebagai pusat perhatian. Perspektif alternatif tidak dimaksudkan menggantikan teori tradisional, melainkan melengkapinya.</p>
      <h5>3.6.1 Etika Kebajikan</h5>
      <p>Etika kebajikan atau <em>virtue ethics</em> yang berakar pada pemikiran Aristoteles menggeser pertanyaan moral dari tindakan ke pelaku. Pertanyaannya bukan lagi tindakan apa yang benar, melainkan pribadi seperti apa yang seharusnya dibentuk. Menurut pandangan ini, tindakan bermoral lahir dari karakter berbudi yang ditempa melalui kebiasaan, dan tujuan akhirnya adalah <em>eudaimonia</em>, yaitu kehidupan yang berkembang penuh dan bermakna, bukan sekadar kesenangan sesaat. Kebajikan terdiri atas kebajikan intelektual seperti kebijaksanaan praktis dan kebajikan moral seperti kejujuran, keberanian, kesetiaan, dan kesederhanaan. Kebajikan tidak dipelajari dari buku semata, melainkan dibentuk dalam komunitas praktik, sehingga budaya organisasi dan keteladanan pemimpin menjadi penentu utama. Implikasi manajerialnya, perusahaan perlu merancang proses rekrutmen, promosi, dan penghargaan yang menumbuhkan karakter, bukan hanya kepatuhan formal terhadap aturan. Tradisi perusahaan keluarga di Indonesia yang menjunjung nilai kepercayaan antargenerasi dalam jaringan dagang merupakan contoh bagaimana kebajikan tumbuh dalam komunitas praktik bisnis.</p>
      <h5>3.6.2 Etika Feminis dan Etika Kepedulian</h5>
      <p>Etika feminis mengkritik teori tradisional yang menyelesaikan konflik moral melalui prinsip abstrak dan impersonal. Sebagai gantinya, pendekatan ini mengutamakan empati, keharmonisan relasi, tanggung jawab sosial yang konkret, serta perhatian pada situasi khusus setiap pihak, yang terangkum dalam konsep <em>ethics of care</em> (Crane dan Matten, 2019). Dalam bisnis, lensa kepedulian mengubah cara pandang terhadap pemangku kepentingan: mereka bukan sekadar pemegang klaim yang harus ditimbang, melainkan pihak yang berada dalam jaringan relasi yang perlu dirawat. Contohnya, ketika perusahaan Indonesia terpaksa melakukan efisiensi, pendekatan kepedulian menuntut proses yang menjaga martabat karyawan melalui komunikasi yang jujur, pendampingan alih kerja, dan perhatian pada kondisi keluarga karyawan, bukan sekadar pemenuhan pesangon minimal menurut aturan.</p>
      <h5>3.6.3 Etika Diskursus</h5>
      <p>Etika diskursus atau <em>discourse ethics</em> yang dikembangkan dari pemikiran Juergen Habermas berpandangan bahwa dalam masyarakat majemuk, norma yang sahih tidak dapat ditetapkan sepihak oleh filsuf atau manajer, melainkan harus dihasilkan melalui dialog yang rasional dan setara di antara para pihak yang terdampak. Suatu norma dianggap sah apabila semua pihak yang berkepentingan dapat menyetujuinya dalam dialog yang bebas dari tekanan kekuasaan, yang disebut situasi tutur ideal. Penerapannya dalam bisnis tampak pada mekanisme dialog pemangku kepentingan, musyawarah dengan masyarakat lingkar tambang, forum bipartit antara manajemen dan serikat pekerja, serta konsultasi publik dalam penyusunan analisis dampak lingkungan. Implikasi manajerialnya, kualitas moral suatu keputusan tidak hanya dinilai dari isinya, melainkan juga dari proses partisipatif yang menghasilkannya.</p>
      <h5>3.6.4 Etika Postmodern</h5>
      <p>Etika postmodern, yang terutama diasosiasikan dengan Zygmunt Bauman, menaruh curiga pada segala bentuk aturan moral yang dirasionalisasi, karena birokrasi dan aturan justru dapat menumpulkan tanggung jawab moral pribadi. Pandangan ini menekankan <em>moral impulse</em>, yaitu dorongan moral batiniah dan emosional yang muncul ketika seseorang berhadapan langsung dengan sesamanya. Crane dan Matten (2019) menegaskan inti pandangan ini dengan menyatakan bahwa etika postmodern "melampaui akal budi menuju keyakinan moral batiniah dan dorongan emosional para pelaku moral". Bagi praktik manajemen, pesan pentingnya adalah bahwa kepatuhan penuh terhadap prosedur tidak pernah membebaskan individu dari tanggung jawab moral pribadinya. Skandal korporasi besar sering terjadi justru ketika setiap orang merasa hanya menjalankan tugas kecil dalam sistem yang besar. Oleh karena itu, manajer perlu menjaga kedekatan dengan dampak nyata keputusannya, misalnya dengan turun langsung menemui pekerja pabrik pemasok, agar dorongan moralnya tidak dibungkam oleh jarak birokratis.</p>`
    },
    {
      no: "3.7",
      title: "Penggunaan Pragmatis Teori Etika Normatif",
      body: `<p>Setelah seluruh teori diuraikan, pertanyaan praktisnya adalah bagaimana manajer menggunakan semuanya. Crane dan Matten (2019) menganjurkan sikap pluralisme pragmatis: alih-alih memilih satu teori sebagai kebenaran tunggal, pengambil keputusan sebaiknya memperlakukan setiap teori sebagai lensa atau prisma yang menyoroti aspek berbeda dari masalah yang sama. Egoisme menyoroti kepentingan dan insentif pelaku, utilitarianisme menyoroti akibat bagi seluruh pihak, etika kewajiban menyoroti prinsip dan martabat manusia, etika hak dan keadilan menyoroti klaim sah serta kewajaran distribusi, sedangkan perspektif alternatif menyoroti karakter, relasi, proses dialog, dan tanggung jawab pribadi. Dengan menyusun pertanyaan dari setiap lensa, manajer memperoleh peta persoalan yang jauh lebih kaya daripada bila hanya mengandalkan intuisi atau perhitungan finansial.</p>
      <table class="bk-table"><caption>Tabel 3.2 Lensa Pertanyaan Manajerial dari Setiap Teori Etika</caption>
      <thead><tr><th>Teori</th><th>Pertanyaan manajerial kunci</th></tr></thead>
      <tbody>
      <tr><td>Egoisme</td><td>Apakah keputusan ini benar-benar melayani kepentingan jangka panjang perusahaan, termasuk reputasinya</td></tr>
      <tr><td>Utilitarianisme</td><td>Siapa saja yang terdampak, dan apakah manfaat bersih bagi seluruh pihak lebih besar daripada kerugiannya</td></tr>
      <tr><td>Etika kewajiban</td><td>Apakah prinsip keputusan ini dapat diuniversalkan, menghormati martabat manusia, dan layak diberitakan secara terbuka</td></tr>
      <tr><td>Etika hak</td><td>Apakah ada hak dasar karyawan, konsumen, atau masyarakat yang dilanggar</td></tr>
      <tr><td>Etika keadilan</td><td>Apakah prosedur dan distribusi hasilnya tetap kita setujui seandainya kita tidak tahu berada di posisi mana</td></tr>
      <tr><td>Etika kebajikan</td><td>Apakah keputusan ini mencerminkan karakter organisasi yang ingin kita bangun</td></tr>
      <tr><td>Etika kepedulian</td><td>Bagaimana keputusan ini memengaruhi relasi konkret dengan pihak yang paling rentan</td></tr>
      <tr><td>Etika diskursus</td><td>Apakah pihak yang terdampak telah didengar dalam dialog yang setara</td></tr>
      <tr><td>Etika postmodern</td><td>Apa kata hati nurani saya bila berhadapan langsung dengan pihak yang menanggung akibatnya</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>
      <p>Sebagai ilustrasi penerapan menyeluruh, pertimbangkan keputusan sebuah platform digital Indonesia untuk memanfaatkan data perilaku pengguna dalam penawaran produk pinjaman daring. Lensa egoisme menunjukkan potensi pendapatan dan risiko reputasi. Lensa utilitarian menimbang manfaat akses kredit yang lebih luas terhadap bahaya jerat utang bagi pengguna berliterasi keuangan rendah. Lensa Kant menguji apakah praktik pemanfaatan data tanpa persetujuan yang jelas dapat diuniversalkan dan apakah pengguna diperlakukan sekadar sebagai alat monetisasi. Lensa hak menyoroti hak privasi yang dijamin Undang-Undang Pelindungan Data Pribadi. Lensa Rawls menanyakan apakah skema bunga dan penagihan tetap disetujui perancangnya seandainya ia sendiri menjadi peminjam paling rentan. Lensa diskursus menuntut konsultasi dengan perwakilan konsumen dan regulator, sedangkan lensa kepedulian dan kebajikan menyoroti relasi jangka panjang dengan pengguna serta karakter perusahaan yang hendak dibangun. Hasil analisis berlapis semacam ini memberikan dasar keputusan yang jauh lebih kokoh dan dapat dipertanggungjawabkan kepada seluruh pemangku kepentingan.</p>
      <p>Perlu diakui bahwa penggunaan banyak lensa dapat menghasilkan kesimpulan yang saling bertentangan, misalnya ketika analisis utilitarian membenarkan sesuatu yang dilarang oleh analisis hak. Ketegangan semacam itu bukan kelemahan metode, melainkan cerminan dari kompleksitas moral yang sesungguhnya. Dalam situasi demikian, manajer dituntut menggunakan pertimbangan praktis yang matang, mendokumentasikan alasan pilihannya, dan bersikap terbuka terhadap koreksi. Dengan demikian, teori etika normatif berfungsi bukan sebagai mesin penghasil jawaban otomatis, melainkan sebagai disiplin berpikir yang menjadikan pertimbangan moral manajerial lebih sistematis, lebih inklusif, dan lebih dapat diaudit.</p>`
    },
    {
      no: "3.8",
      title: "Rangkuman",
      body: `<p>Bab ini menguraikan teori etika normatif sebagai perangkat evaluasi moral atas keputusan bisnis. Pembahasan diawali dengan penolakan terhadap dua posisi ekstrem, yaitu absolutisme yang memaksakan satu kebenaran universal dan relativisme yang menolak segala standar lintas konteks, untuk kemudian mengambil posisi pluralisme etis yang memandang berbagai teori sebagai lensa yang saling melengkapi. Teori modernis Barat dipetakan ke dalam kelompok konsekuensialis, yang mencakup egoisme dan utilitarianisme, serta kelompok non-konsekuensialis, yang mencakup etika kewajiban Kant serta etika hak dan keadilan termasuk kerangka Rawls. Setiap teori menawarkan pertanyaan uji yang khas, mulai dari perhitungan manfaat bersih, uji universalisasi dan martabat manusia, penghormatan hak dasar, hingga uji kewajaran di balik tirai ketidaktahuan.</p>
      <p>Selanjutnya, keterbatasan teori tradisional yang abstrak dan impersonal dijawab oleh empat perspektif alternatif. Etika kebajikan menekankan pembentukan karakter dalam komunitas praktik, etika feminis dan etika kepedulian menekankan empati serta perawatan relasi, etika diskursus menekankan legitimasi norma melalui dialog setara para pihak, dan etika postmodern menekankan tanggung jawab moral pribadi yang tidak dapat diwakilkan kepada prosedur. Keempat perspektif tersebut memperkaya analisis dengan dimensi pelaku, relasi, dan proses yang luput dari prinsip abstrak.</p>
      <p>Pesan akhir bab ini bersifat praktis. Manajer tidak perlu memilih satu teori sebagai pemenang, melainkan menggunakan seluruhnya secara pragmatis sebagai daftar pertanyaan yang memaksa dirinya menimbang kepentingan, akibat, prinsip, hak, keadilan, karakter, relasi, dialog, dan hati nurani sekaligus. Dengan disiplin berpikir semacam itu, keputusan bisnis di lingkungan yang kompleks, termasuk di Indonesia dengan keragaman budaya dan dinamika regulasinya, dapat dipertanggungjawabkan secara lebih utuh kepada seluruh pemangku kepentingan.</p>`
    },
    {
      no: "3.9",
      title: "Daftar Pustaka",
      body: `<p>Crane, A. dan Matten, D. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford University Press.</p>
      <p>Rawls, J. (1971). <em>A Theory of Justice</em>. Edisi ke-1. Harvard University Press.</p>
      <p>Velasquez, M. G. (2018). <em>Business Ethics: Concepts and Cases</em>. Edisi ke-8. Pearson Education.</p>`
    }
  ]
};
