window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[9] = {
  bab: 9,
  judul: "PEMASOK, PESAING, DAN ETIKA BISNIS",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 9",
  lo: [
    "LO1 Mengidentifikasi kepentingan atau stake spesifik yang dimiliki pemasok dan pesaing dalam hubungannya dengan perusahaan.",
    "LO2 Menguraikan berbagai isu etika yang muncul dalam hubungan perusahaan dengan pemasok, termasuk penyalahgunaan kekuasaan, konflik kepentingan, pemberian hadiah, dan etika negosiasi.",
    "LO3 Menguraikan berbagai isu etika yang muncul dalam hubungan perusahaan dengan pesaing, baik akibat persaingan yang terlalu agresif maupun persaingan yang tidak memadai.",
    "LO4 Menjelaskan dampak globalisasi terhadap isu etika dalam jaringan bisnis-ke-bisnis lintas negara.",
    "LO5 Menganalisis tanggung jawab perusahaan yang diperluas atas praktik etis di sepanjang rantai pasok melalui ethical sourcing dan fair trade.",
    "LO6 Mendiskusikan peran hubungan antarperusahaan dalam mewujudkan keberlanjutan, termasuk konsep industrial ecosystems dan rantai pasok tertutup."
  ],
  sections: [
    {
      no: "9.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi kesembilan mata kuliah Business Ethics and Sustainability membahas dimensi etika dalam hubungan perusahaan dengan dua kelompok pemangku kepentingan yang sering diabaikan dalam kajian etika bisnis, yaitu pemasok dan pesaing. Berbeda dengan pemegang saham, karyawan, atau konsumen yang berhubungan langsung dengan perusahaan dalam relasi vertikal yang jelas, pemasok dan pesaing berada dalam jaringan hubungan bisnis-ke-bisnis yang kompleks, dinamis, dan sarat pertimbangan kekuasaan. Pembahasan dimulai dari penetapan kedudukan pemasok dan pesaing sebagai pemangku kepentingan, dilanjutkan dengan pemetaan isu etika dalam hubungan dengan pemasok dan pesaing, dampak globalisasi terhadap isu tersebut, tanggung jawab perusahaan yang diperluas melalui <em>ethical sourcing</em> dan <em>fair trade</em>, serta peran hubungan antarperusahaan dalam agenda keberlanjutan (Crane dan Matten, 2019).</p>
      <p>Setelah menyelesaikan sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <ul>
        <li>Mengidentifikasi kepentingan spesifik yang dimiliki pemasok dan pesaing dalam hubungannya dengan perusahaan.</li>
        <li>Menguraikan isu etika dalam hubungan dengan pemasok, termasuk penyalahgunaan kekuasaan, konflik kepentingan, pemberian hadiah, dan etika negosiasi.</li>
        <li>Menguraikan isu etika dalam hubungan dengan pesaing, baik akibat persaingan yang terlalu agresif maupun persaingan yang tidak memadai.</li>
        <li>Menjelaskan dampak globalisasi terhadap isu etika dalam jaringan bisnis lintas negara.</li>
        <li>Menganalisis tanggung jawab perusahaan atas rantai pasok melalui <em>ethical sourcing</em> dan <em>fair trade</em>.</li>
        <li>Mendiskusikan konsep <em>industrial ecosystems</em> dan rantai pasok tertutup sebagai wujud keberlanjutan dalam jaringan bisnis.</li>
      </ul>`
    },
    {
      no: "9.2",
      title: "Pemasok dan Pesaing sebagai Pemangku Kepentingan",
      body: `<p>Kajian etika bisnis secara tradisional memusatkan perhatian pada kelompok pemangku kepentingan yang berhubungan langsung dengan perusahaan, sehingga hubungan antarperusahaan sering dipandang semata sebagai transaksi pasar yang bebas nilai. Pandangan tersebut tidak lagi memadai karena perusahaan modern beroperasi di dalam jaringan hubungan bisnis-ke-bisnis yang saling bergantung, mulai dari aliansi strategis, kemitraan jangka panjang, hingga rantai pasok global yang melibatkan ribuan organisasi. Menurut Crane dan Matten (2019), pergeseran dari model hubungan yang bersifat transaksional menuju model jaringan atau <em>network model</em> menjadikan batas antara pihak internal dan eksternal perusahaan semakin kabur, sehingga pertimbangan etis tidak dapat berhenti pada batas hukum organisasi. Dengan demikian, keputusan pembelian, penetapan harga, dan strategi bersaing merupakan keputusan yang bermuatan etika, bukan sekadar keputusan teknis komersial.</p>
      <h5>9.2.1 Kepentingan Pemasok</h5>
      <p>Pemasok memiliki kepentingan yang sah terhadap perusahaan karena keberlangsungan usahanya sering bergantung pada kelanjutan hubungan dagang dengan pembeli. Kepentingan tersebut mencakup harga yang wajar atas barang dan jasa yang dipasok, pembayaran yang tepat waktu sesuai kesepakatan, perlakuan yang adil dalam proses tender dan negosiasi, serta kepastian hubungan yang memungkinkan pemasok melakukan investasi jangka panjang (Crane dan Matten, 2019). Ketergantungan tersebut bersifat asimetris ketika satu pembeli menyerap sebagian besar penjualan pemasok, misalnya pemasok komponen otomotif yang menggantungkan lebih dari separuh pendapatannya pada satu pabrikan. Dalam situasi demikian, keputusan sepihak pembeli untuk menekan harga, memperpanjang termin pembayaran, atau memutus kontrak dapat mengancam kelangsungan hidup pemasok beserta karyawannya. Oleh karena itu, teori pemangku kepentingan menempatkan pemasok sebagai pihak yang berhak memperoleh pertimbangan moral, bukan sekadar objek efisiensi biaya.</p>
      <h5>9.2.2 Kepentingan Pesaing</h5>
      <p>Kedudukan pesaing sebagai pemangku kepentingan tampak paradoksal karena logika persaingan justru menghendaki perusahaan mengalahkan pesaingnya. Namun, pesaing tetap memiliki kepentingan yang sah agar arena persaingan diselenggarakan secara adil, yang oleh Crane dan Matten (2019) diibaratkan sebagai kepentingan atas <em>level playing field</em>. Kepentingan tersebut meliputi jaminan bahwa perusahaan lain tidak merusak pasar melalui praktik curang, tidak mencuri rahasia dagang, tidak menjelekkan produk pesaing secara tidak benar, dan tidak menutup akses pasar melalui penyalahgunaan posisi dominan. Selain itu, masyarakat luas berkepentingan terhadap persaingan yang sehat karena persaingan mendorong inovasi, efisiensi, dan harga yang wajar bagi konsumen. Dengan demikian, isu etika terhadap pesaing memiliki dua sisi, yaitu persaingan yang terlalu agresif yang merugikan pesaing secara tidak adil, dan persaingan yang tidak memadai yang merugikan konsumen dan perekonomian.</p>`
    },
    {
      no: "9.3",
      title: "Isu Etika dalam Hubungan dengan Pemasok",
      body: `<p>Hubungan pembeli dan pemasok merupakan hubungan pertukaran yang di dalamnya melekat perbedaan kekuasaan, informasi, dan kepentingan. Crane dan Matten (2019) mengidentifikasi sejumlah isu etika utama dalam hubungan tersebut, yaitu penyalahgunaan kekuasaan, persoalan loyalitas dan perlakuan istimewa, konflik kepentingan, pemberian hadiah dan suap, serta etika dalam negosiasi. Kelima kelompok isu tersebut diuraikan pada sub-sub-bab berikut dan diringkas pada Tabel 9.1.</p>
      <h5>9.3.1 Penyalahgunaan Kekuasaan dalam Hubungan Pembeli dan Pemasok</h5>
      <p>Isu etika yang paling mendasar dalam hubungan dengan pemasok adalah penyalahgunaan kekuasaan atau <em>misuse of power</em> oleh pihak yang posisinya lebih kuat. Kekuasaan pembeli meningkat ketika pembeli berukuran besar, jumlah pembeli alternatif sedikit, dan produk pemasok tidak terdiferensiasi, sebagaimana dialami pemasok produk segar yang berhadapan dengan jaringan ritel raksasa. Bentuk penyalahgunaan yang lazim mencakup penekanan harga hingga di bawah biaya produksi yang wajar, penundaan pembayaran secara sepihak, pembebanan biaya promosi atau <em>listing fee</em> kepada pemasok, perubahan pesanan mendadak tanpa kompensasi, dan ancaman pemutusan hubungan untuk memaksa konsesi (Crane dan Matten, 2019). Praktik semacam ini sering disebut fenomena penekanan rantai pasok karena tekanan biaya dialirkan ke mata rantai yang paling lemah. Dalam konteks Indonesia, relasi antara peritel modern berskala besar dengan pemasok usaha mikro, kecil, dan menengah kerap menghadirkan persoalan serupa, misalnya termin pembayaran yang panjang dan potongan harga wajib, sehingga pemerintah mengatur perjanjian dagang antara toko modern dan pemasok untuk melindungi pihak yang lemah.</p>
      <p>Dari sudut pandang etika, penyalahgunaan kekuasaan dapat dinilai melalui prinsip keadilan distributif dan keadilan prosedural. Harga yang adil bukan hanya harga yang disepakati, melainkan harga yang disepakati melalui proses yang bebas dari paksaan dan eksploitasi ketergantungan. Implikasi manajerialnya, perusahaan pembeli yang berorientasi jangka panjang perlu menyeimbangkan efisiensi biaya dengan keberlanjutan pemasoknya, karena pemasok yang tertekan cenderung menurunkan kualitas, memangkas standar ketenagakerjaan, atau keluar dari pasar, yang pada akhirnya merugikan pembeli itu sendiri.</p>
      <h5>9.3.2 Loyalitas dan Perlakuan Istimewa</h5>
      <p>Persoalan etika berikutnya menyangkut kadar loyalitas yang pantas dalam hubungan dagang. Di satu sisi, hubungan jangka panjang membangun kepercayaan dan mendorong pemasok berinvestasi pada kebutuhan spesifik pembeli. Di sisi lain, muncul pertanyaan apakah pembeli berkewajiban moral mempertahankan pemasok lama ketika tersedia pemasok baru yang lebih murah, atau apakah pemutusan hubungan yang mendadak setelah kerja sama bertahun-tahun merupakan pengkhianatan atas ekspektasi yang sah (Crane dan Matten, 2019). Persoalan sebaliknya adalah perlakuan istimewa atau <em>preferential treatment</em>, yaitu pemberian keuntungan kepada pemasok tertentu atas dasar hubungan pribadi, kekerabatan, atau kepentingan tersembunyi, bukan atas dasar merit. Praktik semacam ini menciderai keadilan prosedural terhadap pemasok lain yang mengikuti proses secara jujur, meskipun pada kasus tertentu perlakuan berbeda dapat dibenarkan secara etis, misalnya kebijakan afirmatif yang memprioritaskan pemasok lokal atau usaha kecil demi tujuan pembangunan. Oleh karena itu, pembeda antara diskriminasi yang tidak etis dan preferensi yang sah terletak pada transparansi kriteria dan legitimasi tujuannya.</p>
      <h5>9.3.3 Konflik Kepentingan</h5>
      <p>Konflik kepentingan merupakan situasi ketika kepentingan pribadi seseorang berpotensi mempengaruhi pelaksanaan kewajiban profesionalnya terhadap organisasi, misalnya manajer pengadaan yang menilai penawaran dari perusahaan milik keluarganya sendiri (Crane dan Matten, 2019). Persoalan etisnya tidak terletak pada terjadinya keputusan yang bias semata, melainkan pada keberadaan situasi yang meruntuhkan kepercayaan terhadap objektivitas pengambil keputusan, sehingga konflik kepentingan tetap bermasalah meskipun keputusan akhirnya benar. Mekanisme penanganannya mencakup pengungkapan atau <em>disclosure</em> kepada atasan, pengunduran diri dari proses pengambilan keputusan terkait, serta pemisahan fungsi dalam proses pengadaan. Dengan demikian, kebijakan perusahaan yang baik tidak hanya melarang penyalahgunaan, melainkan juga mewajibkan pelaporan setiap situasi yang berpotensi menimbulkan konflik.</p>
      <h5>9.3.4 Hadiah, Suap, dan Jamuan</h5>
      <p>Pemberian hadiah, jamuan, dan fasilitas merupakan wilayah abu-abu yang paling sering muncul dalam hubungan dengan pemasok. Suap atau <em>bribery</em> didefinisikan sebagai pemberian sesuatu yang bernilai dengan maksud mempengaruhi penerima agar menyalahgunakan kedudukannya demi keuntungan pemberi, sedangkan hadiah dan jamuan dalam batas kewajaran dapat berfungsi sebagai pelumas hubungan sosial yang sah (Crane dan Matten, 2019). Untuk menilai batas kewajaran tersebut, dapat digunakan beberapa kriteria, yaitu: nilai atau intensi pemberian, waktu pemberian terhadap keputusan bisnis yang sedang berjalan, keterbukaan pemberian, dan kesesuaiannya dengan kebijakan organisasi penerima. Pemberian bernilai besar yang dilakukan diam-diam menjelang keputusan tender jelas mengarah pada suap, sedangkan suvenir bernilai kecil yang diberikan terbuka pada perayaan umum lazim diterima. Dalam konteks Indonesia, kerangka hukum gratifikasi mewajibkan penyelenggara negara melaporkan penerimaan tertentu kepada Komisi Pemberantasan Korupsi, dan banyak korporasi swasta mengadopsi batas nilai hadiah dalam kode etiknya sebagai pengendalian preventif. Implikasi manajerialnya, perusahaan perlu menetapkan kebijakan hadiah yang jelas, ambang nilai yang tegas, dan register pelaporan agar karyawan tidak menafsirkan sendiri batas kepantasan.</p>
      <h5>9.3.5 Etika dalam Negosiasi</h5>
      <p>Negosiasi pengadaan merupakan arena yang rawan secara etis karena para pihak lazim menyembunyikan informasi demi posisi tawar. Crane dan Matten (2019) membedakan taktik yang dapat diterima, seperti tidak mengungkapkan harga cadangan, dari taktik yang tercela, seperti kebohongan mengenai fakta material, pemalsuan penawaran pesaing, ancaman palsu, dan manipulasi psikologis. Ukuran yang dapat digunakan adalah apakah taktik tersebut merusak dasar kepercayaan yang diperlukan agar pertukaran itu sendiri berjalan, serta apakah pelaku bersedia taktik yang sama diterapkan kepadanya, sejalan dengan uji universalisasi dalam etika Kantian. Dengan demikian, kejujuran mengenai fakta material merupakan batas minimum etika negosiasi, sedangkan kepiawaian menawar tetap merupakan bagian sah dari permainan bisnis.</p>
      <table class="bk-table">
        <caption>Tabel 9.1 Isu Etika Utama dalam Hubungan dengan Pemasok</caption>
        <thead><tr><th>Isu</th><th>Inti Persoalan</th><th>Prinsip Etika yang Terancam</th><th>Pengendalian Manajerial</th></tr></thead>
        <tbody>
          <tr><td>Penyalahgunaan kekuasaan</td><td>Eksploitasi ketergantungan pemasok melalui tekanan harga dan syarat sepihak</td><td>Keadilan distributif dan prosedural</td><td>Kebijakan pembayaran adil, kontrak berimbang, dialog pemasok</td></tr>
          <tr><td>Loyalitas dan perlakuan istimewa</td><td>Pemutusan hubungan sepihak atau preferensi tanpa dasar merit</td><td>Kesetaraan kesempatan, itikad baik</td><td>Kriteria seleksi transparan, masa transisi pemutusan</td></tr>
          <tr><td>Konflik kepentingan</td><td>Kepentingan pribadi mempengaruhi keputusan pengadaan</td><td>Kewajiban fidusia, objektivitas</td><td>Pengungkapan, rekusal, pemisahan fungsi</td></tr>
          <tr><td>Hadiah, suap, dan jamuan</td><td>Pemberian yang mempengaruhi keputusan penerima</td><td>Integritas, persaingan sehat</td><td>Ambang nilai hadiah, register gratifikasi, pelatihan</td></tr>
          <tr><td>Etika negosiasi</td><td>Kebohongan dan manipulasi mengenai fakta material</td><td>Kejujuran, kepercayaan</td><td>Pedoman negosiasi, dokumentasi proses</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
      </table>`
    },
    {
      no: "9.4",
      title: "Isu Etika dalam Hubungan dengan Pesaing",
      body: `<p>Isu etika terhadap pesaing dapat dipetakan ke dalam dua kutub yang berlawanan. Pada kutub pertama, persaingan yang terlalu agresif atau <em>overly aggressive competition</em> menempuh cara-cara yang merugikan pesaing secara tidak adil. Pada kutub kedua, persaingan yang tidak memadai atau <em>insufficient competition</em> terjadi ketika perusahaan justru menghindari persaingan melalui kesepakatan diam-diam yang merugikan konsumen (Crane dan Matten, 2019). Kedua kutub tersebut menunjukkan bahwa etika terhadap pesaing bukan berarti bersikap lunak, melainkan bersaing keras di dalam koridor permainan yang adil.</p>
      <h5>9.4.1 Persaingan yang Terlalu Agresif</h5>
      <p>Bentuk pertama persaingan agresif yang bermasalah adalah pengumpulan intelijen bisnis yang melewati batas menjadi spionase industri. Pengumpulan informasi pesaing dari sumber publik, seperti laporan tahunan, pameran dagang, dan publikasi media, merupakan praktik yang sah dan bahkan diperlukan dalam manajemen strategik. Persoalan etis muncul ketika informasi diperoleh melalui cara-cara tercela, yaitu penyusupan atau pencurian langsung, penyamaran identitas untuk mengorek informasi, perekrutan karyawan pesaing dengan tujuan utama menggali rahasia dagangnya, serta penekanan terhadap pihak yang memegang informasi rahasia (Crane dan Matten, 2019). Batas etisnya dapat diuji dengan menanyakan apakah cara perolehan informasi melanggar hak kepemilikan, melibatkan penipuan, atau mendorong pihak lain mengkhianati kewajiban kerahasiaannya.</p>
      <p>Bentuk kedua adalah aneka taktik kotor atau <em>dirty tricks</em> terhadap pesaing. Termasuk di dalamnya iklan negatif yang merendahkan pesaing dengan klaim menyesatkan, perusakan reputasi melalui rumor, pembajakan pelanggan dengan cara menyesatkan, sabotase fisik maupun digital, serta <em>predatory pricing</em>, yaitu penetapan harga di bawah biaya dalam jangka waktu tertentu dengan maksud mematikan pesaing untuk kemudian menaikkan harga setelah pasar dikuasai (Crane dan Matten, 2019). Praktik <em>predatory pricing</em> menjadi perdebatan aktual dalam ekonomi digital karena strategi bakar uang perusahaan platform, termasuk perang harga dan subsidi tarif pada industri transportasi daring dan dagang-el di Indonesia, sulit dibedakan dari penetrasi pasar yang sah. Ukuran yang membedakannya adalah niat dan struktur biaya, yaitu apakah harga rendah dimaksudkan membangun efisiensi jangka panjang yang dinikmati konsumen atau semata menyingkirkan pesaing agar kekuatan pasar dapat dieksploitasi kemudian.</p>
      <h5>9.4.2 Persaingan yang Tidak Memadai: Kolusi, Kartel, dan Penyalahgunaan Posisi Dominan</h5>
      <p>Kutub kedua justru berupa keengganan bersaing. Kolusi terjadi ketika para pesaing secara eksplisit maupun diam-diam menyepakati pengurangan persaingan, yang bentuk kelembagaannya disebut kartel. Praktik yang lazim mencakup penetapan harga bersama atau <em>price fixing</em>, pembagian wilayah dan pelanggan, pembatasan pasokan untuk mengerek harga, serta persekongkolan tender atau <em>bid rigging</em> (Crane dan Matten, 2019). Kolusi dinilai sangat tercela karena korbannya adalah konsumen dan perekonomian secara luas, sementara para pelakunya menikmati laba tanpa upaya inovasi. Selain kolusi, persaingan juga terganggu oleh penyalahgunaan posisi dominan, misalnya praktik mengikat penjualan, diskriminasi harga yang eksklusioner, dan penutupan akses saluran distribusi bagi pesaing kecil. Hampir semua yurisdiksi mengatur persoalan ini melalui hukum persaingan usaha; di Indonesia, Undang-Undang Nomor 5 Tahun 1999 melarang praktik monopoli dan persaingan usaha tidak sehat dengan Komisi Pengawas Persaingan Usaha sebagai penegaknya. Putusan KPPU atas kartel skuter matik antara dua pabrikan sepeda motor besar pada tahun 2017 serta perkara penetapan tarif kargo sejumlah maskapai menunjukkan bahwa isu ini nyata dalam praktik bisnis nasional.</p>
      <p>Dari perspektif teori etika, kolusi dapat dikritik secara konsekuensialis karena menurunkan kesejahteraan agregat, dan secara deontologis karena mengingkari prinsip kejujuran terhadap konsumen yang mengira harga terbentuk dari persaingan. Implikasi manajerialnya, perusahaan perlu membangun program kepatuhan persaingan usaha, termasuk pelatihan bagi staf penjualan mengenai batas komunikasi dengan pesaing dalam asosiasi industri, karena kesepakatan yang melanggar sering lahir dari pertemuan informal yang tampak lumrah. Ringkasan kedua kutub isu terhadap pesaing disajikan pada Tabel 9.2.</p>
      <table class="bk-table">
        <caption>Tabel 9.2 Dua Kutub Isu Etika dalam Hubungan dengan Pesaing</caption>
        <thead><tr><th>Kutub</th><th>Bentuk Praktik</th><th>Pihak yang Dirugikan</th><th>Contoh</th></tr></thead>
        <tbody>
          <tr><td>Persaingan terlalu agresif</td><td>Spionase industri, iklan negatif menyesatkan, sabotase, pembajakan pelanggan, predatory pricing</td><td>Pesaing secara langsung, konsumen dalam jangka panjang</td><td>Perang subsidi tarif platform digital yang menekan pesaing kecil</td></tr>
          <tr><td>Persaingan tidak memadai</td><td>Penetapan harga bersama, pembagian pasar, persekongkolan tender, penyalahgunaan posisi dominan</td><td>Konsumen, pelaku usaha kecil, perekonomian</td><td>Putusan KPPU atas kartel skuter matik tahun 2017</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
      </table>`
    },
    {
      no: "9.5",
      title: "Globalisasi dan Isu Etika dalam Jaringan Bisnis Internasional",
      body: `<p>Globalisasi memperluas jaringan pemasok dan arena persaingan melintasi batas negara, sekaligus melipatgandakan kompleksitas etisnya. Crane dan Matten (2019) menyoroti tiga dampak utama globalisasi terhadap hubungan bisnis-ke-bisnis, yaitu perbedaan cara berbisnis antarbudaya, ketimpangan kekuatan terhadap pemasok di negara berkembang, dan keragaman konteks regulasi antarnegara.</p>
      <p>Dampak pertama menyangkut perbedaan norma budaya dalam praktik bisnis. Praktik pemberian hadiah, jamuan, dan pembangunan relasi personal memiliki makna yang berbeda antarbudaya; jaringan relasi timbal balik yang dikenal sebagai <em>guanxi</em> dalam budaya bisnis Tionghoa, misalnya, merupakan institusi sosial yang sah bagi sebagian pihak, namun dapat dipersepsikan sebagai nepotisme atau suap terselubung oleh pihak lain. Situasi ini menghadirkan dilema klasik antara relativisme etis, yang menghormati norma lokal, dan imperialisme etis, yang memaksakan standar negara asal. Jalan tengah yang lazim ditawarkan adalah membedakan norma yang sekadar berbeda dari norma yang melanggar nilai kemanusiaan mendasar, serta menaati kerangka hukum antikorupsi transnasional yang semakin ketat, seperti pelarangan penyuapan pejabat asing yang berlaku lintas yurisdiksi. Oleh karena itu, korporasi multinasional umumnya menetapkan standar global tunggal untuk isu suap sambil memberi ruang penyesuaian budaya untuk praktik keramahtamahan yang wajar.</p>
      <p>Dampak kedua adalah posisi tawar pemasok negara berkembang yang lemah di hadapan pembeli global. Perusahaan multinasional dapat memindahkan pesanan antarnegara dengan mudah, sehingga pemasok dan bahkan pemerintah negara berkembang saling berlomba menawarkan biaya terendah, yang memunculkan kekhawatiran mengenai <em>race to the bottom</em> dalam upah, keselamatan kerja, dan standar lingkungan (Crane dan Matten, 2019). Tragedi runtuhnya gedung Rana Plaza di Bangladesh pada tahun 2013, yang menewaskan lebih dari seribu pekerja garmen pemasok merek global, menjadi peristiwa penentu yang menunjukkan akibat fatal dari tekanan biaya yang dialirkan ke mata rantai terlemah. Fenomena serupa relevan bagi Indonesia sebagai negara produsen, misalnya pada industri alas kaki dan garmen di Jawa Barat serta rantai pasok minyak sawit yang melibatkan jutaan petani swadaya dengan posisi tawar terbatas terhadap pabrik dan pedagang pengumpul.</p>
      <p>Dampak ketiga adalah keragaman regulasi. Hukum persaingan usaha, hukum kontrak, dan penegakan antikorupsi berbeda tajam antarnegara, sehingga praktik yang legal di satu yurisdiksi dapat ilegal di yurisdiksi lain. Kekosongan atau kelemahan penegakan hukum di sebagian negara menjadikan regulasi tidak dapat diandalkan sebagai satu-satunya kompas perilaku, dan di sinilah etika berperan sebagai standar yang melampaui kepatuhan hukum minimal. Dengan demikian, globalisasi menggeser pertanyaan etis dari sekadar bagaimana perusahaan berperilaku terhadap mitra langsungnya menjadi sejauh mana perusahaan bertanggung jawab atas perilaku seluruh jaringan bisnisnya, yang menjadi pokok bahasan sub-bab berikutnya.</p>`
    },
    {
      no: "9.6",
      title: "Tanggung Jawab yang Diperluas atas Rantai Pasok: Ethical Sourcing dan Fair Trade",
      body: `<p>Perkembangan paling penting dalam etika hubungan bisnis-ke-bisnis adalah perluasan tanggung jawab perusahaan melampaui batas hukumnya sendiri ke seluruh rantai pasoknya, yang mencerminkan peran perusahaan sebagai warga korporasi atau <em>corporate citizen</em> dalam jaringan bisnis. Masyarakat, media, dan lembaga swadaya semakin meminta pertanggungjawaban merek global atas kondisi kerja dan dampak lingkungan di pabrik pemasoknya, meskipun secara hukum pemasok tersebut adalah entitas independen. Crane dan Matten (2019) menyebut gejala ini sebagai rantai tanggung jawab yang diperluas atau <em>extended chain of responsibility</em>, yang secara etis dilandasi argumen bahwa perusahaan turut menyebabkan, memperoleh manfaat dari, dan memiliki kekuasaan untuk mempengaruhi praktik pemasoknya. Dua instrumen utama pelaksanaannya adalah <em>ethical sourcing</em> dan <em>fair trade</em>.</p>
      <h5>9.6.1 Ethical Sourcing dan Kode Etik Pemasok</h5>
      <p><em>Ethical sourcing</em> adalah praktik memasukkan kriteria etis, sosial, dan lingkungan secara eksplisit ke dalam kebijakan dan keputusan pengadaan perusahaan (Crane dan Matten, 2019). Mekanisme pelaksanaannya umumnya berjenjang sebagai berikut: pertama, penetapan kode etik pemasok yang memuat standar minimum, misalnya larangan pekerja anak dan kerja paksa, kebebasan berserikat, upah layak, jam kerja wajar, keselamatan kerja, dan pengelolaan lingkungan, yang banyak di antaranya merujuk pada konvensi Organisasi Perburuhan Internasional serta kode dasar Ethical Trading Initiative; kedua, audit sosial terhadap pemasok untuk memverifikasi kepatuhan, baik oleh auditor internal maupun pihak ketiga; ketiga, tindak lanjut berupa rencana perbaikan, pengembangan kapasitas pemasok, atau penghentian hubungan bagi pelanggaran berat. Sertifikasi pihak ketiga, seperti SA8000 untuk standar ketenagakerjaan dan sertifikasi kelestarian komoditas seperti RSPO pada minyak sawit yang sangat relevan bagi eksportir Indonesia, memperkuat kredibilitas klaim perusahaan.</p>
      <p>Meskipun demikian, efektivitas pendekatan berbasis audit menuai kritik yang serius. Audit yang bersifat kunjungan sesaat mudah diakali melalui pembukuan ganda dan pengaturan jawaban pekerja, subkontrak tersembunyi meloloskan pabrik yang tidak pernah diaudit, dan paradoks yang paling mendasar adalah tekanan harga serta tenggat pesanan dari pembeli itu sendiri yang mendorong pemasok melanggar standar yang dituntut pembeli (Crane dan Matten, 2019). Oleh karena itu, praktik terbaik bergeser dari model kepolisian menuju model kemitraan, yaitu hubungan jangka panjang, harga beli yang memungkinkan kepatuhan, pelibatan pekerja dan serikat dalam pemantauan, serta transparansi rantai pasok kepada publik. Implikasi manajerialnya, fungsi pengadaan tidak dapat lagi dinilai semata dari penghematan biaya, melainkan juga dari kualitas etis rantai pasok yang dibangunnya.</p>
      <h5>9.6.2 Fair Trade</h5>
      <p>Apabila <em>ethical sourcing</em> menetapkan standar minimum, gerakan <em>fair trade</em> melangkah lebih jauh dengan merancang ulang syarat perdagangan agar berpihak pada produsen kecil di negara berkembang. Elemen pokok skema perdagangan berkeadilan mencakup harga minimum yang menjamin biaya produksi berkelanjutan terlindungi dari kejatuhan harga pasar dunia, premi sosial yang dikelola kolektif untuk pembangunan komunitas, pembayaran di muka, serta hubungan dagang jangka panjang yang stabil (Crane dan Matten, 2019). Skema ini dioperasikan melalui sertifikasi dan pelabelan produk, sehingga konsumen akhir dapat memilih membayar lebih untuk keadilan bagi produsen. Kopi merupakan komoditas perintisnya, dan sejumlah koperasi kopi arabika Gayo di Aceh telah memperoleh sertifikasi perdagangan berkeadilan yang memberi petani premi untuk pembangunan fasilitas komunitas. Namun, gerakan ini juga menghadapi kritik, antara lain jangkauannya terbatas pada ceruk pasar, biaya sertifikasi membebani produsen kecil, distribusi manfaat premi tidak selalu sampai ke petani penggarap, dan harga minimum dinilai mendistorsi sinyal pasar. Dari perdebatan tersebut dapat disimpulkan bahwa <em>fair trade</em> merupakan koreksi parsial namun penting atas ketimpangan struktur perdagangan global, yang efektivitasnya bergantung pada tata kelola skema dan komitmen pembeli.</p>
      <table class="bk-table">
        <caption>Tabel 9.3 Perbandingan Ethical Sourcing dan Fair Trade</caption>
        <thead><tr><th>Dimensi</th><th>Ethical Sourcing</th><th>Fair Trade</th></tr></thead>
        <tbody>
          <tr><td>Inisiator utama</td><td>Perusahaan pembeli dan inisiatif industri</td><td>Gerakan sosial dan lembaga sertifikasi</td></tr>
          <tr><td>Fokus</td><td>Standar minimum sosial dan lingkungan pada pemasok</td><td>Perbaikan syarat dagang bagi produsen kecil</td></tr>
          <tr><td>Instrumen</td><td>Kode etik pemasok, audit sosial, pengembangan kapasitas</td><td>Harga minimum, premi sosial, pelabelan produk</td></tr>
          <tr><td>Sasaran perlindungan</td><td>Pekerja pabrik pemasok dan lingkungan</td><td>Petani dan produsen skala kecil</td></tr>
          <tr><td>Kritik utama</td><td>Audit mudah diakali, paradoks tekanan harga pembeli</td><td>Ceruk terbatas, biaya sertifikasi, distribusi manfaat</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot>
      </table>`
    },
    {
      no: "9.7",
      title: "Keberlanjutan dalam Jaringan Bisnis: Menuju Industrial Ecosystems",
      body: `<p>Pembahasan terakhir bab ini mengangkat kontribusi hubungan antarperusahaan terhadap keberlanjutan dalam arti penuh, yang melampaui kepatuhan sosial menuju transformasi ekologis sistem produksi. Crane dan Matten (2019) memperkenalkan konsep ekosistem industrial atau <em>industrial ecosystems</em>, yaitu penerapan cara kerja ekosistem alamiah pada jaringan industri, di mana limbah dan produk samping suatu perusahaan menjadi masukan bagi perusahaan lain sehingga aliran material mendekati siklus tertutup. Contoh yang paling terkenal adalah simbiosis industrial di Kalundborg, Denmark, tempat pembangkit listrik, kilang, produsen farmasi, dan pemerintah kota saling mempertukarkan uap panas, air, dan residu material selama beberapa dekade. Gagasan yang sama mendasari konsep rantai pasok tertutup atau <em>closed-loop supply chain</em>, yang menambahkan aliran balik berupa pengambilan kembali produk bekas, penggunaan ulang, produksi ulang, dan daur ulang ke dalam desain rantai pasok, serta bermuara pada agenda ekonomi sirkular yang kini diadopsi banyak pemerintah dan korporasi.</p>
      <p>Perwujudan ekosistem industrial menuntut prasyarat relasional yang tidak ringan, yaitu kepercayaan jangka panjang antarperusahaan, keterbukaan informasi mengenai aliran material, kedekatan geografis, dan kesediaan berbagi manfaat investasi bersama. Prasyarat tersebut menegaskan kembali tesis utama bab ini bahwa etika hubungan bisnis-ke-bisnis bukan sekadar pengendalian risiko, melainkan fondasi kerja sama produktif; jaringan yang dibangun di atas eksploitasi kekuasaan tidak akan mampu menopang kolaborasi lingkungan yang kompleks. Dalam konteks Indonesia, pengembangan kawasan industri hijau serta program pemanfaatan limbah agroindustri, misalnya pengolahan tandan kosong dan cangkang sawit menjadi energi dan bahan baku industri lain, merupakan langkah awal ke arah simbiosis industrial. Implikasi manajerialnya, manajer perlu memandang pemasok dan bahkan pesaing sebagai mitra potensial dalam inovasi keberlanjutan, misalnya melalui inisiatif prakompetitif untuk standar kemasan dan sistem pengambilan kembali produk, sepanjang kolaborasi tersebut tidak tergelincir menjadi kolusi yang melanggar hukum persaingan.</p>`
    },
    {
      no: "9.8",
      title: "Rangkuman",
      body: `<p>Bab ini menegaskan bahwa pemasok dan pesaing merupakan pemangku kepentingan yang sah dengan klaim moral yang spesifik. Pemasok berkepentingan atas harga yang wajar, pembayaran tepat waktu, dan proses yang adil, sedangkan pesaing berkepentingan atas arena persaingan yang setara. Isu etika terhadap pemasok berpusat pada penyalahgunaan kekuasaan pembeli, persoalan loyalitas dan perlakuan istimewa, konflik kepentingan, batas antara hadiah dan suap, serta kejujuran dalam negosiasi. Isu etika terhadap pesaing terbentang di antara dua kutub, yaitu persaingan yang terlalu agresif dalam bentuk spionase industri, taktik kotor, dan <em>predatory pricing</em>, serta persaingan yang tidak memadai dalam bentuk kolusi, kartel, dan penyalahgunaan posisi dominan yang di Indonesia diawasi oleh KPPU berdasarkan Undang-Undang Nomor 5 Tahun 1999.</p>
      <p>Globalisasi memperumit isu tersebut melalui perbedaan norma budaya berbisnis, lemahnya posisi tawar pemasok negara berkembang yang memunculkan risiko <em>race to the bottom</em>, dan keragaman regulasi antarnegara. Sebagai jawabannya, tanggung jawab perusahaan diperluas ke seluruh rantai pasok melalui <em>ethical sourcing</em>, yang menegakkan standar sosial dan lingkungan lewat kode etik pemasok dan audit, serta <em>fair trade</em>, yang memperbaiki syarat dagang bagi produsen kecil melalui harga minimum dan premi sosial. Keduanya memiliki keterbatasan, sehingga praktik terbaik bergeser dari model pengawasan menuju kemitraan jangka panjang yang harganya memungkinkan kepatuhan.</p>
      <p>Pada tataran paling maju, hubungan antarperusahaan menjadi kendaraan keberlanjutan melalui ekosistem industrial dan rantai pasok tertutup yang meniru siklus material alam. Dengan demikian, pesan manajerial utama bab ini adalah bahwa kualitas etis hubungan bisnis-ke-bisnis menentukan bukan hanya reputasi dan kepatuhan hukum perusahaan, melainkan juga kapasitasnya membangun kolaborasi produktif yang menjadi prasyarat inovasi dan keberlanjutan jangka panjang (Crane dan Matten, 2019).</p>`
    },
    {
      no: "9.9",
      title: "Daftar Pustaka",
      body: `<p>Crane, A., Matten, D., Glozer, S. dan Spence, L. J. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford University Press.</p>
      <p>Republik Indonesia. (1999). <em>Undang-Undang Nomor 5 Tahun 1999 tentang Larangan Praktek Monopoli dan Persaingan Usaha Tidak Sehat</em>. Sekretariat Negara.</p>`
    }
  ]
};
