window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[7] = {
  bab: 7,
  judul: "BAB 7 KARYAWAN DAN ETIKA BISNIS",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 7",
  lo: [
    "LO1 Menjelaskan kedudukan khusus karyawan sebagai pemangku kepentingan perusahaan serta ketegangan etis yang melekat pada relasi kerja.",
    "LO2 Menguraikan kerangka hak dan kewajiban karyawan sebagai landasan analisis isu etis dalam pengelolaan sumber daya manusia.",
    "LO3 Menganalisis isu etis utama dalam praktik manajemen sumber daya manusia, meliputi diskriminasi, privasi, proses yang adil, partisipasi, keselamatan kerja, upah yang layak, kebebasan berbicara, dan hak untuk bekerja.",
    "LO4 Menilai dampak globalisasi terhadap isu etis ketenagakerjaan, termasuk perbedaan nilai budaya, kesenjangan upah lintas negara, dan fenomena perlombaan menuju standar terendah.",
    "LO5 Menerapkan perspektif kewargaan korporasi (corporate citizenship) untuk memahami peran perusahaan dalam menjamin hak sipil, sosial, dan politik karyawan.",
    "LO6 Mengevaluasi implikasi agenda keberlanjutan terhadap relasi kerja, termasuk fleksibilitas kerja, keseimbangan kehidupan kerja, dan konsep pekerjaan yang berkelanjutan."
  ],
  sections: [
    {
      no: "7.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membahas relasi antara perusahaan dan karyawan dari sudut pandang etika bisnis. Karyawan merupakan pemangku kepentingan yang paling dekat dengan operasi perusahaan sehingga hampir setiap keputusan manajerial, mulai dari rekrutmen, penilaian kinerja, pengupahan, hingga pemutusan hubungan kerja, memiliki dimensi etis yang nyata. Pembahasan dalam bab ini mengikuti kerangka Crane dan Matten (2019) yang menempatkan hak dan kewajiban karyawan sebagai alat analisis utama, kemudian memperluas cakupannya ke konteks global dan agenda keberlanjutan.</p>
      <p>Setelah menyelesaikan sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <p><strong>LO1</strong> menjelaskan kedudukan khusus karyawan sebagai pemangku kepentingan serta ketegangan etis yang melekat pada relasi kerja; <strong>LO2</strong> menguraikan kerangka hak dan kewajiban karyawan; <strong>LO3</strong> menganalisis isu etis utama dalam manajemen sumber daya manusia, meliputi diskriminasi, privasi, proses yang adil, partisipasi, keselamatan kerja, upah yang layak, kebebasan berbicara, dan hak untuk bekerja; <strong>LO4</strong> menilai dampak globalisasi terhadap isu etis ketenagakerjaan; <strong>LO5</strong> menerapkan perspektif kewargaan korporasi terhadap relasi karyawan; serta <strong>LO6</strong> mengevaluasi implikasi keberlanjutan terhadap pola hubungan kerja masa depan.</p>`
    },
    {
      no: "7.2",
      title: "Karyawan sebagai Pemangku Kepentingan",
      body: `<p>Dalam teori pemangku kepentingan, karyawan menempati posisi yang unik dibandingkan kelompok lain seperti pemasok, konsumen, atau masyarakat. Karyawan berada di dalam batas organisasi, terikat kontrak kerja yang bersifat berkelanjutan, dan menyumbangkan sesuatu yang tidak dapat dipisahkan dari dirinya sendiri, yaitu tenaga, waktu, keterampilan, dan bahkan identitas pribadinya. Menurut Crane dan Matten (2019), kedekatan ini menimbulkan tanggung jawab moral perusahaan yang lebih besar terhadap karyawan karena keputusan perusahaan berdampak langsung pada penghidupan, kesehatan, dan martabat manusia yang bekerja di dalamnya. Selain itu, karyawan secara hukum sering dianggap mewakili perusahaan, sehingga tindakan mereka dapat dianggap sebagai tindakan korporasi itu sendiri.</p>
      <p>Ketegangan etis mendasar dalam relasi kerja terletak pada istilah manajemen sumber daya manusia atau <em>human resource management</em> itu sendiri. Ketika manusia dipandang sebagai sumber daya, terdapat risiko bahwa karyawan diperlakukan semata sebagai faktor produksi yang dikelola demi efisiensi, bukan sebagai subjek moral yang memiliki tujuan hidupnya sendiri. Dari perspektif etika Kantian, memperlakukan manusia semata sebagai alat untuk mencapai tujuan organisasi merupakan pelanggaran terhadap prinsip penghormatan atas martabat manusia. Oleh karena itu, tugas etis manajer adalah menyeimbangkan tuntutan efisiensi ekonomi dengan pengakuan bahwa karyawan adalah manusia yang memiliki hak yang tidak dapat direduksi menjadi angka biaya tenaga kerja.</p>
      <p>Ketegangan tersebut diperkuat oleh asimetri kekuasaan dalam hubungan kerja. Perusahaan pada umumnya memiliki posisi tawar yang jauh lebih kuat daripada karyawan individual karena menguasai informasi, modal, dan akses terhadap kesempatan kerja. Dengan demikian, pasar tenaga kerja tidak dapat sepenuhnya diserahkan pada mekanisme kontrak sukarela, dan diperlukan kerangka hak karyawan sebagai batas moral yang melindungi pihak yang lebih lemah. Kerangka inilah yang menjadi struktur analisis utama bab ini dan diuraikan pada sub-bab berikutnya.</p>`
    },
    {
      no: "7.3",
      title: "Kerangka Hak dan Kewajiban Karyawan",
      body: `<p>Crane dan Matten (2019) menyusun peta isu etis ketenagakerjaan dengan menggunakan bahasa hak dan kewajiban. Hak karyawan dipahami sebagai perlindungan moral dasar yang bersumber dari hak asasi manusia dan diterapkan pada konteks tempat kerja, sedangkan kewajiban karyawan merupakan tuntutan timbal balik yang muncul dari kontrak kerja. Pendekatan berbasis hak dipilih karena memberikan standar yang relatif stabil dan tidak mudah dinegosiasikan atas nama kepentingan bisnis. Namun, penerapan setiap hak dalam praktik tetap menimbulkan wilayah abu-abu yang memerlukan pertimbangan manajerial, dan wilayah abu-abu itulah yang menjadi inti pembahasan etika bisnis.</p>
      <p>Secara garis besar, hak karyawan yang dibahas dalam bab ini mencakup delapan kelompok, sebagaimana dirangkum pada Tabel 7.1. Setiap hak memiliki isu kontemporer yang diperdebatkan, sehingga manajer perlu memahami bukan hanya rumusan haknya, melainkan juga batas penerapannya.</p>
      <table class="bk-table"><caption>Tabel 7.1 Hak Karyawan dan Isu Etis yang Menyertainya</caption>
      <thead><tr><th>Hak Karyawan</th><th>Makna Pokok</th><th>Isu yang Diperdebatkan</th></tr></thead>
      <tbody>
      <tr><td>Bebas dari diskriminasi</td><td>Perlakuan setara atas dasar kriteria yang relevan dengan pekerjaan</td><td>Tindakan afirmatif, diskriminasi terbalik, pelecehan seksual</td></tr>
      <tr><td>Privasi</td><td>Perlindungan ranah pribadi fisik, sosial, informasional, dan psikologis</td><td>Tes kesehatan dan narkoba, pengawasan elektronik, perilaku di luar jam kerja</td></tr>
      <tr><td>Proses yang adil (<em>due process</em>)</td><td>Keputusan promosi, sanksi, dan pemutusan hubungan kerja berdasarkan prosedur yang jujur</td><td>Etika perampingan organisasi (<em>downsizing</em>)</td></tr>
      <tr><td>Partisipasi dan berserikat</td><td>Keterlibatan dalam keputusan yang memengaruhi kepentingan karyawan</td><td>Pelemahan serikat pekerja, demokrasi tempat kerja</td></tr>
      <tr><td>Kondisi kerja sehat dan aman</td><td>Perlindungan dari bahaya fisik dan psikososial</td><td>Jam kerja berlebihan, stres kerja, kecelakaan industri</td></tr>
      <tr><td>Upah yang adil</td><td>Imbalan yang layak dan proporsional terhadap kontribusi</td><td>Upah hidup layak, kesenjangan gaji eksekutif</td></tr>
      <tr><td>Kebebasan hati nurani dan berbicara</td><td>Menolak perintah yang tidak etis dan mengungkap pelanggaran</td><td>Perlindungan pelapor pelanggaran (<em>whistleblower</em>)</td></tr>
      <tr><td>Hak untuk bekerja</td><td>Akses yang wajar terhadap kesempatan kerja</td><td>Tanggung jawab perusahaan atas kesempatan kerja</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>
      <p>Di sisi lain, karyawan juga memikul kewajiban terhadap perusahaan. Kewajiban tersebut meliputi kewajiban mematuhi kontrak kerja dengan memberikan kinerja pada tingkat yang wajar, kewajiban mematuhi hukum dalam menjalankan pekerjaan, serta kewajiban menghormati properti dan kepentingan sah pemberi kerja. Dengan demikian, relasi kerja yang etis bersifat dua arah, yaitu perusahaan menghormati hak karyawan dan karyawan menunaikan kewajibannya secara jujur. Kerangka dua arah ini menjadi dasar bagi analisis sub-bab 7.4 dan 7.5.</p>`
    },
    {
      no: "7.4",
      title: "Isu Etis dalam Pengelolaan Hak Karyawan",
      body: `<h5>7.4.1 Diskriminasi dan Kesetaraan Kesempatan</h5>
      <p>Diskriminasi dalam konteks ketenagakerjaan dapat didefinisikan sebagai pemberian perlakuan yang berbeda kepada individu atau kelompok atas dasar karakteristik yang tidak relevan dengan tuntutan pekerjaan, seperti jenis kelamin, ras, agama, usia, atau kondisi disabilitas (Crane dan Matten, 2019). Inti persoalannya bukan pada adanya perbedaan perlakuan itu sendiri, melainkan pada relevansi kriteria yang digunakan. Membedakan kandidat berdasarkan kompetensi merupakan praktik seleksi yang sah, sedangkan membedakan kandidat berdasarkan penampilan fisik untuk pekerjaan administratif merupakan diskriminasi. Di Indonesia, praktik iklan lowongan kerja yang mencantumkan syarat usia maksimal, status pernikahan, atau penampilan menarik masih sering dijumpai dan menunjukkan bahwa kesadaran atas isu ini belum merata.</p>
      <p>Untuk mengoreksi ketidakadilan yang bersifat struktural, banyak organisasi menerapkan tindakan afirmatif atau <em>affirmative action</em>. Bentuknya berjenjang, mulai dari perekrutan aktif terhadap kelompok yang kurang terwakili, program pelatihan dan pendampingan khusus, hingga pemberian preferensi atau kuota dalam seleksi dan promosi. Bentuk yang terakhir menimbulkan perdebatan mengenai diskriminasi terbalik atau <em>reverse discrimination</em>, yaitu kekhawatiran bahwa kandidat dari kelompok mayoritas dirugikan oleh kriteria yang juga tidak sepenuhnya berbasis prestasi. Pendukung tindakan afirmatif berargumen bahwa kesetaraan formal tidak cukup ketika titik berangkat setiap kelompok tidak setara, sedangkan penentangnya berargumen bahwa ketidakadilan tidak dapat dikoreksi dengan ketidakadilan baru. Implikasi manajerialnya, perusahaan perlu menetapkan kebijakan keberagaman yang transparan, terukur, dan dapat dipertanggungjawabkan secara publik.</p>
      <p>Isu diskriminasi juga mencakup pelecehan seksual di tempat kerja, yang meliputi permintaan imbalan seksual yang dikaitkan dengan keputusan kepegawaian maupun penciptaan lingkungan kerja yang merendahkan dan mengintimidasi. Oleh karena itu, perusahaan wajib membangun mekanisme pengaduan yang aman, menindak pelaku tanpa memandang jabatan, dan melindungi korban dari pembalasan.</p>
      <h5>7.4.2 Hak atas Privasi</h5>
      <p>Privasi karyawan mencakup empat ranah, yaitu privasi fisik, privasi sosial, privasi informasional, dan privasi psikologis (Crane dan Matten, 2019). Kemajuan teknologi menjadikan hak ini semakin rentan karena perusahaan kini mampu memantau surel, riwayat penelusuran, lokasi, bahkan aktivitas media sosial karyawan dengan biaya rendah. Isu klasik dalam wilayah ini meliputi tes kesehatan dan tes narkoba, pengawasan elektronik di tempat kerja, serta penilaian atas perilaku karyawan di luar jam kerja. Pertanyaan etisnya selalu sama, yaitu sejauh mana informasi tersebut benar-benar relevan dengan pelaksanaan pekerjaan.</p>
      <p>Prinsip yang lazim digunakan adalah prinsip relevansi dan proporsionalitas. Tes narkoba dapat dibenarkan bagi pilot atau pengemudi karena berkaitan langsung dengan keselamatan publik, namun sulit dibenarkan bagi staf administrasi. Demikian pula pengawasan elektronik dapat diterima apabila karyawan diberi tahu secara terbuka, cakupannya terbatas pada kepentingan kerja, dan datanya tidak disalahgunakan. Dengan demikian, manajer perlu menyusun kebijakan privasi tertulis yang menjelaskan jenis data yang dikumpulkan, tujuan penggunaannya, dan jangka waktu penyimpanannya, sejalan pula dengan Undang-Undang Pelindungan Data Pribadi yang berlaku di Indonesia.</p>
      <h5>7.4.3 Proses yang Adil dan Pemutusan Hubungan Kerja</h5>
      <p>Hak atas <em>due process</em> berarti bahwa keputusan yang berdampak besar pada karyawan, seperti promosi, sanksi disiplin, dan pemberhentian, harus diambil melalui prosedur yang jelas, konsisten, dan berbasis bukti, bukan atas dasar kesewenangan atasan. Bentuk pelanggaran yang paling banyak disorot adalah perampingan organisasi atau <em>downsizing</em> yang dilakukan tanpa persiapan yang manusiawi. Perampingan mungkin sah secara ekonomi, namun cara pelaksanaannya menentukan kualitas etisnya. Praktik yang adil mencakup pemberitahuan sedini mungkin, konsultasi dengan perwakilan karyawan, kriteria pemilihan yang objektif, kompensasi yang layak, serta bantuan penempatan kerja kembali (<em>outplacement</em>).</p>
      <p>Gelombang pemutusan hubungan kerja pada perusahaan rintisan teknologi Indonesia pada periode 2022 sampai 2023 memberikan ilustrasi yang relevan. Perusahaan yang mengumumkan perampingan disertai pesangon di atas ketentuan, perpanjangan asuransi kesehatan, dan dukungan pencarian kerja memperoleh penilaian publik yang jauh lebih baik daripada perusahaan yang memberhentikan karyawan secara mendadak melalui pemberitahuan elektronik. Oleh karena itu, proses yang adil bukan hanya kewajiban moral, melainkan juga investasi reputasi dan pemeliharaan moral kerja karyawan yang bertahan.</p>
      <h5>7.4.4 Hak Berpartisipasi dan Berserikat</h5>
      <p>Hak partisipasi bersumber dari gagasan bahwa pihak yang terkena dampak suatu keputusan selayaknya memiliki suara dalam pengambilan keputusan tersebut. Partisipasi karyawan dapat berbentuk partisipasi finansial seperti kepemilikan saham karyawan, partisipasi operasional melalui pendelegasian, pemberian informasi, dan konsultasi, serta partisipasi representatif melalui serikat pekerja dan lembaga kerja sama bipartit. Menurut Crane dan Matten (2019), melemahnya keanggotaan serikat pekerja di banyak negara menimbulkan kekhawatiran bahwa saluran suara kolektif karyawan semakin sempit, padahal saluran tersebut merupakan penyeimbang utama asimetri kekuasaan dalam relasi kerja. Di Indonesia, kebebasan berserikat dijamin undang-undang, dan forum Lembaga Kerja Sama Bipartit diwajibkan bagi perusahaan berukuran menengah ke atas, meskipun efektivitasnya dalam praktik masih beragam.</p>
      <h5>7.4.5 Hak atas Kondisi Kerja yang Sehat dan Aman</h5>
      <p>Hak atas keselamatan dan kesehatan kerja merupakan hak yang paling tua diatur dalam hukum perburuhan, namun tetap relevan karena bentuk bahayanya terus berubah. Selain risiko fisik seperti kecelakaan mesin dan paparan bahan berbahaya, kini berkembang risiko psikososial berupa stres kerja, kelelahan kronis, dan jam kerja berlebihan. Sejumlah kecelakaan fatal di kawasan industri pengolahan nikel di Indonesia menunjukkan bahwa kepatuhan formal terhadap regulasi keselamatan dan kesehatan kerja tidak cukup tanpa budaya keselamatan yang dijalankan konsisten oleh manajemen. Implikasi manajerialnya, keselamatan harus diperlakukan sebagai nilai yang tidak dapat dinegosiasikan dengan target produksi, dan insentif manajer lini perlu memasukkan indikator keselamatan, bukan hanya keluaran.</p>
      <h5>7.4.6 Hak atas Upah yang Adil</h5>
      <p>Keadilan upah menyangkut dua pertanyaan, yaitu berapa batas bawah upah yang layak dan seberapa besar kesenjangan upah yang masih dapat dibenarkan. Konsep upah hidup layak (<em>living wage</em>) menuntut upah yang memungkinkan pekerja memenuhi kebutuhan dasar secara bermartabat, yang tidak selalu sama dengan upah minimum yang ditetapkan pemerintah. Di sisi lain, kesenjangan antara remunerasi eksekutif puncak dan upah pekerja terendah yang terus melebar menimbulkan pertanyaan keadilan distributif, karena sulit dibuktikan bahwa kontribusi eksekutif ratusan kali lebih besar daripada kontribusi pekerja biasa. Bagi manajemen, kebijakan pengupahan yang etis menuntut transparansi struktur upah, kesetaraan upah untuk pekerjaan yang setara, dan kehati-hatian dalam mengaitkan upah dengan kinerja agar tidak mendorong perilaku yang tidak etis.</p>
      <h5>7.4.7 Kebebasan Hati Nurani, Kebebasan Berbicara, dan Whistleblowing</h5>
      <p>Karyawan berhak menolak melaksanakan perintah yang bertentangan dengan hati nurani dan hukum, serta berhak mengungkapkan pelanggaran serius yang diketahuinya. Pengungkapan pelanggaran oleh orang dalam dikenal sebagai <em>whistleblowing</em>, yang dapat dilakukan melalui saluran internal maupun kepada pihak eksternal seperti regulator atau media. Mengacu pada kriteria yang lazim dirujuk dalam literatur etika bisnis, pengungkapan eksternal dipandang dapat dibenarkan apabila pelanggaran menimbulkan bahaya serius, pelapor telah menempuh saluran internal terlebih dahulu, saluran internal terbukti tidak efektif, pelapor memiliki bukti yang memadai, dan pengungkapan tersebut berpeluang menghentikan pelanggaran. Dilema etisnya terletak pada benturan antara kewajiban loyalitas kepada perusahaan dan kewajiban mencegah kerugian masyarakat.</p>
      <p>Praktik di Indonesia menunjukkan pentingnya sistem pelaporan pelanggaran atau <em>whistleblowing system</em> yang kini diwajibkan pada badan usaha milik negara dan diadopsi banyak emiten. Namun, keberadaan sistem tidak berarti banyak apabila pelapor tidak dilindungi dari pembalasan berupa mutasi, penurunan jabatan, atau pemecatan. Oleh karena itu, komitmen manajemen puncak terhadap perlindungan pelapor merupakan penentu utama efektivitas sistem tersebut.</p>
      <h5>7.4.8 Hak untuk Bekerja</h5>
      <p>Hak untuk bekerja berakar pada pandangan bahwa pekerjaan merupakan sarana utama manusia memperoleh penghidupan, harga diri, dan keterlibatan sosial. Hak ini tidak dipahami sebagai kewajiban perusahaan tertentu untuk mempekerjakan setiap orang, melainkan sebagai hak atas akses yang tidak diskriminatif terhadap kesempatan kerja serta tanggung jawab bersama pemerintah dan dunia usaha dalam menciptakan lapangan kerja. Konsekuensinya bagi perusahaan, keputusan otomatisasi dan relokasi pabrik yang menghapus banyak pekerjaan perlu mempertimbangkan program pelatihan ulang dan transisi yang adil bagi pekerja yang terdampak.</p>`
    },
    {
      no: "7.5",
      title: "Kewajiban Karyawan terhadap Perusahaan",
      body: `<p>Relasi kerja yang etis menuntut timbal balik, sehingga pembahasan hak karyawan perlu dilengkapi dengan kewajiban karyawan. Kewajiban pertama adalah mematuhi kontrak kerja, yang berarti memberikan kinerja pada tingkat yang wajar, menjaga kualitas pekerjaan, dan menunjukkan loyalitas yang proporsional terhadap kepentingan sah perusahaan. Loyalitas yang dituntut bukanlah kepatuhan buta, melainkan kesediaan untuk tidak merugikan perusahaan secara sengaja, misalnya dengan membocorkan rahasia dagang kepada pesaing. Kewajiban kedua adalah mematuhi hukum dalam menjalankan pekerjaan, sehingga karyawan tidak dapat berlindung di balik perintah atasan ketika melakukan pelanggaran seperti penyuapan atau pemalsuan laporan.</p>
      <p>Kewajiban ketiga adalah menghormati properti dan aset perusahaan dalam arti luas. Pelanggaran atas kewajiban ini mencakup bentuk yang kasat mata seperti pencurian dan penggelapan, maupun bentuk yang lebih halus seperti penggunaan jam kerja untuk kepentingan pribadi secara berlebihan, penyalahgunaan fasilitas kantor, dan manipulasi laporan pengeluaran. Bentuk pelanggaran yang paling serius terhadap aset informasi adalah perdagangan orang dalam atau <em>insider trading</em>, yaitu transaksi sekuritas dengan memanfaatkan informasi material yang belum tersedia bagi publik. Praktik ini dinilai tidak etis karena mencuri informasi milik perusahaan, merusak keadilan pasar bagi investor lain, dan menggerus kepercayaan terhadap pasar modal secara keseluruhan. Dengan demikian, program etika perusahaan perlu mengatur kewajiban karyawan ini secara eksplisit melalui kode etik, pelatihan, dan mekanisme penegakan yang konsisten.</p>`
    },
    {
      no: "7.6",
      title: "Mempekerjakan Orang dalam Konteks Global",
      body: `<p>Globalisasi memperluas isu etika ketenagakerjaan melampaui batas satu negara karena perusahaan kini mempekerjakan orang lintas yurisdiksi dengan standar hukum, tingkat upah, dan nilai budaya yang berbeda. Perbedaan nilai budaya dapat dipetakan antara lain dengan dimensi budaya Hofstede, seperti jarak kekuasaan, individualisme, maskulinitas, dan penghindaran ketidakpastian, yang membantu menjelaskan mengapa praktik yang dianggap wajar di satu negara dapat dianggap tidak etis di negara lain (Crane dan Matten, 2019). Sebagai contoh, pemberian pekerjaan kepada kerabat dapat dipandang sebagai nepotisme di negara individualis, namun dipandang sebagai kewajiban sosial di masyarakat kolektivis. Namun, relativisme budaya memiliki batas, karena terdapat standar minimum universal seperti larangan kerja paksa dan pekerja anak yang tidak dapat dikompromikan atas nama budaya setempat.</p>
      <p>Isu global yang paling tajam menyangkut upah dan kondisi kerja di negara berkembang. Perusahaan multinasional sering membayar upah yang rendah secara absolut dibandingkan negara asalnya, meskipun secara relatif setara atau lebih tinggi daripada upah setempat. Pertanyaan etisnya adalah apakah pembandingan relatif tersebut cukup untuk membenarkan kondisi kerja pabrik dengan jam kerja panjang dan pengawasan ketat yang sering disebut <em>sweatshop</em>. Persaingan antarnegara dalam menarik investasi melalui pelonggaran standar perburuhan dikenal sebagai perlombaan menuju titik terendah atau <em>race to the bottom</em>, yang menekan upah dan perlindungan pekerja secara sistemik. Industri garmen di Jawa yang memasok merek global menghadapi dinamika ini secara langsung ketika pesanan berpindah ke negara dengan upah lebih rendah, sehingga tanggung jawab etis tidak hanya berada pada pabrik lokal, melainkan juga pada merek global yang menentukan harga beli.</p>
      <p>Selain itu, migrasi tenaga kerja menimbulkan kelompok pekerja yang sangat rentan, yaitu pekerja migran dan pekerja tidak berdokumen. Pengalaman pekerja migran Indonesia di sektor domestik dan perkebunan di luar negeri menunjukkan risiko penahanan dokumen, jeratan utang biaya penempatan, dan keterbatasan akses keadilan. Implikasi manajerialnya, perusahaan yang beroperasi lintas negara perlu menetapkan standar ketenagakerjaan global yang berlaku di seluruh rantai pasok, melakukan audit sosial yang independen, dan menyediakan mekanisme pengaduan yang dapat diakses pekerja pada tingkat pemasok.</p>`
    },
    {
      no: "7.7",
      title: "Perspektif Kewargaan Korporasi dalam Relasi Karyawan",
      body: `<p>Perspektif kewargaan korporasi memandang tempat kerja sebagai arena tempat hak-hak kewargaan karyawan dijalankan atau justru dibatasi. Mengikuti pembagian klasik hak kewargaan, karyawan membawa hak sipil seperti kebebasan berpendapat dan privasi, hak sosial seperti jaminan kesehatan dan pendidikan, serta hak politik seperti berserikat dan bersuara, ke dalam kehidupan kerjanya sehari-hari. Menurut Crane dan Matten (2019), ketika negara mengurangi perannya dalam menyediakan jaminan sosial, perusahaan dalam praktik sering mengambil alih fungsi tersebut melalui asuransi kesehatan, dana pensiun, dan fasilitas pendidikan, sehingga perusahaan menjalankan peran yang menyerupai pemerintah bagi karyawannya.</p>
      <p>Peran menyerupai pemerintah tersebut menimbulkan dilema akuntabilitas. Perusahaan yang menjadi penyedia utama penghidupan dan layanan sosial di suatu komunitas, misalnya perusahaan tambang atau perkebunan yang mendominasi perekonomian satu kabupaten di luar Jawa, memiliki kekuasaan besar atas kehidupan warganya tanpa mekanisme pertanggungjawaban demokratis sebagaimana pemerintah. Oleh karena itu, perspektif kewargaan menuntut perusahaan membuka ruang partisipasi dan suara bagi karyawan dalam tata kelola keputusan yang menyangkut hak-hak mereka, bukan sekadar memberikan fasilitas secara paternalistik. Dengan demikian, demokrasi di tempat kerja bukan hanya persoalan efisiensi manajerial, melainkan bagian dari penghormatan terhadap status karyawan sebagai warga negara yang utuh.</p>`
    },
    {
      no: "7.8",
      title: "Keberlanjutan dan Relasi Kerja",
      body: `<p>Agenda keberlanjutan memperluas tanggung jawab perusahaan terhadap karyawan ke dimensi jangka panjang melalui gagasan pekerjaan yang berkelanjutan (<em>sustainable employment</em>), yaitu pola kerja yang dapat dipertahankan tanpa menggerus kesehatan fisik, kesejahteraan mental, dan kehidupan sosial pekerja. Salah satu tantangan utamanya adalah tren fleksibilitas kerja. Fleksibilitas dapat menguntungkan karyawan ketika berbentuk pengaturan waktu dan tempat kerja yang lebih longgar, namun dapat merugikan ketika berbentuk fleksibilitas numerik, yaitu kemudahan perusahaan menambah dan mengurangi pekerja melalui kontrak jangka pendek dan alih daya, yang memindahkan risiko bisnis kepada pihak yang paling lemah. Fenomena ekonomi gig di Indonesia, seperti status kemitraan pengemudi ojek daring yang bekerja penuh waktu tanpa jaminan sosial ketenagakerjaan yang memadai, memperlihatkan sisi gelap fleksibilitas tersebut.</p>
      <p>Isu keberlanjutan lain menyangkut keseimbangan kehidupan kerja (<em>work-life balance</em>). Teknologi komunikasi menghapus batas antara jam kerja dan waktu pribadi, sehingga muncul budaya selalu terhubung yang mendorong kelelahan kronis. Terkait hal ini dikenal pula gejala <em>presenteeism</em>, yaitu kecenderungan karyawan tetap hadir dan bekerja berlebihan meskipun sakit atau tidak produktif, karena kehadiran dianggap ukuran komitmen. Sebagian pekerja merespons tekanan tersebut dengan <em>downshifting</em>, yaitu secara sadar mengurangi jam kerja dan penghasilan demi kualitas hidup. Bagi manajemen, keberlanjutan relasi kerja menuntut desain pekerjaan yang realistis, penghormatan terhadap waktu istirahat, dan sistem penilaian kinerja yang mengukur hasil, bukan sekadar jam kehadiran, karena tenaga kerja yang sehat merupakan prasyarat kinerja jangka panjang perusahaan.</p>`
    },
    {
      no: "7.9",
      title: "Rangkuman",
      body: `<p>Bab ini menunjukkan bahwa karyawan merupakan pemangku kepentingan dengan kedudukan istimewa karena kontribusinya tidak terpisahkan dari dirinya sebagai manusia, sehingga pengelolaannya tidak dapat disamakan dengan pengelolaan sumber daya lain. Kerangka hak dan kewajiban karyawan yang dikembangkan Crane dan Matten (2019) menyediakan peta analisis yang sistematis, meliputi hak bebas dari diskriminasi, hak privasi, hak atas proses yang adil, hak berpartisipasi dan berserikat, hak atas keselamatan kerja, hak atas upah yang adil, kebebasan hati nurani dan berbicara, serta hak untuk bekerja, yang diimbangi kewajiban karyawan untuk mematuhi kontrak, menaati hukum, dan menghormati properti perusahaan.</p>
      <p>Globalisasi memperumit penerapan kerangka tersebut karena perusahaan beroperasi lintas budaya dan lintas tingkat upah, sehingga diperlukan standar minimum universal di tengah keragaman praktik lokal serta kewaspadaan terhadap perlombaan menuju standar perburuhan terendah. Perspektif kewargaan korporasi selanjutnya mengingatkan bahwa perusahaan sering menjalankan fungsi menyerupai pemerintah dalam menjamin hak sipil, sosial, dan politik karyawan, sehingga dituntut akuntabilitas dan ruang partisipasi yang sepadan dengan kekuasaannya.</p>
      <p>Akhirnya, agenda keberlanjutan mengarahkan perhatian pada kelayakan pola kerja dalam jangka panjang, termasuk sisi gelap fleksibilitas, tekanan terhadap keseimbangan kehidupan kerja, dan kerentanan pekerja ekonomi gig. Dengan demikian, manajer yang etis dituntut memperlakukan karyawan sebagai subjek moral yang memiliki hak, membangun sistem dan prosedur yang adil, serta memastikan bahwa keputusan bisnis, dari rekrutmen hingga perampingan, dapat dipertanggungjawabkan secara moral, hukum, dan sosial.</p>`
    },
    {
      no: "7.10",
      title: "Daftar Pustaka",
      body: `<p>Crane, A. dan Matten, D. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford: Oxford University Press.</p>
      <p>Hofstede, G., Hofstede, G. J. dan Minkov, M. (2010). <em>Cultures and Organizations: Software of the Mind</em>. Edisi ke-3. New York: McGraw-Hill.</p>
      <p>Republik Indonesia. (2003). <em>Undang-Undang Nomor 13 Tahun 2003 tentang Ketenagakerjaan</em>. Jakarta: Sekretariat Negara.</p>
      <p>Republik Indonesia. (2022). <em>Undang-Undang Nomor 27 Tahun 2022 tentang Pelindungan Data Pribadi</em>. Jakarta: Sekretariat Negara.</p>`
    }
  ]
};
