window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.bes = window.MBA_BOOK.bes || {};
window.MBA_BOOK.bes[12] = {
  bab: 12,
  judul: "BAB 12 KESIMPULAN DAN PERSPEKTIF MASA DEPAN: TATA KELOLA DAN ETIKA TEKNOLOGI",
  sumber: "Crane dan Matten (2019), Business Ethics, Edisi ke-5, Oxford University Press, Bab 12",
  lo: [
    "LO1 Merangkum kembali konsep inti etika bisnis, yaitu definisi etika bisnis, globalisasi, keberlanjutan, dan kewargaan korporasi, serta menjelaskan keterkaitan antarkonsep tersebut sebagai satu kerangka utuh.",
    "LO2 Menilai kontribusi teori etika normatif, model pengambilan keputusan etis, dan perangkat manajemen etika bagi praktik bisnis yang bertanggung jawab.",
    "LO3 Membandingkan relevansi etika bisnis pada berbagai kelompok pemangku kepentingan dan berbagai konteks organisasi, termasuk usaha kecil menengah, organisasi sektor publik, dan organisasi masyarakat sipil.",
    "LO4 Menganalisis tantangan etika yang ditimbulkan oleh teknologi digital, seperti mahadata, kecerdasan buatan, privasi, bias algoritmik, dan ekonomi berbagi, beserta implikasinya bagi korporasi.",
    "LO5 Mengevaluasi berbagai mekanisme tata kelola teknologi, mulai dari regulasi pemerintah, regulasi mandiri industri, hingga inovasi yang bertanggung jawab, serta merumuskan implikasi manajerialnya.",
    "LO6 Memproyeksikan arah perkembangan etika bisnis pada masa depan dalam kaitannya dengan agenda keberlanjutan global dan transformasi digital, termasuk dalam konteks Indonesia."
  ],
  sections: [
    {
      no: "12.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab penutup ini memiliki dua fungsi sekaligus, yaitu merangkum keseluruhan bangunan konsep etika bisnis yang telah dibahas pada bab-bab sebelumnya dan mengarahkan pandangan mahasiswa pada tantangan etika yang akan mendominasi masa depan, khususnya tantangan yang bersumber dari perkembangan teknologi digital. Menurut Crane dan Matten (2019), etika bisnis bukan sekadar kumpulan aturan moral yang berdiri sendiri, melainkan suatu bidang kajian yang terus berkembang mengikuti perubahan lingkungan bisnis, sehingga refleksi atas konsep inti perlu selalu dikaitkan dengan perkembangan kontekstual seperti globalisasi, keberlanjutan, dan digitalisasi. Oleh karena itu, bab ini disusun sebagai jembatan antara pemahaman konseptual yang telah dibangun dan kemampuan antisipatif yang dibutuhkan manajer pada masa depan.</p>
<p>Setelah mempelajari materi pada bab ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p><strong>LO1</strong> Merangkum kembali konsep inti etika bisnis, yaitu definisi etika bisnis, globalisasi, keberlanjutan, dan kewargaan korporasi, serta keterkaitannya sebagai satu kerangka utuh. <strong>LO2</strong> Menilai kontribusi teori etika normatif, model pengambilan keputusan etis, dan perangkat manajemen etika bagi praktik bisnis yang bertanggung jawab. <strong>LO3</strong> Membandingkan relevansi etika bisnis pada berbagai kelompok pemangku kepentingan dan berbagai konteks organisasi. <strong>LO4</strong> Menganalisis tantangan etika teknologi digital seperti mahadata, kecerdasan buatan, privasi, dan ekonomi berbagi. <strong>LO5</strong> Mengevaluasi mekanisme tata kelola teknologi beserta implikasi manajerialnya. <strong>LO6</strong> Memproyeksikan arah perkembangan etika bisnis pada masa depan, termasuk dalam konteks Indonesia.</p>`
    },
    {
      no: "12.2",
      title: "Rekapitulasi Konsep Inti Etika Bisnis",
      body: `<p>Sebelum membahas perspektif masa depan, perlu ditegaskan kembali fondasi konseptual yang menjadi kerangka keseluruhan buku. Crane dan Matten (2019) mendefinisikan etika bisnis sebagai kajian mengenai situasi, aktivitas, dan keputusan bisnis yang di dalamnya persoalan benar dan salah secara moral menjadi pokok perhatian. Definisi tersebut menegaskan bahwa etika bisnis berbeda dari sekadar kepatuhan hukum, karena banyak persoalan moral dalam bisnis justru muncul pada wilayah abu-abu yang belum atau tidak diatur oleh hukum. Dari definisi tersebut dapat disimpulkan bahwa etika bisnis merupakan disiplin yang menuntut pertimbangan moral aktif dari manajer, bukan sekadar kepatuhan pasif terhadap peraturan yang berlaku.</p>
<h5>12.2.1 Tiga Konteks Utama: Globalisasi, Keberlanjutan, dan Kewargaan Korporasi</h5>
<p>Terdapat tiga konsep kontekstual yang secara konsisten membingkai pembahasan etika bisnis dalam kerangka Crane dan Matten (2019), yaitu globalisasi, keberlanjutan, dan kewargaan korporasi. Globalisasi dipahami sebagai proses deteritorialisasi aktivitas ekonomi, sosial, dan politik yang menyebabkan keputusan bisnis di satu negara berdampak lintas batas, sehingga korporasi menghadapi pluralisme nilai dan kekosongan regulasi pada tataran global. Keberlanjutan atau <em>sustainability</em> merujuk pada pemenuhan kebutuhan generasi sekarang tanpa mengorbankan kemampuan generasi mendatang, yang dioperasionalkan melalui tiga pilar <em>triple bottom line</em>, yaitu kinerja ekonomi, sosial, dan lingkungan. Selain itu, konsep kewargaan korporasi atau <em>corporate citizenship</em> menggambarkan peran korporasi yang semakin luas dalam mengelola hak-hak kewargaan individu, terutama ketika pemerintah gagal atau tidak mampu menjalankan peran tersebut.</p>
<p>Ketiga konsep tersebut saling berkaitan erat dan tidak dapat dipahami secara terpisah. Globalisasi memperluas jangkauan dampak korporasi sekaligus melemahkan kapasitas regulasi negara-bangsa, keberlanjutan memberikan tujuan normatif jangka panjang yang harus dikejar, dan kewargaan korporasi menjelaskan peran politik baru korporasi dalam mengisi kekosongan tata kelola. Dengan demikian, korporasi modern tidak lagi dapat memposisikan diri semata-mata sebagai aktor ekonomi, melainkan juga sebagai aktor sosial dan politik yang keputusannya menuntut legitimasi moral. Implikasi manajerialnya adalah bahwa manajer perlu mengembangkan kepekaan terhadap dampak keputusan bisnis pada ranah yang jauh melampaui batas hukum dan batas geografis operasi perusahaan.</p>
<h5>12.2.2 Kontribusi Teori Etika dan Pengambilan Keputusan Etis</h5>
<p>Teori etika normatif memberikan perangkat nalar untuk menilai benar salahnya suatu tindakan bisnis. Teori konsekuensialis seperti egoisme dan utilitarianisme menilai moralitas dari akibat tindakan, sedangkan teori nonkonsekuensialis seperti etika kewajiban Kant dan etika hak menilai moralitas dari prinsip yang mendasari tindakan. Selain itu, pendekatan kontemporer seperti etika kebajikan, etika kepedulian, etika wacana, dan postmodernisme memperkaya analisis dengan menekankan karakter pelaku, relasi antarmanusia, dialog, dan intuisi moral. Crane dan Matten (2019) menganjurkan sikap pluralisme pragmatis, yaitu penggunaan beragam teori secara saling melengkapi sebagai lensa yang berbeda untuk menerangi satu masalah moral yang sama, karena tidak ada satu teori tunggal yang mampu menjawab seluruh persoalan etika bisnis.</p>
<p>Pada tataran deskriptif, model pengambilan keputusan etis menjelaskan bahwa keputusan moral individu dipengaruhi oleh faktor individual seperti tahap perkembangan moral kognitif dan faktor situasional seperti intensitas isu, budaya organisasi, dan sistem imbalan. Pemahaman tersebut kemudian dioperasionalkan melalui perangkat manajemen etika, antara lain kode etik, saluran pelaporan pelanggaran atau <em>whistleblowing</em>, pelatihan etika, audit sosial, komite etika, dan kepemimpinan etis. Oleh karena itu, pengelolaan etika yang efektif menuntut kombinasi antara pendekatan kepatuhan yang berbasis aturan dan pendekatan integritas yang berbasis nilai, serta perhatian pada budaya organisasi informal yang sering kali lebih menentukan perilaku nyata karyawan daripada dokumen formal.</p>`
    },
    {
      no: "12.3",
      title: "Etika Bisnis dalam Perspektif Pemangku Kepentingan",
      body: `<p>Salah satu sumbangan terpenting kerangka Crane dan Matten (2019) adalah pengorganisasian isu etika bisnis berdasarkan kelompok pemangku kepentingan atau <em>stakeholder</em>. Menurut Freeman sebagaimana dikutip Crane dan Matten (2019), pemangku kepentingan adalah setiap kelompok atau individu yang mempengaruhi atau dipengaruhi oleh pencapaian tujuan organisasi. Dari definisi tersebut dapat disimpulkan bahwa tanggung jawab moral korporasi tidak hanya tertuju pada pemegang saham, melainkan tersebar pada jejaring relasi yang luas dan saling bergantung. Setiap kelompok pemangku kepentingan membawa isu etika yang khas sekaligus peran tata kelola yang berbeda dalam mengawasi perilaku korporasi.</p>
<p>Pemegang saham berkaitan dengan isu tata kelola korporat, transparansi laporan keuangan, remunerasi eksekutif, perdagangan orang dalam, dan tanggung jawab investor melalui investasi yang etis. Karyawan berkaitan dengan isu diskriminasi, privasi di tempat kerja, kondisi kerja yang layak, kebebasan berserikat, dan dilema loyalitas ketika menghadapi pelanggaran perusahaan. Konsumen berkaitan dengan isu keamanan produk, kejujuran iklan, penetapan harga yang adil, praktik pemasaran yang rentan mengeksploitasi kelompok lemah, serta perlindungan data pelanggan. Pemasok dan pesaing berkaitan dengan etika negosiasi, suap dan gratifikasi, kekuatan tawar yang timpang, persaingan usaha yang sehat, dan tanggung jawab atas kondisi kerja di sepanjang rantai pasok global. Di sisi lain, masyarakat sipil berperan sebagai kekuatan pengawas melalui kampanye, boikot, dan kemitraan, sedangkan pemerintah berperan sebagai regulator sekaligus mitra yang hubungannya dengan bisnis rawan konflik kepentingan seperti lobi dan korupsi.</p>
<table class="bk-table"><caption>Tabel 12.1 Isu Etika Utama dan Peran Tata Kelola per Kelompok Pemangku Kepentingan</caption>
<thead><tr><th>Pemangku Kepentingan</th><th>Isu Etika Utama</th><th>Peran dalam Tata Kelola Korporasi</th></tr></thead>
<tbody>
<tr><td>Pemegang saham</td><td>Transparansi, remunerasi eksekutif, perdagangan orang dalam</td><td>Pemilik yang menuntut akuntabilitas melalui mekanisme tata kelola korporat dan investasi etis</td></tr>
<tr><td>Karyawan</td><td>Diskriminasi, privasi, kondisi kerja, kebebasan berserikat</td><td>Pelaksana nilai perusahaan sekaligus pengawas internal melalui pelaporan pelanggaran</td></tr>
<tr><td>Konsumen</td><td>Keamanan produk, iklan menyesatkan, harga, data pribadi</td><td>Penekan pasar melalui konsumsi etis dan boikot</td></tr>
<tr><td>Pemasok dan pesaing</td><td>Suap, kekuatan tawar timpang, kondisi kerja rantai pasok</td><td>Mitra dalam standar industri dan kode etik rantai pasok</td></tr>
<tr><td>Masyarakat sipil</td><td>Legitimasi kampanye, akuntabilitas organisasi nirlaba</td><td>Pengawas eksternal melalui advokasi, kampanye, dan kemitraan</td></tr>
<tr><td>Pemerintah</td><td>Lobi, korupsi, penangkapan regulasi</td><td>Regulator, penegak hukum, dan mitra ko-regulasi</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>
<p>Perspektif pemangku kepentingan tersebut memiliki implikasi manajerial yang penting bagi perumusan strategi. Manajer perlu memetakan pemangku kepentingan berdasarkan kekuatan, legitimasi, dan urgensi klaimnya, kemudian membangun mekanisme dialog dan akuntabilitas yang sesuai untuk masing-masing kelompok. Dalam konteks Indonesia, kewajiban tanggung jawab sosial dan lingkungan yang diatur dalam Undang-Undang Nomor 40 Tahun 2007 tentang Perseroan Terbatas menunjukkan bahwa perspektif pemangku kepentingan telah diadopsi secara formal dalam kerangka hukum nasional, sehingga pengabaian terhadap pemangku kepentingan bukan hanya berisiko reputasi, melainkan juga berisiko hukum.</p>`
    },
    {
      no: "12.4",
      title: "Etika Bisnis dalam Berbagai Konteks Organisasi",
      body: `<p>Salah satu refleksi penting pada bagian penutup buku adalah pengakuan bahwa pembahasan etika bisnis cenderung berfokus pada korporasi besar, padahal sebagian besar aktivitas ekonomi dunia justru dijalankan oleh organisasi dengan karakteristik yang berbeda. Crane dan Matten (2019) menegaskan bahwa prinsip etika bisnis perlu diterjemahkan secara berbeda ketika diterapkan pada usaha kecil dan menengah, organisasi sektor publik, dan organisasi masyarakat sipil, karena struktur insentif, sumber daya, dan basis legitimasi ketiganya tidak sama dengan korporasi multinasional. Dengan demikian, mahasiswa perlu memahami bahwa satu perangkat manajemen etika tidak dapat diterapkan secara seragam pada semua jenis organisasi.</p>
<p>Pada usaha kecil dan menengah, etika cenderung dikelola secara informal melalui nilai personal pemilik dan kedekatan relasi dengan karyawan serta pelanggan, bukan melalui kode etik tertulis atau komite etika. Kekuatan konteks ini terletak pada keteladanan langsung pemilik, sedangkan kelemahannya terletak pada ketiadaan mekanisme formal ketika terjadi sengketa dan keterbatasan sumber daya untuk kepatuhan. Dalam konteks Indonesia, usaha mikro, kecil, dan menengah menyumbang porsi terbesar lapangan kerja nasional, sehingga pembangunan integritas bisnis nasional tidak cukup hanya menyasar emiten besar, melainkan harus menjangkau jutaan pelaku usaha kecil melalui pendekatan pembinaan yang sederhana dan kontekstual. Di sisi lain, organisasi sektor publik menghadapi isu etika yang khas seperti akuntabilitas kepada publik, konflik kepentingan, dan integritas pengadaan barang dan jasa, sementara organisasi masyarakat sipil menghadapi tuntutan akuntabilitas atas dana donor, legitimasi klaim mewakili masyarakat, dan konsistensi antara nilai yang dikampanyekan dan praktik internalnya.</p>
<p>Perkembangan lain yang digarisbawahi adalah munculnya bentuk organisasi hibrida seperti wirausaha sosial atau <em>social enterprise</em> yang menggabungkan misi sosial dengan model bisnis komersial. Bentuk hibrida ini menjanjikan solusi atas masalah sosial yang tidak tertangani pasar maupun negara, namun juga menghadirkan ketegangan etis tersendiri ketika logika komersial berbenturan dengan logika misi sosial. Oleh karena itu, implikasi manajerial dari bagian ini adalah pentingnya menyesuaikan desain tata kelola etika dengan karakter organisasi, misalnya mengandalkan keteladanan dan dialog pada organisasi kecil, memperkuat sistem formal pada organisasi besar, serta menjaga keseimbangan misi ganda pada organisasi hibrida.</p>`
    },
    {
      no: "12.5",
      title: "Tantangan Etika Era Digital: Mahadata, Privasi, dan Kecerdasan Buatan",
      body: `<p>Perspektif masa depan yang paling menonjol dalam bab penutup ini adalah kebangkitan teknologi digital sebagai sumber persoalan etika bisnis baru. Crane dan Matten (2019) menempatkan digitalisasi sejajar dengan globalisasi dan keberlanjutan sebagai kekuatan yang mengubah lanskap etika bisnis secara mendasar, karena teknologi digital mengubah cara perusahaan menciptakan nilai, cara konsumen berinteraksi, dan cara kekuasaan terdistribusi antara korporasi, negara, dan individu. Ciri khas persoalan etika teknologi adalah kecepatan inovasi yang jauh melampaui kecepatan pembentukan norma sosial dan regulasi, sehingga tercipta kesenjangan tata kelola atau <em>governance gap</em> yang menuntut korporasi mengambil tanggung jawab moral sebelum hukum mewajibkannya.</p>
<h5>12.5.1 Mahadata dan Privasi</h5>
<p>Model bisnis digital kontemporer dibangun di atas pengumpulan dan pengolahan data pribadi dalam skala masif, yang lazim disebut mahadata atau <em>big data</em>. Persoalan etisnya terletak pada beberapa dimensi, yaitu keabsahan persetujuan pengguna yang sering kali diberikan tanpa pemahaman memadai, penggunaan data untuk tujuan yang berbeda dari tujuan pengumpulan awal, pemantauan perilaku yang mendalam demi kepentingan komersial, dan risiko kebocoran data yang merugikan jutaan orang. Fenomena komersialisasi jejak perilaku pengguna ini oleh sebagian ilmuwan disebut sebagai kapitalisme pengawasan atau <em>surveillance capitalism</em>, yaitu model akumulasi yang menjadikan pengalaman manusia sebagai bahan baku prediksi perilaku yang diperjualbelikan. Dalam konteks Indonesia, rangkaian insiden kebocoran data pelanggan pada berbagai platform digital dan lembaga publik pada periode 2020 sampai 2022 mendorong lahirnya Undang-Undang Nomor 27 Tahun 2022 tentang Pelindungan Data Pribadi, yang menuntut perusahaan menunjuk petugas pelindungan data, membatasi pemrosesan data, dan menghadapi sanksi atas kelalaian.</p>
<h5>12.5.2 Kecerdasan Buatan dan Bias Algoritmik</h5>
<p>Kecerdasan buatan atau <em>artificial intelligence</em> menimbulkan lapisan persoalan etika berikutnya karena keputusan yang dahulu diambil manusia kini didelegasikan kepada algoritma, misalnya dalam penyaringan lamaran kerja, penilaian kelayakan kredit, penetapan harga dinamis, dan moderasi konten. Persoalan pertama adalah bias algoritmik, yaitu kecenderungan sistem menghasilkan keputusan diskriminatif karena dilatih dengan data historis yang mengandung ketimpangan, misalnya sistem rekrutmen yang merugikan pelamar perempuan karena belajar dari pola perekrutan masa lalu yang didominasi laki-laki. Persoalan kedua adalah opasitas atau sifat kotak hitam algoritma yang menyulitkan penjelasan dan gugatan atas keputusan yang merugikan, sehingga muncul tuntutan atas <em>explainability</em> dan <em>algorithmic accountability</em>. Persoalan ketiga adalah atribusi tanggung jawab moral, yaitu pertanyaan mengenai siapa yang bertanggung jawab ketika sistem otonom menimbulkan kerugian, apakah pengembang, operator, atau pemilik data. Sebagai contoh di Indonesia, penilaian kredit berbasis algoritma pada industri teknologi finansial berpotensi memperluas inklusi keuangan, namun sekaligus berisiko mengucilkan kelompok masyarakat yang jejak digitalnya tipis apabila variabel penilaian tidak diaudit secara berkala.</p>
<p>Implikasi manajerial dari kedua isu tersebut adalah bahwa perusahaan tidak dapat memperlakukan etika data dan etika algoritma sebagai urusan teknis semata. Manajemen perlu menetapkan prinsip pemrosesan data yang sah dan proporsional, melakukan audit bias secara berkala, menyediakan mekanisme banding bagi pihak yang dirugikan keputusan algoritmik, dan memastikan bahwa pertimbangan etis dilibatkan sejak tahap desain produk, bukan setelah produk diluncurkan. Dengan demikian, kompetensi etika digital menjadi bagian dari kompetensi inti manajerial, bukan sekadar tanggung jawab divisi teknologi informasi.</p>`
    },
    {
      no: "12.6",
      title: "Ekonomi Berbagi, Otomasi, dan Masa Depan Pekerjaan",
      body: `<p>Selain persoalan data dan algoritma, transformasi digital juga melahirkan model bisnis platform yang mengubah struktur pasar tenaga kerja dan konsumsi. Ekonomi berbagi atau <em>sharing economy</em> pada mulanya dimaknai sebagai pemanfaatan bersama aset yang menganggur melalui platform digital, namun dalam praktiknya berkembang menjadi ekonomi pertunjukan atau <em>gig economy</em> yang menempatkan jutaan pekerja sebagai mitra lepas tanpa status karyawan. Crane dan Matten (2019) mencatat bahwa model ini menimbulkan pertanyaan etis mengenai kaburnya tanggung jawab pemberi kerja, karena platform menikmati kendali algoritmik atas cara kerja mitranya, tetapi menolak kewajiban ketenagakerjaan seperti upah minimum, jaminan sosial, dan hak berserikat. Selain itu, model platform cenderung menghasilkan konsentrasi pasar karena efek jaringan, sehingga menimbulkan isu persaingan usaha dan ketimpangan kekuatan tawar terhadap mitra dan konsumen.</p>
<p>Contoh Indonesia yang sangat relevan adalah ekosistem transportasi daring seperti Gojek dan Grab yang menyerap jutaan pengemudi sebagai mitra. Di satu sisi, platform tersebut memperluas kesempatan kerja, meningkatkan pendapatan sebagian masyarakat, dan mendorong inklusi keuangan melalui dompet digital. Namun, di sisi lain muncul perdebatan publik yang berulang mengenai skema potongan komisi, perubahan tarif sepihak melalui algoritma, ketiadaan jaminan sosial yang memadai, dan ketergantungan penuh pengemudi pada keputusan sistem yang tidak transparan. Perdebatan tersebut menggambarkan secara nyata dilema etika platform, yaitu klaim kemitraan yang setara berhadapan dengan realitas kendali algoritmik yang menyerupai hubungan kerja. Oleh karena itu, regulator Indonesia melalui Kementerian Perhubungan telah menetapkan batas tarif dan batas komisi aplikator, yang menunjukkan pergeseran dari regulasi mandiri platform menuju intervensi negara.</p>
<p>Isu lanjutan yang tidak kalah penting adalah otomasi dan masa depan pekerjaan. Kecerdasan buatan dan robotika diperkirakan menggantikan sebagian besar pekerjaan rutin, baik manual maupun kognitif, sehingga menimbulkan pertanyaan etis mengenai tanggung jawab perusahaan terhadap karyawan yang tergantikan. Pilihan etis perusahaan berkisar dari sekadar pemutusan hubungan kerja yang legal, hingga investasi aktif pada pelatihan ulang atau <em>reskilling</em> dan penempatan ulang tenaga kerja. Dengan demikian, implikasi manajerialnya adalah bahwa keputusan adopsi teknologi tidak boleh dinilai semata dari efisiensi biaya, melainkan juga dari dampak sosialnya terhadap karyawan, komunitas, dan legitimasi jangka panjang perusahaan sebagai warga korporasi yang baik.</p>`
    },
    {
      no: "12.7",
      title: "Tata Kelola Teknologi: Regulasi, Regulasi Mandiri, dan Inovasi yang Bertanggung Jawab",
      body: `<p>Pertanyaan sentral pada bagian akhir buku adalah bagaimana masyarakat sebaiknya mengatur teknologi agar manfaatnya dapat dinikmati tanpa mengorbankan nilai kemanusiaan. Crane dan Matten (2019) menunjukkan bahwa tidak ada mekanisme tunggal yang memadai, sehingga tata kelola teknologi harus dipahami sebagai kombinasi berlapis antara regulasi pemerintah, regulasi mandiri korporasi dan industri, serta tata kelola multipihak yang melibatkan masyarakat sipil dan akademisi. Regulasi pemerintah memiliki kekuatan pemaksa dan legitimasi demokratis, namun sering tertinggal dari kecepatan inovasi dan terbatas oleh yurisdiksi nasional, sebagaimana tampak pada kesulitan berbagai negara menegakkan aturan terhadap platform global. Di sisi lain, regulasi mandiri seperti kode etik industri dan prinsip etika kecerdasan buatan yang diterbitkan perusahaan teknologi bersifat lentur dan cepat, namun rawan menjadi pencucian etika atau <em>ethics washing</em> apabila tidak disertai mekanisme akuntabilitas yang independen.</p>
<p>Sebagai jalan tengah, berkembang kerangka inovasi yang bertanggung jawab atau <em>responsible innovation</em> yang menuntut pertimbangan etis diintegrasikan ke dalam keseluruhan proses inovasi. Kerangka ini lazim dirumuskan dalam empat dimensi yang dapat digunakan manajer sebagai daftar uji, yaitu: pertama, antisipasi atau <em>anticipation</em>, yakni memetakan secara sistematis dampak yang mungkin timbul sebelum teknologi diluncurkan; kedua, refleksivitas atau <em>reflexivity</em>, yakni kesediaan organisasi mempertanyakan asumsi dan motif inovasinya sendiri; ketiga, inklusi atau <em>inclusion</em>, yakni pelibatan pemangku kepentingan yang terdampak dalam proses desain; dan keempat, responsivitas atau <em>responsiveness</em>, yakni kemampuan mengubah arah pengembangan ketika muncul bukti dampak negatif. Cara memakainya adalah dengan menjadikan keempat dimensi tersebut sebagai pertanyaan wajib pada setiap gerbang keputusan pengembangan produk, sehingga pertimbangan etis melekat pada proses, bukan menjadi tinjauan tempelan di akhir. Pendekatan pelengkapnya adalah etika berdasarkan desain atau <em>ethics by design</em> dan privasi berdasarkan desain atau <em>privacy by design</em>, yang menanamkan nilai etis langsung ke dalam arsitektur teknis produk.</p>
<table class="bk-table"><caption>Tabel 12.2 Perbandingan Mekanisme Tata Kelola Teknologi</caption>
<thead><tr><th>Mekanisme</th><th>Contoh Instrumen</th><th>Kekuatan</th><th>Kelemahan</th></tr></thead>
<tbody>
<tr><td>Regulasi pemerintah</td><td>Undang-undang pelindungan data pribadi, regulasi tarif transportasi daring</td><td>Daya paksa hukum dan legitimasi demokratis</td><td>Tertinggal dari inovasi, terbatas yurisdiksi nasional</td></tr>
<tr><td>Regulasi mandiri korporasi dan industri</td><td>Kode etik industri, prinsip etika kecerdasan buatan perusahaan, dewan etika internal</td><td>Cepat, lentur, dekat dengan pengetahuan teknis</td><td>Rawan pencucian etika, tanpa sanksi eksternal</td></tr>
<tr><td>Tata kelola multipihak</td><td>Forum standar global, kemitraan dengan masyarakat sipil dan akademisi</td><td>Legitimasi luas, menjangkau lintas batas negara</td><td>Proses lambat, kepatuhan bersifat sukarela</td></tr>
<tr><td>Inovasi yang bertanggung jawab</td><td>Antisipasi, refleksivitas, inklusi, responsivitas, etika berdasarkan desain</td><td>Melekat pada proses inovasi sejak awal</td><td>Bergantung pada komitmen dan kapabilitas internal</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Crane dan Matten (2019)</td></tr></tfoot></table>
<p>Dalam konteks Indonesia, arsitektur tata kelola teknologi memperlihatkan kombinasi mekanisme tersebut secara nyata. Undang-Undang Pelindungan Data Pribadi dan berbagai peraturan Otoritas Jasa Keuangan mengenai teknologi finansial mewakili jalur regulasi negara, sementara asosiasi seperti Asosiasi Fintech Pendanaan Bersama Indonesia menjalankan regulasi mandiri melalui kode perilaku bagi penyelenggara pinjaman daring, antara lain pembatasan cara penagihan dan transparansi biaya. Pengalaman maraknya pinjaman daring ilegal menunjukkan bahwa regulasi mandiri tanpa penegakan negara tidak memadai, sebaliknya penegakan negara tanpa kerja sama industri berjalan lambat. Oleh karena itu, implikasi manajerialnya adalah perusahaan sebaiknya tidak memandang regulasi sebagai beban, melainkan berpartisipasi aktif membentuk standar industri yang kredibel, karena kepercayaan publik terhadap keseluruhan industri merupakan aset bersama yang menentukan keberlanjutan model bisnis digital.</p>`
    },
    {
      no: "12.8",
      title: "Perspektif Masa Depan Etika Bisnis",
      body: `<p>Bagian akhir bab merumuskan arah perkembangan etika bisnis pada masa depan dengan menegaskan bahwa relevansi bidang ini akan semakin meningkat, bukan menurun. Crane dan Matten (2019) berargumen bahwa tiga kekuatan besar akan terus membentuk agenda etika bisnis, yaitu berlanjutnya globalisasi beserta arus baliknya berupa proteksionisme dan populisme, semakin mendesaknya krisis keberlanjutan terutama perubahan iklim, dan semakin dalamnya penetrasi teknologi digital ke seluruh aspek kehidupan. Agenda keberlanjutan global yang dikristalkan dalam Tujuan Pembangunan Berkelanjutan atau <em>Sustainable Development Goals</em> menempatkan korporasi sebagai aktor kunci penyelesaian masalah global, sehingga ekspektasi masyarakat terhadap peran sosial korporasi akan terus meningkat. Dengan demikian, batas antara strategi bisnis dan tanggung jawab sosial akan semakin kabur, dan kemampuan mengelola isu etika akan menjadi penentu daya saing, bukan sekadar pelengkap reputasi.</p>
<p>Pada ranah teknologi, masa depan etika bisnis akan ditandai oleh perluasan pertanyaan moral dari dampak teknologi menuju hakikat teknologi itu sendiri. Pertanyaan yang semula berkisar pada bagaimana menggunakan teknologi secara benar akan bergeser menjadi apakah teknologi tertentu layak dikembangkan sama sekali, misalnya sistem senjata otonom, pengawasan biometrik massal, dan manipulasi perilaku berbasis kecerdasan buatan. Pergeseran tersebut menuntut korporasi memiliki kapasitas musyawarah etis atau <em>ethical deliberation</em> yang melibatkan beragam disiplin dan pemangku kepentingan, serta kesediaan menolak peluang komersial yang bertentangan dengan nilai kemanusiaan. Selain itu, profesi manajer sendiri akan berubah, karena sebagian fungsi analitis manajerial diambil alih algoritma, sehingga nilai tambah manajer justru terletak pada pertimbangan moral, empati, dan kebijaksanaan praktis yang tidak dapat diotomasi.</p>
<p>Bagi Indonesia, perspektif masa depan tersebut memiliki resonansi khusus. Sebagai negara dengan ekonomi digital terbesar di Asia Tenggara dan populasi muda yang besar, Indonesia berpeluang menikmati dividen digital sekaligus menghadapi risiko ketimpangan digital, eksploitasi pekerja platform, dan penyalahgunaan data dalam skala luas. Perusahaan Indonesia yang mampu membangun kepercayaan digital, mematuhi standar pelindungan data, dan memperlakukan mitra kerja platform secara adil akan memiliki keunggulan legitimasi di mata konsumen, regulator, dan investor global yang semakin menilai kinerja lingkungan, sosial, dan tata kelola. Oleh karena itu, pendidikan etika bisnis bagi calon pemimpin perusahaan Indonesia perlu membekali kemampuan menganalisis persoalan etika teknologi secara sistematis sebagaimana kerangka yang telah diuraikan pada bab ini.</p>`
    },
    {
      no: "12.9",
      title: "Rangkuman",
      body: `<p>Bab penutup ini merangkum keseluruhan bangunan konsep etika bisnis dan mengarahkannya pada tantangan masa depan. Etika bisnis dipahami sebagai kajian atas persoalan benar dan salah secara moral dalam aktivitas bisnis yang melampaui kepatuhan hukum, dan dibingkai oleh tiga konteks besar, yaitu globalisasi, keberlanjutan, dan kewargaan korporasi. Teori etika normatif memberikan lensa penilaian moral yang saling melengkapi, model pengambilan keputusan etis menjelaskan faktor individual dan situasional yang mempengaruhi perilaku, dan perangkat manajemen etika menerjemahkan komitmen moral menjadi sistem organisasi. Perspektif pemangku kepentingan mengorganisasi isu etika pada relasi korporasi dengan pemegang saham, karyawan, konsumen, pemasok, pesaing, masyarakat sipil, dan pemerintah, serta perlu disesuaikan penerapannya pada konteks usaha kecil menengah, sektor publik, organisasi masyarakat sipil, dan organisasi hibrida.</p>
<p>Perspektif masa depan bab ini menempatkan teknologi digital sebagai sumber utama persoalan etika bisnis baru. Mahadata dan model bisnis berbasis data menimbulkan persoalan privasi, persetujuan, dan kapitalisme pengawasan; kecerdasan buatan menimbulkan persoalan bias algoritmik, opasitas, dan atribusi tanggung jawab; ekonomi platform menimbulkan persoalan status pekerja dan kendali algoritmik; sedangkan otomasi menimbulkan persoalan tanggung jawab atas masa depan pekerjaan. Tata kelola atas persoalan tersebut menuntut kombinasi regulasi pemerintah, regulasi mandiri industri, tata kelola multipihak, dan kerangka inovasi yang bertanggung jawab dengan empat dimensinya, yaitu antisipasi, refleksivitas, inklusi, dan responsivitas. Pengalaman Indonesia dengan Undang-Undang Pelindungan Data Pribadi, regulasi transportasi daring, dan penertiban pinjaman daring ilegal menunjukkan bekerjanya kombinasi mekanisme tersebut dalam praktik.</p>
<p>Dengan demikian, pesan akhir bab ini adalah bahwa etika bisnis akan semakin sentral bagi praktik manajemen pada masa depan. Manajer masa depan dituntut bukan hanya menguasai analisis ekonomi dan teknologi, melainkan juga kapasitas musyawarah etis untuk menimbang teknologi mana yang layak dikembangkan, model bisnis mana yang adil, dan tanggung jawab apa yang melekat pada kekuatan korporasi. Kemampuan tersebut merupakan sumber legitimasi sekaligus keunggulan bersaing yang berkelanjutan bagi perusahaan pada era digital.</p>`
    },
    {
      no: "12.10",
      title: "Daftar Pustaka",
      body: `<p>Crane, A. dan Matten, D. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi ke-5. Oxford: Oxford University Press.</p>
<p>Crane, A., Matten, D., Glozer, S. dan Spence, L. J. (2019). <em>Business Ethics</em>. Edisi ke-5. Oxford: Oxford University Press.</p>
<p>Republik Indonesia. (2007). <em>Undang-Undang Nomor 40 Tahun 2007 tentang Perseroan Terbatas</em>. Jakarta: Sekretariat Negara.</p>
<p>Republik Indonesia. (2022). <em>Undang-Undang Nomor 27 Tahun 2022 tentang Pelindungan Data Pribadi</em>. Jakarta: Sekretariat Negara.</p>`
    }
  ]
};
