window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.gbe = window.MBA_BOOK.gbe || {};
window.MBA_BOOK.gbe[7] = {
  bab: 7,
  judul: "BAB 7 LINGKUNGAN TEKNOLOGI",
  sumber: "Modul GBE: deck Pak Wirawan (Google Drive) dan referensi akademik standar topik Lingkungan Teknologi",
  lo: [
    "LO1 Menjelaskan hakikat lingkungan teknologi serta hubungan antara kreasi, invensi, dan inovasi dalam konteks bisnis global.",
    "LO2 Mengidentifikasi tren dan kemajuan teknologi utama beserta kerangka analitis untuk menilai kematangan dan arah perkembangannya.",
    "LO3 Menganalisis mekanisme disrupsi digital dan merumuskan respons strategis perusahaan terhadap ancaman maupun peluang disrupsi.",
    "LO4 Menilai peran kecerdasan buatan sebagai teknologi berdaya guna umum beserta implikasi manajerial dan etisnya.",
    "LO5 Merumuskan implikasi lingkungan teknologi terhadap pengembangan produk, proses, dan strategi komersialisasi teknologi."
  ],
  sections: [
    {
      no: "7.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi ketujuh mata kuliah <em>General Business Environment</em> membahas lingkungan teknologi sebagai salah satu dimensi eksternal yang paling dinamis dan paling menentukan keberlangsungan usaha. Teknologi dan inovasi merupakan kunci bagi kelangsungan hidup serta pertumbuhan bisnis pada pasar global yang semakin kompetitif, sehingga manajer dituntut memahami bukan hanya teknologi itu sendiri, melainkan juga ekosistem kelembagaan yang menghasilkannya dan mekanisme yang mengubah temuan ilmiah menjadi nilai komersial. Materi sesi ini disusun berdasarkan modul dosen pengampu serta referensi akademik standar dalam bidang manajemen teknologi dan inovasi.</p>
      <p>Setelah menyelesaikan sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <p>Pertama, menjelaskan hakikat lingkungan teknologi serta membedakan konsep kreasi, invensi, dan inovasi. Kedua, mengidentifikasi tren dan kemajuan teknologi kontemporer beserta kerangka analitis seperti kurva S dan <em>Technology Readiness Level</em>. Ketiga, menganalisis mekanisme disrupsi digital serta merumuskan respons strategis perusahaan mapan. Keempat, menilai peran kecerdasan buatan dalam lingkungan bisnis beserta implikasi manajerial dan etisnya. Kelima, merumuskan implikasi lingkungan teknologi terhadap pengembangan produk, proses, dan komersialisasi teknologi, termasuk pilihan antara lisensi dan <em>spin-out</em>.</p>`
    },
    {
      no: "7.2",
      title: "Hakikat Lingkungan Teknologi dan Inovasi",
      body: `<p>Lingkungan bisnis eksternal terdiri atas sejumlah dimensi yang lazim dianalisis melalui kerangka PESTLE, yaitu politik, ekonomi, sosial, teknologi, hukum, dan lingkungan alam. Dimensi teknologi mencakup keseluruhan pengetahuan, keterampilan, artefak, dan kelembagaan yang memengaruhi cara perusahaan menciptakan serta menyampaikan nilai kepada pelanggan. Menurut Schilling (2020), inovasi teknologi merupakan tindakan memperkenalkan perangkat, metode, atau bahan baru untuk diaplikasikan pada tujuan komersial maupun praktis. Sementara itu, Khalil (2000) mendefinisikan teknologi sebagai seluruh pengetahuan, produk, proses, alat, metode, dan sistem yang digunakan dalam penciptaan barang atau penyediaan jasa. Dari definisi tersebut dapat disimpulkan bahwa lingkungan teknologi bukan sekadar kumpulan mesin atau perangkat lunak, melainkan sistem pengetahuan terapan yang terus berubah dan mengubah struktur persaingan industri.</p>
      <h5>7.2.1 Kreasi, Invensi, dan Inovasi</h5>
      <p>Modul dosen pengampu menekankan rantai konseptual kreasi, invensi, dan inovasi sebagai transformasi semangat berkarya menjadi solusi teknologis. Kreasi merujuk pada aktivitas kreatif menghasilkan gagasan baru, invensi merujuk pada perwujudan gagasan menjadi temuan yang dapat didemonstrasikan, sedangkan inovasi merujuk pada penerapan temuan tersebut sehingga menghasilkan nilai ekonomi atau sosial. Menurut Tidd dan Bessant (2021), inovasi adalah proses mengubah peluang menjadi gagasan baru dan memasukkannya ke dalam praktik yang digunakan secara luas. Dengan demikian, sebuah paten yang tidak pernah diterapkan baru berhenti pada tahap invensi, dan nilai bisnis baru muncul ketika temuan tersebut diadopsi pasar. Implikasi manajerialnya adalah perusahaan perlu mengelola keseluruhan rantai tersebut, bukan hanya berinvestasi pada riset, karena kegagalan komersialisasi merupakan titik gugur yang paling sering terjadi.</p>
      <p>Selain itu, modul dosen menggarisbawahi tiga prasyarat budaya inovasi dalam organisasi, yaitu pembiasaan berinovasi (<em>culture of innovation</em>), kesediaan saling mendengar dan berkomunikasi (<em>communicate with each other</em>), serta konsistensi tindakan berupa komitmen pada hasil (<em>consistency in action</em>). Ketiga prasyarat tersebut sejalan dengan temuan Hamel (2007) bahwa inovasi manajemen menuntut organisasi membangun kebiasaan bereksperimen dan menoleransi kegagalan yang terkendali. Oleh karena itu, pembangunan lingkungan teknologi internal perusahaan menuntut kepemimpinan yang menyediakan ruang eksperimen, saluran komunikasi lintas fungsi, dan disiplin eksekusi.</p>
      <h5>7.2.2 Inovasi Terbuka versus Tertutup</h5>
      <p>Strategi inovasi dapat dibedakan menjadi inovasi tertutup dan inovasi terbuka. Pada model tertutup, seluruh kegiatan riset, pengembangan, dan komersialisasi dilakukan di dalam batas perusahaan dengan asumsi bahwa pengetahuan terbaik harus dimiliki secara eksklusif. Menurut Chesbrough (2003), inovasi terbuka adalah penggunaan aliran pengetahuan ke dalam dan ke luar organisasi secara sengaja untuk mempercepat inovasi internal dan memperluas pasar bagi pemanfaatan inovasi secara eksternal. Perusahaan yang menganut inovasi terbuka bersedia membeli lisensi teknologi pihak lain, menggandeng perguruan tinggi, serta melepas teknologi yang tidak terpakai melalui lisensi keluar. Di sisi lain, model tertutup masih relevan pada industri yang sangat sensitif terhadap kebocoran rahasia dagang. Pilihan antara keduanya merupakan keputusan strategis yang bergantung pada kecepatan perubahan teknologi, sebaran pengetahuan di luar perusahaan, dan kekuatan rezim perlindungan kekayaan intelektual.</p>
      <h5>7.2.3 Ekosistem Inovasi dan Empat Pendekatan Lingkungan Teknologi</h5>
      <p>Lingkungan teknologi terbentuk melalui interaksi banyak aktor. Model <em>triple helix</em> dari Etzkowitz dan Leydesdorff (2000) menggambarkan sinergi antara akademisi, industri, dan pemerintah, yang kemudian diperluas menjadi <em>quadruple helix</em> dengan menambahkan masyarakat sebagai aktor keempat (Carayannis dan Campbell, 2009). Modul dosen pengampu merinci empat pendekatan lingkungan teknologi yang bersesuaian dengan model tersebut, yaitu: produk inovatif yang bersumber dari riset akademik (<em>academic driven</em>); produk inovatif hasil kolaborasi mitra strategis untuk memenuhi kebutuhan industri (<em>industry driven</em>); produk inovatif melalui pengembangan usaha dan pemberdayaan komunitas (<em>community based driven</em>); serta produk inovatif yang didorong kebijakan pemerintah (<em>policy based driven</em>).</p>
      <p>Contoh nyata pendekatan akademik di Indonesia adalah GeNose C19, alat penapisan Covid-19 berbasis embusan napas yang dikembangkan Universitas Gadjah Mada dan dihilirkan melalui mitra industri pada masa pandemi. Contoh pendekatan berbasis kebijakan tampak pada program hilirisasi mineral yang mendorong tumbuhnya industri pengolahan nikel untuk baterai kendaraan listrik. Dengan demikian, manajer perlu memetakan pada pendekatan mana perusahaan berada dan aktor helix mana yang paling strategis untuk digandeng, karena akses terhadap sumber teknologi eksternal semakin menjadi penentu daya saing.</p>`
    },
    {
      no: "7.3",
      title: "Tren dan Kemajuan Teknologi",
      body: `<p>Kemajuan teknologi tidak berlangsung secara linier, melainkan mengikuti pola yang dapat dianalisis. Pemahaman atas pola tersebut membantu manajer memutuskan kapan mengadopsi, kapan menunggu, dan kapan beralih ke teknologi generasi berikutnya. Bagian ini membahas kurva S teknologi, tingkat kesiapterapan teknologi, serta tren besar yang membentuk lanskap bisnis kontemporer.</p>
      <h5>7.3.1 Kurva S dan Siklus Hidup Teknologi</h5>
      <p>Menurut Foster (1986), kinerja suatu teknologi bila dipetakan terhadap akumulasi upaya riset akan membentuk kurva S: pada tahap awal kemajuan berjalan lambat karena pengetahuan dasar belum matang, kemudian memasuki fase percepatan ketika prinsip kunci telah dikuasai, dan akhirnya melandai ketika teknologi mendekati batas fisiknya. Ketika sebuah teknologi memasuki fase pelandaian, teknologi penantang yang masih berada pada tahap awal kurva S baru berpotensi melampauinya, sebagaimana lampu LED melampaui lampu pijar dan penyimpanan awan menggantikan pusat data lokal. Sejalan dengan itu, Rogers (2003) menjelaskan bahwa difusi inovasi menyebar mengikuti kategori adopter mulai dari <em>innovators</em>, <em>early adopters</em>, <em>early majority</em>, <em>late majority</em>, hingga <em>laggards</em>. Implikasi manajerialnya, perusahaan harus memantau sinyal pelandaian teknologi inti dan menyiapkan lompatan ke kurva baru sebelum pesaing melakukannya, sekaligus menyesuaikan strategi pemasaran dengan kategori adopter yang sedang dibidik.</p>
      <h5>7.3.2 Tingkat Kesiapterapan Teknologi</h5>
      <p>Untuk menilai kematangan sebuah teknologi sebelum diinvestasikan, dunia industri dan lembaga riset menggunakan kerangka <em>Technology Readiness Level</em> (TRL) yang mula-mula dikembangkan NASA (Mankins, 1995). Kerangka ini membagi perjalanan teknologi dari prinsip dasar hingga operasi komersial ke dalam sembilan tingkat, sebagaimana disintesiskan pada Tabel 7.1. Modul dosen pengampu menempatkan TRL 1 sampai 4 sebagai ranah perguruan tinggi dan TRL 7 sampai 9 sebagai ranah bisnis, sehingga wilayah TRL 4 sampai 7 sering disebut lembah kematian (<em>valley of death</em>) karena pendanaan riset akademik telah berhenti sementara investor komersial belum bersedia masuk. Cara menggunakan kerangka ini cukup langsung: manajer menilai bukti yang tersedia atas suatu teknologi, menetapkan tingkat TRL saat ini, lalu menghitung kebutuhan dana, waktu, dan mitra untuk menaikkan tingkat tersebut hingga layak dipasarkan.</p>
      <table class="bk-table"><caption>Tabel 7.1 Tingkat Kesiapterapan Teknologi dan Implikasi Manajerial</caption>
      <thead><tr><th>Tingkat</th><th>Deskripsi Ringkas</th><th>Aktor Dominan</th><th>Fokus Keputusan</th></tr></thead>
      <tbody>
      <tr><td>TRL 1-2</td><td>Prinsip dasar diamati; konsep teknologi dirumuskan</td><td>Perguruan tinggi, lembaga riset</td><td>Pendanaan riset dasar dan publikasi</td></tr>
      <tr><td>TRL 3-4</td><td>Pembuktian konsep dan validasi di laboratorium</td><td>Perguruan tinggi dan mitra awal</td><td>Perlindungan kekayaan intelektual</td></tr>
      <tr><td>TRL 5-6</td><td>Validasi dan demonstrasi prototipe pada lingkungan relevan</td><td>Konsorsium riset-industri</td><td>Pendanaan penjembatan, uji pasar awal</td></tr>
      <tr><td>TRL 7-8</td><td>Demonstrasi pada lingkungan operasional dan kualifikasi sistem</td><td>Industri, investor</td><td>Skala produksi, sertifikasi, regulasi</td></tr>
      <tr><td>TRL 9</td><td>Teknologi terbukti melalui operasi komersial</td><td>Industri</td><td>Efisiensi, perluasan pasar</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Mankins (1995) dan modul GBE Pak Wirawan (2025)</td></tr></tfoot></table>
      <h5>7.3.3 Tren Besar Teknologi Kontemporer</h5>
      <p>Schwab (2016) menyebut gelombang perubahan saat ini sebagai Revolusi Industri Keempat, yaitu perpaduan teknologi yang mengaburkan batas antara ranah fisik, digital, dan biologis. Tren yang menonjol mencakup kecerdasan buatan dan analitik data raksasa, <em>internet of things</em> yang menghubungkan mesin dan sensor, komputasi awan yang mengubah belanja modal menjadi belanja operasional, manufaktur aditif atau pencetakan tiga dimensi, bioteknologi dan rekayasa genetika, serta teknologi energi terbarukan dan penyimpanan energi. Selain itu, konektivitas pita lebar bergerak menjadikan telepon pintar sebagai kanal utama transaksi ekonomi digital. Menurut Brynjolfsson dan McAfee (2014), teknologi digital bersifat eksponensial, digital, dan kombinatorial, sehingga kemajuan pada satu bidang saling menguatkan dengan bidang lain dan menghasilkan percepatan yang sulit diantisipasi oleh perencanaan linier.</p>
      <p>Bagi Indonesia, tren tersebut termanifestasi dalam pertumbuhan ekonomi digital yang ditopang dompet elektronik, perdagangan elektronik, dan layanan pesan antar berbasis aplikasi. Pemerintah turut membentuk lingkungan teknologi melalui peta jalan Making Indonesia 4.0 yang memprioritaskan lima sektor manufaktur untuk transformasi digital. Oleh karena itu, analisis lingkungan teknologi dalam kerangka PESTLE perlu memberi bobot pada arah kebijakan nasional, kesiapan infrastruktur digital, dan ketersediaan talenta, bukan semata pada kecanggihan teknologinya.</p>`
    },
    {
      no: "7.4",
      title: "Disrupsi Digital dan Respons Strategis Perusahaan",
      body: `<p>Disrupsi digital merupakan fenomena ketika model bisnis berbasis teknologi digital menggeser model bisnis lama secara cepat dan mendasar. Fenomena ini penting dipahami manajer karena perusahaan yang gagal membaca sinyal disrupsi dapat kehilangan pasar dalam waktu singkat meskipun sebelumnya menjadi pemimpin industri, sebagaimana dialami Kodak pada fotografi film dan Nokia pada telepon seluler.</p>
      <h5>7.4.1 Teori Inovasi Disruptif</h5>
      <p>Menurut Christensen (1997), inovasi disruptif adalah inovasi yang pada awalnya menawarkan kinerja lebih rendah menurut ukuran arus utama, tetapi membawa atribut baru seperti harga murah, kesederhanaan, dan kemudahan akses sehingga diterima oleh segmen bawah pasar atau non-konsumen. Christensen membedakannya dengan inovasi berkelanjutan (<em>sustaining innovation</em>) yang memperbaiki kinerja produk pada dimensi yang dihargai pelanggan utama. Mekanisme disrupsi berlangsung bertahap: pendatang masuk dari segmen yang diabaikan, memperbaiki kualitas mengikuti lintasan kemajuan teknologinya, kemudian merangsek ke segmen utama ketika kinerjanya telah mencukupi, sementara petahana terlambat merespons karena struktur biaya dan pelanggan terbaiknya justru menahan mereka pada model lama. "Disruptive technologies typically enable new markets to emerge" (Christensen, 1997). Dengan demikian, kegagalan petahana sering bukan akibat manajemen yang buruk, melainkan akibat logika alokasi sumber daya yang rasional pada masanya.</p>
      <h5>7.4.2 Ekonomi Platform dan Transformasi Digital</h5>
      <p>Bentuk disrupsi yang paling menonjol dewasa ini adalah model bisnis platform yang mempertemukan dua sisi pasar atau lebih dan tumbuh melalui efek jaringan (<em>network effects</em>), yaitu kondisi ketika nilai layanan meningkat seiring bertambahnya pengguna. Efek jaringan menghasilkan dinamika pemenang mengambil sebagian besar pasar, sehingga persaingan platform menekankan kecepatan penguasaan pengguna. Di Indonesia, Gojek berawal dari layanan panggilan ojek sederhana dan berkembang menjadi platform super yang mendisrupsi transportasi, logistik kurir, dan pembayaran tunai, sementara Tokopedia dan Shopee menggeser sebagian peran ritel fisik, serta bank digital dan teknologi finansial menantang model perbankan cabang. Contoh tersebut menunjukkan bahwa disrupsi tidak hanya mengganti produk, melainkan mengganti arsitektur industri dan titik penangkapan nilai.</p>
      <p>Bagi perusahaan mapan, jawaban atas disrupsi adalah transformasi digital, yaitu perubahan menyeluruh atas proses, model bisnis, dan budaya organisasi dengan memanfaatkan teknologi digital, bukan sekadar otomatisasi proses lama. Respons strategis yang lazim direkomendasikan literatur mencakup beberapa pilihan sebagai berikut: membentuk unit otonom yang bebas dari logika bisnis inti untuk menggarap pasar disruptif; mengakuisisi atau bermitra dengan perusahaan rintisan; membangun kapabilitas data dan talenta digital secara internal; serta mengubah proposisi nilai dari penjualan produk menjadi layanan berlangganan. Namun, transformasi digital menuntut komitmen pimpinan puncak karena hambatan terbesarnya bersifat kultural dan struktural, bukan teknis. Oleh karena itu, manajer perlu menilai secara berkala apakah model bisnis perusahaan masih selaras dengan perilaku konsumen yang telah berpindah ke kanal digital.</p>`
    },
    {
      no: "7.5",
      title: "Kecerdasan Buatan dalam Lingkungan Bisnis",
      body: `<p>Kecerdasan buatan atau <em>artificial intelligence</em> (AI) merupakan tren teknologi yang paling banyak mengubah lingkungan bisnis dalam satu dekade terakhir dan diperlakukan banyak ekonom sebagai teknologi berdaya guna umum (<em>general purpose technology</em>) setara mesin uap dan listrik. Menurut Russell dan Norvig (2021), kecerdasan buatan adalah kajian tentang agen yang menerima persepsi dari lingkungan dan melakukan tindakan secara rasional untuk mencapai tujuan. Sementara itu, dalam praktik bisnis AI sering dimaknai sebagai kemampuan sistem komputer menjalankan tugas yang lazimnya menuntut kecerdasan manusia, seperti mengenali pola, memahami bahasa, dan mengambil keputusan. Dari definisi tersebut dapat disimpulkan bahwa inti AI adalah otomatisasi fungsi kognitif, sehingga dampaknya menjangkau pekerjaan pengetahuan yang sebelumnya dianggap kebal terhadap mesin.</p>
      <h5>7.5.1 Taksonomi dan Perkembangan Teknologi AI</h5>
      <p>Teknologi AI modern ditopang oleh pembelajaran mesin (<em>machine learning</em>), yaitu pendekatan yang membangun model prediktif dari data alih-alih dari aturan yang diprogram secara eksplisit. Cabang pembelajaran mendalam (<em>deep learning</em>) menggunakan jaringan saraf berlapis dan melejit sejak ketersediaan data raksasa serta komputasi grafis murah. Perkembangan mutakhir adalah AI generatif berbasis model bahasa besar yang mampu menghasilkan teks, gambar, kode program, dan analisis dalam bahasa alami, sehingga menurunkan hambatan pemakaian AI bagi pengguna awam. Davenport dan Ronanki (2018) mengelompokkan penerapan AI di perusahaan ke dalam tiga kategori, yaitu otomatisasi proses, wawasan kognitif melalui analisis data, dan keterlibatan kognitif melalui agen percakapan. Ketiga kategori tersebut membantu manajer memilah inisiatif AI berdasarkan nilai bisnis, bukan berdasarkan kecanggihan teknologinya.</p>
      <h5>7.5.2 Penerapan Bisnis dan Contoh Indonesia</h5>
      <p>Dalam fungsi pemasaran, AI digunakan untuk segmentasi mikro, rekomendasi produk, dan penetapan harga dinamis. Dalam operasi, AI menopang peramalan permintaan, pemeliharaan prediktif mesin, dan pengendalian mutu berbasis citra. Dalam keuangan, AI dipakai untuk penilaian kredit dan deteksi kecurangan transaksi. Di Indonesia, perusahaan teknologi finansial memanfaatkan penilaian kredit alternatif berbasis jejak digital untuk menjangkau masyarakat yang belum tersentuh bank, sementara platform dagang elektronik menggunakan mesin rekomendasi untuk menaikkan nilai keranjang belanja, dan perbankan memanfaatkan asisten virtual berbahasa Indonesia untuk layanan nasabah. Contoh tersebut menunjukkan bahwa nilai AI muncul ketika dipadukan dengan data khas perusahaan dan proses yang didesain ulang, bukan ketika dibeli sebagai perangkat semata.</p>
      <h5>7.5.3 Implikasi Manajerial, Etika, dan Tata Kelola</h5>
      <p>Adopsi AI membawa persoalan manajerial yang serius. Pertama, kualitas keputusan AI bergantung pada kualitas data, sehingga bias historis dalam data dapat menghasilkan diskriminasi algoritmik dalam rekrutmen atau kredit. Kedua, otomatisasi kognitif menggeser komposisi pekerjaan sehingga perusahaan perlu merencanakan peningkatan keterampilan (<em>upskilling</em>) dan alih keterampilan (<em>reskilling</em>) karyawan. Ketiga, model generatif dapat menghasilkan keluaran yang keliru namun meyakinkan, sehingga diperlukan mekanisme manusia sebagai pengawas (<em>human in the loop</em>) pada keputusan berisiko tinggi. Keempat, regulasi berkembang cepat, termasuk regulasi pelindungan data pribadi di Indonesia melalui Undang-Undang Nomor 27 Tahun 2022 yang membatasi cara perusahaan mengumpulkan dan mengolah data. Oleh karena itu, tata kelola AI yang mencakup kebijakan data, audit algoritma, dan kejelasan akuntabilitas merupakan bagian tidak terpisahkan dari strategi teknologi perusahaan, dan manajer non-teknis tetap bertanggung jawab atas keputusan yang didelegasikan kepada mesin.</p>`
    },
    {
      no: "7.6",
      title: "Implikasi terhadap Pengembangan Produk, Proses, dan Komersialisasi Teknologi",
      body: `<p>Analisis lingkungan teknologi pada akhirnya harus diterjemahkan menjadi keputusan internal perusahaan, terutama pada pengembangan produk, desain proses, dan strategi komersialisasi. Bagian ini membahas keterkaitan teknologi dengan prioritas kompetitif, tiga wilayah aplikasi teknologi, serta jalur hilirisasi teknologi baru ke pasar.</p>
      <h5>7.6.1 Teknologi dan Prioritas Kompetitif</h5>
      <p>Modul dosen pengampu menegaskan bahwa teknologi harus mendukung prioritas kompetitif perusahaan, yaitu pilihan bersaing pada biaya, kualitas, waktu, atau fleksibilitas (Heizer, Render dan Munson, 2017). Bersaing pada biaya berarti menawarkan produk dengan harga relatif rendah, biasanya pada volume tinggi dengan variasi terbatas, dan sering ditopang otomatisasi untuk menekan biaya per unit; biaya rendah tidak berarti kualitas rendah. Bersaing pada kualitas mencakup dua dimensi, yaitu desain berkinerja tinggi dengan fitur unggul serta konsistensi produk dan jasa yang memenuhi spesifikasi. Bersaing pada waktu menekankan pengiriman cepat dan pengiriman tepat waktu, karena pihak yang mampu menyerahkan lebih dahulu sering memenangkan persaingan. Bersaing pada fleksibilitas mencakup fleksibilitas produk untuk berganti item dan menyesuaikan pesanan khusus serta fleksibilitas volume untuk menaikturunkan produksi mengikuti permintaan. Keputusan teknologi yang tidak selaras dengan prioritas tersebut berisiko menjadi investasi mahal tanpa keunggulan, karena teknologi memiliki potensi positif berupa perbaikan proses dan keunggulan bersaing, sekaligus potensi negatif berupa biaya besar dan manfaat yang dilebih-lebihkan.</p>
      <h5>7.6.2 Teknologi Produk, Proses, dan Informasi</h5>
      <p>Aplikasi teknologi dalam perusahaan dapat dikelompokkan menjadi tiga wilayah. Teknologi produk melekat pada barang atau jasa yang dijual, misalnya material baru, serat optik, atau fitur perangkat lunak dalam kendaraan. Teknologi proses melekat pada cara produksi, misalnya otomatisasi fleksibel, robotika, dan desain berbantuan komputer. Teknologi informasi melekat pada pengelolaan data dan koordinasi, misalnya sistem titik penjualan, pertukaran data elektronik, dan <em>enterprise resource planning</em>. Menurut Porter dan Heppelmann (2014), produk pintar yang terhubung mengaburkan batas ketiganya karena produk kini mengandung sensor dan perangkat lunak yang mengirim data pemakaian kembali ke pabrikan, sehingga membuka model pendapatan berbasis layanan. Implikasinya bagi pengembangan produk, siklus pengembangan menjadi lebih pendek dan bersifat iteratif, kolaborasi lintas fungsi antara teknik, pemasaran, dan teknologi informasi menjadi keharusan, serta keputusan desain harus mempertimbangkan pembaruan berkelanjutan pascapenjualan. Implikasinya bagi proses, digitalisasi memungkinkan kustomisasi massal (<em>mass customization</em>), yaitu kemampuan melayani pesanan spesifik pelanggan dengan biaya mendekati produksi massal.</p>
      <h5>7.6.3 Komersialisasi Teknologi dan Kekayaan Intelektual</h5>
      <p>Teknologi baru hanya bernilai bila berhasil mencapai pasar, dan perjalanan tersebut dimulai dari penetapan kebutuhan yang belum terpenuhi (<em>unmet need</em>). Modul dosen pengampu menganjurkan empat langkah menemukan pelanggan, yaitu menetapkan teknologi yang akan dikomersialkan, mengidentifikasi praktik yang menjadi aplikasi potensial, menentukan pengguna akhir dalam praktik tersebut, dan menentukan pihak yang akan membayar. Kelayakan proyek dinilai dari daya tarik pasar yang besar dan bertumbuh, kebutuhan pengembangan lanjutan, dukungan inventor, serta kekuatan dan keluasan paten. Perlindungan kekayaan intelektual, terutama paten, menjadi penentu daya tawar karena memberi hak eksklusif yang dapat dilisensikan atau dijadikan basis usaha baru.</p>
      <p>Terdapat dua jalur utama komersialisasi teknologi hasil riset, yaitu lisensi kepada perusahaan yang sudah mapan atau pendirian perusahaan pemisahan (<em>spin-out</em>). Perbandingan kedua jalur disintesiskan pada Tabel 7.2. Secara umum, lisensi cocok untuk teknologi dengan aplikasi tunggal pada pasar yang telah mapan dan bersifat penyempurnaan bertahap, sedangkan <em>spin-out</em> cocok untuk teknologi platform dengan banyak aplikasi, pasar baru berpotensi tumbuh tinggi, dan karakter disruptif. Dengan demikian, pilihan jalur bukan soal mana yang terbaik secara mutlak, melainkan soal kesesuaian antara sifat teknologi, kondisi pasar, dan ketersediaan pendana.</p>
      <table class="bk-table"><caption>Tabel 7.2 Perbandingan Jalur Komersialisasi Lisensi dan Spin-out</caption>
      <thead><tr><th>Aspek</th><th>Lisensi</th><th>Spin-out</th></tr></thead>
      <tbody>
      <tr><td>Kompleksitas transaksi</td><td>Satu perjanjian, aktor sedikit</td><td>Banyak perjanjian, aktor banyak</td></tr>
      <tr><td>Horizon imbal hasil</td><td>Lebih cepat, nilai dibagi dengan pemegang lisensi</td><td>Lebih lama, nilai lebih besar tertahan di pendiri</td></tr>
      <tr><td>Komitmen dan kendali</td><td>Komitmen penerima lisensi dapat rendah, ruang gerak dibatasi kebijakan mitra</td><td>Komitmen tinggi, kebebasan komersial luas</td></tr>
      <tr><td>Profil teknologi yang cocok</td><td>Aplikasi tunggal, pasar mapan, perbaikan inkremental</td><td>Teknologi platform, pasar baru, karakter disruptif</td></tr>
      <tr><td>Prasyarat pendukung</td><td>Ada calon penerima lisensi yang berminat</td><td>Ada investor dan tim manajemen yang bersedia</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari modul GBE Pak Wirawan (2025)</td></tr></tfoot></table>
      <p>Dalam konteks Indonesia, jalur hilirisasi semacam ini dijalankan antara lain melalui taman sains dan teknologi perguruan tinggi serta kantor pengelolaan kekayaan intelektual, seperti UGM Science Techno Park yang menginkubasi perusahaan rintisan berbasis riset. Bagi manajer korporasi, kerangka yang sama berlaku terbalik: perusahaan dapat memindai teknologi kampus pada TRL menengah, mengambil lisensi, lalu menuntaskan pengembangan hingga skala komersial sebagai wujud inovasi terbuka. Selain itu, evaluasi pasar bagi teknologi baru sebaiknya dilakukan secara terstruktur dengan memadukan analisis PESTLE untuk pendorong lingkungan makro, lima kekuatan Porter untuk struktur industri, analisis pesaing dan pemangku kepentingan, serta analisis SWOT untuk posisi kompetitif, dengan setiap faktor diberi bobot dan arah dampak agar keputusan tidak semata mengandalkan intuisi.</p>`
    },
    {
      no: "7.7",
      title: "Rangkuman",
      body: `<p>Lingkungan teknologi merupakan dimensi eksternal yang paling cepat berubah dan menentukan kelangsungan bisnis pada pasar global yang kompetitif. Nilai bisnis lahir dari rantai kreasi, invensi, dan inovasi yang hanya tuntas apabila temuan diadopsi pasar, dan rantai tersebut kini semakin sering dikerjakan lintas organisasi melalui inovasi terbuka serta kolaborasi <em>quadruple helix</em> antara akademisi, industri, pemerintah, dan masyarakat. Kerangka kurva S dan <em>Technology Readiness Level</em> membantu manajer menilai arah dan kematangan teknologi, sementara tren Revolusi Industri Keempat menunjukkan perpaduan teknologi digital, fisik, dan biologis yang bergerak eksponensial.</p>
      <p>Disrupsi digital berlangsung ketika pendatang membawa proposisi murah dan sederhana dari segmen yang diabaikan, kemudian merangsek ke pasar utama, sering diperkuat efek jaringan model platform sebagaimana ditunjukkan Gojek dan platform dagang elektronik di Indonesia. Kecerdasan buatan memperluas otomatisasi ke ranah kognitif melalui pembelajaran mesin dan AI generatif, memberi peluang efisiensi dan personalisasi sekaligus menuntut tata kelola data, mitigasi bias, dan pengembangan ulang keterampilan karyawan.</p>
      <p>Pada tataran internal, teknologi harus dipilih untuk mendukung prioritas kompetitif biaya, kualitas, waktu, dan fleksibilitas, serta diterapkan pada wilayah produk, proses, dan informasi secara selaras. Teknologi baru mencapai pasar melalui jalur lisensi atau <em>spin-out</em> sesuai sifat teknologi dan kondisi pasar, dengan kekayaan intelektual sebagai penopang daya tawar. Dengan demikian, kompetensi membaca lingkungan teknologi dan menerjemahkannya menjadi keputusan investasi, organisasi, dan komersialisasi merupakan kecakapan manajerial inti yang dituntut dari lulusan program magister manajemen.</p>`
    },
    {
      no: "7.8",
      title: "Daftar Pustaka",
      body: `<p>Brynjolfsson, E. dan McAfee, A. (2014). <em>The Second Machine Age: Work, Progress, and Prosperity in a Time of Brilliant Technologies</em>. W. W. Norton.</p>
      <p>Carayannis, E. G. dan Campbell, D. F. J. (2009). "Mode 3" and "Quadruple Helix": Toward a 21st Century Fractal Innovation Ecosystem. <em>International Journal of Technology Management</em>, 46(3-4).</p>
      <p>Chesbrough, H. (2003). <em>Open Innovation: The New Imperative for Creating and Profiting from Technology</em>. Harvard Business School Press.</p>
      <p>Christensen, C. M. (1997). <em>The Innovator's Dilemma: When New Technologies Cause Great Firms to Fail</em>. Harvard Business School Press.</p>
      <p>Davenport, T. H. dan Ronanki, R. (2018). Artificial Intelligence for the Real World. <em>Harvard Business Review</em>, 96(1).</p>
      <p>Etzkowitz, H. dan Leydesdorff, L. (2000). The Dynamics of Innovation: From National Systems and Mode 2 to a Triple Helix of University-Industry-Government Relations. <em>Research Policy</em>, 29(2).</p>
      <p>Foster, R. N. (1986). <em>Innovation: The Attacker's Advantage</em>. Summit Books.</p>
      <p>Hamel, G. (2007). <em>The Future of Management</em>. Harvard Business School Press.</p>
      <p>Heizer, J., Render, B. dan Munson, C. (2017). <em>Operations Management: Sustainability and Supply Chain Management</em>. Edisi 12. Pearson.</p>
      <p>Khalil, T. M. (2000). <em>Management of Technology: The Key to Competitiveness and Wealth Creation</em>. McGraw-Hill.</p>
      <p>Mankins, J. C. (1995). <em>Technology Readiness Levels: A White Paper</em>. NASA Office of Space Access and Technology.</p>
      <p>Porter, M. E. dan Heppelmann, J. E. (2014). How Smart, Connected Products Are Transforming Competition. <em>Harvard Business Review</em>, 92(11).</p>
      <p>Rogers, E. M. (2003). <em>Diffusion of Innovations</em>. Edisi 5. Free Press.</p>
      <p>Russell, S. dan Norvig, P. (2021). <em>Artificial Intelligence: A Modern Approach</em>. Edisi 4. Pearson.</p>
      <p>Schilling, M. A. (2020). <em>Strategic Management of Technological Innovation</em>. Edisi 6. McGraw-Hill Education.</p>
      <p>Schwab, K. (2016). <em>The Fourth Industrial Revolution</em>. World Economic Forum.</p>
      <p>Tidd, J. dan Bessant, J. (2021). <em>Managing Innovation: Integrating Technological, Market and Organizational Change</em>. Edisi 7. Wiley.</p>
      <p>Wirawan, S. K. (2025). <em>Modul General Business Environment: Technology and Innovation</em>. Program Magister Manajemen.</p>`
    }
  ]
};
