window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.gbe = window.MBA_BOOK.gbe || {};
window.MBA_BOOK.gbe[9] = {
  bab: 9,
  judul: "LINGKUNGAN ALAMI (NATURAL)",
  sumber: "Modul GBE: deck Pak Andhika (Google Drive) dan referensi akademik standar topik Lingkungan Alami (Natural)",
  lo: [
    "LO1 Menjelaskan konsep lingkungan alami, sumber daya alam, jasa ekosistem, dan daya dukung lingkungan sebagai fondasi analisis lingkungan bisnis.",
    "LO2 Menganalisis hubungan timbal balik antara aktivitas bisnis dan sistem ekologi dengan menggunakan kerangka keseimbangan material dan dekomposisi Holdren dan Ehrlich.",
    "LO3 Mengidentifikasi jenis polusi dan eksternalitas negatif yang ditimbulkan kegiatan usaha serta instrumen pengendaliannya.",
    "LO4 Mengevaluasi tekanan publik, konsumen, dan regulator terhadap perusahaan serta respons manajerial yang tepat.",
    "LO5 Menilai risiko dan peluang bisnis yang timbul dari perubahan iklim dan transisi hijau, termasuk dalam konteks kebijakan Indonesia."
  ],
  sections: [
    {
      no: "9.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membahas lingkungan alami (<em>natural environment</em>) sebagai salah satu dimensi lingkungan eksternal yang mempengaruhi keputusan bisnis global. Lingkungan alami bukan latar belakang yang pasif, melainkan sistem penyedia sumber daya dan jasa ekosistem yang menentukan kelangsungan operasi perusahaan dalam jangka panjang, sehingga pemahaman interaksi ekonomi dan ekologi menjadi prasyarat perumusan strategi yang berkelanjutan.</p>
<p>Capaian pembelajaran sesi ini mencakup lima kemampuan sebagaimana dirinci pada daftar LO bab, mulai dari penguasaan konsep lingkungan alami, analisis hubungan timbal balik bisnis dan ekologi, identifikasi polusi dan eksternalitas, evaluasi tekanan publik dan konsumen, hingga penilaian risiko dan peluang perubahan iklim serta transisi hijau.</p>`
    },
    {
      no: "9.2",
      title: "Konsep Dasar Lingkungan Alami dan Sumber Daya Alam",
      body: `<h5>3.2.1 Definisi Lingkungan Alami</h5>
<p>Istilah lingkungan merujuk pada kondisi dan faktor eksternal yang mempengaruhi kehidupan organisme atau sekelompok organisme. Faktor eksternal tersebut lazim dikelompokkan menjadi tiga, yaitu faktor fisik seperti air, tanah, dan udara, faktor biologis yang mencakup tumbuhan dan hewan dalam biosfer, serta faktor sosial yang meliputi sistem kultural dan politik. Menurut modul perkuliahan, lingkungan alami (<em>natural environment</em>) mencakup semua bentuk kehidupan dan benda tidak hidup yang muncul secara alami dan berfungsi sebagai unit ekologis lengkap tanpa campur tangan manusia, meliputi vegetasi, hewan, mikroorganisme, batuan, atmosfer, serta fenomena alam. Konsep tersebut dibedakan dari lingkungan buatan (<em>built environment</em>) yang merujuk pada kawasan dan komponen yang dibentuk oleh aktivitas manusia, seperti kota, kawasan industri, dan infrastruktur.</p>
<p>Dalam literatur lingkungan bisnis, Worthington dan Britton (2015) menempatkan lingkungan alami sebagai bagian dari lingkungan makro yang mencakup faktor geografis dan ekologis yang mempengaruhi operasi perusahaan, antara lain ketersediaan sumber daya alam, kondisi cuaca dan iklim, aspek lokasi, dan faktor topografi. Dari berbagai pengertian tersebut dapat disimpulkan bahwa lingkungan alami merupakan keseluruhan sistem ekologis penyedia sumber daya dan jasa kehidupan yang menjadi basis material bagi seluruh aktivitas ekonomi. Oleh karena itu, keputusan bisnis, mulai dari pemilihan lokasi pabrik hingga desain produk, tidak dapat dilepaskan dari karakteristik lingkungan alami; pabrik gula, misalnya, didirikan di dekat sentra perkebunan tebu karena kedekatan bahan baku menurunkan biaya logistik dan menjaga mutu input.</p>
<h5>3.2.2 Sumber Daya Alam dalam Perspektif Ekonomi</h5>
<p>Dalam ilmu ekonomi, sumber daya alam dikelompokkan ke dalam faktor produksi tanah (<em>land</em>) yang mencakup tanah itu sendiri, mineral, minyak bumi, hutan, ikan, air, dan energi matahari. Pasokan faktor tanah tidak sepenuhnya tetap karena produktivitasnya masih dapat ditingkatkan, misalnya produktivitas lahan pertanian dapat dinaikkan melalui penggunaan pupuk dan teknologi budidaya. Pembedaan yang paling penting dalam perspektif ini adalah antara sumber daya terbarukan (<em>renewable resources</em>) dan sumber daya tidak terbarukan (<em>non-renewable resources</em>). Lahan pertanian dapat ditanami secara berulang dari musim ke musim, sedangkan minyak bumi yang telah dikonsumsi tidak dapat digunakan kembali. Menurut Tietenberg dan Lewis (2018), sumber daya terbarukan dikelola agar laju pemanenan tidak melampaui laju regenerasi, sedangkan sumber daya tidak terbarukan dikelola dengan memperhitungkan kelangkaan antargenerasi dan pengembangan substitusinya.</p>
<p>Meningkatnya pengetahuan mengenai dampak penipisan sumber daya alam telah mendorong kesadaran lingkungan masyarakat, yang tercermin pada minat terhadap konservasi, daur ulang, dan energi alternatif. Dengan demikian, manajer perlu memandang sumber daya alam bukan sekadar input produksi yang murah, melainkan sebagai modal alam (<em>natural capital</em>) yang kelangkaannya semakin diperhitungkan oleh pasar, regulator, dan lembaga keuangan.</p>
<h5>3.2.3 Jasa Ekosistem dan Nilai Ekonomi Total</h5>
<p>Jasa ekosistem (<em>ecosystem services</em>) adalah manfaat yang diberikan lingkungan alami bagi manusia. Daily (1997) mendefinisikan jasa ekosistem sebagai kondisi dan proses yang melaluinya ekosistem alami beserta spesies di dalamnya menopang dan memenuhi kehidupan manusia. Berdasarkan kerangka <em>Millennium Ecosystem Assessment</em> (2005), jasa ekosistem dikelompokkan menjadi empat kategori, yaitu jasa penyediaan (<em>provisioning</em>) seperti pangan, kayu, dan air bersih, jasa pengaturan (<em>regulating</em>) seperti pengendalian iklim dan banjir, jasa kultural (<em>cultural</em>) seperti rekreasi, kesehatan, dan pariwisata, serta jasa pendukung (<em>supporting</em>) seperti pembentukan tanah dan siklus air. Kontak dengan alam juga memberikan manfaat kesehatan fisik dan mental yang nyata bagi masyarakat.</p>
<p>Untuk keperluan pengambilan keputusan, manfaat ekosistem dinilai dengan kerangka nilai ekonomi total (<em>total economic value</em>). Nilai ekonomi total terdiri atas nilai guna (<em>use value</em>) dan nilai non-guna (<em>non-use value</em>). Nilai guna mencakup nilai guna langsung dari pemanfaatan produk keanekaragaman hayati seperti kayu, ikan, dan tanaman, termasuk manfaat non-konsumtif seperti ekowisata, kemudian nilai guna tidak langsung berupa jasa ekosistem seperti perlindungan daerah aliran sungai, penyerapan karbon, dan penyaringan air, serta nilai opsi (<em>option value</em>) berupa kesediaan membayar untuk menjaga pilihan pemanfaatan pada masa depan. Nilai non-guna umumnya berupa nilai keberadaan (<em>existence value</em>), yaitu nilai yang tidak terkait dengan rencana pemanfaatan sumber daya. Studi Torras (2000) mengenai deforestasi Amazon Brasil memperkirakan nilai hutan hujan sekitar 1.175 dolar Amerika Serikat per hektare per tahun, dengan komponen terbesar berupa nilai guna langsung dan tidak langsung. Kerangka klasifikasi tersebut disintesiskan pada Tabel 3.1.</p>
<table class="bk-table"><caption>Tabel 3.1 Kerangka Nilai Ekonomi Total Keanekaragaman Hayati</caption>
<thead><tr><th>Komponen Nilai</th><th>Pengertian</th><th>Contoh</th></tr></thead>
<tbody>
<tr><td>Nilai guna langsung</td><td>Manfaat dari pemanfaatan produk ekosistem secara konsumtif maupun non-konsumtif</td><td>Kayu, ikan, hasil hutan bukan kayu, ekowisata</td></tr>
<tr><td>Nilai guna tidak langsung</td><td>Manfaat dari jasa ekosistem yang menopang aktivitas ekonomi</td><td>Perlindungan daerah aliran sungai, penyerapan karbon, penyaringan air</td></tr>
<tr><td>Nilai opsi</td><td>Kesediaan membayar untuk menjaga peluang pemanfaatan pada masa depan</td><td>Konservasi plasma nutfah untuk farmasi</td></tr>
<tr><td>Nilai keberadaan</td><td>Nilai yang tidak terkait pemanfaatan aktual maupun terencana</td><td>Kesediaan membayar untuk kelestarian orangutan</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari modul GBE Pak Andhika serta Daily (1997) dan Torras (2000)</td></tr></tfoot></table>
<h5>3.2.4 Daya Dukung Lingkungan</h5>
<p>Daya dukung lingkungan (<em>carrying capacity</em>) adalah kemampuan lingkungan untuk mendukung perikehidupan manusia dan makhluk hidup lainnya, atau jumlah populasi maksimum yang dapat ditopang oleh ketersediaan sumber daya dan jasa ekosistem tanpa menimbulkan kerusakan yang bersifat permanen. Batas daya dukung ekosistem ditentukan oleh tiga faktor, yaitu jumlah sumber daya alam yang tersedia, ukuran populasi, dan tingkat konsumsi sumber daya setiap individu dalam komunitas. Sebagai ilustrasi, daya dukung air suatu wilayah dianalisis dengan membandingkan pasokan (<em>supply</em>) dan kebutuhan (<em>demand</em>) air; apabila kebutuhan melampaui pasokan, daya dukung air dinyatakan terlampaui.</p>
<p>Konsep ini relevan secara manajerial karena pertumbuhan ekonomi mendorong aglomerasi penduduk yang meningkatkan kebutuhan ruang untuk permukiman, kegiatan usaha, dan infrastruktur. Apabila daya dukung terlampaui, wilayah tersebut menghadapi risiko banjir, longsor, penurunan muka tanah, dan intrusi air laut, sebagaimana dialami pesisir utara Jakarta akibat ekstraksi air tanah yang berlebihan. Oleh karena itu, analisis kelayakan investasi jangka panjang perlu memasukkan penilaian daya dukung lingkungan yang di Indonesia menjadi basis instrumen perencanaan seperti Kajian Lingkungan Hidup Strategis dan AMDAL.</p>`
    },
    {
      no: "9.3",
      title: "Hubungan Timbal Balik antara Bisnis dan Ekologi",
      body: `<h5>3.3.1 Bisnis dan Ekologi sebagai Sistem yang Saling Mempengaruhi</h5>
<p>Hubungan antara bisnis dan lingkungan alami bersifat timbal balik (<em>reciprocal relationship</em>). Pada satu arah, ekologi menyediakan input bagi bisnis berupa bahan baku, energi, air, dan jasa ekosistem, sekaligus menentukan pilihan lokasi dan pola operasi perusahaan. Pada arah sebaliknya, bisnis mengembalikan residu, limbah, dan emisi ke lingkungan, sehingga kualitas ekosistem dipengaruhi oleh skala dan teknologi produksi. Carroll dan Buchholtz (2015) mencatat bahwa selama bertahun-tahun perusahaan beroperasi dengan kepedulian yang rendah terhadap konsekuensi lingkungan dan memberi label dampak negatif tindakannya sebagai eksternalitas yang diabaikan; perusahaan baru berhenti merusak lingkungan ketika tindakan tersebut menjadi ilegal atau tidak menguntungkan.</p>
<p>Situasi tersebut kini berubah karena environmentalisme justru menjadi sumber keuntungan. Porter dan van der Linde (1995) berargumen bahwa regulasi lingkungan yang dirancang dengan baik dapat memicu inovasi yang mengimbangi biaya kepatuhan. Dengan demikian, lingkungan alami menghadirkan ancaman berupa kelangkaan sumber daya, bencana ekologis, dan pengetatan regulasi, sekaligus peluang berupa pasar produk hijau, efisiensi sumber daya, dan diferensiasi berbasis keberlanjutan.</p>
<h5>3.3.2 Kerangka Keseimbangan Material</h5>
<p>Hubungan ekonomi dan lingkungan dapat dianalisis melalui kerangka keseimbangan material (<em>materials balance</em>) yang berakar pada hukum kekekalan massa. Dalam kerangka ini, lingkungan menyediakan jasa ekologis dan sumber daya alam sebagai input produksi serta kapasitas asimilatif untuk mengurai limbah dan meregenerasi sumber daya terbarukan. Prinsip keseimbangannya menyatakan bahwa jumlah material yang diambil dari lingkungan harus sama dengan massa residu yang dikembalikan ke lingkungan ditambah massa yang dikonversi menjadi energi dan investasi neto dalam barang modal serta barang tahan lama. Implikasinya, tidak ada aktivitas produksi yang benar-benar bebas limbah karena material yang tidak menjadi produk pada akhirnya menjadi residu yang ditampung lingkungan.</p>
<p>Bagi manajer operasi, kerangka ini menegaskan bahwa pengurangan limbah paling efektif dilakukan di hulu melalui desain produk dan proses, bukan sekadar pengolahan di ujung pipa (<em>end of pipe</em>). Pendekatan 3R dan ekonomi sirkular merupakan penerapan langsung logika keseimbangan material karena memperpanjang umur material dalam sistem ekonomi dan menekan residu yang kembali ke lingkungan.</p>
<h5>3.3.3 Dekomposisi Holdren dan Ehrlich</h5>
<p>Bentuk ringkas hubungan manusia dan lingkungan diberikan oleh dekomposisi Holdren dan Ehrlich (1974), yang dalam modul dituliskan sebagai ED = P x Y x I. Dalam persamaan tersebut ED adalah degradasi lingkungan agregat, P adalah jumlah populasi manusia, Y adalah output riil atau pendapatan per kapita, dan I adalah koefisien dampak lingkungan agregat per unit aktivitas ekonomi. Persamaan ini sejalan dengan identitas IPAT yang dikenal luas dalam literatur, yaitu <em>Impact = Population x Affluence x Technology</em> (Ehrlich dan Holdren, 1971). Cara menggunakannya adalah dengan menelusuri sumber perubahan degradasi lingkungan pada tiga pengungkitnya, yaitu perubahan jumlah penduduk, perubahan pendapatan per kapita, dan perubahan intensitas dampak per unit output.</p>
<p>Kerangka ini menjelaskan mengapa pertumbuhan ekonomi tanpa perubahan teknologi cenderung memperbesar tekanan lingkungan. Apabila P dan Y terus meningkat, satu-satunya jalan menurunkan ED adalah menurunkan I secara lebih cepat melalui inovasi teknologi bersih, efisiensi energi, dan perubahan pola konsumsi. Target penurunan intensitas emisi Indonesia, misalnya, menuntut penurunan I yang tajam karena populasi dan pendapatan per kapita diproyeksikan terus tumbuh, sehingga investasi perusahaan pada teknologi rendah karbon merupakan kontribusi langsung terhadap penurunan koefisien I.</p>
<h5>3.3.4 Keanekaragaman Hayati sebagai Modal Alam</h5>
<p>Keanekaragaman hayati (<em>biodiversity</em>), yaitu variasi bentuk kehidupan di dalam suatu ekosistem, merupakan indikator utama kesehatan ekosistem sekaligus bagian dari modal alam yang memberikan jasa bagi manusia. Carroll dan Buchholtz (2015) mengingatkan bahwa laju kepunahan saat ini diperkirakan seribu kali lebih tinggi daripada laju alami dan degradasi lahan mengancam penghidupan lebih dari satu miliar orang. Bagi dunia usaha, kehilangan keanekaragaman hayati berarti menyusutnya basis bahan baku, meningkatnya volatilitas pasokan pertanian dan perikanan, serta hilangnya nilai opsi bagi industri farmasi dan bioteknologi. Oleh karena itu, sejumlah perusahaan global kini mengadopsi kerangka pelaporan seperti <em>Taskforce on Nature-related Financial Disclosures</em> untuk mengukur ketergantungan dan dampak bisnisnya terhadap alam.</p>`
    },
    {
      no: "9.4",
      title: "Polusi dan Eksternalitas Lingkungan",
      body: `<h5>3.4.1 Eksternalitas sebagai Akar Masalah</h5>
<p>Polusi dalam perspektif ekonomi merupakan wujud eksternalitas negatif, yaitu dampak sampingan aktivitas produksi atau konsumsi yang ditanggung pihak ketiga tanpa kompensasi. Eksternalitas terjadi karena biaya sosial pencemaran tidak tercermin dalam harga pasar, sehingga barang yang produksinya mencemari cenderung diproduksi melebihi tingkat yang efisien secara sosial (Tietenberg dan Lewis, 2018). Kegagalan pasar inilah yang menjadi dasar intervensi pemerintah dalam pengendalian pencemaran. Dari sudut pandang manajerial, internalisasi biaya lingkungan sejak dini merupakan bentuk manajemen risiko, karena biaya yang hari ini bersifat eksternal dapat berubah menjadi biaya internal ketika regulasi diperketat.</p>
<h5>3.4.2 Jenis dan Karakteristik Polusi</h5>
<p>Berdasarkan medianya, polusi dikelompokkan menjadi pencemaran udara, pencemaran air, pencemaran tanah, dan pencemaran lintas media (<em>cross-media pollution</em>) ketika polutan berpindah dari satu media ke media lain, misalnya limbah cair yang mencemari tanah kemudian meresap ke air tanah. Berdasarkan sumbernya, pencemaran dibedakan menjadi pencemaran sumber titik (<em>point source</em>) yang berasal dari titik pembuangan yang teridentifikasi seperti cerobong pabrik, dan pencemaran sumber menyebar (<em>non-point source</em>) yang berasal dari banyak sumber tersebar seperti residu bahan kimia pertanian yang terbawa aliran permukaan. Pencemaran sumber menyebar jauh lebih sulit dikendalikan karena tanggung jawabnya sulit dilacak ke pelaku tertentu, sedangkan polutan akumulatif seperti logam berat dan plastik menimbulkan dampak yang menumpuk lintas waktu dan rantai makanan.</p>
<p>Konteks Indonesia memberikan contoh yang nyata. Sungai Citarum di Jawa Barat selama bertahun-tahun tercemar limbah industri tekstil dan limbah domestik, sehingga pemerintah menetapkan program Citarum Harum untuk memulihkan kualitas airnya. Selain itu, kebakaran hutan dan lahan gambut yang berulang menimbulkan polusi asap lintas batas yang mengganggu kesehatan publik dan hubungan diplomatik dengan negara tetangga. Kasus tersebut menunjukkan bahwa pencemaran bukan sekadar persoalan teknis produksi, melainkan persoalan strategi dan legitimasi sosial perusahaan.</p>
<h5>3.4.3 Instrumen Pengendalian Pencemaran</h5>
<p>Instrumen pengendalian pencemaran dapat dikelompokkan menjadi tiga, yaitu instrumen komando dan kendali (<em>command and control</em>) berupa baku mutu, perizinan, dan sanksi, instrumen berbasis pasar (<em>market-based instruments</em>) berupa pajak lingkungan, retribusi limbah, dan perdagangan izin emisi, serta instrumen sukarela dan informasional berupa sertifikasi, ekolabel, dan keterbukaan informasi kinerja lingkungan (Tietenberg dan Lewis, 2018). Di Indonesia, kerangka hukum utamanya adalah Undang-Undang Nomor 32 Tahun 2009 tentang Perlindungan dan Pengelolaan Lingkungan Hidup yang mengatur perencanaan, pemanfaatan, pengendalian, pemeliharaan, pengawasan, dan penegakan hukum lingkungan, sedangkan instrumen informasional yang khas adalah PROPER yang memeringkat kinerja lingkungan perusahaan dari peringkat emas hingga hitam dan mempublikasikannya kepada masyarakat.</p>
<p>Pada tingkat perusahaan, hierarki pengelolaan limbah terpadu (<em>integrated waste management</em>) menempatkan pencegahan di posisi tertinggi, diikuti <em>reduce</em>, <em>reuse</em>, <em>recycle</em>, pemulihan energi, dan pembuangan akhir sebagai pilihan terakhir. Dengan demikian, kepatuhan lingkungan sebaiknya tidak diperlakukan sebagai pusat biaya semata, karena program efisiensi material dan energi yang baik sering kali sekaligus menurunkan biaya produksi melalui praktik produksi bersih (<em>cleaner production</em>).</p>`
    },
    {
      no: "9.5",
      title: "Tekanan Publik dan Konsumen terhadap Bisnis",
      body: `<h5>3.5.1 Sumber Tekanan Pemangku Kepentingan</h5>
<p>Perhatian perusahaan terhadap lingkungan tidak tumbuh secara sukarela semata, melainkan didorong oleh tekanan berbagai pemangku kepentingan. Modul perkuliahan menggambarkan tekanan tersebut dalam beberapa arus, yaitu tuntutan publik atas perlindungan lingkungan yang diwujudkan melalui CSR dan pengembangan komunitas, tuntutan konsumen atas proses dan produk yang bersih serta penerapan 3R, persyaratan kompetitif berupa ekolabel, dan tuntutan internasional dalam perjanjian perdagangan yang menghendaki perlakuan setara dan kesempatan setara. Crane dan Matten (2019) menjelaskan bahwa legitimasi perusahaan bergantung pada kesesuaian perilakunya dengan nilai dan harapan masyarakat, sehingga pengabaian isu lingkungan dapat mengikis izin sosial untuk beroperasi (<em>social license to operate</em>). Selain itu, konektivitas digital memungkinkan pemangku kepentingan memantau upaya keberlanjutan secara cepat, sehingga reputasi dapat dibangun dan dihancurkan dalam waktu singkat (Carroll dan Buchholtz, 2015).</p>
<p>Pemerintah juga merupakan sumber tekanan yang utama karena berperan melindungi, mengenakan pajak, menata zona kawasan berbasis lingkungan alami, dan menjalankan kendali regulatif atas pemanfaatannya (Carroll dan Buchholtz, 2015), sehingga sektor bisnis memikul tanggung jawab tambahan seperti kewajiban AMDAL, rehabilitasi pascatambang, dan moratorium pembukaan hutan primer di Indonesia.</p>
<h5>3.5.2 Konsumen Hijau dan Ekolabel</h5>
<p>Tekanan konsumen mewujud dalam fenomena konsumerisme hijau (<em>green consumerism</em>), yaitu preferensi konsumen terhadap produk yang proses produksinya ramah lingkungan. Preferensi tersebut mendorong permintaan atas atribut seperti kandungan daur ulang, efisiensi energi, kemasan minimal, dan jejak karbon yang rendah. Ekolabel berfungsi sebagai mekanisme sinyal yang mengurangi asimetri informasi antara produsen dan konsumen, misalnya sertifikasi pengelolaan hutan lestari untuk produk kayu serta sertifikasi RSPO dan ISPO untuk produk sawit Indonesia. Namun, manajer perlu mewaspadai praktik <em>greenwashing</em>, yaitu klaim lingkungan yang berlebihan atau menyesatkan, karena berisiko menimbulkan sanksi regulator dan kehancuran reputasi; klaim hijau harus didukung data yang dapat diverifikasi dan sertifikasi pihak ketiga yang kredibel.</p>
<h5>3.5.3 Respons Manajerial: Sistem Manajemen Lingkungan dan CSR</h5>
<p>Respons perusahaan terhadap tekanan tersebut dilembagakan melalui sistem manajemen lingkungan (<em>environmental management system</em>), dengan ISO 14001 sebagai standar internasional yang paling luas diadopsi dan diselaraskan dengan Standar Nasional Indonesia. Standar ini menuntut perusahaan menetapkan kebijakan lingkungan, mengidentifikasi aspek dan dampak lingkungan, serta menjalankan siklus perbaikan berkelanjutan. Selain itu, perusahaan menjalankan tanggung jawab sosial yang di Indonesia diwajibkan bagi perseroan di bidang sumber daya alam berdasarkan Undang-Undang Nomor 40 Tahun 2007, dalam kerangka <em>triple bottom line</em> yang menuntut kinerja seimbang pada dimensi ekonomi, sosial, dan lingkungan (Elkington, 1997). Dengan demikian, respons yang efektif bukanlah reaksi terhadap setiap tekanan, melainkan integrasi pertimbangan lingkungan ke dalam strategi, rantai pasok, dan pengukuran kinerja secara sistematis.</p>`
    },
    {
      no: "9.6",
      title: "Perubahan Iklim dan Transisi Hijau",
      body: `<h5>3.6.1 Mekanisme dan Bukti Perubahan Iklim</h5>
<p>Perubahan iklim merupakan perubahan jangka panjang pola suhu dan cuaca bumi yang didorong oleh peningkatan konsentrasi gas rumah kaca akibat aktivitas manusia, terutama pembakaran bahan bakar fosil dan perubahan tata guna lahan. Aktivitas tersebut mengganggu siklus karbon alami antara atmosfer, biosfer, lautan, dan kerak bumi, karena karbon yang tersimpan jutaan tahun dalam bentuk fosil dilepaskan ke atmosfer dalam waktu singkat. IPCC (2023) menyimpulkan bahwa pemanasan sistem iklim disebabkan oleh aktivitas manusia dan suhu permukaan global telah meningkat sekitar 1,1 derajat Celsius di atas tingkat praindustri, dengan konsekuensi berupa kenaikan permukaan laut, cuaca ekstrem, gangguan pola hujan, dan tekanan terhadap ekosistem serta produksi pangan.</p>
<h5>3.6.2 Risiko Iklim bagi Bisnis</h5>
<p>Risiko iklim bagi perusahaan lazim dikelompokkan menjadi dua kategori mengikuti kerangka <em>Task Force on Climate-related Financial Disclosures</em> (TCFD, 2017). Pertama, risiko fisik (<em>physical risk</em>) yang mencakup risiko akut seperti banjir, badai, dan kekeringan, serta risiko kronis seperti kenaikan permukaan laut dan pergeseran zona iklim yang mengganggu aset, rantai pasok, dan produktivitas. Kedua, risiko transisi (<em>transition risk</em>) yang timbul dari proses peralihan menuju ekonomi rendah karbon, meliputi perubahan kebijakan dan regulasi, perubahan teknologi, pergeseran preferensi pasar, dan risiko reputasi. Aset padat karbon seperti pembangkit batu bara menghadapi risiko menjadi aset terdampar (<em>stranded assets</em>) apabila kebijakan iklim diperketat lebih cepat daripada umur ekonomis asetnya. Oleh karena itu, analisis skenario iklim semakin menjadi bagian baku dari manajemen risiko korporasi dan penilaian kredit perbankan (Carroll dan Buchholtz, 2015).</p>
<h5>3.6.3 Arsitektur Kebijakan Global dan Nasional</h5>
<p>Arsitektur kebijakan iklim global berpuncak pada Persetujuan Paris tahun 2015 yang menargetkan pembatasan kenaikan suhu jauh di bawah 2 derajat Celsius melalui kontribusi yang ditetapkan secara nasional (<em>Nationally Determined Contribution</em>). Indonesia menetapkan target penurunan emisi dalam <em>Enhanced NDC</em> sebesar 31,89 persen dengan upaya sendiri dan 43,20 persen dengan dukungan internasional pada tahun 2030, serta visi emisi nol bersih (<em>net zero emission</em>) pada tahun 2060 atau lebih cepat. Instrumen nasional yang relevan bagi bisnis antara lain nilai ekonomi karbon berdasarkan Peraturan Presiden Nomor 98 Tahun 2021, pajak karbon, bursa karbon IDXCarbon yang diluncurkan tahun 2023, serta kebijakan percepatan kendaraan listrik dan energi terbarukan. Bagi perusahaan, harga karbon dengan demikian secara bertahap masuk ke dalam struktur biaya, sehingga penganggaran modal perlu menggunakan harga karbon bayangan (<em>shadow carbon price</em>).</p>
<h5>3.6.4 Transisi Hijau sebagai Peluang Strategis</h5>
<p>Transisi hijau (<em>green transition</em>) adalah pergeseran struktural perekonomian menuju aktivitas rendah karbon dan efisien sumber daya. Konsep dasarnya adalah pembangunan berkelanjutan, yang didefinisikan WCED (1987) sebagai pembangunan yang memenuhi kebutuhan masa kini tanpa mengorbankan kemampuan generasi mendatang untuk memenuhi kebutuhannya sendiri. Elemen pembangunan berkelanjutan mencakup eksploitasi bahan baku yang minimal, pembaruan sumber daya, pemeliharaan jangka panjang, dan daur ulang melalui prinsip <em>reduce</em>, <em>reuse</em>, dan <em>recycle</em>, yang berlawanan dengan budaya industrial lama yang berciri perencanaan jangka pendek, pemeliharaan minimal, dan eksploitasi bahan baku yang maksimal. Peluang bisnisnya terbentang luas, antara lain energi terbarukan, kendaraan listrik, efisiensi energi, pertanian regeneratif, dan jasa berbasis alam. Konteks Indonesia memberikan contoh yang jelas, yaitu hilirisasi nikel untuk baterai kendaraan listrik dan potensi kredit karbon dari hutan hujan tropis serta ekosistem mangrove yang termasuk terluas di dunia. Sintesis risiko dan peluang iklim disajikan pada Tabel 3.2.</p>
<table class="bk-table"><caption>Tabel 3.2 Risiko dan Peluang Bisnis dalam Transisi Hijau</caption>
<thead><tr><th>Dimensi</th><th>Risiko</th><th>Peluang</th></tr></thead>
<tbody>
<tr><td>Fisik</td><td>Kerusakan aset dan gangguan rantai pasok akibat cuaca ekstrem</td><td>Jasa adaptasi iklim, asuransi parametrik, infrastruktur tahan iklim</td></tr>
<tr><td>Kebijakan</td><td>Pajak karbon, pengetatan baku mutu, aset terdampar</td><td>Insentif fiskal energi terbarukan, pasar karbon</td></tr>
<tr><td>Teknologi</td><td>Keusangan teknologi padat emisi</td><td>Energi surya, kendaraan listrik, efisiensi energi</td></tr>
<tr><td>Pasar dan reputasi</td><td>Pergeseran preferensi konsumen, tekanan investor</td><td>Diferensiasi produk hijau, akses pembiayaan berkelanjutan</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari TCFD (2017) serta Carroll dan Buchholtz (2015)</td></tr></tfoot></table>`
    },
    {
      no: "9.7",
      title: "Lingkungan Alami Indonesia dan Implikasi Manajerial",
      body: `<p>Indonesia memiliki karakteristik lingkungan alami yang luar biasa dan strategis bagi bisnis. Indonesia merupakan negara kepulauan terbesar di dunia dengan sekitar 17.508 pulau, garis pantai sekitar 81.000 kilometer, lebih dari 100 gunung berapi, serta wilayah laut yang jauh lebih luas daripada daratannya (Tandjung, 2012). Indonesia diperkirakan memiliki sampai sekitar 17 persen dari total spesies dunia, termasuk sekitar 10 persen spesies tumbuhan berbunga, 12 persen spesies mamalia, dan 25 persen spesies ikan dunia, dengan tingkat endemisme yang tinggi. Ekosistemnya membentang dari padang rumput alpin di Papua hingga hutan hujan, terumbu karang, dan mangrove, menjadi modal alam penopang sektor perikanan, kehutanan, pertanian, dan pariwisata bahari.</p>
<p>Namun, modal alam tersebut menghadapi tekanan berat dari deforestasi, konversi lahan, pencemaran, penangkapan ikan berlebih, dan perubahan iklim. Sebagai negara kepulauan, Indonesia sangat rentan terhadap kenaikan permukaan laut dan variabilitas iklim yang mengganggu produksi pangan. Di sisi lain, kepemilikan hutan tropis dan mangrove yang luas menempatkannya sebagai aktor kunci solusi iklim berbasis alam (<em>nature-based solutions</em>) yang bernilai ekonomi melalui mekanisme karbon.</p>
<p>Implikasi manajerialnya dapat dirangkum dalam tiga hal. Pertama, perusahaan perlu memetakan ketergantungan dan dampaknya terhadap ekosistem lokal sebagai bagian dari uji tuntas investasi, termasuk kepatuhan pada AMDAL dan tata ruang. Kedua, perusahaan perlu membangun kapabilitas kepatuhan dan pelaporan lingkungan melalui ISO 14001, PROPER, dan pelaporan keberlanjutan yang diwajibkan Otoritas Jasa Keuangan bagi emiten. Ketiga, manajer perlu membaca transisi hijau sebagai agenda strategis dengan mengevaluasi portofolio bisnis terhadap skenario harga karbon dan preferensi pasar yang berubah. Dengan demikian, keunggulan bersaing masa depan di Indonesia banyak ditentukan oleh kemampuan perusahaan mengelola hubungan timbal baliknya dengan lingkungan alami secara bertanggung jawab dan inovatif.</p>`
    },
    {
      no: "9.8",
      title: "Rangkuman",
      body: `<p>Lingkungan alami adalah keseluruhan sistem ekologis penyedia sumber daya dan jasa kehidupan yang menjadi basis material seluruh aktivitas ekonomi, dan dibedakan dari lingkungan buatan yang dibentuk manusia. Hubungan bisnis dan ekologi bersifat timbal balik; ekologi menyediakan input, jasa ekosistem, dan kapasitas asimilatif, sedangkan bisnis mengembalikan residu dan emisi yang mempengaruhi kualitas ekosistem. Kerangka keseimbangan material dan dekomposisi Holdren dan Ehrlich, ED = P x Y x I, menunjukkan bahwa degradasi lingkungan ditentukan oleh populasi, pendapatan per kapita, dan intensitas dampak per unit output, sedangkan konsep jasa ekosistem, nilai ekonomi total, dan daya dukung lingkungan menyediakan alat untuk menilai manfaat alam dan batas pemanfaatannya.</p>
<p>Polusi merupakan eksternalitas negatif yang timbul karena biaya sosial pencemaran tidak tercermin dalam harga pasar, sehingga pemerintah mengintervensinya melalui instrumen komando dan kendali, instrumen berbasis pasar, serta instrumen sukarela dan informasional seperti PROPER. Tekanan publik, konsumen hijau, ekolabel, dan tuntutan perdagangan internasional mendorong perusahaan melembagakan sistem manajemen lingkungan seperti ISO 14001 dan menjalankan tanggung jawab sosial dalam kerangka <em>triple bottom line</em>. Sementara itu, perubahan iklim menghadirkan risiko fisik dan risiko transisi yang material bagi bisnis, sekaligus membuka peluang melalui transisi hijau menuju ekonomi rendah karbon.</p>
<p>Bagi Indonesia, dengan kekayaan hayati dan kerentanan iklim yang sama-sama tinggi, pengelolaan lingkungan alami merupakan penentu daya saing jangka panjang. Perusahaan yang menginternalisasi biaya lingkungan lebih awal dan memanfaatkan peluang ekonomi hijau akan memperoleh legitimasi sosial sekaligus keunggulan bersaing, sehingga lingkungan alami harus diperlakukan sebagai variabel strategis yang sejajar dengan variabel ekonomi, politik, dan teknologi.</p>`
    },
    {
      no: "9.9",
      title: "Daftar Pustaka",
      body: `<p>Carroll, A. B. dan Buchholtz, A. K. (2015). <em>Business and Society: Ethics, Sustainability, and Stakeholder Management</em>. Edisi 9. Cengage Learning.</p>
<p>Crane, A. dan Matten, D. (2019). <em>Business Ethics: Managing Corporate Citizenship and Sustainability in the Age of Globalization</em>. Edisi 5. Oxford University Press.</p>
<p>Daily, G. C. (1997). <em>Nature's Services: Societal Dependence on Natural Ecosystems</em>. Island Press.</p>
<p>Ehrlich, P. R. dan Holdren, J. P. (1971). Impact of Population Growth. <em>Science</em>, 171(3977), 1212-1217.</p>
<p>Elkington, J. (1997). <em>Cannibals with Forks: The Triple Bottom Line of 21st Century Business</em>. Capstone.</p>
<p>IPCC. (2023). <em>Climate Change 2023: Synthesis Report</em>. Intergovernmental Panel on Climate Change.</p>
<p>Millennium Ecosystem Assessment. (2005). <em>Ecosystems and Human Well-being: Synthesis</em>. Island Press.</p>
<p>Porter, M. E. dan van der Linde, C. (1995). Toward a New Conception of the Environment-Competitiveness Relationship. <em>Journal of Economic Perspectives</em>, 9(4), 97-118.</p>
<p>Tandjung, S. D. (2012). <em>The Natural Environment of Indonesia</em>. Materi kuliah, Universitas Gadjah Mada.</p>
<p>TCFD. (2017). <em>Recommendations of the Task Force on Climate-related Financial Disclosures</em>. Financial Stability Board.</p>
<p>Tietenberg, T. dan Lewis, L. (2018). <em>Environmental and Natural Resource Economics</em>. Edisi 11. Routledge.</p>
<p>Torras, M. (2000). The Total Economic Value of Amazonian Deforestation, 1978-1993. <em>Ecological Economics</em>, 33(2), 283-297.</p>
<p>WCED. (1987). <em>Our Common Future</em>. Oxford University Press.</p>
<p>Worthington, I. dan Britton, C. (2015). <em>The Business Environment</em>. Edisi 7. Pearson.</p>
<p>Modul GBE Sesi 3: deck perkuliahan Lingkungan Alami (Natural), Pak Andhika, Program Studi Magister Manajemen.</p>`
    }
  ]
};
