window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.gbe = window.MBA_BOOK.gbe || {};
window.MBA_BOOK.gbe[8] = {
  bab: 8,
  judul: "BAB 8 LINGKUNGAN HUKUM BISNIS INDONESIA",
  sumber: "Modul GBE: deck Pak Ferry (Google Drive) dan referensi akademik standar topik Lingkungan Hukum Bisnis Indonesia",
  lo: [
    "LO1 Menjelaskan hakikat hukum, fungsi hukum dalam pembangunan ekonomi, serta kedudukan hukum bisnis dalam klasifikasi hukum publik dan hukum privat.",
    "LO2 Mengidentifikasi subyek hukum, obyek hukum, hubungan hukum, sumber hukum, dan hierarki peraturan perundang-undangan yang berlaku bagi pelaku usaha di Indonesia.",
    "LO3 Membedakan bentuk badan usaha berbadan hukum dan tidak berbadan hukum serta menganalisis tanggung jawab direksi dan penerapan business judgment rule.",
    "LO4 Menganalisis keabsahan kontrak berdasarkan syarat sah perjanjian, mengidentifikasi wanprestasi dan perbuatan melawan hukum, serta merumuskan tuntutan ganti rugi.",
    "LO5 Menjelaskan kerangka hukum penanaman modal dan perizinan berusaha berbasis risiko beserta implikasinya bagi keputusan investasi.",
    "LO6 Menerapkan kerangka hukum persaingan usaha, termasuk pengukuran konsentrasi pasar, pendekatan per se illegal dan rule of reason, serta kewajiban notifikasi merger.",
    "LO7 Menguraikan kewajiban pelaku usaha menurut hukum perlindungan konsumen serta kerangka pengaturan sektor perbankan dan pasar modal.",
    "LO8 Mengevaluasi risiko hukum dan kepatuhan perusahaan serta memilih mekanisme penyelesaian sengketa bisnis yang tepat."
  ],
  sections: [
    {
      no: "8.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membahas lingkungan hukum sebagai dimensi lingkungan bisnis yang menentukan keabsahan operasi perusahaan. Berbeda dengan dimensi ekonomi atau teknologi yang bekerja melalui mekanisme pasar, dimensi hukum bekerja melalui norma yang memaksa dan disertai sanksi, sehingga pelanggarannya dapat menghentikan kegiatan usaha meskipun kinerja finansial sedang baik. Materi disusun dari modul General Business Environment mengenai Indonesian Business Law dan diperdalam dengan referensi akademik standar agar cakupannya utuh sampai ke bidang investasi, persaingan usaha, perlindungan konsumen, perbankan, dan pasar modal.</p>
<p>Penekanan bab ini bukan pada hafalan pasal, melainkan pada kemampuan manajer mengenali titik persinggungan antara keputusan bisnis dan kewajiban hukum. Oleh karena itu, pembahasan mengikuti alur legalitas yang dihadapi perusahaan sejak berdiri sampai berperkara, yaitu legalitas badan usaha, legalitas operasional, legalitas transaksional, legalitas aset, kepatuhan sektoral, serta penyelesaian sengketa.</p>
<p>Capaian pembelajaran bab ini adalah sebagai berikut:</p>
<ul>
<li>Menjelaskan hakikat, unsur, dan fungsi hukum serta kedudukan hukum bisnis di antara hukum publik dan hukum privat.</li>
<li>Mengidentifikasi subyek hukum, obyek hukum, hubungan hukum, sumber hukum, dan asas penyelesaian pertentangan norma.</li>
<li>Membedakan bentuk badan usaha serta menganalisis tanggung jawab organ perseroan.</li>
<li>Menganalisis keabsahan kontrak, wanprestasi, perbuatan melawan hukum, dan ganti rugi.</li>
<li>Menjelaskan kerangka penanaman modal dan perizinan berusaha berbasis risiko.</li>
<li>Menerapkan kerangka hukum persaingan usaha dan mengukur konsentrasi pasar.</li>
<li>Menguraikan kewajiban perlindungan konsumen serta pengaturan perbankan dan pasar modal.</li>
<li>Mengevaluasi risiko hukum dan memilih mekanisme penyelesaian sengketa bisnis.</li>
</ul>`
    },
    {
      no: "8.2",
      title: "Hakikat Hukum dan Kedudukan Hukum Bisnis",
      body: `<p>Kegiatan bisnis selalu bersinggungan dengan norma yang berlaku dalam masyarakat. Purbacaraka dan Soekanto membedakan norma kepercayaan, kesusilaan, sopan santun, dan hukum, dan hanya norma hukum yang pelaksanaannya dapat dipaksakan negara. Menurut Mertokusumo (2010), hukum adalah keseluruhan peraturan tentang tingkah laku dalam kehidupan bersama yang pelaksanaannya dapat dipaksakan dengan sanksi, sedangkan Prodjodikoro (2011) menekankan tujuannya, yaitu menjamin keselamatan dan ketertiban masyarakat. Dari definisi tersebut dapat disimpulkan bahwa hukum memuat empat unsur, yaitu peraturan tentang tingkah laku, dibuat badan resmi, bersifat memaksa, dan disertai sanksi tegas.</p>
<h5>8.2.1 Fungsi Hukum dalam Pembangunan Ekonomi</h5>
<p>Fungsi hukum dibedakan menjadi fungsi normatif yang menjaga keadilan, kepastian, kemanfaatan, dan penghormatan hak asasi manusia, serta fungsi instrumental yang menjadikan hukum alat pengendalian dan rekayasa perilaku. Dalam pembangunan ekonomi, hukum baru berperan produktif bila menghadirkan <em>predictability</em> berupa kepastian akibat suatu tindakan, <em>stability</em> berupa kemampuan mengakomodasi kepentingan yang bersaing, dan <em>fairness</em> berupa keadilan perlakuan. Posner (2014) menambahkan bahwa bekerjanya hukum perlu dinilai dari nilai, kegunaan, dan efisiensinya, sehingga aturan yang secara normatif benar tetapi menimbulkan biaya kepatuhan berlebihan tetap perlu dievaluasi. Implikasi manajerialnya, kualitas lingkungan hukum menjadi variabel penilaian risiko negara ketika perusahaan memutuskan ekspansi lintas yurisdiksi.</p>
<h5>8.2.2 Subyek Hukum, Obyek Hukum, dan Hubungan Hukum</h5>
<p>Subyek hukum adalah pendukung hak dan kewajiban, terdiri atas manusia pribadi dan badan hukum. Badan hukum merupakan subyek hukum dalam arti yuridis yang diakui dapat melakukan perbuatan hukum layaknya manusia, dan dibedakan menjadi badan hukum publik seperti negara dan bank sentral, serta badan hukum privat seperti perseroan terbatas dan yayasan. Cirinya meliputi kekayaan terpisah, tujuan tertentu, kepentingan sendiri, dan organisasi teratur. Obyek hukum menurut Pasal 499 KUH Perdata berwujud benda, baik barang berwujud maupun hak yang tidak berwujud, yang digolongkan menjadi benda bergerak dan tidak bergerak serta benda terdaftar dan tidak terdaftar. Hubungan hukum adalah ikatan antara subyek hukum berkenaan dengan obyek hukum yang tercermin pada hak sebagai kepentingan yang dilindungi hukum dan kewajiban sebagai beban yang harus dipenuhi.</p>
<h5>8.2.3 Sumber Hukum dan Asas Penyelesaian Konflik Norma</h5>
<p>Sumber hukum meliputi undang-undang, yurisprudensi, perjanjian internasional, kebiasaan, dan doktrin. Hierarki peraturan diatur dalam Pasal 7 Undang-Undang Nomor 12 Tahun 2011 beserta perubahannya, dari Undang-Undang Dasar Negara Republik Indonesia Tahun 1945, ketetapan Majelis Permusyawaratan Rakyat, undang-undang, peraturan pemerintah, peraturan presiden, hingga peraturan daerah. Peraturan lembaga seperti Bank Indonesia dan Otoritas Jasa Keuangan tetap mengikat sepanjang diperintahkan peraturan yang lebih tinggi, dan justru aturan sektoral inilah yang paling sering dihadapi manajer industri keuangan. Bila terjadi pertentangan norma berlaku tiga asas, yaitu <em>lex superior derogat legi inferiori</em>, <em>lex specialis derogat legi generali</em>, dan <em>lex posterior derogat legi priori</em>.</p>
<h5>8.2.4 Hukum Publik, Hukum Privat, dan Letak Hukum Bisnis</h5>
<p>Hukum publik mengatur kepentingan umum dan hubungan negara dengan warga negara, mencakup hukum tata negara, hukum administrasi negara, hukum pidana, dan hukum acara. Hukum privat mengatur kepentingan perseorangan dalam kedudukan sejajar, mencakup hukum perorangan, keluarga, waris, dan harta kekayaan yang di dalamnya terdapat hukum benda serta hukum perikatan. Menurut Pramono (2013), hukum bisnis adalah hukum yang berkaitan dengan perikatan dan badan usaha dalam berbagai lapangan perdagangan, sehingga akarnya berada pada hukum privat. Namun, hukum bisnis modern bersifat campuran karena perizinan, pengawasan persaingan, dan pertanggungjawaban pidana korporasi menariknya ke ranah publik. Dengan demikian, satu peristiwa bisnis dapat melahirkan tiga akibat sekaligus, yaitu perdata, administratif, dan pidana.</p>
<table class="bk-table">
<caption>Tabel 8.1 Perbandingan Hukum Publik dan Hukum Privat bagi Pelaku Usaha</caption>
<thead><tr><th>Segi Pembeda</th><th>Hukum Publik</th><th>Hukum Privat</th></tr></thead>
<tbody>
<tr><td>Kepentingan yang dilindungi</td><td>Kepentingan umum dan ketertiban pasar</td><td>Kepentingan perseorangan para pihak</td></tr>
<tr><td>Kedudukan para pihak</td><td>Tidak sejajar karena negara sebagai regulator</td><td>Sejajar antara pelaku usaha dan mitranya</td></tr>
<tr><td>Pihak yang menegakkan</td><td>Negara melalui penuntut umum atau otoritas sektoral</td><td>Pihak yang berkepentingan sendiri</td></tr>
<tr><td>Contoh dalam bisnis</td><td>Perizinan berusaha, pengawasan persaingan</td><td>Perjanjian kredit, jual beli, distribusi</td></tr>
<tr><td>Konsekuensi manajerial</td><td>Kepatuhan wajib dan tidak dapat dinegosiasikan</td><td>Dapat diatur sendiri sepanjang tidak melanggar hukum</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari modul General Business Environment dan Fuady (2019)</td></tr></tfoot>
</table>`
    },
    {
      no: "8.3",
      title: "Legalitas Badan Usaha dan Tanggung Jawab Organ Perseroan",
      body: `<p>Legalitas pendirian merupakan lapis pertama kepatuhan karena menentukan pengakuan suatu entitas sebagai pendukung hak dan kewajiban. Perusahaan menurut Undang-Undang Nomor 8 Tahun 1997 tentang Dokumen Perusahaan adalah setiap bentuk usaha yang menjalankan kegiatan secara tetap dan terus menerus untuk memperoleh keuntungan, baik oleh perseorangan maupun badan usaha berbadan hukum maupun bukan. Doktrin menambahkan kriteria menjalankan perusahaan, yaitu bertindak tidak terputus-putus, terang-terangan, dalam kedudukan tertentu, berhubungan dengan pihak ketiga, bertujuan laba, dan tercatat dalam pembukuan. Pemilihan bentuk badan usaha karena itu merupakan keputusan strategis yang menentukan batas tanggung jawab pemilik, akses pembiayaan, dan kelayakan memasuki sektor tertentu.</p>
<h5>8.3.1 Badan Usaha Berbadan Hukum dan Tidak Berbadan Hukum</h5>
<p>Badan usaha tidak berbadan hukum seperti persekutuan perdata, firma, dan persekutuan komanditer bukan subyek hukum mandiri, sehingga kekayaannya tidak terpisah dari kekayaan pribadi sekutu dan tanggung jawabnya tidak terbatas hingga harta pribadi. Sebaliknya, badan usaha berbadan hukum seperti perseroan terbatas, koperasi berbadan hukum, dan badan usaha milik negara dapat membuat kontrak serta berperkara atas namanya sendiri dengan tanggung jawab pemegang saham yang terbatas. Status badan hukum privat diperoleh setelah pengesahan menteri, sedangkan badan hukum publik ditetapkan melalui peraturan perundang-undangan. Perseroan terbatas diatur dalam Undang-Undang Nomor 40 Tahun 2007 sebagaimana diubah melalui undang-undang bidang cipta kerja, yang memperkenalkan perseroan perorangan bagi usaha mikro dan kecil sehingga pelaku usaha kecil dapat menikmati tanggung jawab terbatas tanpa prosedur pendirian yang berat. Implikasi manajerialnya, pemilik usaha yang menghadapi risiko gugatan besar sebaiknya tidak mempertahankan bentuk persekutuan yang membuka seluruh harta pribadi terhadap tuntutan kreditur.</p>
<table class="bk-table">
<caption>Tabel 8.2 Konsekuensi Pemilihan Bentuk Badan Usaha</caption>
<thead><tr><th>Aspek</th><th>Perseorangan dan Persekutuan</th><th>Perseroan Terbatas</th></tr></thead>
<tbody>
<tr><td>Status subyek hukum</td><td>Melekat pada pendiri atau sekutu</td><td>Mandiri dan terpisah dari pemegang saham</td></tr>
<tr><td>Tanggung jawab</td><td>Tidak terbatas sampai harta pribadi</td><td>Terbatas pada nilai penyertaan saham</td></tr>
<tr><td>Kesinambungan usaha</td><td>Bergantung pada keberadaan sekutu</td><td>Berlanjut meskipun pemegang saham berganti</td></tr>
<tr><td>Akses pembiayaan</td><td>Terbatas pada kredit dan modal sekutu</td><td>Terbuka pada penyertaan modal dan pasar modal</td></tr>
<tr><td>Sektor terregulasi</td><td>Umumnya tidak memenuhi syarat</td><td>Disyaratkan bagi bank, asuransi, dan penanaman modal asing</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Undang-Undang Nomor 40 Tahun 2007 dan Fuady (2019)</td></tr></tfoot>
</table>
<h5>8.3.2 Tanggung Jawab Direksi dan Business Judgment Rule</h5>
<p>Pasal 92 dan Pasal 97 Undang-Undang Nomor 40 Tahun 2007 menegaskan bahwa direksi bertanggung jawab atas pengurusan perseroan dan wajib menjalankannya dengan itikad baik serta penuh tanggung jawab, sehingga anggota direksi yang bersalah atau lalai dapat dimintai pertanggungjawaban pribadi atas kerugian perseroan. Ketentuan ini diimbangi <em>business judgment rule</em> dalam Pasal 97 ayat (5), yang membebaskan direksi dari tanggung jawab pribadi apabila kerugian bukan karena kesalahan atau kelalaiannya, pengurusan dilakukan dengan itikad baik dan kehati-hatian sesuai maksud dan tujuan perseroan, tidak terdapat benturan kepentingan, serta telah diambil tindakan untuk mencegah berlanjutnya kerugian. Doktrin ini penting karena keputusan bisnis mengandung ketidakpastian, sehingga hukum tidak menghukum kerugian itu sendiri melainkan proses pengambilan keputusan yang cacat. Rangkaian perkara yang menjerat sejumlah mantan direktur utama badan usaha milik negara di Indonesia menunjukkan bahwa keputusan investasi tanpa kajian memadai dapat berpindah dari ranah perdata ke ranah pidana ketika terdapat kerugian keuangan negara. Oleh karena itu, dokumentasi kajian kelayakan, notulen rapat direksi, opini ahli independen, dan pengungkapan benturan kepentingan berfungsi sebagai alat bukti yang melindungi pengurus.</p>`
    },
    {
      no: "8.4",
      title: "Hukum Kontrak dan Legalitas Transaksional",
      body: `<p>Legalitas transaksional paling sering disentuh manajer karena hampir seluruh aktivitas bisnis dituangkan dalam perikatan, yaitu hubungan hukum dalam lapangan harta kekayaan antara dua pihak yang menimbulkan hak pada kreditur dan kewajiban berprestasi pada debitur. Menurut Pasal 1233 KUH Perdata, perikatan lahir karena perjanjian atau karena undang-undang. Prestasi menurut Pasal 1234 KUH Perdata berbentuk memberikan sesuatu, berbuat sesuatu, atau tidak berbuat sesuatu, dan bentuk prestasi itulah yang menentukan cara menuntut pemenuhannya di kemudian hari.</p>
<h5>8.4.1 Pengertian, Fungsi, dan Syarat Sah Perjanjian</h5>
<p>Pasal 1313 KUH Perdata merumuskan perjanjian sebagai perbuatan dengan mana satu orang atau lebih mengikatkan dirinya terhadap satu orang atau lebih. Rumusan itu dinilai kurang lengkap sehingga doktrin melengkapinya, dan Mertokusumo (2010) menyatakan bahwa perjanjian adalah "hubungan hukum antara dua pihak atau lebih berdasarkan kata sepakat untuk menimbulkan akibat hukum". Dari kedua rumusan tersebut dapat disimpulkan bahwa perjanjian menuntut kesepakatan yang sengaja diarahkan pada lahirnya akibat hukum, dengan fungsi sebagai alat bukti hubungan hukum sekaligus alat mengantisipasi konflik. Pasal 1320 KUH Perdata menetapkan empat syarat sah, yaitu sepakat mereka yang mengikatkan diri, kecakapan, suatu hal tertentu, dan suatu sebab yang halal. Dua syarat pertama merupakan syarat subyektif yang bila tidak terpenuhi membuat perjanjian dapat dibatalkan, sedangkan dua syarat terakhir merupakan syarat obyektif yang bila tidak terpenuhi membuat perjanjian batal demi hukum sehingga dianggap tidak pernah ada.</p>
<p>Kesepakatan harus bebas dari cacat kehendak karena Pasal 1321 KUH Perdata menyatakan tiada sepakat yang sah apabila diberikan karena kekhilafan, paksaan, atau penipuan, dan doktrin menambahkan penyalahgunaan keadaan. Kecakapan berarti kemampuan melakukan perbuatan hukum secara mandiri, dan Pasal 1330 KUH Perdata mengecualikan orang yang belum dewasa serta mereka yang berada di bawah pengampuan, sedangkan bagi badan hukum kecakapan diwakili organ yang berwenang seperti direksi. Suatu hal tertentu menuntut obyek yang sekurang-kurangnya dapat ditentukan jenisnya dan berada dalam perdagangan, sedangkan sebab yang halal menuntut tujuan perjanjian tidak bertentangan dengan peraturan perundang-undangan, ketertiban umum, dan kesusilaan. Dalam praktik korporasi, kelalaian memeriksa kewenangan penanda tangan merupakan cacat yang paling sering muncul, misalnya ketika kontrak bernilai besar ditandatangani pejabat yang menurut anggaran dasar memerlukan persetujuan dewan komisaris.</p>
<h5>8.4.2 Unsur dan Bentuk Perjanjian</h5>
<p>Perjanjian mengandung tiga unsur yang perlu dibedakan, yaitu:</p>
<ul>
<li><em>Essensialia</em>, unsur mutlak yang tanpa kehadirannya perjanjian tidak mungkin ada, misalnya kesepakatan barang dan harga dalam jual beli.</li>
<li><em>Naturalia</em>, unsur yang telah diatur undang-undang sehingga berlaku otomatis bila tidak diatur para pihak, misalnya kewajiban penjual menanggung cacat tersembunyi.</li>
<li><em>Accidentalia</em>, unsur yang hanya berlaku bila diperjanjikan secara tegas, misalnya denda keterlambatan angsuran.</li>
</ul>
<p>Perjanjian dapat dibuat lisan maupun tertulis, dan bentuk tertulis dibedakan menjadi akta di bawah tangan serta akta otentik yang dibuat oleh atau di hadapan pejabat berwenang. Akta otentik memiliki kekuatan pembuktian sempurna sehingga lazim dipakai untuk transaksi bernilai besar, hak atas tanah, dan pemberian jaminan. Dalam kerja sama bisnis, para pihak sering memulai dengan nota kesepahaman yang memuat ruang lingkup umum, kemudian menurunkannya menjadi perjanjian kerja sama yang memuat hak dan kewajiban konkret. Manajer perlu menyadari bahwa nota kesepahaman umumnya belum melahirkan kewajiban prestasi yang dapat dituntut, sehingga menempatkan komitmen komersial penting hanya pada dokumen tersebut melemahkan posisi hukum perusahaan.</p>
<h5>8.4.3 Wanprestasi, Perbuatan Melawan Hukum, dan Ganti Rugi</h5>
<p>Wanprestasi adalah keadaan debitur tidak memenuhi kewajiban sesuai kesepakatan, yang wujudnya berupa tidak melakukan apa yang disanggupi, melakukan tetapi tidak sebagaimana diperjanjikan, melakukan tetapi terlambat, atau melakukan sesuatu yang menurut perjanjian tidak boleh dilakukan. Debitur baru dinyatakan wanprestasi bila terpenuhi syarat materiil berupa kesalahan dalam bentuk kesengajaan atau kelalaian, dan syarat formil berupa pernyataan lalai atau somasi sebagaimana diatur dalam Pasal 1238 KUH Perdata. Somasi yang baik memuat apa yang dituntut, dasar tuntutan, dan batas waktu terakhir pemenuhan prestasi, sehingga berfungsi sekaligus sebagai alat bukti dan upaya penyelamatan hubungan bisnis. Akibat hukum wanprestasi meliputi kewajiban ganti rugi, pembatalan perjanjian, peralihan risiko, dan pembayaran biaya perkara.</p>
<p>Sumber tuntutan ganti rugi kedua adalah perbuatan melawan hukum menurut Pasal 1365 KUH Perdata, yang menuntut adanya perbuatan melawan hukum, kesalahan, kerugian, dan hubungan sebab akibat. Perbedaan praktisnya, wanprestasi mensyaratkan hubungan kontraktual sebelumnya, sedangkan perbuatan melawan hukum dapat diajukan tanpa kontrak, misalnya oleh warga yang dirugikan pencemaran limbah suatu pabrik. Besaran tuntutan ganti rugi dapat dirumuskan sebagai berikut:</p>
<p><strong>Ganti Rugi = Kerugian yang Nyata Diderita (damnum emergens) + Keuntungan yang Sedianya Diperoleh (lucrum cessans) + Bunga dan Biaya Perkara</strong></p>
<p>Cara memakai rumus tersebut adalah menghitung lebih dahulu biaya yang benar-benar dikeluarkan dan kehilangan nilai aset akibat pelanggaran, menambahkan proyeksi keuntungan yang hilang yang dapat dibuktikan secara wajar berdasarkan kontrak atau kinerja historis, lalu menambahkan bunga dan biaya perkara. Pengadilan menuntut pembuktian terukur sehingga proyeksi keuntungan yang spekulatif sering ditolak. Oleh karena itu, perusahaan perlu merancang klausul ganti rugi, denda keterlambatan, dan pembatasan tanggung jawab secara eksplisit agar besaran risiko dapat diperkirakan sejak awal.</p>`
    },
    {
      no: "8.5",
      title: "Hukum Investasi dan Legalitas Operasional",
      body: `<p>Setelah badan usaha berdiri, perusahaan memerlukan legalitas operasional yang menjamin keabsahan kegiatan usahanya. Kerangka penanaman modal bertumpu pada Undang-Undang Nomor 25 Tahun 2007 tentang Penanaman Modal, yang membedakan penanaman modal dalam negeri dan penanaman modal asing serta menganut asas kepastian hukum, keterbukaan, akuntabilitas, dan perlakuan yang sama tanpa membedakan asal negara penanam modal. Undang-undang tersebut mensyaratkan penanaman modal asing berbentuk perseroan terbatas berdasarkan hukum Indonesia, sehingga investor asing tidak dapat berusaha melalui bentuk persekutuan. Ketentuan pelaksana menetapkan ambang nilai investasi minimum di luar tanah dan bangunan, sedangkan pengaturan bidang usaha kini lebih terbuka melalui daftar prioritas investasi dalam peraturan presiden mengenai bidang usaha penanaman modal.</p>
<h5>8.5.1 Fasilitas dan Perlindungan Investasi</h5>
<p>Negara memberikan sejumlah insentif untuk menarik penanaman modal, antara lain pengurangan pajak penghasilan badan bagi industri pionir, pengurangan penghasilan neto pada bidang usaha tertentu, pembebasan bea masuk barang modal, serta kemudahan hak atas tanah dan izin tinggal tenaga kerja asing. Sebagai imbangannya, penanam modal wajib menerapkan tata kelola perusahaan yang baik, melaksanakan tanggung jawab sosial dan lingkungan, menyampaikan laporan kegiatan penanaman modal, dan menghormati hak masyarakat sekitar. Undang-undang tersebut juga menyediakan penyelesaian sengketa antara pemerintah dan penanam modal asing melalui arbitrase internasional yang disepakati para pihak, yang menjadi jaminan kepastian bagi investor. Bagi manajer, pemetaan insentif bersifat strategis karena perbedaan status fasilitas dapat mengubah proyeksi arus kas proyek sehingga perlu dikaji sebelum lokasi dan struktur entitas ditetapkan.</p>
<h5>8.5.2 Perizinan Berusaha Berbasis Risiko</h5>
<p>Reformasi melalui undang-undang bidang cipta kerja dan Peraturan Pemerintah Nomor 5 Tahun 2021 mengubah paradigma perizinan menjadi berbasis risiko yang diproses melalui sistem perizinan berusaha terintegrasi secara elektronik. Tingkat risiko ditentukan oleh penilaian bahaya dan potensi terjadinya bahaya, lalu menentukan dokumen yang wajib dimiliki, yaitu nomor induk berusaha bagi kegiatan berisiko rendah, nomor induk berusaha dan sertifikat standar bagi kegiatan berisiko menengah, serta nomor induk berusaha, sertifikat standar, dan izin bagi kegiatan berisiko tinggi. Klasifikasi melekat pada kode Klasifikasi Baku Lapangan Usaha Indonesia sehingga perusahaan dengan beberapa lini usaha dapat menyandang beberapa tingkat risiko sekaligus. Sebagai ilustrasi, budidaya sapi potong tergolong berisiko rendah, pertanian kedelai skala menengah memerlukan tambahan sertifikat standar, sedangkan pertambangan batu bara tergolong berisiko tinggi sehingga menuntut izin penuh. Beroperasi tanpa izin atau dengan izin yang telah berakhir dapat berujung pada sanksi administratif berupa denda dan penghentian kegiatan, bahkan sanksi pidana pada sektor tertentu.</p>
<h5>8.5.3 Legalitas Aset dan Jaminan</h5>
<p>Legalitas aset mencakup keabsahan kepemilikan, peralihan, dan penjaminan. Kepemilikan tanah dibuktikan dengan sertifikat hak milik, hak guna bangunan, atau hak pakai, kendaraan dengan bukti pemilikan kendaraan bermotor, dan merek dengan sertifikat pendaftaran. Peralihan menuntut prosedur tersendiri seperti akta jual beli di hadapan pejabat pembuat akta tanah, balik nama kendaraan, atau akta pemindahan hak atas saham. Penjaminan mengikuti sifat bendanya, yaitu hak tanggungan untuk tanah, hipotek untuk kapal berukuran tertentu, gadai untuk benda bergerak yang diserahkan penguasaannya, dan jaminan fidusia untuk benda bergerak yang tetap dikuasai debitur termasuk hak kekayaan intelektual. Kasus sertifikat tanah ganda yang kerap muncul di Indonesia menunjukkan bahwa uji tuntas dokumen kepemilikan merupakan pengendalian risiko yang tidak boleh dilewati, karena aset cacat hukum melemahkan neraca sekaligus posisi perusahaan di hadapan kreditur.</p>`
    },
    {
      no: "8.6",
      title: "Hukum Persaingan Usaha",
      body: `<p>Hukum persaingan usaha bertujuan menjaga proses persaingan agar efisiensi dan kesejahteraan konsumen terpelihara. Landasannya adalah Undang-Undang Nomor 5 Tahun 1999 tentang Larangan Praktek Monopoli dan Persaingan Usaha Tidak Sehat, yang penegakannya dipercayakan kepada Komisi Pengawas Persaingan Usaha sebagai lembaga kuasi yudisial dengan kewenangan menyelidiki, memeriksa, dan memutus perkara. Undang-undang tersebut memakai istilah pelaku usaha, yaitu setiap orang perseorangan atau badan usaha yang menyelenggarakan kegiatan ekonomi di wilayah hukum Indonesia, sehingga jangkauannya mencakup badan usaha yang tidak berbadan hukum. Larangannya dikelompokkan menjadi perjanjian yang dilarang, kegiatan yang dilarang, dan penyalahgunaan posisi dominan.</p>
<h5>8.6.1 Larangan Pokok dan Ambang Posisi Dominan</h5>
<p>Perjanjian yang dilarang meliputi oligopoli, penetapan harga, diskriminasi harga, pembagian wilayah pemasaran, pemboikotan, kartel, trust, oligopsoni, integrasi vertikal, perjanjian tertutup, serta perjanjian dengan pihak luar negeri yang mengakibatkan persaingan tidak sehat. Kegiatan yang dilarang meliputi praktik monopoli, monopsoni, penguasaan pasar yang menghambat pesaing, dan persekongkolan termasuk persekongkolan tender. Kelompok posisi dominan meliputi penyalahgunaan posisi dominan, jabatan rangkap, pemilikan saham silang, serta penggabungan, peleburan, dan pengambilalihan yang dapat mengakibatkan praktik monopoli. Undang-undang memberi ambang indikatif, yaitu satu pelaku usaha dianggap berposisi dominan bila menguasai lebih dari lima puluh persen pangsa pasar, sedangkan dua atau tiga pelaku usaha dianggap dominan bila bersama-sama menguasai lebih dari tujuh puluh lima persen pangsa pasar satu jenis barang atau jasa tertentu.</p>
<h5>8.6.2 Pendekatan Penilaian dan Pengukuran Konsentrasi Pasar</h5>
<p>Penilaian perkara memakai dua pendekatan. Pendekatan <em>per se illegal</em> menyatakan suatu perbuatan melanggar hukum semata karena bentuknya tanpa perlu membuktikan dampaknya, dan lazim diterapkan pada kartel penetapan harga. Pendekatan <em>rule of reason</em> menuntut analisis apakah perbuatan tersebut benar-benar mengakibatkan praktik monopoli atau persaingan tidak sehat, dan dikenali dari rumusan pasal yang memuat frasa mengenai akibat terjadinya persaingan usaha tidak sehat. Analisis diawali penetapan pasar bersangkutan menurut dimensi produk dan dimensi geografis, kemudian dilanjutkan pengukuran konsentrasi dengan dua alat berikut:</p>
<p><strong>CR4 = S1 + S2 + S3 + S4</strong>, yaitu penjumlahan pangsa pasar empat pelaku usaha terbesar dalam persen.</p>
<p><strong>HHI = (S1)&sup2; + (S2)&sup2; + ... + (Sn)&sup2;</strong>, yaitu penjumlahan kuadrat pangsa pasar seluruh pelaku usaha dalam persen.</p>
<p>Cara memakainya adalah menghitung pangsa pasar setiap pelaku usaha berdasarkan nilai penjualan pada pasar bersangkutan, lalu menempatkan hasil HHI pada spektrum konsentrasi, di mana nilai rendah menandakan pasar terdesentralisasi dan nilai tinggi menandakan pasar terkonsentrasi sehingga menuntut penelaahan lebih dalam. Selain nilai absolut, otoritas menaruh perhatian pada perubahan HHI sebelum dan sesudah transaksi karena kenaikan tajam menandakan hilangnya tekanan persaingan. Kerangka yang sama dapat dipakai manajer secara internal untuk menilai apakah rencana akuisisi berpotensi menimbulkan keberatan otoritas sebelum kesepakatan ditandatangani.</p>
<h5>8.6.3 Notifikasi Merger dan Sanksi</h5>
<p>Penggabungan, peleburan, dan pengambilalihan saham yang mengakibatkan nilai aset atau nilai penjualan gabungan melampaui ambang tertentu wajib diberitahukan kepada Komisi Pengawas Persaingan Usaha dalam tiga puluh hari kerja setelah transaksi berlaku efektif secara yuridis, sebagaimana diatur peraturan pemerintah mengenai penggabungan atau peleburan badan usaha dan pengambilalihan saham. Keterlambatan dikenai denda administratif per hari, sedangkan pelanggaran materiil dapat berujung perintah pembatalan transaksi. Sanksi pelanggaran substantif berupa pembatalan perjanjian, perintah penghentian kegiatan, dan denda administratif yang perhitungannya dikaitkan dengan keuntungan bersih yang diperoleh atau nilai penjualan pada pasar bersangkutan selama periode pelanggaran. Perkara dugaan kartel di Indonesia pernah menyentuh industri pangan, unggas, dan telekomunikasi, dan pola yang berulang menunjukkan bahwa pertukaran informasi harga antarpesaing melalui asosiasi merupakan titik rawan yang sering tidak disadari manajer pemasaran. Oleh karena itu, perusahaan perlu memiliki pedoman kepatuhan persaingan yang mengatur batas komunikasi dengan pesaing.</p>`
    },
    {
      no: "8.7",
      title: "Hukum Perlindungan Konsumen",
      body: `<p>Hukum perlindungan konsumen mengoreksi ketimpangan posisi tawar yang bersumber dari asimetri informasi. Landasannya adalah Undang-Undang Nomor 8 Tahun 1999 tentang Perlindungan Konsumen, yang mendefinisikan konsumen sebagai setiap orang pemakai barang atau jasa yang tersedia dalam masyarakat untuk kepentingan diri sendiri, keluarga, atau makhluk hidup lain dan tidak untuk diperdagangkan. Menurut Shidarta (2006), hukum perlindungan konsumen tidak dimaksudkan mematikan usaha melainkan mendorong iklim usaha sehat dengan menempatkan kejujuran informasi sebagai syarat bersaing. Dengan demikian, kepatuhan pada bidang ini sebaiknya dipandang sebagai investasi reputasi dan bukan sekadar beban biaya.</p>
<h5>8.7.1 Hak Konsumen dan Kewajiban Pelaku Usaha</h5>
<p>Pasal 4 memberikan sejumlah hak kepada konsumen, antara lain hak atas kenyamanan dan keselamatan dalam mengonsumsi barang atau jasa, hak memilih dan memperoleh barang sesuai nilai tukar serta kondisi yang dijanjikan, hak atas informasi yang benar dan jujur, hak didengar keluhannya, hak memperoleh advokasi dan penyelesaian sengketa, hak atas pendidikan konsumen, hak diperlakukan tidak diskriminatif, serta hak memperoleh kompensasi. Sebagai cerminannya, Pasal 7 mewajibkan pelaku usaha beritikad baik, memberikan informasi yang benar, melayani secara tidak diskriminatif, menjamin mutu barang berdasarkan standar yang berlaku, memberi kesempatan menguji barang tertentu, serta memberi kompensasi bila barang tidak sesuai perjanjian. Pasal 8 sampai Pasal 17 melengkapinya dengan larangan memproduksi dan memperdagangkan barang yang tidak memenuhi standar, tidak sesuai label, kedaluwarsa, atau dipromosikan secara menyesatkan.</p>
<h5>8.7.2 Klausula Baku, Tanggung Jawab Produk, dan Sengketa Konsumen</h5>
<p>Pasal 18 melarang klausula baku yang mengalihkan tanggung jawab pelaku usaha, menundukkan konsumen pada aturan baru yang dibuat sepihak, atau memberi kuasa kepada pelaku usaha untuk membebani konsumen secara sepihak, dan klausula demikian batal demi hukum. Pasal 19 mewajibkan pemberian ganti rugi atas kerusakan, pencemaran, atau kerugian akibat mengonsumsi barang dan jasa yang dihasilkan, dengan tenggang waktu pemenuhan yang singkat. Ciri khas rezim ini adalah bergesernya beban pembuktian kepada pelaku usaha, sehingga pelaku usaha tanpa dokumentasi mutu produksi berada pada posisi lemah ketika berperkara. Penyelesaian sengketa dapat ditempuh melalui pengadilan maupun di luar pengadilan, dengan jalur khusus melalui Badan Penyelesaian Sengketa Konsumen yang memutus secara konsiliasi, mediasi, atau arbitrase. Perkembangan perdagangan melalui sistem elektronik memperluas kewajiban tersebut karena peraturan pemerintah mengenai perdagangan melalui sistem elektronik menuntut kelengkapan informasi produk, kejelasan identitas pedagang, dan mekanisme pengembalian barang, yang dalam praktik menjadi standar layanan pada lokapasar besar di pasar domestik. Implikasi manajerialnya, kepatuhan fungsi pemasaran dan layanan purnajual perlu ditinjau sejak perancangan kampanye, bukan setelah keluhan konsumen muncul.</p>`
    },
    {
      no: "8.8",
      title: "Hukum Perbankan dan Pasar Modal",
      body: `<p>Sektor jasa keuangan merupakan lapangan bisnis dengan intensitas regulasi tertinggi karena bertumpu pada kepercayaan publik dan mengandung risiko sistemik. Perbankan diatur Undang-Undang Nomor 7 Tahun 1992 sebagaimana diubah dengan Undang-Undang Nomor 10 Tahun 1998 dan disempurnakan melalui undang-undang mengenai pengembangan dan penguatan sektor keuangan, dengan pengawasan mikroprudensial oleh Otoritas Jasa Keuangan berdasarkan Undang-Undang Nomor 21 Tahun 2011, sedangkan kebijakan moneter dan sistem pembayaran berada pada Bank Indonesia. Bank adalah badan usaha yang menghimpun dana masyarakat dalam bentuk simpanan dan menyalurkannya dalam bentuk kredit atau bentuk lain untuk meningkatkan taraf hidup rakyat banyak, sehingga bentuk hukumnya dibatasi pada bentuk tertentu seperti perseroan terbatas. Penjaminan simpanan diselenggarakan Lembaga Penjamin Simpanan sebagai pelengkap arsitektur pengamanan sektor keuangan.</p>
<h5>8.8.1 Prinsip Kehati-hatian dan Rahasia Bank</h5>
<p>Prinsip kehati-hatian mewajibkan bank menjalankan usaha dengan pengelolaan risiko memadai, yang diterjemahkan menjadi kewajiban penyediaan modal minimum, batas maksimum pemberian kredit untuk mencegah pemusatan risiko pada satu debitur atau kelompok terkait, penilaian kualitas aktiva, serta penerapan prinsip mengenal nasabah dan pencegahan pencucian uang. Kewajiban penyediaan modal minimum lazim diukur dengan rasio berikut:</p>
<p><strong>CAR = (Modal Inti + Modal Pelengkap) / Aktiva Tertimbang Menurut Risiko x 100 persen</strong></p>
<p>Cara memakainya adalah membandingkan hasil perhitungan dengan ambang minimum yang ditetapkan regulator berdasarkan profil risiko bank, dan bank yang berada di bawah ambang tersebut wajib menambah modal atau menurunkan eksposur berisiko. Selain itu, rahasia bank mewajibkan bank tidak mengungkapkan keterangan mengenai nasabah penyimpan dan simpanannya kecuali dalam hal yang dikecualikan undang-undang, misalnya untuk kepentingan perpajakan, peradilan pidana, atau atas persetujuan tertulis nasabah. Bagi manajer korporasi nonbank, pemahaman ini menjelaskan mengapa bank menuntut jaminan serta pembatasan finansial dalam perjanjian kredit dan seberapa jauh struktur pembiayaan yang diusulkan dapat diterima.</p>
<h5>8.8.2 Pasar Modal dan Prinsip Keterbukaan</h5>
<p>Pasar modal Indonesia berlandaskan Undang-Undang Nomor 8 Tahun 1995 tentang Pasar Modal beserta perubahannya, dengan pengawasan Otoritas Jasa Keuangan dan infrastruktur berupa bursa efek, lembaga kliring dan penjaminan, serta lembaga penyimpanan dan penyelesaian. Asas utamanya adalah prinsip keterbukaan, yaitu kewajiban emiten menyampaikan seluruh informasi material yang dapat memengaruhi keputusan investor secara akurat, lengkap, dan tepat waktu, baik melalui prospektus pada saat penawaran umum maupun melalui laporan berkala dan laporan informasi material setelah tercatat. Undang-undang tersebut melarang manipulasi pasar dan perdagangan orang dalam, yaitu transaksi efek oleh pihak yang memiliki informasi orang dalam yang belum tersedia bagi publik, dan larangan itu menjangkau pula pihak yang menerima informasi tersebut. Bagi perusahaan yang mempertimbangkan penawaran umum perdana, konsekuensi terpenting adalah beralihnya perusahaan dari rezim keterbukaan sukarela ke rezim keterbukaan wajib, sehingga struktur tata kelola, komite audit, dan pengendalian internal harus disiapkan jauh sebelum pencatatan saham.</p>`
    },
    {
      no: "8.9",
      title: "Risiko Hukum dan Penyelesaian Sengketa Bisnis",
      body: `<p>Seluruh lapis legalitas bermuara pada pertanyaan seberapa besar eksposur risiko hukum perusahaan dan bagaimana mengelolanya. Risiko hukum timbul akibat tuntutan hukum atau kelemahan aspek yuridis, sedangkan risiko kepatuhan timbul akibat perusahaan tidak mematuhi peraturan yang berlaku. Pelanggaran aspek legalitas dapat melahirkan sanksi perdata berupa ganti rugi, sanksi administratif berupa denda hingga pencabutan izin, dan sanksi pidana berupa denda maupun pemidanaan pengurus. Untuk memetakannya dapat dipakai kerangka berikut:</p>
<p><strong>Eksposur Risiko Hukum = Probabilitas Terjadinya Peristiwa Hukum x Dampak Finansial dan Reputasi x (1 - Efektivitas Pengendalian)</strong></p>
<p>Cara memakainya adalah menyusun daftar peristiwa hukum yang mungkin terjadi pada setiap lapis legalitas, menaksir probabilitas dan dampaknya dalam skala yang konsisten, lalu menilai efektivitas pengendalian yang telah ada seperti uji tuntas kontrak, pemantauan masa berlaku izin, pelatihan kepatuhan persaingan, dan pengarsipan dokumen mutu. Hasilnya berupa peringkat risiko yang menentukan prioritas alokasi sumber daya kepatuhan. Kerangka ini mengubah pembicaraan hukum yang sering bersifat kualitatif menjadi bahan keputusan yang dapat dibandingkan dengan risiko bisnis lainnya.</p>
<h5>8.9.1 Jalur Penyelesaian Sengketa Bisnis</h5>
<p>Sutiyoso (2008) mengelompokkan sengketa bisnis ke dalam sengketa perniagaan, perbankan, keuangan, penanaman modal, hak kekayaan intelektual, konsumen, kontrak, perburuhan, dan properti. Penyelesaiannya ditempuh melalui tiga jalur. Jalur litigasi berlangsung di pengadilan negeri dan tingkat berikutnya, dengan pengadilan niaga untuk perkara kepailitan, penundaan kewajiban pembayaran utang, dan hak kekayaan intelektual. Jalur nonlitigasi diatur dalam Undang-Undang Nomor 30 Tahun 1999 tentang Arbitrase dan Alternatif Penyelesaian Sengketa yang mencakup negosiasi, mediasi, konsiliasi, dan arbitrase, dengan putusan arbitrase bersifat final dan mengikat serta didaftarkan ke pengadilan negeri untuk memperoleh kekuatan eksekutorial. Jalur ketiga adalah lembaga kuasi yudisial seperti Komisi Pengawas Persaingan Usaha dan Badan Penyelesaian Sengketa Konsumen.</p>
<p>Pemilihan jalur sebaiknya ditetapkan sejak penyusunan kontrak melalui klausul penyelesaian sengketa, karena setelah sengketa muncul kesepakatan sulit dicapai. Arbitrase unggul dalam kerahasiaan, keahlian arbiter, dan kepastian waktu, tetapi menuntut biaya di muka yang relatif tinggi. Litigasi memberi akses upaya hukum berjenjang dan kekuatan eksekusi langsung, tetapi bersifat terbuka sehingga berisiko bagi reputasi. Mediasi paling murah dan menjaga hubungan bisnis, tetapi bergantung pada itikad baik kedua pihak. Oleh karena itu, perusahaan yang berorientasi hubungan jangka panjang dengan pemasok strategis lazim menempuh mekanisme berjenjang yang dimulai dari musyawarah dalam tenggat tertentu sebelum beralih ke arbitrase.</p>
<h5>8.9.2 Tantangan Hukum Bisnis pada Era Digital</h5>
<p>Digitalisasi menghadirkan model usaha yang tumbuh lebih cepat daripada pembentukan aturannya, sebagaimana terlihat dari perusahaan rintisan berbasis platform yang valuasinya melampaui perusahaan mapan dalam waktu singkat. Regulator Indonesia meresponsnya melalui undang-undang mengenai informasi dan transaksi elektronik beserta perubahannya, peraturan pemerintah mengenai penyelenggara sistem dan transaksi elektronik, peraturan pemerintah mengenai perdagangan melalui sistem elektronik, peraturan otoritas jasa keuangan mengenai layanan pendanaan bersama berbasis teknologi informasi, peraturan bank sentral mengenai penyelenggaraan teknologi finansial, serta undang-undang mengenai pelindungan data pribadi. Aturan pelindungan data pribadi mengubah cara perusahaan memperlakukan data pelanggan karena menuntut dasar pemrosesan yang sah, penunjukan pejabat pelindungan data pada kondisi tertentu, dan kewajiban pemberitahuan bila terjadi kegagalan pelindungan data. Dengan demikian, lingkungan hukum yang mudah berubah, tidak pasti, kompleks, dan ambigu menuntut kemampuan pemantauan regulasi yang berkelanjutan, bukan kepatuhan sesaat pada waktu izin diterbitkan.</p>`
    },
    {
      no: "8.10",
      title: "Rangkuman",
      body: `<p>Bab ini memperlihatkan bahwa lingkungan hukum bekerja melalui norma yang memaksa dan disertai sanksi, sehingga kedudukannya berbeda dari dimensi lingkungan bisnis lain yang bekerja melalui mekanisme pasar. Hukum menopang pembangunan ekonomi apabila mampu menghadirkan kepastian, stabilitas, dan keadilan, dan pemahaman atas subyek hukum, obyek hukum, hubungan hukum, sumber hukum, serta hierarki peraturan menjadi dasar bagi manajer untuk membaca kewajiban yang mengikat perusahaannya. Hukum bisnis berakar pada hukum privat, tetapi dalam praktik bersifat campuran karena perizinan, pengawasan persaingan, dan pertanggungjawaban pidana korporasi menariknya ke ranah publik.</p>
<p>Alur kepatuhan perusahaan dapat disusun dalam lapis berurutan, yaitu legalitas badan usaha yang menentukan batas tanggung jawab pemilik dan pengurus, legalitas operasional yang kini berbasis risiko, legalitas transaksional yang bertumpu pada syarat sah perjanjian dan pengelolaan wanprestasi, serta legalitas aset yang menjamin keabsahan kepemilikan, peralihan, dan penjaminan. Di atasnya berdiri kepatuhan sektoral berupa hukum penanaman modal, persaingan usaha, perlindungan konsumen, serta pengaturan perbankan dan pasar modal, yang masing-masing memiliki otoritas pengawas dan bentuk sanksi tersendiri.</p>
<p>Implikasi manajerialnya, risiko hukum perlu dikelola sebagaimana risiko bisnis lain, yaitu diidentifikasi, diukur, dikendalikan, dan dipantau berkala. Kerangka eksposur risiko hukum, pengukuran konsentrasi pasar melalui CR4 dan HHI, perhitungan ganti rugi, serta rasio kecukupan modal merupakan alat yang dapat dipakai untuk menerjemahkan kewajiban hukum menjadi angka yang sebanding dengan sasaran kinerja. Dengan demikian, kepatuhan berhenti menjadi beban administratif dan berubah menjadi kemampuan bertransaksi, memperoleh pembiayaan, serta mempertahankan reputasi pada pasar yang semakin diawasi.</p>`
    },
    {
      no: "8.11",
      title: "Daftar Pustaka",
      body: `<p>Daftar pustaka berikut memuat sumber utama yang dipakai untuk menjaga akurasi pembahasan bab ini, meliputi modul mata kuliah, peraturan perundang-undangan Indonesia, dan literatur akademik standar bidang hukum bisnis.</p>
<ul>
<li>Fuady, M. (2019). <em>Pengantar Hukum Bisnis: Menata Bisnis Modern di Era Global</em>. Citra Aditya Bakti.</li>
<li>Harjono, D. K. (2019). <em>Hukum Penanaman Modal</em>. RajaGrafindo Persada.</li>
<li>Lubis, A. F. dkk. (2017). <em>Hukum Persaingan Usaha</em>. Edisi Kedua. Komisi Pengawas Persaingan Usaha.</li>
<li>Mertokusumo, S. (2010). <em>Mengenal Hukum: Suatu Pengantar</em>. Liberty.</li>
<li>Nasution, A. Z. (2002). <em>Hukum Perlindungan Konsumen: Suatu Pengantar</em>. Diadit Media.</li>
<li>Posner, R. A. (2014). <em>Economic Analysis of Law</em>. Edisi Kesembilan. Wolters Kluwer.</li>
<li>Pramono, N. (2013). <em>Hukum PT Go Public dan Pasar Modal</em>. Andi Offset.</li>
<li>Prodjodikoro, W. (2011). <em>Asas-asas Hukum Perjanjian</em>. Mandar Maju.</li>
<li>Shidarta. (2006). <em>Hukum Perlindungan Konsumen Indonesia</em>. Grasindo.</li>
<li>Subekti, R. (2005). <em>Hukum Perjanjian</em>. Intermasa.</li>
<li>Sutiyoso, B. (2008). <em>Penyelesaian Sengketa Bisnis</em>. Citra Media.</li>
<li>Usman, R. (2003). <em>Aspek-aspek Hukum Perbankan di Indonesia</em>. Gramedia Pustaka Utama.</li>
<li>Kitab Undang-Undang Hukum Perdata dan Kitab Undang-Undang Hukum Dagang.</li>
<li>Undang-Undang Nomor 5 Tahun 1999, Undang-Undang Nomor 8 Tahun 1999, Undang-Undang Nomor 25 Tahun 2007, Undang-Undang Nomor 40 Tahun 2007, serta peraturan pelaksananya.</li>
</ul>`
    }
  ]
};
