window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.gbe = window.MBA_BOOK.gbe || {};
window.MBA_BOOK.gbe[6] = {
  bab: 6,
  judul: "BAB 6 LINGKUNGAN DEMOGRAFI",
  sumber: "Modul GBE: deck Ibu Amelia (Google Drive) dan referensi akademik standar topik Lingkungan Demografi",
  lo: [
    "LO1 Mengenal dinamika data kependudukan serta variabel demografi pokok yang membentuk struktur penduduk suatu negara.",
    "LO2 Mendiskusikan faktor pendorong dan implikasi perubahan variabel demografi, khususnya fertilitas, mortalitas, migrasi, dan urbanisasi.",
    "LO3 Menjelaskan konsep bonus demografi, cara mengukurnya melalui rasio ketergantungan, serta prasyarat pemanfaatannya bagi perekonomian.",
    "LO4 Menganalisis dampak perubahan demografi terhadap pasokan tenaga kerja dan pola permintaan pasar.",
    "LO5 Merumuskan implikasi manajerial lingkungan demografi bagi pengambilan keputusan bisnis di Indonesia."
  ],
  sections: [
    {
      no: "6.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membahas lingkungan demografi sebagai salah satu dimensi lingkungan umum bisnis (<em>general business environment</em>) yang bekerja secara lambat namun pasti dalam membentuk peluang dan ancaman bagi perusahaan. Berbeda dengan variabel ekonomi yang berfluktuasi dalam hitungan bulan, variabel kependudukan berubah dalam hitungan dekade, sehingga sering kali luput dari perhatian manajer padahal konsekuensinya sangat besar terhadap pasar tenaga kerja dan pasar konsumen. Materi bab ini disusun berdasarkan modul perkuliahan GBE yang diampu oleh Ibu Amelia serta referensi akademik standar bidang demografi dan lingkungan bisnis. Setelah mengikuti sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<ul>
<li>Mengenal dinamika data kependudukan serta variabel demografi pokok yang membentuk struktur penduduk suatu negara.</li>
<li>Mendiskusikan faktor pendorong dan implikasi perubahan variabel demografi, khususnya fertilitas, mortalitas, migrasi, dan urbanisasi.</li>
<li>Menjelaskan konsep bonus demografi, cara mengukurnya melalui rasio ketergantungan, serta prasyarat pemanfaatannya bagi perekonomian.</li>
<li>Menganalisis dampak perubahan demografi terhadap pasokan tenaga kerja dan pola permintaan pasar.</li>
<li>Merumuskan implikasi manajerial lingkungan demografi bagi pengambilan keputusan bisnis di Indonesia.</li>
</ul>
<p>Untuk mencapai capaian tersebut, pembahasan diawali dengan konsep dasar dan sumber data kependudukan, dilanjutkan dengan struktur dan perubahan variabel demografi, kualitas sumber daya manusia, bonus demografi, serta dampaknya terhadap tenaga kerja dan permintaan. Bab ditutup dengan rangkuman dan daftar pustaka.</p>`
    },
    {
      no: "6.2",
      title: "Konsep Dasar Lingkungan Demografi",
      body: `<h5>6.2.1 Definisi dan Ruang Lingkup Demografi</h5>
<p>Kajian mengenai penduduk telah lama menjadi perhatian ilmu sosial karena penduduk merupakan subjek sekaligus objek pembangunan. Demografi didefinisikan sebagai ilmu yang mempelajari jumlah, persebaran, komposisi, dan perubahan penduduk beserta komponen penyebab perubahannya, yaitu kelahiran, kematian, dan perpindahan (Weeks, 2021). Menurut Adioetomo dan Samosir (2010), demografi menekankan analisis kuantitatif atas struktur dan proses penduduk, sedangkan studi kependudukan memperluasnya dengan menautkan variabel demografi pada variabel sosial, ekonomi, dan budaya. Dari kedua definisi tersebut dapat disimpulkan bahwa lingkungan demografi dalam konteks bisnis adalah keseluruhan karakteristik penduduk beserta dinamikanya yang memengaruhi ketersediaan sumber daya manusia dan potensi pasar suatu perusahaan.</p>
<p>Dalam manajemen pemasaran, lingkungan demografi ditempatkan sebagai kekuatan makro pertama yang wajib dipantau karena penduduk adalah pembentuk pasar (Kotler dan Keller, 2016). Ukuran pasar potensial, daya beli agregat, hingga preferensi konsumsi pada akhirnya berakar pada berapa banyak orang yang ada, di mana mereka tinggal, berapa usia mereka, dan bagaimana kualitas hidup mereka. Oleh karena itu, analisis lingkungan demografi bukan sekadar latihan statistik, melainkan fondasi bagi perencanaan strategis jangka panjang. Perusahaan yang memahami arah perubahan penduduk dapat mengantisipasi pergeseran pasar sepuluh sampai dua puluh tahun ke depan, jauh sebelum pesaingnya menyadari perubahan tersebut.</p>
<h5>6.2.2 Sumber Data Kependudukan</h5>
<p>Analisis demografi yang baik menuntut penguasaan atas sumber data kependudukan beserta keterbatasannya. Terdapat tiga sumber data utama, yaitu: sensus penduduk yang mencacah seluruh penduduk secara periodik, survei sampel seperti Survei Sosial Ekonomi Nasional (Susenas) dan Survei Angkatan Kerja Nasional (Sakernas), serta registrasi vital yang mencatat kelahiran, kematian, dan perpindahan secara terus menerus (Adioetomo dan Samosir, 2010). Di Indonesia, Badan Pusat Statistik merupakan produsen data resmi melalui Sensus Penduduk yang terakhir dilaksanakan pada tahun 2020, sedangkan pada tingkat global rujukan utama adalah publikasi <em>World Population Prospects</em> dari Divisi Kependudukan Perserikatan Bangsa-Bangsa (United Nations, 2019). Studi akademik, misalnya kajian elektrifikasi dan fertilitas di Indonesia, lazim menggabungkan beberapa sumber sekaligus seperti Susenas, Potensi Desa, dan <em>Demographic and Health Survey</em> untuk memperoleh gambaran yang utuh (Grimm, Sparrow dan Tasciotti, 2015).</p>
<p>Bagi manajer, kemampuan membaca data kependudukan memiliki nilai praktis yang tinggi karena proyeksi penduduk memungkinkan estimasi ukuran pasar masa depan, data ketenagakerjaan membantu perencanaan rekrutmen dan lokasi fasilitas, sedangkan data pengeluaran rumah tangga menjadi dasar segmentasi daya beli. Namun, proyeksi penduduk disusun dengan asumsi tertentu, misalnya varian medium dalam proyeksi Perserikatan Bangsa-Bangsa, sehingga penggunaannya harus disertai analisis sensitivitas. Dengan demikian, data demografi sebaiknya diperlakukan sebagai peta arah, bukan sebagai angka pasti yang bebas dari ketidakpastian.</p>`
    },
    {
      no: "6.3",
      title: "Struktur dan Perubahan Variabel Demografi",
      body: `<p>Struktur penduduk suatu negara dibentuk oleh interaksi tiga komponen dinamis, yaitu fertilitas, mortalitas, dan migrasi. Ketiganya menentukan jumlah, laju pertumbuhan, komposisi umur, dan sebaran geografis penduduk. Sub-bab ini menguraikan variabel tersebut satu per satu, dimulai dari ukuran agregat hingga komponen perubahannya, dengan menempatkan pengalaman Indonesia dalam perbandingan internasional. Ringkasan variabel dan indikatornya disajikan pada Tabel 6.1.</p>
<table class="bk-table">
<caption>Tabel 6.1 Variabel Demografi Pokok dan Indikator Pengukurannya</caption>
<thead><tr><th>Variabel</th><th>Indikator utama</th><th>Makna bagi bisnis</th></tr></thead>
<tbody>
<tr><td>Jumlah dan pertumbuhan</td><td>Jumlah penduduk, laju pertumbuhan tahunan (r)</td><td>Ukuran dan arah pertumbuhan pasar agregat</td></tr>
<tr><td>Sebaran dan kepadatan</td><td>Kepadatan per km persegi, tingkat urbanisasi</td><td>Pilihan lokasi, jaringan distribusi, pasar perkotaan</td></tr>
<tr><td>Struktur umur</td><td>Piramida penduduk, median umur, rasio ketergantungan</td><td>Segmen pasar dominan, pasokan tenaga kerja</td></tr>
<tr><td>Fertilitas</td><td>Angka kelahiran kasar, <em>total fertility rate</em> (TFR)</td><td>Pasar produk anak, ukuran angkatan kerja masa depan</td></tr>
<tr><td>Mortalitas dan kesehatan</td><td>Angka kematian bayi, umur harapan hidup</td><td>Pasar kesehatan, asuransi, produk lansia</td></tr>
<tr><td>Migrasi</td><td>Migrasi neto, arus urbanisasi</td><td>Ketersediaan tenaga kerja lokal, pertumbuhan kota</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Weeks (2021), Adioetomo dan Samosir (2010), dan modul GBE Ibu Amelia</td></tr></tfoot>
</table>
<h5>6.3.1 Jumlah, Pertumbuhan, dan Sebaran Penduduk</h5>
<p>Ukuran paling dasar dalam demografi adalah jumlah penduduk dan laju pertumbuhannya. Laju pertumbuhan penduduk lazim dihitung dengan model pertumbuhan eksponensial, yaitu r = (1/t) x ln(Pt/P0) x 100 persen, dengan P0 sebagai jumlah penduduk awal, Pt jumlah penduduk pada tahun ke-t, dan r laju pertumbuhan tahunan dalam persen. Rumus tersebut digunakan untuk membandingkan kecepatan pertumbuhan antarnegara dan untuk memproyeksikan penduduk masa depan melalui bentuk kebalikannya, Pt = P0 x e pangkat rt. Data Perserikatan Bangsa-Bangsa menunjukkan pola yang timpang, yaitu laju pertumbuhan tertinggi terkonsentrasi di Afrika Sub-Sahara dan sebagian Asia Selatan, sementara sejumlah negara Eropa Timur dan Asia Timur justru mengalami pertumbuhan negatif (United Nations, 2019). Ketimpangan tersebut menjadi perhatian pembangunan karena pertumbuhan penduduk tercepat justru terjadi di kawasan dengan produktivitas pertanian dan cakupan perlindungan sosial yang paling rendah.</p>
<p>Selain jumlah, sebaran penduduk juga menentukan konfigurasi pasar. Kepadatan penduduk dihitung sebagai jumlah penduduk dibagi luas wilayah dan di Indonesia variasinya sangat ekstrem, yaitu Pulau Jawa dihuni lebih dari separuh penduduk dengan kepadatan di beberapa provinsi melebihi seribu jiwa per kilometer persegi, sedangkan Kalimantan dan Papua sebagian besar berada di bawah tiga puluh jiwa per kilometer persegi (Badan Pusat Statistik, 2023). Fenomena global yang menyertainya adalah urbanisasi, yaitu diperkirakan sekitar enam puluh persen penduduk dunia akan tinggal di kawasan perkotaan pada tahun 2030 (United Nations, 2014). Bagi perusahaan, konsentrasi penduduk perkotaan menurunkan biaya distribusi per konsumen dan menciptakan pasar padat untuk ritel modern, transportasi daring, dan hunian vertikal. Di sisi lain, wilayah berpenduduk jarang menuntut model bisnis berbeda, misalnya distribusi berbasis agen dan pemanfaatan saluran digital untuk menjangkau konsumen yang tersebar.</p>
<h5>6.3.2 Struktur Umur dan Piramida Penduduk</h5>
<p>Komposisi penduduk menurut umur dan jenis kelamin lazim divisualisasikan dalam piramida penduduk. Piramida berbentuk segitiga lebar di bawah menandakan penduduk muda akibat fertilitas tinggi, bentuk granat atau lonceng menandakan transisi menuju penduduk usia kerja yang besar, sedangkan bentuk konstruktif yang menyempit di bawah menandakan penuaan penduduk (Weeks, 2021). Indikator turunannya adalah rasio ketergantungan (<em>dependency ratio</em>), yang dihitung dengan rumus: rasio ketergantungan = (penduduk umur 0-14 tahun + penduduk umur 65 tahun ke atas) dibagi penduduk umur 15-64 tahun, dikalikan seratus. Semakin rendah rasio tersebut, semakin ringan beban ekonomi yang ditanggung setiap penduduk usia produktif. Piramida penduduk Indonesia saat ini berbentuk cembung di kelompok usia muda dan dewasa awal, berbeda dengan Jepang yang piramidanya telah terbalik karena didominasi penduduk tua.</p>
<p>Struktur umur memiliki makna strategis karena setiap kelompok umur membawa pola konsumsi dan produksi yang berbeda. Penduduk usia sekolah membutuhkan layanan pendidikan, penduduk usia kerja menghasilkan pendapatan dan menabung, sedangkan penduduk lanjut usia membutuhkan layanan kesehatan dan jaminan pensiun. Oleh karena itu, pembacaan piramida penduduk memungkinkan manajer memperkirakan segmen mana yang akan membesar dan mengecil dalam dua dekade mendatang. Sebagai contoh, gelombang kelahiran besar hari ini akan menjadi gelombang permintaan perumahan pertama sekitar dua puluh lima tahun kemudian, suatu keteraturan yang sangat berguna bagi industri properti dan pembiayaan.</p>
<h5>6.3.3 Fertilitas dan Faktor Pendorong Perubahannya</h5>
<p>Fertilitas adalah komponen perubahan penduduk yang paling banyak dikaji karena paling responsif terhadap kebijakan dan perubahan sosial. Indikator utamanya adalah <em>total fertility rate</em> (TFR), yaitu rata-rata jumlah anak yang akan dilahirkan seorang perempuan sepanjang masa reproduksinya apabila pola fertilitas menurut umur tidak berubah (Weeks, 2021). TFR sekitar 2,1 disebut tingkat penggantian (<em>replacement level</em>) karena jumlah kelahiran tepat menggantikan generasi orang tuanya. TFR Indonesia menurun tajam dari 5,61 pada tahun 1961 menjadi sekitar 2,18 pada tahun 2022 berdasarkan hasil Sensus Penduduk 2020 dan proyeksinya (Badan Pusat Statistik, 2023). Penurunan tersebut merupakan bagian dari transisi demografi, yaitu perpindahan dari rezim kelahiran dan kematian tinggi menuju rezim kelahiran dan kematian rendah seiring modernisasi ekonomi (Lee, 2003).</p>
<p>Pengalaman berbagai kawasan menunjukkan keragaman jalur transisi fertilitas. Di Inggris, perubahan sosio-demografis tampak pada mengecilnya ukuran rumah tangga dan meningkatnya umur perkawinan pertama sejak dekade 1970-an (Social Issues Research Centre, 2008). Di Asia Timur, Jepang, Korea Selatan, dan Taiwan mengalami penurunan TFR hingga jauh di bawah tingkat penggantian yang disertai kenaikan rata-rata umur melahirkan, sehingga ketiganya kini menghadapi penyusutan angkatan kerja dan penuaan penduduk yang cepat. Sebaliknya, sebagian besar Afrika Sub-Sahara masih berada pada fase fertilitas tinggi. Faktor pendorong penurunan fertilitas mencakup program keluarga berencana, investasi pendidikan bagi perempuan, perluasan kesempatan kerja perempuan, serta transisi nilai dan norma keluarga dalam masyarakat, sebagaimana dirangkum dalam modul perkuliahan Ibu Amelia. Studi Grimm, Sparrow dan Tasciotti (2015) di Indonesia menambahkan bukti menarik bahwa akses listrik berasosiasi dengan penurunan angka kelahiran, antara lain melalui penyebaran informasi lewat media massa serta perubahan alokasi waktu rumah tangga, dengan temuan pendukung berupa kenaikan pemakaian kontrasepsi dari 27 persen pada 1980 menjadi 43 persen pada 2010 dan naiknya median umur kawin pertama perempuan dari 17 menjadi 20 tahun.</p>
<p>Pemerintah berbagai negara menempuh strategi yang beragam untuk mengelola pertumbuhan penduduk, yaitu: penyediaan alat kontrasepsi, pemanfaatan media massa untuk menyebarkan norma keluarga kecil, pendekatan budaya setempat, insentif finansial seperti keringanan pajak untuk biaya pengasuhan anak, serta pendekatan hukum (May, 2012). Perlu dicatat bahwa arah kebijakan dapat berbalik, yaitu negara yang dahulu menekan kelahiran kini justru memberikan insentif kelahiran ketika fertilitas jatuh terlalu rendah. Bagi dunia usaha, arah pergerakan TFR merupakan sinyal dini tentang ukuran pasar produk ibu dan anak, kebutuhan sekolah, hingga pasokan tenaga kerja dua dekade mendatang.</p>
<h5>6.3.4 Mortalitas dan Umur Harapan Hidup</h5>
<p>Komponen kedua adalah mortalitas, yang lazim diukur dengan angka kematian bayi dan umur harapan hidup saat lahir. Data global memperlihatkan kemajuan luar biasa, yaitu umur harapan hidup dunia yang pada periode 1950-1955 di banyak negara masih di bawah lima puluh tahun kini telah melampaui tujuh puluh tahun pada periode 2020-2025 (United Nations, 2019). Kemajuan tersebut didorong oleh perbaikan gizi, sanitasi, imunisasi, dan pelayanan kesehatan. Kombinasi umur harapan hidup yang meningkat dan fertilitas yang menurun menghasilkan rumah tangga yang lebih kecil dengan kehidupan yang lebih panjang, suatu perubahan mendasar dalam struktur permintaan masyarakat. Dengan demikian, mortalitas yang menurun bukan hanya indikator keberhasilan pembangunan, melainkan juga pembentuk pasar baru seperti layanan kesehatan lanjut usia, dana pensiun, dan asuransi jiwa.</p>
<h5>6.3.5 Migrasi dan Urbanisasi</h5>
<p>Komponen ketiga adalah migrasi, yaitu perpindahan penduduk yang melintasi batas wilayah untuk menetap. Migrasi internasional memengaruhi pasokan tenaga kerja dan arus remitansi, sedangkan migrasi internal, terutama urbanisasi, mengubah peta pasar domestik. Indonesia mengalami keduanya, yaitu penempatan pekerja migran ke luar negeri yang menghasilkan devisa remitansi, serta arus perpindahan desa ke kota yang menjadikan kawasan aglomerasi seperti Jabodetabek pusat pertumbuhan konsumsi nasional. Konsentrasi penduduk usia produktif di perkotaan mempercepat pembentukan kelas menengah dan adopsi teknologi digital. Namun, urbanisasi yang tidak disertai penyediaan infrastruktur memadai menimbulkan biaya kemacetan, permukiman kumuh, dan tekanan lingkungan yang pada akhirnya juga meningkatkan biaya operasi bisnis di perkotaan.</p>`
    },
    {
      no: "6.4",
      title: "Kualitas Sumber Daya Manusia sebagai Dimensi Demografi",
      body: `<p>Analisis lingkungan demografi tidak cukup berhenti pada kuantitas penduduk, melainkan harus mencakup kualitasnya. Kualitas sumber daya manusia lazim dipotret melalui tiga dimensi, yaitu kesehatan, pendidikan, dan standar hidup, sebagaimana tercermin dalam <em>Human Development Index</em> yang menggabungkan umur harapan hidup, lama sekolah, dan pendapatan per kapita (UNDP, 2020). Ketiga dimensi tersebut menentukan produktivitas tenaga kerja sekaligus kecanggihan permintaan konsumen. Negara dengan penduduk besar namun berkualitas rendah hanya menawarkan pasar berdaya beli terbatas dan tenaga kerja berketerampilan rendah, sedangkan penduduk yang sehat dan terdidik menjadi basis industri bernilai tambah tinggi.</p>
<p>Pada dimensi kesehatan, isu penting bagi negara berkembang adalah beban pembiayaan kesehatan yang ditanggung langsung oleh rumah tangga (<em>out-of-pocket payment</em>). Organisasi Kesehatan Dunia mencatat bahwa pengeluaran kesehatan langsung tersebut memperdalam kesenjangan kemiskinan, dengan beban relatif terbesar justru pada kelompok termiskin (WHO, 2017). Indonesia menunjukkan perbaikan bertahap, yaitu proporsi pengeluaran kesehatan yang bersumber dari kantong sendiri menurun dari sekitar 44,6 persen pada 2021 menjadi sekitar 38,2 persen pada 2023, seiring kepesertaan jaminan kesehatan yang meningkat dari 68,4 persen menjadi 72,4 persen penduduk pada periode yang sama (Badan Pusat Statistik, 2023). Perluasan Jaminan Kesehatan Nasional tersebut bukan hanya kebijakan sosial, melainkan juga pembentuk pasar besar bagi industri farmasi, rumah sakit, dan alat kesehatan karena permintaan yang semula tertahan menjadi permintaan efektif.</p>
<p>Pada dimensi pendidikan, kesenjangan kesempatan dimulai sejak usia dini dan berkorelasi dengan tingkat pendapatan. Kurva investasi modal manusia Heckman menunjukkan bahwa imbal hasil investasi pendidikan tertinggi diperoleh pada usia dini dan menurun pada jenjang berikutnya (Heckman, 2006). Data Indonesia memperlihatkan pola serupa, yaitu rata-rata lama sekolah penduduk umur lima belas tahun ke atas pada kelompok pengeluaran tertinggi melebihi sebelas tahun, sedangkan pada kelompok terbawah hanya sekitar tujuh tahun (Badan Pusat Statistik, 2023). Angka partisipasi sekolah juga menurun tajam pada kelompok umur 16-18 dan 19-24 tahun serta bervariasi antarprovinsi. Pengalaman kebijakan yang sering dirujuk adalah program Sekolah Dasar Instruksi Presiden (SD Inpres) 1973-1978 yang membangun sekitar 61 ribu sekolah dasar, dan terbukti meningkatkan partisipasi sekolah serta upah pekerja pada masa dewasanya (Duflo, 2001). Temuan tersebut menegaskan bahwa investasi pendidikan hari ini adalah kualitas angkatan kerja dua puluh tahun kemudian.</p>
<p>Pada dimensi standar hidup, proporsi penduduk dunia yang hidup dalam kemiskinan ekstrem menurun signifikan antara 1990 dan 2012, terutama berkat pertumbuhan Asia Timur, meskipun cakupan perlindungan sosial di negara berpendapatan rendah masih sangat terbatas (World Bank, 2016). Bagi manajer, ketiga dimensi kualitas tersebut memiliki dua sisi implikasi. Dari sisi pasokan, perusahaan yang beroperasi di wilayah dengan pendidikan rendah harus menyediakan pelatihan internal yang lebih intensif. Dari sisi permintaan, naiknya kualitas hidup menggeser konsumsi dari kebutuhan pokok menuju barang tahan lama, pendidikan, kesehatan, dan gaya hidup, sehingga peta segmen pasar terus bergerak mengikuti perbaikan kualitas sumber daya manusia.</p>`
    },
    {
      no: "6.5",
      title: "Bonus Demografi",
      body: `<p>Konsep sentral yang menghubungkan struktur umur dengan kinerja ekonomi adalah bonus demografi. Bloom, Canning dan Sevilla (2003) mendefinisikan <em>demographic dividend</em> sebagai percepatan pertumbuhan ekonomi yang dapat timbul ketika penurunan fertilitas mengubah struktur umur sehingga proporsi penduduk usia produktif meningkat relatif terhadap penduduk usia nonproduktif. Mekanismenya bekerja melalui beberapa jalur, yaitu bertambahnya pasokan tenaga kerja per kapita, meningkatnya tabungan nasional karena penduduk usia kerja menabung lebih banyak, serta membesarnya investasi pada modal manusia karena keluarga kecil mampu berinvestasi lebih besar per anak. Kondisi ketika rasio ketergantungan berada pada titik terendah sering disebut jendela peluang (<em>window of opportunity</em>) karena hanya terjadi satu kali dalam sejarah demografi suatu negara dan berlangsung terbatas.</p>
<p>Pengukuran bonus demografi dilakukan melalui rasio ketergantungan sebagaimana dirumuskan pada sub-bab 6.3.2. Suatu negara dikatakan menikmati bonus demografi apabila rasio ketergantungannya menurun dan berada di bawah kisaran lima puluh, yang berarti setiap seratus penduduk usia produktif menanggung kurang dari lima puluh penduduk nonproduktif. Cara menggunakannya dalam analisis bisnis cukup langsung, yaitu analis menghitung rasio tersebut dari data struktur umur, mengamati arah trennya dalam proyeksi penduduk, kemudian menandai periode ketika rasio mencapai titik terendah sebagai periode pasar tenaga kerja paling longgar dan pasar konsumen usia produktif paling besar. Untuk Indonesia, kajian World Bank (2014) memproyeksikan bonus demografi berlanjut hingga sekitar tahun 2030 sebelum berbalik arah ketika proporsi penduduk lanjut usia mulai menanjak, dengan jumlah penduduk usia kerja yang terus bertambah menuju kisaran dua ratus juta jiwa.</p>
<p>Hal yang perlu ditekankan adalah bahwa bonus demografi bersifat potensial, bukan otomatis. "The demographic dividend is not automatic" (Bloom, Canning dan Sevilla, 2003). Prasyarat pemanfaatannya mencakup lapangan kerja produktif yang cukup untuk menyerap angkatan kerja, kualitas pendidikan dan kesehatan yang memadai, kedalaman sektor keuangan untuk menyalurkan tabungan menjadi investasi, serta tata kelola yang baik. Apabila prasyarat tersebut gagal dipenuhi, jendela peluang justru berubah menjadi beban berupa pengangguran usia muda yang masif dan risiko terjebak pada tingkat pendapatan menengah (<em>middle income trap</em>), sebagaimana diingatkan dalam kajian World Bank (2014) mengenai Indonesia. Pengalaman Asia Timur menunjukkan sisi sebaliknya, yaitu Korea Selatan dan Taiwan berhasil mengonversi bonus demografinya menjadi industrialisasi berorientasi ekspor karena berinvestasi besar pada pendidikan sebelum jendela peluang terbuka.</p>
<p>Bagi pelaku usaha, bonus demografi Indonesia mengandung dua pesan strategis. Pertama, hingga sekitar 2030 pasar domestik akan digerakkan oleh penduduk usia produktif yang bekerja, berpendapatan, dan membentuk rumah tangga baru, sehingga permintaan perumahan pertama, kendaraan, pembiayaan konsumen, dan layanan digital berada pada fase ekspansi. Kedua, setelah jendela menutup, struktur pasar akan bergeser menuju penuaan sehingga perusahaan perlu menyiapkan portofolio produk untuk penduduk lanjut usia sejak sekarang. Dengan demikian, bonus demografi sebaiknya dibaca bukan sebagai jaminan pertumbuhan, melainkan sebagai jadwal perubahan struktur pasar yang menuntut penyesuaian strategi secara bertahap.</p>`
    },
    {
      no: "6.6",
      title: "Dampak Demografi terhadap Tenaga Kerja dan Permintaan",
      body: `<h5>6.6.1 Dampak terhadap Pasar Tenaga Kerja</h5>
<p>Dari sisi pasokan, struktur demografi menentukan jumlah dan komposisi angkatan kerja. Dua indikator pokok yang digunakan adalah tingkat partisipasi angkatan kerja (TPAK), yang dihitung sebagai jumlah angkatan kerja dibagi penduduk usia kerja dikalikan seratus persen, dan tingkat pengangguran terbuka (TPT), yang dihitung sebagai jumlah penganggur dibagi jumlah angkatan kerja dikalikan seratus persen (Badan Pusat Statistik, 2023). Kedua rumus tersebut digunakan bersama untuk membaca kesehatan pasar kerja, yaitu TPAK memotret seberapa besar penduduk usia kerja yang aktif secara ekonomi, sedangkan TPT memotret ketidakmampuan pasar menyerap mereka yang aktif mencari kerja. Data Sakernas menunjukkan pola yang konsisten dari tahun ke tahun, yaitu TPT tertinggi berada pada kelompok umur muda 15-24 tahun dan relatif tinggi pada lulusan sekolah menengah kejuruan, yang mengindikasikan persoalan ketidaksesuaian antara keluaran pendidikan dan kebutuhan industri (<em>skill mismatch</em>).</p>
<p>Struktur lapangan kerja Indonesia juga mencerminkan transformasi ekonomi yang belum tuntas, yaitu penyerapan tenaga kerja masih terpusat pada pertanian, perdagangan, dan industri pengolahan, dengan proporsi pekerja informal yang besar. Pasokan tenaga kerja muda yang melimpah menekan biaya tenaga kerja dan menguntungkan industri padat karya, namun kelangkaan tenaga terampil pada saat yang sama menaikkan premi gaji untuk talenta digital dan manajerial. Oleh karena itu, strategi sumber daya manusia perlu dibangun di atas data demografi, misalnya menempatkan fasilitas produksi di daerah dengan surplus angkatan kerja muda, membangun kemitraan dengan pendidikan vokasi, dan merancang jenjang karier yang mengakomodasi angkatan kerja lintas generasi. Di negara yang menua seperti Jepang, arah persoalannya berkebalikan, yaitu perusahaan bersaing memperebutkan pekerja yang jumlahnya menyusut sehingga otomatisasi dan perpanjangan usia pensiun menjadi keharusan.</p>
<h5>6.6.2 Dampak terhadap Permintaan dan Segmentasi Pasar</h5>
<p>Dari sisi permintaan, penduduk membentuk pasar melalui jumlah, daya beli, dan preferensinya. Kotler dan Keller (2016) menegaskan bahwa pemasar memantau lingkungan demografi terutama melalui ukuran dan laju pertumbuhan penduduk, distribusi umur, komposisi rumah tangga, sebaran geografis, serta bauran pendidikan dan etnis. Perubahan pada setiap dimensi tersebut menggeser komposisi permintaan agregat. Penurunan fertilitas mengecilkan pasar produk bayi namun menaikkan belanja per anak karena keluarga kecil berinvestasi lebih besar pada kualitas. Mengecilnya ukuran rumah tangga menumbuhkan permintaan hunian kompak, kemasan porsi kecil, dan layanan untuk lajang. Penuaan penduduk membesarkan pasar kesehatan, wisata lansia, dan produk keuangan purnakarya, sebagaimana telah terjadi di Jepang dan mulai tampak di Tiongkok.</p>
<p>Dalam konteks Indonesia, bonus demografi dan urbanisasi menghasilkan segmen kelas menengah muda perkotaan yang menjadi motor permintaan baru. Segmen inilah yang menopang pertumbuhan ekonomi digital Indonesia, misalnya ekspansi layanan superapp transportasi dan dagang elektronik yang bertumpu pada penduduk muda pengguna telepon pintar di kota besar. Contoh lain adalah industri properti dan pembiayaan yang membidik gelombang pembentukan rumah tangga baru melalui produk rumah tapak sederhana dan kredit pemilikan rumah subsidi di kota penyangga. Namun, pemasar juga harus mengantisipasi keragaman antarwilayah, yaitu provinsi dengan struktur penduduk muda seperti Nusa Tenggara Timur dan Papua menuntut strategi berbeda dari DI Yogyakarta yang paling cepat menua. Dengan demikian, segmentasi demografis di Indonesia perlu dilakukan pada tingkat provinsi atau kota, bukan hanya pada tingkat nasional.</p>
<h5>6.6.3 Implikasi Manajerial dan Kerangka Analisis</h5>
<p>Secara manajerial, analisis lingkungan demografi sebaiknya diintegrasikan ke dalam kerangka analisis lingkungan makro seperti PESTEL pada komponen sosial-demografis, kemudian diterjemahkan menjadi implikasi pada dua sisi, yaitu sisi pasokan sumber daya manusia dan sisi permintaan pasar. Prosedur praktisnya sebagai berikut: pertama, mengidentifikasi variabel demografi yang paling relevan bagi industri; kedua, mengumpulkan data dan proyeksinya dari sumber resmi; ketiga, menghitung indikator kunci seperti laju pertumbuhan, rasio ketergantungan, TPAK, dan TPT; keempat, menilai arah dan kecepatan perubahan; dan kelima, merumuskan respons strategi pada produk, pasar, lokasi, dan sumber daya manusia. Ringkasan keterkaitan perubahan demografi dan respons bisnis disajikan pada Tabel 6.2.</p>
<table class="bk-table">
<caption>Tabel 6.2 Perubahan Demografi Utama dan Implikasi Bisnisnya</caption>
<thead><tr><th>Perubahan demografi</th><th>Dampak tenaga kerja</th><th>Dampak permintaan</th><th>Contoh respons strategis</th></tr></thead>
<tbody>
<tr><td>Bonus demografi</td><td>Pasokan tenaga kerja muda melimpah</td><td>Ekspansi pasar usia produktif</td><td>Investasi kapasitas, produk rumah tangga baru</td></tr>
<tr><td>Penurunan fertilitas</td><td>Angkatan kerja masa depan mengecil</td><td>Pasar anak menyusut, belanja per anak naik</td><td>Produk premium anak, diversifikasi segmen</td></tr>
<tr><td>Penuaan penduduk</td><td>Kelangkaan pekerja, biaya pensiun naik</td><td>Pasar kesehatan dan lansia membesar</td><td>Otomatisasi, produk <em>silver economy</em></td></tr>
<tr><td>Urbanisasi</td><td>Konsentrasi talenta di kota</td><td>Pasar perkotaan padat dan digital</td><td>Ritel modern, layanan daring, hunian vertikal</td></tr>
<tr><td>Peningkatan pendidikan</td><td>Produktivitas dan ekspektasi karier naik</td><td>Permintaan produk bernilai tambah</td><td>Peningkatan mutu, merek, jenjang karier</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Kotler dan Keller (2016), Bloom, Canning dan Sevilla (2003), dan modul GBE Ibu Amelia</td></tr></tfoot>
</table>
<p>Kerangka pada Tabel 6.2 digunakan dengan cara membaca baris yang paling relevan bagi industri perusahaan, kemudian menguji apakah strategi yang berjalan telah konsisten dengan arah perubahan demografis pada kolom dampaknya. Perusahaan yang menyelaraskan strategi dengan arah demografi memperoleh keunggulan karena perubahan penduduk berlangsung gradual dan lebih dapat diprediksi daripada variabel makro lainnya, sedangkan mengabaikannya dapat berakibat fatal, misalnya membangun kapasitas besar untuk segmen yang sedang menyusut. Oleh karena itu, pemantauan lingkungan demografi selayaknya menjadi agenda rutin dalam perencanaan strategis tahunan perusahaan.</p>`
    },
    {
      no: "6.7",
      title: "Rangkuman",
      body: `<p>Lingkungan demografi merupakan dimensi lingkungan umum bisnis yang mempelajari jumlah, sebaran, komposisi, dan perubahan penduduk melalui tiga komponen pokok, yaitu fertilitas, mortalitas, dan migrasi. Dunia sedang mengalami perubahan demografis besar berupa perlambatan pertumbuhan penduduk yang timpang antarkawasan, urbanisasi yang menuju enam puluh persen penduduk dunia pada 2030, kenaikan umur harapan hidup, serta penurunan fertilitas hingga di bawah tingkat penggantian di banyak negara maju. Indonesia mengikuti jalur transisi demografi tersebut, yaitu TFR menurun dari 5,61 pada 1961 menjadi sekitar 2,18 pada 2022, didorong oleh program keluarga berencana, pendidikan perempuan, perluasan kesempatan kerja, transisi nilai budaya, serta faktor pendukung seperti elektrifikasi. Kualitas sumber daya manusia yang dipotret melalui kesehatan, pendidikan, dan standar hidup menentukan apakah kuantitas penduduk dapat menjadi kekuatan ekonomi.</p>
<p>Perubahan struktur umur menghadirkan bonus demografi, yaitu jendela peluang ketika rasio ketergantungan mencapai titik terendah, yang bagi Indonesia diproyeksikan berlangsung hingga sekitar 2030. Bonus tersebut bersifat potensial dan hanya terwujud apabila tersedia lapangan kerja produktif, pendidikan dan kesehatan yang bermutu, serta tata kelola yang baik; kegagalan memenuhinya berisiko menimbulkan pengangguran usia muda dan jebakan pendapatan menengah. Dari sisi tenaga kerja, demografi menentukan pasokan angkatan kerja yang diukur melalui TPAK dan TPT, sedangkan dari sisi permintaan, demografi membentuk ukuran dan komposisi pasar melalui jumlah penduduk, struktur umur, ukuran rumah tangga, dan sebaran geografis.</p>
<p>Bagi manajer, pesan utama bab ini adalah bahwa demografi bergerak lambat namun pasti, sehingga merupakan variabel lingkungan yang paling dapat diprediksi untuk perencanaan jangka panjang. Analisis demografi yang disiplin, mulai dari pembacaan data resmi hingga penerjemahannya menjadi strategi produk, pasar, lokasi, dan sumber daya manusia, memberikan keunggulan antisipatif yang sulit ditiru pesaing. Dengan demikian, lingkungan demografi selayaknya diperlakukan sebagai fondasi perencanaan strategis, bukan sekadar latar belakang statistik.</p>`
    },
    {
      no: "6.8",
      title: "Daftar Pustaka",
      body: `<p>Adioetomo, S. M. dan Samosir, O. B. (2010). <em>Dasar-Dasar Demografi</em>. Edisi 2. Salemba Empat.</p>
<p>Badan Pusat Statistik. (2023). <em>Statistik Indonesia 2023</em> dan <em>Profil Statistik Kesehatan 2023</em>. BPS.</p>
<p>Bloom, D. E., Canning, D. dan Sevilla, J. (2003). <em>The Demographic Dividend: A New Perspective on the Economic Consequences of Population Change</em>. RAND Corporation.</p>
<p>Duflo, E. (2001). Schooling and Labor Market Consequences of School Construction in Indonesia. <em>American Economic Review</em>, 91(4).</p>
<p>Grimm, M., Sparrow, R. dan Tasciotti, L. (2015). Does Electrification Spur the Fertility Transition? Evidence from Indonesia. <em>Demography</em>, 52(5).</p>
<p>Heckman, J. J. (2006). Skill Formation and the Economics of Investing in Disadvantaged Children. <em>Science</em>, 312(5782).</p>
<p>Kotler, P. dan Keller, K. L. (2016). <em>Marketing Management</em>. Edisi 15. Pearson.</p>
<p>Lee, R. (2003). The Demographic Transition: Three Centuries of Fundamental Change. <em>Journal of Economic Perspectives</em>, 17(4).</p>
<p>May, J. F. (2012). <em>World Population Policies: Their Origin, Evolution, and Impact</em>. Springer.</p>
<p>Social Issues Research Centre. (2008). <em>Childhood and Family Life: Socio-Demographic Changes</em>. SIRC.</p>
<p>UNDP. (2020). <em>Human Development Report 2020</em>. United Nations Development Programme.</p>
<p>United Nations. (2014). <em>World Urbanization Prospects: The 2014 Revision</em>. UN DESA Population Division.</p>
<p>United Nations. (2019). <em>World Population Prospects 2019</em>. UN DESA Population Division.</p>
<p>Weeks, J. R. (2021). <em>Population: An Introduction to Concepts and Issues</em>. Edisi 13. Cengage.</p>
<p>WHO. (2017). <em>World Health Statistics 2017</em>. World Health Organization.</p>
<p>World Bank. (2014). <em>Indonesia: Avoiding the Trap. Development Policy Review 2014</em>. World Bank.</p>
<p>World Bank. (2016). <em>World Development Indicators 2016</em>. World Bank.</p>
<p>Modul perkuliahan: Maika, A. <em>General Business Environment: Demographical Environment</em>. Deck perkuliahan GBE (Google Drive).</p>`
    }
  ]
};
