window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.gbe = window.MBA_BOOK.gbe || {};
window.MBA_BOOK.gbe[7] = {
  bab: 7,
  judul: "LINGKUNGAN POLITIK NASIONAL DAN INTERNASIONAL",
  sumber: "Modul GBE: deck Hempri Suyatna (Google Drive) dan referensi akademik standar topik Lingkungan Politik Nasional dan Internasional",
  lo: [
    "LO1 Menjelaskan mengapa lingkungan politik merupakan sumber ketidakpastian yang harus diperhitungkan dalam pengambilan keputusan bisnis.",
    "LO2 Menguraikan fungsi negara dalam perekonomian serta relasi antara lembaga eksekutif, legislatif, dan yudikatif beserta implikasinya bagi kepastian regulasi.",
    "LO3 Menganalisis hubungan antara stabilitas politik, kualitas demokrasi, patronase, dan klientelisme dengan iklim usaha, khususnya dalam konteks Indonesia.",
    "LO4 Menjelaskan dinamika lingkungan politik internasional, globalisasi, dan geopolitik dunia yang memengaruhi strategi perusahaan.",
    "LO5 Mengidentifikasi jenis risiko politik bagi bisnis serta menerapkan kerangka penilaian dan strategi mitigasi risiko politik."
  ],
  sections: [
    {
      no: "7.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi kelima mata kuliah <em>General Business Environment</em> membahas lingkungan politik nasional dan internasional sebagai salah satu dimensi lingkungan makro yang paling menentukan bagi kelangsungan usaha. Keputusan bisnis tidak pernah diambil dalam ruang hampa karena setiap perusahaan beroperasi di dalam suatu tatanan politik yang menetapkan aturan main, memberikan perlindungan, sekaligus dapat menimbulkan gangguan. Oleh karena itu, pemahaman yang utuh mengenai cara kerja negara, dinamika demokrasi, relasi antarlembaga, serta pergeseran geopolitik dunia merupakan kompetensi dasar bagi seorang manajer.</p>
<p>Setelah mengikuti sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p>Pertama, menjelaskan alasan lingkungan politik menjadi sumber ketidakpastian yang wajib diperhitungkan dalam pengambilan keputusan bisnis. Kedua, menguraikan fungsi negara dalam perekonomian serta relasi eksekutif, legislatif, dan yudikatif beserta implikasinya bagi kepastian hukum dan regulasi. Ketiga, menganalisis keterkaitan antara stabilitas politik, kualitas demokrasi, patronase, dan klientelisme dengan iklim usaha di Indonesia. Keempat, menjelaskan dinamika globalisasi dan geopolitik dunia yang membentuk lingkungan bisnis internasional. Kelima, mengidentifikasi jenis risiko politik serta merumuskan strategi penilaian dan mitigasinya pada tingkat perusahaan.</p>`
    },
    {
      no: "7.2",
      title: "Ketidakpastian Politik dan Pengambilan Keputusan Bisnis",
      body: `<p>Titik tolak pembahasan lingkungan politik adalah kenyataan bahwa bisnis merupakan usaha yang penuh risiko. Ilmu ekonomi konvensional sering menyederhanakan persoalan melalui asumsi <em>ceteris paribus</em>, yaitu anggapan bahwa variabel lain di luar model dianggap tetap. Dalam praktik pengambilan keputusan, asumsi tersebut tidak dapat dipertahankan karena keputusan bisnis dipengaruhi oleh berbagai peristiwa sosial, politik, hukum, dan keamanan yang bergerak serentak (Suyatna, modul GBE). Dengan demikian, pengambil keputusan dituntut mempertimbangkan banyak dimensi kehidupan manusia, baik yang bersifat fisik maupun sosial, dan ketidakpastian itulah yang menjadi sumber utama kesulitan dalam manajemen.</p>
<p>Tantangan yang bersumber dari lingkungan politik dan hukum dapat dikelompokkan ke dalam beberapa bentuk, yaitu: serangan kriminal, ketidakstabilan politik, gugatan atau tantangan hukum, dan gejolak ekonomi yang dipicu oleh keputusan politik. Setiap bentuk tantangan tersebut membawa dua jenis konsekuensi bagi perusahaan, yakni risiko kehilangan nyawa bagi personel dan risiko kerugian finansial bagi organisasi. Sebagai contoh, kerusuhan sosial dapat menghentikan operasi pabrik, sementara perubahan mendadak kebijakan fiskal dapat menggerus profitabilitas dalam waktu singkat. Oleh karena itu, analisis lingkungan politik bukan kegiatan pelengkap, melainkan bagian integral dari perumusan strategi.</p>
<p>Lingkungan politik lazim dibedakan menjadi dua lapis, yaitu politik domestik dan politik internasional. Politik domestik mencakup struktur negara, relasi antarlembaga, sistem kepartaian, dan kualitas demokrasi di negara tempat perusahaan beroperasi. Di sisi lain, politik internasional mencakup relasi antarnegara, lembaga multilateral, rezim perdagangan, dan konflik geopolitik yang melintasi batas negara. Kondisi ideal bagi dunia usaha adalah keberadaan negara bangsa yang kuat dengan pemerintahan yang berfungsi baik, karena kombinasi tersebut menghasilkan ketertiban, kepastian hukum, dan prediktabilitas kebijakan. Sebaliknya, negara yang lemah atau gagal menimbulkan biaya transaksi tinggi karena perusahaan harus menyediakan sendiri keamanan dan penegakan kontrak yang semestinya menjadi tugas negara.</p>`
    },
    {
      no: "7.3",
      title: "Negara dan Lingkungan Politik Domestik",
      body: `<p>Pemahaman terhadap lingkungan politik domestik harus dimulai dari konsep negara. Menurut Weber sebagaimana dikutip Heywood (2011), negara adalah organisasi yang memonopoli penggunaan kekerasan yang sah di dalam suatu wilayah tertentu. Dari definisi tersebut dapat disimpulkan bahwa negara merupakan satu-satunya aktor yang berwenang menetapkan dan menegakkan aturan main bagi seluruh aktivitas masyarakat, termasuk aktivitas ekonomi. Bagi dunia usaha, tiga fungsi pokok negara yang paling relevan adalah stabilisasi, regulasi, dan redistribusi. Fungsi stabilisasi diwujudkan melalui layanan keamanan internal dan eksternal serta pengelolaan makroekonomi; fungsi regulasi diwujudkan melalui penetapan aturan bagi kegiatan ekonomi; dan fungsi redistribusi diwujudkan melalui perpajakan dan kebijakan anggaran.</p>
<h5>5.3.1 Pembentukan Negara dan Sumber Legitimasi</h5>
<p>Kapasitas negara modern tidak terbentuk seketika, melainkan melalui empat tahap sejarah yang sekaligus menjadi sumber legitimasinya. Tahap pertama adalah pembentukan negara (<em>state formation</em>), yaitu proses ketika elite penguasa mengonsolidasikan suatu wilayah dengan kekuatan militer dan sumber daya ekonomi, kemudian membangun institusi seperti tentara, kepolisian, dan pengadilan untuk menegakkan ketertiban. Tahap kedua adalah pembangunan bangsa (<em>nation building</em>), yaitu penetapan standar bersama berupa bahasa, pendidikan, mata uang, serta satuan ukur di seluruh wilayah. Tahap ketiga adalah demokratisasi, yaitu terbukanya akses massa rakyat terhadap aparat dan proses pemerintahan. Tahap keempat adalah pembentukan negara kesejahteraan, yaitu ketika negara mendukung pemerataan, solidaritas nasional, dan etika kesetaraan (Suyatna, modul GBE).</p>
<p>Keempat tahap tersebut memiliki makna manajerial yang nyata. Perusahaan yang berekspansi ke suatu negara perlu menilai sampai tahap mana proses pembangunan negara di wilayah tersebut telah berlangsung. Negara yang belum menyelesaikan konsolidasi keamanan akan menyulitkan perlindungan aset, sedangkan negara yang belum menuntaskan pembangunan bangsa berpotensi mengalami konflik identitas yang mengganggu pasar. Dengan demikian, analisis kelembagaan negara merupakan langkah awal dalam penilaian daya tarik suatu pasar.</p>
<h5>5.3.2 Spektrum Fungsi Negara dalam Perekonomian</h5>
<p>World Bank (1997) dalam <em>World Development Report</em> menyusun peta fungsi negara berdasarkan dua sumbu, yaitu mengatasi kegagalan pasar (<em>market failure</em>) dan memperbaiki pemerataan (<em>equity</em>), dengan tiga tingkatan intensitas yang bergerak dari fungsi minimal, fungsi menengah, hingga fungsi aktivis. Kerangka ini bermanfaat bagi manajer untuk membaca seberapa jauh pemerintah suatu negara lazim melakukan intervensi terhadap pasar, sehingga perusahaan dapat mengantisipasi arah regulasi. Sintesis kerangka tersebut disajikan pada tabel berikut.</p>
<table class="bk-table"><caption>Tabel 5.1 Spektrum Fungsi Negara dalam Perekonomian</caption>
<thead><tr><th>Tingkat Fungsi</th><th>Mengatasi Kegagalan Pasar</th><th>Memperbaiki Pemerataan</th></tr></thead>
<tbody>
<tr><td>Minimal</td><td>Penyediaan barang publik murni: pertahanan, hukum dan ketertiban, hak milik, manajemen makroekonomi, kesehatan masyarakat</td><td>Perlindungan kelompok miskin: program antikemiskinan dan bantuan bencana</td></tr>
<tr><td>Menengah</td><td>Penanganan eksternalitas (pendidikan dasar, perlindungan lingkungan), regulasi monopoli (utilitas, antimonopoli), serta koreksi informasi tidak sempurna (regulasi keuangan, asuransi, perlindungan konsumen)</td><td>Penyediaan asuransi sosial: pensiun redistributif, tunjangan keluarga, asuransi pengangguran</td></tr>
<tr><td>Aktivis</td><td>Koordinasi kegiatan swasta: pengembangan pasar dan inisiatif klaster industri</td><td>Redistribusi aset</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari World Bank (1997)</td></tr></tfoot></table>
<p>Cara menggunakan kerangka ini adalah dengan memetakan kebijakan aktual suatu pemerintah ke dalam sel tabel, kemudian menilai konsistensinya. Negara yang berambisi menjalankan fungsi aktivis tanpa kapasitas birokrasi yang memadai cenderung menghasilkan regulasi yang berubah-ubah dan rawan penyalahgunaan. Sebaliknya, negara yang membatasi diri pada fungsi minimal tetapi menjalankannya dengan konsisten sering kali lebih ramah bagi investasi jangka panjang. Dalam konteks Indonesia, kehadiran negara pada fungsi aktivis terlihat pada kebijakan hilirisasi mineral yang mewajibkan pengolahan di dalam negeri, suatu intervensi yang membuka peluang investasi smelter sekaligus menimbulkan sengketa dagang di Organisasi Perdagangan Dunia.</p>`
    },
    {
      no: "7.4",
      title: "Relasi Eksekutif, Legislatif, dan Yudikatif",
      body: `<p>Struktur kekuasaan negara modern dibangun di atas doktrin pemisahan kekuasaan yang dirumuskan Montesquieu, yaitu pembagian kekuasaan negara ke dalam cabang eksekutif, legislatif, dan yudikatif. Menurut Heywood (2011), pemisahan kekuasaan yang disertai mekanisme saling kontrol dan saling imbang (<em>checks and balances</em>) bertujuan mencegah pemusatan kekuasaan pada satu tangan. Eksekutif menjalankan pemerintahan dan mengeksekusi undang-undang, legislatif membentuk undang-undang dan mengawasi pemerintah, sedangkan yudikatif menafsirkan hukum dan mengadili sengketa. Bagi dunia usaha, kualitas relasi ketiga cabang tersebut menentukan tiga hal pokok, yaitu prediktabilitas pembentukan regulasi, konsistensi pelaksanaan kebijakan, dan keandalan penyelesaian sengketa.</p>
<p>Relasi eksekutif dan legislatif berbeda menurut sistem pemerintahan. Dalam sistem presidensial seperti Indonesia dan Amerika Serikat, presiden dipilih terpisah dari parlemen sehingga keduanya memiliki legitimasi sendiri; kondisi ini berpotensi menimbulkan kebuntuan (<em>gridlock</em>) apabila presiden tidak menguasai mayoritas parlemen, namun juga menghasilkan stabilitas masa jabatan. Dalam sistem parlementer, eksekutif lahir dari dan bertanggung jawab kepada parlemen sehingga pembuatan undang-undang lebih cepat, tetapi pemerintahan dapat jatuh sewaktu-waktu melalui mosi tidak percaya. Oleh karena itu, manajer yang menilai suatu negara perlu memeriksa konfigurasi koalisi politik, karena koalisi yang terlalu gemuk di sistem presidensial dapat melemahkan fungsi pengawasan legislatif, sedangkan koalisi rapuh di sistem parlementer dapat memicu pergantian kebijakan yang cepat.</p>
<p>Cabang yudikatif memiliki arti khusus bagi bisnis karena independensi peradilan merupakan penjamin akhir hak milik dan kepastian kontrak. North (1990) menegaskan bahwa institusi yang menegakkan hak milik secara kredibel merupakan penentu utama kinerja ekonomi jangka panjang. Peradilan yang dapat dipengaruhi oleh kekuasaan atau uang akan menaikkan premi risiko investasi karena investor tidak yakin kontraknya dapat ditegakkan. Dalam konteks Indonesia, mekanisme <em>checks and balances</em> dapat diamati pada proses legislasi Undang-Undang Cipta Kerja: pemerintah dan Dewan Perwakilan Rakyat mengesahkan undang-undang tersebut dengan metode omnibus untuk menyederhanakan perizinan, kemudian Mahkamah Konstitusi menyatakan pembentukannya inkonstitusional bersyarat dan memerintahkan perbaikan. Peristiwa ini memperlihatkan bahwa yudikatif mampu mengoreksi produk eksekutif dan legislatif, namun bagi pelaku usaha episode tersebut juga menghadirkan ketidakpastian regulasi selama masa perbaikan.</p>
<p>Selain relasi horizontal antarcabang, terdapat relasi vertikal antara pemerintah pusat dan daerah. Desentralisasi yang dijalankan Indonesia sejak tahun 2001 memindahkan sebagian kewenangan perizinan dan pungutan ke pemerintah daerah, sehingga perusahaan berhadapan dengan banyak titik regulasi. Dengan demikian, analisis lingkungan politik yang baik harus memetakan seluruh simpul kekuasaan yang relevan bagi operasi perusahaan, mulai dari kementerian teknis, parlemen nasional, pemerintah daerah, hingga lembaga peradilan, kemudian menilai arah kepentingan masing-masing simpul terhadap industri yang digeluti.</p>`
    },
    {
      no: "7.5",
      title: "Stabilitas Politik, Kualitas Demokrasi, dan Regulasi",
      body: `<p>Stabilitas politik adalah kondisi ketika pergantian kekuasaan dan pembuatan kebijakan berlangsung menurut aturan yang disepakati tanpa kekerasan dan tanpa perubahan yang mendadak. Stabilitas tidak identik dengan pemerintahan yang tidak pernah berganti; yang dibutuhkan dunia usaha adalah prediktabilitas prosedur. Kualitas demokrasi menjadi ukuran penting karena demokrasi yang sehat menyediakan mekanisme koreksi kebijakan yang damai, kebebasan informasi yang menurunkan asimetri informasi pasar, serta perlindungan hukum yang setara bagi pelaku usaha.</p>
<h5>5.5.1 Mengukur Kualitas Demokrasi</h5>
<p>Terdapat dua instrumen pengukuran yang lazim dirujuk. Pertama, Indeks Demokrasi Indonesia (IDI) yang disusun Badan Pusat Statistik mengukur aspek kebebasan, kesetaraan, dan kapasitas lembaga demokrasi; capaian IDI tahun 2022 sebesar 80,41 kemudian menurun menjadi 79,51 pada tahun 2023 (Suyatna, modul GBE). Kedua, Indeks Demokrasi dari <em>Economist Intelligence Unit</em> (EIU) yang mengelompokkan negara menjadi demokrasi penuh (skor di atas 8), demokrasi cacat (di atas 6 sampai 8), rezim hibrida (di atas 4 sampai 6), dan rezim otoriter (0 sampai 4). Indonesia memperoleh skor 6,71 pada tahun 2022 dan 6,53 pada tahun 2023 sehingga tergolong demokrasi cacat (<em>flawed democracy</em>), dengan kelemahan paling dalam pada budaya politik dan kebebasan sipil, sementara negara dengan skor tertinggi adalah Norwegia, Selandia Baru, dan Islandia (EIU, 2023). Bagi manajer, indeks semacam ini digunakan sebagai indikator dini: penurunan skor kebebasan sipil dan budaya politik biasanya mendahului kebijakan yang lebih tertutup dan meningkatnya politisasi regulasi.</p>
<p>Levitsky dan Ziblatt (2019) dalam karya <em>How Democracies Die</em> mengingatkan bahwa kemunduran demokrasi masa kini jarang terjadi melalui kudeta, melainkan melalui pelemahan bertahap norma toleransi dan kesabaran institusional oleh pemimpin yang terpilih secara sah. Dari perspektif bisnis, gejala pelemahan tersebut perlu diwaspadai karena lembaga negara yang berubah menjadi formalitas belaka akan kehilangan kemampuannya menjamin kesetaraan pelaku usaha di hadapan hukum, sehingga persaingan bergeser dari kompetisi pasar menuju kompetisi kedekatan dengan kekuasaan.</p>
<h5>5.5.2 Patronase, Klientelisme, dan Politik Biaya Tinggi</h5>
<p>Kualitas regulasi juga ditentukan oleh cara politik dibiayai. Menurut Aspinall dan Berenschot (2019), patronase adalah pemberian materi atau keuntungan oleh politisi kepada pemilih atau pendukung untuk memperoleh dukungan politik, sedangkan klientelisme adalah relasi kekuasaan yang mempertukarkan dukungan politik dengan imbalan yang bersifat personal dan berkelanjutan. Pola patronase di Indonesia muncul dalam beberapa bentuk, yaitu: pembelian suara, pemberian pribadi, pelayanan dan aktivitas, barang kelompok (<em>club goods</em>), serta proyek gentong babi (<em>pork barrel</em>). Adapun mesin klientelisme bekerja melalui tim sukses, jaringan sosial, dan partai politik. Praktik tersebut melahirkan politik biaya tinggi yang bersifat patrimonialistik, yaitu memperlakukan urusan publik seolah urusan pribadi, dan klientelistik, yaitu memperlakukan warga negara seolah klien (Suyatna, modul GBE).</p>
<p>Implikasi manajerialnya serius. Politik biaya tinggi mendorong pejabat terpilih mencari pengembalian investasi politik melalui jual beli fasilitas, izin, dan proyek, sehingga perusahaan menghadapi pungutan informal dan persaingan yang tidak setara. Selain itu, partai yang oligarkis dan kehilangan ideologi menghasilkan kebijakan yang bersifat transaksional, misalnya melalui pembagian proyek, sumbangan organisasi, dan <em>success fee</em>. Perusahaan yang menolak terlibat dalam relasi semacam ini perlu membangun keunggulan kepatuhan, sementara perusahaan yang terlibat menghadapi risiko hukum antikorupsi, termasuk jangkauan ekstrateritorial <em>Foreign Corrupt Practices Act</em> Amerika Serikat dan <em>UK Bribery Act</em>.</p>
<h5>5.5.3 Pelajaran dari Studi Relasi Bisnis dan Politik di Indonesia</h5>
<p>Sejumlah studi klasik menunjukkan betapa eratnya jalinan bisnis dan politik di Indonesia. Muhaimin meneliti kebijakan ekonomi Indonesia periode 1950 sampai 1980 dan menemukan bahwa tiga sistem politik yang berbeda, yakni demokrasi parlementer, demokrasi terpimpin, dan Orde Baru, sama-sama melahirkan pengusaha klien, yaitu pengusaha yang menggantungkan usahanya pada penguasa; Program Benteng yang semula dimaksudkan melindungi pengusaha pribumi pada praktiknya berubah menjadi jual beli fasilitas antara birokrasi dan pendukungnya (Suyatna, modul GBE). Robison (1986) menyimpulkan bahwa kelompok kapitalis Indonesia bukan borjuasi independen, melainkan pejabat negara, perwira militer, keluarga, kerabat, dan pedagang Tionghoa yang dekat dengan pejabat, yang tumbuh melalui monopoli, kontrak, dan konsesi proyek pembangunan. MacIntyre (1991) memperlihatkan bahwa kelompok kepentingan pengusaha mampu memengaruhi kebijakan pada industri tekstil, farmasi, dan asuransi, sedangkan Chalmers (1996) menunjukkan bahwa kebijakan industri otomotif rentan terhadap tarik-menarik antara korporasi transnasional, pengambil kebijakan negara, dan borjuasi lokal.</p>
<p>Studi pascareformasi memperlihatkan kesinambungan pola tersebut. Transisi demokrasi dimulai ketika Presiden Suharto mengundurkan diri pada Mei 1998 di tengah krisis ekonomi, dilanjutkan liberalisasi politik oleh Presiden Habibie melalui kebebasan pers, pembebasan tahanan politik, dan pemilu 1999. Namun, Hadiz (2005) menemukan bahwa desentralisasi tidak serta-merta menguatkan demokrasi karena dominasi elite lama tetap berlangsung, bahkan desentralisasi membuka ruang korupsi, politik uang, dan konsolidasi kekuatan preman di tingkat lokal. Hidayat (2004; 2009) mendokumentasikan praktik <em>shadow state</em> di Provinsi Banten, tempat pengusaha jawara yang berjasa memenangkan kepala daerah memperoleh imbalan proyek melalui tender yang formalistik, lobi informal, suap, dan intimidasi. Suyatna (2012) menemukan bahwa kebijakan industri kecil pada era desentralisasi berubah menjadi arena pertarungan elite lokal, sehingga pergeseran dari otoritarianisme menuju demokrasi tidak otomatis memperbaiki ekonomi rakyat. Dari rangkaian studi tersebut dapat disimpulkan bahwa perubahan rezim tidak dengan sendirinya mengubah basis material kekuasaan, sehingga analisis lingkungan politik harus menembus struktur formal dan membaca jaringan kepentingan informal yang sesungguhnya bekerja.</p>`
    },
    {
      no: "7.6",
      title: "Lingkungan Politik Internasional dan Geopolitik Dunia",
      body: `<p>Lingkungan politik internasional dibentuk oleh rangkaian peristiwa transformatif yang mengubah profil lingkungan bisnis global, antara lain berakhirnya Perang Dingin, serangan terorisme 11 September 2001, krisis keuangan global 2008, hingga pandemi dan perang di Eropa Timur. Menurut Rugman dan Collinson (2009), profil lingkungan bisnis global yang berubah ditandai oleh lima kekuatan, yaitu: liberalisasi perdagangan, perkembangan teknologi dan inovasi, perubahan sikap terhadap perusahaan multinasional, terorisme internasional, dan globalisasi. Kelima kekuatan tersebut saling berkaitan dan menentukan pilihan lokasi, moda masuk pasar, serta konfigurasi rantai pasok perusahaan.</p>
<h5>5.6.1 Globalisasi dan Dimensinya</h5>
<p>Menurut Hodgetts, Luthans dan Doh (2006), globalisasi adalah "proses integrasi sosial, politik, ekonomi, budaya, dan teknologi di antara negara-negara di seluruh dunia". Held, McGrew, Goldblatt dan Perraton (1999) menekankan dimensi politiknya, yaitu perluasan kekuasaan dan aktivitas politik melampaui batas negara bangsa modern, sedangkan Steger (2003) menekankan intensifikasi dan perluasan relasi ekonomi serta arus budaya lintas dunia. Dari definisi tersebut dapat disimpulkan bahwa globalisasi merupakan proses multidimensi yang menghubungkan negara melalui jalur politik, ekonomi, dan budaya secara serentak, bukan sekadar peningkatan perdagangan internasional.</p>
<p>Pada dimensi politik, globalisasi menantang prinsip kedaulatan negara melalui menguatnya organisasi antarpemerintah, organisasi nonpemerintah internasional, kelompok penekan transnasional, serta tata kelola regional dan global; masalah global seperti terorisme dan kerusakan lingkungan turut mengaburkan batas antara urusan domestik dan internasional (Held et al., 1999). Pada dimensi ekonomi, globalisasi diukur dari intensitas, jangkauan, dan kecepatan interaksi ekonomi dunia mulai dari perdagangan, produksi, keuangan, hingga migrasi, dengan korporasi transnasional, lembaga ekonomi internasional, dan sistem perdagangan regional sebagai aktornya (McGrew, 2005). Pada dimensi budaya, terjadi perdebatan antara tesis homogenisasi budaya populer yang sering disebut Amerikanisasi dan tesis glokalisasi, yaitu adaptasi produk global terhadap selera lokal. Praktik glokalisasi dapat diamati di Indonesia, misalnya jaringan restoran cepat saji global yang menyajikan menu nasi dan ayam goreng sesuai preferensi konsumen lokal. Adapun kekuatan yang menopang keberlanjutan globalisasi meliputi liberalisasi kebijakan, peningkatan efisiensi bisnis, perluasan akses pasar, dan peningkatan arus barang, jasa, serta manusia.</p>
<h5>5.6.2 Geopolitik Dunia Kontemporer</h5>
<p>Geopolitik adalah studi tentang pengaruh faktor geografi terhadap politik antarnegara, khususnya persaingan kekuasaan atas wilayah, sumber daya, dan jalur perdagangan. Setelah tiga dekade hiperglobalisasi, dunia memasuki fase rivalitas kekuatan besar yang ditandai persaingan strategis Amerika Serikat dan Tiongkok, perang Rusia dan Ukraina beserta rezim sanksi ekonominya, serta ketegangan di kawasan Indo Pasifik. Konsekuensinya, kebijakan ekonomi semakin tunduk pada pertimbangan keamanan: muncul praktik <em>decoupling</em> dan <em>de-risking</em> rantai pasok, <em>friend-shoring</em> atau pemindahan produksi ke negara sahabat, pengendalian ekspor teknologi strategis seperti semikonduktor, dan penapisan investasi asing. Fenomena ini sering disebut fragmentasi geoekonomi, yaitu berbaliknya integrasi ekonomi dunia karena alasan politik.</p>
<p>Bagi perusahaan, geopolitik mengubah kalkulus strategi dalam tiga cara. Pertama, pilihan lokasi tidak lagi semata mengikuti efisiensi biaya, tetapi juga keselarasan blok politik. Kedua, kepatuhan terhadap sanksi dan pengendalian ekspor menjadi fungsi manajemen risiko tersendiri karena pelanggarannya berakibat denda besar dan penutupan akses pasar. Ketiga, negara berkembang seperti Indonesia memperoleh peluang dari strategi diversifikasi rantai pasok, misalnya relokasi sebagian manufaktur elektronik dari Tiongkok ke Asia Tenggara, sekaligus menghadapi tekanan untuk memihak dalam persaingan blok. Politik luar negeri Indonesia yang bebas aktif memberikan ruang bagi perusahaan nasional untuk berdagang dengan berbagai blok, namun manajer tetap harus memantau daftar sanksi dan aturan kandungan teknologi ketika bermitra lintas blok.</p>
<h5>5.6.3 Keamanan Global, Terorisme, dan Sikap terhadap Perusahaan Multinasional</h5>
<p>Menurut Heywood (2011), terorisme adalah bentuk kekerasan politik yang berupaya mencapai tujuannya dengan menciptakan iklim ketakutan dan kecemasan. Konsep ini bersifat problematik karena penilaian atas suatu tindakan dapat berbeda menurut pihak yang menilai; pihak yang disebut teroris oleh satu negara dapat dianggap pejuang kemerdekaan oleh pihak lain. Bagi bisnis, terorisme menaikkan biaya keamanan, asuransi, dan logistik, serta dapat meruntuhkan industri tertentu secara mendadak, sebagaimana dialami sektor pariwisata Bali setelah peristiwa bom tahun 2002. Selain itu, sikap masyarakat dan pemerintah tuan rumah terhadap perusahaan multinasional juga berubah-ubah, bergerak antara penerimaan karena kontribusi modal, teknologi, dan lapangan kerja, dengan kecurigaan karena dominasi pasar dan repatriasi laba. Oleh karena itu, perusahaan multinasional perlu membangun legitimasi sosial melalui kemitraan lokal, alih pengetahuan, dan tanggung jawab sosial yang substantif.</p>`
    },
    {
      no: "7.7",
      title: "Risiko Politik bagi Bisnis dan Manajemennya",
      body: `<p>Muara dari seluruh pembahasan lingkungan politik adalah konsep risiko politik. Menurut Kobrin (1979), risiko politik adalah kemungkinan terjadinya peristiwa politik yang mengubah prospek profitabilitas suatu investasi. Hill (2021) mendefinisikannya sebagai kemungkinan kekuatan politik menyebabkan perubahan drastis pada lingkungan bisnis suatu negara yang merugikan laba dan tujuan perusahaan. Dari definisi tersebut dapat disimpulkan bahwa risiko politik bukan sekadar ketidakstabilan politik itu sendiri, melainkan dampak peristiwa politik terhadap arus kas dan nilai perusahaan, sehingga tingkat risiko yang sama dapat berdampak berbeda bagi industri yang berbeda.</p>
<p>Risiko politik lazim diklasifikasikan menurut dua sumbu. Sumbu pertama membedakan risiko makro yang menimpa seluruh perusahaan di suatu negara, misalnya revolusi, perang saudara, atau nasionalisasi menyeluruh, dan risiko mikro yang menimpa industri atau perusahaan tertentu, misalnya pencabutan izin tambang atau diskriminasi terhadap perusahaan asing di sektor tertentu. Sumbu kedua membedakan jenis kerugian yang ditimbulkan, sebagaimana disajikan pada tabel berikut.</p>
<table class="bk-table"><caption>Tabel 5.2 Tipologi Risiko Politik dan Contohnya</caption>
<thead><tr><th>Jenis Risiko</th><th>Pengertian</th><th>Contoh Peristiwa</th></tr></thead>
<tbody>
<tr><td>Risiko kepemilikan (<em>ownership risk</em>)</td><td>Ancaman terhadap hak milik atas aset dan nyawa personel</td><td>Ekspropriasi, nasionalisasi, penyanderaan, perusakan fasilitas</td></tr>
<tr><td>Risiko operasi (<em>operating risk</em>)</td><td>Gangguan terhadap kelancaran operasi yang sedang berjalan</td><td>Perubahan regulasi mendadak, kewajiban kandungan lokal, pemogokan yang dipolitisasi, kerusuhan, terorisme</td></tr>
<tr><td>Risiko transfer (<em>transfer risk</em>)</td><td>Hambatan perpindahan dana dan sumber daya lintas negara</td><td>Kontrol devisa, larangan repatriasi laba, pembekuan aset akibat sanksi</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Kobrin (1979) dan Hill (2021)</td></tr></tfoot></table>
<p>Penilaian risiko politik dilakukan melalui kerangka analisis bertahap. Langkah pertama adalah identifikasi, yaitu memetakan peristiwa politik yang mungkin terjadi di negara sasaran dengan memanfaatkan indikator seperti indeks demokrasi, indeks persepsi korupsi, <em>Worldwide Governance Indicators</em>, serta jasa pemeringkat risiko negara. Langkah kedua adalah penaksiran, yaitu menilai probabilitas setiap peristiwa dan besaran dampaknya terhadap arus kas perusahaan; secara sederhana eksposur dapat dihitung sebagai perkalian antara probabilitas peristiwa dan nilai kerugian yang ditimbulkannya. Langkah ketiga adalah pemetaan prioritas dengan matriks probabilitas dan dampak, sehingga manajemen dapat memusatkan perhatian pada risiko berprobabilitas tinggi dan berdampak besar. Langkah keempat adalah perumusan respons, dan langkah kelima adalah pemantauan berkelanjutan karena konstelasi politik berubah setiap saat, terutama menjelang pemilihan umum.</p>
<p>Strategi mitigasi risiko politik dapat dikelompokkan menjadi tiga. Pertama, strategi penghindaran dan seleksi, yaitu tidak masuk atau membatasi eksposur pada negara berisiko tinggi, misalnya melalui moda masuk berisiko rendah seperti lisensi dan ekspor alih-alih investasi langsung. Kedua, strategi adaptasi, yaitu menyesuaikan diri dengan lingkungan politik melalui usaha patungan dengan mitra lokal, pelibatan pemangku kepentingan, pengembangan kandungan lokal, dan program tanggung jawab sosial yang membangun legitimasi. Ketiga, strategi pengalihan risiko, yaitu memindahkan sebagian risiko kepada pihak lain melalui asuransi risiko politik seperti yang disediakan <em>Multilateral Investment Guarantee Agency</em> (MIGA) dari kelompok Bank Dunia, klausul stabilisasi dalam kontrak dengan pemerintah tuan rumah, arbitrase internasional, serta pendanaan proyek yang melibatkan lembaga multilateral agar pemerintah tuan rumah enggan bertindak sepihak. Dalam konteks Indonesia, investor pernah menggunakan mekanisme arbitrase investasi internasional dalam sengketa pencabutan izin pertambangan, yang menunjukkan pentingnya membaca perjanjian perlindungan investasi bilateral sebelum menanam modal. Dengan demikian, manajemen risiko politik yang efektif memadukan analisis kelembagaan pada sesi ini, mulai dari relasi antarlembaga negara, kualitas demokrasi, hingga geopolitik, ke dalam keputusan investasi dan operasi sehari-hari.</p>`
    },
    {
      no: "7.8",
      title: "Rangkuman",
      body: `<p>Lingkungan politik merupakan sumber ketidakpastian utama bagi pengambilan keputusan bisnis karena negara menetapkan aturan main melalui fungsi stabilisasi, regulasi, dan redistribusi. Kapasitas negara terbentuk melalui tahap pembentukan negara, pembangunan bangsa, demokratisasi, dan negara kesejahteraan, sedangkan cakupan intervensinya dapat dipetakan dari fungsi minimal hingga aktivis menurut kerangka World Bank (1997). Relasi eksekutif, legislatif, dan yudikatif yang dilandasi <em>checks and balances</em> menentukan prediktabilitas regulasi dan keandalan penegakan kontrak, sebagaimana diperlihatkan dinamika legislasi omnibus dan putusan Mahkamah Konstitusi di Indonesia.</p>
<p>Kualitas demokrasi memengaruhi iklim usaha melalui mekanisme koreksi kebijakan dan kesetaraan di hadapan hukum. Indeks Demokrasi Indonesia dan indeks EIU menempatkan Indonesia pada kategori demokrasi cacat, dan berbagai studi dari Muhaimin, Robison, MacIntyre, Chalmers, hingga Hadiz, Hidayat, dan Suyatna menunjukkan persistensi patronase, klientelisme, dan politik biaya tinggi yang melahirkan pengusaha klien serta praktik transaksional pada era desentralisasi. Pada lapis internasional, globalisasi mengintegrasikan negara secara politik, ekonomi, dan budaya, namun fase geopolitik kontemporer yang ditandai rivalitas kekuatan besar, sanksi, dan fragmentasi geoekonomi menuntut perusahaan menimbang keselarasan blok politik dalam konfigurasi rantai pasoknya.</p>
<p>Seluruh dinamika tersebut bermuara pada manajemen risiko politik. Perusahaan perlu mengidentifikasi risiko kepemilikan, operasi, dan transfer pada tingkat makro maupun mikro, menaksir probabilitas dan dampaknya, kemudian meresponsnya melalui strategi penghindaran, adaptasi, dan pengalihan risiko seperti usaha patungan, klausul stabilisasi, arbitrase, dan asuransi MIGA. Dengan demikian, kecakapan membaca lingkungan politik nasional dan internasional merupakan bagian tidak terpisahkan dari kompetensi strategik seorang manajer.</p>`
    },
    {
      no: "7.9",
      title: "Daftar Pustaka",
      body: `<p>Aspinall, E. dan Berenschot, W. (2019). <em>Democracy for Sale: Elections, Clientelism, and the State in Indonesia</em>. Cornell University Press.</p>
<p>Chalmers, I. (1996). <em>Konglomerasi: Negara dan Modal dalam Industri Otomotif Indonesia 1950-1985</em>. Gramedia Pustaka Utama.</p>
<p>Economist Intelligence Unit. (2023). <em>Democracy Index 2023</em>. EIU.</p>
<p>Hadiz, V. R. (2005). <em>Dinamika Kekuasaan: Ekonomi Politik Indonesia Pasca-Soeharto</em>. LP3ES.</p>
<p>Held, D., McGrew, A., Goldblatt, D. dan Perraton, J. (1999). <em>Global Transformations: Politics, Economics and Culture</em>. Polity Press.</p>
<p>Heywood, A. (2011). <em>Global Politics</em>. Palgrave Macmillan.</p>
<p>Hill, C. W. L. (2021). <em>International Business: Competing in the Global Marketplace</em>. Edisi ke-13. McGraw-Hill Education.</p>
<p>Hodgetts, R. M., Luthans, F. dan Doh, J. P. (2006). <em>International Management: Culture, Strategy, and Behavior</em>. Edisi ke-6. McGraw-Hill.</p>
<p>Kobrin, S. J. (1979). Political Risk: A Review and Reconsideration. <em>Journal of International Business Studies</em>, 10(1).</p>
<p>Levitsky, S. dan Ziblatt, D. (2019). <em>How Democracies Die</em>. Crown Publishing.</p>
<p>MacIntyre, A. (1991). <em>Business and Politics in Indonesia</em>. Allen and Unwin.</p>
<p>North, D. C. (1990). <em>Institutions, Institutional Change and Economic Performance</em>. Cambridge University Press.</p>
<p>Robison, R. (1986). <em>Indonesia: The Rise of Capital</em>. Allen and Unwin.</p>
<p>Rugman, A. M. dan Collinson, S. (2009). <em>International Business</em>. Edisi ke-5. Pearson Education.</p>
<p>Steger, M. B. (2003). <em>Globalization: A Very Short Introduction</em>. Oxford University Press.</p>
<p>Suyatna, H. (2012). Politik Kebijakan Industri Kecil pada Era Desentralisasi. Universitas Gadjah Mada.</p>
<p>Suyatna, H. Modul GBE: Political Environment. Materi kuliah General Business Environment.</p>
<p>World Bank. (1997). <em>World Development Report 1997: The State in a Changing World</em>. Oxford University Press.</p>`
    }
  ]
};
