window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.otm = window.MBA_BOOK.otm || {};
window.MBA_BOOK.otm[9] = {
  bab: 9,
  judul: "BAB 9 PERBAIKAN, OPERASI LEAN DAN AGILE",
  sumber: "Heizer, Render dan Munson (2017), Operations Management 12e; Turban, Pollard dan Wood (2021), IT for Management 12e; Slack, Brandon-Jones dan Burgess (2022), Operations Management 10e",
  lo: [
    "LO1 Menjelaskan konsep perbaikan operasi serta membedakan pendekatan breakthrough improvement dan continuous improvement, termasuk siklus PDCA dan benchmarking",
    "LO2 Mendefinisikan operasi lean, just-in-time (JIT), dan Toyota Production System (TPS) beserta tiga isu fundamental perbaikan operasi",
    "LO3 Mengidentifikasi tujuh pemborosan menurut Ohno dan menerapkan checklist 5S untuk membangun tempat kerja yang lean",
    "LO4 Mengidentifikasi tujuan kemitraan pemasok dalam sistem JIT beserta lima kekhawatiran pemasok ketika beralih ke kemitraan tersebut",
    "LO5 Menentukan waktu setup optimal dengan memodifikasi model production order quantity",
    "LO6 Mendefinisikan kanban dan menghitung jumlah kartu atau kontainer kanban yang dibutuhkan",
    "LO7 Mengidentifikasi atribut organisasi lean serta menjelaskan penerapan lean pada sektor jasa",
    "LO8 Membedakan operasi lean dan agile serta menentukan kondisi pasar yang sesuai bagi masing-masing pendekatan, termasuk strategi hibrida leagile"
  ],
  sections: [
    {
      no: "9.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini membahas tiga tema yang saling berkaitan dalam manajemen operasi, yaitu perbaikan operasi (<em>operations improvement</em>), operasi lean, dan operasi agile. Ketiga tema tersebut menempati posisi strategis karena keunggulan bersaing perusahaan pada akhirnya ditentukan oleh kemampuan operasinya untuk terus menjadi lebih baik, lebih hemat, dan lebih tanggap dibandingkan pesaing. Pembahasan diawali dengan filosofi dan kerangka perbaikan operasi, dilanjutkan dengan konsep operasi lean yang mencakup just-in-time (JIT) dan Toyota Production System (TPS) menurut Heizer, Render dan Munson (2017), kemudian ditutup dengan perbandingan lean dan agile yang dikembangkan dari Slack, Brandon-Jones dan Burgess (2022) serta dukungan teknologi informasi menurut Turban, Pollard dan Wood (2021).</p>
<p>Setelah mempelajari bab ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<ul>
<li>Menjelaskan konsep perbaikan operasi serta membedakan pendekatan <em>breakthrough improvement</em> dan <em>continuous improvement</em>, termasuk siklus PDCA dan <em>benchmarking</em>.</li>
<li>Mendefinisikan operasi lean, <em>just-in-time</em> (JIT), dan <em>Toyota Production System</em> (TPS) beserta tiga isu fundamental perbaikan operasi.</li>
<li>Mengidentifikasi tujuh pemborosan menurut Ohno dan menerapkan <em>checklist</em> 5S.</li>
<li>Mengidentifikasi tujuan kemitraan pemasok dalam sistem JIT beserta lima kekhawatiran pemasok.</li>
<li>Menentukan waktu <em>setup</em> optimal dengan memodifikasi model <em>production order quantity</em>.</li>
<li>Mendefinisikan kanban dan menghitung jumlah kanban yang dibutuhkan.</li>
<li>Mengidentifikasi atribut organisasi lean serta menjelaskan penerapan lean pada sektor jasa.</li>
<li>Membedakan operasi lean dan agile serta menentukan kondisi pasar yang sesuai bagi masing-masing pendekatan.</li>
</ul>`
    },
    {
      no: "9.2",
      title: "Konsep Perbaikan Operasi",
      body: `<p>Setiap operasi, sebaik apa pun kinerjanya saat ini, selalu memiliki ruang untuk diperbaiki. Menurut Slack, Brandon-Jones dan Burgess (2022), perbaikan operasi merupakan aktivitas mempersempit kesenjangan antara kinerja aktual dan kinerja yang diinginkan pada dimensi kualitas, kecepatan, keandalan, fleksibilitas, dan biaya. Heizer, Render dan Munson (2017) menempatkan perbaikan sebagai inti dari operasi kelas dunia melalui tiga isu fundamental, yaitu menghilangkan pemborosan, menghapus variabilitas, dan meningkatkan <em>throughput</em>. Dari kedua pandangan tersebut dapat disimpulkan bahwa perbaikan operasi adalah proses sistematis dan berkelanjutan untuk menutup kesenjangan kinerja dengan cara membuang aktivitas yang tidak bernilai tambah dan menstabilkan proses. Oleh karena itu, perbaikan bukan proyek sesaat, melainkan bagian permanen dari pekerjaan setiap manajer operasi.</p>
<h5>9.2.1 Breakthrough Improvement dan Continuous Improvement</h5>
<p>Terdapat dua filosofi besar dalam melakukan perbaikan. Pertama, <em>breakthrough improvement</em> atau perbaikan radikal, yaitu perubahan besar dan dramatis yang biasanya membutuhkan investasi modal signifikan, misalnya penggantian lini produksi lama dengan lini otomatis atau penerapan sistem <em>enterprise resource planning</em> baru. Kedua, <em>continuous improvement</em> atau kaizen, yaitu akumulasi banyak perbaikan kecil yang dilakukan terus menerus oleh seluruh karyawan (Slack, Brandon-Jones dan Burgess, 2022). Perbaikan radikal menjanjikan lompatan kinerja dalam waktu singkat, namun berisiko tinggi dan sering menimbulkan resistensi organisasi. Di sisi lain, perbaikan berkelanjutan bergerak lambat namun menanamkan budaya belajar sehingga hasilnya lebih lestari. Dalam praktik, kedua pendekatan tidak saling meniadakan; perusahaan unggul menggabungkan lompatan teknologi dengan disiplin kaizen agar hasil lompatan tersebut tidak tergerus kembali.</p>
<h5>9.2.2 Siklus PDCA</h5>
<p>Kerangka yang paling banyak dipakai untuk mengelola perbaikan berkelanjutan adalah siklus PDCA (<em>plan, do, check, act</em>) yang dipopulerkan oleh W. Edwards Deming. Tahap <em>plan</em> berisi identifikasi masalah, pengumpulan data, dan perumusan hipotesis perbaikan. Tahap <em>do</em> berupa uji coba solusi dalam skala terbatas. Tahap <em>check</em> membandingkan hasil uji coba dengan target yang direncanakan, dan tahap <em>act</em> menstandarkan solusi yang terbukti berhasil atau mengulang siklus apabila hasil belum memuaskan. Sifat siklus ini berulang tanpa akhir, sehingga setiap standar baru menjadi titik awal bagi perbaikan berikutnya. Pendekatan yang lebih terstruktur, seperti Six Sigma dengan tahapan DMAIC (<em>define, measure, analyze, improve, control</em>), pada dasarnya merupakan pengembangan dari logika PDCA dengan disiplin statistik yang lebih ketat (Heizer, Render dan Munson, 2017).</p>
<h5>9.2.3 Benchmarking dan Prioritas Perbaikan</h5>
<p>Sebelum memperbaiki, manajer perlu menentukan apa yang paling penting untuk diperbaiki. Slack, Brandon-Jones dan Burgess (2022) menawarkan matriks kepentingan-kinerja (<em>importance-performance matrix</em>) yang memetakan setiap faktor kompetitif berdasarkan dua sumbu, yaitu seberapa penting faktor tersebut bagi pelanggan dan seberapa baik kinerja perusahaan dibandingkan pesaing. Faktor yang sangat penting bagi pelanggan namun kinerjanya di bawah pesaing masuk zona mendesak (<em>urgent action</em>) dan menjadi prioritas utama perbaikan. Selain itu, perusahaan dapat menggunakan <em>benchmarking</em>, yaitu pembandingan sistematis proses dan kinerja terhadap organisasi lain yang dianggap terbaik di kelasnya, baik pesaing langsung maupun perusahaan dari industri berbeda. Dengan demikian, agenda perbaikan tidak ditentukan oleh selera internal, melainkan oleh suara pelanggan dan posisi relatif terhadap pesaing.</p>`
    },
    {
      no: "9.3",
      title: "Konsep Dasar Operasi Lean",
      body: `<p>Operasi lean lahir dari praktik manufaktur Jepang, khususnya Toyota, dan kini menjadi pendekatan perbaikan yang paling berpengaruh di dunia. Menurut Heizer, Render dan Munson (2017), operasi lean adalah operasi yang memasok pelanggan dengan tepat apa yang diinginkan pelanggan, pada saat pelanggan menginginkannya, tanpa pemborosan, melalui perbaikan berkelanjutan. Aliran kerja dalam operasi lean digerakkan oleh tarikan pesanan pelanggan, bukan oleh dorongan rencana produksi. Dua komponen historis yang membentuk lean adalah <em>just-in-time</em> (JIT), yaitu pendekatan pemecahan masalah secara terus menerus dan terpaksa melalui fokus pada <em>throughput</em> dan pengurangan persediaan, serta <em>Toyota Production System</em> (TPS) yang menekankan perbaikan berkelanjutan, penghormatan terhadap manusia, dan praktik kerja standar. Dengan demikian, lean dapat dipahami sebagai payung yang merangkum seluruh teknik JIT dan TPS dalam satu strategi operasi yang utuh.</p>
<h5>9.3.1 Eliminasi Pemborosan dan Tujuh Pemborosan Ohno</h5>
<p>Prinsip pertama lean adalah bahwa nilai didefinisikan oleh pelanggan; setiap aktivitas yang tidak menambah nilai di mata pelanggan adalah pemborosan (<em>waste</em> atau <em>muda</em>). Taiichi Ohno, arsitek TPS, mengidentifikasi tujuh kategori pemborosan yang menjadi rujukan universal organisasi lean (Heizer, Render dan Munson, 2017). Tabel 9.1 menyajikan sintesis ketujuh pemborosan tersebut beserta contoh dan arah penanggulangannya.</p>
<table class="bk-table">
<caption>Tabel 9.1 Tujuh Pemborosan Menurut Ohno dan Penanggulangannya</caption>
<thead><tr><th>Pemborosan</th><th>Makna</th><th>Contoh</th><th>Arah Penanggulangan</th></tr></thead>
<tbody>
<tr><td><em>Overproduction</em></td><td>Memproduksi lebih banyak atau lebih awal daripada permintaan</td><td>Pabrik roti memanggang melebihi pesanan harian</td><td>Sistem tarik, <em>level schedule</em></td></tr>
<tr><td><em>Queues</em></td><td>Waktu menganggur, penyimpanan, dan antrean</td><td>Barang setengah jadi menunggu di depan mesin</td><td>Penyeimbangan lini, lot kecil</td></tr>
<tr><td><em>Transportation</em></td><td>Perpindahan material yang tidak perlu</td><td>Material bolak-balik antar gudang dan lini</td><td>Tata letak sel kerja, pengiriman langsung ke titik pakai</td></tr>
<tr><td><em>Inventory</em></td><td>Bahan baku, barang dalam proses, dan barang jadi berlebih</td><td>Stok komponen untuk tiga bulan</td><td>JIT, kanban, kemitraan pemasok</td></tr>
<tr><td><em>Motion</em></td><td>Gerakan orang atau mesin yang tidak bernilai tambah</td><td>Operator berjalan jauh mengambil perkakas</td><td>5S, studi metode kerja</td></tr>
<tr><td><em>Overprocessing</em></td><td>Pengerjaan melebihi spesifikasi yang dihargai pelanggan</td><td>Pemolesan komponen yang tidak terlihat pelanggan</td><td>Desain proses berbasis nilai pelanggan</td></tr>
<tr><td><em>Defective product</em></td><td>Produk cacat, pengerjaan ulang, klaim garansi</td><td>Retur produk dan <em>rework</em></td><td><em>Poka-yoke</em>, pengendalian proses statistik</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017)</td></tr></tfoot>
</table>
<p>Perspektif yang lebih luas menambahkan bahwa sumber daya seperti energi, air, dan udara juga sering diboroskan, sehingga produksi yang efisien sekaligus berkelanjutan berupaya meminimalkan seluruh input dan memaksimalkan output. Sebagai alat bantu praktis untuk menghilangkan pemborosan di tempat kerja, organisasi lean menggunakan <em>checklist</em> 5S yang dikembangkan di Jepang, yaitu: <em>sort</em> (memilah dan menyingkirkan barang yang tidak diperlukan dari area kerja), <em>simplify</em> (menata dan memberi label agar alur kerja sederhana dan ergonomis), <em>shine</em> (membersihkan area kerja setiap hari), <em>standardize</em> (membakukan prosedur sehingga penyimpangan mudah terlihat), dan <em>sustain</em> (mendisiplinkan diri agar keempat S sebelumnya terpelihara). Manajer di Amerika Serikat sering menambahkan dua S lain, yaitu <em>safety</em> dan <em>support/maintenance</em> (Heizer, Render dan Munson, 2017). Selain berfungsi sebagai daftar periksa, 5S merupakan kendaraan perubahan budaya karena melibatkan setiap karyawan dalam menjaga keteraturan tempat kerjanya sendiri.</p>
<h5>9.3.2 Reduksi Variabilitas</h5>
<p>Isu fundamental kedua adalah menghapus variabilitas. Variabilitas didefinisikan sebagai setiap penyimpangan dari proses optimum yang menghasilkan produk sempurna tepat waktu setiap saat (Heizer, Render dan Munson, 2017). Sumber variabilitas antara lain proses yang buruk sehingga jumlah atau mutu produksi menyimpang, pemeliharaan fasilitas yang tidak memadai, permintaan pelanggan yang tidak diketahui, serta gambar teknik dan spesifikasi yang tidak akurat. Semakin kecil variabilitas dalam sistem, semakin kecil pula pemborosan yang menyertainya. Pengurangan persediaan melalui JIT merupakan alat yang efektif untuk mengungkap penyebab variabilitas, karena ketiadaan penyangga persediaan membuat setiap masalah kualitas, jadwal, maupun pemasok segera terlihat dan terpaksa diselesaikan.</p>
<h5>9.3.3 Peningkatan Throughput dan Sistem Tarik</h5>
<p><em>Throughput</em> adalah laju perpindahan unit melewati suatu proses, sedangkan <em>manufacturing cycle time</em> adalah waktu antara kedatangan bahan baku dan pengiriman produk jadi (Heizer, Render dan Munson, 2017). Setiap menit produk tertahan dalam proses, biaya terakumulasi dan keunggulan bersaing berkurang. Teknik utama untuk meningkatkan <em>throughput</em> adalah sistem tarik (<em>pull system</em>), yaitu konsep yang membuat material diproduksi hanya ketika diminta dan dipindahkan ke tempat yang membutuhkan tepat pada saat dibutuhkan. Sistem tarik berkebalikan dengan sistem dorong (<em>push system</em>) yang melimpahkan pesanan ke stasiun kerja berikutnya tanpa memperhatikan kesiapan sumber daya di sana. Dengan menarik material dalam lot yang sangat kecil, persediaan dan kekacauan berkurang, masalah menjadi tampak, investasi persediaan menurun, dan <em>manufacturing cycle time</em> memendek. Oleh karena itu, sistem tarik menjadi alat standar dalam setiap implementasi lean.</p>`
    },
    {
      no: "9.4",
      title: "Lean dan Just-in-Time",
      body: `<p>JIT merupakan komponen lean yang menuntut material tiba di tempat yang membutuhkan hanya pada saat dibutuhkan dan dalam jumlah yang dibutuhkan. Kekuatan JIT justru terletak pada sifatnya yang memaksa; ketika unit yang baik tidak tiba tepat waktu, sebuah masalah teridentifikasi dan harus diselesaikan, sehingga perhatian organisasi terus terarah pada perbaikan (Heizer, Render dan Munson, 2017). Penerapan JIT yang berhasil menuntut perubahan pada lima wilayah keputusan, yaitu kemitraan pemasok, tata letak, persediaan, penjadwalan, dan kualitas, yang diuraikan pada sub-sub-bab berikut.</p>
<h5>9.4.1 Kemitraan Pemasok</h5>
<p>Kemitraan pemasok (<em>supplier partnership</em>) terjadi ketika pemasok dan pembeli bekerja sama dengan komunikasi terbuka untuk menghilangkan pemborosan dan menurunkan biaya demi manfaat bersama (Heizer, Render dan Munson, 2017). Tujuan spesifik kemitraan dalam konteks JIT meliputi penghapusan aktivitas yang tidak perlu seperti inspeksi kedatangan dan administrasi penagihan, penghapusan persediaan di pabrik melalui pengiriman lot kecil langsung ke departemen pengguna, penghapusan persediaan dalam perjalanan dengan mendorong pemasok berlokasi dekat pembeli, serta perbaikan kualitas dan keandalan melalui komitmen jangka panjang. Salah satu teknik yang lazim digunakan adalah <em>consignment inventory</em>, yaitu pengaturan ketika pemasok tetap memegang kepemilikan persediaan sampai persediaan tersebut digunakan oleh pembeli. Namun, pemasok memiliki lima kekhawatiran yang harus dikelola, yaitu keinginan diversifikasi pelanggan agar risiko tidak terkonsentrasi, keraguan terhadap kemampuan pembeli menyusun jadwal yang mulus, waktu tunggu yang sempit untuk mengakomodasi perubahan rekayasa, keterbatasan kapasitas teknologi untuk memenuhi tuntutan kualitas, dan kecurigaan bahwa pengiriman lot kecil hanyalah cara pembeli memindahkan biaya penyimpanan kepada pemasok. Praktik ini terlihat pada PT Toyota Motor Manufacturing Indonesia di Karawang dan PT Astra Honda Motor di Cikarang, yang membina pemasok komponen lokal di kawasan industri sekitarnya agar mampu mengirim komponen beberapa kali sehari langsung ke lini perakitan.</p>
<h5>9.4.2 Tata Letak Lean</h5>
<p>Tata letak lean ditujukan untuk mengurangi pemborosan pergerakan material dan manusia. Manajer merancang sel kerja (<em>work cell</em>) berbentuk huruf U yang memuat beberapa mesin berbeda untuk memproses satu keluarga produk yang diidentifikasi melalui <em>group technology</em>, sehingga jarak tempuh material menjadi sangat pendek (Heizer, Render dan Munson, 2017). Selain pengurangan jarak, tata letak lean menekankan fleksibilitas, yaitu area kerja yang mudah diatur ulang karena hampir tidak ada peralatan yang dipasang permanen, serta dampak positif terhadap karyawan karena operasi yang berurutan memungkinkan umpan balik kualitas seketika antar pekerja. Ruang yang sempit juga mengurangi tempat bagi penumpukan persediaan, dan perangkat <em>poka-yoke</em> atau alat anti kesalahan dipasang agar cacat terdeteksi secara otomatis pada setiap tahap.</p>
<h5>9.4.3 Persediaan Lean dan Reduksi Waktu Setup</h5>
<p>Persediaan lean adalah persediaan minimum yang diperlukan untuk menjaga sistem yang sempurna tetap berjalan (Heizer, Render dan Munson, 2017). Filosofinya sering digambarkan dengan analogi danau; permukaan air yang tinggi melambangkan persediaan yang menyembunyikan batu-batu masalah seperti keterlambatan pengiriman, waktu <em>setup</em> panjang, dan masalah kualitas. Ketika persediaan diturunkan, masalah tersingkap dan dapat diselesaikan satu per satu. Shigeo Shingo, salah satu pengembang sistem JIT Toyota, bahkan menyatakan "inventory is evil" untuk menegaskan bahwa persediaan menyembunyikan masalah dengan biaya yang mahal (Heizer, Render dan Munson, 2017). Kunci pengurangan persediaan adalah memproduksi dalam lot kecil, dan kunci lot kecil adalah waktu <em>setup</em> yang singkat. Ukuran lot produksi dihitung dengan model <em>production order quantity</em> sebagai berikut: Q*p = akar dari [2DS / (H(1 - d/p))], dengan D adalah permintaan tahunan, S biaya <em>setup</em>, H biaya penyimpanan per unit per tahun, d permintaan harian, dan p laju produksi harian. Dalam lingkungan lean, logika rumus tersebut dibalik; manajer terlebih dahulu menetapkan ukuran lot kecil yang diinginkan, kemudian menghitung biaya <em>setup</em> maksimum yang harus dicapai melalui persamaan S = (Q kuadrat kali H kali (1 - d/p)) / (2D). Waktu <em>setup</em> optimal diperoleh dengan membagi biaya <em>setup</em> tersebut dengan tarif upah per jam. Sebagai ilustrasi, apabila permintaan tahunan 400.000 unit, permintaan harian 1.600 unit, laju produksi 4.000 unit per hari, lot yang diinginkan 400 unit, biaya simpan 20 dolar per unit per tahun, dan upah 30 dolar per jam, maka biaya <em>setup</em> yang diizinkan adalah 2,40 dolar sehingga waktu <em>setup</em> sasaran hanya 0,08 jam atau 4,8 menit. Pengurangan waktu <em>setup</em> dicapai secara bertahap, mulai dari memisahkan persiapan yang dapat dilakukan saat mesin masih beroperasi, mendekatkan material, membakukan perkakas, sampai menghilangkan penyetelan dengan sistem sekali sentuh.</p>
<h5>9.4.4 Penjadwalan Lean: Level Schedule dan Kanban</h5>
<p>Jadwal yang efektif dan dikomunikasikan kepada pihak internal maupun pemasok merupakan syarat JIT. Dua teknik penjadwalan yang utama adalah jadwal berimbang dan kanban. Jadwal berimbang (<em>level schedule</em>), yang disebut <em>heijunka</em> oleh orang Jepang, memproses lot kecil yang sering dengan mencampur berbagai model pada lini yang sama, sehingga produksi setiap hari sesuai dengan permintaan hari itu (Heizer, Render dan Munson, 2017). Sementara itu, kanban adalah kata Jepang untuk kartu yang telah bermakna sinyal; sistem kanban memindahkan komponen melalui produksi berdasarkan tarikan dari sebuah sinyal. Kartu, lampu, bendera, atau bahkan posisi kosong di lantai menjadi otorisasi bagi stasiun pemasok untuk memproduksi satu kontainer komponen berikutnya, sehingga jumlah kartu kanban secara langsung membatasi barang dalam proses di antara sel kerja. Jumlah kanban dihitung dengan rumus: Jumlah kanban = (Permintaan selama <em>lead time</em> + Persediaan pengaman) / Ukuran kontainer. Sebagai contoh, sebuah pabrik kue dengan permintaan harian 500 unit, <em>lead time</em> produksi 2 hari, persediaan pengaman setengah hari permintaan, dan ukuran kontainer 250 unit membutuhkan (1.000 + 250) / 250 = 5 kontainer kanban. Keunggulan kanban adalah kesederhanaannya, namun sistem ini menuntut jadwal yang ketat serta proses yang stabil karena setiap kekurangan berdampak seketika pada seluruh sistem.</p>
<h5>9.4.5 Kualitas Lean</h5>
<p>Tidak ada lean tanpa kualitas. Produksi tarik, ukuran batch kecil, dan persediaan rendah justru meningkatkan kualitas karena bukti kesalahan tetap segar dan sumber kesalahan yang potensial menjadi terbatas, sehingga lean berfungsi sebagai sistem peringatan dini bagi masalah kualitas (Heizer, Render dan Munson, 2017). Sebaliknya, kualitas yang konsisten mengurangi kebutuhan penyangga persediaan sehingga sistem lean semakin murah dipertahankan. Taktik kualitas lean mencakup pengendalian proses statistik, pemberdayaan karyawan, metode anti gagal seperti <em>poka-yoke</em> dan <em>checklist</em>, penyingkapan kualitas buruk melalui lot kecil, serta umpan balik seketika. Dengan demikian, hubungan lean dan kualitas bersifat saling menguatkan; persediaan menyembunyikan kualitas yang buruk, sedangkan lean menyingkapnya.</p>`
    },
    {
      no: "9.5",
      title: "Toyota Production System dan Organisasi Lean",
      body: `<p>Eiji Toyoda dan Taiichi Ohno dari Toyota Motor diakui sebagai pencipta TPS, sistem yang menjadikan Toyota salah satu produsen kendaraan terbesar di dunia dengan kualitas yang konsisten dan jam kerja perakitan terendah di industrinya (Heizer, Render dan Munson, 2017). Tiga komponen inti TPS adalah perbaikan berkelanjutan, penghormatan terhadap manusia, dan praktik kerja standar, yang kini dipandang sebagai bagian integral dari lean.</p>
<h5>9.5.1 Tiga Pilar TPS</h5>
<p>Perbaikan berkelanjutan dalam TPS berarti membangun budaya organisasi dan menanamkan sistem nilai bahwa proses selalu dapat diperbaiki, dan bahwa perbaikan adalah bagian dari pekerjaan setiap karyawan. Proses ini diformalkan melalui kaizen, kata Jepang yang berarti perubahan menuju kebaikan, dan sering diwujudkan dalam <em>kaizen event</em>, yaitu pertemuan anggota tim kerja untuk mengembangkan cara inovatif yang segera diterapkan guna memperbaiki proses (Heizer, Render dan Munson, 2017). Pilar kedua, penghormatan terhadap manusia, berarti karyawan direkrut, dilatih, dan diperlakukan sebagai pekerja berpengetahuan; melalui pelatihan silang yang agresif dan klasifikasi pekerjaan yang sedikit, karyawan diberdayakan bukan hanya untuk mengusulkan perbaikan, melainkan juga untuk menghentikan mesin dan proses ketika terdapat masalah kualitas. Pilar ketiga, praktik kerja standar, menuntut pekerjaan dispesifikasi lengkap menyangkut isi, urutan, waktu, dan hasil; hubungan pemasok internal maupun eksternal bersifat langsung; aliran material sederhana dan terarah; serta perbaikan proses dilakukan hanya setelah analisis yang ketat pada tingkat organisasi terendah. Praktik menghentikan produksi ketika terjadi cacat disebut <em>jidoka</em>, sedangkan kebiasaan manajer mendatangi tempat pekerjaan benar-benar dilakukan disebut <em>gemba walk</em>. Di Indonesia, PT Toyota Motor Manufacturing Indonesia menerapkan TPS secara penuh di pabrik Karawang, termasuk papan <em>andon</em>, sel kaizen, dan pemberdayaan operator untuk menghentikan lini, sehingga pabrik tersebut menjadi basis ekspor kendaraan ke puluhan negara.</p>
<h5>9.5.2 Atribut Organisasi Lean</h5>
<p>Membangun organisasi lean menuntut kepemimpinan yang luar biasa karena yang dibangun bukan sekadar seperangkat alat, melainkan budaya perbaikan berkelanjutan yang menghancurkan sekat-sekat fungsional. Heizer, Render dan Munson (2017) mengidentifikasi enam atribut organisasi lean, yaitu: menghormati dan mengembangkan karyawan melalui desain pekerjaan dan pelatihan berkelanjutan; memberdayakan karyawan dengan mendorong tanggung jawab ke tingkat terendah yang mungkin; mengembangkan fleksibilitas pekerja melalui pelatihan silang; membangun proses yang menghancurkan variabilitas agar setiap karyawan menghasilkan produk sempurna; mengembangkan kemitraan kolaboratif dengan pemasok; dan menghilangkan pemborosan dengan hanya melakukan aktivitas bernilai tambah. Keberhasilan menuntut komitmen penuh manajemen, karyawan, dan pemasok sekaligus, dan imbalannya adalah posisi sebagai <em>benchmark</em> industri seperti yang dicapai Toyota, United Parcel Service, dan Alaska Airlines.</p>
<h5>9.5.3 Lean dan Keberlanjutan</h5>
<p>Lean dan keberlanjutan merupakan dua sisi mata uang yang sama karena keduanya berupaya memaksimalkan efisiensi sumber daya dan ekonomi. Lean mengusir pemborosan karena pemborosan tidak menambah apa pun bagi pelanggan, sedangkan keberlanjutan mengusir pemborosan karena pemborosan mahal dan merusak lingkungan (Heizer, Render dan Munson, 2017). Namun, apabila lean hanya berfokus pada proses internal, manajer dapat melewatkan isu keberlanjutan di luar batas perusahaan. Oleh karena itu, perusahaan perlu memandang sistem secara luas hingga mencakup pemangku kepentingan agar lean dan keberlanjutan sama-sama mencapai kinerja yang lebih tinggi, misalnya melalui pengurangan emisi transportasi ketika pemasok berlokasi dekat pabrik.</p>`
    },
    {
      no: "9.6",
      title: "Lean pada Sektor Jasa",
      body: `<p>Fitur lean berlaku pada jasa sebagaimana pada manufaktur, mulai dari rumah sakit, taman hiburan, sampai maskapai penerbangan. Perbedaan penekanannya terletak pada tingginya interaksi dengan pelanggan, sehingga pelatihan, motivasi, dan pemberdayaan karyawan garis depan menjadi semakin penting (Heizer, Render dan Munson, 2017). Penerapan lean pada jasa dapat ditinjau dari empat wilayah keputusan. Pertama, pemasok; hampir setiap restoran berhubungan dengan pemasoknya secara JIT karena bahan makanan yang menumpuk akan rusak, dan sektor keuangan memproses transaksi nasabah seketika sebagai standar industri. Kedua, tata letak; dapur restoran dirancang agar makanan panas tersaji panas, sebagaimana McDonald's mengkonfigurasi ulang dapurnya untuk memangkas detik demi detik dari proses produksi. Ketiga, persediaan; pialang saham menekan persediaan pesanan mendekati nol setiap hari, dan rumah sakit mengelola persediaan obat kritis pada tingkat rendah dengan jejaring komunitas sebagai cadangan. Keempat, penjadwalan; alih-alih menyimpan persediaan barang, perusahaan jasa menjadwalkan personel secara presisi berbasis peramalan permintaan sampai satuan lima belas menit agar kapasitas hadir tepat ketika permintaan memuncak.</p>
<p>Konteks Indonesia menyediakan banyak contoh penerapan lean jasa. Jaringan restoran cepat saji lokal dan gerai kopi seperti Kopi Kenangan menerapkan prinsip dapur lean dengan stasiun kerja berurutan, ukuran batch kecil, dan bahan baku yang dikirim harian agar kesegaran terjaga dan pembuangan minimal. Beberapa rumah sakit besar, misalnya rumah sakit jejaring universitas di Jakarta dan Surabaya, mengadopsi <em>kaizen event</em> untuk memangkas waktu tunggu pasien rawat jalan dan menerapkan 5S pada ruang farmasi sehingga kesalahan pengambilan obat menurun. Selain itu, perusahaan logistik yang melayani dagang elektronik menerapkan prinsip tarik dan tata letak lean pada gudang <em>sorting</em> agar paket mengalir tanpa penumpukan. Dari contoh-contoh tersebut dapat disimpulkan bahwa teknik lean bekerja pada perusahaan penghasil barang maupun jasa; wujudnya saja yang berbeda. Implikasi manajerialnya, manajer jasa perlu mengidentifikasi pemborosan dalam bentuk waktu tunggu pelanggan, gerakan karyawan, dan kapasitas menganggur, kemudian menyerang pemborosan tersebut dengan alat yang sama seperti di pabrik, yaitu 5S, standar kerja, sistem tarik, dan perbaikan berkelanjutan.</p>`
    },
    {
      no: "9.7",
      title: "Operasi Agile serta Perbandingan Lean dan Agile",
      body: `<p>Lean bukan satu-satunya paradigma operasi modern. Ketika pasar bergejolak dan sulit diramal, kemampuan bergerak cepat dapat lebih bernilai daripada efisiensi semata. Menurut Slack, Brandon-Jones dan Burgess (2022), <em>agility</em> adalah kemampuan operasi dan rantai pasokan untuk merespons secara cepat dan hemat biaya terhadap perubahan pasar yang tidak terduga, baik dalam volume maupun ragam produk. Dari definisi tersebut dapat disimpulkan bahwa agile menekankan kecepatan tanggapan dan fleksibilitas sebagai tujuan utama, sedangkan lean menekankan penghapusan pemborosan dan aliran yang mulus pada permintaan yang relatif stabil.</p>
<h5>9.7.1 Kapan Lean dan Kapan Agile</h5>
<p>Pilihan antara lean dan agile bergantung pada karakter produk dan pasar. Produk fungsional dengan permintaan stabil, siklus hidup panjang, dan margin tipis, misalnya bahan pokok, komponen standar, dan produk perawatan rumah tangga, paling tepat dilayani rantai pasokan lean yang efisien secara fisik. Sebaliknya, produk inovatif dengan permintaan sulit diramal, siklus hidup pendek, dan risiko usang tinggi, misalnya pakaian mode dan gawai elektronik, menuntut rantai pasokan agile yang tanggap terhadap pasar (Slack, Brandon-Jones dan Burgess, 2022). Tabel 9.2 menyajikan sintesis perbandingan kedua pendekatan.</p>
<table class="bk-table">
<caption>Tabel 9.2 Perbandingan Operasi Lean dan Agile</caption>
<thead><tr><th>Dimensi</th><th>Lean</th><th>Agile</th></tr></thead>
<tbody>
<tr><td>Tujuan utama</td><td>Menghapus pemborosan dan biaya</td><td>Merespons perubahan permintaan dengan cepat</td></tr>
<tr><td>Karakter permintaan</td><td>Stabil dan dapat diramal</td><td>Bergejolak dan sulit diramal</td></tr>
<tr><td>Tipe produk</td><td>Fungsional, siklus hidup panjang</td><td>Inovatif, siklus hidup pendek</td></tr>
<tr><td>Pemenang pesanan</td><td>Biaya dan kualitas konsisten</td><td>Ketersediaan, kecepatan, dan ragam</td></tr>
<tr><td>Kebijakan persediaan</td><td>Minimum di seluruh aliran</td><td>Penyangga kapasitas atau komponen generik pada titik strategis</td></tr>
<tr><td>Kebijakan kapasitas</td><td>Utilisasi tinggi, aliran rata</td><td>Kapasitas cadangan untuk lonjakan</td></tr>
<tr><td>Fokus perbaikan</td><td>Reduksi waktu setup dan variabilitas</td><td>Reduksi waktu tunggu total dan modularitas produk</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Slack, Brandon-Jones dan Burgess (2022) serta Heizer, Render dan Munson (2017)</td></tr></tfoot>
</table>
<h5>9.7.2 Strategi Hibrida Leagile dan Decoupling Point</h5>
<p>Dalam praktik, banyak perusahaan menggabungkan keduanya melalui strategi hibrida yang dikenal sebagai <em>leagile</em>. Kuncinya adalah <em>decoupling point</em>, yaitu titik dalam rantai pasokan tempat persediaan strategis disimpan dan tempat aliran berbasis ramalan berganti menjadi aliran berbasis pesanan (Slack, Brandon-Jones dan Burgess, 2022). Di hulu titik tersebut, perusahaan beroperasi secara lean dengan memproduksi komponen generik dalam volume efisien; di hilirnya, perusahaan beroperasi secara agile dengan merakit atau menyelesaikan produk sesuai pesanan aktual, sebuah praktik yang juga disebut <em>postponement</em>. Contoh klasiknya adalah produsen komputer yang menyimpan modul standar dan baru merakit konfigurasi akhir setelah pesanan diterima. Di Indonesia, strategi serupa diterapkan produsen pakaian muslim dan pelaku industri kreatif yang menyiapkan kain dan pola dasar secara efisien jauh hari, kemudian menjahit model dan warna yang sedang tren menjelang Ramadan ketika sinyal permintaan sudah jelas; demikian pula pelaku dagang elektronik yang menempatkan stok generik di gudang regional dan melakukan pengemasan akhir sesuai pesanan harian.</p>
<h5>9.7.3 Peran Teknologi Informasi dalam Lean dan Agile</h5>
<p>Kemampuan lean maupun agile pada masa kini semakin ditopang oleh teknologi informasi. Menurut Turban, Pollard dan Wood (2021), visibilitas data ujung ke ujung melalui sistem <em>enterprise resource planning</em>, kanban elektronik, <em>internet of things</em>, dan analitik permintaan memungkinkan perusahaan berbagi jadwal produksi dengan pemasok secara waktu nyata, mendeteksi penyimpangan proses lebih dini, dan meramal permintaan dengan lebih akurat. Bagi operasi lean, teknologi tersebut memperhalus sistem tarik dan menekan persediaan pengaman; bagi operasi agile, teknologi mempercepat penginderaan tren pasar sehingga keputusan kapasitas dan ragam produk dapat diambil lebih cepat. Implikasi manajerialnya, investasi teknologi informasi perlu diarahkan bukan untuk mengotomasi pemborosan yang ada, melainkan untuk memperkuat prinsip aliran, tarikan, dan respons yang telah dibenahi terlebih dahulu melalui perbaikan proses.</p>`
    },
    {
      no: "9.8",
      title: "Rangkuman",
      body: `<p>Perbaikan operasi merupakan aktivitas permanen untuk mempersempit kesenjangan antara kinerja aktual dan kinerja yang diinginkan, yang dapat ditempuh melalui lompatan radikal maupun akumulasi perbaikan kecil bergaya kaizen dengan kerangka siklus PDCA, <em>benchmarking</em>, dan matriks kepentingan-kinerja sebagai penentu prioritas. Operasi lean, yang merangkum JIT dan TPS, mengejar kesempurnaan dengan menyerang tiga isu fundamental, yaitu menghilangkan tujuh pemborosan Ohno dengan bantuan 5S, menghapus variabilitas, dan meningkatkan <em>throughput</em> melalui sistem tarik. Penerapannya menuntut kemitraan pemasok yang saling percaya, tata letak sel kerja yang memangkas jarak, persediaan minimum yang dimungkinkan oleh lot kecil dan waktu <em>setup</em> singkat, penjadwalan berimbang dengan kanban, serta kualitas yang tersingkap oleh rendahnya persediaan.</p>
<p>TPS menambahkan dimensi budaya melalui tiga pilarnya, yaitu perbaikan berkelanjutan, penghormatan terhadap manusia, dan praktik kerja standar, yang menjadikan organisasi lean bercirikan karyawan berdaya, pemasok kolaboratif, dan proses yang stabil. Prinsip lean terbukti berlaku pada sektor jasa dengan penyesuaian pada pemasok, tata letak, persediaan, dan penjadwalan personel, sebagaimana ditunjukkan restoran, rumah sakit, dan lembaga keuangan di berbagai negara termasuk Indonesia. Di sisi lain, pasar yang bergejolak menuntut operasi agile yang mengutamakan kecepatan respons, dan banyak perusahaan menggabungkan keduanya melalui strategi <em>leagile</em> dengan menempatkan <em>decoupling point</em> secara strategis. Dengan demikian, tugas manajer operasi bukan memilih salah satu paradigma secara dogmatis, melainkan mencocokkan konfigurasi lean, agile, atau hibrida dengan karakter produk dan pasar yang dilayani, serta menopangnya dengan teknologi informasi dan budaya perbaikan yang berkelanjutan.</p>`
    },
    {
      no: "9.9",
      title: "Daftar Pustaka",
      body: `<p>Heizer, J., Render, B. dan Munson, C. (2017). <em>Operations Management: Sustainability and Supply Chain Management</em>. 12th Edition. Pearson Education.</p>
<p>Slack, N., Brandon-Jones, A. dan Burgess, N. (2022). <em>Operations Management</em>. 10th Edition. Pearson Education.</p>
<p>Turban, E., Pollard, C. dan Wood, G. (2021). <em>Information Technology for Management: Driving Digital Transformation to Increase Local and Global Performance, Growth and Sustainability</em>. 12th Edition. John Wiley and Sons.</p>`
    }
  ]
};
