window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.otm = window.MBA_BOOK.otm || {};
window.MBA_BOOK.otm[11] = {
  bab: 11,
  judul: "BAB 11 KEANDALAN DAN RESILIENSI OPERASI",
  sumber: "Heizer, Render dan Munson (2017), Operations Management 12e; Turban, Pollard dan Wood (2021), IT for Management 12e; Slack, Brandon-Jones dan Burgess (2022), Operations Management 10e",
  lo: [
    "LO1 Menjelaskan arti penting strategis pemeliharaan (maintenance) dan keandalan (reliability) bagi kinerja dan daya saing operasi",
    "LO2 Menghitung keandalan sistem berkomponen seri serta menjelaskan taktik perbaikan keandalan komponen individual",
    "LO3 Menghitung tingkat kegagalan produk FR(%), FR(N), dan mean time between failures (MTBF)",
    "LO4 Menjelaskan mekanisme redundansi cadangan (backup) dan redundansi paralel untuk menaikkan keandalan sistem",
    "LO5 Membedakan preventive maintenance dan breakdown maintenance serta membandingkan biaya kedua kebijakan tersebut",
    "LO6 Mendefinisikan autonomous maintenance dan menjelaskan pilar Total Productive Maintenance (TPM)",
    "LO7 Menerapkan teknik manajemen proyek, meliputi work breakdown structure, diagram Gantt, PERT/CPM, dan crashing, pada proyek pemeliharaan dan perbaikan keandalan",
    "LO8 Menjelaskan kerangka manajemen risiko operasi dan resiliensi, meliputi identifikasi kegagalan, failure mode and effect analysis (FMEA), pencegahan, mitigasi, dan pemulihan, termasuk kontinuitas layanan teknologi informasi"
  ],
  sections: [
    {
      no: "11.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi kesebelas mata kuliah Operations and Technology Management membahas keandalan dan resiliensi operasi (<em>operations reliability and resilience</em>). Pembahasan pada sesi ini merupakan kelanjutan logis dari sesi manajemen kualitas, karena sistem operasi yang bermutu tidak akan berarti apabila mesin, proses, dan teknologi pendukungnya sering mengalami kegagalan. Materi sesi ini bersumber pada Bab 17 buku Heizer, Render dan Munson (2017) mengenai <em>maintenance and reliability</em>, diperkaya dengan Bab 3 buku yang sama mengenai manajemen proyek sebagai kerangka pengelolaan proyek perbaikan dan overhaul, Bab 18 dan 19 buku Slack, Brandon-Jones dan Burgess (2022) mengenai manajemen risiko dan resiliensi operasi, serta Bab 13 buku Turban, Pollard dan Wood (2021) mengenai pengelolaan proyek dan keandalan layanan teknologi informasi.</p>
<p>Kegagalan operasi dapat berdampak sangat besar terhadap biaya, keselamatan, dan reputasi perusahaan. Oleh karena itu, manajer operasi dituntut mampu merancang sistem yang andal, memelihara aset secara terencana, dan menyiapkan organisasi agar tangguh menghadapi gangguan yang tidak dapat dicegah. Setelah mengikuti sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p>Pertama, menjelaskan arti penting strategis pemeliharaan dan keandalan bagi kinerja operasi. Kedua, menghitung keandalan sistem berkomponen seri dan menjelaskan cara memperbaikinya. Ketiga, menghitung tingkat kegagalan dan <em>mean time between failures</em>. Keempat, menjelaskan redundansi sebagai taktik menaikkan keandalan. Kelima, membedakan serta membandingkan biaya <em>preventive maintenance</em> dan <em>breakdown maintenance</em>. Keenam, mendefinisikan <em>autonomous maintenance</em> dan Total Productive Maintenance. Ketujuh, menerapkan teknik manajemen proyek pada proyek perbaikan keandalan. Kedelapan, menjelaskan kerangka manajemen risiko dan resiliensi operasi, termasuk kontinuitas layanan teknologi informasi.</p>`
    },
    {
      no: "11.2",
      title: "Arti Penting Strategis Pemeliharaan dan Keandalan",
      body: `<p>Setiap sistem operasi bergantung pada kesiapan mesin, fasilitas, dan teknologi untuk bekerja sesuai spesifikasi. Ketika sebuah komponen gagal, dampaknya jarang berhenti pada komponen tersebut, melainkan menjalar ke jadwal produksi, persediaan, keselamatan kerja, dan kepuasan pelanggan. Menurut Heizer, Render dan Munson (2017), pemeliharaan (<em>maintenance</em>) mencakup seluruh aktivitas yang dilakukan untuk menjaga peralatan suatu sistem tetap berada dalam kondisi siap bekerja, sedangkan keandalan (<em>reliability</em>) adalah probabilitas suatu komponen mesin atau produk berfungsi dengan baik selama waktu tertentu pada kondisi yang telah ditetapkan. Dari kedua definisi tersebut dapat disimpulkan bahwa tujuan pemeliharaan dan keandalan adalah memelihara kapabilitas sistem sekaligus menekan variabilitas, sehingga sistem mampu menghasilkan keluaran sesuai standar kinerja dan kualitas yang diharapkan.</p>
<p>Arti penting strategis fungsi ini terlihat jelas pada kasus Orlando Utilities Commission (OUC), perusahaan pembangkit listrik di Florida yang menjadi profil pembuka bab. Setiap hari pembangkit berhenti untuk pemeliharaan terjadwal, OUC menanggung biaya sekitar 110 ribu dolar untuk membeli listrik pengganti, sedangkan satu hari gangguan yang tidak terjadwal (<em>forced outage</em>) dapat menimbulkan biaya tambahan 350 ribu sampai 600 ribu dolar (Heizer, Render dan Munson, 2017). Perbandingan angka tersebut menunjukkan bahwa pemeliharaan terencana jauh lebih murah daripada kegagalan mendadak. Perusahaan seperti Frito-Lay, Walt Disney, dan UPS juga menempatkan pemeliharaan sebagai sumber keunggulan bersaing karena utilisasi pabrik yang tinggi, keselamatan pengunjung, dan umur armada yang panjang hanya dapat dicapai apabila peralatan andal.</p>
<p>Dalam konteks Indonesia, pelajaran serupa dapat ditarik dari peristiwa pemadaman listrik massal di Jawa bagian barat pada Agustus 2019 yang melumpuhkan transportasi, telekomunikasi, dan aktivitas bisnis selama berjam-jam, serta menimbulkan kewajiban kompensasi yang sangat besar bagi PLN. Di sisi lain, GMF AeroAsia, anak usaha Garuda Indonesia di bidang <em>maintenance, repair and overhaul</em> (MRO) pesawat, menunjukkan bahwa kapabilitas pemeliharaan dapat dikembangkan menjadi unit bisnis tersendiri yang melayani maskapai regional. Kedua contoh tersebut menegaskan bahwa keandalan bukan sekadar urusan teknis bagian bengkel, melainkan keputusan strategis yang menentukan kelangsungan pendapatan dan reputasi perusahaan.</p>
<p>Heizer, Render dan Munson (2017) merumuskan empat taktik utama untuk meningkatkan keandalan dan pemeliharaan. Taktik keandalan terdiri atas dua hal, yaitu memperbaiki komponen individual dan menyediakan redundansi. Taktik pemeliharaan juga terdiri atas dua hal, yaitu menerapkan atau memperbaiki pemeliharaan preventif serta meningkatkan kapabilitas atau kecepatan reparasi. Keberhasilan keempat taktik tersebut menuntut keterlibatan karyawan melalui pelatihan keterampilan, sistem penghargaan, dan pemberdayaan, serta prosedur yang baik seperti pembersihan, pelumasan, pemantauan, dan pencatatan yang akurat. Dengan demikian, pemeliharaan yang baik pada dasarnya merupakan perpaduan antara sistem teknis dan sistem manusia.</p>`
    },
    {
      no: "11.3",
      title: "Keandalan Sistem: Pengukuran dan Perbaikan",
      body: `<p>Sistem operasi tersusun atas serangkaian komponen yang saling terkait dan masing-masing menjalankan fungsi tertentu. Apabila komponen tersusun secara seri, kegagalan satu komponen saja sudah cukup untuk menggagalkan keseluruhan sistem. Oleh karena itu, pemahaman kuantitatif atas keandalan sistem menjadi titik awal setiap upaya perbaikan.</p>
<h5>11.3.1 Keandalan Sistem Seri</h5>
<p>Keandalan sistem seri (Rs) dihitung sebagai hasil kali keandalan setiap komponen dengan rumus Rs = R1 x R2 x R3 x ... x Rn, dengan R1 adalah keandalan komponen pertama, R2 keandalan komponen kedua, dan seterusnya (Heizer, Render dan Munson, 2017). Rumus tersebut mengasumsikan setiap komponen bersifat independen dan keandalan dinyatakan sebagai probabilitas, sehingga keandalan 0,90 berarti komponen bekerja sebagaimana mestinya 90 persen dari waktu dan gagal 10 persen dari waktu. Implikasi rumus ini sangat penting, yaitu keandalan sistem selalu lebih rendah daripada keandalan komponen terlemahnya, dan keandalan menurun cepat seiring bertambahnya jumlah komponen. Sistem dengan 50 komponen seri yang masing-masing andal 99,5 persen hanya memiliki keandalan keseluruhan sekitar 78 persen, dan apabila jumlah komponen menjadi 100, keandalan keseluruhan turun menjadi sekitar 60 persen.</p>
<p>Sebagai ilustrasi, proses persetujuan pembiayaan pada sebuah bank yang melalui tiga analis secara berurutan dengan keandalan 0,90, 0,80, dan 0,99 menghasilkan keandalan proses sebesar 0,90 x 0,80 x 0,99 = 0,713. Angka tersebut lebih rendah daripada kinerja analis mana pun secara individual karena probabilitas kesalahan bersifat kumulatif. Implikasi manajerialnya, manajer perlu memetakan proses pelayanan sebagai rangkaian komponen, mengidentifikasi mata rantai dengan keandalan terendah, kemudian memperbaikinya melalui pelatihan, penyederhanaan proses, otomasi, atau redundansi.</p>
<h5>11.3.2 Tingkat Kegagalan dan MTBF</h5>
<p>Satuan dasar pengukuran keandalan adalah tingkat kegagalan produk (<em>failure rate</em>). Tingkat kegagalan dapat dinyatakan dalam dua bentuk, yaitu persentase kegagalan FR(%) = (jumlah kegagalan / jumlah unit yang diuji) x 100 persen, dan jumlah kegagalan per satuan waktu operasi FR(N) = jumlah kegagalan / jumlah jam-unit waktu operasi (Heizer, Render dan Munson, 2017). Ukuran yang paling lazim digunakan dalam analisis keandalan adalah <em>mean time between failures</em> (MTBF), yaitu waktu rata-rata yang diharapkan antara satu perbaikan dan kegagalan berikutnya, yang dihitung sebagai kebalikan dari FR(N) dengan rumus MTBF = 1 / FR(N).</p>
<p>Cara penggunaannya dapat dijelaskan melalui contoh pengujian. Apabila 20 unit sistem pendingin diuji selama 1.000 jam dan dua unit gagal, maka FR(%) = 2/20 x 100 persen = 10 persen. Waktu operasi total adalah 20.000 jam-unit dikurangi waktu tidak beroperasi akibat kegagalan, sehingga FR(N) dan MTBF dapat dihitung dari data tersebut. Nilai MTBF selanjutnya digunakan untuk memperkirakan frekuensi kegagalan pada suatu periode operasi, misalnya per penerbangan atau per bulan produksi. Manajer memanfaatkan MTBF untuk menetapkan interval pemeliharaan preventif, menentukan kebutuhan suku cadang, dan mengevaluasi pemasok peralatan.</p>
<h5>11.3.3 Redundansi Cadangan dan Redundansi Paralel</h5>
<p>Taktik kedua peningkatan keandalan adalah redundansi (<em>redundancy</em>), yaitu penggunaan komponen cadangan atau jalur paralel agar sistem tetap memiliki jalan keluar apabila satu komponen gagal (Heizer, Render dan Munson, 2017). Pada redundansi cadangan (<em>backup</em>), keandalan gabungan dihitung sebagai probabilitas komponen utama bekerja ditambah hasil kali probabilitas komponen cadangan bekerja dengan probabilitas cadangan tersebut dibutuhkan. Sebagai contoh, komponen berkeandalan 0,80 yang didukung cadangan berkeandalan 0,75 menghasilkan keandalan 0,80 + (0,75 x 0,20) = 0,95. Pada redundansi paralel, keandalan sistem dihitung dengan mengurangkan satu dengan hasil kali probabilitas kegagalan seluruh jalur, sehingga tiga jalur paralel yang masing-masing cukup andal dapat menghasilkan keandalan sistem di atas 0,999.</p>
<p>Redundansi banyak diterapkan pada sistem yang menuntut ketersediaan tinggi, misalnya pembangkit cadangan pada rumah sakit, pasokan listrik ganda pada pusat data, dan sistem hidrolik rangkap pada pesawat terbang. Namun, redundansi menimbulkan biaya investasi dan pemeliharaan tambahan. Oleh karena itu, manajer perlu menimbang nilai kerugian akibat kegagalan terhadap biaya redundansi, dan memprioritaskan redundansi pada komponen yang paling kritis serta paling rendah keandalannya.</p>`
    },
    {
      no: "11.4",
      title: "Pemeliharaan: Preventif, Breakdown, dan Analisis Biayanya",
      body: `<p>Terdapat dua jenis pemeliharaan yang menjadi pilihan kebijakan manajer operasi. <em>Preventive maintenance</em> adalah rencana yang mencakup pemantauan, inspeksi rutin, servis berkala, dan penjagaan fasilitas dalam kondisi baik dengan tujuan menemukan potensi kegagalan sebelum terjadi. <em>Breakdown maintenance</em> adalah pemeliharaan remedial yang dilakukan ketika pemeliharaan preventif gagal dan peralatan harus diperbaiki secara darurat atau prioritas (Heizer, Render dan Munson, 2017). Dari kedua definisi tersebut dapat disimpulkan bahwa pemeliharaan preventif bersifat proaktif dan terjadwal, sedangkan pemeliharaan breakdown bersifat reaktif dan tidak terencana, sehingga umumnya lebih mahal dan lebih mengganggu.</p>
<h5>11.4.1 Kapan Pemeliharaan Preventif Layak Dilakukan</h5>
<p>Pemeliharaan preventif mensyaratkan kemampuan memperkirakan kapan sistem memerlukan servis atau akan gagal. Kegagalan tidak terdistribusi merata sepanjang umur produk. Pada awal umur pakai sering terjadi tingkat kegagalan tinggi yang disebut <em>infant mortality</em>, yang umumnya bukan disebabkan cacat produk melainkan pemakaian yang tidak tepat. Fenomena ini mendorong produsen elektronik melakukan <em>burn-in</em>, yaitu serangkaian pengujian sebelum pengiriman, serta membangun layanan purnajual berupa instalasi dan pelatihan pengguna. Setelah produk melewati masa awal tersebut, distribusi MTBF dapat dipelajari. Apabila distribusi MTBF memiliki deviasi standar kecil, peralatan tersebut merupakan kandidat yang baik untuk pemeliharaan preventif karena waktu kegagalannya dapat diprediksi. Sebaliknya, apabila biaya pemeliharaan preventif sangat kecil, kebijakan preventif tetap layak dijalankan meskipun distribusi kegagalannya lebar. Catatan riwayat mesin, biaya reparasi, dan waktu perbaikan menjadi masukan penting dalam keputusan ini, dan pada praktik modern dikelola melalui sistem manajemen pemeliharaan terkomputerisasi yang menghasilkan perintah kerja, daftar kebutuhan material, dan laporan analisis biaya.</p>
<h5>11.4.2 Membandingkan Biaya Preventif dan Breakdown</h5>
<p>Pandangan tradisional menggambarkan adanya titik optimum yang menyeimbangkan kenaikan biaya pemeliharaan preventif dengan penurunan biaya breakdown. Namun, kurva biaya tradisional sering mengabaikan biaya penuh sebuah kegagalan, seperti persediaan pengaman yang harus disimpan untuk mengantisipasi henti mesin, dampak negatif terhadap keselamatan dan moral karyawan, serta kerusakan jadwal pengiriman yang menghancurkan hubungan pelanggan dan penjualan masa depan (Heizer, Render dan Munson, 2017). Apabila seluruh biaya tersebut diperhitungkan, titik optimum bergeser ke arah komitmen pemeliharaan yang jauh lebih besar, dan biaya total minimum tercapai ketika sistem praktis hanya gagal akibat kejadian luar biasa yang tidak terduga.</p>
<p>Perbandingan kuantitatif kedua kebijakan dilakukan melalui empat langkah, yaitu: pertama, menghitung ekspektasi jumlah kegagalan per periode berdasarkan data historis apabila perusahaan berjalan tanpa kontrak pemeliharaan; kedua, menghitung ekspektasi biaya breakdown per periode sebagai hasil kali ekspektasi jumlah kegagalan dengan biaya per kegagalan; ketiga, menghitung biaya kebijakan preventif sebagai penjumlahan biaya kegagalan yang masih tersisa dan biaya kontrak servis; keempat, memilih kebijakan dengan biaya total terendah. Sebagai contoh, sebuah kantor jasa yang secara historis mengalami rata-rata 1,6 kerusakan mesin cetak per bulan dengan kerugian 300 dolar per kerusakan menanggung ekspektasi biaya 480 dolar per bulan. Apabila kontrak pemeliharaan preventif seharga 150 dolar per bulan menurunkan kerusakan menjadi satu kali per bulan, total biaya kebijakan preventif adalah 450 dolar sehingga kontrak tersebut layak diambil. Keputusan semacam ini hanya valid apabila perusahaan memiliki catatan pemeliharaan yang baik.</p>
<h5>11.4.3 Meningkatkan Kapabilitas Reparasi</h5>
<p>Karena keandalan dan pemeliharaan preventif tidak pernah sempurna, perusahaan tetap memerlukan kapabilitas reparasi. Pilihan pelaksana reparasi membentang pada suatu kontinum, mulai dari operator mesin itu sendiri, departemen pemeliharaan internal, layanan lapangan pabrikan, hingga pengembalian peralatan ke depo servis. Bergerak ke arah pabrikan dan depo umumnya menaikkan kompetensi teknis, namun juga menaikkan biaya dan memperpanjang waktu peralatan tidak tersedia. Sebaliknya, mendekatkan reparasi ke operator mempercepat penanganan dan menumbuhkan rasa memiliki. Oleh karena itu, manajer perlu menetapkan jenis kerusakan mana yang ditangani di setiap tingkat, serta memastikan ketersediaan suku cadang, teknisi multi keterampilan, dan prosedur eskalasi yang jelas.</p>
<table class="bk-table"><caption>Tabel 11.1 Perbandingan Preventive Maintenance dan Breakdown Maintenance</caption>
<thead><tr><th>Aspek</th><th>Preventive Maintenance</th><th>Breakdown Maintenance</th></tr></thead>
<tbody>
<tr><td>Sifat</td><td>Proaktif, terjadwal, berbasis data MTBF dan kondisi mesin</td><td>Reaktif, darurat, dilakukan setelah kegagalan terjadi</td></tr>
<tr><td>Biaya langsung</td><td>Biaya inspeksi, servis, dan penggantian komponen terencana</td><td>Biaya reparasi darurat, lembur, dan suku cadang mendesak</td></tr>
<tr><td>Biaya tersembunyi</td><td>Relatif kecil, kapasitas hilang dapat dijadwalkan pada permintaan rendah</td><td>Persediaan pengaman, keterlambatan pengiriman, kerusakan moral dan reputasi</td></tr>
<tr><td>Kesesuaian</td><td>Peralatan kritis dengan distribusi kegagalan sempit atau biaya kegagalan besar</td><td>Peralatan tidak kritis dengan biaya reparasi rendah dan dampak kegagalan kecil</td></tr>
<tr><td>Prasyarat</td><td>Catatan riwayat mesin, sistem informasi pemeliharaan, disiplin jadwal</td><td>Kapabilitas reparasi cepat dan ketersediaan suku cadang</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017) serta Slack, Brandon-Jones dan Burgess (2022)</td></tr></tfoot></table>`
    },
    {
      no: "11.5",
      title: "Autonomous Maintenance dan Total Productive Maintenance",
      body: `<p>Kebijakan pemeliharaan modern menekankan keterlibatan operator sebagai garis pertahanan pertama. <em>Autonomous maintenance</em> adalah pendekatan ketika operator bermitra dengan personel pemeliharaan untuk mengamati, memeriksa, menyetel, membersihkan, dan melaporkan kondisi peralatannya sendiri (Heizer, Render dan Munson, 2017). Pendekatan ini sejalan dengan konsep pemberdayaan karyawan, karena operator yang setiap hari berinteraksi dengan mesin berada pada posisi terbaik untuk mendeteksi gejala awal kegagalan, seperti getaran, suara, atau suhu yang tidak wajar. Dengan demikian, karyawan dapat memprediksi kegagalan, mencegah kerusakan, dan memperpanjang umur peralatan sebelum masalah membesar.</p>
<p>Pada tingkat yang lebih luas, banyak perusahaan mengadopsi <em>total productive maintenance</em> (TPM), yaitu pendekatan yang menggabungkan prinsip manajemen kualitas total dengan pandangan strategis atas pemeliharaan, mulai dari desain proses dan peralatan sampai pemeliharaan preventif. TPM mencakup empat pilar praktik, yaitu: pertama, merancang mesin yang andal, mudah dioperasikan, dan mudah dipelihara; kedua, menekankan biaya kepemilikan total (<em>total cost of ownership</em>) pada saat pembelian mesin sehingga biaya servis dan pemeliharaan ikut diperhitungkan; ketiga, menyusun rencana pemeliharaan preventif yang memanfaatkan praktik terbaik operator, departemen pemeliharaan, dan depo servis; keempat, melatih operator untuk memelihara mesinnya sendiri dan bermitra dengan personel pemeliharaan (Heizer, Render dan Munson, 2017). Kemajuan teknologi sensor, simulasi, dan sistem pakar memperkuat TPM karena kondisi mesin kini dapat dipantau secara waktu nyata, sehingga berkembang praktik <em>predictive maintenance</em> berbasis data kondisi aktual.</p>
<p>Kasus Frito-Lay memberikan gambaran penerapan TPM yang matang. Pabrik makanan ringan tersebut beroperasi dengan volume tinggi sehingga setiap satu persen waktu henti yang tidak terjadwal diperkirakan mengurangi laba tahunan sekitar 200 ribu dolar. Melalui program yang mengajarkan operator untuk mengidentifikasi dan langsung menangani masalah, tinjauan standar pada awal, tengah, dan akhir setiap giliran kerja, serta teknisi multi keterampilan yang bekerja penuh selama 24 jam, pabrik tersebut mampu menekan waktu henti tidak terjadwal jauh di bawah tolok ukur kelas dunia sebesar dua persen (Heizer, Render dan Munson, 2017). Di Indonesia, praktik serupa telah lama dijalankan pabrik-pabrik dalam ekosistem manufaktur otomotif seperti Toyota Motor Manufacturing Indonesia dan grup Astra yang mengadopsi TPM sebagai bagian dari sistem produksi ramping, serta industri pupuk dan petrokimia yang menerapkan program keandalan pabrik untuk memperpanjang jarak antar <em>turnaround</em>. Implikasi manajerialnya, keberhasilan TPM lebih ditentukan oleh budaya disiplin, pelatihan, dan kepemilikan lintas fungsi daripada oleh kecanggihan teknologi semata.</p>`
    },
    {
      no: "11.6",
      title: "Manajemen Proyek untuk Pemeliharaan dan Perbaikan Keandalan",
      body: `<p>Kegiatan perbaikan keandalan berskala besar, seperti overhaul pembangkit, <em>turnaround</em> kilang, instalasi peralatan pengendali polusi, atau implementasi sistem informasi pemeliharaan, pada dasarnya merupakan proyek, yaitu serangkaian tugas terkait yang diarahkan pada satu keluaran utama dengan waktu mulai dan tenggat yang jelas. Overhaul pembangkit OUC, misalnya, memuat sekitar 1.800 tugas berbeda dan menyerap 72.000 jam kerja sehingga mustahil dikelola tanpa disiplin manajemen proyek (Heizer, Render dan Munson, 2017). Manajemen proyek meliputi tiga fase, yaitu perencanaan (penetapan sasaran, pendefinisian proyek, dan pengorganisasian tim), penjadwalan (mengaitkan orang, dana, dan pasokan dengan aktivitas serta mengaitkan antar aktivitas), dan pengendalian (memantau sumber daya, biaya, kualitas, dan anggaran serta merevisi rencana). Di Indonesia, <em>turnaround</em> kilang milik Pertamina merupakan contoh nyata proyek pemeliharaan raksasa yang melibatkan ribuan pekerja kontraktor dan harus selesai tepat waktu agar pasokan bahan bakar nasional tidak terganggu.</p>
<h5>11.6.1 Perencanaan dan Penjadwalan Proyek</h5>
<p>Perencanaan dimulai dengan <em>work breakdown structure</em> (WBS), yaitu uraian hierarkis proyek menjadi komponen yang kian rinci, mulai dari proyek, tugas utama, subtugas, sampai paket kerja beserta biayanya (Heizer, Render dan Munson, 2017). WBS memastikan tidak ada pekerjaan yang terlewat dan menjadi dasar estimasi kebutuhan orang, material, dan peralatan. Penjadwalan selanjutnya dapat menggunakan diagram Gantt, yaitu diagram batang horizontal yang menampilkan waktu mulai dan selesai setiap aktivitas pada garis waktu, yang sederhana dan murah namun kurang mampu menggambarkan saling ketergantungan antar aktivitas. Untuk proyek kompleks digunakan teknik jaringan PERT (<em>program evaluation and review technique</em>) dan CPM (<em>critical path method</em>) yang secara eksplisit memodelkan hubungan pendahulu antar aktivitas melalui diagram <em>activity on node</em>.</p>
<h5>11.6.2 Jalur Kritis, Variabilitas Waktu, dan Crashing</h5>
<p>Inti analisis PERT/CPM adalah penentuan jalur kritis (<em>critical path</em>), yaitu jalur waktu terpanjang melalui jaringan yang menentukan durasi penyelesaian proyek. Melalui perhitungan maju diperoleh waktu mulai dan selesai paling awal (ES dan EF), sedangkan perhitungan mundur menghasilkan waktu mulai dan selesai paling lambat (LS dan LF). Kelonggaran setiap aktivitas dihitung dengan rumus Slack = LS dikurangi ES atau LF dikurangi EF, dan aktivitas dengan kelonggaran nol adalah aktivitas kritis yang tidak boleh terlambat (Heizer, Render dan Munson, 2017). PERT menampung ketidakpastian dengan tiga estimasi waktu untuk setiap aktivitas, yaitu waktu optimistis a, waktu paling mungkin m, dan waktu pesimistis b. Waktu harapan aktivitas dihitung dengan rumus t = (a + 4m + b) / 6 dan variansnya [(b - a) / 6] kuadrat. Varians proyek adalah jumlah varians aktivitas pada jalur kritis, sehingga probabilitas proyek selesai sebelum tenggat tertentu dapat dihitung melalui nilai Z = (tenggat dikurangi waktu penyelesaian harapan) dibagi deviasi standar proyek pada distribusi normal. Bagi manajer pemeliharaan, perhitungan ini memungkinkan pernyataan yang jujur kepada manajemen puncak, misalnya bahwa peluang overhaul selesai dalam 16 minggu hanya sekitar 71 persen sehingga perlu cadangan waktu.</p>
<p>Apabila proyek harus dipercepat, dilakukan <em>crashing</em>, yaitu memperpendek durasi aktivitas dengan biaya tambahan serendah mungkin. Biaya percepatan per periode dihitung dengan rumus (biaya crash dikurangi biaya normal) dibagi (waktu normal dikurangi waktu crash), kemudian aktivitas pada jalur kritis dengan biaya percepatan termurah dipercepat satu periode, jaringan dihitung ulang, dan proses diulang sampai tenggat tercapai (Heizer, Render dan Munson, 2017). Teknik ini sangat relevan pada proyek pemeliharaan karena setiap hari tambahan mesin berhenti berarti kapasitas dan pendapatan yang hilang, sehingga membayar biaya percepatan sering kali lebih ekonomis daripada memperpanjang waktu henti. Namun, manajer juga perlu waspada terhadap keterbatasan PERT/CPM, antara lain estimasi waktu yang subjektif dan bahaya terlalu berfokus pada jalur kritis sehingga jalur hampir kritis dengan varians besar luput dari pemantauan.</p>`
    },
    {
      no: "11.7",
      title: "Manajemen Risiko Operasi dan Resiliensi",
      body: `<p>Keandalan komponen dan pemeliharaan terencana tidak menghapus seluruh kemungkinan gangguan. Operasi tetap menghadapi risiko dari pemasok yang gagal kirim, kesalahan manusia, kegagalan teknologi, bencana alam, pandemi, sampai serangan siber. Menurut Slack, Brandon-Jones dan Burgess (2022), manajemen risiko operasi mencakup empat rangkaian aktivitas, yaitu memahami dan mengidentifikasi potensi kegagalan, mencegah kegagalan terjadi, meminimalkan konsekuensi negatifnya (mitigasi), dan memulihkan operasi setelah kegagalan terjadi. Resiliensi operasi (<em>operational resilience</em>) adalah kemampuan organisasi menjalankan keempat aktivitas tersebut sehingga mampu menyerap gangguan dan kembali beroperasi normal dengan cepat. Dari uraian tersebut dapat disimpulkan bahwa organisasi yang resilien tidak berhenti pada pencegahan, melainkan secara sadar merencanakan apa yang dilakukan ketika pencegahan gagal.</p>
<h5>11.7.1 Identifikasi Kegagalan dan FMEA</h5>
<p>Sumber kegagalan dapat dikelompokkan menjadi kegagalan pasokan, kegagalan internal seperti mesin dan fasilitas, kegagalan manusia baik berupa kekeliruan maupun pelanggaran, kegagalan organisasi seperti desain proses yang buruk, kegagalan teknologi termasuk perangkat lunak, serta gangguan lingkungan eksternal (Slack, Brandon-Jones dan Burgess, 2022). Alat analisis yang lazim digunakan adalah <em>failure mode and effect analysis</em> (FMEA), yaitu prosedur sistematis untuk mengenali setiap moda kegagalan yang mungkin terjadi pada produk atau proses, menilai dampaknya, dan memprioritaskan tindakan pencegahan. Setiap moda kegagalan dinilai pada tiga dimensi dengan skala 1 sampai 10, yaitu tingkat keparahan dampak (<em>severity</em>), probabilitas keterjadian (<em>occurrence</em>), dan kemungkinan lolos dari deteksi (<em>detection</em>). Hasil kali ketiganya menghasilkan <em>risk priority number</em> (RPN) dengan rumus RPN = S x O x D, dan moda kegagalan dengan RPN tertinggi memperoleh prioritas perbaikan pertama. Analisis dapat diperkuat dengan telaah riwayat keluhan, data MTBF, dan kurva bak mandi (<em>bathtub curve</em>) yang menggambarkan tiga tahap kegagalan, yaitu tahap awal, tahap kehidupan normal, dan tahap keausan.</p>
<h5>11.7.2 Pencegahan, Mitigasi, dan Pemulihan</h5>
<p>Pencegahan kegagalan dilakukan antara lain melalui desain proses yang menghilangkan titik rawan, mekanisme anti salah (<em>fail-safeing</em> atau <em>poka-yoke</em>), pemeliharaan preventif dan prediktif, serta inspeksi dan audit berkala. Mitigasi diarahkan untuk mengurangi dampak ketika kegagalan tetap terjadi, misalnya melalui redundansi kapasitas, persediaan penyangga, diversifikasi pemasok pada lebih dari satu lokasi geografis, fleksibilitas proses yang memungkinkan produksi dipindahkan antar lini atau antar pabrik, dan perlindungan asuransi (Slack, Brandon-Jones dan Burgess, 2022). Pemulihan menuntut rencana kontinuitas bisnis (<em>business continuity plan</em>) yang menetapkan langkah tanggap darurat, urutan pemulihan proses kritis, komunikasi krisis kepada pelanggan dan regulator, serta pembelajaran pasca kejadian agar kegagalan serupa tidak terulang. Pandemi Covid-19 dan gangguan rantai pasok global yang menyertainya menegaskan pentingnya mitigasi struktural, dan banyak perusahaan Indonesia sejak saat itu menata ulang pasokannya dengan menambah pemasok domestik sebagai penyeimbang pemasok impor.</p>
<table class="bk-table"><caption>Tabel 11.2 Kerangka Manajemen Risiko dan Resiliensi Operasi</caption>
<thead><tr><th>Tahap</th><th>Pertanyaan Kunci</th><th>Alat dan Praktik Utama</th></tr></thead>
<tbody>
<tr><td>Identifikasi</td><td>Apa saja yang dapat gagal dan seberapa besar dampaknya</td><td>FMEA dan RPN, analisis riwayat kegagalan, MTBF, pemetaan risiko rantai pasok</td></tr>
<tr><td>Pencegahan</td><td>Bagaimana mencegah kegagalan terjadi</td><td>Desain andal, poka-yoke, preventive dan predictive maintenance, TPM, pelatihan</td></tr>
<tr><td>Mitigasi</td><td>Bagaimana mengurangi dampak apabila kegagalan terjadi</td><td>Redundansi, persediaan penyangga, multi pemasok, fleksibilitas proses, asuransi</td></tr>
<tr><td>Pemulihan</td><td>Bagaimana kembali beroperasi normal secepat mungkin</td><td>Business continuity plan, disaster recovery, komunikasi krisis, pembelajaran pasca kejadian</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Slack, Brandon-Jones dan Burgess (2022) serta Heizer, Render dan Munson (2017)</td></tr></tfoot></table>
<p>Implikasi manajerial kerangka di atas adalah perlunya keseimbangan antara efisiensi dan ketangguhan. Operasi yang terlalu ramping tanpa cadangan apa pun memang murah pada kondisi normal, namun sangat rapuh terhadap gangguan. Sebaliknya, redundansi yang berlebihan memberatkan biaya. Manajer yang efektif menggunakan analisis risiko untuk menentukan secara selektif proses dan pasokan mana yang layak diberi lapisan perlindungan tambahan.</p>`
    },
    {
      no: "11.8",
      title: "Keandalan Layanan Teknologi Informasi dan Proyek Digital",
      body: `<p>Pada era digital, keandalan operasi tidak dapat dipisahkan dari keandalan sistem informasi karena hampir seluruh proses bisnis, mulai dari penjadwalan produksi sampai pembayaran pelanggan, berjalan di atas infrastruktur teknologi informasi. Turban, Pollard dan Wood (2021) menekankan bahwa pengembangan sistem harus dikelola melalui siklus hidup pengembangan sistem dan disiplin manajemen proyek agar sistem yang dihasilkan berfungsi sesuai kebutuhan pengguna dan tidak mengganggu operasi. Pendekatan DevOps, yang mengintegrasikan pengembang, penguji, dan personel operasi teknologi informasi dalam satu tim lintas fungsi, secara eksplisit menempatkan keandalan sebagai sasaran utama, yaitu gangguan bisnis yang minimal, keandalan kinerja yang maksimal, tingkat kegagalan rilis baru yang rendah, dan <em>mean time to recovery</em> yang singkat. Konsep tersebut sejajar dengan filosofi pemeliharaan pada pabrik, hanya saja objeknya berupa layanan perangkat lunak.</p>
<p>Proyek teknologi informasi memiliki risiko kegagalan yang tinggi apabila tata kelolanya lemah. Setiap proyek dibatasi oleh <em>triple constraint</em>, yaitu lingkup, waktu, dan biaya, yang saling terkait sehingga perubahan pada satu sisi selalu berdampak pada dua sisi lainnya (Turban, Pollard dan Wood, 2021). Kegagalan sering bersumber pada <em>scope creep</em>, yaitu penumpukan perubahan kecil yang secara agregat menggeser lingkup proyek tanpa penyesuaian anggaran dan jadwal, serta pada budaya yang menghukum pembawa kabar buruk sehingga masalah disembunyikan sampai terlambat. Kasus bandara Berlin Brandenburg yang tertunda sembilan tahun dan sistem bagasi otomatis bandara Denver yang akhirnya ditinggalkan setelah menelan ratusan juta dolar menunjukkan mahalnya pengabaian studi kelayakan, pelibatan pemangku kepentingan, dan pengendalian perubahan (Turban, Pollard dan Wood, 2021). Praktik yang dianjurkan meliputi pembentukan <em>project management office</em>, dokumen <em>baseline</em> yang disepakati, laporan status berkala, tonggak capaian yang jelas, register risiko, serta keberanian menghentikan proyek yang tidak lagi layak tanpa terjebak pada biaya yang sudah tertanam (<em>sunk cost</em>).</p>
<p>Sisi lain keandalan teknologi informasi adalah kontinuitas layanan ketika terjadi insiden. Serangan siber terhadap sebuah bank syariah besar di Indonesia pada Mei 2023, yang membuat layanan kantor cabang dan aplikasi seluler terganggu selama beberapa hari, memperlihatkan bahwa gangguan digital kini berdampak langsung pada operasi inti dan kepercayaan nasabah. Oleh karena itu, organisasi perlu memiliki rencana pemulihan bencana (<em>disaster recovery plan</em>) yang mencakup pusat data cadangan, replikasi data, prosedur pengalihan layanan, dan pengujian berkala, sebagai bagian tidak terpisahkan dari rencana kontinuitas bisnis. Implikasi manajerialnya, investasi keandalan teknologi informasi harus dinilai dengan logika yang sama dengan pemeliharaan pabrik, yaitu membandingkan biaya pencegahan dan redundansi dengan ekspektasi kerugian akibat gangguan, termasuk kerugian reputasi yang sulit dipulihkan.</p>`
    },
    {
      no: "11.9",
      title: "Rangkuman",
      body: `<p>Keandalan dan resiliensi merupakan fondasi yang menopang seluruh keputusan operasi lainnya. Pemeliharaan mencakup semua aktivitas untuk menjaga peralatan tetap siap bekerja, sedangkan keandalan adalah probabilitas komponen berfungsi baik selama waktu tertentu pada kondisi tertentu. Keandalan sistem seri merupakan hasil kali keandalan komponennya sehingga menurun cepat seiring bertambahnya komponen, dan dapat diperbaiki melalui dua taktik, yaitu memperbaiki komponen individual dan menyediakan redundansi cadangan maupun paralel. Ukuran kuantitatif utama adalah tingkat kegagalan FR(%) dan FR(N) serta MTBF sebagai kebalikan dari FR(N), yang menjadi dasar penetapan interval pemeliharaan dan evaluasi peralatan.</p>
<p>Kebijakan pemeliharaan terentang dari <em>preventive maintenance</em> yang proaktif sampai <em>breakdown maintenance</em> yang reaktif, dan pilihan di antara keduanya ditentukan melalui perbandingan ekspektasi biaya dengan memperhitungkan biaya penuh kegagalan, bukan hanya biaya reparasi langsung. <em>Autonomous maintenance</em> dan <em>total productive maintenance</em> memperluas tanggung jawab pemeliharaan kepada operator dan mengaitkannya dengan desain mesin, biaya kepemilikan total, dan pelatihan, sebagaimana dipraktikkan Frito-Lay maupun pabrik manufaktur otomotif di Indonesia. Proyek pemeliharaan besar seperti overhaul dan <em>turnaround</em> dikelola dengan disiplin manajemen proyek melalui WBS, diagram Gantt, analisis jalur kritis PERT/CPM, perhitungan probabilitas penyelesaian, dan <em>crashing</em> ketika jadwal harus dipercepat.</p>
<p>Karena tidak semua kegagalan dapat dicegah, organisasi membangun resiliensi melalui empat tahap manajemen risiko operasi, yaitu identifikasi dengan alat seperti FMEA dan RPN, pencegahan, mitigasi, dan pemulihan yang ditopang rencana kontinuitas bisnis. Prinsip yang sama berlaku pada ranah digital, ketika keandalan layanan teknologi informasi dijaga melalui tata kelola proyek yang disiplin, pendekatan DevOps, serta rencana pemulihan bencana. Dengan demikian, manajer operasi yang efektif memandang pemeliharaan, keandalan, dan resiliensi bukan sebagai pusat biaya, melainkan sebagai investasi strategis yang melindungi kapasitas, reputasi, dan profitabilitas perusahaan.</p>`
    },
    {
      no: "11.10",
      title: "Daftar Pustaka",
      body: `<p>Heizer, J., Render, B. dan Munson, C. (2017). <em>Operations Management: Sustainability and Supply Chain Management</em>. Edisi 12. Pearson Education.</p>
<p>Slack, N., Brandon-Jones, A. dan Burgess, N. (2022). <em>Operations Management</em>. Edisi 10. Pearson Education.</p>
<p>Turban, E., Pollard, C. dan Wood, G. (2021). <em>Information Technology for Management: Driving Digital Transformation to Increase Local and Global Performance, Growth and Sustainability</em>. Edisi 12. John Wiley and Sons.</p>`
    }
  ]
};
