window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.otm = window.MBA_BOOK.otm || {};
window.MBA_BOOK.otm[6] = {
  bab: 6,
  judul: "MANAJEMEN PERSEDIAAN",
  sumber: "Heizer, Render dan Munson (2017), Operations Management 12e; Turban, Pollard dan Wood (2021), IT for Management 12e; Slack, Brandon-Jones dan Burgess (2022), Operations Management 10e",
  lo: [
    "LO1 Melakukan analisis ABC untuk mengklasifikasikan butir persediaan berdasarkan volume nilai tahunan.",
    "LO2 Menjelaskan dan menggunakan cycle counting untuk menjaga akurasi catatan persediaan.",
    "LO3 Menjelaskan dan menggunakan model EOQ untuk permintaan persediaan yang independen.",
    "LO4 Menghitung titik pemesanan ulang (reorder point) dan menjelaskan konsep safety stock.",
    "LO5 Menerapkan model production order quantity pada situasi penerimaan persediaan secara bertahap.",
    "LO6 Menjelaskan dan menggunakan model quantity discount dalam keputusan pembelian.",
    "LO7 Memahami service level serta model persediaan probabilistik, termasuk model single-period dan sistem fixed-period."
  ],
  sections: [
    {
      no: "6.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi keenam mata kuliah Manajemen Operasi dan Teknologi membahas manajemen persediaan sebagai salah satu keputusan operasi yang paling berpengaruh terhadap struktur biaya dan tingkat layanan perusahaan. Pembahasan dimulai dari arti penting, fungsi, dan jenis persediaan, dilanjutkan dengan teknik pengelolaan persediaan melalui analisis ABC, akurasi catatan, dan <em>cycle counting</em>, kemudian masuk ke model kuantitatif untuk permintaan independen yang menjawab dua pertanyaan mendasar, yaitu berapa banyak yang harus dipesan dan kapan pesanan harus dilakukan. Model yang dibahas mencakup <em>economic order quantity</em>, <em>production order quantity</em>, <em>quantity discount</em>, model probabilistik dengan <em>safety stock</em>, model <em>single-period</em>, dan sistem <em>fixed-period</em>. Sesi ini juga menyinggung peran teknologi informasi dalam menjaga visibilitas dan akurasi persediaan modern.</p>
      <p>Setelah menyelesaikan sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <ul>
        <li>Melakukan analisis ABC untuk mengklasifikasikan butir persediaan berdasarkan volume nilai tahunan.</li>
        <li>Menjelaskan dan menggunakan <em>cycle counting</em> untuk menjaga akurasi catatan persediaan.</li>
        <li>Menjelaskan dan menggunakan model EOQ untuk permintaan persediaan yang independen.</li>
        <li>Menghitung titik pemesanan ulang serta menjelaskan konsep <em>safety stock</em>.</li>
        <li>Menerapkan model <em>production order quantity</em>.</li>
        <li>Menjelaskan dan menggunakan model <em>quantity discount</em>.</li>
        <li>Memahami <em>service level</em> serta model persediaan probabilistik, termasuk model <em>single-period</em> dan sistem <em>fixed-period</em>.</li>
      </ul>`
    },
    {
      no: "6.2",
      title: "Arti Penting, Fungsi, dan Jenis Persediaan",
      body: `<p>Persediaan merupakan salah satu aset termahal bagi banyak perusahaan dan dapat mewakili hingga sekitar 50 persen dari total modal yang diinvestasikan (Heizer, Render dan Munson, 2017). Di satu sisi, pengurangan persediaan menurunkan biaya penyimpanan dan membebaskan modal kerja. Di sisi lain, persediaan yang terlalu rendah dapat menghentikan produksi dan mengecewakan pelanggan ketika barang tidak tersedia. Oleh karena itu, tujuan manajemen persediaan adalah menyeimbangkan investasi persediaan dengan tingkat layanan kepada pelanggan. Menurut Slack, Brandon-Jones dan Burgess (2022), persediaan pada dasarnya adalah akumulasi sumber daya yang timbul karena perbedaan waktu dan laju antara pasokan dan permintaan. Dari kedua pandangan tersebut dapat disimpulkan bahwa persediaan adalah instrumen penyangga antara pasokan dan permintaan yang keberadaannya harus dikelola secara sadar karena menyerap modal dalam jumlah besar.</p>
      <p>Persediaan menjalankan beberapa fungsi yang memberikan fleksibilitas bagi operasi perusahaan, yaitu: pertama, menyediakan pilihan barang untuk mengantisipasi permintaan pelanggan dan memisahkan perusahaan dari fluktuasi permintaan tersebut, sebagaimana lazim ditemukan pada bisnis ritel; kedua, memisahkan atau melakukan <em>decoupling</em> berbagai tahap proses produksi sehingga gangguan pada satu tahap tidak langsung menghentikan tahap berikutnya; ketiga, memanfaatkan diskon kuantitas karena pembelian dalam jumlah besar dapat menurunkan harga barang atau biaya pengirimannya; dan keempat, melindungi perusahaan dari inflasi dan kenaikan harga. Keempat fungsi tersebut menjelaskan alasan rasional perusahaan tetap memegang persediaan meskipun persediaan tersebut menimbulkan biaya.</p>
      <p>Untuk menjalankan fungsi tersebut, perusahaan memelihara empat jenis persediaan. Persediaan bahan baku adalah bahan yang telah dibeli namun belum diproses dan berfungsi memisahkan pemasok dari proses produksi. Persediaan barang dalam proses atau <em>work-in-process</em> adalah komponen atau bahan yang telah mengalami perubahan namun belum menjadi produk jadi; persediaan ini timbul karena adanya waktu siklus produksi, dan sebagian besar waktu siklus tersebut sesungguhnya merupakan waktu menunggu, sehingga pemendekan waktu siklus secara langsung menurunkan persediaan. Persediaan MRO mencakup perlengkapan pemeliharaan, perbaikan, dan operasi yang diperlukan untuk menjaga mesin dan proses tetap produktif, yang kebutuhannya sering tidak dapat dipastikan waktunya. Persediaan barang jadi adalah produk selesai yang menunggu pengiriman dan disimpan karena permintaan pelanggan di masa depan tidak diketahui secara pasti. Ringkasan keempat jenis persediaan disajikan pada Tabel 6.1.</p>
      <table class="bk-table">
        <caption>Tabel 6.1 Jenis Persediaan dan Alasan Keberadaannya</caption>
        <thead><tr><th>Jenis Persediaan</th><th>Wujud</th><th>Alasan Utama Keberadaan</th></tr></thead>
        <tbody>
          <tr><td>Bahan baku</td><td>Bahan yang dibeli dan belum diproses</td><td>Memisahkan variabilitas pemasok dari proses produksi</td></tr>
          <tr><td>Barang dalam proses (WIP)</td><td>Komponen setengah jadi di lantai produksi</td><td>Konsekuensi waktu siklus produksi yang belum selesai</td></tr>
          <tr><td>MRO</td><td>Perlengkapan pemeliharaan, perbaikan, dan operasi</td><td>Kebutuhan pemeliharaan yang waktunya tidak pasti</td></tr>
          <tr><td>Barang jadi</td><td>Produk selesai yang siap dijual</td><td>Permintaan pelanggan masa depan yang tidak diketahui</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017) dan Slack, Brandon-Jones dan Burgess (2022)</td></tr></tfoot>
      </table>
      <p>Implikasi manajerialnya, manajer operasi tidak cukup hanya mengetahui jumlah persediaan, melainkan harus memahami jenis dan fungsi setiap persediaan agar kebijakan pengendaliannya tepat sasaran. Pengalaman Amazon.com menunjukkan bahwa pengelolaan persediaan yang presisi pada ratusan gudang dengan jutaan butir barang dapat menjadi sumber keunggulan bersaing melalui harga rendah, pengiriman cepat, dan pemenuhan pesanan yang nyaris bebas kesalahan (Heizer, Render dan Munson, 2017). Dengan demikian, manajemen persediaan bukan sekadar fungsi administratif, melainkan bagian dari strategi operasi.</p>`
    },
    {
      no: "6.3",
      title: "Pengelolaan Persediaan",
      body: `<h5>6.3.1 Analisis ABC</h5>
      <p>Langkah awal pengelolaan persediaan adalah mengklasifikasikan butir persediaan menurut tingkat kepentingannya. Analisis ABC adalah metode pembagian persediaan ke dalam tiga kelas berdasarkan volume nilai tahunan, yaitu hasil perkalian permintaan tahunan setiap butir dengan biaya per unitnya (Heizer, Render dan Munson, 2017). Metode ini merupakan penerapan prinsip Pareto pada persediaan, yang menyatakan bahwa terdapat "critical few and trivial many" (Heizer, Render dan Munson, 2017). Kelas A berisi butir dengan volume nilai tahunan tinggi; kelompok ini biasanya hanya sekitar 15 persen dari jumlah butir namun mewakili 70 sampai 80 persen dari total nilai penggunaan. Kelas B berisi butir dengan nilai menengah, sekitar 30 persen dari jumlah butir dengan 15 sampai 25 persen dari total nilai. Kelas C berisi butir bernilai rendah yang jumlahnya dapat mencapai 55 persen dari seluruh butir namun hanya sekitar 5 persen dari total nilai tahunan.</p>
      <p>Konsekuensi kebijakan dari klasifikasi tersebut adalah pengendalian yang berjenjang. Butir kelas A memperoleh pengembangan pemasok yang lebih intensif, pengendalian fisik yang lebih ketat, verifikasi catatan yang lebih sering, dan peramalan yang lebih cermat dibandingkan butir kelas B dan C. Batas persentase antar kelas tidak bersifat kaku karena tujuan utamanya adalah memisahkan butir yang penting dari butir yang kurang penting, dan kriteria selain nilai tahunan seperti biaya kekurangan yang tinggi, permasalahan pengiriman, atau permasalahan kualitas dapat menjadi alasan menaikkan kelas suatu butir. Sebagai contoh dalam konteks Indonesia, sebuah apotek jaringan seperti Kimia Farma dapat menempatkan obat keras bernilai tinggi dan berisiko kedaluwarsa sebagai kelas A yang dihitung dan diawasi setiap hari, sedangkan perlengkapan penunjang seperti kapas dan plester diperlakukan sebagai kelas C dengan pengendalian yang lebih longgar.</p>
      <h5>6.3.2 Akurasi Catatan dan Cycle Counting</h5>
      <p>Akurasi catatan merupakan prasyarat manajemen persediaan, penjadwalan produksi, dan penjualan karena keputusan pemesanan hanya bermakna apabila perusahaan mengetahui apa yang benar-benar dimilikinya. Akurasi dapat dijaga melalui sistem periodik yang menghitung persediaan pada interval tertentu, termasuk variasinya berupa sistem dua wadah atau <em>two-bin system</em>, atau melalui sistem perpetual yang mencatat setiap penerimaan dan pengeluaran secara berkelanjutan, misalnya dengan pemindai kode batang di gudang dan mesin kasir <em>point-of-sale</em> di toko (Heizer, Render dan Munson, 2017). Selain sistem pencatatan, akurasi menuntut keamanan fisik berupa akses gudang yang terbatas, tata letak yang rapi, dan pelabelan lokasi penyimpanan yang benar.</p>
      <p>Meskipun pencatatan telah dilakukan dengan baik, catatan tetap harus diverifikasi melalui audit berkelanjutan yang disebut <em>cycle counting</em>, yaitu rekonsiliasi terus-menerus antara persediaan fisik dengan catatan persediaan (Heizer, Render dan Munson, 2017). Teknik ini memanfaatkan klasifikasi ABC: butir kelas A dihitung paling sering, misalnya sebulan sekali, butir kelas B setiap triwulan, dan butir kelas C setiap enam bulan, sehingga setiap hari hanya sebagian kecil butir yang dihitung oleh petugas terlatih. Sebagai ilustrasi, apabila sebuah distributor memiliki 500 butir kelas A yang dihitung setiap 20 hari kerja, maka setiap hari cukup dihitung 25 butir kelas A. Dibandingkan penghitungan fisik tahunan yang menghentikan operasi, <em>cycle counting</em> menghilangkan gangguan produksi, menghapus penyesuaian persediaan tahunan yang besar, memungkinkan penelusuran penyebab ketidaksesuaian, dan menjaga catatan tetap akurat sepanjang tahun. Oleh karena itu, banyak perusahaan kelas dunia menjadikan teknik ini sebagai praktik baku.</p>
      <h5>6.3.3 Pengendalian Persediaan pada Sektor Jasa</h5>
      <p>Sektor jasa, khususnya perdagangan besar dan eceran, memegang persediaan dalam jumlah besar sehingga pengendaliannya menentukan keberhasilan usaha. Dalam ritel dikenal istilah <em>shrinkage</em>, yaitu persediaan yang tidak dapat dipertanggungjawabkan antara saat penerimaan dan saat penjualan akibat kerusakan, pencurian, maupun administrasi yang buruk, serta <em>pilferage</em> untuk pencurian dalam jumlah kecil (Heizer, Render dan Munson, 2017). Kehilangan persediaan ritel sebesar 1 persen dari penjualan sudah tergolong baik, sedangkan pada banyak toko angka tersebut melampaui 3 persen sehingga dampaknya terhadap laba sangat besar. Teknik yang dapat diterapkan meliputi seleksi, pelatihan, dan pendisiplinan karyawan yang baik, pengendalian ketat atas kiriman yang masuk dengan kode batang dan RFID, serta pengendalian efektif atas seluruh barang yang keluar dari fasilitas melalui label magnetik, pengamatan langsung, dan kamera pengawas. Dalam konteks Indonesia, jaringan minimarket seperti Indomaret dan Alfamart menggabungkan mesin kasir <em>point-of-sale</em>, penghitungan berkala di tingkat gerai, dan audit internal untuk menekan <em>shrinkage</em> pada ribuan gerai yang tersebar secara geografis.</p>`
    },
    {
      no: "6.4",
      title: "Permintaan Independen dan Biaya Persediaan",
      body: `<p>Model pengendalian persediaan dibedakan menurut sifat permintaannya. Permintaan independen adalah permintaan suatu butir yang tidak bergantung pada permintaan butir lain, misalnya permintaan lemari pendingin, sedangkan permintaan dependen adalah permintaan yang diturunkan dari kebutuhan produk lain, misalnya permintaan komponen lemari pendingin yang mengikuti rencana produksi produk akhirnya (Heizer, Render dan Munson, 2017). Bab ini memusatkan perhatian pada permintaan independen yang lazim dijumpai pada barang jadi dan barang dagangan, sedangkan permintaan dependen dikelola melalui <em>material requirements planning</em> yang dibahas pada sesi lain.</p>
      <p>Terdapat tiga kelompok biaya yang relevan dalam model persediaan. Biaya penyimpanan atau <em>holding cost</em> adalah biaya untuk menyimpan atau membawa persediaan sepanjang waktu, yang mencakup biaya gedung, penanganan bahan, tenaga kerja gudang, biaya investasi atas modal yang tertanam, serta penyusutan, keusangan, dan kehilangan. Banyak perusahaan meremehkan biaya ini; total biaya penyimpanan tahunan umumnya berada pada kisaran 26 persen dari nilai persediaan dan dapat melampaui 40 persen pada industri berteknologi tinggi dan produk mode yang cepat usang (Heizer, Render dan Munson, 2017). Biaya pemesanan atau <em>ordering cost</em> meliputi biaya formulir, pemrosesan pesanan, dan dukungan administrasi pembelian. Apabila barang diproduksi sendiri, padanan biaya pemesanan adalah biaya penyiapan atau <em>setup cost</em>, yaitu biaya mempersiapkan mesin atau proses untuk memproduksi suatu pesanan. Rincian komponen biaya penyimpanan disajikan pada Tabel 6.2.</p>
      <table class="bk-table">
        <caption>Tabel 6.2 Komponen Biaya Penyimpanan Persediaan</caption>
        <thead><tr><th>Kategori Biaya</th><th>Contoh Komponen</th><th>Perkiraan Persentase dari Nilai Persediaan</th></tr></thead>
        <tbody>
          <tr><td>Biaya gedung</td><td>Sewa atau penyusutan gudang, pajak, asuransi bangunan</td><td>Sekitar 6 persen</td></tr>
          <tr><td>Penanganan bahan</td><td>Sewa atau penyusutan peralatan, listrik, biaya operasi</td><td>Sekitar 3 persen</td></tr>
          <tr><td>Tenaga kerja</td><td>Penerimaan, pergudangan, keamanan</td><td>Sekitar 3 persen</td></tr>
          <tr><td>Biaya investasi</td><td>Biaya modal atau bunga, pajak dan asuransi atas persediaan</td><td>Sekitar 11 persen</td></tr>
          <tr><td>Kehilangan dan keusangan</td><td>Pencurian, barang rusak, produk usang</td><td>Sekitar 3 persen</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017)</td></tr></tfoot>
      </table>
      <p>Dalam lingkungan manufaktur, biaya penyiapan berkorelasi erat dengan waktu penyiapan mesin. Dengan perencanaan yang baik, sebagian besar pekerjaan penyiapan dapat dilakukan sebelum mesin dihentikan sehingga waktu penyiapan turun drastis; produsen kelas dunia mampu menurunkan penyiapan yang semula berjam-jam menjadi hitungan menit. Implikasinya penting bagi manajemen, karena penurunan biaya penyiapan menurunkan ukuran lot yang ekonomis, memperkecil persediaan, dan meningkatkan fleksibilitas produksi. Dengan demikian, perbaikan proses penyiapan merupakan pengungkit strategis, bukan sekadar perbaikan teknis di lantai pabrik.</p>`
    },
    {
      no: "6.5",
      title: "Model Economic Order Quantity (EOQ)",
      body: `<p>Model <em>economic order quantity</em> merupakan teknik pengendalian persediaan yang paling banyak digunakan untuk menjawab pertanyaan berapa banyak yang harus dipesan. Menurut Heizer, Render dan Munson (2017), EOQ adalah teknik yang meminimumkan jumlah biaya pemesanan dan biaya penyimpanan. Model ini bertumpu pada enam asumsi, yaitu: permintaan diketahui, relatif konstan, dan independen; <em>lead time</em> diketahui dan konsisten; penerimaan persediaan bersifat seketika dan lengkap dalam satu kiriman; diskon kuantitas tidak tersedia; biaya variabel hanya terdiri atas biaya pemesanan atau penyiapan dan biaya penyimpanan; serta kehabisan persediaan dapat dihindari sepenuhnya apabila pesanan dilakukan pada waktu yang tepat. Dengan asumsi tersebut, grafik tingkat persediaan terhadap waktu berbentuk gigi gergaji dengan persediaan maksimum sebesar Q dan persediaan rata-rata sebesar Q/2.</p>
      <p>Logika model ini adalah pertukaran antara dua biaya yang bergerak berlawanan arah. Semakin besar kuantitas pesanan, semakin sedikit frekuensi pemesanan sehingga biaya pemesanan tahunan turun, namun persediaan rata-rata membesar sehingga biaya penyimpanan tahunan naik. Dengan notasi Q sebagai jumlah unit per pesanan, D sebagai permintaan tahunan, S sebagai biaya pemesanan per pesanan, dan H sebagai biaya penyimpanan per unit per tahun, biaya pemesanan tahunan adalah (D/Q)S dan biaya penyimpanan tahunan adalah (Q/2)H. Kuantitas optimal Q* diperoleh pada titik ketika kedua biaya tersebut sama besar, sehingga diperoleh rumus:</p>
      <p><strong>Q* = &radic;(2DS/H)</strong></p>
      <p>Dari Q* dapat diturunkan jumlah pesanan yang diharapkan per tahun N = D/Q*, waktu antar pesanan T = jumlah hari kerja per tahun dibagi N, dan total biaya variabel tahunan TC = (D/Q)S + (Q/2)H. Apabila biaya pembelian ingin disertakan, total biaya menjadi TC = (D/Q)S + (Q/2)H + PD, dengan P sebagai harga per unit; komponen PD tidak memengaruhi pilihan Q selama harga tidak berubah menurut kuantitas. Sebagai ilustrasi dalam konteks Indonesia, sebuah distributor alat tulis di Bandung dengan permintaan 10.000 rim kertas per tahun, biaya pemesanan Rp200.000 per pesanan, dan biaya penyimpanan Rp1.000 per rim per tahun akan memperoleh Q* = &radic;(2 x 10.000 x 200.000/1.000) = 2.000 rim. Dengan 250 hari kerja per tahun, distributor tersebut memesan lima kali setahun dengan selang sekitar 50 hari kerja, dan total biaya pemesanan plus penyimpanan tahunannya sebesar Rp2.000.000.</p>
      <p>Kelebihan penting model EOQ adalah sifatnya yang <em>robust</em>, dalam arti "gives satisfactory answers even with substantial variation in its parameters" (Heizer, Render dan Munson, 2017). Kurva total biaya di sekitar titik minimum sangat landai, sehingga kesalahan estimasi permintaan, biaya pemesanan, atau biaya penyimpanan hanya menimbulkan kenaikan biaya total yang relatif kecil; kesalahan estimasi permintaan sebesar 50 persen misalnya hanya menaikkan biaya total sekitar 2 persen. Implikasi manajerialnya, manajer tidak perlu menunda penggunaan model hanya karena parameter biayanya sulit diukur dengan presisi, karena jawaban model tetap layak dipakai sebagai pedoman kebijakan pemesanan.</p>`
    },
    {
      no: "6.6",
      title: "Titik Pemesanan Ulang dan Safety Stock",
      body: `<p>Setelah kuantitas pesanan ditetapkan, pertanyaan berikutnya adalah kapan pesanan harus dilakukan. Dalam kenyataannya terdapat tenggang waktu antara penempatan pesanan dan penerimaan barang yang disebut <em>lead time</em>, yang dapat berkisar dari beberapa jam hingga beberapa bulan. Keputusan kapan memesan dinyatakan dalam bentuk titik pemesanan ulang atau <em>reorder point</em>, yaitu tingkat persediaan pada saat tindakan pengisian kembali harus dilakukan (Heizer, Render dan Munson, 2017). Apabila permintaan harian d dan <em>lead time</em> L keduanya konstan, maka:</p>
      <p><strong>ROP = d x L</strong>, dengan d = D dibagi jumlah hari kerja per tahun.</p>
      <p>Sebagai contoh, sebuah gerai gawai di Jakarta dengan permintaan 8.000 unit telepon pintar per tahun dan 250 hari kerja memiliki permintaan harian 32 unit. Apabila pengiriman dari pusat distribusi memerlukan 3 hari kerja, gerai harus menempatkan pesanan ketika persediaan turun menjadi 96 unit. Apabila pengiriman kadang terlambat satu hari, gerai dapat menambahkan persediaan pengaman sebesar satu hari permintaan sehingga titik pemesanan ulang menjadi 128 unit.</p>
      <p>Ketika permintaan selama <em>lead time</em> atau <em>lead time</em> itu sendiri tidak konstan, perusahaan menambahkan <em>safety stock</em>, yaitu persediaan ekstra sebagai penyangga terhadap ketidakpastian, sehingga ROP = permintaan yang diharapkan selama <em>lead time</em> + <em>safety stock</em>. Besarnya <em>safety stock</em> mencerminkan pertukaran antara biaya kehabisan persediaan dan biaya menyimpan persediaan tambahan. Implikasi manajerialnya, titik pemesanan ulang menghubungkan kebijakan persediaan dengan kinerja pemasok; semakin pendek dan semakin andal <em>lead time</em> pemasok, semakin rendah titik pemesanan ulang dan persediaan pengaman yang harus ditanggung perusahaan. Penetapan besaran <em>safety stock</em> secara analitis dibahas pada sub-bab model probabilistik.</p>`
    },
    {
      no: "6.7",
      title: "Model Production Order Quantity",
      body: `<p>Model EOQ dasar mengasumsikan seluruh pesanan diterima sekaligus dalam satu waktu. Pada banyak situasi produksi, asumsi tersebut tidak berlaku karena persediaan mengalir masuk secara bertahap selama periode produksi, atau karena unit diproduksi dan dijual secara bersamaan. Untuk situasi tersebut digunakan model <em>production order quantity</em>, yaitu teknik kuantitas pesanan ekonomis yang diterapkan pada pesanan produksi (Heizer, Render dan Munson, 2017). Karena selama masa produksi barang juga dikonsumsi, persediaan maksimum tidak pernah mencapai Q, melainkan Q(1 - d/p), dengan p sebagai laju produksi harian dan d sebagai laju permintaan harian. Dengan menyamakan biaya penyiapan dan biaya penyimpanan diperoleh:</p>
      <p><strong>Q*p = &radic;(2DS / (H(1 - d/p)))</strong></p>
      <p>Rumus yang sama dapat dinyatakan dengan data tahunan, yaitu dengan mengganti d/p dengan rasio laju permintaan tahunan terhadap laju produksi tahunan. Karena faktor (1 - d/p) memperkecil biaya penyimpanan efektif, kuantitas produksi optimal model ini selalu lebih besar daripada EOQ dasar untuk data biaya yang sama. Heizer, Render dan Munson (2017) memberikan ilustrasi yang relevan dengan konteks Indonesia melalui contoh Race One Motors, produsen otomotif di Jakarta yang memproduksi subkomponen dengan laju 300 unit per hari dan menggunakannya 12.500 unit per tahun, sehingga kuantitas produksi ekonomisnya dihitung dengan model ini dan pabrik hanya memproduksi komponen tersebut pada sebagian waktu operasinya.</p>
      <p>Implikasi manajerial model ini bersifat ganda. Pertama, manajer produksi memperoleh ukuran lot yang meminimumkan jumlah biaya penyiapan dan penyimpanan pada kondisi produksi bertahap. Kedua, model ini memperlihatkan bahwa penurunan waktu dan biaya penyiapan akan menurunkan ukuran lot optimal, sehingga perusahaan dapat berproduksi dalam lot kecil secara ekonomis. Kemampuan berproduksi dalam lot kecil inilah yang menjadi fondasi sistem produksi ramping dan kustomisasi massal, sebagaimana ditunjukkan produsen elektronik yang mampu mengganti model produksi setelah lot yang sangat kecil.</p>`
    },
    {
      no: "6.8",
      title: "Model Quantity Discount",
      body: `<p>Diskon kuantitas adalah pengurangan harga per unit untuk pembelian dalam jumlah yang lebih besar, dan hampir seluruh perusahaan menawarkan atau menerima diskon semacam ini untuk sebagian produknya (Heizer, Render dan Munson, 2017). Kehadiran diskon menimbulkan pertukaran baru: pembelian dalam jumlah besar menurunkan biaya produk dan biaya pemesanan, namun menaikkan biaya penyimpanan karena persediaan rata-rata membesar. Oleh karena itu, biaya produk harus dimasukkan ke dalam perhitungan sehingga total biaya tahunan menjadi:</p>
      <p><strong>TC = (D/Q)S + (Q/2)IP + PD</strong></p>
      <p>dengan P sebagai harga per unit dan I sebagai biaya penyimpanan tahunan yang dinyatakan sebagai persentase harga. Biaya penyimpanan ditulis IP dan bukan H karena nilai barang yang disimpan ikut berubah ketika harga berubah pada setiap tingkat diskon. Rumus kuantitas optimal juga disesuaikan menjadi Q* = &radic;(2DS/(IP)) dan dihitung untuk setiap tingkat harga. Suatu EOQ disebut layak atau <em>feasible</em> apabila berada dalam rentang kuantitas yang memang memperoleh harga yang dipakai dalam perhitungannya.</p>
      <p>Prosedur penyelesaiannya terdiri atas dua langkah. Langkah pertama, mulai dari harga terendah dalam skedul diskon, hitung Q* untuk setiap harga secara berurutan menuju harga yang lebih tinggi sampai ditemukan EOQ pertama yang layak; kandidat kuantitas terbaik adalah EOQ layak pertama tersebut beserta seluruh kuantitas batas diskon atau <em>price-break quantity</em> untuk harga yang lebih rendah. Langkah kedua, hitung total biaya tahunan untuk setiap kandidat dan pilih kuantitas dengan total biaya terendah. Harga yang lebih tinggi daripada harga EOQ layak pertama tidak perlu diperiksa karena total biayanya pasti lebih besar. Hasil perhitungan sering menunjukkan bahwa mengejar harga termurah tidak selalu optimal karena tambahan biaya penyimpanan dapat melebihi penghematan harga.</p>
      <p>Dalam praktik, diskon kuantitas muncul dalam berbagai bentuk selain diskon seluruh unit, misalnya diskon inkremental yang hanya berlaku untuk unit di atas batas tertentu, biaya tetap pengiriman yang mendorong pembelian lebih besar, serta agregasi diskon menurut gabungan barang atau menurut total pembelian dalam kurun waktu tertentu. Sebagai contoh Indonesia, pedagang grosir sembako yang membeli minyak goreng dari distributor umumnya dihadapkan pada harga berjenjang per karton; pemilik usaha yang memahami model ini akan membandingkan penghematan harga dengan tambahan biaya gudang dan risiko kedaluwarsa sebelum memutuskan membeli pada jenjang harga terendah. Dengan demikian, model diskon kuantitas melatih manajer melihat total biaya, bukan sekadar harga beli per unit.</p>`
    },
    {
      no: "6.9",
      title: "Model Probabilistik, Service Level, dan Penentuan Safety Stock",
      body: `<p>Seluruh model sebelumnya mengasumsikan permintaan konstan dan pasti. Model probabilistik melonggarkan asumsi tersebut dan berlaku ketika permintaan tidak diketahui secara pasti namun dapat dinyatakan melalui distribusi probabilitas (Heizer, Render dan Munson, 2017). Konsep sentral dalam model ini adalah <em>service level</em>, yaitu probabilitas permintaan tidak melebihi pasokan selama <em>lead time</em>; <em>service level</em> merupakan komplemen dari probabilitas kehabisan persediaan, sehingga probabilitas <em>stockout</em> sebesar 5 persen setara dengan <em>service level</em> 95 persen. Ketidakpastian permintaan dihadapi dengan menambahkan <em>safety stock</em> pada titik pemesanan ulang sehingga ROP = d x L + ss.</p>
      <p>Terdapat dua pendekatan penentuan besaran <em>safety stock</em>. Pendekatan pertama digunakan apabila biaya kehabisan persediaan per unit dapat diperkirakan; untuk setiap alternatif <em>safety stock</em>, dihitung tambahan biaya penyimpanan dan ekspektasi biaya <em>stockout</em> tahunan, yaitu jumlah unit kekurangan pada setiap tingkat permintaan dikalikan probabilitasnya, dikalikan biaya <em>stockout</em> per unit, dikalikan jumlah pesanan per tahun, lalu dipilih alternatif dengan total biaya terendah. Pendekatan kedua digunakan apabila biaya <em>stockout</em> sulit diukur; manajer menetapkan target <em>service level</em> dan, dengan asumsi permintaan selama <em>lead time</em> berdistribusi normal, menghitung:</p>
      <p><strong>ROP = permintaan yang diharapkan selama lead time + Z&sigma;<sub>dLT</sub></strong>, sehingga <strong>safety stock = Z&sigma;<sub>dLT</sub></strong></p>
      <p>dengan Z sebagai jumlah simpangan baku sesuai target layanan, misalnya Z = 1,645 untuk 95 persen dan Z = 1,28 untuk 90 persen, dan &sigma;<sub>dLT</sub> sebagai simpangan baku permintaan selama <em>lead time</em>. Apabila data permintaan selama <em>lead time</em> tidak tersedia secara langsung, terdapat tiga variasi rumus sesuai sumber ketidakpastiannya, sebagaimana diringkas pada Tabel 6.3. Ketiganya mengasumsikan permintaan dan <em>lead time</em> saling independen.</p>
      <table class="bk-table">
        <caption>Tabel 6.3 Rumus Titik Pemesanan Ulang pada Berbagai Situasi Ketidakpastian</caption>
        <thead><tr><th>Situasi</th><th>Rumus ROP</th><th>Keterangan</th></tr></thead>
        <tbody>
          <tr><td>Permintaan variabel, lead time konstan</td><td>ROP = (rata-rata permintaan harian x L) + Z&sigma;<sub>d</sub>&radic;L</td><td>&sigma;<sub>d</sub> adalah simpangan baku permintaan harian</td></tr>
          <tr><td>Permintaan konstan, lead time variabel</td><td>ROP = (d x rata-rata lead time) + Z d &sigma;<sub>LT</sub></td><td>&sigma;<sub>LT</sub> adalah simpangan baku lead time dalam hari</td></tr>
          <tr><td>Permintaan dan lead time variabel</td><td>ROP = (rata-rata d x rata-rata L) + Z&sigma;<sub>dLT</sub></td><td>&sigma;<sub>dLT</sub> = &radic;(rata-rata L x &sigma;<sub>d</sub><sup>2</sup> + (rata-rata d)<sup>2</sup> x &sigma;<sub>LT</sub><sup>2</sup>)</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017)</td></tr></tfoot>
      </table>
      <p>Sebagai ilustrasi, sebuah toko elektronik dengan permintaan laptop rata-rata 15 unit per hari, simpangan baku 5 unit, dan <em>lead time</em> konstan 2 hari yang menargetkan layanan 90 persen memerlukan ROP = (15 x 2) + 1,28 x 5 x &radic;2, yaitu sekitar 39 unit, dengan <em>safety stock</em> sekitar 9 unit. Implikasi manajerial yang penting adalah biaya kebijakan persediaan meningkat secara tidak linier terhadap kenaikan <em>service level</em>, sehingga target layanan 98 atau 99 persen menuntut persediaan pengaman yang jauh lebih besar daripada target 90 persen. Manajer perlu menetapkan target layanan secara berbeda menurut kelas ABC dan kekritisan barang; rumah sakit misalnya menetapkan layanan yang sangat tinggi untuk perlengkapan penyelamat nyawa, sedangkan barang pelengkap dapat mentoleransi risiko <em>stockout</em> yang lebih besar.</p>`
    },
    {
      no: "6.10",
      title: "Model Single-Period",
      body: `<p>Model <em>single-period</em> menggambarkan situasi ketika pesanan hanya dilakukan satu kali untuk satu periode penjualan dan sisa barang pada akhir periode hanya bernilai kecil atau tidak bernilai sama sekali, sebagaimana terjadi pada surat kabar, majalah, produk roti, dan barang musiman (Heizer, Render dan Munson, 2017). Persoalan ini sering disebut <em>newsstand problem</em> karena pedagang koran harus memutuskan jumlah pesanan sebelum permintaan diketahui, dan barang yang tidak terjual tidak dapat disimpan untuk periode berikutnya. Keputusan optimal menyeimbangkan dua biaya marjinal, yaitu biaya kekurangan Cs = harga jual per unit dikurangi biaya per unit, dan biaya kelebihan Co = biaya per unit dikurangi nilai sisa per unit apabila ada. Tingkat layanan optimal ditentukan oleh rasio kritis:</p>
      <p><strong>Service level = Cs / (Cs + Co)</strong></p>
      <p>Kuantitas pesanan dinaikkan sampai probabilitas terjualnya seluruh unit mencapai rasio tersebut. Apabila permintaan berdistribusi normal dengan rata-rata &mu; dan simpangan baku &sigma;, kuantitas optimal adalah &mu; + Z&sigma;, dengan Z diperoleh dari rasio kritis; nilai Z bertanda positif apabila rasio kritis melebihi 0,5 dan bertanda negatif apabila di bawahnya. Sebagai contoh Indonesia, pedagang nasi bungkus di kawasan perkantoran Jakarta yang menjual rata-rata 120 porsi per hari dengan simpangan baku 15 porsi, margin keuntungan per porsi lebih besar daripada kerugian per porsi yang tidak terjual, akan memasak sedikit di atas rata-rata permintaan; sebaliknya, apabila kerugian barang sisa lebih besar daripada margin, jumlah masakan optimal justru di bawah rata-rata permintaan.</p>
      <p>Implikasi manajerial model ini sangat luas karena logika rasio kritis digunakan pada industri jasa mulai dari hotel dan maskapai penerbangan sampai peritel pakaian musiman. Model ini mengajarkan bahwa keputusan kuantitas untuk barang yang tidak tahan lama bukan sekadar meramal permintaan rata-rata, melainkan menimbang konsekuensi ekonomi dari kelebihan dan kekurangan secara eksplisit. Oleh karena itu, dua pedagang dengan permintaan yang sama dapat memiliki kuantitas optimal yang berbeda apabila struktur margin dan nilai sisa barangnya berbeda.</p>`
    },
    {
      no: "6.11",
      title: "Sistem Fixed-Period (P)",
      body: `<p>Seluruh model sebelumnya termasuk dalam sistem kuantitas tetap atau sistem Q, yaitu sistem yang memesan jumlah yang sama setiap kali pesanan dilakukan dan pemesanannya dipicu oleh peristiwa turunnya persediaan ke titik pemesanan ulang. Sistem seperti ini menuntut pemantauan berkelanjutan melalui sistem persediaan perpetual yang mencatat setiap penambahan dan pengambilan. Sebagai alternatif, sistem <em>fixed-period</em> atau sistem P melakukan pemesanan pada akhir periode yang tetap; pada saat itu persediaan dihitung dan yang dipesan hanyalah jumlah yang diperlukan untuk menaikkan persediaan ke tingkat target T, sehingga kuantitas pesanan berubah-ubah dari satu periode ke periode berikutnya (Heizer, Render dan Munson, 2017). Perbandingan kedua sistem disajikan pada Tabel 6.4.</p>
      <table class="bk-table">
        <caption>Tabel 6.4 Perbandingan Sistem Kuantitas Tetap (Q) dan Sistem Periode Tetap (P)</caption>
        <thead><tr><th>Aspek</th><th>Sistem Q</th><th>Sistem P</th></tr></thead>
        <tbody>
          <tr><td>Pemicu pesanan</td><td>Persediaan mencapai titik pemesanan ulang</td><td>Berakhirnya interval waktu peninjauan</td></tr>
          <tr><td>Kuantitas pesanan</td><td>Tetap sebesar Q setiap pesanan</td><td>Berubah, sebesar selisih target T dengan persediaan saat peninjauan</td></tr>
          <tr><td>Pemantauan persediaan</td><td>Berkelanjutan (perpetual)</td><td>Hanya pada saat peninjauan berkala</td></tr>
          <tr><td>Kebutuhan safety stock</td><td>Relatif lebih rendah, menutup risiko selama lead time</td><td>Lebih tinggi, menutup risiko selama interval peninjauan ditambah lead time</td></tr>
          <tr><td>Kesesuaian penggunaan</td><td>Barang bernilai tinggi yang layak dipantau ketat</td><td>Kunjungan pemasok rutin dan penggabungan pesanan beberapa barang</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017) dan Slack, Brandon-Jones dan Burgess (2022)</td></tr></tfoot>
      </table>
      <p>Keunggulan sistem P adalah kemudahan administratif karena tidak diperlukan penghitungan fisik setiap kali barang diambil, serta kecocokannya dengan praktik pemasok yang berkunjung secara rutin atau dengan keinginan pembeli menggabungkan pesanan beberapa barang untuk menghemat biaya pemesanan dan transportasi. Contohnya adalah perusahaan mesin penjual otomatis yang mengisi ulang mesinnya setiap hari tertentu, atau sales distributor barang konsumsi di Indonesia yang mengunjungi warung dan toko kelontong setiap pekan lalu mengisi persediaan sampai tingkat tertentu. Kelemahannya, karena persediaan tidak dipantau di antara dua peninjauan, terdapat kemungkinan kehabisan persediaan selama periode tersebut, sehingga sistem P memerlukan <em>safety stock</em> yang lebih besar dibandingkan sistem Q. Dengan demikian, pilihan antara sistem Q dan sistem P merupakan pertukaran antara biaya pemantauan dan biaya persediaan pengaman.</p>`
    },
    {
      no: "6.12",
      title: "Peran Teknologi Informasi dalam Manajemen Persediaan",
      body: `<p>Efektivitas seluruh model persediaan bergantung pada data permintaan, posisi persediaan, dan <em>lead time</em> yang akurat, dan di sinilah teknologi informasi berperan besar. Menurut Turban, Pollard dan Wood (2021), sistem manajemen persediaan berbasis komputer yang terhubung dengan kode batang, RFID, dan data transaksi <em>point-of-sale</em> memungkinkan perusahaan memantau posisi persediaan secara waktu nyata, memicu pemesanan ulang secara otomatis, dan mengurangi kesalahan manusia dalam pencatatan. Teknologi RFID melangkah lebih jauh daripada kode batang karena mampu membaca banyak label sekaligus tanpa garis pandang, sehingga penerimaan barang, penghitungan, dan pelacakan lokasi menjadi jauh lebih cepat. Selain itu, praktik <em>vendor-managed inventory</em> menyerahkan pemantauan dan pengisian ulang persediaan kepada pemasok berdasarkan data yang dibagikan pembeli, sehingga menurunkan biaya administrasi dan risiko kehabisan barang.</p>
      <p>Slack, Brandon-Jones dan Burgess (2022) menekankan bahwa sistem informasi persediaan menjalankan beberapa fungsi pokok, yaitu memutakhirkan catatan transaksi, menghasilkan pesanan secara otomatis berdasarkan aturan keputusan seperti EOQ dan ROP, menghasilkan laporan status dan peramalan permintaan, serta menjadi dasar analisis kinerja persediaan. Praktik Amazon.com yang memadukan otomasi gudang, pemindaian berulang pada setiap butir, dan algoritma penempatan barang menunjukkan bagaimana teknologi mengubah manajemen persediaan menjadi sumber keunggulan bersaing (Heizer, Render dan Munson, 2017). Dalam konteks Indonesia, platform dagang elektronik seperti Tokopedia dan jaringan ritel modern memanfaatkan data penjualan waktu nyata untuk menempatkan barang pada gudang yang paling dekat dengan konsentrasi permintaan, memperpendek waktu kirim, dan menekan persediaan total. Implikasi manajerialnya, investasi teknologi informasi persediaan harus dinilai bukan hanya dari penghematan biaya administrasi, melainkan dari perbaikan akurasi catatan, penurunan <em>safety stock</em>, dan peningkatan <em>service level</em> yang dimungkinkannya.</p>`
    },
    {
      no: "6.13",
      title: "Rangkuman",
      body: `<p>Persediaan merupakan investasi besar yang harus dikelola dengan menyeimbangkan biaya penyimpanan terhadap tingkat layanan pelanggan. Perusahaan memegang empat jenis persediaan, yaitu bahan baku, barang dalam proses, MRO, dan barang jadi, yang masing-masing menjalankan fungsi penyangga tertentu. Pengelolaan dimulai dari klasifikasi ABC yang memusatkan sumber daya pengendalian pada sedikit butir bernilai besar, dijaga oleh akurasi catatan melalui sistem perpetual maupun periodik, dan diverifikasi secara berkelanjutan melalui <em>cycle counting</em>. Pada sektor jasa dan ritel, pengendalian <em>shrinkage</em> dan <em>pilferage</em> menjadi penentu profitabilitas.</p>
      <p>Untuk permintaan independen, model EOQ menetapkan kuantitas pesanan yang meminimumkan jumlah biaya pemesanan dan penyimpanan, dan sifatnya yang <em>robust</em> membuatnya tetap berguna meskipun parameter biayanya tidak presisi. Titik pemesanan ulang menjawab pertanyaan kapan memesan berdasarkan permintaan harian dan <em>lead time</em>. Model <em>production order quantity</em> menyesuaikan EOQ untuk penerimaan bertahap, sedangkan model <em>quantity discount</em> menambahkan biaya produk ke dalam analisis ketika harga bervariasi menurut kuantitas. Ketika permintaan tidak pasti, model probabilistik menetapkan <em>safety stock</em> berdasarkan target <em>service level</em> dan variabilitas permintaan maupun <em>lead time</em>, model <em>single-period</em> menetapkan kuantitas optimal barang musiman melalui rasio kritis biaya kekurangan dan kelebihan, dan sistem <em>fixed-period</em> menawarkan alternatif peninjauan berkala dengan konsekuensi persediaan pengaman yang lebih besar.</p>
      <p>Bagi manajer, pesan utama sesi ini adalah bahwa keputusan persediaan selalu merupakan keputusan pertukaran biaya yang dapat dianalisis secara kuantitatif, dan kualitas keputusan tersebut bergantung pada akurasi data yang semakin ditopang oleh teknologi informasi seperti kode batang, RFID, dan sistem <em>point-of-sale</em>. Perusahaan yang menggabungkan disiplin analitis, pengendalian fisik yang baik, dan teknologi yang tepat dapat menjadikan manajemen persediaan sebagai sumber keunggulan bersaing sebagaimana ditunjukkan oleh Amazon.com maupun peritel modern di Indonesia.</p>`
    },
    {
      no: "6.14",
      title: "Daftar Pustaka",
      body: `<p>Heizer, J., Render, B. dan Munson, C. (2017). <em>Operations Management: Sustainability and Supply Chain Management</em>. 12th Edition. Pearson Education.</p>
      <p>Slack, N., Brandon-Jones, A. dan Burgess, N. (2022). <em>Operations Management</em>. 10th Edition. Pearson Education.</p>
      <p>Turban, E., Pollard, C. dan Wood, G. (2021). <em>Information Technology for Management: Driving Digital Transformation to Increase Local and Global Performance, Growth and Sustainability</em>. 12th Edition. John Wiley and Sons.</p>`
    }
  ]
};
