window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.otm = window.MBA_BOOK.otm || {};
window.MBA_BOOK.otm[5] = {
  bab: 5,
  judul: "MANAJEMEN KAPASITAS",
  sumber: "Heizer, Render dan Munson (2017), Operations Management 12e; Turban, Pollard dan Wood (2021), IT for Management 12e; Slack, Brandon-Jones dan Burgess (2022), Operations Management 10e",
  lo: [
    "LO1 Mendefinisikan sales and operations planning serta menjelaskan perannya dalam mengoordinasikan fungsi organisasi dan rantai pasokan.",
    "LO2 Mendefinisikan perencanaan agregat dan manajemen kapasitas serta menjelaskan kedudukannya dalam hierarki perencanaan operasi.",
    "LO3 Mengidentifikasi opsi kapasitas dan opsi permintaan dalam penyusunan rencana agregat serta membedakan strategi chase, level, demand management, dan mixed.",
    "LO4 Menyusun rencana agregat dengan metode grafis dan membandingkan biaya total beberapa alternatif rencana.",
    "LO5 Menyelesaikan persoalan perencanaan agregat dengan metode transportasi program linear.",
    "LO6 Menjelaskan penerapan perencanaan agregat pada sektor jasa termasuk pengelolaan antrean sebagai konsekuensi ketidakseimbangan kapasitas dan permintaan.",
    "LO7 Memahami dan menyelesaikan persoalan revenue management sederhana untuk memaksimalkan pendapatan dari kapasitas yang terbatas."
  ],
  sections: [
    {
      no: "5.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi kelima mata kuliah Manajemen Operasi dan Teknologi membahas manajemen kapasitas pada horizon perencanaan jangka menengah. Pembahasan dimulai dari kedudukan perencanaan agregat dalam hierarki perencanaan operasi dan konsep dasar pengukuran kapasitas, dilanjutkan dengan proses <em>sales and operations planning</em> yang menghasilkan rencana agregat, delapan opsi kapasitas dan permintaan beserta strategi <em>chase</em>, <em>level</em>, <em>demand management</em>, dan <em>mixed</em>, metode grafis dan metode transportasi untuk menyusun rencana agregat, penerapan perencanaan agregat pada sektor jasa termasuk pengelolaan antrean, dan diakhiri dengan <em>revenue management</em> sebagai teknik memaksimalkan pendapatan dari kapasitas yang terbatas. Materi ini menghubungkan keputusan strategis kapasitas jangka panjang yang dibahas pada sesi sebelumnya dengan penjadwalan jangka pendek yang dibahas pada sesi berikutnya.</p>
      <p>Setelah menyelesaikan sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <ul>
        <li>Mendefinisikan <em>sales and operations planning</em> serta menjelaskan perannya dalam mengoordinasikan fungsi organisasi dan rantai pasokan.</li>
        <li>Mendefinisikan perencanaan agregat dan manajemen kapasitas serta menjelaskan kedudukannya dalam hierarki perencanaan operasi.</li>
        <li>Mengidentifikasi opsi kapasitas dan opsi permintaan dalam penyusunan rencana agregat serta membedakan strategi <em>chase</em>, <em>level</em>, <em>demand management</em>, dan <em>mixed</em>.</li>
        <li>Menyusun rencana agregat dengan metode grafis dan membandingkan biaya total beberapa alternatif rencana.</li>
        <li>Menyelesaikan persoalan perencanaan agregat dengan metode transportasi program linear.</li>
        <li>Menjelaskan penerapan perencanaan agregat pada sektor jasa termasuk pengelolaan antrean.</li>
        <li>Memahami dan menyelesaikan persoalan <em>revenue management</em> sederhana.</li>
      </ul>`
    },
    {
      no: "5.2",
      title: "Kedudukan Manajemen Kapasitas dalam Hierarki Perencanaan",
      body: `<h5>5.2.1 Konsep Kapasitas dan Manajemen Kapasitas</h5>
      <p>Setiap operasi memiliki batas atas keluaran yang dapat dihasilkan dalam kurun waktu tertentu dengan sumber daya yang tersedia. Menurut Slack, Brandon-Jones dan Burgess (2022), kapasitas merupakan tingkat aktivitas bernilai tambah maksimum yang mampu dicapai suatu proses dalam kondisi operasi normal selama periode waktu tertentu. Sementara itu, Heizer, Render dan Munson (2017) memandang kapasitas sebagai jumlah keluaran yang dapat ditampung, diterima, disimpan, atau diproduksi oleh sebuah fasilitas dalam suatu periode. Dari kedua definisi tersebut dapat disimpulkan bahwa kapasitas selalu terikat pada dimensi waktu dan pada konfigurasi sumber daya, sehingga manajemen kapasitas pada hakikatnya adalah aktivitas menyesuaikan tingkat ketersediaan sumber daya dengan tingkat permintaan yang berfluktuasi agar pelanggan terlayani tanpa pemborosan sumber daya.</p>
      <p>Dalam analisis kapasitas dikenal beberapa ukuran dasar yang perlu dipahami sebelum menyusun rencana agregat. Kapasitas desain (<em>design capacity</em>) adalah keluaran maksimum teoretis dalam kondisi ideal, sedangkan kapasitas efektif (<em>effective capacity</em>) adalah kapasitas yang realistis dicapai setelah memperhitungkan waktu penyetelan, pemeliharaan, dan bauran produk. Dua ukuran kinerja yang lazim digunakan dihitung sebagai berikut: Utilisasi = Keluaran aktual / Kapasitas desain, dan Efisiensi = Keluaran aktual / Kapasitas efektif (Heizer, Render dan Munson, 2017). Sebagai ilustrasi, apabila sebuah pabrik pengolahan susu di Jawa Barat memiliki kapasitas desain 10.000 liter per hari, kapasitas efektif 8.000 liter per hari, dan keluaran aktual 7.200 liter per hari, maka utilisasi sebesar 72 persen dan efisiensi sebesar 90 persen. Angka tersebut menunjukkan bahwa rendahnya keluaran lebih disebabkan oleh faktor perencanaan, bukan oleh kinerja pelaksanaan produksi. Oleh karena itu, ukuran ini menjadi titik awal diagnosis sebelum manajer memutuskan menambah atau menyesuaikan kapasitas.</p>
      <h5>5.2.2 Tiga Horizon Perencanaan</h5>
      <p>Keputusan kapasitas tersebar pada tiga horizon perencanaan yang saling berjenjang. Perencanaan jangka panjang, biasanya lebih dari satu tahun, menjadi tanggung jawab manajemen puncak dan mencakup keputusan investasi modal, penambahan fasilitas, lokasi, produk baru, dan pengembangan rantai pasokan. Perencanaan jangka menengah, sekitar 3 sampai 18 bulan, menjadi tanggung jawab manajer operasi bersama fungsi lain dan diwujudkan melalui perencanaan agregat yang menetapkan tingkat produksi, tenaga kerja, persediaan, dan subkontrak. Perencanaan jangka pendek, sampai dengan tiga bulan, menerjemahkan rencana agregat menjadi jadwal mingguan, harian, dan per jam termasuk penugasan pekerjaan dan lembur (Heizer, Render dan Munson, 2017). Dengan demikian, rencana jangka menengah harus konsisten dengan strategi jangka panjang dan sekaligus dapat dieksekusi dalam jadwal jangka pendek.</p>
      <p>Kedudukan berjenjang tersebut memiliki implikasi manajerial yang penting. Manajer operasi tidak dapat mengubah kapasitas fisik pabrik dalam horizon menengah karena keputusan tersebut telah dikunci oleh perencanaan jangka panjang. Ruang gerak yang tersisa adalah variabel yang dapat dikendalikan dalam beberapa bulan, yaitu jumlah tenaga kerja, jam kerja, tingkat persediaan, subkontrak, dan pengelolaan permintaan. Oleh karena itu, mutu perencanaan agregat sangat menentukan seberapa efisien kapasitas terpasang dimanfaatkan, sebagaimana ditunjukkan Frito-Lay yang mengandalkan perencanaan agregat untuk menjaga utilisasi tinggi pada 36 pabriknya yang padat modal (Heizer, Render dan Munson, 2017).</p>`
    },
    {
      no: "5.3",
      title: "Sales and Operations Planning dan Rencana Agregat",
      body: `<h5>5.3.1 Pengertian dan Proses S&OP</h5>
      <p>Perencanaan jangka menengah yang baik menuntut koordinasi antara ramalan permintaan dengan seluruh area fungsional perusahaan dan mitra rantai pasokannya. Proses koordinasi tersebut dikenal sebagai <em>sales and operations planning</em> atau S&OP. Menurut Heizer, Render dan Munson (2017), S&OP adalah proses menyeimbangkan sumber daya dengan permintaan yang diramalkan, menyelaraskan tuntutan yang saling bersaing dari rantai pasokan sampai pelanggan akhir, sekaligus mengaitkan perencanaan strategis dengan operasi pada seluruh horizon perencanaan. Karena masukannya berasal dari banyak sumber internal dan eksternal, S&OP lazim dijalankan oleh tim lintas fungsi yang beranggotakan wakil operasi, pemasaran, keuangan, dan logistik. Tim tersebut menilai rencana mana yang layak dilaksanakan pada bulan-bulan mendatang dan memberikan peringatan dini kepada manajemen puncak apabila sumber daya tidak sepadan dengan ekspektasi pasar.</p>
      <p>Agar tetap mutakhir, S&OP menggunakan ramalan bergulir (<em>rolling forecast</em>) yang diperbarui secara mingguan atau bulanan. Selain harus representatif, tepat waktu, dan menyeluruh, proses S&OP yang efektif memerlukan empat unsur, yaitu satuan ukuran penjualan dan keluaran yang logis, ramalan permintaan periode menengah dalam satuan agregat, metode penentuan biaya yang relevan, dan model yang menggabungkan ramalan dengan biaya sehingga keputusan penjadwalan dapat diambil (Heizer, Render dan Munson, 2017). Dukungan teknologi informasi memperkuat proses ini karena sistem <em>enterprise resource planning</em> dan analitik data memungkinkan integrasi data penjualan, kapasitas, dan keuangan secara waktu nyata sehingga siklus S&OP dapat dipersingkat (Turban, Pollard dan Wood, 2021).</p>
      <h5>5.3.2 Rencana Agregat, Disagregasi, dan Jadwal Produksi Induk</h5>
      <p>Keluaran dari proses S&OP adalah rencana agregat. Rencana agregat menetapkan kuantitas dan waktu produksi untuk 3 sampai 18 bulan ke depan dengan menggunakan informasi keluarga produk, bukan produk individual. Rencana agregat sebuah pabrikan mobil, misalnya, menyatakan berapa unit mobil yang akan diproduksi setiap bulan tanpa merinci varian warna atau tipe. Agregasi seperti ini disengaja karena pada horizon menengah yang relevan adalah kecukupan kapasitas total, sedangkan rincian produk akan ditetapkan kemudian. Proses memecah rencana agregat menjadi rincian yang lebih detail disebut disagregasi, dan hasilnya adalah jadwal produksi induk (<em>master production schedule</em>) yang menentukan apa yang akan dibuat dan kapan, serta menjadi masukan bagi sistem perencanaan kebutuhan material (Heizer, Render dan Munson, 2017).</p>
      <p>Praktik pada perusahaan kelas dunia menunjukkan nilai strategis proses ini. Frito-Lay menyusun profil permintaan total dari data penjualan historis, ramalan produk baru, dan promosi, kemudian mencocokkannya dengan kapasitas 36 pabriknya, dan setiap kuartal rencana dimutakhirkan bersama setiap pabrik (Heizer, Render dan Munson, 2017). Dalam konteks Indonesia, praktik serupa dijalankan produsen barang konsumsi seperti Indofood yang harus menaikkan rencana produksi agregat mi instan dan tepung menjelang bulan Ramadan dan Lebaran, ketika permintaan melonjak jauh di atas rata-rata tahunan, kemudian menurunkannya kembali setelah musim puncak berlalu. Dengan demikian, S&OP bukan sekadar ritual perencanaan, melainkan mekanisme tata kelola yang mengikat komitmen penjualan, produksi, dan keuangan dalam satu angka yang sama.</p>`
    },
    {
      no: "5.4",
      title: "Strategi Perencanaan Agregat",
      body: `<h5>5.4.1 Opsi Kapasitas</h5>
      <p>Dalam menyusun rencana agregat, manajer operasi menghadapi pertanyaan mendasar mengenai variabel mana yang akan dimanipulasi untuk menyerap fluktuasi permintaan. Kelompok pilihan pertama disebut opsi kapasitas karena berupaya menyerap fluktuasi permintaan tanpa mengubah permintaan itu sendiri. Heizer, Render dan Munson (2017) mengidentifikasi lima opsi kapasitas sebagai berikut:</p>
      <ul>
        <li>mengubah tingkat persediaan;</li>
        <li>mengubah ukuran tenaga kerja melalui perekrutan atau pemutusan hubungan kerja;</li>
        <li>mengubah laju produksi melalui lembur atau waktu menganggur;</li>
        <li>menggunakan subkontrak; dan</li>
        <li>memanfaatkan pekerja paruh waktu.</li>
      </ul>
      <p>Setiap opsi membawa konsekuensi biaya dan risiko tersendiri. Menumpuk persediaan pada periode sepi menimbulkan biaya penyimpanan, asuransi, keusangan, dan modal tertanam, sementara persediaan yang terlalu tipis berisiko kehabisan stok dan hilangnya penjualan. Merekrut dan memberhentikan pekerja menimbulkan biaya pelatihan, penurunan produktivitas sementara, dan kemerosotan moral karyawan. Lembur dibatasi oleh kelelahan pekerja dan premi upah yang lebih tinggi, sedangkan subkontrak berisiko pada mutu, margin, dan terbukanya peluang bagi pesaing. Pekerja paruh waktu fleksibel dan murah, namun tingkat keluar masuknya tinggi sehingga cocok terutama untuk pekerjaan berketerampilan rendah di sektor jasa (Heizer, Render dan Munson, 2017).</p>
      <h5>5.4.2 Opsi Permintaan</h5>
      <p>Kelompok pilihan kedua disebut opsi permintaan karena berupaya memuluskan pola permintaan agar sesuai dengan kapasitas yang tersedia. Tiga opsi permintaan yang utama adalah memengaruhi permintaan melalui iklan, promosi, penjualan personal, dan potongan harga; menerapkan <em>back order</em> atau pesanan tertunda pada periode permintaan tinggi; serta membangun bauran produk dan jasa yang berlawanan musim (<em>counterseasonal mixing</em>), misalnya produsen yang membuat pemanas ruangan sekaligus pendingin udara (Heizer, Render dan Munson, 2017). Slack, Brandon-Jones dan Burgess (2022) menyebut pendekatan ini sebagai <em>demand management</em>, yaitu upaya aktif memindahkan permintaan dari periode puncak ke periode lembah melalui penetapan harga diferensial dan promosi. Praktik hotel di kawasan Bali yang menawarkan tarif rendah pada musim sepi, maskapai yang memberikan harga murah untuk penerbangan tengah pekan, dan restoran yang memberi diskon di luar jam makan merupakan wujud nyata opsi ini. Namun, opsi permintaan tidak selalu mampu menyeimbangkan permintaan dengan kapasitas secara sempurna sehingga umumnya dikombinasikan dengan opsi kapasitas.</p>
      <table class="bk-table">
        <caption>Tabel 5.1 Opsi Kapasitas dan Opsi Permintaan dalam Perencanaan Agregat</caption>
        <thead><tr><th>Opsi</th><th>Keunggulan Utama</th><th>Kelemahan Utama</th></tr></thead>
        <tbody>
          <tr><td>Mengubah tingkat persediaan</td><td>Perubahan sumber daya manusia gradual, produksi stabil</td><td>Biaya penyimpanan meningkat, risiko kehabisan stok</td></tr>
          <tr><td>Merekrut atau memberhentikan pekerja</td><td>Produksi mengikuti permintaan tanpa biaya persediaan</td><td>Biaya rekrutmen, pelatihan, dan moral karyawan</td></tr>
          <tr><td>Lembur atau waktu menganggur</td><td>Menyerap fluktuasi musiman tanpa biaya rekrutmen</td><td>Premi lembur, kelelahan, batas kapasitas lembur</td></tr>
          <tr><td>Subkontrak</td><td>Fleksibilitas kapasitas tanpa investasi</td><td>Kendali mutu berkurang, margin tergerus, risiko pesaing</td></tr>
          <tr><td>Pekerja paruh waktu</td><td>Lebih murah dan lentur daripada pekerja tetap</td><td>Perputaran tinggi, biaya pelatihan, mutu bervariasi</td></tr>
          <tr><td>Memengaruhi permintaan</td><td>Memanfaatkan kapasitas berlebih, menarik pelanggan baru</td><td>Ketidakpastian permintaan tetap tinggi</td></tr>
          <tr><td>Pesanan tertunda</td><td>Kapasitas tetap konstan, menghindari lembur</td><td>Pelanggan harus bersedia menunggu, risiko kehilangan goodwill</td></tr>
          <tr><td>Bauran produk berlawanan musim</td><td>Sumber daya dan tenaga kerja termanfaatkan penuh</td><td>Dapat menjauh dari kompetensi inti perusahaan</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017) dan Slack, Brandon-Jones dan Burgess (2022)</td></tr></tfoot>
      </table>
      <h5>5.4.3 Strategi Chase, Level, Demand Management, dan Mixed</h5>
      <p>Kombinasi opsi di atas mengerucut pada beberapa strategi dasar. Strategi <em>chase</em> menetapkan tingkat keluaran setiap periode sama dengan ramalan permintaan periode tersebut, yang dicapai melalui variasi jumlah tenaga kerja, lembur, pekerja paruh waktu, atau subkontrak. Strategi ini banyak dianut organisasi jasa seperti pendidikan, perhotelan, dan konstruksi karena jasa tidak dapat disimpan sebagai persediaan (Heizer, Render dan Munson, 2017). Sebaliknya, strategi <em>level</em> atau penjadwalan berimbang mempertahankan tingkat produksi atau tenaga kerja yang konstan sepanjang horizon perencanaan dan membiarkan persediaan barang jadi berfluktuasi sebagai penyangga. Filosofi di balik strategi <em>level</em>, yang dianut antara lain oleh Toyota, adalah bahwa tenaga kerja yang stabil menghasilkan mutu yang lebih baik, perputaran karyawan yang lebih rendah, dan komitmen yang lebih kuat terhadap tujuan perusahaan.</p>
      <p>Slack, Brandon-Jones dan Burgess (2022) menempatkan <em>demand management</em> sebagai strategi murni ketiga di samping <em>level capacity</em> dan <em>chase demand</em>, sehingga manajer sesungguhnya memiliki tiga tuas, yaitu menyimpan keluaran, mengubah kapasitas, atau mengubah permintaan. Karena setiap strategi murni jarang optimal secara sendiri-sendiri, kebanyakan perusahaan menempuh strategi campuran (<em>mixed strategy</em>) yang menggabungkan dua atau lebih variabel kendali untuk mencapai biaya minimum. Sebagai contoh Indonesia, produsen biskuit dan sirup yang menghadapi puncak permintaan Lebaran umumnya menjalankan strategi campuran, yaitu menimbun persediaan sejak beberapa bulan sebelumnya dengan produksi berimbang, menambah lembur ketika mendekati musim puncak, dan menggunakan pemaketan pihak ketiga sebagai subkontrak apabila lonjakan melebihi perkiraan. Implikasi manajerialnya adalah pemilihan strategi tidak semata soal biaya, melainkan juga menyangkut kebijakan ketenagakerjaan, mutu, dan tingkat layanan yang ingin dipertahankan perusahaan.</p>`
    },
    {
      no: "5.5",
      title: "Metode Penyusunan Rencana Agregat",
      body: `<h5>5.5.1 Metode Grafis</h5>
      <p>Metode grafis merupakan teknik perencanaan agregat yang paling populer karena mudah dipahami dan digunakan. Teknik ini bekerja dengan sedikit variabel sekaligus dan bersifat coba-coba (<em>trial and error</em>), sehingga tidak menjamin rencana optimal, namun hanya memerlukan perhitungan sederhana. Lima langkah metode grafis adalah menentukan permintaan setiap periode; menentukan kapasitas waktu reguler, lembur, dan subkontrak setiap periode; menghitung biaya tenaga kerja, biaya rekrutmen dan pemberhentian, serta biaya penyimpanan persediaan; mempertimbangkan kebijakan perusahaan mengenai tenaga kerja dan tingkat persediaan; dan menyusun beberapa rencana alternatif untuk dibandingkan biaya totalnya (Heizer, Render dan Munson, 2017). Titik tolak analisis adalah kebutuhan rata-rata yang dihitung dengan rumus: Kebutuhan rata-rata = Total permintaan yang diperkirakan / Jumlah hari produksi. Garis kebutuhan rata-rata tersebut kemudian dibandingkan dengan grafik permintaan harian setiap bulan untuk memperlihatkan periode mana yang berada di atas dan di bawah rata-rata.</p>
      <p>Sebagai ilustrasi sederhana, misalkan sebuah produsen genteng metal di Karawang meramalkan permintaan enam bulan sebesar 6.000 unit dengan 120 hari produksi, sehingga kebutuhan rata-rata adalah 50 unit per hari. Rencana pertama mempertahankan tenaga kerja konstan pada 50 unit per hari; persediaan menumpuk pada bulan sepi dan terkuras pada bulan ramai, sehingga biaya rencana ini adalah biaya tenaga kerja reguler ditambah biaya penyimpanan seluruh persediaan yang dibawa antarbulan. Rencana kedua menetapkan tenaga kerja konstan pada tingkat bulan permintaan terendah dan memenuhi kekurangan melalui subkontrak, sehingga tidak ada biaya persediaan namun muncul biaya subkontrak per unit. Rencana ketiga merekrut dan memberhentikan pekerja agar produksi setiap bulan persis sama dengan permintaan, sehingga muncul biaya perubahan tingkat produksi baik saat naik maupun turun. Langkah terakhir adalah membandingkan biaya total ketiga rencana dan memilih yang termurah, dengan catatan bahwa metode grafis hanya membantu mengevaluasi alternatif yang diajukan, bukan membangkitkan alternatif terbaik (Heizer, Render dan Munson, 2017). Dalam praktik, perhitungan semacam ini mudah dibangun pada lembar kerja elektronik, dan sistem informasi perusahaan menyediakan data biaya serta ramalan yang diperlukan secara terpusat (Turban, Pollard dan Wood, 2021).</p>
      <h5>5.5.2 Metode Transportasi Program Linear</h5>
      <p>Apabila persoalan perencanaan agregat dipandang sebagai persoalan mengalokasikan kapasitas operasi untuk memenuhi permintaan yang diramalkan, persoalan tersebut dapat dirumuskan dalam format program linear. Metode transportasi program linear menghasilkan rencana optimal berbiaya minimum, bukan sekadar rencana yang layak, dan mampu merinci produksi waktu reguler, lembur, dan subkontrak setiap periode serta persediaan yang dibawa antarperiode (Heizer, Render dan Munson, 2017). Struktur tabelnya menempatkan sumber pasokan, yaitu persediaan awal serta kapasitas reguler, lembur, dan subkontrak setiap periode, pada baris, dan permintaan setiap periode pada kolom. Karena metode transportasi mensyaratkan pasokan sama dengan permintaan, ditambahkan kolom semu kapasitas tidak terpakai dengan biaya nol. Biaya setiap sel adalah biaya produksi ditambah biaya penyimpanan sebesar tarif per unit per periode dikalikan lama penyimpanan, dan sel yang menyiratkan pemenuhan permintaan masa lalu diblokir apabila pesanan tertunda tidak diizinkan.</p>
      <p>Prosedur pengisian tabel dilakukan dengan mengalokasikan produksi sebanyak mungkin ke sel berbiaya terkecil tanpa melampaui kapasitas baris maupun permintaan kolom, kemudian beralih ke sel berbiaya terkecil berikutnya sampai seluruh permintaan terpenuhi. Kelemahan metode ini adalah asumsi biaya linear, sehingga faktor nonlinear atau negatif seperti biaya rekrutmen dan pemberhentian tidak dapat ditangani dan memerlukan formulasi program linear yang lebih umum atau simulasi komputer. Saat ini tersedia berbagai perangkat lunak S&OP komersial yang mengotomatiskan perhitungan tersebut, dan bagi manajemen nilai tambah utamanya adalah kemampuan menguji berbagai skenario permintaan dan biaya secara cepat sebelum berkomitmen pada satu rencana (Heizer, Render dan Munson, 2017; Turban, Pollard dan Wood, 2021).</p>`
    },
    {
      no: "5.6",
      title: "Perencanaan Agregat pada Sektor Jasa",
      body: `<h5>5.6.1 Karakteristik dan Teknik pada Organisasi Jasa</h5>
      <p>Sebagian organisasi jasa menyusun rencana agregat dengan cara yang sama seperti manufaktur, namun dengan peran <em>demand management</em> yang jauh lebih aktif karena jasa tidak dapat disimpan. Variabel utama perencanaan agregat pada jasa adalah tenaga kerja, sehingga pengendalian biaya tenaga kerja menjadi kritis. Empat teknik yang terbukti berhasil adalah penjadwalan jam kerja yang akurat agar respons terhadap permintaan pelanggan cepat, penyediaan tenaga kerja siap panggil (<em>on-call</em>) untuk permintaan tidak terduga, fleksibilitas keterampilan individual sehingga tenaga kerja dapat dialihkan antartugas, dan fleksibilitas laju keluaran atau jam kerja (Heizer, Render dan Munson, 2017). Praktik seperti kasir swalayan yang merangkap petugas rak ketika antrean memanjang, atau restoran yang memulangkan karyawan lebih awal ketika sepi, merupakan penerapan sehari-hari teknik tersebut.</p>
      <p>Pendekatan perencanaan agregat berbeda menurut jenis jasa yang diberikan. Pada restoran dengan permintaan sangat fluktuatif, perencanaan diarahkan pada pemulusan laju produksi dan penentuan ukuran tenaga kerja optimal, dengan persediaan kecil yang mudah rusak. Rumah sakit merencanakan alokasi dana, staf, dan pasokan berdasarkan ramalan beban pasien, misalnya melalui staf perawat mengambang antarunit. Jaringan nasional usaha jasa kecil dapat memusatkan perencanaan pembelian dan kapasitas ketika permintaan dapat dipengaruhi promosi. Jasa lain-lain seperti keuangan, transportasi, dan rekreasi berfokus pada perencanaan kebutuhan sumber daya manusia dan pengelolaan permintaan, misalnya kantor akuntan yang menghitung kebutuhan tenaga profesional dengan membagi jam kerja tertagih yang diramalkan dengan jam tersedia per orang. Industri penerbangan menghadapi persoalan paling kompleks karena harus menjadwalkan jumlah penerbangan, penumpang, awak, dan alokasi kursi pada berbagai kelas tarif di banyak lokasi sekaligus (Heizer, Render dan Munson, 2017).</p>
      <h5>5.6.2 Antrean sebagai Konsekuensi Ketidakseimbangan Kapasitas</h5>
      <p>Ketika kapasitas jasa tidak dapat mengikuti fluktuasi permintaan dan permintaan tidak dapat sepenuhnya dimuluskan, kelebihan permintaan tidak berubah menjadi persediaan melainkan menjadi antrean pelanggan. Slack, Brandon-Jones dan Burgess (2022) menegaskan bahwa keputusan kapasitas pada operasi jasa pada dasarnya merupakan pertukaran antara biaya kapasitas menganggur dengan biaya menunggu yang ditanggung pelanggan, termasuk risiko pelanggan meninggalkan antrean atau berpindah ke pesaing. Panjang antrean dipengaruhi oleh variabilitas kedatangan dan variabilitas waktu layanan, sehingga bahkan pada utilisasi di bawah 100 persen antrean tetap terbentuk; semakin tinggi utilisasi mendekati kapasitas penuh, semakin cepat waktu tunggu memanjang. Oleh karena itu, operasi jasa yang menargetkan waktu tunggu pendek harus dengan sengaja menyediakan bantalan kapasitas (<em>capacity cushion</em>) dan tidak mengejar utilisasi maksimum.</p>
      <p>Selain sisi kuantitatif, terdapat sisi persepsi yang dapat dikelola. Waktu menunggu terasa lebih pendek apabila pelanggan disibukkan, diberi informasi perkiraan lama tunggu, dan diperlakukan adil melalui disiplin antrean yang jelas. Praktik perbankan Indonesia memberikan contoh yang baik, yaitu bank besar seperti BCA memadukan penambahan kasir pada jam dan tanggal sibuk, mesin antrean dengan estimasi waktu, dan pengalihan transaksi ke kanal digital sehingga beban antrean di cabang menurun secara struktural. Demikian pula fasilitas kesehatan yang menerapkan pendaftaran daring dan janji temu bertujuan memindahkan variabilitas kedatangan menjadi jadwal yang lebih rata. Implikasi manajerialnya adalah pengelolaan antrean merupakan bagian integral dari manajemen kapasitas jasa, yang menggabungkan penyesuaian kapasitas, pengelolaan permintaan, dan pengelolaan persepsi pelanggan secara serentak (Slack, Brandon-Jones dan Burgess, 2022).</p>`
    },
    {
      no: "5.7",
      title: "Revenue Management",
      body: `<h5>5.7.1 Pengertian dan Prasyarat Revenue Management</h5>
      <p>Kebanyakan model operasi mengasumsikan perusahaan mengenakan satu harga yang sama untuk semua pelanggan, padahal banyak perusahaan justru berupaya keras menetapkan harga yang berbeda sesuai kesediaan membayar setiap segmen. Menurut Heizer, Render dan Munson (2017), <em>revenue management</em> atau <em>yield management</em> adalah proses perencanaan agregat yang mengalokasikan sumber daya perusahaan yang langka kepada pelanggan pada tingkat harga yang memaksimalkan pendapatan. Teknik ini mengubah fokus perencanaan agregat dari pengelolaan kapasitas menjadi pengelolaan permintaan. Pemanfaatannya meluas sejak sistem reservasi American Airlines memungkinkan perubahan harga tiket secara waktu nyata berdasarkan informasi permintaan pada setiap rute, dan kemudian diadopsi industri perhotelan, penyewaan mobil, kapal pesiar, dan hiburan. Kemajuan analitik data dan algoritma penetapan harga dinamis semakin memperluas penerapannya karena keputusan harga kini dapat dihitung ulang ribuan kali setiap malam (Turban, Pollard dan Wood, 2021).</p>
      <p>Tidak semua bisnis cocok menerapkan teknik ini. Organisasi yang memiliki persediaan mudah kedaluwarsa (<em>perishable</em>) berkepentingan terhadap <em>revenue management</em> apabila memenuhi lima karakteristik, yaitu jasa atau produk dapat dijual sebelum dikonsumsi, permintaan berfluktuasi, kapasitas relatif tetap, permintaan dapat disegmentasi, serta biaya variabel rendah dan biaya tetap tinggi (Heizer, Render dan Munson, 2017). Kursi pesawat yang tidak terjual pada saat pintu ditutup kehilangan seluruh nilainya, sehingga menjual kursi tersebut pada harga diskon tetap lebih baik daripada membiarkannya kosong sepanjang harga melebihi biaya variabel.</p>
      <h5>5.7.2 Mekanisme Perhitungan dan Pengelolaannya</h5>
      <p>Logika dasarnya dapat ditunjukkan dengan perhitungan kontribusi. Misalkan sebuah hotel berkapasitas 100 kamar di Yogyakarta menjual kamar pada satu harga Rp1.500.000 per malam dengan biaya variabel Rp150.000 per kamar dan rata-rata penjualan 50 kamar, sehingga kontribusi per malam adalah 50 dikali selisih harga dengan biaya variabel, yaitu Rp67,5 juta. Apabila manajemen menetapkan dua tingkat harga, misalnya 30 kamar terjual pada Rp1.000.000 untuk pemesanan jauh hari dan 30 kamar pada Rp2.000.000 untuk pemesanan mendekati hari menginap, kontribusi menjadi 30 kali Rp850.000 ditambah 30 kali Rp1.850.000, yaitu Rp81 juta. Rumus umumnya adalah: Kontribusi total = Jumlah unit terjual pada setiap tingkat harga dikali (Harga pada tingkat tersebut dikurangi Biaya variabel per unit), dijumlahkan untuk seluruh tingkat harga. Peningkatan kontribusi terjadi karena harga majemuk menangkap sebagian surplus konsumen yang bersedia membayar mahal sekaligus mengisi kapasitas dengan konsumen yang hanya bersedia membayar murah namun masih di atas biaya variabel.</p>
      <p>Agar <em>revenue management</em> berhasil, perusahaan harus mengelola tiga isu, yaitu struktur harga majemuk yang layak dan tampak logis serta adil bagi pelanggan, ramalan penggunaan dan durasi penggunaan kapasitas, dan perubahan permintaan termasuk penanganan <em>overbooking</em> ketika ramalan meleset (Heizer, Render dan Munson, 2017). Dalam konteks Indonesia, maskapai seperti Garuda Indonesia dan Citilink menjual satu penerbangan dalam banyak subkelas tarif yang kuotanya disesuaikan secara dinamis, dan PT Kereta Api Indonesia menerapkan subkelas harga pada rute yang sama menurut waktu pemesanan dan tingkat keterisian. Implikasi manajerial yang perlu diperhatikan adalah aspek keadilan yang dipersepsikan pelanggan, karena perbedaan harga yang tidak dapat dijelaskan dengan pembeda layanan yang masuk akal dapat merusak kepercayaan dan reputasi perusahaan.</p>`
    },
    {
      no: "5.8",
      title: "Rangkuman",
      body: `<p>Manajemen kapasitas pada horizon jangka menengah diwujudkan melalui proses <em>sales and operations planning</em> yang menyeimbangkan sumber daya dengan permintaan yang diramalkan dan menghasilkan rencana agregat. Rencana agregat menetapkan kuantitas dan waktu produksi untuk 3 sampai 18 bulan ke depan pada tingkat keluarga produk, menjadi jembatan antara keputusan kapasitas jangka panjang dengan penjadwalan jangka pendek, dan melalui disagregasi diturunkan menjadi jadwal produksi induk yang mengarahkan sistem perencanaan kebutuhan material. Untuk menyerap fluktuasi permintaan, manajer dapat memanipulasi lima opsi kapasitas dan tiga opsi permintaan yang mengerucut pada strategi <em>chase</em>, <em>level</em>, <em>demand management</em>, dan strategi campuran, dengan pertimbangan biaya, kebijakan ketenagakerjaan, dan tingkat layanan.</p>
      <p>Dari sisi metode, rencana agregat dapat disusun dengan metode grafis yang sederhana dan bersifat coba-coba maupun metode transportasi program linear yang menghasilkan solusi optimal selama struktur biayanya linear. Pada sektor jasa, tenaga kerja menjadi variabel utama perencanaan agregat karena keluaran jasa tidak dapat disimpan, sehingga fleksibilitas penjadwalan dan keterampilan menjadi kunci, dan ketidakseimbangan kapasitas dengan permintaan mewujud sebagai antrean yang harus dikelola baik secara kuantitatif maupun persepsional. Akhirnya, <em>revenue management</em> melengkapi perangkat manajemen kapasitas dengan mengalokasikan kapasitas yang langka kepada segmen pelanggan pada harga berbeda untuk memaksimalkan pendapatan, khususnya pada industri berbiaya tetap tinggi dengan persediaan mudah kedaluwarsa. Dengan demikian, kompetensi menyusun dan mengevaluasi rencana agregat merupakan salah satu tanggung jawab inti manajer operasi dalam memastikan kapasitas terpasang dimanfaatkan secara efisien dan menguntungkan.</p>`
    },
    {
      no: "5.9",
      title: "Daftar Pustaka",
      body: `<p>Heizer, J., Render, B. dan Munson, C. (2017). <em>Operations Management: Sustainability and Supply Chain Management</em>. Edisi 12. Pearson Education.</p>
      <p>Slack, N., Brandon-Jones, A. dan Burgess, N. (2022). <em>Operations Management</em>. Edisi 10. Pearson Education.</p>
      <p>Turban, E., Pollard, C. dan Wood, G. (2021). <em>Information Technology for Management: Driving Digital Transformation to Increase Local and Global Performance, Growth and Sustainability</em>. Edisi 12. John Wiley and Sons.</p>`
    }
  ]
};
