window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.otm = window.MBA_BOOK.otm || {};
window.MBA_BOOK.otm[2] = {
  bab: 2,
  judul: "STRATEGI OPERASI DALAM LINGKUNGAN GLOBAL",
  sumber: "Heizer, Render dan Munson (2017), Operations Management 12e; Turban, Pollard dan Wood (2021), IT for Management 12e; Slack, Brandon-Jones dan Burgess (2022), Operations Management 10e",
  lo: [
    "LO1 Mendefinisikan misi dan strategi organisasi serta menjelaskan hierarki misi sampai ke tingkat fungsi operasi.",
    "LO2 Mengidentifikasi dan menjelaskan tiga pendekatan strategis untuk mencapai keunggulan bersaing melalui operasi, yaitu diferensiasi, kepemimpinan biaya, dan respons.",
    "LO3 Menjelaskan empat perspektif strategi operasi, konsep order winners dan order qualifiers, serta matriks strategi operasi.",
    "LO4 Memahami signifikansi faktor kunci keberhasilan dan kompetensi inti dalam pengembangan dan implementasi strategi operasi.",
    "LO5 Menggunakan metode pemeringkatan faktor untuk mengevaluasi pilihan negara maupun penyedia alih daya.",
    "LO6 Mengidentifikasi dan menjelaskan empat opsi strategi operasi global beserta kondisi penggunaannya."
  ],
  sections: [
    {
      no: "2.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi kedua mata kuliah Manajemen Operasi dan Teknologi membahas strategi operasi dalam lingkungan global. Pembahasan dimulai dari pandangan global atas operasi dan rantai pasokan, dilanjutkan dengan konsep misi dan strategi, tiga pendekatan keunggulan bersaing melalui operasi, empat perspektif strategi operasi beserta konsep <em>order winners</em> dan <em>order qualifiers</em>, isu dalam pengembangan strategi, keputusan alih daya beserta metode pemeringkatan faktor, dan diakhiri dengan empat opsi strategi operasi global. Materi ini menjadi fondasi konseptual bagi seluruh keputusan operasi yang dibahas pada sesi berikutnya.</p>
      <p>Setelah menyelesaikan sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <ul>
        <li>Mendefinisikan misi dan strategi organisasi serta menjelaskan hierarki misi sampai ke tingkat fungsi operasi.</li>
        <li>Mengidentifikasi dan menjelaskan tiga pendekatan strategis untuk mencapai keunggulan bersaing melalui operasi, yaitu diferensiasi, kepemimpinan biaya, dan respons.</li>
        <li>Menjelaskan empat perspektif strategi operasi, konsep <em>order winners</em> dan <em>order qualifiers</em>, serta matriks strategi operasi.</li>
        <li>Memahami signifikansi faktor kunci keberhasilan dan kompetensi inti dalam pengembangan dan implementasi strategi operasi.</li>
        <li>Menggunakan metode pemeringkatan faktor untuk mengevaluasi pilihan negara maupun penyedia alih daya.</li>
        <li>Mengidentifikasi dan menjelaskan empat opsi strategi operasi global beserta kondisi penggunaannya.</li>
      </ul>`
    },
    {
      no: "2.2",
      title: "Pandangan Global atas Operasi dan Rantai Pasokan",
      body: `<h5>2.2.1 Globalisasi dan Standar Daya Saing Baru</h5>
      <p>Lingkungan bisnis dewasa ini ditandai oleh integrasi ekonomi antarnegara yang terus meningkat. Menurut Heizer, Render dan Munson (2017), globalisasi merupakan meningkatnya integrasi dan saling ketergantungan ekonomi antarnegara sehingga pelanggan, talenta, dan pemasok perusahaan tersebar di seluruh dunia. Sementara itu, Turban, Pollard dan Wood (2021) memandang globalisasi operasi sebagai hasil dari kemajuan teknologi informasi, komputasi awan, dan konektivitas digital yang memungkinkan koordinasi aktivitas bisnis lintas negara secara waktu nyata. Dari kedua definisi tersebut dapat disimpulkan bahwa globalisasi merupakan perluasan lingkup pasar, pasokan, dan sumber daya perusahaan ke tingkat dunia yang dimungkinkan oleh turunnya hambatan perdagangan dan kemajuan teknologi komunikasi serta transportasi.</p>
      <p>Globalisasi membawa konsekuensi ganda bagi manajer operasi. Di satu sisi, strategi global menyumbang efisiensi dan menambah nilai bagi produk dan jasa. Di sisi lain, kompleksitas, risiko, dan intensitas persaingan meningkat karena standar daya saing global menuntut mutu, keragaman, kustomisasi, kenyamanan, ketepatan waktu, dan biaya secara serentak. Contoh yang sering dikutip adalah Boeing yang membangun pesawat 787 Dreamliner bersama lebih dari tiga ratus pemasok di belasan negara, sehingga perusahaan tersebut pada hakikatnya bersaing dengan kapabilitas seluruh rantai pasokan globalnya, bukan hanya dengan keahlian internalnya sendiri (Heizer, Render dan Munson, 2017). Dengan demikian, kemampuan merancang dan mengelola jejaring operasi lintas negara telah menjadi penentu utama keunggulan bersaing modern.</p>
      <h5>2.2.2 Enam Alasan Internasionalisasi Operasi</h5>
      <p>Perusahaan domestik memutuskan beralih ke bentuk operasi internasional karena berbagai motif. Heizer, Render dan Munson (2017) mengidentifikasi enam alasan utama internasionalisasi operasi sebagai berikut:</p>
      <ul>
        <li>memperbaiki rantai pasokan;</li>
        <li>menurunkan biaya dan risiko nilai tukar;</li>
        <li>memperbaiki operasi;</li>
        <li>memahami pasar;</li>
        <li>memperbaiki produk; dan</li>
        <li>menarik serta mempertahankan talenta global.</li>
      </ul>
      <p>Perbaikan rantai pasokan diperoleh ketika fasilitas ditempatkan di negara yang memiliki sumber daya unik, baik berupa keahlian, tenaga kerja berbiaya rendah, maupun bahan baku, sebagaimana terkonsentrasinya produksi sepatu atletik dunia di Guangzhou, Tiongkok. Penurunan biaya difasilitasi oleh mekanisme perdagangan seperti kawasan <em>maquiladora</em> di perbatasan Amerika Serikat dan Meksiko, penurunan tarif yang didorong World Trade Organization, serta blok perdagangan regional seperti Uni Eropa, NAFTA, dan MERCOSUR. Dalam konteks Indonesia, keikutsertaan dalam ASEAN Free Trade Area dan Regional Comprehensive Economic Partnership memberikan insentif tarif serupa, sehingga banyak produsen elektronik dan otomotif menjadikan Indonesia basis produksi regional. Selain itu, kehadiran fasilitas di beberapa negara dengan mata uang berbeda memungkinkan perusahaan meredam risiko fluktuasi nilai tukar.</p>
      <p>Alasan berikutnya lebih bersifat pembelajaran dan pengembangan pasar. Operasi internasional memperbaiki praktik manajemen karena perusahaan menyerap inovasi dari negara lain, misalnya teknik manajemen persediaan dari Jepang dan ergonomika dari negara Skandinavia. Kehadiran internasional juga membantu perusahaan memahami arah pasar, mendiversifikasi basis pelanggan, dan memperpanjang siklus hidup produk yang telah matang di pasar domestik. Kolaborasi riset baterai antara Toyota dan BMW memperlihatkan bahwa keterbukaan terhadap aliran gagasan lintas negara memperbaiki produk kedua belah pihak (Heizer, Render dan Munson, 2017). Terakhir, organisasi global lebih mampu menarik dan mempertahankan karyawan bermutu karena menawarkan jenjang karier yang lebih luas dan perlindungan terhadap gejolak ekonomi di satu negara. Contoh Indonesia yang relevan adalah ekspansi Indofood yang memproduksi mi instan di sejumlah negara Afrika melalui kemitraan lisensi dan usaha patungan, sehingga memperpanjang siklus hidup produk Indomie sekaligus mendiversifikasi pasar.</p>
      <h5>2.2.3 Isu Budaya dan Etika dalam Operasi Global</h5>
      <p>Meskipun dorongan globalisasi sangat kuat, perbedaan perilaku sosial dan budaya antarnegara tetap menjadi tantangan serius bagi manajer operasi. Praktik yang dianggap lazim di suatu negara dapat dinilai tidak etis atau melanggar hukum di negara lain, misalnya dalam isu suap, pekerja anak, dan pengelolaan lingkungan. Perkembangan hukum internasional, perjanjian perdagangan, dan kode etik global secara bertahap mendorong keseragaman standar perilaku manajerial di antara negara (Heizer, Render dan Munson, 2017). Bagi perusahaan Indonesia yang menjadi bagian rantai pasokan merek global, misalnya industri garmen dan alas kaki di Jawa Tengah, kepatuhan terhadap standar ketenagakerjaan dan keberlanjutan telah menjadi prasyarat untuk mempertahankan kontrak produksi. Oleh karena itu, sensitivitas budaya dan integritas etika merupakan kompetensi manajerial yang melekat pada strategi operasi global, bukan sekadar pelengkap administratif.</p>`
    },
    {
      no: "2.3",
      title: "Misi dan Strategi Organisasi",
      body: `<h5>2.3.1 Misi Organisasi</h5>
      <p>Upaya manajemen operasi yang efektif harus berangkat dari arah organisasi yang jelas. Menurut Heizer, Render dan Munson (2017), misi merupakan tujuan atau alasan keberadaan organisasi, yaitu kontribusi yang hendak diberikan organisasi kepada masyarakat. Pernyataan misi memberikan batasan dan fokus bagi organisasi serta menjadi konsep pemersatu bagi seluruh anggota organisasi. Setelah misi korporat ditetapkan, setiap area fungsional seperti pemasaran, keuangan, dan operasi menyusun misi pendukung, dan di dalam fungsi operasi disusun pula misi turunan bagi setiap bidang keputusan seperti desain produk, mutu, proses, lokasi, tata letak, sumber daya manusia, rantai pasokan, persediaan, penjadwalan, dan pemeliharaan. Dengan demikian, terbentuk hierarki misi yang menjamin konsistensi arah dari tingkat korporat sampai ke tingkat departemen operasi.</p>
      <h5>2.3.2 Strategi dan Tiga Cara Konseptual Mencapai Misi</h5>
      <p>Setelah misi ditetapkan, organisasi menyusun strategi untuk mewujudkannya. Strategi didefinisikan sebagai rencana tindakan organisasi untuk mencapai misi dan sasarannya (Heizer, Render dan Munson, 2017). Setiap area fungsional memiliki strategi masing-masing yang mengeksploitasi peluang dan kekuatan, menetralkan ancaman, serta menghindari kelemahan. Pada tataran konseptual, perusahaan mencapai misinya melalui tiga cara, yaitu diferensiasi, kepemimpinan biaya, dan respons, yang berarti fungsi operasi dituntut menghasilkan barang dan jasa yang lebih baik atau setidaknya berbeda, lebih murah, dan lebih tanggap. Oleh karena itu, tugas manajer operasi adalah menerjemahkan konsep strategis tersebut menjadi tugas nyata yang dapat dilaksanakan, karena kombinasi ketiganya dapat menghasilkan sistem yang memiliki keunggulan unik atas pesaing.</p>`
    },
    {
      no: "2.4",
      title: "Membangun Keunggulan Bersaing melalui Operasi",
      body: `<p>Keunggulan bersaing menyiratkan penciptaan sistem yang memiliki keunggulan unik atas pesaing melalui penciptaan nilai pelanggan secara efisien dan berkelanjutan (Heizer, Render dan Munson, 2017). Bentuk murni dari ketiga strategi jarang dijumpai dalam praktik, sehingga manajer operasi umumnya mengimplementasikan kombinasi dari ketiganya. Sub-bab ini menguraikan mekanisme setiap pendekatan beserta contohnya.</p>
      <h5>2.4.1 Bersaing melalui Diferensiasi</h5>
      <p>Diferensiasi berkaitan dengan penyediaan keunikan yang dipersepsikan pelanggan sebagai penambah nilai. Peluang menciptakan keunikan tidak terbatas pada satu fungsi tertentu, melainkan dapat muncul pada hampir semua aktivitas perusahaan, mulai dari fitur produk, keluasan lini produk, layanan purnajual, sampai kemudahan akses distribusi. Karena hampir semua produk mengandung unsur jasa dan hampir semua jasa mengandung unsur produk, ruang bagi diferensiasi hanya dibatasi oleh imajinasi manajemen (Heizer, Render dan Munson, 2017). Pada sektor jasa, diferensiasi dapat diperluas melalui pengalaman, yang dikenal sebagai <em>experience differentiation</em>, yaitu melibatkan pancaindra pelanggan sehingga pelanggan terserap atau bahkan menjadi partisipan aktif dalam produk. Disney dengan Magic Kingdom dan Hard Rock Cafe dengan konsep pengalaman bersantap merupakan contoh klasik, sedangkan di Indonesia jaringan kedai kopi seperti Tanamera atau restoran bertema warisan budaya menerapkan logika serupa dengan menjual suasana, cerita, dan interaksi, bukan sekadar makanan dan minuman.</p>
      <h5>2.4.2 Bersaing melalui Kepemimpinan Biaya</h5>
      <p>Kepemimpinan biaya rendah berarti mencapai nilai maksimum sebagaimana didefinisikan oleh pelanggan dengan tingkat biaya yang lebih rendah daripada pesaing. Strategi ini menuntut penelaahan setiap keputusan operasi secara terus-menerus untuk menekan biaya tanpa mengorbankan ekspektasi nilai pelanggan, sehingga strategi biaya rendah tidak identik dengan nilai rendah atau mutu rendah (Heizer, Render dan Munson, 2017). Southwest Airlines mencapainya melalui pemanfaatan bandara sekunder, satu tipe armada Boeing 737, waktu putar pesawat yang singkat, dan utilisasi kapasitas yang tinggi, sedangkan Walmart menekan biaya overhead toko dan biaya distribusi sehingga perputaran persediaannya tinggi. Dalam konteks Indonesia, model maskapai berbiaya hemat seperti Citilink dan Super Air Jet meniru logika yang sama, yaitu armada seragam, layanan minimal, dan utilisasi pesawat yang tinggi untuk menawarkan tarif rendah di rute domestik yang padat. Mekanisme intinya adalah utilisasi fasilitas yang efektif, sehingga biaya tetap tersebar pada volume keluaran yang besar dan biaya per unit menurun.</p>
      <h5>2.4.3 Bersaing melalui Respons</h5>
      <p>Respons sering dipahami sebagai respons yang fleksibel, namun konsep ini juga mencakup respons yang andal dan cepat. Respons didefinisikan sebagai keseluruhan rentang nilai yang terkait dengan pengembangan dan pengiriman produk yang tepat waktu, penjadwalan yang dapat diandalkan, serta kinerja yang fleksibel (Heizer, Render dan Munson, 2017). Fleksibilitas tampak pada kemampuan Hewlett-Packard menyesuaikan desain dan volume produk komputer yang siklus hidupnya sangat singkat. Keandalan tampak pada industri permesinan Jerman yang mempertahankan daya saing melalui jadwal yang bermakna dan selalu ditepati meskipun biaya tenaga kerjanya termasuk yang tertinggi di dunia. Kecepatan tampak pada Johnson Electric yang menjadikan kecepatan pengembangan, produksi, dan pengiriman motor listrik mini sebagai keunggulan utamanya. Contoh Indonesia yang relevan adalah J&T Express dan ekosistem logistik lokapasar yang bersaing melalui kecepatan dan keandalan pengiriman pada volume transaksi perdagangan elektronik yang berfluktuasi tajam, misalnya pada periode promosi tanggal kembar.</p>
      <p>Ketiga pendekatan tersebut dapat diringkas dalam Tabel 2.1 berikut.</p>
      <table class="bk-table">
        <caption>Tabel 2.1 Tiga Pendekatan Keunggulan Bersaing melalui Operasi</caption>
        <thead><tr><th>Pendekatan</th><th>Inti Konsep</th><th>Tuas Operasi Utama</th><th>Contoh</th></tr></thead>
        <tbody>
          <tr><td>Diferensiasi (lebih baik)</td><td>Keunikan yang menambah nilai bagi pelanggan</td><td>Desain inovatif, lini produk luas, layanan purnajual, pengalaman</td><td>Safeskin, Hard Rock Cafe, kedai kopi spesialti Indonesia</td></tr>
          <tr><td>Kepemimpinan biaya (lebih murah)</td><td>Nilai maksimum menurut pelanggan pada biaya terendah</td><td>Overhead rendah, utilisasi kapasitas efektif, manajemen persediaan</td><td>Southwest Airlines, Walmart, Citilink</td></tr>
          <tr><td>Respons (lebih tanggap)</td><td>Kinerja cepat, fleksibel, dan andal</td><td>Fleksibilitas volume dan desain, keandalan jadwal, kecepatan</td><td>Hewlett-Packard, Johnson Electric, J&amp;T Express</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017)</td></tr></tfoot>
      </table>
      <p>Implikasi manajerialnya, pilihan pendekatan keunggulan bersaing harus diterjemahkan secara konsisten ke dalam sepuluh keputusan strategis manajemen operasi. Dua perusahaan pada industri yang sama dapat mengonfigurasi keputusan produk, mutu, proses, lokasi, tata letak, sumber daya manusia, rantai pasokan, persediaan, penjadwalan, dan pemeliharaan secara sangat berbeda, misalnya produsen obat bermerek yang menekankan riset dan mutu di atas standar regulasi dibandingkan produsen obat generik yang menekankan utilisasi tinggi dan biaya rendah. Dengan demikian, strategi bukan sekadar pernyataan, melainkan pola keputusan operasi yang saling konsisten.</p>`
    },
    {
      no: "2.5",
      title: "Empat Perspektif Strategi Operasi, Order Winners dan Order Qualifiers",
      body: `<h5>2.5.1 Empat Perspektif Strategi Operasi</h5>
      <p>Selain kerangka Heizer, Render dan Munson, literatur strategi operasi memberikan sudut pandang yang lebih kaya mengenai bagaimana strategi operasi terbentuk. Menurut Slack, Brandon-Jones dan Burgess (2022), strategi operasi merupakan pola keputusan dan tindakan yang membentuk peran, tujuan, dan aktivitas jangka panjang fungsi operasi. Strategi tersebut dapat dilihat dari empat perspektif yang saling melengkapi, yaitu: perspektif <em>top-down</em>, yang memandang strategi operasi sebagai penerjemahan strategi korporat dan strategi bisnis ke dalam keputusan operasi; perspektif <em>bottom-up</em>, yang memandang strategi operasi tumbuh dari pembelajaran dan pengalaman operasional sehari-hari yang kemudian dikukuhkan menjadi arah strategis; perspektif <em>market requirements</em>, yang menuntut operasi memenuhi apa yang dipersyaratkan pasar; dan perspektif <em>operations resources</em>, yang menekankan pembangunan kapabilitas sumber daya operasi sebagai basis keunggulan jangka panjang. Perspektif keempat ini sejalan dengan pandangan berbasis sumber daya dalam manajemen strategik.</p>
      <p>Keempat perspektif tersebut tidak saling meniadakan, melainkan bekerja sebagai proses rekonsiliasi. Strategi operasi yang efektif merupakan titik temu antara apa yang diminta pasar dan apa yang mampu dilakukan sumber daya operasi, sekaligus konsisten dengan arah korporat dan terbuka terhadap gagasan perbaikan dari lini depan. Sebagai ilustrasi, keberhasilan Gojek di Indonesia dapat dibaca sebagai rekonsiliasi antara kebutuhan pasar akan transportasi dan pengantaran yang cepat serta terjangkau dengan kapabilitas sumber daya berupa platform teknologi dan jejaring mitra pengemudi yang masif, yang sebagian fiturnya justru lahir dari pembelajaran operasional di lapangan.</p>
      <h5>2.5.2 Order Winners dan Order Qualifiers</h5>
      <p>Untuk menerjemahkan kebutuhan pasar menjadi prioritas operasi, digunakan konsep faktor kompetitif yang dibedakan menjadi dua kelompok. <em>Order qualifiers</em> merupakan faktor yang harus berada di atas tingkat minimum tertentu agar produk atau jasa sekadar dipertimbangkan oleh pelanggan, sedangkan <em>order winners</em> merupakan faktor yang secara langsung dan signifikan memenangkan transaksi karena menjadi alasan utama pelanggan memilih suatu penawaran (Slack, Brandon-Jones dan Burgess, 2022). Kinerja pada <em>order qualifiers</em> yang melampaui ambang tidak banyak menambah daya saing, namun kinerja di bawah ambang menyebabkan produk langsung tersingkir dari pertimbangan. Sebaliknya, peningkatan kinerja pada <em>order winners</em> berbanding lurus dengan peluang memenangkan pesanan. Pada bisnis penerbangan berbiaya hemat, misalnya, keselamatan dan ketersediaan jadwal merupakan <em>order qualifiers</em>, sedangkan harga tiket merupakan <em>order winner</em> utama; pada jasa katering korporat di Jakarta, sertifikasi halal dan higienitas merupakan <em>order qualifiers</em>, sedangkan ketepatan waktu pengiriman dan fleksibilitas menu dapat menjadi <em>order winners</em>.</p>
      <p>Implikasi manajerial konsep ini sangat praktis. Manajer operasi harus mengalokasikan sumber daya perbaikan secara berbeda, yaitu menjaga <em>order qualifiers</em> tetap berada di atas ambang dengan biaya yang wajar dan memusatkan investasi peningkatan kinerja pada <em>order winners</em>. Selain itu, komposisi kedua faktor tersebut berubah sepanjang siklus hidup produk dan berbeda antarsegmen pasar, sehingga analisis harus dilakukan per segmen dan diperbarui secara berkala.</p>
      <h5>2.5.3 Matriks Strategi Operasi</h5>
      <p>Slack, Brandon-Jones dan Burgess (2022) menyediakan kerangka pemetaan yang disebut matriks strategi operasi, yaitu matriks yang mempertemukan lima sasaran kinerja operasi pada satu dimensi dengan empat area keputusan strategis pada dimensi lainnya. Lima sasaran kinerja tersebut adalah mutu (<em>quality</em>), kecepatan (<em>speed</em>), keandalan (<em>dependability</em>), fleksibilitas (<em>flexibility</em>), dan biaya (<em>cost</em>), sedangkan empat area keputusan mencakup kapasitas, jejaring pasokan, teknologi proses, serta pengembangan dan organisasi. Cara menggunakannya adalah sebagai berikut: pertama, tetapkan sasaran kinerja mana yang menjadi <em>order winners</em> dan <em>order qualifiers</em> bagi segmen pasar yang dilayani; kedua, telusuri setiap sel matriks untuk menilai apakah keputusan pada setiap area telah mendukung sasaran kinerja prioritas; ketiga, tandai sel yang kritis dan sel yang kosong atau tidak konsisten sebagai agenda perbaikan strategis. Matriks ini memaksa manajemen memeriksa kelengkapan dan koherensi strategi operasi secara menyeluruh.</p>
      <table class="bk-table">
        <caption>Tabel 2.2 Kerangka Matriks Strategi Operasi</caption>
        <thead><tr><th>Sasaran Kinerja</th><th>Kapasitas</th><th>Jejaring Pasokan</th><th>Teknologi Proses</th><th>Pengembangan dan Organisasi</th></tr></thead>
        <tbody>
          <tr><td>Mutu</td><td>Kecukupan kapasitas untuk inspeksi dan proses stabil</td><td>Seleksi dan sertifikasi pemasok</td><td>Otomasi dan kendali proses</td><td>Budaya mutu dan pelatihan</td></tr>
          <tr><td>Kecepatan</td><td>Kapasitas penyangga pada beban puncak</td><td>Pemasok yang dekat dan tanggap</td><td>Proses dengan waktu siklus pendek</td><td>Struktur keputusan yang ringkas</td></tr>
          <tr><td>Keandalan</td><td>Perencanaan kapasitas yang realistis</td><td>Kontrak tingkat layanan pemasok</td><td>Pemeliharaan preventif</td><td>Disiplin penjadwalan</td></tr>
          <tr><td>Fleksibilitas</td><td>Kapasitas yang dapat diskalakan</td><td>Basis pemasok majemuk</td><td>Teknologi serbaguna</td><td>Karyawan multiketerampilan</td></tr>
          <tr><td>Biaya</td><td>Utilisasi tinggi</td><td>Konsolidasi volume pembelian</td><td>Standardisasi proses</td><td>Perbaikan berkelanjutan</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Slack, Brandon-Jones dan Burgess (2022)</td></tr></tfoot>
      </table>`
    },
    {
      no: "2.6",
      title: "Isu dalam Strategi Operasi dan Proses Pengembangan Strategi",
      body: `<h5>2.6.1 Perspektif Analitis Pendahuluan</h5>
      <p>Sebelum strategi ditetapkan dan diimplementasikan, beberapa perspektif analitis perlu ditinjau. Pertama, pandangan sumber daya (<em>resources view</em>) menuntut manajer berpikir dalam kerangka sumber daya finansial, fisik, manusia, dan teknologi yang tersedia serta memastikan strategi yang diusulkan kompatibel dengan sumber daya tersebut (Heizer, Render dan Munson, 2017). Kedua, analisis rantai nilai (<em>value-chain analysis</em>) dari Porter digunakan untuk mengidentifikasi aktivitas yang menjadi kekuatan atau kekuatan potensial tempat perusahaan menambahkan nilai uniknya, misalnya riset produk, desain, manajemen rantai pasokan, inovasi proses, atau manajemen mutu. Ketiga, model lima kekuatan (<em>five forces model</em>) menganalisis lima kekuatan dalam lingkungan persaingan, yaitu pesaing langsung, pendatang potensial, pelanggan, pemasok, dan produk substitusi. Selain lingkungan persaingan, perusahaan beroperasi dalam sistem dengan faktor eksternal ekonomi, hukum, dan budaya yang menuntut pemindaian lingkungan secara terus-menerus.</p>
      <p>Perusahaan juga mengalami perubahan internal yang konstan, salah satunya melalui siklus hidup produk. Strategi operasi harus berubah ketika produk bergerak dari tahap perkenalan, pertumbuhan, kedewasaan, sampai penurunan. Pada tahap perkenalan, desain produk dan proses masih sering berubah sehingga biaya produksi tinggi dan fokus diarahkan pada mutu serta pengembangan; pada tahap pertumbuhan, peramalan dan penambahan kapasitas menjadi kritis; pada tahap kedewasaan, standardisasi, proses yang stabil, dan produksi berjangka panjang menjadi prioritas; dan pada tahap penurunan, minimisasi biaya serta pemangkasan lini produk yang tidak memberikan margin memadai menjadi keharusan (Heizer, Render dan Munson, 2017). Dengan demikian, strategi operasi bersifat dinamis mengikuti perubahan internal dan eksternal.</p>
      <h5>2.6.2 Analisis SWOT dan Proses Pengembangan Strategi</h5>
      <p>Analisis SWOT merupakan tinjauan formal atas kekuatan dan kelemahan internal serta peluang dan ancaman eksternal (Heizer, Render dan Munson, 2017). Melalui analisis ini organisasi memposisikan diri untuk memperoleh keunggulan bersaing dengan memaksimalkan peluang dan kekuatan sekaligus meminimalkan ancaman dan kelemahan. Proses pengembangan strategi berlangsung dalam tiga tahap, yaitu menganalisis lingkungan, menetapkan misi korporat, dan membentuk strategi yang membangun keunggulan bersaing, misalnya melalui harga rendah, fleksibilitas desain atau volume, mutu, kecepatan pengiriman, keandalan, layanan purnajual, atau lini produk yang luas. Gagasan awal mengenai misi kemudian dievaluasi ulang agar konsisten dengan hasil SWOT, dan strategi yang terbentuk dievaluasi terus-menerus terhadap nilai yang diberikan kepada pelanggan dan realitas persaingan.</p>
      <h5>2.6.3 Faktor Kunci Keberhasilan dan Kompetensi Inti</h5>
      <p>Karena tidak ada perusahaan yang unggul dalam segala hal, strategi yang berhasil menuntut identifikasi faktor kunci keberhasilan dan kompetensi inti. Faktor kunci keberhasilan (<em>key success factors</em>) merupakan aktivitas yang mutlak dikerjakan dengan baik agar perusahaan mencapai tujuannya, sedangkan kompetensi inti (<em>core competencies</em>) merupakan sekumpulan keterampilan, talenta, dan kapabilitas unik yang dilakukan perusahaan pada standar kelas dunia sehingga membedakannya dari pesaing (Heizer, Render dan Munson, 2017). Bagi McDonald's, tata letak dapur dan jalur pesan-antar merupakan faktor kunci keberhasilan, sementara konsistensi dan mutu merupakan kompetensi intinya; bagi Honda, kompetensi intinya adalah desain dan manufaktur mesin berbahan bakar bensin yang diterapkan pada beragam produk. Manajer operasi memulai penelusuran dengan tiga pertanyaan, yaitu tugas apa yang harus dikerjakan dengan sangat baik agar strategi berhasil, aktivitas mana yang memberikan keunggulan bersaing, dan elemen mana yang paling berisiko gagal sehingga memerlukan komitmen sumber daya tambahan.</p>
      <p>Faktor kunci keberhasilan dan kompetensi inti harus ditopang oleh aktivitas pendukung yang saling terkait. Salah satu alat identifikasinya adalah peta aktivitas (<em>activity map</em>) yang menghubungkan keunggulan bersaing, faktor kunci keberhasilan, dan aktivitas pendukung. Peta aktivitas Southwest Airlines memperlihatkan bagaimana armada seragam, waktu putar dua puluh menit, karyawan yang produktif, dan rute jarak pendek antarbandara sekunder saling memperkuat dalam menopang keunggulan biaya rendah. Semakin terintegrasi dan saling memperkuat aktivitas tersebut, semakin sulit strategi ditiru pesaing sehingga keunggulan menjadi lebih berkelanjutan. Implikasinya, imitasi parsial atas satu aktivitas, misalnya sekadar meniru tarif murah tanpa sistem aktivitas pendukungnya, jarang menghasilkan kinerja setara.</p>
      <h5>2.6.4 Implementasi Sepuluh Keputusan Strategis Manajemen Operasi</h5>
      <p>Setelah strategi, faktor kunci keberhasilan, dan integrasi aktivitas teridentifikasi, langkah berikutnya adalah mengelompokkan aktivitas ke dalam struktur organisasi dan mengisinya dengan personel yang tepat. Implementasi strategi pada akhirnya diwujudkan melalui sepuluh keputusan strategis manajemen operasi, yaitu desain barang dan jasa, mutu, desain proses dan kapasitas, lokasi, tata letak, sumber daya manusia, manajemen rantai pasokan, persediaan, penjadwalan, dan pemeliharaan. Bobot dan cara implementasi setiap keputusan berbeda bergantung pada strategi yang dipilih, bauran produk, tahap siklus hidup, dan lingkungan persaingan. Turban, Pollard dan Wood (2021) menambahkan bahwa teknologi informasi kini menjadi pemampu lintas keputusan tersebut, misalnya sistem perencanaan sumber daya perusahaan yang mengintegrasikan penjadwalan dan persediaan serta analitika data yang mempertajam keputusan kapasitas dan lokasi. Oleh karena itu, keselarasan antara strategi operasi dan strategi teknologi informasi merupakan syarat implementasi yang efektif pada era digital.</p>`
    },
    {
      no: "2.7",
      title: "Perencanaan Strategis, Kompetensi Inti, dan Alih Daya",
      body: `<h5>2.7.1 Konsep Alih Daya dan Teori Keunggulan Komparatif</h5>
      <p>Ketika organisasi mengidentifikasi kompetensi intinya, aktivitas yang bukan inti menjadi kandidat untuk dialihdayakan. Alih daya (<em>outsourcing</em>) didefinisikan sebagai pemindahan aktivitas perusahaan yang secara tradisional bersifat internal kepada pemasok eksternal (Heizer, Render dan Munson, 2017). Praktik ini merupakan perluasan dari keputusan klasik membuat atau membeli (<em>make-or-buy</em>) dan terus berkembang karena tiga tren global, yaitu meningkatnya keahlian teknologi, transportasi yang lebih andal dan murah, serta perkembangan pesat telekomunikasi dan komputer. Landasan ekonominya adalah teori keunggulan komparatif, yang menyatakan bahwa apabila penyedia eksternal dapat melaksanakan suatu aktivitas secara lebih produktif daripada perusahaan pembeli, maka aktivitas tersebut sebaiknya dikerjakan penyedia eksternal agar perusahaan dapat berfokus pada kompetensi intinya. Apple yang berfokus pada kreativitas dan desain sambil mengalihdayakan manufaktur, serta banyak perusahaan Indonesia yang menyerahkan pengelolaan pusat data kepada penyedia komputasi awan, merupakan penerapan logika tersebut (Turban, Pollard dan Wood, 2021).</p>
      <h5>2.7.2 Risiko dan Pertimbangan Alih Daya</h5>
      <p>Meskipun menjanjikan efisiensi, alih daya menambah kompleksitas dan risiko pada rantai pasokan. Hampir separuh perjanjian alih daya dinilai gagal karena perencanaan dan analisis yang tidak memadai, dengan masalah utama berupa ketepatan pengiriman, standar mutu, serta kenaikan biaya logistik dan persediaan yang diremehkan (Heizer, Render dan Munson, 2017). Potensi keunggulannya mencakup penghematan biaya, akses keahlian dan teknologi eksternal, perbaikan operasi dan layanan, serta terjaganya fokus pada kompetensi inti; sebaliknya, potensi kelemahannya mencakup kenaikan biaya logistik dan persediaan, hilangnya kendali atas mutu dan pengiriman, kemungkinan terciptanya pesaing masa depan, dampak negatif terhadap karyawan, serta risiko yang baru tampak setelah bertahun-tahun. Alih daya lintas negara menambah pertimbangan berupa daya tarik finansial, ketersediaan keterampilan, lingkungan bisnis, dan risiko reaksi politik atas pemindahan lapangan kerja, yang pada gilirannya mendorong fenomena <em>reshoring</em>, yaitu kembalinya aktivitas bisnis ke negara asal. Implikasinya, manajer harus berhati-hati agar elemen yang menjadi sumber keunggulan bersaing tidak ikut dialihdayakan.</p>
      <h5>2.7.3 Metode Pemeringkatan Faktor</h5>
      <p>Penyebab kegagalan alih daya yang paling umum adalah keputusan yang diambil tanpa analisis yang memadai. Metode pemeringkatan faktor (<em>factor-rating method</em>) menyediakan cara objektif untuk mengevaluasi penyedia alih daya maupun pilihan negara tujuan. Prosedurnya terdiri atas lima langkah, yaitu: menetapkan kriteria atau faktor yang relevan; memberikan bobot kepentingan w<sub>i</sub> pada setiap faktor dengan jumlah seluruh bobot sama dengan satu; memberikan skor r<sub>ij</sub> pada setiap alternatif j untuk setiap faktor i, misalnya pada skala satu sampai lima; menghitung skor tertimbang total setiap alternatif dengan rumus S<sub>j</sub> = &Sigma; (w<sub>i</sub> &times; r<sub>ij</sub>); dan memilih alternatif dengan skor tertimbang tertinggi. Tabel 2.3 menyajikan ilustrasi hipotetis sebuah bank di Jakarta yang mengevaluasi tiga penyedia alih daya pengembangan aplikasi.</p>
      <table class="bk-table">
        <caption>Tabel 2.3 Ilustrasi Pemeringkatan Faktor untuk Pemilihan Penyedia Alih Daya TI</caption>
        <thead><tr><th>Faktor</th><th>Bobot</th><th>Vendor A (Jakarta)</th><th>Vendor B (Vietnam)</th><th>Vendor C (India)</th></tr></thead>
        <tbody>
          <tr><td>Penghematan biaya</td><td>0,30</td><td>3 (0,90)</td><td>5 (1,50)</td><td>4 (1,20)</td></tr>
          <tr><td>Kompetensi teknis</td><td>0,25</td><td>4 (1,00)</td><td>3 (0,75)</td><td>5 (1,25)</td></tr>
          <tr><td>Mutu layanan</td><td>0,20</td><td>4 (0,80)</td><td>3 (0,60)</td><td>4 (0,80)</td></tr>
          <tr><td>Keamanan data</td><td>0,15</td><td>5 (0,75)</td><td>3 (0,45)</td><td>4 (0,60)</td></tr>
          <tr><td>Kesesuaian budaya kerja</td><td>0,10</td><td>5 (0,50)</td><td>3 (0,30)</td><td>3 (0,30)</td></tr>
          <tr><td><strong>Skor tertimbang total</strong></td><td>1,00</td><td><strong>3,95</strong></td><td><strong>3,60</strong></td><td><strong>4,15</strong></td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: ilustrasi hipotetis, diolah dengan metode dari Heizer, Render dan Munson (2017)</td></tr></tfoot>
      </table>
      <p>Berdasarkan perhitungan tersebut, Vendor C terpilih karena memiliki skor tertimbang tertinggi sebesar 4,15. Namun, apabila selisih skor antaralternatif tipis, analisis sensitivitas perlu dilakukan karena perubahan kecil pada bobot atau skor dapat mengubah keputusan akhir. Selain itu, pertimbangan kualitatif seperti regulasi perlindungan data pribadi di Indonesia dapat menjadi faktor pembatas yang harus dipenuhi sebelum skor kuantitatif diperbandingkan. Dengan demikian, metode ini sebaiknya diposisikan sebagai alat bantu strukturisasi keputusan, bukan pengganti pertimbangan manajerial.</p>`
    },
    {
      no: "2.8",
      title: "Opsi Strategi Operasi Global",
      body: `<p>Banyak strategi operasi kini menuntut dimensi internasional. Bisnis internasional adalah perusahaan yang terlibat dalam perdagangan atau investasi lintas negara, sedangkan korporasi multinasional adalah perusahaan dengan keterlibatan bisnis internasional yang luas, yang membeli sumber daya, menciptakan barang atau jasa, dan menjualnya di berbagai negara (Heizer, Render dan Munson, 2017). Manajer operasi perusahaan semacam itu memposisikan diri pada salah satu dari empat strategi operasi global yang dipetakan dalam matriks dengan sumbu vertikal tekanan penurunan biaya dan sumbu horizontal tekanan tanggapan lokal, yaitu kecepatan respons dan diferensiasi yang dibutuhkan pasar setempat.</p>
      <p>Strategi internasional (<em>international strategy</em>) menembus pasar global melalui ekspor dan lisensi dengan perubahan minimal pada operasi yang ada. Strategi ini paling mudah dijalankan namun paling sedikit memberikan keunggulan karena tanggapan lokalnya rendah dan keunggulan biayanya kecil. Strategi multidomestik (<em>multidomestic strategy</em>) mendesentralisasi wewenang keputusan operasi kepada setiap negara melalui anak perusahaan, waralaba, atau usaha patungan yang cukup otonom, sehingga tanggapan lokal maksimal meskipun keunggulan biaya terbatas; strategi ini lazim pada produsen makanan seperti Heinz dan jaringan McDonald's yang menyesuaikan menu dengan selera lokal, sebagaimana McDonald's Indonesia menyediakan nasi dan ayam goreng. Strategi global (<em>global strategy</em>) memusatkan keputusan di kantor pusat yang mengoordinasikan standardisasi dan pembelajaran antarpabrik untuk meraih skala ekonomi, sehingga sesuai ketika fokus strategis adalah penurunan biaya dan produk relatif seragam di seluruh dunia, seperti alat berat Caterpillar. Terakhir, strategi transnasional (<em>transnational strategy</em>) menggabungkan efisiensi skala global dengan tanggapan lokal dengan mengakui bahwa kompetensi inti dapat berada di mana pun dalam organisasi, sehingga material, orang, dan gagasan melintasi batas negara, sebagaimana dipraktikkan Nestle yang sebagian besar aset, penjualan, dan karyawannya berada di luar negara asalnya.</p>
      <table class="bk-table">
        <caption>Tabel 2.4 Perbandingan Empat Strategi Operasi Global</caption>
        <thead><tr><th>Strategi</th><th>Tekanan Biaya</th><th>Tanggapan Lokal</th><th>Mekanisme Utama</th><th>Contoh</th></tr></thead>
        <tbody>
          <tr><td>Internasional</td><td>Rendah</td><td>Rendah</td><td>Ekspor dan lisensi produk yang ada</td><td>Harley-Davidson, US Steel</td></tr>
          <tr><td>Multidomestik</td><td>Rendah</td><td>Tinggi</td><td>Desentralisasi melalui anak perusahaan, waralaba, usaha patungan</td><td>Heinz, McDonald's, The Body Shop</td></tr>
          <tr><td>Global</td><td>Tinggi</td><td>Rendah</td><td>Sentralisasi, standardisasi, skala ekonomi</td><td>Caterpillar, Texas Instruments</td></tr>
          <tr><td>Transnasional</td><td>Tinggi</td><td>Tinggi</td><td>Jejaring saling tergantung, aliran material, orang, dan gagasan lintas negara</td><td>Nestle, Coca-Cola</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017)</td></tr></tfoot>
      </table>
      <p>Pemilihan strategi bergantung pada karakteristik produk dan pasar. Produk yang seragam secara global dengan persaingan berbasis harga mengarah pada strategi global, sedangkan produk yang sangat dipengaruhi selera lokal mengarah pada strategi multidomestik. Perusahaan Indonesia yang mulai mendunia dapat memanfaatkan kerangka ini; Indofood, misalnya, bergerak dari strategi internasional berbasis ekspor menuju pola multidomestik dengan fasilitas produksi dan penyesuaian rasa di pasar Afrika dan Timur Tengah. Dengan demikian, matriks strategi global membantu manajer operasi menilai posisi saat ini dan arah evolusi konfigurasi operasi internasionalnya, karena posisi dalam matriks dapat berubah seiring perkembangan kapabilitas dan tekanan pasar.</p>`
    },
    {
      no: "2.9",
      title: "Rangkuman",
      body: `<p>Strategi operasi dalam lingkungan global berangkat dari kenyataan bahwa pelanggan, talenta, dan pemasok kini tersebar di seluruh dunia. Perusahaan menginternasionalisasi operasinya untuk memperbaiki rantai pasokan, menurunkan biaya dan risiko nilai tukar, memperbaiki operasi dan produk, memahami pasar, serta menarik talenta global, dengan tetap memperhatikan perbedaan budaya dan etika antarnegara. Arah organisasi ditetapkan melalui misi, kemudian diterjemahkan menjadi strategi yang diwujudkan fungsi operasi melalui tiga pendekatan keunggulan bersaing, yaitu diferensiasi, kepemimpinan biaya, dan respons, yang seluruhnya diimplementasikan melalui sepuluh keputusan strategis manajemen operasi.</p>
      <p>Kerangka empat perspektif strategi operasi menegaskan bahwa strategi yang efektif merupakan rekonsiliasi antara arah korporat, pembelajaran operasional, kebutuhan pasar, dan kapabilitas sumber daya. Konsep <em>order winners</em> dan <em>order qualifiers</em> membantu memprioritaskan sasaran kinerja, sedangkan matriks strategi operasi memeriksa koherensi antara sasaran kinerja dan area keputusan. Analisis SWOT, pandangan sumber daya, rantai nilai, lima kekuatan, dan siklus hidup produk memperkaya proses pengembangan strategi, yang kemudian dipertajam melalui identifikasi faktor kunci keberhasilan dan kompetensi inti serta pemetaan aktivitas pendukungnya.</p>
      <p>Keputusan alih daya memungkinkan perusahaan berfokus pada kompetensi inti sesuai teori keunggulan komparatif, namun mengandung risiko kehilangan kendali yang menuntut analisis cermat, antara lain melalui metode pemeringkatan faktor. Pada tataran internasional, perusahaan memilih di antara strategi internasional, multidomestik, global, atau transnasional sesuai tekanan penurunan biaya dan tuntutan tanggapan lokal yang dihadapinya. Dengan demikian, sesi ini menegaskan bahwa fungsi operasi bukan sekadar pelaksana, melainkan sumber keunggulan bersaing yang strategis.</p>`
    },
    {
      no: "2.10",
      title: "Daftar Pustaka",
      body: `<p>Heizer, J., Render, B. dan Munson, C. (2017). <em>Operations Management: Sustainability and Supply Chain Management</em>. Edisi ke-12. Pearson Education.</p>
      <p>Slack, N., Brandon-Jones, A. dan Burgess, N. (2022). <em>Operations Management</em>. Edisi ke-10. Pearson Education.</p>
      <p>Turban, E., Pollard, C. dan Wood, G. (2021). <em>Information Technology for Management: Driving Digital Transformation to Increase Local and Global Performance, Growth and Sustainability</em>. Edisi ke-12. John Wiley and Sons.</p>`
    }
  ]
};
