window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.otm = window.MBA_BOOK.otm || {};
window.MBA_BOOK.otm[1] = {
  bab: 1,
  judul: "MANAJEMEN OPERASI DAN RANTAI NILAI BISNIS",
  sumber: "Heizer, Render dan Munson (2017), Operations Management 12e; Turban, Pollard dan Wood (2021), IT for Management 12e; Slack, Brandon-Jones dan Burgess (2022), Operations Management 10e",
  lo: [
    "LO1 Mendefinisikan manajemen operasi serta menjelaskan kedudukan fungsi operasi di antara tiga fungsi dasar organisasi.",
    "LO2 Menjelaskan model transformasi input-proses-output beserta empat karakteristik proses operasi (4V).",
    "LO3 Menjelaskan konsep rantai nilai bisnis dan rantai pasok sebagai jaringan penciptaan nilai bagi pelanggan.",
    "LO4 Menjelaskan perbedaan antara operasi barang dan operasi jasa serta implikasinya bagi pengelolaan operasi.",
    "LO5 Membedakan produksi dan produktivitas serta menghitung produktivitas faktor tunggal dan produktivitas multifaktor.",
    "LO6 Mengidentifikasi variabel kritis dalam peningkatan produktivitas serta tantangan kontemporer manajemen operasi.",
    "LO7 Menjelaskan peran teknologi informasi, ekonomi on-demand dan rekayasa ulang proses bisnis dalam transformasi digital operasi perusahaan."
  ],
  sections: [
    {
      no: "1.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini merupakan sesi pembuka mata kuliah Operations and Technology Management yang membahas kedudukan fungsi operasi dalam organisasi bisnis serta keterkaitannya dengan rantai nilai bisnis (<em>business value chain</em>). Pembahasan mencakup konsep dasar manajemen operasi, model transformasi, karakteristik proses operasi, rantai nilai dan rantai pasok, perbedaan operasi barang dan jasa, produktivitas, perkembangan historis disiplin, serta tantangan kontemporer dan peran teknologi informasi dalam transformasi digital operasi bisnis. Materi disintesiskan dari Heizer, Render dan Munson (2017), Slack, Brandon-Jones dan Burgess (2022), serta Turban, Pollard dan Wood (2021).</p>
<p>Setelah menyelesaikan sesi ini, mahasiswa diharapkan memiliki capaian pembelajaran sebagai berikut:</p>
<ul>
<li>Mendefinisikan manajemen operasi serta menjelaskan kedudukan fungsi operasi di antara tiga fungsi dasar organisasi.</li>
<li>Menjelaskan model transformasi input-proses-output beserta empat karakteristik proses operasi yang dikenal sebagai 4V.</li>
<li>Menjelaskan konsep rantai nilai bisnis dan rantai pasok sebagai jaringan penciptaan nilai bagi pelanggan.</li>
<li>Menjelaskan perbedaan antara operasi barang dan operasi jasa serta implikasinya bagi pengelolaan operasi.</li>
<li>Membedakan produksi dan produktivitas serta menghitung produktivitas faktor tunggal dan produktivitas multifaktor.</li>
<li>Mengidentifikasi variabel kritis dalam peningkatan produktivitas serta tantangan kontemporer manajemen operasi.</li>
<li>Menjelaskan peran teknologi informasi, ekonomi <em>on-demand</em> dan rekayasa ulang proses bisnis dalam transformasi digital operasi perusahaan.</li>
</ul>`
    },
    {
      no: "1.2",
      title: "Konsep Dasar Manajemen Operasi",
      body: `<h5>1.2.1 Definisi Produksi dan Manajemen Operasi</h5>
<p>Setiap organisasi, baik yang berorientasi laba maupun nirlaba, pada hakikatnya menjalankan kegiatan menghasilkan barang atau jasa bagi pihak yang dilayaninya. Menurut Heizer, Render dan Munson (2017), produksi (<em>production</em>) adalah kegiatan penciptaan barang dan jasa, sedangkan manajemen operasi (<em>operations management</em>) adalah serangkaian aktivitas yang menciptakan nilai dalam bentuk barang dan jasa melalui transformasi masukan menjadi keluaran. Sementara itu, Slack, Brandon-Jones dan Burgess (2022) mendefinisikan manajemen operasi sebagai aktivitas mengelola sumber daya yang ditujukan untuk memproduksi dan menyampaikan produk serta jasa kepada pelanggan. Dari kedua definisi tersebut dapat disimpulkan bahwa manajemen operasi merupakan fungsi manajerial yang bertanggung jawab mengelola proses transformasi sumber daya menjadi barang dan jasa yang bernilai bagi pelanggan secara efektif dan efisien.</p>
<p>Pada perusahaan manufaktur, kegiatan produksi mudah diamati karena menghasilkan produk berwujud seperti kendaraan bermotor atau peralatan elektronik. Sebaliknya, pada organisasi jasa fungsi produksi sering tidak tampak oleh publik, misalnya pemindahan dana antar-rekening di bank, pengisian kursi kosong pada suatu penerbangan, atau proses pendidikan seorang mahasiswa (Heizer, Render dan Munson, 2017). Heizer, Render dan Munson (2017) mencontohkan Hard Rock Cafe yang setiap hari menghasilkan ribuan hidangan; manajer operasinya merancang menu, menguji resep, memilih pemasok, menjadwalkan karyawan dan menata tata letak dapur agar makanan berkualitas tersaji tepat waktu. Dengan demikian, prinsip manajemen operasi berlaku universal pada pabrik, rumah sakit, restoran, bank maupun kantor pemerintahan.</p>
<h5>1.2.2 Tiga Fungsi Dasar Organisasi</h5>
<p>Untuk menghasilkan barang dan jasa, seluruh organisasi menjalankan tiga fungsi dasar, yaitu: pemasaran yang membangkitkan permintaan atau setidaknya menerima pesanan atas produk; produksi atau operasi yang menciptakan, memproduksi dan menyampaikan produk; serta keuangan dan akuntansi yang memantau kesehatan organisasi, membayar tagihan dan mengumpulkan kas (Heizer, Render dan Munson, 2017). Ketiga fungsi tersebut merupakan prasyarat kelangsungan hidup organisasi sehingga fungsi operasi tidak dapat dikelola secara terpisah dari fungsi lainnya. Pada bank komersial, misalnya, fungsi operasi mencakup penjadwalan teller, kliring cek dan pemrosesan transaksi, sedangkan pada maskapai penerbangan meliputi dukungan darat, pemeliharaan pesawat dan penjadwalan awak. Oleh karena itu, mahasiswa manajemen perlu memahami cara fungsi operasi berinteraksi dengan pemasaran dan keuangan dalam menciptakan nilai bagi pelanggan.</p>
<h5>1.2.3 Alasan Mempelajari Manajemen Operasi</h5>
<p>Terdapat empat alasan utama mempelajari manajemen operasi. Pertama, manajemen operasi merupakan salah satu dari tiga fungsi utama organisasi yang terkait erat dengan seluruh fungsi bisnis lainnya. Kedua, dengan mempelajari manajemen operasi seseorang memahami bagaimana barang dan jasa dihasilkan oleh masyarakat. Ketiga, pemahaman atas pekerjaan manajer operasi membantu siapa pun bekerja lebih baik pada posisi apa pun sekaligus membuka peluang karier yang luas. Keempat, manajemen operasi merupakan bagian organisasi yang paling banyak menyerap biaya sehingga menjadi peluang terbesar untuk memperbaiki profitabilitas (Heizer, Render dan Munson, 2017).</p>
<p>Alasan keempat dapat diilustrasikan melalui contoh Fisher Technologies yang dianalisis oleh Heizer, Render dan Munson (2017). Menaikkan penjualan 50 persen melalui opsi pemasaran hanya meningkatkan kontribusi terhadap biaya tetap dan laba sebesar 71 persen, dan memangkas biaya pendanaan 50 persen melalui opsi keuangan hanya menaikkan kontribusi 21 persen, sedangkan menurunkan biaya produksi 20 persen melalui opsi operasi meningkatkan kontribusi 114 persen. Selain berdampak terbesar, opsi operasi sering merupakan satu-satunya opsi yang layak karena dua opsi lainnya dalam praktik sangat sulit dicapai. Dengan demikian, perbaikan operasi merupakan tuas yang paling efektif bagi manajemen dalam memperbaiki kinerja keuangan perusahaan.</p>
<h5>1.2.4 Sepuluh Keputusan Strategis Manajemen Operasi</h5>
<p>Manajer operasi menjalankan proses manajemen yang terdiri atas perencanaan, pengorganisasian, pengisian staf, kepemimpinan dan pengendalian terhadap serangkaian area keputusan. Heizer, Render dan Munson (2017) merumuskan sepuluh keputusan strategis manajemen operasi yang menjadi kerangka kerja bagi keseluruhan aktivitas operasi, sebagaimana disintesiskan pada Tabel 1.1 berikut.</p>
<table class="bk-table">
<caption>Tabel 1.1 Sepuluh Keputusan Strategis Manajemen Operasi</caption>
<thead><tr><th>Keputusan</th><th>Esensi Persoalan yang Dijawab</th></tr></thead>
<tbody>
<tr><td>Desain barang dan jasa</td><td>Menentukan produk apa yang ditawarkan; desain produk menetapkan batas bawah biaya dan batas atas kualitas.</td></tr>
<tr><td>Manajemen kualitas</td><td>Menetapkan ekspektasi kualitas pelanggan serta kebijakan dan prosedur untuk mencapainya.</td></tr>
<tr><td>Strategi proses dan kapasitas</td><td>Menentukan cara produk dihasilkan serta komitmen teknologi, sumber daya manusia dan modal yang membentuk struktur biaya dasar.</td></tr>
<tr><td>Strategi lokasi</td><td>Menimbang kedekatan dengan pelanggan, pemasok dan talenta terhadap biaya, infrastruktur dan regulasi.</td></tr>
<tr><td>Strategi tata letak</td><td>Mengatur aliran material, orang dan informasi yang efisien sesuai kebutuhan kapasitas dan teknologi.</td></tr>
<tr><td>Sumber daya manusia dan desain pekerjaan</td><td>Menentukan cara merekrut, memotivasi dan mempertahankan personel dengan talenta yang dibutuhkan.</td></tr>
<tr><td>Manajemen rantai pasok</td><td>Memutuskan apa yang dibeli, dari siapa dan dengan syarat apa dalam kerangka integrasi strategi perusahaan.</td></tr>
<tr><td>Manajemen persediaan</td><td>Mengoptimalkan keputusan pemesanan dan penyimpanan persediaan dengan mempertimbangkan kepuasan pelanggan dan kapabilitas pemasok.</td></tr>
<tr><td>Penjadwalan</td><td>Menyusun jadwal jangka menengah dan pendek yang mendayagunakan personel dan fasilitas sekaligus memenuhi permintaan.</td></tr>
<tr><td>Pemeliharaan</td><td>Menjaga keandalan dan stabilitas proses dengan mempertimbangkan kapasitas fasilitas dan tuntutan produksi.</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017)</td></tr></tfoot>
</table>
<p>Kesepuluh keputusan tersebut saling terkait satu sama lain. Sebagai contoh, keputusan desain produk menentukan tuntutan terhadap proses, kapasitas, kualitas dan sumber daya manusia, sedangkan keputusan lokasi memengaruhi biaya logistik dan struktur rantai pasok. Oleh karena itu, efektivitas seorang manajer operasi dinilai dari kemampuannya mengambil kesepuluh keputusan tersebut secara konsisten dengan strategi bersaing perusahaan.</p>`
    },
    {
      no: "1.3",
      title: "Model Transformasi dan Karakteristik Proses Operasi",
      body: `<h5>1.3.1 Model Input-Transformasi-Output</h5>
<p>Kerangka analitis paling mendasar dalam manajemen operasi adalah model transformasi <em>input-transformation-output</em>. Menurut Slack, Brandon-Jones dan Burgess (2022), seluruh operasi dapat digambarkan sebagai proses yang mengambil sekumpulan masukan, mentransformasikannya, kemudian menghasilkan keluaran berupa barang dan jasa. Masukan dibedakan menjadi dua kelompok, yaitu sumber daya yang ditransformasikan (<em>transformed resources</em>) yang meliputi material, informasi dan pelanggan, serta sumber daya yang mentransformasikan (<em>transforming resources</em>) yang meliputi fasilitas, teknologi dan sumber daya manusia. Proses transformasi dapat mengubah sifat fisik material, kepemilikan atau lokasi informasi, maupun kondisi fisiologis dan psikologis pelanggan.</p>
<p>Heizer, Render dan Munson (2017) melengkapi model tersebut dengan lingkar umpan balik (<em>feedback loop</em>) yang mengevaluasi kinerja proses terhadap strategi atau standar serta menilai kepuasan pelanggan, kemudian mengirimkan sinyal kepada manajer yang mengendalikan masukan dan proses transformasi. Sebagai ilustrasi, rumah sakit mentransformasikan kondisi kesehatan pasien, operator kereta komuter di wilayah Jakarta mentransformasikan lokasi penumpang, sedangkan restoran Padang mentransformasikan bahan pangan mentah menjadi hidangan sekaligus pengalaman layanan. Implikasi manajerialnya, manajer operasi harus mampu mengidentifikasi masukan, proses dan keluaran pada unit yang dikelolanya karena pemetaan tersebut merupakan titik awal untuk menemukan peluang perbaikan kinerja.</p>
<h5>1.3.2 Empat Karakteristik Proses Operasi (4V)</h5>
<p>Meskipun seluruh operasi memiliki kesamaan model transformasi, proses operasi berbeda satu sama lain dalam empat dimensi yang dikenal sebagai 4V, yaitu volume, variasi (<em>variety</em>), variabilitas permintaan (<em>variation in demand</em>) dan tingkat keterlihatan (<em>visibility</em>) (Slack, Brandon-Jones dan Burgess, 2022). Keempat dimensi tersebut menentukan cara proses dirancang serta struktur biaya yang menyertainya, sebagaimana disintesiskan pada Tabel 1.2.</p>
<table class="bk-table">
<caption>Tabel 1.2 Empat Dimensi Karakteristik Proses Operasi (4V)</caption>
<thead><tr><th>Dimensi</th><th>Pengertian</th><th>Implikasi apabila Tinggi</th><th>Implikasi apabila Rendah</th></tr></thead>
<tbody>
<tr><td>Volume</td><td>Jumlah keluaran yang dihasilkan per periode</td><td>Sistematisasi, spesialisasi tugas dan biaya per unit rendah</td><td>Tugas beragam per karyawan dan biaya per unit tinggi</td></tr>
<tr><td>Variety</td><td>Keragaman jenis produk atau jasa yang ditawarkan</td><td>Proses fleksibel, kompleks dan berbiaya tinggi</td><td>Proses terstandardisasi, rutin dan berbiaya rendah</td></tr>
<tr><td>Variation</td><td>Fluktuasi permintaan dari waktu ke waktu</td><td>Kapasitas harus adaptif sehingga utilisasi rendah dan biaya tinggi</td><td>Permintaan stabil, utilisasi tinggi dan biaya rendah</td></tr>
<tr><td>Visibility</td><td>Sejauh mana proses dialami langsung oleh pelanggan</td><td>Kontak pelanggan tinggi, toleransi tunggu pendek dan biaya tinggi</td><td>Proses dapat dipisahkan dari pelanggan dan dijalankan efisien</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Slack, Brandon-Jones dan Burgess (2022)</td></tr></tfoot>
</table>
<p>Secara umum, kombinasi volume tinggi dengan variasi, variabilitas dan keterlihatan yang rendah menghasilkan biaya operasi terendah. Sebagai contoh, jaringan gerai kopi modern di Indonesia yang melayani volume pesanan besar dengan menu terbatas mampu menawarkan harga per cangkir yang rendah, sedangkan kafe spesialti yang meracik setiap cangkir sesuai selera individual pelanggan menanggung biaya per unit yang jauh lebih tinggi. Oleh karena itu, manajer operasi perlu memetakan profil 4V unit operasinya sebelum menentukan desain proses, tingkat otomatisasi dan kebijakan kapasitas yang sesuai.</p>`
    },
    {
      no: "1.4",
      title: "Rantai Nilai Bisnis dan Rantai Pasok",
      body: `<p>Nilai bagi pelanggan tidak diciptakan oleh satu aktivitas tunggal, melainkan oleh rangkaian aktivitas yang saling terkait mulai dari perancangan produk, pengadaan bahan baku, produksi, distribusi, pemasaran hingga layanan purnajual. Rangkaian aktivitas yang setiap tahapnya menambahkan nilai inilah yang disebut rantai nilai bisnis (<em>business value chain</em>). Dalam perspektif manajemen operasi, setiap mata rantai harus memberikan nilai tambah yang lebih besar daripada biaya yang ditimbulkannya; aktivitas yang tidak menambah nilai merupakan pemborosan yang perlu dieliminasi. Melalui tiga fungsi dasar organisasi, yaitu pemasaran, operasi dan keuangan, nilai bagi pelanggan diciptakan dan diwujudkan (Heizer, Render dan Munson, 2017).</p>
<p>Namun, perusahaan jarang menciptakan seluruh nilai tersebut sendirian. Menurut Heizer, Render dan Munson (2017), rantai pasok (<em>supply chain</em>) adalah jaringan global organisasi dan aktivitas yang memasok barang dan jasa kepada sebuah perusahaan. Sebotol minuman ringan, misalnya, melibatkan petani tebu, produsen sirup, perusahaan pembotolan, distributor dan pengecer yang masing-masing menambahkan nilai sebelum produk sampai ke konsumen akhir. Spesialisasi keahlian, komunikasi instan dan biaya transportasi yang murah mendorong rantai pasok menjadi mendunia karena tidak lagi menguntungkan bagi perusahaan untuk mengerjakan segala sesuatunya sendiri. Heizer, Render dan Munson (2017) menegaskan pergeseran arena persaingan ini dalam pernyataan "Competition in the 21st century is not between companies; it is between supply chains". Dengan demikian, kolaborasi antaranggota rantai pasok menjadi sumber efisiensi sekaligus keunggulan bersaing (<em>competitive advantage</em>).</p>
<p>Dalam konteks Indonesia, kerangka rantai nilai dapat diamati pada Indofood yang mengintegrasikan aktivitas dari penggilingan tepung terigu, manufaktur mi instan, distribusi, sampai jaringan ritel sehingga nilai tambah tercipta pada setiap tahap. Contoh lain adalah ekosistem digital GoTo yang menghubungkan mitra pengemudi, pedagang usaha mikro, kecil dan menengah, serta konsumen dalam satu platform sehingga penciptaan nilai terjadi secara simultan pada banyak mata rantai. Implikasi manajerialnya, manajer operasi harus memutuskan aktivitas mana yang dikerjakan sendiri dan aktivitas mana yang diserahkan kepada pemasok, membangun kemitraan jangka panjang dengan pemasok kunci, serta memastikan seluruh mata rantai terkoordinasi demi kepuasan pelanggan akhir.</p>`
    },
    {
      no: "1.5",
      title: "Operasi Barang dan Jasa",
      body: `<p>Perusahaan manufaktur menghasilkan produk berwujud, sedangkan produk jasa umumnya tidak berwujud. Meskipun demikian, aktivitas operasi keduanya memiliki banyak kesamaan, seperti adanya standar kualitas, jadwal produksi yang menyesuaikan permintaan, serta fasilitas tempat orang bekerja (Heizer, Render dan Munson, 2017). Perbedaan pokok antara karakteristik barang dan jasa disintesiskan pada Tabel 1.3 berikut.</p>
<table class="bk-table">
<caption>Tabel 1.3 Perbandingan Karakteristik Barang dan Jasa</caption>
<thead><tr><th>Aspek</th><th>Karakteristik Jasa</th><th>Karakteristik Barang</th></tr></thead>
<tbody>
<tr><td>Wujud</td><td>Tidak berwujud, misalnya pengalaman menumpang pesawat</td><td>Berwujud dan dapat disentuh, misalnya kursi pesawat itu sendiri</td></tr>
<tr><td>Waktu produksi dan konsumsi</td><td>Diproduksi dan dikonsumsi secara bersamaan</td><td>Dapat disimpan sebagai persediaan</td></tr>
<tr><td>Keunikan</td><td>Cenderung unik bagi setiap pelanggan</td><td>Produk serupa diproduksi berulang</td></tr>
<tr><td>Interaksi pelanggan</td><td>Interaksi tinggi dan sering menjadi inti layanan</td><td>Keterlibatan pelanggan dalam produksi terbatas</td></tr>
<tr><td>Standardisasi</td><td>Definisi produk tidak konsisten antarpelanggan</td><td>Produk terstandardisasi sehingga otomatisasi layak</td></tr>
<tr><td>Lokasi</td><td>Layanan tersebar mendekati pelanggan</td><td>Umumnya diproduksi pada fasilitas tetap</td></tr>
<tr><td>Evaluasi kualitas</td><td>Kualitas sulit dievaluasi secara objektif</td><td>Banyak aspek kualitas mudah diukur</td></tr>
<tr><td>Penjualan kembali</td><td>Tidak lazim dijual kembali</td><td>Produk sering memiliki nilai sisa</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017)</td></tr></tfoot>
</table>
<p>Dalam praktik, batas antara barang dan jasa tidak selalu tegas karena hampir semua produk merupakan bauran keduanya. Penjualan mobil menyertakan jasa pembiayaan dan pengiriman, mesin fotokopi memerlukan pelatihan dan pemeliharaan purnajual, sedangkan jasa konsultansi tetap menghasilkan laporan yang berwujud (Heizer, Render dan Munson, 2017). Jasa yang sepenuhnya murni tanpa komponen berwujud sangat jarang ditemukan. Oleh karena itu, manajer operasi perlu mengelola kombinasi elemen barang dan jasa dalam setiap penawaran produknya.</p>
<p>Sektor jasa telah tumbuh menjadi sektor ekonomi terbesar pada masyarakat pascaindustri; di Amerika Serikat lebih dari 85 persen lapangan kerja berada pada sektor jasa sebagai akibat peningkatan produktivitas pertanian dan manufaktur yang membebaskan sumber daya untuk kegiatan jasa (Heizer, Render dan Munson, 2017). Kecenderungan serupa terjadi di Indonesia seiring berkembangnya jasa keuangan digital, logistik, telekomunikasi dan pariwisata. Selain itu, anggapan bahwa pekerjaan jasa selalu bergaji rendah tidak sepenuhnya benar karena banyak posisi jasa, seperti manajer operasi fasilitas pemeliharaan pesawat, memperoleh imbalan tinggi. Dengan demikian, penguasaan teknik manajemen operasi pada konteks jasa menjadi kompetensi strategis bagi mahasiswa magister manajemen.</p>`
    },
    {
      no: "1.6",
      title: "Tantangan Produktivitas",
      body: `<h5>1.6.1 Produksi versus Produktivitas</h5>
<p>Produksi dan produktivitas merupakan dua konsep yang sering dicampuradukkan padahal maknanya berbeda. Produksi mengacu pada jumlah barang dan jasa yang dihasilkan, sedangkan produktivitas menurut Heizer, Render dan Munson (2017) adalah rasio antara keluaran berupa barang dan jasa dengan masukan berupa sumber daya seperti tenaga kerja dan modal. Produksi yang tinggi hanya menunjukkan bahwa banyak orang bekerja, dan tidak dengan sendirinya menunjukkan produktivitas yang tinggi. Peningkatan produktivitas berarti memperbaiki rasio tersebut, yaitu menghasilkan keluaran lebih banyak dengan masukan yang sama atau menghasilkan keluaran yang sama dengan masukan lebih sedikit. Hanya melalui peningkatan produktivitas standar hidup masyarakat dapat membaik, karena kenaikan imbalan bagi tenaga kerja, modal dan manajemen tanpa kenaikan produktivitas hanya akan mendorong kenaikan harga (Heizer, Render dan Munson, 2017).</p>
<h5>1.6.2 Pengukuran Produktivitas</h5>
<p>Pengukuran produktivitas yang paling sederhana menggunakan satu jenis masukan dan disebut produktivitas faktor tunggal (<em>single-factor productivity</em>) dengan rumus: Produktivitas = Unit yang dihasilkan dibagi Masukan yang digunakan. Sebagai contoh, apabila sebuah konveksi menghasilkan 1.200 potong pakaian dengan 300 jam kerja, maka produktivitas tenaga kerjanya adalah 1.200 dibagi 300, yaitu 4 potong per jam kerja. Masukan yang digunakan tidak terbatas pada jam kerja; modal, material, atau energi juga dapat menjadi penyebut sesuai tujuan analisis (Heizer, Render dan Munson, 2017).</p>
<p>Pandangan yang lebih menyeluruh diberikan oleh produktivitas multifaktor (<em>multifactor productivity</em>) yang memasukkan seluruh masukan dan dihitung dengan rumus: Produktivitas multifaktor = Keluaran dibagi jumlah dari Tenaga kerja, Material, Energi, Modal dan Masukan lain-lain, dengan seluruh masukan dinyatakan dalam satuan uang (Heizer, Render dan Munson, 2017). Sebagai ilustrasi dalam konteks Indonesia, sebuah usaha konveksi batik menghasilkan 600 kemeja per hari dengan total biaya masukan Rp25 juta sehingga produktivitas multifaktornya adalah 24 kemeja per juta rupiah. Apabila perbaikan tata letak menaikkan keluaran menjadi 660 kemeja tanpa tambahan masukan, produktivitas menjadi 26,4 kemeja per juta rupiah atau meningkat 10 persen. Cara penggunaannya adalah membandingkan angka produktivitas antarperiode, antarfasilitas, atau dengan pesaing untuk menilai apakah pengelolaan sumber daya membaik.</p>
<p>Namun, pengukuran produktivitas memiliki sejumlah keterbatasan. Pertama, kualitas dapat berubah meskipun jumlah masukan dan keluaran tetap, misalnya televisi masa kini jauh lebih baik daripada televisi beberapa dekade lalu meskipun satuan hitungnya sama. Kedua, faktor eksternal seperti keandalan pasokan listrik dapat menaikkan atau menurunkan produktivitas tanpa keterkaitan dengan keputusan manajerial di dalam perusahaan. Ketiga, satuan pengukuran yang presisi sering tidak tersedia karena produk tidak selalu homogen (Heizer, Render dan Munson, 2017). Kesulitan ini semakin besar pada sektor jasa karena keluaran layanan, seperti hasil sebuah perkara hukum atau kualitas potongan rambut, sulit didefinisikan secara kuantitatif.</p>
<h5>1.6.3 Variabel Produktivitas</h5>
<p>Heizer, Render dan Munson (2017) mengidentifikasi tiga variabel yang menentukan peningkatan produktivitas, yaitu tenaga kerja yang menyumbang sekitar 10 persen dari kenaikan tahunan, modal yang menyumbang sekitar 38 persen, dan manajemen yang menyumbang sekitar 52 persen. Kontribusi tenaga kerja diperbaiki melalui pendidikan dasar, gizi angkatan kerja, serta infrastruktur sosial seperti transportasi dan sanitasi. Modal berperan karena manusia memerlukan alat untuk bekerja, sehingga penurunan investasi modal per karyawan dapat menekan produktivitas, sedangkan inflasi dan pajak yang menaikkan biaya modal menggeser pertukaran antara penggunaan modal dan tenaga kerja. Adapun manajemen bertanggung jawab memastikan tenaga kerja dan modal digunakan secara efektif, termasuk mengaplikasikan teknologi dan pengetahuan pada masyarakat pengetahuan (<em>knowledge society</em>) yang angkatan kerjanya telah bergeser dari pekerjaan manual ke pekerjaan berbasis pengetahuan. Implikasi manajerialnya, negara maupun perusahaan tidak dapat menjadi pesaing kelas dunia dengan masukan kelas dua, sehingga investasi pada pendidikan, teknologi dan kapabilitas manajerial merupakan prasyarat produktivitas tinggi.</p>
<h5>1.6.4 Produktivitas Sektor Jasa</h5>
<p>Produktivitas sektor jasa terbukti sulit ditingkatkan karena pekerjaan jasa umumnya padat karya, berfokus pada atribut atau keinginan individual, berupa tugas intelektual yang dijalankan profesional, sulit dimekanisasi, serta sulit dievaluasi kualitasnya (Heizer, Render dan Munson, 2017). Meskipun demikian, perbaikan tetap dimungkinkan. Heizer, Render dan Munson (2017) menceritakan bahwa Starbucks memperbaiki produktivitas gerainya sekitar 27 persen dalam beberapa tahun melalui perbaikan kecil seperti perancangan ulang sendok es dan mesin espresso yang lebih cepat, sedangkan Taco Bell memindahkan sebagian persiapan makanan ke pemasok sehingga waktu layanan dan kebutuhan ruang dapur turun drastis. Dalam konteks Indonesia, perbankan nasional memindahkan sebagian besar transaksi dari kantor cabang ke aplikasi <em>mobile banking</em> sehingga jumlah transaksi yang dilayani per pegawai meningkat berlipat tanpa penambahan kantor. Dengan demikian, perhatian manajemen terhadap cara kerja yang sesungguhnya terjadi di lapangan mampu menghasilkan lompatan produktivitas sekalipun pada sektor jasa.</p>`
    },
    {
      no: "1.7",
      title: "Perkembangan Historis Manajemen Operasi",
      body: `<p>Disiplin manajemen operasi relatif muda, namun akarnya panjang dan kaya. Eli Whitney pada awal abad kesembilan belas mempopulerkan konsep komponen yang dapat dipertukarkan (<em>interchangeable parts</em>) melalui standardisasi dan pengendalian kualitas. Frederick W. Taylor, yang dikenal sebagai bapak manajemen ilmiah, memberikan kontribusi pada seleksi personel, perencanaan, penjadwalan dan studi gerak, serta meyakini bahwa manajemen harus bertanggung jawab menempatkan karyawan pada pekerjaan yang tepat, menyediakan pelatihan, menyediakan metode dan alat kerja yang layak, serta menetapkan insentif yang wajar (Heizer, Render dan Munson, 2017). Selanjutnya, Henry Ford dan Charles Sorensen pada tahun 1913 memadukan konsep komponen standar dengan lini perakitan bergerak, ketika pekerja berdiri di tempat dan material yang bergerak. Kontribusi penting lain datang dari Walter Shewhart yang meletakkan dasar pengendalian kualitas statistik, serta W. Edwards Deming yang menekankan tanggung jawab manajemen memperbaiki lingkungan dan proses kerja agar kualitas meningkat.</p>
<p>Heizer, Render dan Munson (2017) merangkum perjalanan disiplin ini ke dalam beberapa era. Era fokus biaya mencakup konsep awal pembagian kerja dan standardisasi, era manajemen ilmiah, serta era produksi massal dengan lini perakitan dan kuantitas pesanan ekonomis. Era fokus kualitas ditandai produksi ramping dengan <em>just-in-time</em>, manajemen kualitas total dan pemberdayaan karyawan; era kustomisasi massal didorong internet, perencanaan sumber daya perusahaan dan produksi berdasarkan pesanan; sedangkan era globalisasi ditandai rantai pasok global, komunikasi instan, logistik, etika tenaga kerja global dan keberlanjutan. Kemajuan disiplin ini juga ditopang kontribusi teknik industri, statistika, ekonomi, ilmu fisika dan teknologi informasi. Dengan memahami akar historis tersebut, mahasiswa dapat menilai bahwa praktik operasi terbaik masa kini merupakan akumulasi inovasi lintas generasi.</p>`
    },
    {
      no: "1.8",
      title: "Tantangan Kontemporer, Etika dan Keberlanjutan",
      body: `<p>Manajer operasi masa kini bekerja dalam lingkungan yang dinamis akibat berbagai kekuatan perubahan. Heizer, Render dan Munson (2017) mengidentifikasi enam tantangan utama sebagai berikut: globalisasi, yaitu penurunan biaya komunikasi dan transportasi yang menjadikan pasar dan sumber daya bersifat global; kemitraan rantai pasok, karena siklus hidup produk yang pendek menuntut kolaborasi erat dengan pemasok yang memiliki keahlian unik; keberlanjutan (<em>sustainability</em>), yaitu perancangan produk dan proses yang ramah lingkungan serta dapat didaur ulang; pengembangan produk yang cepat sebagai respons atas siklus hidup produk yang kian pendek; kustomisasi massal (<em>mass customization</em>), yaitu kemampuan menghasilkan produk sesuai keinginan individual kapan pun dan di mana pun dibutuhkan; serta operasi ramping (<em>lean operations</em>), yaitu model manajemen yang memuaskan pelanggan, menghormati karyawan dan menghilangkan pemborosan.</p>
<p>Selain tantangan tersebut, sistem operasi berfungsi di tengah beragam pemangku kepentingan (<em>stakeholders</em>) yang meliputi pelanggan, distributor, pemasok, pemilik, kreditur, karyawan dan masyarakat, yang kepentingannya sering saling bertentangan (Heizer, Render dan Munson, 2017). Manajer operasi ditantang mengembangkan produk yang aman, berkualitas dan ramah lingkungan, melatih serta memotivasi karyawan dalam lingkungan kerja yang selamat, dan menghormati komitmen kepada pemangku kepentingan. Dalam konteks Indonesia, tuntutan tersebut tampak pada industri minyak kelapa sawit yang diwajibkan memenuhi sertifikasi keberlanjutan agar diterima pasar ekspor, serta pada industri tekstil yang dituntut mengelola limbah produksinya. Dengan demikian, keputusan operasi tidak dapat dinilai semata dari efisiensi biaya, melainkan juga dari dampak etis, sosial dan lingkungannya.</p>`
    },
    {
      no: "1.9",
      title: "Transformasi Digital dan Peran Teknologi Informasi dalam Operasi",
      body: `<h5>1.9.1 Ekonomi On-Demand dan Ekonomi Berbagi</h5>
<p>Perkembangan teknologi digital telah melahirkan model bisnis baru yang mengubah cara operasi dijalankan. Model bisnis secara sederhana didefinisikan sebagai cara perusahaan menghasilkan pendapatan dan laba. Menurut Turban, Pollard dan Wood (2021), ekonomi <em>on-demand</em> adalah aktivitas ekonomi yang diciptakan perusahaan teknologi untuk memenuhi permintaan konsumen melalui penyediaan produk dan jasa secara seketika, sedangkan ekonomi berbagi (<em>sharing economy</em>) adalah sistem ekonomi ketika barang atau jasa dibagikan antarindividu, baik gratis maupun berbayar, melalui platform daring. Uber mendisrupsi industri taksi dengan mempertemukan pengemudi dan penumpang melalui aplikasi berbasis lokasi, sedangkan Airbnb mendisrupsi industri perhotelan dengan memungkinkan siapa pun menyewakan ruang miliknya kepada tamu di seluruh dunia (Turban, Pollard dan Wood, 2021). Turban, Pollard dan Wood (2021) mengelompokkan model bisnis digital disruptif ke dalam empat tipe, yaitu model akses atas kepemilikan seperti Airbnb dan Zipcar, model pengalaman seperti Tesla dan Apple, model <em>on-demand</em> seperti Uber dan TaskRabbit, serta model ekosistem seperti Apple dan Google.</p>
<p>Fenomena serupa berkembang pesat di Indonesia melalui Gojek dan Grab pada layanan transportasi dan pengantaran <em>on-demand</em>, Tokopedia pada perdagangan elektronik, serta Traveloka pada layanan perjalanan. Agar mampu menopang model bisnis semacam itu, teknologi informasi perusahaan harus diarahkan pada enam sasaran bisnis, yaitu pengembangan produk, integrasi pemangku kepentingan, perbaikan proses, efisiensi biaya, keunggulan bersaing dan globalisasi (Turban, Pollard dan Wood, 2021). Implikasi manajerialnya, kemampuan operasi perusahaan masa kini sangat ditentukan oleh kemampuan sistem teknologi informasi dan manajemen datanya, sehingga keputusan investasi teknologi merupakan bagian tidak terpisahkan dari strategi operasi.</p>
<h5>1.9.2 Perbaikan Proses Bisnis dan Business Process Reengineering</h5>
<p>Menurut Turban, Pollard dan Wood (2021), proses bisnis adalah serangkaian langkah yang digunakan organisasi untuk mengoordinasikan dan mengatur tugas agar pekerjaan terselesaikan di dalam maupun lintas fungsi bisnis. Setiap proses bisnis memiliki tiga komponen, yaitu masukan berupa material, data dan keahlian; aktivitas yang mentransformasikan masukan; serta keluaran (<em>deliverables</em>) berupa produk, jasa, atau rencana. Proses dapat bersifat formal yang terdokumentasi dalam prosedur operasi standar, maupun informal yang pengetahuannya masih melekat pada individu. Karena seluruh kinerja perusahaan merupakan hasil dari proses-prosesnya, proses yang cacat atau usang akan memboroskan sumber daya, menaikkan biaya, menimbulkan keterlambatan dan mengecewakan pelanggan; kegagalan pemenuhan pesanan sering kali bersumber dari proses yang keliru, bukan dari ketidakmampuan karyawan (Turban, Pollard dan Wood, 2021).</p>
<p>Perbaikan proses dapat dilakukan secara inkremental maupun radikal. Pendekatan radikal dikenal sebagai rekayasa ulang proses bisnis (<em>business process reengineering</em>) yang didefinisikan sebagai perancangan ulang secara mendasar proses bisnis inti untuk mencapai perbaikan dramatis dalam produktivitas, waktu siklus (<em>cycle time</em>) dan kualitas, dengan semboyan "Don't automate, obliterate" (Hammer dan Champy dalam Turban, Pollard dan Wood, 2021). Rekayasa ulang berlangsung dalam delapan tahap, mulai dari penetapan visi dan tujuan, pemahaman proses berjalan, identifikasi proses yang didesain ulang, identifikasi tuas perubahan, implementasi, operasionalisasi, evaluasi, sampai perbaikan berkelanjutan, dan penerapannya dibantu perangkat lunak manajemen proses bisnis. Namun, perbaikan proses yang keliru arah dapat berbalik merugikan, sebagaimana pengalaman Dell yang memangkas durasi panggilan dukungan teknis sehingga kualitas layanan justru merosot dan pelanggan harus menelepon berulang kali (Turban, Pollard dan Wood, 2021). Contoh keberhasilan di Indonesia tampak pada bank digital yang merekayasa ulang proses pembukaan rekening dari hitungan hari menjadi hitungan menit melalui verifikasi identitas elektronik sehingga biaya akuisisi nasabah turun drastis.</p>
<h5>1.9.3 SMAC dan Megatren Teknologi</h5>
<p>Turban, Pollard dan Wood (2021) menjelaskan bahwa dunia bisnis kini berada pada era komputasi <em>social-mobile-analytics-cloud</em> (SMAC), yaitu konvergensi empat teknologi yang membentuk infrastruktur teknis bisnis digital: hampir semua orang terhubung melalui media sosial, bergerak melalui perangkat seluler, memperoleh wawasan melalui analitik, serta mengakses produk dan jasa setiap saat melalui komputasi awan. Di atas fondasi tersebut bekerja sejumlah megatren teknologi yang menggerakkan transformasi digital, yaitu konektivitas, mahadata (<em>big data</em>) dan analitik data, kecerdasan buatan dan robotika, digitisasi, serta teknologi mesin-ke-mesin dan <em>Internet of Things</em>. Digitisasi proses yang padat informasi dilaporkan mampu memangkas biaya sampai 90 persen dan mempercepat waktu proses berlipat ganda, misalnya proses aplikasi kredit pemilikan rumah yang persetujuan awalnya dipangkas dari beberapa hari menjadi sekitar satu menit (Turban, Pollard dan Wood, 2021). Sensor yang tertanam pada produk memungkinkan perusahaan memantau penggunaan dari jarak jauh dan mengembangkan model bisnis baru, seperti premi asuransi kendaraan yang dihitung dari perilaku berkendara aktual.</p>
<p>Pandemi COVID-19 terbukti mempercepat transformasi digital pada hampir semua sektor karena perusahaan dipaksa memindahkan interaksi pelanggan, karyawan dan mitra ke kanal digital dalam waktu singkat (Turban, Pollard dan Wood, 2021). Bagi manajemen operasi, perkembangan tersebut menegaskan bahwa teknologi bukan lagi sekadar pusat biaya, melainkan pembeda daya saing yang menentukan konfigurasi rantai nilai. Oleh karena itu, manajer operasi dituntut menjadi pengguna teknologi informasi yang terinformasi (<em>informed user</em>) agar mampu memilih dan memanfaatkan teknologi yang tepat untuk memperbaiki proses, produktivitas dan penciptaan nilai bagi pelanggan.</p>`
    },
    {
      no: "1.10",
      title: "Rangkuman",
      body: `<p>Manajemen operasi adalah serangkaian aktivitas yang menciptakan nilai dalam bentuk barang dan jasa melalui transformasi masukan menjadi keluaran, dan merupakan satu dari tiga fungsi dasar organisasi bersama pemasaran serta keuangan dan akuntansi. Seluruh operasi dapat dianalisis dengan model input-transformasi-output, sedangkan perbedaan antarproses dijelaskan oleh empat dimensi 4V, yaitu volume, variasi, variabilitas permintaan dan tingkat keterlihatan. Nilai bagi pelanggan diciptakan melalui rantai nilai bisnis yang melibatkan jaringan rantai pasok lintas organisasi, sehingga persaingan modern pada hakikatnya berlangsung antar rantai pasok, bukan sekadar antarperusahaan. Kerangka sepuluh keputusan strategis manajemen operasi memberikan peta lengkap wilayah keputusan yang harus dikelola manajer operasi secara konsisten dengan strategi bersaing.</p>
<p>Produktivitas, yaitu rasio keluaran terhadap masukan, merupakan ukuran utama keberhasilan pengelolaan operasi sekaligus penentu standar hidup masyarakat. Produktivitas dapat diukur secara faktor tunggal maupun multifaktor, dengan tenaga kerja, modal dan manajemen sebagai tiga variabel penentu peningkatannya. Pengukuran produktivitas menghadapi kendala terutama pada sektor jasa yang padat karya dan sulit distandardisasi, meskipun perbaikan tetap dapat dicapai melalui perhatian manajerial terhadap detail proses. Di samping itu, manajer operasi kontemporer menghadapi tantangan globalisasi, kemitraan rantai pasok, keberlanjutan, pengembangan produk cepat, kustomisasi massal dan operasi ramping, serta tuntutan etika dan tanggung jawab sosial terhadap pemangku kepentingan.</p>
<p>Akhirnya, teknologi informasi telah menjadi penggerak utama transformasi operasi melalui ekonomi <em>on-demand</em> dan ekonomi berbagi, model bisnis digital disruptif, rekayasa ulang proses bisnis, serta megatren SMAC, mahadata, kecerdasan buatan dan <em>Internet of Things</em>. Perusahaan yang mampu memadukan disiplin manajemen operasi klasik dengan pemanfaatan teknologi digital secara cerdas akan memperoleh keunggulan bersaing yang berkelanjutan. Dengan demikian, sesi ini meletakkan fondasi konseptual bagi pembahasan sesi-sesi berikutnya mengenai strategi operasi, desain proses, kualitas, rantai pasok dan teknologi manajemen operasi.</p>`
    },
    {
      no: "1.11",
      title: "Daftar Pustaka",
      body: `<p>Heizer, J., Render, B. dan Munson, C. (2017). <em>Operations Management: Sustainability and Supply Chain Management</em>. Edisi 12. Pearson Education.</p>
<p>Slack, N., Brandon-Jones, A. dan Burgess, N. (2022). <em>Operations Management</em>. Edisi 10. Pearson Education.</p>
<p>Turban, E., Pollard, C. dan Wood, G. (2021). <em>Information Technology for Management: Driving Digital Transformation to Increase Local and Global Performance, Growth and Sustainability</em>. Edisi 12. John Wiley and Sons.</p>`
    }
  ]
};
