window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.otm = window.MBA_BOOK.otm || {};
window.MBA_BOOK.otm[10] = {
  bab: 10,
  judul: "BAB 10 MANAJEMEN KUALITAS (QUALITY MANAGEMENT)",
  sumber: "Heizer, Render dan Munson (2017), Operations Management 12e; Turban, Pollard dan Wood (2021), IT for Management 12e; Slack, Brandon-Jones dan Burgess (2022), Operations Management 10e",
  lo: [
    "LO1 Mendefinisikan kualitas dan Total Quality Management (TQM) serta menjelaskan keterkaitan kualitas dengan strategi dan profitabilitas perusahaan",
    "LO2 Mendeskripsikan standar kualitas internasional ISO 9000 serta penghargaan mutu seperti Malcolm Baldrige National Quality Award dan Deming Prize",
    "LO3 Menguraikan empat kategori biaya kualitas (cost of quality) serta kontribusi tokoh utama manajemen mutu",
    "LO4 Menjelaskan tujuh konsep TQM, termasuk perbaikan berkesinambungan, Six Sigma, pemberdayaan karyawan, benchmarking, just-in-time, dan konsep Taguchi",
    "LO5 Menggunakan tujuh alat TQM untuk mengidentifikasi dan menganalisis masalah kualitas",
    "LO6 Menjelaskan peran inspeksi, pengendalian proses statistis (SPC) secara ringkas, kapabilitas proses, serta penerapan TQM pada sektor jasa"
  ],
  sections: [
    {
      no: "10.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi kesepuluh mata kuliah Operations and Technology Management membahas manajemen kualitas sebagai salah satu dari sepuluh keputusan strategis manajemen operasi. Kualitas bukan sekadar persoalan teknis di lantai produksi, melainkan penentu reputasi, biaya, dan daya saing perusahaan secara keseluruhan. Pembahasan dimulai dari definisi kualitas dan keterkaitannya dengan strategi, dilanjutkan dengan standar internasional, biaya kualitas, tujuh konsep <em>Total Quality Management</em> (TQM), tujuh alat mutu, peran inspeksi, pengendalian proses statistis secara ringkas, dan diakhiri dengan penerapan TQM pada sektor jasa. Setelah mengikuti sesi ini, mahasiswa diharapkan mampu mencapai hal-hal sebagai berikut:</p>
<p>Capaian pembelajaran sesi ini adalah sebagai berikut: <strong>LO1</strong> mendefinisikan kualitas dan TQM serta keterkaitannya dengan strategi dan profitabilitas; <strong>LO2</strong> mendeskripsikan standar ISO 9000 dan penghargaan mutu; <strong>LO3</strong> menguraikan empat kategori biaya kualitas serta kontribusi tokoh utama manajemen mutu; <strong>LO4</strong> menjelaskan tujuh konsep TQM; <strong>LO5</strong> menggunakan tujuh alat TQM untuk mengidentifikasi masalah kualitas; dan <strong>LO6</strong> menjelaskan peran inspeksi, dasar pengendalian proses statistis dan kapabilitas proses, serta penerapan TQM pada jasa.</p>`
    },
    {
      no: "10.2",
      title: "Kualitas dan Strategi Operasi",
      body: `<p>Manajemen kualitas yang baik mendukung ketiga strategi generik operasi, yaitu diferensiasi, biaya rendah, dan respons cepat. Bose membedakan diri melalui kualitas suaranya, Nucor menghasilkan baja bermutu dengan biaya rendah, dan Dell merespons pesanan dengan cepat karena sistem mutunya menekan pengerjaan ulang (Heizer, Render dan Munson, 2017). Dengan demikian, kualitas bukan pilihan yang berdiri sendiri, melainkan prasyarat bagi keberhasilan strategi operasi mana pun.</p>
<h5>10.2.1 Definisi Kualitas</h5>
<p>Kualitas dapat didefinisikan dari beberapa sudut pandang. American Society for Quality, sebagaimana dikutip Heizer, Render dan Munson (2017), mendefinisikan kualitas sebagai keseluruhan fitur dan karakteristik produk atau jasa yang berkaitan dengan kemampuannya memenuhi kebutuhan yang dinyatakan maupun yang tersirat. Menurut Slack, Brandon-Jones dan Burgess (2022), kualitas adalah kesesuaian yang konsisten terhadap ekspektasi pelanggan (<em>consistent conformance to customers' expectations</em>). Dari kedua definisi tersebut dapat disimpulkan bahwa kualitas selalu berpangkal pada pelanggan, baik dalam bentuk kebutuhan yang dinyatakan secara eksplisit maupun harapan yang tidak diucapkan.</p>
<p>Selain definisi umum tersebut, terdapat tiga kategori pendekatan terhadap kualitas. Pendekatan berbasis pengguna (<em>user based</em>) memandang kualitas sebagai sesuatu yang berada di mata pelanggan, sehingga kualitas yang lebih tinggi berarti kinerja dan fitur yang lebih baik. Pendekatan berbasis manufaktur (<em>manufacturing based</em>) memandang kualitas sebagai kesesuaian terhadap standar dan mengerjakan dengan benar sejak awal. Pendekatan berbasis produk (<em>product based</em>) memandang kualitas sebagai variabel yang presisi dan terukur, misalnya kadar lemak susu pada es krim. Ketiga pendekatan tersebut saling melengkapi: karakteristik mutu diidentifikasi melalui riset pelanggan, diterjemahkan menjadi atribut produk, kemudian proses produksi diorganisasikan agar produk sesuai spesifikasi; pengabaian salah satu tahap akan menggagalkan mutu produk.</p>
<h5>10.2.2 Kualitas dan Profitabilitas</h5>
<p>Perbaikan kualitas meningkatkan profitabilitas melalui dua jalur. Jalur pertama adalah kenaikan penjualan (<em>sales gains</em>) yang terjadi karena respons yang lebih cepat, keleluasaan penetapan harga, dan reputasi produk yang membaik. Jalur kedua adalah penurunan biaya (<em>reduced costs</em>) yang terjadi karena produktivitas meningkat serta biaya pengerjaan ulang (<em>rework</em>), sisa produksi (<em>scrap</em>), dan garansi menurun (Heizer, Render dan Munson, 2017). Sebuah studi yang dikutip dalam buku tersebut menemukan bahwa perusahaan dengan kualitas tertinggi mencapai produktivitas hingga lima kali lipat dibandingkan perusahaan dengan kualitas terendah. Oleh karena itu, apabila biaya jangka panjang dan potensi kenaikan penjualan diperhitungkan, biaya total justru dapat mencapai titik minimum ketika seluruh keluaran bebas cacat.</p>
<h5>10.2.3 Implikasi dan Etika Kualitas</h5>
<p>Di luar aspek operasional, kualitas memiliki tiga implikasi penting. Pertama, reputasi perusahaan (<em>company reputation</em>) akan mengikuti tingkat mutu yang dihasilkan, baik ataupun buruk, dan promosi tidak dapat menggantikan produk yang bermutu. Kedua, tanggung jawab hukum atas produk (<em>product liability</em>) menuntut perusahaan menanggung kerugian yang timbul dari produk cacat, sebagaimana makanan tercemar atau komponen kendaraan yang gagal berfungsi dapat berujung pada tuntutan hukum yang mahal. Ketiga, implikasi global menuntut produk memenuhi ekspektasi mutu, desain, dan harga internasional; penolakan produk perikanan ekspor Indonesia yang tidak memenuhi standar keamanan pangan negara tujuan, misalnya, merugikan perusahaan sekaligus citra industri nasional.</p>
<p>Dari sisi etika, manajer operasi berkewajiban menghasilkan produk yang sehat, aman, dan bermutu. Apabila perusahaan meyakini produknya bermasalah, tindakan yang bertanggung jawab harus diambil, termasuk penarikan produk secara global sebagaimana dilakukan Johnson &amp; Johnson terhadap Tylenol. Manajemen juga perlu menimbang kepentingan seluruh pemangku kepentingan dan menetapkan nilai-nilai inti sebagai pedoman perilaku organisasi.</p>`
    },
    {
      no: "10.3",
      title: "Standar Kualitas Internasional dan Penghargaan Mutu",
      body: `<p>Globalisasi rantai pasokan mendorong dunia usaha bersepakat pada satu standar mutu internasional, yaitu ISO 9000 yang dikembangkan oleh International Organization for Standardization. ISO 9000 merupakan satu-satunya standar kualitas yang memperoleh pengakuan internasional dan berfokus pada peningkatan keberhasilan organisasi melalui delapan prinsip manajemen mutu, yaitu kepemimpinan manajemen puncak, kepuasan pelanggan, perbaikan berkelanjutan, keterlibatan orang, analisis proses, pengambilan keputusan berbasis data, pendekatan sistem terhadap manajemen, dan hubungan pemasok yang saling menguntungkan (Heizer, Render dan Munson, 2017). Standar ini mendorong organisasi menyusun prosedur manajemen mutu, dokumentasi yang rinci, instruksi kerja, dan pencatatan yang tertib. Organisasi yang tersertifikasi wajib diaudit ulang setiap tiga tahun, dan versi mutakhir ISO 9001:2015 memberikan penekanan lebih besar pada pemikiran berbasis risiko (<em>risk based thinking</em>) untuk mencegah hasil yang tidak diinginkan.</p>
<p>Lebih dari satu juta sertifikasi ISO telah diberikan kepada perusahaan di lebih dari dua ratus negara, sehingga sertifikasi menjadi prasyarat praktis untuk berbisnis secara global. Di Indonesia, sertifikasi ISO 9001 telah menjadi standar umum bagi badan usaha milik negara maupun swasta, misalnya PLN, Pertamina, dan produsen komponen otomotif pemasok jaringan produksi Toyota dan Honda. Selain itu, Standar Nasional Indonesia (SNI) berperan serupa pada tingkat nasional dan bersifat wajib untuk produk tertentu seperti helm dan air minum dalam kemasan. Dengan demikian, kepatuhan terhadap standar mutu merupakan tiket masuk pasar, bukan sekadar sarana promosi.</p>
<p>Di samping standar, terdapat penghargaan mutu yang mendorong perusahaan berlomba mencapai keunggulan. Amerika Serikat menyelenggarakan Malcolm Baldrige National Quality Award yang dinamai menurut mantan Menteri Perdagangan Malcolm Baldrige, dengan pemenang antara lain Motorola, FedEx, dan Ritz-Carlton. Jepang memiliki Deming Prize yang dinamai menurut Dr. W. Edwards Deming, seorang ahli statistik Amerika yang berjasa membangun kembali industri Jepang pasca Perang Dunia II. Penghargaan sejenis di Indonesia adalah SNI Award. Bagi manajer, kriteria penghargaan tersebut bermanfaat sebagai kerangka penilaian mandiri (<em>self appraisal</em>) atas kematangan sistem manajemen mutu organisasi.</p>`
    },
    {
      no: "10.4",
      title: "Biaya Kualitas dan Tokoh Utama Manajemen Mutu",
      body: `<p>Keputusan investasi dalam mutu memerlukan pemahaman mengenai biaya kualitas. Biaya kualitas (<em>cost of quality</em>, COQ) adalah biaya akibat mengerjakan sesuatu secara salah, yaitu harga dari ketidaksesuaian (Heizer, Render dan Munson, 2017). Konsep ini membantu manajer membandingkan biaya pencegahan dengan biaya kegagalan sehingga keputusan mutu dapat diambil atas dasar ekonomi, bukan sekadar slogan.</p>
<h5>10.4.1 Empat Kategori Biaya Kualitas</h5>
<p>Terdapat empat kategori biaya yang berkaitan dengan kualitas, yaitu biaya pencegahan (<em>prevention costs</em>) untuk mengurangi potensi cacat, biaya penilaian (<em>appraisal costs</em>) untuk mengevaluasi produk dan proses, biaya kegagalan internal (<em>internal failure costs</em>) akibat cacat yang ditemukan sebelum produk diserahkan, dan biaya kegagalan eksternal (<em>external failure costs</em>) setelah produk cacat sampai ke pelanggan. Tiga kategori pertama relatif dapat diestimasi, sedangkan biaya kegagalan eksternal sangat sulit dikuantifikasi sehingga biaya mutu yang buruk cenderung diremehkan. Tabel 10.1 menyajikan sintesis keempat kategori tersebut.</p>
<table class="bk-table"><caption>Tabel 10.1 Empat Kategori Biaya Kualitas</caption>
<thead><tr><th>Kategori</th><th>Sifat</th><th>Contoh</th><th>Implikasi Manajerial</th></tr></thead>
<tbody>
<tr><td>Biaya pencegahan</td><td>Investasi sebelum cacat terjadi</td><td>Pelatihan karyawan, desain proses, program mutu</td><td>Meningkatkan pencegahan menurunkan total biaya jangka panjang</td></tr>
<tr><td>Biaya penilaian</td><td>Biaya evaluasi dan pengukuran</td><td>Pengujian, kalibrasi, inspeksi, audit mutu</td><td>Diperlukan, namun tidak menambah nilai produk</td></tr>
<tr><td>Biaya kegagalan internal</td><td>Cacat ditemukan sebelum pengiriman</td><td>Pengerjaan ulang, sisa produksi, waktu henti</td><td>Dapat diestimasi dan dijadikan target perbaikan proses</td></tr>
<tr><td>Biaya kegagalan eksternal</td><td>Cacat ditemukan pelanggan</td><td>Retur, garansi, tuntutan hukum, hilangnya loyalitas</td><td>Paling mahal dan paling sulit dikuantifikasi</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017)</td></tr></tfoot></table>
<p>Philip Crosby berargumen bahwa dalam pertukaran tradisional antara biaya perbaikan mutu dan biaya mutu yang buruk, biaya mutu yang buruk selalu ditaksir terlalu rendah. Dalam bukunya ia menyatakan "quality is free" (Crosby, 1979, dalam Heizer, Render dan Munson, 2017), karena yang sesungguhnya mahal adalah segala tindakan akibat tidak mengerjakan pekerjaan dengan benar sejak awal. Kasus penarikan 3,1 juta mesin pencuci piring oleh GE, yang biaya perbaikannya melebihi nilai seluruh mesin tersebut, menegaskan argumen ini.</p>
<h5>10.4.2 Tokoh Utama Manajemen Mutu</h5>
<p>Pemikiran manajemen mutu modern dibentuk oleh sejumlah tokoh. Deming menekankan tanggung jawab manajemen membangun sistem yang baik karena karyawan tidak mungkin menghasilkan mutu melebihi kapabilitas proses yang disediakan, dan ia merumuskan empat belas butir perbaikan mutu. Juran mendefinisikan kualitas sebagai kecocokan penggunaan (<em>fitness for use</em>), Feigenbaum memandang mutu sebagai bidang total yang mengintegrasikan seluruh proses perusahaan, dan Crosby memopulerkan konsep tanpa cacat (<em>zero defects</em>). Tabel 10.2 merangkum kontribusi keempat tokoh tersebut.</p>
<table class="bk-table"><caption>Tabel 10.2 Kontribusi Tokoh Utama Manajemen Mutu</caption>
<thead><tr><th>Tokoh</th><th>Gagasan Inti</th><th>Warisan Utama</th></tr></thead>
<tbody>
<tr><td>W. Edwards Deming</td><td>Manajemen bertanggung jawab atas sistem; variasi dikendalikan secara statistis</td><td>14 butir Deming, siklus PDCA, Deming Prize</td></tr>
<tr><td>Joseph M. Juran</td><td>Kualitas sebagai kecocokan penggunaan yang berfokus pada pelanggan</td><td>Trilogi mutu dan popularisasi prinsip Pareto</td></tr>
<tr><td>Armand Feigenbaum</td><td>Mutu sebagai tanggung jawab terintegrasi seluruh fungsi perusahaan</td><td>Total Quality Control dan kerja tim lintas fungsi</td></tr>
<tr><td>Philip B. Crosby</td><td>Biaya mutu buruk selalu diremehkan; kerjakan benar sejak awal</td><td>Konsep zero defects dan Quality Is Free</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017)</td></tr></tfoot></table>`
    },
    {
      no: "10.5",
      title: "Total Quality Management dan Tujuh Konsepnya",
      body: `<p><em>Total Quality Management</em> (TQM) adalah pengelolaan seluruh organisasi agar unggul dalam semua aspek produk dan jasa yang penting bagi pelanggan (Heizer, Render dan Munson, 2017). Penekanan kata total menunjukkan bahwa mutu mencakup keseluruhan rantai dari pemasok hingga pelanggan. Keberhasilan TQM mengalir dari praktik organisasi (kepemimpinan, misi, prosedur, pelatihan), menuju prinsip mutu, menuju pemenuhan karyawan, dan berujung pada kepuasan pelanggan yang memenangkan pesanan. Dari empat belas butir Deming dikembangkan tujuh konsep program TQM yang efektif, yaitu perbaikan berkesinambungan, Six Sigma, pemberdayaan karyawan, <em>benchmarking</em>, <em>just-in-time</em>, konsep Taguchi, dan penguasaan alat TQM.</p>
<h5>10.5.1 Perbaikan Berkesinambungan</h5>
<p>Perbaikan berkesinambungan (<em>continuous improvement</em>) mencakup manusia, peralatan, pemasok, bahan, dan prosedur dengan keyakinan bahwa setiap aspek operasi dapat diperbaiki. Walter Shewhart mengembangkan model lingkaran PDCA (<em>plan, do, check, act</em>) yang kemudian disebarluaskan Deming di Jepang. Tahap <em>plan</em> mengidentifikasi masalah dan menyusun rencana, <em>do</em> menguji rencana, <em>check</em> memeriksa hasilnya, dan <em>act</em> mengimplementasikan serta mendokumentasikan perbaikan, kemudian siklus berulang. Orang Jepang menyebut proses perbaikan tanpa akhir ini <em>kaizen</em>. Implikasinya, manajer operasi harus membangun budaya yang menjadikan penyempurnaan standar sebagai kegiatan rutin, bukan proyek sesaat.</p>
<h5>10.5.2 Six Sigma</h5>
<p>Six Sigma yang dipopulerkan Motorola, Honeywell, dan GE memiliki dua makna. Secara statistis, Six Sigma menggambarkan proses dengan kapabilitas sangat tinggi, yaitu akurasi 99,9997 persen atau hanya 3,4 cacat per satu juta kesempatan, jauh lebih ketat daripada program tiga sigma yang menghasilkan 2.700 cacat per juta. Secara program, Six Sigma adalah sistem menyeluruh berupa strategi karena berfokus pada kepuasan total pelanggan, disiplin karena mengikuti model perbaikan formal DMAIC, dan seperangkat alat mutu (Heizer, Render dan Munson, 2017). Model DMAIC terdiri atas lima langkah, yaitu <em>define</em> (menetapkan tujuan, lingkup, dan keluaran proyek berdasarkan definisi mutu pelanggan), <em>measure</em> (mengukur proses dan mengumpulkan data), <em>analyze</em> (menganalisis data), <em>improve</em> (memodifikasi atau merancang ulang proses), dan <em>control</em> (menjaga tingkat kinerja proses baru). Implementasinya menuntut komitmen besar manajemen puncak serta tenaga ahli bersertifikat seperti <em>green belt</em> dan <em>black belt</em>, dan proyeknya harus terkait langsung dengan arah strategis perusahaan.</p>
<h5>10.5.3 Pemberdayaan Karyawan dan Gugus Kendali Mutu</h5>
<p>Pemberdayaan karyawan (<em>employee empowerment</em>) berarti melibatkan karyawan dalam setiap langkah proses produksi dengan memperluas pekerjaan sehingga tanggung jawab dan wewenang berpindah ke tingkat serendah mungkin dalam organisasi. Riset yang dikutip Heizer, Render dan Munson (2017) menunjukkan bahwa sekitar 85 persen masalah kualitas bersumber pada bahan dan proses, bukan pada kinerja karyawan, sehingga ketika ketidaksesuaian terjadi, karyawan jarang menjadi penyebabnya. Teknik pemberdayaan mencakup jaringan komunikasi yang melibatkan karyawan, penyelia yang terbuka dan suportif, pemindahan tanggung jawab kepada karyawan produksi, organisasi bermoral tinggi, serta struktur formal seperti tim dan gugus kendali mutu. Gugus kendali mutu (<em>quality circle</em>) adalah kelompok karyawan yang bertemu berkala bersama fasilitator untuk memecahkan masalah di area kerja mereka; di Indonesia praktik ini melembaga melalui konvensi Gugus Kendali Mutu yang rutin diikuti perusahaan manufaktur seperti kelompok Astra.</p>
<h5>10.5.4 Benchmarking</h5>
<p><em>Benchmarking</em> adalah pemilihan standar kinerja terbaik yang telah terbukti sebagai pembanding bagi proses atau aktivitas organisasi. Lima langkah pengembangannya adalah menentukan apa yang dibandingkan, membentuk tim, mengidentifikasi mitra pembanding, mengumpulkan serta menganalisis informasi, dan mengambil tindakan untuk menyamai atau melampaui tolok ukur. Ukuran kinerja yang lazim meliputi persentase cacat, biaya per unit, waktu proses, waktu respons layanan, dan tingkat kepuasan pelanggan. Mitra pembanding tidak harus berasal dari industri yang sama; sebuah rumah sakit anak di Inggris mempelajari pergantian ban tim balap Ferrari untuk memperbaiki serah terima pasien dari ruang operasi sehingga kesalahan turun lebih dari 40 persen (Heizer, Render dan Munson, 2017). Pada organisasi besar, <em>benchmarking</em> internal antarunit juga efektif karena datanya lebih mudah diakses.</p>
<h5>10.5.5 Just-in-Time</h5>
<p>Filosofi <em>just-in-time</em> (JIT) berkaitan dengan mutu melalui tiga cara. Pertama, JIT memangkas biaya mutu karena sisa produksi, pengerjaan ulang, dan kerusakan berkaitan langsung dengan persediaan yang ditahan, sementara persediaan yang rendah juga tidak menyembunyikan mutu yang buruk. Kedua, JIT memperbaiki mutu karena memperpendek <em>lead time</em> sehingga bukti kesalahan tetap segar dan berfungsi sebagai sistem peringatan dini. Ketiga, mutu yang baik memungkinkan persediaan lebih kecil sehingga JIT lebih mudah dijalankan. Dengan demikian, JIT dan mutu saling memperkuat.</p>
<h5>10.5.6 Konsep Taguchi</h5>
<p>Sebagian besar masalah kualitas berakar pada desain produk dan proses yang buruk. Genichi Taguchi menyumbangkan tiga konsep perbaikan, yaitu ketangguhan mutu, kualitas berorientasi target, dan fungsi kerugian mutu. Produk yang tangguh mutunya (<em>quality robust</em>) dapat diproduksi secara seragam meskipun kondisi manufaktur dan lingkungan tidak menguntungkan, karena Taguchi memilih menghilangkan pengaruh kondisi buruk dan bukan penyebabnya, yang sering kali lebih murah. Kualitas berorientasi target (<em>target oriented quality</em>) adalah filosofi perbaikan berkesinambungan untuk membawa produk tepat pada nilai target, bukan sekadar berada dalam batas spesifikasi; studi pabrik Sony menunjukkan konsumen lebih menyukai televisi buatan pabrik yang berorientasi target meskipun desain kedua pabrik sama. Fungsi kerugian mutu (<em>quality loss function</em>, QLF) mengestimasi seluruh biaya yang berkaitan dengan mutu buruk dan menunjukkan bahwa biaya tersebut meningkat secara kuadratik ketika keluaran menjauhi nilai target, dengan bentuk umum L = D<sup>2</sup>C, di mana L adalah kerugian, D adalah deviasi dari nilai target, dan C adalah biaya deviasi pada batas spesifikasi. Bagi manajer, QLF menjadi alat untuk menilai apakah tambahan biaya proses yang lebih presisi sepadan dengan nilai produk yang dihasilkan.</p>`
    },
    {
      no: "10.6",
      title: "Tujuh Alat TQM",
      body: `<p>Agar TQM menjadi upaya berkelanjutan, seluruh anggota organisasi perlu dilatih menggunakan tujuh alat mutu yang dikelompokkan menurut fungsinya: alat pembangkit gagasan (lembar periksa, diagram sebar, diagram sebab akibat), alat pengorganisasi data (diagram Pareto, diagram alir), dan alat pengidentifikasi masalah (histogram, peta kendali proses statistis). Tabel 10.3 merangkum fungsi masing-masing alat.</p>
<table class="bk-table"><caption>Tabel 10.3 Tujuh Alat TQM dan Kegunaannya</caption>
<thead><tr><th>Alat</th><th>Deskripsi</th><th>Kegunaan Utama</th></tr></thead>
<tbody>
<tr><td>Lembar periksa (<em>check sheet</em>)</td><td>Formulir terorganisasi untuk mencatat data</td><td>Menemukan pola fakta saat data dikumpulkan</td></tr>
<tr><td>Diagram sebar (<em>scatter diagram</em>)</td><td>Grafik hubungan dua variabel</td><td>Menguji keterkaitan dua ukuran, misalnya produktivitas dan absensi</td></tr>
<tr><td>Diagram sebab akibat (Ishikawa)</td><td>Skema tulang ikan penyebab masalah</td><td>Mengidentifikasi lokasi masalah mutu secara sistematis</td></tr>
<tr><td>Diagram Pareto</td><td>Grafik masalah berurutan menurut frekuensi</td><td>Memfokuskan perbaikan pada sedikit penyebab yang kritis</td></tr>
<tr><td>Diagram alir (<em>flowchart</em>)</td><td>Diagram blok tahapan proses</td><td>Memahami proses dan menemukan aktivitas tanpa nilai tambah</td></tr>
<tr><td>Histogram</td><td>Distribusi frekuensi suatu ukuran</td><td>Melihat sebaran, nilai yang paling sering, dan sumber variasi</td></tr>
<tr><td>Peta kendali (SPC <em>chart</em>)</td><td>Plot data proses terhadap waktu dengan batas kendali</td><td>Memantau stabilitas proses dan mendeteksi penyimpangan</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Heizer, Render dan Munson (2017)</td></tr></tfoot></table>
<p>Diagram sebab akibat, yang juga disebut diagram Ishikawa atau diagram tulang ikan, dimulai dari empat kategori penyebab yang dikenal sebagai 4M, yaitu material (bahan), <em>machinery</em> (mesin), <em>manpower</em> (tenaga kerja), dan <em>methods</em> (metode). Penyebab individual pada tiap kategori digali melalui curah pendapat dan digambarkan sebagai tulang-tulang cabang, sehingga titik inspeksi dan potensi masalah mutu tersorot secara sistematis. Diagram Pareto dilandasi temuan Vilfredo Pareto yang dipopulerkan Juran bahwa sekitar 80 persen masalah perusahaan bersumber dari hanya 20 persen penyebab. Contoh klasiknya adalah Hard Rock Hotel di Bali yang menganalisis 75 panggilan keluhan dan menemukan bahwa 72 persen keluhan berasal dari satu penyebab saja, yaitu layanan kamar, sehingga perbaikan satu penyebab tersebut menghilangkan mayoritas keluhan (Heizer, Render dan Munson, 2017). Dalam konteks Indonesia, tim mutu rumah sakit swasta dapat memakai pendekatan yang sama untuk mengurutkan keluhan pasien rawat jalan dan memusatkan perbaikan pada penyebab dengan frekuensi tertinggi, misalnya lama antrean farmasi.</p>
<p>Diagram alir bermanfaat untuk memahami proses sebelum memperbaikinya, sebagaimana rumah sakit Arnold Palmer memetakan sebelas langkah proses MRI untuk menemukan aktivitas yang dapat dihilangkan. Histogram menampilkan rentang nilai pengukuran beserta frekuensinya sehingga bentuk distribusi dapat dilihat secara visual. Adapun pengendalian proses statistis memantau standar, melakukan pengukuran, dan mengambil tindakan korektif selagi produk atau jasa sedang diproduksi, dengan peta kendali sebagai instrumen utamanya. Sistem informasi modern mempermudah penggunaan alat-alat ini karena data mutu terkumpul secara otomatis dari sensor produksi maupun kanal keluhan pelanggan, sehingga dasbor mutu menyajikan diagram Pareto dan peta kendali tanpa rekapitulasi manual (Turban, Pollard dan Wood, 2021). Oleh karena itu, investasi teknologi informasi dan program mutu sebaiknya dirancang sebagai satu kesatuan.</p>`
    },
    {
      no: "10.7",
      title: "Peran Inspeksi",
      body: `<p>Inspeksi adalah sarana untuk memastikan bahwa suatu operasi menghasilkan produk pada tingkat kualitas yang diharapkan, berupa pengukuran, pencicipan, penimbangan, atau pengujian produk untuk mendeteksi proses yang buruk sesegera mungkin. Namun, inspeksi tidak memperbaiki kekurangan sistem maupun cacat produk dan tidak menambah nilai; inspeksi hanya menemukan kekurangan dan mahal biayanya. Sebuah eksperimen yang dikutip Heizer, Render dan Munson (2017) menunjukkan bahwa inspektur hanya menemukan 68 dari 100 barang cacat pada pemeriksaan pertama, dan dua cacat terakhir tidak pernah ditemukan. Dari temuan tersebut dapat disimpulkan bahwa kualitas tidak dapat diinspeksikan ke dalam produk, sehingga proses yang baik, pemberdayaan karyawan, dan pengendalian di sumber merupakan solusi yang lebih tepat.</p>
<p>Keputusan kapan dan di mana inspeksi dilakukan bergantung pada jenis proses dan nilai tambah setiap tahap. Titik inspeksi yang lazim meliputi pabrik pemasok, penerimaan barang, sebelum proses yang mahal atau tidak dapat dibalik, selama proses produksi, saat produksi selesai, sebelum pengiriman, dan pada titik kontak pelanggan. Prinsip umumnya adalah mencegah cacat mengalir ke tahap berikutnya karena biaya kegagalan meningkat semakin jauh cacat berjalan dalam proses.</p>
<p>Bentuk inspeksi terbaik adalah inspeksi pada sumber (<em>source inspection</em>), yaitu pengendalian pada titik produksi atau pembelian di mana setiap karyawan memeriksa pekerjaannya sendiri dan memperlakukan tahap berikutnya sebagai pelanggan. Inspeksi semacam ini dibantu oleh <em>poka-yoke</em>, yaitu perangkat atau teknik anti kesalahan yang menjamin produksi unit yang baik setiap saat. Contohnya adalah nosel pompa solar yang tidak dapat masuk ke lubang tangki bensin dan sekop kentang goreng McDonald's yang otomatis menakar porsi yang tepat. Daftar periksa (<em>checklist</em>) merupakan jenis <em>poka-yoke</em> yang menjamin konsistensi dan kelengkapan tugas, sebagaimana daftar periksa pra penerbangan pilot; daftar periksa lima langkah pemasangan kateter yang dikembangkan Dr. Peter Pronovost terbukti menurunkan tingkat infeksi hingga mendekati nol di banyak rumah sakit. Dalam konteks Indonesia, <em>poka-yoke</em> mudah ditemukan pada lini perakitan sepeda motor berupa <em>jig</em> yang mencegah pemasangan komponen secara terbalik, serta pada layanan perbankan digital yang menolak transaksi apabila nomor rekening tujuan tidak valid.</p>
<p>Ketika inspeksi dilakukan, karakteristik mutu dapat diukur sebagai atribut atau variabel. Inspeksi atribut (<em>attribute inspection</em>) mengklasifikasikan barang sebagai baik atau cacat tanpa memperhatikan derajat kegagalannya, misalnya lampu menyala atau tidak. Inspeksi variabel (<em>variable inspection</em>) mengukur dimensi kontinu seperti berat, kecepatan, ukuran, atau kekuatan untuk menilai apakah barang berada dalam rentang yang dapat diterima. Pembedaan ini penting karena menentukan jenis peta kendali statistis yang digunakan, sebagaimana dibahas pada sub-bab berikutnya.</p>`
    },
    {
      no: "10.8",
      title: "Pengendalian Proses Statistis dan Kapabilitas Proses",
      body: `<p>Pengendalian proses statistis (<em>statistical process control</em>, SPC) adalah penerapan teknik statistik untuk memastikan proses memenuhi standar. Semua proses mengandung variabilitas. Walter Shewhart membedakan variasi alami (<em>natural variation</em>) yang melekat pada setiap proses dan membentuk pola distribusi yang stabil, dari variasi terusut (<em>assignable variation</em>) yang dapat dilacak ke penyebab spesifik seperti keausan mesin, peralatan yang tidak disetel, pekerja yang lelah, atau bahan baku yang berbeda (Heizer, Render dan Munson, 2017). Suatu proses dikatakan berada dalam kendali statistis apabila satu-satunya sumber variasi adalah penyebab alami. Tugas manajer ada dua, yaitu memastikan proses mampu beroperasi dalam kendali hanya dengan variasi alami, kemudian mengidentifikasi dan menghilangkan variasi terusut agar proses tetap terkendali.</p>
<p>Instrumen utama SPC adalah peta kendali (<em>control chart</em>), yaitu penyajian grafis data proses dari waktu ke waktu dengan batas kendali atas (UCL) dan batas kendali bawah (LCL) yang telah ditentukan. Landasan teoretisnya adalah teorema limit pusat yang menyatakan bahwa distribusi rata-rata sampel mendekati kurva normal berapa pun bentuk distribusi populasinya, sehingga sekitar 99,73 persen rata-rata sampel akan berada dalam batas plus minus tiga deviasi standar apabila proses hanya mengandung variasi alami. Untuk data variabel digunakan sepasang peta: peta x-bar memantau kecenderungan terpusat (rata-rata) proses dan peta R memantau dispersi (rentang) proses. Batas kendali peta rata-rata dihitung dengan rumus UCL = x-bar + A<sub>2</sub>R-bar dan LCL = x-bar dikurangi A<sub>2</sub>R-bar, sedangkan batas peta rentang adalah UCL<sub>R</sub> = D<sub>4</sub>R-bar dan LCL<sub>R</sub> = D<sub>3</sub>R-bar, dengan x-bar sebagai rata-rata dari rata-rata sampel, R-bar sebagai rata-rata rentang sampel, serta A<sub>2</sub>, D<sub>3</sub>, dan D<sub>4</sub> sebagai faktor tabel menurut ukuran sampel. Kedua peta dipakai bersama karena rata-rata dapat bergeser tanpa perubahan dispersi, dan sebaliknya.</p>
<p>Untuk data atribut digunakan peta p dan peta c. Peta p memantau persentase cacat dalam sampel dengan batas kendali p-bar plus minus z dikali akar dari p-bar(1 dikurangi p-bar) dibagi n, sedangkan peta c memantau jumlah cacat per unit keluaran berdasarkan distribusi Poisson dengan batas kendali c-bar plus minus tiga kali akar c-bar. Pemilihan peta mengikuti jenis data: ukuran kontinu memakai peta x-bar dan R, klasifikasi baik atau cacat memakai peta p, dan hitungan cacat per unit memakai peta c. Lima langkah pembangunan peta kendali adalah mengumpulkan 20 sampai 25 sampel dari proses yang stabil, menghitung batas kendali awal, memplot data, menyelidiki pola di luar kendali dan menghilangkan penyebabnya, kemudian memvalidasi ulang batas kendali dengan sampel tambahan.</p>
<p>Proses yang terkendali secara statistis belum tentu memenuhi spesifikasi desain. Kemampuan proses memenuhi spesifikasi disebut kapabilitas proses dan diukur dengan dua indikator. Rasio kapabilitas proses dihitung sebagai C<sub>p</sub> = (spesifikasi atas dikurangi spesifikasi bawah) dibagi 6 sigma, dengan nilai minimal 1,0 untuk proses yang kapabel dan nilai 2,0 setara dengan standar Six Sigma. Karena C<sub>p</sub> tidak memperhitungkan posisi rata-rata proses terhadap target, digunakan indeks C<sub>pk</sub> yang merupakan nilai minimum dari (batas spesifikasi atas dikurangi rata-rata proses) dibagi 3 sigma dan (rata-rata proses dikurangi batas spesifikasi bawah) dibagi 3 sigma. Nilai C<sub>pk</sub> sebesar 1,0 menandakan proses tepat pada batas kapabel, dan nilai di atas 1,0 semakin diinginkan karena proses dapat bergeser. Sebagai pelengkap, <em>acceptance sampling</em> menguji sampel acak dari lot produk jadi terhadap standar yang ditetapkan, dengan risiko produsen (lot baik ditolak) dan risiko konsumen (lot buruk diterima) sebagai parameter rancangannya; meskipun demikian, arah mutakhir manajemen mutu adalah membangun pengendalian statistis di pemasok sehingga <em>acceptance sampling</em> dapat dihilangkan. Contoh penerapan di Indonesia adalah produsen air minum dalam kemasan yang memantau volume isi botol dengan peta x-bar dan R setiap jam agar memenuhi ketentuan SNI.</p>`
    },
    {
      no: "10.9",
      title: "TQM dalam Sektor Jasa",
      body: `<p>Komponen personal pada jasa lebih sulit diukur daripada komponen berwujud pada barang, karena perbedaan antarjasa dan ekspektasi pelanggan sering kali bersifat tak berwujud dan hanya berupa citra dalam benak pembeli. Manajer operasi berperan pada empat aspek kualitas jasa. Pertama, komponen berwujud jasa tetap penting, misalnya ketepatan tagihan hotel. Kedua, proses jasa menentukan mutu karena sembilan dari sepuluh determinan kualitas jasa berkaitan dengan proses, yaitu keandalan (<em>reliability</em>), daya tanggap (<em>responsiveness</em>), kompetensi, akses, kesopanan, komunikasi, kredibilitas, keamanan, pemahaman pelanggan, dan bukti fisik (<em>tangibles</em>). Ketiga, ekspektasi pelanggan adalah standar penilaian jasa, sehingga manajer tidak boleh menjanjikan lebih dari yang mampu diberikan. Keempat, manajer harus mengantisipasi pengecualian dengan rencana alternatif untuk kondisi operasi yang tidak ideal.</p>
<p>Perusahaan yang dikelola dengan baik memiliki strategi pemulihan layanan (<em>service recovery</em>), yaitu melatih dan memberdayakan karyawan garis depan untuk segera memecahkan masalah pelanggan. Marriott membekali stafnya dengan rutinitas LEARN (<em>listen, empathize, apologize, react, notify</em>) yang memastikan keluhan diumpanbalikkan ke sistem, sementara karyawan Alaska Airlines dibekali seperangkat opsi kompensasi yang dapat langsung ditawarkan kepada penumpang yang dirugikan (Heizer, Render dan Munson, 2017). Instrumen SERVQUAL yang membandingkan ekspektasi layanan dengan kinerja layanan pada lima faktor, yaitu keandalan, jaminan, bukti fisik, empati, dan daya tanggap, lazim digunakan untuk mengukur kesenjangan mutu jasa. Menurut Slack, Brandon-Jones dan Burgess (2022), kesenjangan antara harapan dan persepsi pelanggan itulah yang harus ditutup melalui perancangan spesifikasi layanan dan komunikasi yang konsisten. Dalam konteks Indonesia, Garuda Indonesia membangun standar layanan berjenjang dari salam awak kabin hingga ketepatan waktu, sedangkan bank-bank nasional memantau waktu antrean teller dan tingkat penyelesaian keluhan pada kontak pertama sebagai indikator mutu proses. Selain itu, analitik media sosial memungkinkan perusahaan jasa memantau sentimen pelanggan sehingga masalah layanan terdeteksi sebelum meluas (Turban, Pollard dan Wood, 2021). Dengan demikian, kunci mutu jasa adalah merancang produk layanan, mengelola proses, menyelaraskan ekspektasi pelanggan, dan bersiap menghadapi pengecualian.</p>`
    },
    {
      no: "10.10",
      title: "Rangkuman",
      body: `<p>Kualitas adalah keseluruhan fitur dan karakteristik produk atau jasa yang berkaitan dengan kemampuannya memenuhi kebutuhan pelanggan, dan pengelolaannya menopang strategi diferensiasi, biaya rendah, maupun respons cepat. Perbaikan kualitas meningkatkan laba melalui kenaikan penjualan dan penurunan biaya, sementara kegagalan mutu menimbulkan biaya yang sering diremehkan. Standar ISO 9000 menjadi acuan mutu internasional, dan pemikiran Deming, Juran, Feigenbaum, serta Crosby menempatkan tanggung jawab sistem pada manajemen.</p>
<p>TQM mengelola seluruh organisasi agar unggul pada aspek yang penting bagi pelanggan melalui tujuh konsep, yaitu perbaikan berkesinambungan dengan siklus PDCA, Six Sigma dengan model DMAIC, pemberdayaan karyawan termasuk gugus kendali mutu, <em>benchmarking</em>, <em>just-in-time</em>, konsep Taguchi yang mencakup ketangguhan mutu dan fungsi kerugian kualitas, serta penguasaan tujuh alat TQM. Inspeksi hanya menemukan cacat dan tidak menambah nilai, sehingga pengendalian pada sumber dengan <em>poka-yoke</em> dan daftar periksa lebih diutamakan; SPC melengkapinya dengan peta kendali variabel dan atribut serta ukuran kapabilitas proses C<sub>p</sub> dan C<sub>pk</sub>.</p>
<p>Pada sektor jasa, mutu dinilai dari perbandingan ekspektasi dan pengalaman aktual pelanggan pada determinan seperti keandalan, daya tanggap, dan empati, sehingga strategi pemulihan layanan dan instrumen SERVQUAL menjadi penting. Implikasi manajerial bagi mahasiswa MBA adalah bahwa mutu merupakan hasil rancangan sistem, bukan hasil pemeriksaan akhir; manajer harus membangun budaya perbaikan berkesinambungan, memberdayakan karyawan, memanfaatkan data dan teknologi informasi, serta menyelaraskan program mutu dengan arah strategis perusahaan.</p>`
    },
    {
      no: "10.11",
      title: "Daftar Pustaka",
      body: `<p>Heizer, J., Render, B. dan Munson, C. (2017). <em>Operations Management: Sustainability and Supply Chain Management</em>. Edisi 12. Pearson Education.</p>
<p>Slack, N., Brandon-Jones, A. dan Burgess, N. (2022). <em>Operations Management</em>. Edisi 10. Pearson Education.</p>
<p>Turban, E., Pollard, C. dan Wood, G. (2021). <em>Information Technology for Management: Driving Digital Transformation to Increase Local and Global Performance, Growth and Sustainability</em>. Edisi 12. John Wiley and Sons.</p>
<p>Crosby, P. B. (1979). <em>Quality Is Free</em>. McGraw-Hill.</p>
<p>Deming, W. E. (2000). <em>Out of the Crisis</em>. The MIT Press.</p>`
    }
  ]
};
