window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.sm = window.MBA_BOOK.sm || {};
window.MBA_BOOK.sm[5] = {
  bab: 5,
  judul: "BAB 5 EVALUASI SUMBER DAYA, KAPABILITAS, DAN DAYA SAING PERUSAHAAN",
  sumber: "Thompson, Peteraf, Gamble dan Strickland (2024), Crafting and Executing Strategy, 2024 Release, McGraw Hill",
  lo: [
    "LO 4-1 Mengevaluasi seberapa baik strategi perusahaan saat ini bekerja.",
    "LO 4-2 Menilai kekuatan dan kelemahan perusahaan dalam kaitannya dengan peluang pasar dan ancaman eksternal.",
    "LO 4-3 Menjelaskan mengapa sumber daya dan kapabilitas perusahaan bersifat kritis bagi perolehan keunggulan bersaing atas para pesaing.",
    "LO 4-4 Memahami bagaimana aktivitas rantai nilai memengaruhi struktur biaya dan proposisi nilai pelanggan perusahaan.",
    "LO 4-5 Menjelaskan bagaimana evaluasi menyeluruh atas situasi bersaing perusahaan dapat membantu manajer mengambil keputusan penting mengenai langkah strategis berikutnya."
  ],
  sections: [
    {
      no: "5.1",
      title: "Capaian Pembelajaran",
      body: `<p>Setelah pada sesi sebelumnya dibahas alat analisis untuk menilai lingkungan eksternal perusahaan, sesi ini mengalihkan sorotan analitis ke situasi internal perusahaan. Analisis internal mencakup penilaian atas efektivitas strategi yang sedang berjalan, kekuatan dan kelemahan organisasi, kumpulan sumber daya dan kapabilitas yang dimiliki, serta aktivitas yang dilakukan perusahaan di sepanjang rantai nilainya (Thompson et al., 2024). Analisis internal memungkinkan manajer menentukan apakah strategi perusahaan berpeluang memberikan keunggulan bersaing yang berarti atas para pesaing dengan mempertimbangkan kondisi eksternal yang telah dipetakan sebelumnya. Dengan demikian, kombinasi analisis eksternal dan internal menjadi fondasi bagi perusahaan untuk lulus uji kesesuaian, yaitu uji pertama dari tiga uji strategi yang unggul.</p>
<p>Setelah mempelajari materi pada sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut: pertama, mengevaluasi seberapa baik strategi perusahaan saat ini bekerja; kedua, menilai kekuatan dan kelemahan perusahaan dalam kaitannya dengan peluang pasar dan ancaman eksternal; ketiga, menjelaskan mengapa sumber daya dan kapabilitas perusahaan bersifat kritis bagi perolehan keunggulan bersaing atas para pesaing; keempat, memahami bagaimana aktivitas rantai nilai memengaruhi struktur biaya dan proposisi nilai pelanggan; dan kelima, menjelaskan bagaimana evaluasi menyeluruh atas situasi bersaing perusahaan membantu manajer mengambil keputusan strategis berikutnya.</p>
<p>Untuk mencapai kelima capaian tersebut, pembahasan sesi ini disusun mengikuti enam pertanyaan analitis yang diajukan Thompson et al. (2024), yaitu: seberapa baik strategi perusahaan saat ini bekerja; apa kekuatan dan kelemahan perusahaan dalam kaitannya dengan peluang pasar dan ancaman eksternal; apa sumber daya dan kapabilitas terpenting perusahaan dan apakah keduanya mampu memberikan keunggulan bersaing yang tahan lama; bagaimana aktivitas rantai nilai memengaruhi struktur biaya dan proposisi nilai pelanggan; apakah perusahaan secara kompetitif lebih kuat atau lebih lemah daripada pesaing utama; dan isu strategis apa yang menuntut perhatian utama manajemen. Dalam menjawab keenam pertanyaan tersebut digunakan lima alat analisis utama, yaitu analisis sumber daya dan kapabilitas, analisis SWOT, analisis rantai nilai, <em>benchmarking</em>, dan penilaian kekuatan bersaing.</p>`
    },
    {
      no: "5.2",
      title: "Evaluasi Efektivitas Strategi Perusahaan Saat Ini",
      body: `<p>Langkah awal analisis internal adalah memperoleh gambaran yang jernih mengenai strategi yang sedang dijalankan perusahaan sebelum menilai efektivitasnya. Hal pertama yang perlu diperiksa adalah pendekatan bersaing perusahaan, misalnya apakah perusahaan berupaya meraih keunggulan melalui biaya rendah atau melalui penawaran produk yang lebih baik, serta apakah perusahaan melayani spektrum pelanggan yang luas atau ceruk pasar yang sempit (Thompson et al., 2024). Selain itu, strategi perusahaan juga tercermin dari langkah-langkah terkini untuk menarik pelanggan, seperti penurunan harga, perbaikan desain produk, penambahan fitur, intensifikasi promosi, atau perluasan pasar geografis. Strategi fungsional di bidang riset dan pengembangan, produksi, pemasaran, keuangan, sumber daya manusia, dan teknologi informasi, serta upaya membangun aliansi strategis dengan perusahaan lain, turut melengkapi karakterisasi strategi bisnis tunggal perusahaan.</p>
<p>Menurut Thompson et al. (2024), dua indikator terbaik untuk menilai seberapa baik strategi perusahaan bekerja adalah apakah perusahaan mencatat perbaikan kekuatan finansial dan profitabilitas, serta apakah kekuatan bersaing dan posisi pasar perusahaan mengalami peningkatan. Kegagalan yang terus berulang dalam mencapai target kinerja dan kinerja pasar yang lemah dibandingkan pesaing merupakan tanda peringatan yang andal bahwa perusahaan memiliki strategi yang lemah, eksekusi strategi yang buruk, atau keduanya. Indikator spesifik yang lazim digunakan mencakup tren pertumbuhan penjualan dan laba, tren harga saham, kekuatan finansial keseluruhan, tingkat retensi pelanggan, laju perolehan pelanggan baru, serta bukti perbaikan proses internal seperti tingkat cacat, ketepatan pemenuhan pesanan, waktu pengiriman, hari persediaan, dan produktivitas karyawan. Semakin kuat kinerja keseluruhan perusahaan saat ini, semakin besar kemungkinan strategi perusahaan dirumuskan dan dieksekusi dengan baik; sebaliknya, semakin lemah kinerja finansial dan posisi pasar perusahaan, semakin patut strategi yang berjalan dipertanyakan.</p>
<p>Evaluasi kinerja finansial dilakukan dengan menghitung rasio-rasio keuangan kunci dari laporan keuangan perusahaan. Tabel 5.1 menyajikan sintesis kelompok rasio yang paling sering digunakan beserta rumus dan maknanya. Dalam praktiknya, angka rasio suatu perusahaan harus dibandingkan dengan rata-rata industri dan dengan pesaing utama agar interpretasinya bermakna secara kompetitif, bukan sekadar dibaca sebagai angka absolut. Oleh karena itu, manajer perlu memeriksa tren rasio dari waktu ke waktu untuk menangkap arah perbaikan atau pemburukan kinerja.</p>
<table class="bk-table"><caption>Tabel 5.1 Rasio Keuangan Kunci untuk Menilai Kinerja Strategi</caption>
<thead><tr><th>Kelompok Rasio</th><th>Contoh Rasio dan Rumus</th><th>Makna bagi Evaluasi Strategi</th></tr></thead>
<tbody>
<tr><td>Rasio profitabilitas</td><td><em>Gross profit margin</em> = (Penjualan dikurangi Harga Pokok Penjualan) / Penjualan; <em>operating profit margin</em> = Laba operasi / Penjualan; <em>net profit margin</em> = Laba setelah pajak / Penjualan; ROA = Laba setelah pajak / Total aset; ROE = Laba setelah pajak / Total ekuitas pemegang saham</td><td>Mengukur kemampuan strategi menghasilkan laba dari penjualan, aset, dan modal pemegang saham</td></tr>
<tr><td>Rasio likuiditas</td><td><em>Current ratio</em> = Aset lancar / Kewajiban lancar; modal kerja = Aset lancar dikurangi Kewajiban lancar</td><td>Mengukur kemampuan membayar kewajiban jangka pendek dan ketersediaan dana internal</td></tr>
<tr><td>Rasio leverage</td><td><em>Debt to assets</em> = Total utang / Total aset; <em>debt to equity</em> = Total utang / Total ekuitas; <em>times interest earned</em> = Laba operasi / Beban bunga</td><td>Mengukur struktur permodalan, risiko keuangan, dan kapasitas menanggung beban bunga</td></tr>
<tr><td>Rasio aktivitas</td><td>Hari persediaan = Persediaan / (Harga Pokok Penjualan dibagi 365); perputaran persediaan = Harga Pokok Penjualan / Persediaan; periode penagihan rata-rata = Piutang / (Penjualan dibagi 365)</td><td>Mengukur efektivitas pengelolaan persediaan dan piutang perusahaan</td></tr>
<tr><td>Ukuran penting lain</td><td>Dividen per saham, <em>free cash flow</em>, imbal hasil dividen, rasio harga terhadap laba</td><td>Mengukur imbal hasil bagi pemegang saham dan kapasitas pendanaan internal bagi inisiatif strategis baru</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot></table>
<p>Implikasi manajerialnya, hasil evaluasi kinerja strategi menentukan skala perubahan yang diperlukan. Apabila indikator finansial dan indikator pasar menunjukkan kinerja yang kuat, manajemen cukup melakukan penyesuaian kecil atas strategi yang berjalan. Namun, apabila kinerja terus tertinggal dari target dan dari pesaing, manajemen perlu mempertimbangkan perubahan strategi yang lebih mendasar setelah menuntaskan analisis internal secara menyeluruh melalui alat-alat yang dibahas pada sub-bab berikutnya.</p>`
    },
    {
      no: "5.3",
      title: "Analisis SWOT: Kekuatan, Kelemahan, Peluang, dan Ancaman",
      body: `<p>Pertanyaan analitis kedua menyangkut posisi perusahaan dalam kaitannya dengan kondisi pasar. Alat yang paling sederhana dan paling banyak digunakan untuk keperluan tersebut adalah analisis SWOT, yaitu penilaian atas kekuatan (<em>strengths</em>), kelemahan (<em>weaknesses</em>), peluang (<em>opportunities</em>), dan ancaman (<em>threats</em>) perusahaan (Thompson et al., 2024). Analisis SWOT memberikan gambaran ringkas mengenai kesehatan situasi keseluruhan perusahaan, dengan premis bahwa strategi yang baik harus dibangun di atas kekuatan perusahaan, diarahkan untuk menangkap peluang pasar terbaik, serta sekaligus memperbaiki kelemahan dan mempertahankan diri dari ancaman eksternal.</p>
<h5>5.3.1 Identifikasi Kekuatan dan Kompetensi Perusahaan</h5>
<p>Kekuatan adalah sesuatu yang mampu dilakukan perusahaan dengan baik atau atribut yang meningkatkan daya saingnya di pasar. Salah satu bentuk kekuatan yang paling penting adalah kompetensi, yaitu aktivitas yang telah dipelajari perusahaan hingga mampu dilakukan secara konsisten dengan baik dan pada biaya yang dapat diterima (Thompson et al., 2024). Tingkatan kompetensi dapat dibedakan menjadi tiga, yaitu: kompetensi biasa, <em>core competence</em>, dan <em>distinctive competence</em>. <em>Core competence</em> adalah aktivitas yang dilakukan perusahaan dengan sangat mahir dan bersifat sentral bagi strategi serta keberhasilan bersaingnya, sedangkan <em>distinctive competence</em> adalah aktivitas penting secara kompetitif yang dilakukan perusahaan lebih baik daripada para pesaingnya. Dengan demikian, <em>distinctive competence</em> merupakan kekuatan yang paling bernilai secara strategis karena secara langsung menjadi basis keunggulan bersaing yang berkelanjutan.</p>
<h5>5.3.2 Identifikasi Kelemahan, Peluang Pasar, dan Ancaman Eksternal</h5>
<p>Kelemahan atau defisiensi kompetitif adalah sesuatu yang tidak dimiliki atau dilakukan perusahaan dengan buruk dibandingkan pesaing, atau suatu kondisi yang menempatkan perusahaan pada posisi yang tidak menguntungkan di pasar. Kelemahan dapat berupa keterampilan atau kapabilitas yang inferior, kekurangan aset fisik, organisasional, maupun aset tidak berwujud yang penting secara kompetitif. Di sisi lain, peluang pasar adalah faktor eksternal yang relevan untuk pertumbuhan dan profitabilitas; peluang yang paling layak dikejar adalah peluang yang paling sesuai dengan sumber daya dan kapabilitas perusahaan serta menawarkan prospek pertumbuhan dan laba terbaik. Ancaman eksternal mencakup faktor-faktor seperti masuknya teknologi yang mengganggu, pesaing baru yang agresif, perubahan regulasi, kenaikan suku bunga, atau pergeseran selera pembeli yang dapat menekan profitabilitas perusahaan. Oleh karena itu, manajer perlu menilai peluang mana yang benar-benar cocok dengan perusahaan dan ancaman mana yang memerlukan tindakan defensif segera.</p>
<h5>5.3.3 Menarik Simpulan dari Analisis SWOT</h5>
<p>Nilai sesungguhnya dari analisis SWOT tidak terletak pada penyusunan empat daftar, melainkan pada simpulan yang ditarik dari daftar tersebut dan pada terjemahan simpulan itu menjadi tindakan strategis (Thompson et al., 2024). Simpulan yang perlu dirumuskan mencakup penilaian atas daya tarik situasi keseluruhan perusahaan serta implikasi tindakan, yaitu: menggunakan kekuatan sebagai fondasi strategi, mengejar peluang pasar yang paling sesuai dengan kekuatan perusahaan, memperbaiki kelemahan yang menghambat pengejaran peluang penting atau yang meningkatkan kerentanan terhadap ancaman, dan menggunakan kekuatan perusahaan untuk mengurangi dampak ancaman eksternal yang serius. Sebagai contoh dalam konteks Indonesia, PT Indofood dapat membaca kekuatan jaringan distribusinya yang menjangkau warung-warung di seluruh nusantara sebagai fondasi untuk menangkap peluang pertumbuhan kategori makanan kemasan baru, sekaligus mengantisipasi ancaman masuknya merek mi instan asing melalui penguatan loyalitas merek Indomie. Dengan demikian, analisis SWOT menjadi jembatan antara diagnosis situasi dan perumusan langkah strategis.</p>`
    },
    {
      no: "5.4",
      title: "Analisis Sumber Daya dan Kapabilitas serta Uji VRIN",
      body: `<p>Pertanyaan analitis ketiga menuntut pemeriksaan yang lebih dalam atas aset kompetitif perusahaan. Analisis sumber daya dan kapabilitas menyediakan kerangka bagi manajer untuk mengidentifikasi aset kompetitif perusahaan dan menilai apakah aset tersebut mampu menopang keunggulan bersaing yang berkelanjutan atas para pesaing (Thompson et al., 2024). Pendekatan ini berakar pada pandangan berbasis sumber daya (<em>resource-based view</em>) yang menyatakan bahwa perbedaan kinerja antarperusahaan dalam satu industri terutama bersumber dari perbedaan kualitas sumber daya dan kapabilitas yang dimiliki masing-masing perusahaan.</p>
<h5>5.4.1 Identifikasi Sumber Daya dan Kapabilitas</h5>
<p>Sumber daya adalah input produktif atau aset kompetitif yang dimiliki atau dikendalikan perusahaan, sedangkan kapabilitas adalah kecakapan perusahaan dalam melaksanakan suatu aktivitas secara baik dengan mendayagunakan sumber dayanya (Thompson et al., 2024). Sumber daya dapat dikelompokkan menjadi sumber daya berwujud (<em>tangible</em>) dan tidak berwujud (<em>intangible</em>). Sumber daya berwujud mencakup sumber daya fisik seperti pabrik dan lokasi strategis, sumber daya finansial, aset teknologi seperti paten, serta sumber daya organisasional seperti sistem informasi. Sumber daya tidak berwujud mencakup aset manusia dan modal intelektual, merek serta citra dan reputasi perusahaan, hubungan dengan mitra dan pelanggan, dan budaya serta sistem insentif organisasi. Dalam banyak kasus, sumber daya tidak berwujud justru lebih bernilai secara kompetitif karena lebih sulit ditiru pesaing. Kapabilitas pada umumnya bersifat lintas fungsi dan dibangun dari pengetahuan serta kerja sama orang-orang di berbagai unit organisasi, misalnya kapabilitas pengembangan produk baru yang cepat atau kapabilitas pemasaran digital.</p>
<h5>5.4.2 Empat Uji Kekuatan Kompetitif Sumber Daya (VRIN)</h5>
<p>Untuk menilai apakah suatu sumber daya atau kapabilitas mampu menjadi basis keunggulan bersaing yang berkelanjutan, digunakan empat uji yang dikenal sebagai uji VRIN, yaitu <em>Valuable</em>, <em>Rare</em>, <em>Inimitable</em>, dan <em>Non-substitutable</em> (Thompson et al., 2024). Tabel 5.2 merangkum keempat uji tersebut beserta pertanyaan diagnostiknya. Sumber daya yang lulus dua uji pertama berpotensi memberikan keunggulan bersaing, sedangkan sumber daya yang lulus keempat uji berpotensi memberikan keunggulan bersaing yang berkelanjutan. Sumber daya yang bernilai dan langka tergolong sulit ditiru apabila secara fisik unik, terikat pada lintasan sejarah perusahaan (<em>path dependent</em>), bersifat ambigu secara kausal sehingga pesaing tidak memahami sumbernya, atau memerlukan investasi yang sangat besar untuk direplikasi.</p>
<table class="bk-table"><caption>Tabel 5.2 Uji VRIN atas Kekuatan Kompetitif Sumber Daya dan Kapabilitas</caption>
<thead><tr><th>Uji</th><th>Pertanyaan Diagnostik</th><th>Implikasi bila Lulus</th></tr></thead>
<tbody>
<tr><td><em>Valuable</em> (bernilai)</td><td>Apakah sumber daya relevan secara kompetitif dan berkontribusi pada efektivitas strategi perusahaan di pasar?</td><td>Menjadi prasyarat dasar; tanpa nilai kompetitif, sumber daya tidak berkontribusi pada keunggulan</td></tr>
<tr><td><em>Rare</em> (langka)</td><td>Apakah sumber daya jarang dimiliki oleh para pesaing dalam industri?</td><td>Bersama nilai, kelangkaan memungkinkan keunggulan bersaing sementara</td></tr>
<tr><td><em>Inimitable</em> (sulit ditiru)</td><td>Apakah sumber daya sulit ditiru karena keunikan fisik, ketergantungan lintasan sejarah, ambiguitas kausal, atau hambatan ekonomi?</td><td>Keunggulan lebih tahan lama karena upaya imitasi pesaing terhambat</td></tr>
<tr><td><em>Non-substitutable</em> (tidak tersubstitusi)</td><td>Apakah tidak tersedia sumber daya lain yang berbeda namun mampu menjalankan fungsi kompetitif yang setara?</td><td>Keunggulan bersaing berpotensi berkelanjutan karena tidak dapat dilangkahi lewat substitusi</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot></table>
<p>Sebagai ilustrasi penerapan, kapabilitas layanan perbankan digital dan reputasi keandalan yang dibangun Bank Central Asia selama puluhan tahun di Indonesia dapat dinilai bernilai dan langka, serta relatif sulit ditiru karena melekat pada kepercayaan nasabah dan efek jaringan basis pelanggan yang sangat besar. Sebaliknya, kepemilikan mesin anjungan tunai mandiri semata tidak lulus uji kelangkaan karena hampir semua bank memilikinya. Contoh tersebut menunjukkan bahwa uji VRIN membantu manajer memilah aset mana yang benar-benar strategis dan aset mana yang sekadar menjadi syarat minimum untuk bersaing.</p>
<h5>5.4.3 Kapabilitas Dinamis dan Pembaruan Aset Kompetitif</h5>
<p>Nilai kompetitif suatu sumber daya tidak bersifat permanen karena perubahan teknologi, preferensi pelanggan, dan langkah pesaing dapat mengikis relevansinya. Oleh karena itu, perusahaan memerlukan kapabilitas dinamis (<em>dynamic capabilities</em>), yaitu kapasitas perusahaan untuk memodifikasi, memperdalam, atau merekonfigurasi sumber daya dan kapabilitas yang ada serta menciptakan yang baru secara berkesinambungan (Thompson et al., 2024). Kapabilitas dinamis dapat diwujudkan melalui investasi berkelanjutan pada peningkatan kompetensi yang telah dimiliki, akuisisi kapabilitas baru melalui merger dan aliansi, maupun pembentukan kapabilitas melalui proses belajar organisasi lintas fungsi. Implikasi manajerialnya, tugas manajer bukan hanya mengeksploitasi aset kompetitif saat ini, melainkan juga memperbarui portofolio aset tersebut agar tetap selaras dengan kondisi pasar yang berubah.</p>`
    },
    {
      no: "5.5",
      title: "Analisis Rantai Nilai dan Benchmarking",
      body: `<p>Pertanyaan analitis keempat berkaitan dengan daya saing harga dan biaya perusahaan serta efektivitasnya dalam menyampaikan nilai kepada pelanggan. Semakin besar nilai yang diberikan perusahaan kepada pelanggan secara menguntungkan dibandingkan pesaing, semakin kecil kerentanan kompetitifnya. Dua alat analisis yang digunakan untuk menjawab pertanyaan ini adalah analisis rantai nilai dan <em>benchmarking</em> (Thompson et al., 2024). Keduanya membantu manajer menelusuri dari mana biaya perusahaan berasal dan di aktivitas mana nilai pelanggan diciptakan.</p>
<h5>5.5.1 Konsep Rantai Nilai Perusahaan</h5>
<p>Rantai nilai (<em>value chain</em>) adalah rangkaian aktivitas internal yang dilakukan perusahaan dalam merancang, memproduksi, memasarkan, mengirimkan, dan mendukung produknya, yang masing-masing menciptakan nilai bagi pelanggan sekaligus menimbulkan biaya (Thompson et al., 2024). Aktivitas rantai nilai terbagi menjadi dua kelompok, yaitu aktivitas primer dan aktivitas pendukung. Aktivitas primer mencakup manajemen rantai pasokan, operasi, distribusi, penjualan dan pemasaran, serta layanan purnajual, karena aktivitas-aktivitas tersebut secara langsung menciptakan nilai bagi pelanggan. Aktivitas pendukung mencakup riset dan pengembangan produk, teknologi dan pengembangan sistem, manajemen sumber daya manusia, serta administrasi umum, yang menopang pelaksanaan aktivitas primer. Dengan memetakan biaya dan kontribusi nilai setiap aktivitas, manajer dapat mengidentifikasi aktivitas mana yang menjadi sumber keunggulan biaya, aktivitas mana yang menjadi pendorong diferensiasi, dan aktivitas mana yang justru membebani struktur biaya tanpa menambah nilai yang berarti bagi proposisi nilai pelanggan.</p>
<h5>5.5.2 Sistem Rantai Nilai Industri</h5>
<p>Daya saing biaya perusahaan tidak hanya ditentukan oleh rantai nilai internalnya, melainkan juga oleh rantai nilai pemasok di hulu dan rantai nilai mitra saluran distribusi di hilir, yang bersama-sama membentuk sistem rantai nilai industri (<em>value chain system</em>). Biaya dan marjin pemasok menjadi bagian dari biaya perusahaan, sedangkan biaya dan marjin distributor serta peritel memengaruhi harga akhir yang dibayar pembeli dan kepuasan mereka. Oleh karena itu, penilaian daya saing yang akurat menuntut manajer memahami keseluruhan sistem penyampaian nilai, bukan hanya rantai nilai perusahaannya sendiri. Sebagai contoh, keberhasilan produsen barang konsumsi di Indonesia sangat bergantung pada efisiensi jaringan distributor dan jutaan pedagang eceran tradisional yang menjadi mata rantai terakhir menuju konsumen, sehingga program kemitraan dan digitalisasi warung menjadi agenda strategis untuk menekan biaya sistem secara keseluruhan.</p>
<h5>5.5.3 Benchmarking sebagai Alat Penilaian Biaya dan Efektivitas Aktivitas</h5>
<p>Menurut Thompson et al. (2024), <em>benchmarking</em> adalah alat yang ampuh untuk membandingkan cara perusahaan melaksanakan aktivitas rantai nilai tertentu dengan cara pelaksanaan aktivitas serupa oleh perusahaan lain yang berkinerja terbaik, guna mengetahui apakah biaya dan efektivitas aktivitas perusahaan kompetitif. Objek perbandingan dapat mencakup cara pembelian material, pengelolaan persediaan, perakitan produk, kecepatan peluncuran produk baru, hingga cara pelaksanaan fungsi pemeliharaan. Sumber data <em>benchmarking</em> meliputi laporan publik, pameran dagang, wawancara dengan pelanggan dan pemasok, serta jasa lembaga konsultan dan asosiasi <em>benchmarking</em> independen yang menjaga kerahasiaan identitas perusahaan pembanding. Dalam pelaksanaannya, etika <em>benchmarking</em> menuntut peserta untuk tidak meminta informasi rahasia pesaing secara tidak patut dan tidak menyebarkan data mitra pembanding tanpa izin. Hasil <em>benchmarking</em> memberi tolok ukur objektif mengenai posisi biaya perusahaan, apakah tergolong pemimpin biaya atau justru tertinggal.</p>
<h5>5.5.4 Opsi Strategis Memperbaiki Kelemahan Biaya dan Nilai</h5>
<p>Apabila analisis rantai nilai dan <em>benchmarking</em> mengungkap kelemahan biaya atau kelemahan penyampaian nilai, tindakan perbaikan dapat diarahkan pada tiga wilayah sistem rantai nilai. Pertama, pada aktivitas yang dilakukan secara internal, perusahaan dapat menerapkan praktik terbaik, merekayasa ulang proses, merelokasi aktivitas berbiaya tinggi, mengalihdayakan aktivitas kepada pihak yang lebih efisien, atau berinvestasi pada teknologi yang meningkatkan produktivitas. Kedua, pada rantai nilai pemasok, perusahaan dapat menegosiasikan harga yang lebih menguntungkan, bekerja sama memperbaiki efisiensi pemasok, atau beralih ke input substitusi yang lebih murah. Ketiga, pada rantai nilai saluran distribusi, perusahaan dapat mendorong efisiensi distributor, mengubah strategi distribusi termasuk menjual langsung kepada konsumen melalui kanal digital, atau berbagi manfaat efisiensi dengan mitra saluran. Dengan demikian, analisis rantai nilai bukan hanya alat diagnosis, melainkan juga peta jalan perbaikan proposisi nilai pelanggan dan struktur biaya.</p>
<h5>5.5.5 Rantai Nilai, Kompetensi Inti, dan Keunggulan Bersaing</h5>
<p>Kinerja aktivitas rantai nilai yang unggul merupakan sumber pembentukan kapabilitas dan kompetensi perusahaan. Aktivitas yang dilakukan secara konsisten dengan sangat baik dari waktu ke waktu dapat berkembang menjadi <em>core competence</em> dan pada akhirnya <em>distinctive competence</em> yang menopang keunggulan bersaing, baik melalui posisi biaya yang lebih rendah maupun melalui diferensiasi yang dihargai pembeli. Oleh karena itu, manajer perlu memandang rantai nilai sebagai wahana pembelajaran organisasi, tempat investasi dan perbaikan berkelanjutan diarahkan pada aktivitas yang paling menentukan keberhasilan strategi perusahaan.</p>`
    },
    {
      no: "5.6",
      title: "Penilaian Kekuatan Bersaing Perusahaan",
      body: `<p>Pertanyaan analitis kelima adalah apakah perusahaan secara keseluruhan lebih kuat atau lebih lemah secara kompetitif dibandingkan para pesaing utamanya. Untuk menjawabnya digunakan penilaian kekuatan bersaing (<em>competitive strength assessment</em>), yaitu pemeringkatan kuantitatif perusahaan terhadap pesaing kunci pada setiap faktor penentu keberhasilan industri dan setiap tolok ukur kekuatan kompetitif yang relevan (Thompson et al., 2024). Data hasil <em>benchmarking</em> dan pengamatan atas pesaing menjadi masukan utama dalam penilaian ini.</p>
<p>Prosedur penilaian kekuatan bersaing dilakukan melalui empat langkah, yaitu: pertama, menyusun daftar faktor kunci keberhasilan industri dan ukuran kekuatan kompetitif yang paling menentukan, umumnya enam sampai sepuluh faktor; kedua, memberikan bobot pada setiap faktor sesuai tingkat kepentingannya sehingga jumlah seluruh bobot sama dengan satu; ketiga, memberi skor kepada perusahaan dan setiap pesaing pada tiap faktor, lazimnya dengan skala satu sampai sepuluh; dan keempat, mengalikan skor dengan bobot untuk memperoleh nilai tertimbang, lalu menjumlahkannya menjadi skor kekuatan bersaing keseluruhan setiap perusahaan. Perbandingan skor keseluruhan menunjukkan siapa yang memiliki keunggulan bersaing neto terbesar, sedangkan perbandingan skor per faktor menunjukkan pada dimensi apa perusahaan unggul atau tertinggal terhadap setiap pesaing.</p>
<p>Hasil penilaian kekuatan bersaing memiliki implikasi ofensif dan defensif yang penting. Perusahaan sebaiknya mengarahkan serangan kompetitif pada wilayah di mana perusahaan kuat dan pesaing lemah, karena di wilayah itulah serangan paling berpeluang berhasil, serta membidik pesaing yang skor keseluruhannya lebih rendah. Sebaliknya, skor yang rendah pada faktor tertentu menandakan kerentanan yang perlu segera diperkuat sebelum dieksploitasi pesaing. Sebagai contoh sederhana, sebuah maskapai berbiaya rendah di Indonesia yang unggul pada faktor biaya per kursi namun tertinggal pada faktor ketepatan waktu dapat menyimpulkan bahwa perbaikan keandalan operasional merupakan prioritas defensif, sementara ekspansi pada rute yang dilayani pesaing berbiaya tinggi merupakan peluang ofensif. Dengan demikian, penilaian kekuatan bersaing menerjemahkan seluruh analisis sebelumnya menjadi peta posisi kompetitif yang dapat ditindaklanjuti.</p>`
    },
    {
      no: "5.7",
      title: "Identifikasi Isu Strategis yang Menuntut Perhatian Manajemen",
      body: `<p>Langkah analitis terakhir dan sekaligus paling penting adalah merumuskan isu dan masalah strategis yang harus menjadi perhatian utama manajemen. Langkah ini menuntut manajer menarik benang merah dari hasil analisis lingkungan eksternal pada sesi sebelumnya dan hasil analisis internal pada sesi ini, kemudian menuangkannya ke dalam suatu daftar kekhawatiran (<em>worry list</em>) berisi persoalan yang wajib diselesaikan agar perusahaan berhasil secara finansial dan kompetitif pada tahun-tahun mendatang (Thompson et al., 2024). Isu-isu tersebut lazim dirumuskan dalam bentuk pertanyaan bagaimana atau apakah, misalnya bagaimana perusahaan mempertahankan pangsa pasar dari tekanan pesaing berbiaya rendah, atau apakah perusahaan sebaiknya memperluas lini produk ke segmen yang berdekatan.</p>
<p>Perumusan daftar isu strategis yang tajam menentukan seberapa tepat agenda tindakan manajemen. Apabila strategi yang berjalan telah sesuai dengan situasi internal dan eksternal, isu yang muncul cenderung menuntut penyempurnaan; sebaliknya, apabila strategi saat ini tidak lagi cocok dengan kondisi yang dihadapi, isu yang muncul menuntut perumusan strategi yang benar-benar baru. Dengan demikian, kualitas keputusan strategis pada akhirnya bergantung pada kejujuran dan ketelitian manajemen dalam mendiagnosis situasi perusahaan, karena strategi yang unggul hanya dapat lahir dari pemahaman yang akurat atas persoalan yang sesungguhnya dihadapi.</p>`
    },
    {
      no: "5.8",
      title: "Rangkuman",
      body: `<p>Sesi ini membahas enam pertanyaan kunci dan lima alat analisis untuk mengevaluasi situasi internal perusahaan. Evaluasi diawali dengan menilai seberapa baik strategi saat ini bekerja melalui indikator kinerja finansial dan posisi pasar, termasuk rasio-rasio keuangan kunci. Analisis SWOT selanjutnya memetakan kekuatan, kelemahan, peluang, dan ancaman, dengan penekanan bahwa nilai analisis terletak pada simpulan dan tindak lanjutnya. Analisis sumber daya dan kapabilitas beserta uji VRIN menilai apakah aset kompetitif perusahaan bernilai, langka, sulit ditiru, dan tidak tersubstitusi sehingga mampu menopang keunggulan bersaing yang berkelanjutan, sementara kapabilitas dinamis menjamin pembaruan aset tersebut seiring perubahan lingkungan.</p>
<p>Selanjutnya, analisis rantai nilai dan <em>benchmarking</em> menelusuri bagaimana aktivitas primer dan aktivitas pendukung membentuk struktur biaya serta proposisi nilai pelanggan, termasuk keterkaitannya dengan rantai nilai pemasok dan saluran distribusi dalam sistem rantai nilai industri. Kelemahan biaya atau nilai yang teridentifikasi dapat diperbaiki melalui tindakan pada aktivitas internal, pada hubungan dengan pemasok, maupun pada saluran distribusi. Penilaian kekuatan bersaing tertimbang kemudian mengukur posisi kompetitif perusahaan relatif terhadap pesaing utama pada faktor-faktor kunci keberhasilan industri, sehingga terlihat wilayah keunggulan yang layak diserang dan kerentanan yang perlu dipertahankan.</p>
<p>Keseluruhan hasil analisis eksternal dan internal bermuara pada penyusunan daftar isu strategis yang menuntut perhatian utama manajemen. Daftar tersebut menjadi agenda perumusan langkah strategis berikutnya, baik berupa penyempurnaan strategi yang berjalan maupun perubahan strategi yang mendasar. Dengan demikian, evaluasi menyeluruh atas sumber daya, kapabilitas, dan daya saing perusahaan merupakan prasyarat bagi perumusan strategi yang lulus uji kesesuaian, uji keunggulan bersaing, dan uji kinerja.</p>`
    },
    {
      no: "5.9",
      title: "Daftar Pustaka",
      body: `<p>Thompson, A. A., Peteraf, M. A., Gamble, J. E. dan Strickland, A. J. (2024). <em>Crafting and Executing Strategy: The Quest for Competitive Advantage, Concepts and Cases</em>. 2024 Release. McGraw Hill.</p>
<p>Barney, J. B. (1991). Firm Resources and Sustained Competitive Advantage. <em>Journal of Management</em>, 17(1), 99-120.</p>
<p>Porter, M. E. (1985). <em>Competitive Advantage: Creating and Sustaining Superior Performance</em>. Free Press.</p>`
    }
  ]
};
