window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.sm = window.MBA_BOOK.sm || {};
window.MBA_BOOK.sm[8] = {
  bab: 8,
  judul: "BAB 8 STRATEGI KORPORAT: DIVERSIFIKASI DAN PERUSAHAAN MULTIBISNIS",
  sumber: "Thompson, Peteraf, Gamble dan Strickland (2024), Crafting and Executing Strategy, 2024 Release, McGraw Hill",
  lo: [
    "LO 8-1 Menjelaskan kapan dan bagaimana diversifikasi bisnis dapat meningkatkan nilai pemegang saham.",
    "LO 8-2 Menguraikan bagaimana strategi diversifikasi terkait dapat menghasilkan kecocokan strategis lintas bisnis yang mampu memberikan keunggulan bersaing.",
    "LO 8-3 Mengidentifikasi manfaat dan risiko strategi diversifikasi tidak terkait.",
    "LO 8-4 Menggunakan alat analisis untuk mengevaluasi strategi diversifikasi suatu perusahaan.",
    "LO 8-5 Memahami empat opsi utama strategi korporat yang dapat ditempuh perusahaan terdiversifikasi untuk memperbaiki kinerja perusahaan."
  ],
  sections: [
    {
      no: "8.1",
      title: "Capaian Pembelajaran",
      body: `<p>Bab ini menaikkan tingkat analisis strategi dari perusahaan bisnis tunggal menuju perusahaan multibisnis yang terdiversifikasi. Pada perusahaan bisnis tunggal, manajemen hanya perlu merumuskan satu <em>business strategy</em> untuk bersaing dalam satu lingkungan industri. Sebaliknya, pada perusahaan terdiversifikasi, manajemen puncak harus menilai berbagai lingkungan industri sekaligus, mengembangkan satu strategi bisnis untuk setiap arena industri, serta merumuskan strategi korporat yang menyatukan seluruh portofolio bisnis menjadi satu kesatuan yang rasional dan bernilai (Thompson et al., 2024). Oleh karena itu, pemahaman terhadap logika ekonomi diversifikasi menjadi kompetensi penting bagi mahasiswa program magister manajemen yang kelak mengelola perusahaan multibisnis.</p>
<p>Setelah mempelajari materi pada sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p>1. Menjelaskan kapan dan bagaimana diversifikasi bisnis dapat meningkatkan nilai pemegang saham. 2. Menguraikan bagaimana strategi diversifikasi terkait dapat menghasilkan kecocokan strategis lintas bisnis yang mampu memberikan keunggulan bersaing. 3. Mengidentifikasi manfaat dan risiko strategi diversifikasi tidak terkait. 4. Menggunakan alat analisis untuk mengevaluasi strategi diversifikasi suatu perusahaan. 5. Memahami empat opsi utama strategi korporat yang dapat ditempuh perusahaan terdiversifikasi untuk memperbaiki kinerja keseluruhan perusahaan.</p>`
    },
    {
      no: "8.2",
      title: "Hakikat Strategi Korporat dan Keputusan untuk Berdiversifikasi",
      body: `<p>Pertanyaan mengenai ke mana dan bagaimana perusahaan memperluas diri ke bisnis baru merupakan inti dari strategi korporat. Menurut Thompson et al. (2024), strategi korporat adalah strategi tingkat perusahaan yang menetapkan lingkup bisnis yang dimasuki perusahaan serta cara mengelola kumpulan bisnis tersebut agar kinerja gabungannya lebih baik daripada kinerja masing-masing bisnis secara terpisah. Dengan demikian, strategi korporat berbeda dari strategi bisnis, karena fokusnya bukan pada cara memenangkan persaingan di satu industri, melainkan pada komposisi portofolio bisnis dan penciptaan nilai lintas bisnis.</p>
<h5>8.2.1 Tiga Tugas Utama Perumusan Strategi Diversifikasi</h5>
<p>Perumusan strategi korporat perusahaan terdiversifikasi berada di tangan eksekutif puncak dan mencakup tiga tugas utama. Pertama, memilih industri baru yang akan dimasuki dan menentukan cara masuknya, yaitu melalui akuisisi, pendirian usaha baru dari nol, atau usaha patungan dengan perusahaan lain. Kedua, mengejar peluang untuk mengubah hubungan rantai nilai lintas bisnis yang memiliki kecocokan strategis menjadi keunggulan bersaing, misalnya dengan mentransfer sumber daya dan kapabilitas antarbisnis, menggabungkan aktivitas rantai nilai yang serupa untuk menurunkan biaya, berbagi merek yang kuat, serta mendorong kolaborasi dan pertukaran pengetahuan antarunit. Ketiga, memprakarsai tindakan untuk meningkatkan kinerja gabungan seluruh bisnis, baik dengan mempertahankan susunan bisnis yang ada, memperluas basis diversifikasi, melepas bisnis yang berkinerja buruk, maupun merestrukturisasi portofolio secara menyeluruh (Thompson et al., 2024). Karena ketiga tugas tersebut menuntut waktu dan perhatian yang besar, eksekutif korporat umumnya mendelegasikan tanggung jawab strategi bisnis kepada pimpinan masing-masing unit dan menuntut akuntabilitas atas hasil keuangan serta hasil strategisnya.</p>
<h5>8.2.2 Kapan Diversifikasi Perlu Dipertimbangkan</h5>
<p>Selama perusahaan masih memiliki peluang pertumbuhan yang menguntungkan di industrinya saat ini, tidak ada urgensi untuk berdiversifikasi. Namun, peluang pertumbuhan sering kali terbatas pada industri yang telah matang, ketika permintaan pembeli mendatar atau menurun, atau ketika perubahan kondisi industri seperti teknologi baru, produk substitusi, pergeseran preferensi pembeli, dan intensifikasi persaingan menggerus kemampuan perusahaan menghasilkan pertumbuhan pendapatan dan laba (Thompson et al., 2024). Contoh yang dikemukakan dalam buku adalah News Corp yang melindungi nilai pemegang saham dari penurunan penjualan surat kabar dengan berdiversifikasi ke layanan video berlangganan, layanan properti digital, serta jasa informasi riset keuangan. Dalam konteks Indonesia, fenomena serupa terlihat pada Kompas Gramedia yang memperluas usahanya dari media cetak ke perhotelan, pendidikan, dan media digital ketika industri surat kabar mengalami tekanan struktural. Oleh karena itu, keputusan diversifikasi harus selalu diawali dengan justifikasi ekonomi yang kuat, bukan sekadar keinginan untuk menjadi besar.</p>`
    },
    {
      no: "8.3",
      title: "Membangun Nilai Pemegang Saham: Tiga Uji Keunggulan Korporat",
      body: `<p>Diversifikasi harus memberikan manfaat yang lebih besar daripada sekadar menyebarkan risiko bisnis ke berbagai industri. Menurut Thompson et al. (2024), diversifikasi hanya dapat dibenarkan apabila menghasilkan tambahan nilai ekonomi jangka panjang bagi pemegang saham, yaitu nilai yang tidak dapat diperoleh pemegang saham sendiri dengan cara membeli saham perusahaan di industri lain atau berinvestasi pada reksa dana. Dari pemikiran tersebut dapat disimpulkan bahwa alasan penyebaran risiko semata tidak cukup, karena investor mampu mendiversifikasi portofolionya sendiri dengan biaya yang jauh lebih murah daripada biaya akuisisi perusahaan.</p>
<p>Suatu langkah diversifikasi berpeluang membangun nilai pemegang saham apabila lulus tiga uji keunggulan korporat (<em>Tests of Corporate Advantage</em>) sebagai berikut:</p>
<p>Pertama, uji daya tarik industri (<em>industry attractiveness test</em>). Industri yang akan dimasuki harus menarik secara struktural menurut kerangka lima kekuatan Porter, memiliki kebutuhan sumber daya yang sesuai dengan sumber daya perusahaan induk, serta menawarkan prospek pertumbuhan, profitabilitas, dan imbal hasil investasi yang baik. Kedua, uji biaya masuk (<em>cost-of-entry test</em>). Biaya memasuki industri sasaran tidak boleh sedemikian tinggi sehingga menghapus potensi laba yang akan diperoleh. Terdapat situasi dilematis pada uji ini, karena semakin menarik suatu industri, semakin tinggi pula hambatan masuk dan harga akuisisi perusahaan yang sudah mapan di dalamnya, sehingga akuisisi perusahaan yang sukses sering kali gagal memenuhi uji biaya masuk. Ketiga, uji menjadi lebih baik (<em>better-off test</em>). Bisnis baru harus berpotensi berkinerja lebih baik di bawah satu payung korporat bersama bisnis yang sudah ada dibandingkan apabila masing-masing beroperasi secara mandiri, suatu efek yang dikenal sebagai sinergi (Thompson et al., 2024).</p>
<p>Konsep sinergi sering dilambangkan dengan efek 1 + 1 = 3, yang berarti gabungan bisnis menghasilkan kinerja melebihi penjumlahan kinerja masing-masing bisnis secara terpisah. Apabila laba konsolidasi perusahaan pengakuisisi dan perusahaan yang diakuisisi tidak lebih besar daripada laba yang dapat dicapai keduanya secara mandiri, diversifikasi tersebut tidak menambah nilai karena pemegang saham dapat memperoleh hasil 1 + 1 = 2 hanya dengan membeli saham kedua perusahaan. Dengan demikian, langkah diversifikasi harus lulus ketiga uji sekaligus untuk menumbuhkan nilai pemegang saham dalam jangka panjang, sedangkan langkah yang hanya lulus satu atau dua uji patut diragukan. Implikasi manajerialnya adalah setiap usulan ekspansi ke bisnis baru perlu diuji secara disiplin dengan ketiga kriteria tersebut sebelum keputusan investasi diambil, agar perusahaan terhindar dari diversifikasi yang menghancurkan nilai.</p>`
    },
    {
      no: "8.4",
      title: "Cara Memasuki Bisnis Baru",
      body: `<p>Setelah keputusan berdiversifikasi diambil, manajemen harus memilih moda masuk ke bisnis baru. Menurut Thompson et al. (2024), terdapat tiga bentuk utama cara masuk, yaitu akuisisi perusahaan yang sudah ada, pendirian usaha baru secara internal, dan usaha patungan dengan perusahaan lain. Masing-masing moda memiliki keunggulan dan kelemahan yang harus dipertimbangkan sesuai kondisi industri sasaran dan sumber daya perusahaan.</p>
<h5>8.4.1 Diversifikasi melalui Akuisisi</h5>
<p>Akuisisi merupakan cara masuk yang paling populer karena lebih cepat daripada membangun operasi baru dan efektif untuk melompati hambatan masuk seperti penguasaan teknologi, hubungan pemasok, skala ekonomi, kesadaran merek, dan akses distribusi. Akuisisi juga lazim digunakan untuk memperoleh sumber daya dan kapabilitas yang bersifat komplementer dan sulit dikembangkan sendiri. Namun, akuisisi dapat menjadi sangat mahal karena mencakup harga beli, biaya uji tuntas, biaya negosiasi, dan biaya integrasi pascaakuisisi. Apabila perusahaan sasaran merupakan perusahaan yang sukses, pembeli harus membayar premi akuisisi (<em>acquisition premium</em>), yaitu selisih antara harga penawaran dan nilai pasar perusahaan sasaran sebelum akuisisi, yang secara historis di Amerika Serikat rata-rata berkisar 25 sampai 30 persen (Thompson et al., 2024). Contohnya adalah akuisisi Jimmy Choo oleh Michael Kors yang memuat premi sekitar 36,5 persen di atas harga saham sebelumnya. Semakin besar premi yang dibayar, semakin berat pula tuntutan sinergi yang harus direalisasikan agar akuisisi lulus uji biaya masuk.</p>
<h5>8.4.2 Diversifikasi melalui Pengembangan Internal</h5>
<p>Pengembangan internal atau pendirian usaha baru dari dalam perusahaan, yang sering disebut <em>corporate venturing</em> atau <em>new venture development</em>, berarti perusahaan membangun sendiri bisnis baru mulai dari perekrutan, pembangunan fasilitas, pengembangan produk, hingga pembentukan jaringan distribusi. Moda ini menarik apabila perusahaan memiliki kapabilitas internal yang memadai, waktu yang tersedia cukup longgar, biaya internal lebih rendah daripada biaya akuisisi, industri sasaran masih bertumbuh, penambahan kapasitas baru tidak mengganggu keseimbangan penawaran dan permintaan industri, serta pesaing yang ada lambat bereaksi terhadap pendatang baru (Thompson et al., 2024). Di sisi lain, pengembangan internal menghadapi risiko kegagalan yang tinggi karena harus mengatasi hambatan masuk secara mandiri dan membutuhkan waktu lama untuk mencapai skala yang menguntungkan.</p>
<h5>8.4.3 Diversifikasi melalui Usaha Patungan</h5>
<p>Usaha patungan (<em>joint venture</em>) berguna untuk memasuki bisnis baru dalam tiga situasi. Pertama, ketika peluang bisnis terlalu berisiko atau terlalu kompleks untuk ditangani satu perusahaan sendirian. Kedua, ketika peluang tersebut menuntut kombinasi sumber daya dan kapabilitas yang tidak dimiliki satu perusahaan secara lengkap, sehingga penggabungan kekuatan dua pihak atau lebih menjadi keharusan. Ketiga, ketika masuk ke pasar luar negeri memerlukan mitra lokal karena regulasi pemerintah atau kebutuhan pemahaman kondisi setempat. Namun, usaha patungan mengandung potensi konflik kepentingan antarmitra, perbedaan tujuan strategis, dan pertanyaan mengenai pembagian kendali yang dapat menghambat pengambilan keputusan (Thompson et al., 2024).</p>
<h5>8.4.4 Memilih Moda Masuk yang Tepat</h5>
<p>Pemilihan moda masuk terbaik bergantung pada empat pertanyaan kunci. Pertama, apakah perusahaan memiliki seluruh sumber daya dan kapabilitas yang diperlukan untuk masuk; apabila belum, akuisisi atau usaha patungan lebih tepat. Kedua, apakah hambatan masuk industri tinggi; hambatan yang tinggi cenderung membuat akuisisi lebih unggul daripada pengembangan internal. Ketiga, apakah kecepatan merupakan faktor penting; akuisisi memberikan kecepatan, sedangkan pengembangan internal menuntut kesabaran. Keempat, moda mana yang biayanya paling rendah; pertimbangan ini berkaitan dengan konsep biaya transaksi (<em>transaction costs</em>), yaitu biaya menyelesaikan kesepakatan bisnis yang melampaui harga kesepakatan itu sendiri, mencakup biaya pencarian mitra, negosiasi, dan pemantauan kontrak (Thompson et al., 2024). Dengan demikian, tidak ada moda masuk yang unggul secara mutlak, karena keputusan harus disesuaikan dengan konteks industri dan kondisi internal perusahaan.</p>`
    },
    {
      no: "8.5",
      title: "Diversifikasi ke Bisnis Terkait dan Kecocokan Strategis",
      body: `<p>Pilihan jalur diversifikasi pada dasarnya terbagi menjadi dua, yaitu diversifikasi ke bisnis terkait (<em>related diversification</em>) dan diversifikasi ke bisnis tidak terkait (<em>unrelated diversification</em>). Menurut Thompson et al. (2024), bisnis dikatakan terkait apabila rantai nilainya memperlihatkan kesamaan lintas bisnis yang bernilai secara kompetitif, sedangkan bisnis tidak terkait memiliki rantai nilai dan kebutuhan sumber daya yang berbeda tanpa hubungan lintas bisnis yang berarti. Dari definisi tersebut dapat disimpulkan bahwa keterkaitan tidak diukur dari kemiripan produk secara kasat mata, melainkan dari ada tidaknya kecocokan strategis pada aktivitas rantai nilai dan sumber daya yang digunakan.</p>
<h5>8.5.1 Konsep Kecocokan Strategis Lintas Bisnis</h5>
<p>Kecocokan strategis (<em>strategic fit</em>) terjadi ketika rantai nilai bisnis yang berbeda memberikan peluang penciptaan nilai lintas bisnis. Peluang tersebut muncul dalam beberapa bentuk, yaitu: transfer keahlian khusus, pengetahuan teknologi, atau kapabilitas bernilai lain dari satu bisnis ke bisnis lain; penggabungan aktivitas rantai nilai yang serupa untuk mencapai biaya yang lebih rendah; pemanfaatan bersama nama merek yang kuat dan sumber daya lain yang mendukung diferensiasi; serta kolaborasi lintas bisnis untuk membangun kapabilitas bersaing baru yang bernilai (Thompson et al., 2024). Kecocokan strategis dapat ditemukan di sepanjang rantai nilai, mulai dari riset dan pengembangan serta teknologi, aktivitas rantai pasokan, manufaktur, penjualan dan pemasaran, distribusi, sampai layanan pelanggan, dan juga pada aktivitas pendukung seperti sistem administrasi dan manajemen sumber daya manusia. Buku memberikan contoh Inditex yang membangun portofolio merek busana seperti Zara dan Massimo Dutti di atas kapabilitas rantai pasokan cepat yang sama, News Corp pada rumpun media, serta Kimberly-Clark pada produk berbasis kertas dan perawatan pribadi.</p>
<h5>8.5.2 Skala Ekonomi dan Cakupan Ekonomi</h5>
<p>Manfaat biaya dari kecocokan strategis dikenal sebagai cakupan ekonomi (<em>economies of scope</em>), yaitu penurunan biaya yang timbul karena beberapa bisnis berbagi teknologi, fasilitas, sumber daya, atau kapabilitas yang sama di bawah satu korporasi. Konsep ini berbeda dari skala ekonomi (<em>economies of scale</em>) yang merupakan penurunan biaya per unit akibat peningkatan volume operasi satu bisnis. Cakupan ekonomi bersumber langsung dari lingkup operasi multibisnis, sehingga hanya dapat dinikmati perusahaan terdiversifikasi yang bisnis-bisnisnya memiliki keterkaitan rantai nilai (Thompson et al., 2024). Sebagai contoh di Indonesia, Indofood memanfaatkan cakupan ekonomi antara bisnis tepung terigu Bogasari, mi instan, dan distribusi, karena bahan baku, kapabilitas manufaktur pangan, jaringan distribusi, dan kekuatan merek dapat digunakan bersama lintas kategori produk. Demikian pula Wings Group membagi jaringan distribusi dan kapabilitas pemasaran produk konsumen antara lini deterjen dan lini makanan serta minuman.</p>
<p>Untuk memperjelas letak peluang kecocokan strategis, Tabel 8.1 menyajikan sintesis jenis kecocokan strategis di sepanjang rantai nilai beserta mekanisme penciptaan nilainya.</p>
<table class="bk-table"><caption>Tabel 8.1 Kecocokan Strategis di Sepanjang Rantai Nilai dan Mekanisme Penciptaan Nilainya</caption>
<thead><tr><th>Wilayah Rantai Nilai</th><th>Bentuk Kecocokan Strategis</th><th>Mekanisme Penciptaan Nilai</th></tr></thead>
<tbody>
<tr><td>Riset dan pengembangan serta teknologi</td><td>Berbagi teknologi dan menggabungkan kegiatan R&amp;D</td><td>Penghematan biaya pengembangan, percepatan inovasi produk lintas bisnis</td></tr>
<tr><td>Rantai pasokan</td><td>Penggabungan pembelian bahan baku dan logistik masuk</td><td>Daya tawar lebih besar terhadap pemasok, biaya pengadaan lebih rendah</td></tr>
<tr><td>Manufaktur</td><td>Transfer praktik produksi unggul, berbagi fasilitas produksi</td><td>Peningkatan kualitas dan produktivitas, utilisasi kapasitas lebih tinggi</td></tr>
<tr><td>Penjualan dan pemasaran</td><td>Pemakaian bersama tenaga penjualan, saluran promosi, dan merek payung</td><td>Biaya penjualan per unit lebih rendah, diferensiasi diperkuat reputasi merek</td></tr>
<tr><td>Distribusi</td><td>Pemakaian bersama pusat distribusi dan jaringan dealer</td><td>Biaya logistik keluar lebih rendah, jangkauan pasar lebih luas</td></tr>
<tr><td>Layanan pelanggan</td><td>Pemakaian bersama infrastruktur layanan purnajual</td><td>Kepuasan pelanggan meningkat dengan biaya layanan lebih efisien</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson, Peteraf, Gamble dan Strickland (2024)</td></tfoot>
</table>
<h5>8.5.3 Kecocokan Strategis sebagai Sumber Keunggulan Bersaing dan Nilai Pemegang Saham</h5>
<p>Kecocokan strategis, cakupan ekonomi, dan keunggulan bersaing memiliki hubungan berjenjang. Semakin besar keterkaitan antarbisnis perusahaan terdiversifikasi, semakin besar peluang mengubah kecocokan strategis menjadi keunggulan bersaing melalui biaya yang lebih rendah, transfer keahlian dan kapabilitas, pemanfaatan merek bersama, atau penciptaan kapabilitas baru. Terdapat beberapa hal yang perlu diperhatikan, yaitu manfaat kecocokan strategis hanya terwujud apabila peluang tersebut benar-benar dieksploitasi melalui koordinasi nyata, manfaatnya harus melebihi biaya koordinasi lintas bisnis, dan keunggulan yang dihasilkan sulit ditiru pesaing yang tidak memiliki portofolio serupa (Thompson et al., 2024). Diversifikasi terkait yang dikelola dengan baik merupakan jalur yang paling meyakinkan untuk menghasilkan efek 1 + 1 = 3, sehingga sekaligus memenuhi uji menjadi lebih baik. Implikasi manajerialnya adalah manajer korporat harus secara aktif membangun mekanisme koordinasi, insentif, dan struktur organisasi yang memfasilitasi realisasi sinergi, karena kecocokan strategis di atas kertas tidak dengan sendirinya menjadi keunggulan bersaing.</p>`
    },
    {
      no: "8.6",
      title: "Diversifikasi ke Bisnis Tidak Terkait",
      body: `<p>Strategi diversifikasi tidak terkait dijalankan perusahaan yang bersedia memasuki industri apa pun yang menjanjikan keuntungan finansial menarik, tanpa mensyaratkan adanya kecocokan strategis lintas bisnis. Perusahaan semacam ini sering disebut konglomerat. Menurut Thompson et al. (2024), perusahaan yang menempuh jalur ini tetap harus memastikan setiap bisnis yang dimasuki lulus uji daya tarik industri dan uji biaya masuk, sedangkan uji menjadi lebih baik dipenuhi bukan melalui sinergi rantai nilai, melainkan melalui kemampuan korporat menumbuhkan nilai pada bisnis-bisnis yang tidak berhubungan. Contoh klasiknya adalah Berkshire Hathaway dan Tata Group, sedangkan pada konteks Indonesia dapat dilihat pada Astra International yang membentang dari otomotif, jasa keuangan, alat berat dan pertambangan, agribisnis, infrastruktur, sampai teknologi informasi.</p>
<h5>8.6.1 Membangun Nilai Pemegang Saham melalui Diversifikasi Tidak Terkait</h5>
<p>Nilai pada diversifikasi tidak terkait diciptakan melalui apa yang disebut keunggulan pengasuhan korporat (<em>parenting advantage</em>), yaitu situasi ketika suatu korporasi mampu menambah nilai lebih besar kepada bisnis-bisnisnya dibandingkan induk korporat lain mana pun. Terdapat tiga mekanisme utama penciptaan nilai tersebut. Pertama, pengasuhan korporat yang cerdas (<em>astute corporate parenting</em>), berupa penyediaan pengawasan tingkat tinggi, disiplin keuangan, bimbingan pemecahan masalah kepada manajer unit bisnis, serta penyediaan sumber daya korporat bernilai seperti reputasi, keahlian manajerial, dan merek payung (<em>umbrella brand</em>) yang dapat dipakai lintas bisnis, sebagaimana nama Tata digunakan pada berbagai industri. Kedua, alokasi sumber daya keuangan lintas bisnis, ketika korporasi berperan sebagai pasar modal internal (<em>internal capital market</em>) yang memindahkan dana dari bisnis penghasil kas berlebih ke bisnis yang membutuhkan modal dan berprospek tinggi, suatu peran yang bernilai terutama ketika pasar modal eksternal tidak efisien. Ketiga, akuisisi dan restrukturisasi perusahaan yang dinilai terlalu murah (<em>undervalued companies</em>), yaitu membeli perusahaan dengan harga di bawah nilai wajarnya, memperbaiki operasinya, kemudian mengelolanya secara menguntungkan atau menjualnya kembali dengan harga lebih tinggi (Thompson et al., 2024).</p>
<h5>8.6.2 Kelemahan dan Risiko Diversifikasi Tidak Terkait</h5>
<p>Jalur tidak terkait mengandung dua kelemahan besar. Pertama, tuntutan manajerial yang sangat berat, karena semakin banyak dan semakin beragam bisnis dalam portofolio, semakin sulit eksekutif korporat memahami kondisi setiap industri, menilai kualitas rencana strategis manajer unit, dan mengetahui masalah sejak dini. Kesalahan penilaian atas daya tarik industri sasaran atau kesulitan tersembunyi perusahaan yang diakuisisi dapat menimbulkan kerugian besar. Kedua, potensi keunggulan bersaingnya terbatas, karena tanpa kecocokan strategis lintas bisnis, tidak ada sumber sinergi rantai nilai; nilai tambah sepenuhnya bergantung pada keahlian pengasuhan eksekutif korporat, sehingga efek yang dicapai sering kali hanya 1 + 1 = 2 (Thompson et al., 2024). Oleh karena itu, banyak konglomerat diperdagangkan dengan diskon konglomerasi di pasar modal ketika investor meragukan kemampuan pengasuhan induknya.</p>
<h5>8.6.3 Alasan Keliru dalam Diversifikasi Tidak Terkait</h5>
<p>Thompson et al. (2024) mengingatkan beberapa alasan yang keliru untuk berdiversifikasi tidak terkait, yaitu: penyebaran risiko semata, karena pemegang saham dapat melakukannya sendiri dengan biaya lebih murah; pengejaran pertumbuhan demi ukuran perusahaan semata, karena pertumbuhan tanpa profitabilitas tidak menciptakan nilai; stabilisasi laba antarsiklus bisnis, yang dalam praktik jarang terbukti efektif; serta motif kepentingan pribadi manajerial, seperti prestise, kompensasi yang lebih besar, dan keamanan jabatan. Dengan demikian, satu-satunya justifikasi yang sahih tetaplah peningkatan nilai pemegang saham dalam jangka panjang.</p>
<h5>8.6.4 Strategi Diversifikasi Kombinasi</h5>
<p>Dalam praktik, perusahaan tidak harus memilih secara mutlak salah satu jalur. Terdapat perusahaan dengan bisnis dominan yang menyumbang mayoritas pendapatan disertai beberapa bisnis kecil, perusahaan yang terdiversifikasi secara sempit pada sedikit bisnis, perusahaan yang terdiversifikasi secara luas, serta perusahaan multibisnis yang menggabungkan beberapa kelompok bisnis terkait dengan bisnis lain yang tidak terkait (Thompson et al., 2024). Pilihan kombinasi tersebut bergantung pada selera risiko, ambisi pertumbuhan, dan kapabilitas pengasuhan yang dimiliki manajemen korporat.</p>`
    },
    {
      no: "8.7",
      title: "Evaluasi Strategi Perusahaan Terdiversifikasi: Enam Langkah Analisis",
      body: `<p>Analisis strategi perusahaan yang telah terdiversifikasi menggunakan konsep dan teknik yang serupa dengan analisis perusahaan bisnis tunggal, namun ditambah prosedur khusus untuk menilai portofolio secara keseluruhan. Menurut Thompson et al. (2024), evaluasi strategi perusahaan terdiversifikasi dilakukan melalui enam langkah yang berurutan, mulai dari penilaian daya tarik industri sampai perumusan langkah strategis baru. Keenam langkah tersebut diuraikan sebagai berikut.</p>
<h5>8.7.1 Langkah 1: Menilai Daya Tarik Industri</h5>
<p>Langkah pertama adalah menilai daya tarik jangka panjang setiap industri tempat perusahaan beroperasi, baik secara individual maupun sebagai satu kelompok. Penilaian dilakukan dengan metode skor tertimbang: manajemen memilih ukuran daya tarik seperti ukuran pasar dan proyeksi pertumbuhan, intensitas persaingan, peluang dan ancaman yang muncul, kecocokan strategis lintas industri, kebutuhan sumber daya, serta ketidakpastian dan risiko industri; memberi bobot kepentingan pada setiap ukuran dengan jumlah bobot 1,00; memberi peringkat setiap industri pada skala 1 sampai 10 untuk tiap ukuran; kemudian menghitung skor dengan rumus: skor daya tarik industri = jumlah dari (bobot ukuran dikalikan peringkat industri pada ukuran tersebut). Industri dengan skor di atas 5,0 dipandang cukup menarik, sedangkan skor jauh di bawah 5,0 menandakan industri yang kurang layak dipertahankan (Thompson et al., 2024).</p>
<h5>8.7.2 Langkah 2: Menilai Kekuatan Bersaing Unit Bisnis</h5>
<p>Langkah kedua adalah menilai kekuatan bersaing setiap unit bisnis dalam industrinya masing-masing dengan metode skor tertimbang yang sama. Ukuran yang lazim digunakan meliputi pangsa pasar relatif, biaya relatif terhadap pesaing, kemampuan menandingi pesaing pada atribut produk kunci, kekuatan merek dan reputasi, kemampuan tawar-menawar, tingkat keuntungan relatif, serta kecocokan sumber daya unit dengan faktor kunci sukses industri. Pangsa pasar relatif dihitung dengan rumus: pangsa pasar relatif = pangsa pasar unit bisnis dibagi pangsa pasar pesaing terbesar di industri tersebut, sehingga nilai lebih besar dari 1,0 hanya dimiliki pemimpin pasar. Hasil kedua langkah pertama kemudian dipetakan pada matriks sembilan sel daya tarik industri dan kekuatan bersaing (<em>nine-cell industry attractiveness-competitive strength matrix</em>), dengan daya tarik industri pada sumbu vertikal dan kekuatan bersaing pada sumbu horizontal, masing-masing dibagi menjadi tinggi, sedang, dan rendah. Unit yang berada pada tiga sel kiri atas berprioritas tinggi untuk alokasi sumber daya, unit pada sel diagonal berprioritas menengah, dan unit pada tiga sel kanan bawah menjadi kandidat divestasi (Thompson et al., 2024).</p>
<h5>8.7.3 Langkah 3: Menilai Nilai Kompetitif Kecocokan Strategis Lintas Bisnis</h5>
<p>Langkah ketiga adalah memeriksa seberapa besar nilai kompetitif yang dapat diperoleh dari kecocokan strategis antarunit bisnis. Pemeriksaan dilakukan dengan menelusuri rantai nilai setiap unit dan mengidentifikasi peluang penggabungan aktivitas, transfer kapabilitas, pemakaian merek bersama, dan kolaborasi lintas unit, sebagaimana dijelaskan pada sub-bab 8.5. Langkah ini terutama penting bagi perusahaan yang mengklaim menjalankan diversifikasi terkait, karena tanpa bukti kecocokan strategis yang bernilai, klaim tersebut tidak berdasar (Thompson et al., 2024).</p>
<h5>8.7.4 Langkah 4: Memeriksa Kecocokan Sumber Daya</h5>
<p>Langkah keempat adalah menguji apakah kebutuhan sumber daya seluruh bisnis sesuai dengan sumber daya keuangan dan nonkeuangan yang dimiliki korporasi. Pada dimensi keuangan, analisis menggunakan konsep pasar modal internal serta pembedaan antara bisnis penyedot kas (<em>cash hog</em>), yaitu bisnis yang arus kas internalnya tidak cukup untuk mendanai kebutuhan modal kerjanya dan investasi pertumbuhannya, dan bisnis sapi perah kas (<em>cash cow</em>), yaitu bisnis yang menghasilkan arus kas jauh melebihi kebutuhan investasinya sendiri. Portofolio yang sehat memiliki cukup bisnis sapi perah untuk mendanai bisnis penyedot kas yang berprospek baik, di samping menyisakan dana untuk dividen, pembelian kembali saham, dan pembayaran utang. Pada dimensi nonkeuangan, perusahaan harus memastikan kapabilitas manajerial, teknologi, dan organisasionalnya tidak terentang terlalu tipis oleh jumlah dan keragaman bisnis (Thompson et al., 2024).</p>
<h5>8.7.5 Langkah 5: Menyusun Peringkat Prospek dan Prioritas Alokasi Sumber Daya</h5>
<p>Langkah kelima adalah memeringkat prospek kinerja setiap bisnis dari yang terbaik sampai yang terburuk berdasarkan pertumbuhan penjualan, pertumbuhan laba, kontribusi terhadap laba perusahaan, imbal hasil atas modal yang digunakan, dan arus kas, kemudian menetapkan prioritas alokasi sumber daya. Bisnis dengan prospek terbaik memperoleh prioritas investasi tertinggi, sedangkan bisnis berprospek lemah menjadi kandidat perbaikan, panen (<em>harvest</em>), atau divestasi. Opsi penggunaan dana korporat mencakup opsi strategis, seperti investasi untuk memperkuat unit yang ada dan akuisisi baru, serta opsi keuangan, seperti pembayaran dividen, pembelian kembali saham, dan pelunasan utang (Thompson et al., 2024).</p>
<h5>8.7.6 Langkah 6: Merumuskan Langkah Strategis Baru</h5>
<p>Langkah keenam adalah merumuskan langkah strategis baru untuk memperbaiki kinerja korporasi secara keseluruhan. Langkah ini menghubungkan hasil kelima langkah analisis sebelumnya dengan empat opsi utama strategi korporat yang dibahas pada sub-bab 8.8. Dengan demikian, keenam langkah tersebut membentuk kerangka evaluasi yang utuh, mulai dari diagnosis portofolio sampai preskripsi tindakan, dan sebaiknya dilakukan secara berkala mengingat daya tarik industri dan posisi bersaing unit bisnis terus berubah.</p>`
    },
    {
      no: "8.8",
      title: "Empat Opsi Strategi Korporat untuk Memperbaiki Kinerja Perusahaan Terdiversifikasi",
      body: `<p>Setelah portofolio dievaluasi, manajemen korporat memiliki empat opsi utama untuk memperbaiki kinerja perusahaan terdiversifikasi (Thompson et al., 2024). Keempat opsi tersebut beserta kondisi penggunaannya disajikan secara ringkas pada Tabel 8.2, kemudian diuraikan pada paragraf berikutnya.</p>
<table class="bk-table"><caption>Tabel 8.2 Empat Opsi Strategi Korporat Perusahaan Terdiversifikasi</caption>
<thead><tr><th>Opsi Strategi</th><th>Inti Tindakan</th><th>Kondisi yang Sesuai</th></tr></thead>
<tbody>
<tr><td>Bertahan pada susunan bisnis yang ada</td><td>Memusatkan sumber daya pada peluang pertumbuhan bisnis yang telah dimiliki</td><td>Portofolio saat ini menawarkan prospek pertumbuhan dan laba yang menarik</td></tr>
<tr><td>Memperluas basis diversifikasi</td><td>Mengakuisisi bisnis baru pada industri terkait maupun tidak terkait</td><td>Pertumbuhan melambat, peluang transfer kapabilitas tersedia, atau posisi bisnis inti perlu diperkuat</td></tr>
<tr><td>Divestasi dan penciutan basis diversifikasi</td><td>Melepas bisnis yang berkinerja lemah atau tidak lagi sesuai arah jangka panjang</td><td>Terlalu banyak bisnis mengalihkan perhatian manajemen atau tidak memiliki kecocokan strategis dan sumber daya</td></tr>
<tr><td>Restrukturisasi menyeluruh portofolio</td><td>Kombinasi divestasi besar dan akuisisi baru untuk membentuk wajah portofolio yang baru</td><td>Kinerja keseluruhan buruk, terlalu banyak bisnis lemah, atau perubahan besar kondisi industri</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson, Peteraf, Gamble dan Strickland (2024)</td></tfoot>
</table>
<p>Opsi pertama, bertahan erat pada susunan bisnis yang ada, masuk akal apabila portofolio saat ini masih menawarkan peluang pertumbuhan yang menarik dan mampu menciptakan nilai ekonomi bagi pemegang saham. Opsi kedua, memperluas basis diversifikasi, ditempuh dengan mengakuisisi bisnis tambahan yang melengkapi dan memperkuat posisi pasar bisnis yang ada, misalnya ketika pertumbuhan bisnis inti melambat, ketika kapabilitas perusahaan dapat ditransfer ke bisnis baru, atau ketika perubahan teknologi membuka arena yang berdekatan. Opsi ketiga, divestasi dan penciutan ke basis diversifikasi yang lebih sempit, dilakukan dengan melepas bisnis yang berkinerja buruk atau tidak lagi cocok, agar sumber daya korporat terpusat pada sedikit bisnis inti yang dipilih secara cermat. Divestasi dapat berbentuk penjualan kepada pihak lain maupun pemisahan menjadi perusahaan independen (<em>spin-off</em>). Opsi keempat, restrukturisasi menyeluruh (<em>corporate restructuring</em>), melibatkan kombinasi radikal antara divestasi sejumlah bisnis dan akuisisi bisnis baru sehingga komposisi portofolio berubah secara substansial, biasanya dipicu kinerja yang jauh di bawah harapan, beban utang yang berat, atau kemunculan teknologi dan pasar baru yang menuntut perombakan arah (Thompson et al., 2024).</p>
<p>Sebagai ilustrasi konteks Indonesia, keputusan Grup Salim dan sejumlah konglomerasi nasional memfokuskan kembali portofolionya setelah krisis moneter 1998 mencerminkan opsi penciutan dan restrukturisasi, sedangkan langkah Astra International menambah lini bisnis infrastruktur dan ekonomi digital pada dekade terakhir mencerminkan opsi perluasan basis diversifikasi. Implikasi manajerialnya adalah pemilihan opsi tidak boleh didasarkan pada preferensi pribadi eksekutif, melainkan pada hasil enam langkah evaluasi portofolio, khususnya perbandingan prospek kinerja tiap unit dan ketersediaan sumber daya korporat.</p>`
    },
    {
      no: "8.9",
      title: "Rangkuman",
      body: `<p>Strategi korporat perusahaan multibisnis berpusat pada tiga tugas, yaitu memilih industri baru beserta moda masuknya, mengubah kecocokan strategis lintas bisnis menjadi keunggulan bersaing, dan memperbaiki kinerja gabungan portofolio. Diversifikasi hanya dapat dibenarkan apabila menambah nilai pemegang saham jangka panjang, yang diuji melalui uji daya tarik industri, uji biaya masuk, dan uji menjadi lebih baik. Moda masuk ke bisnis baru dapat berupa akuisisi, pengembangan internal, atau usaha patungan, dan pilihannya bergantung pada kelengkapan sumber daya, tinggi rendahnya hambatan masuk, kebutuhan kecepatan, serta pertimbangan biaya transaksi.</p>
<p>Diversifikasi terkait menciptakan nilai melalui kecocokan strategis di sepanjang rantai nilai yang menghasilkan cakupan ekonomi, transfer kapabilitas, pemanfaatan merek bersama, dan kolaborasi lintas bisnis, sehingga berpotensi menghasilkan efek sinergi 1 + 1 = 3. Diversifikasi tidak terkait menciptakan nilai melalui keunggulan pengasuhan korporat, alokasi dana pada pasar modal internal, dan restrukturisasi perusahaan yang dinilai terlalu murah, namun menghadapi tuntutan manajerial yang berat dan potensi keunggulan bersaing yang terbatas. Evaluasi strategi perusahaan terdiversifikasi dilakukan melalui enam langkah, yaitu menilai daya tarik industri, menilai kekuatan bersaing unit bisnis, memeriksa nilai kompetitif kecocokan strategis, memeriksa kecocokan sumber daya, memeringkat prospek dan prioritas alokasi sumber daya, serta merumuskan langkah strategis baru.</p>
<p>Pada akhirnya, manajemen korporat memiliki empat opsi untuk memperbaiki kinerja, yaitu bertahan pada susunan bisnis yang ada, memperluas basis diversifikasi, melakukan divestasi untuk menciutkan basis diversifikasi, atau merestrukturisasi portofolio secara menyeluruh. Dengan demikian, keberhasilan perusahaan multibisnis tidak ditentukan oleh banyaknya bisnis yang dimiliki, melainkan oleh disiplin manajemen dalam memastikan setiap bisnis lulus ketiga uji keunggulan korporat dan oleh kemampuan korporasi menambah nilai kepada bisnis-bisnisnya melebihi induk korporat lain.</p>`
    },
    {
      no: "8.10",
      title: "Daftar Pustaka",
      body: `<p>Thompson, A. A., Peteraf, M. A., Gamble, J. E. dan Strickland, A. J. (2024). <em>Crafting and Executing Strategy: The Quest for Competitive Advantage, Concepts and Cases</em>. 2024 Release. New York: McGraw Hill.</p>
<p>Porter, M. E. (1987). From Competitive Advantage to Corporate Strategy. <em>Harvard Business Review</em>, 65(3), 43-59.</p>
<p>Campbell, A., Goold, M. dan Alexander, M. (1995). Corporate Strategy: The Quest for Parenting Advantage. <em>Harvard Business Review</em>, 73(2), 120-132.</p>`
    }
  ]
};
