window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.sm = window.MBA_BOOK.sm || {};
window.MBA_BOOK.sm[10] = {
  bab: 10,
  judul: "BAB 10 MENGELOLA OPERASI INTERNAL: TINDAKAN YANG MENDUKUNG EKSEKUSI STRATEGI YANG BAIK",
  sumber: "Thompson, Peteraf, Gamble dan Strickland (2024), Crafting and Executing Strategy, 2024 Release, McGraw Hill",
  lo: [
    "LO 11-1 Menjelaskan mengapa alokasi sumber daya harus selalu didasarkan pada prioritas strategis.",
    "LO 11-2 Memahami bagaimana kebijakan dan prosedur yang dirancang dengan baik dapat memfasilitasi eksekusi strategi yang baik.",
    "LO 11-3 Memahami bagaimana perangkat manajemen proses mendorong perbaikan berkelanjutan dalam pelaksanaan aktivitas rantai nilai.",
    "LO 11-4 Mengenali peran sistem informasi dan sistem operasi dalam memampukan personel perusahaan menjalankan peran strategisnya secara cakap.",
    "LO 11-5 Menjelaskan bagaimana dan mengapa penggunaan insentif yang dirancang dengan baik dapat menjadi alat manajemen yang paling ampuh untuk mendorong keunggulan operasi."
  ],
  sections: [
    {
      no: "10.1",
      title: "Capaian Pembelajaran",
      body: `<p>Pada sesi sebelumnya telah dibahas bahwa eksekusi strategi yang cakap diawali dengan tiga tindakan manajerial, yaitu penempatan orang yang tepat, pembangunan sumber daya dan kapabilitas organisasi, serta penataan struktur organisasi yang mendukung strategi. Sesi ini melanjutkan pembahasan tersebut dengan menguraikan lima tindakan manajerial tambahan yang mendorong eksekusi strategi yang baik menurut Thompson, Peteraf, Gamble dan Strickland (2024), yaitu mengalokasikan sumber daya yang memadai bagi upaya eksekusi strategi, menetapkan kebijakan dan prosedur yang memfasilitasi eksekusi strategi, menggunakan perangkat manajemen proses untuk mendorong perbaikan berkelanjutan, memasang sistem informasi dan sistem operasi yang mendukung implementasi strategi, serta mengaitkan penghargaan dan insentif dengan pencapaian sasaran kinerja. Kelima tindakan tersebut menyentuh sisi operasi internal perusahaan sehingga strategi yang telah dirumuskan dapat diterjemahkan menjadi hasil operasi yang nyata.</p>
      <p>Setelah mengikuti sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <p><strong>LO 11-1</strong> Menjelaskan mengapa alokasi sumber daya harus selalu didasarkan pada prioritas strategis. <strong>LO 11-2</strong> Memahami bagaimana kebijakan dan prosedur yang dirancang dengan baik dapat memfasilitasi eksekusi strategi yang baik. <strong>LO 11-3</strong> Memahami bagaimana perangkat manajemen proses mendorong perbaikan berkelanjutan dalam pelaksanaan aktivitas rantai nilai. <strong>LO 11-4</strong> Mengenali peran sistem informasi dan sistem operasi dalam memampukan personel perusahaan menjalankan peran strategisnya secara cakap. <strong>LO 11-5</strong> Menjelaskan bagaimana dan mengapa insentif yang dirancang dengan baik dapat menjadi alat manajemen yang paling ampuh untuk mendorong keunggulan operasi.</p>`
    },
    {
      no: "10.2",
      title: "Alokasi Sumber Daya untuk Upaya Eksekusi Strategi",
      body: `<p>Setiap strategi hanya dapat dijalankan apabila unit organisasi yang menanggung beban eksekusi memperoleh dana, orang, peralatan dan fasilitas yang memadai. Menurut Thompson et al. (2024), pada tahap awal implementasi strategi manajer harus menentukan sumber daya apa saja yang dibutuhkan dan bagaimana sumber daya tersebut didistribusikan ke berbagai unit organisasi, termasuk menyaring secara cermat setiap usulan penambahan orang, fasilitas dan peralatan, menyetujui usulan yang berkontribusi pada eksekusi strategi, dan menolak usulan yang tidak berkontribusi. Apabila arus kas internal tidak mencukupi untuk mendanai inisiatif strategis, manajemen perlu menghimpun dana tambahan melalui pinjaman atau penerbitan saham. Dengan demikian, prinsip pokok pada bagian ini adalah bahwa prioritas strategis perusahaan harus menjadi dasar bagi keputusan alokasi modal dan besaran anggaran operasi setiap unit.</p>
      <p>Kekurangan maupun kelebihan pendanaan sama-sama merugikan upaya eksekusi strategi. Pendanaan yang terlalu kecil memperlambat kemajuan dan menghambat kemampuan unit organisasi melaksanakan bagiannya dari rencana strategis, sedangkan pendanaan yang berlebihan pada unit atau aktivitas rantai nilai tertentu memboroskan sumber daya organisasi dan menurunkan kinerja keuangan (Thompson et al., 2024). Oleh karena itu, manajer dituntut terlibat secara mendalam dalam menelaah usulan anggaran serta mengarahkan jenis dan jumlah sumber daya yang tepat ke unit-unit yang kritikal bagi strategi. Perubahan strategi hampir selalu menuntut realokasi anggaran dan pemindahan sumber daya, dalam arti unit yang perannya mengecil dalam strategi baru mungkin perlu dirampingkan, sementara unit yang peran strategisnya membesar memerlukan tambahan orang, peralatan baru, fasilitas tambahan dan kenaikan anggaran operasi di atas rata-rata. Manajer juga harus berani mengambil keputusan sulit untuk menghentikan proyek dan aktivitas yang tidak lagi dapat dibenarkan secara strategis.</p>
      <p>Tindakan yang terlihat nyata dalam merealokasikan dana operasi dan memindahkan orang ke unit baru memberikan sinyal komitmen yang sungguh-sungguh terhadap perubahan strategis sehingga mempercepat proses implementasi dan memberikan kredibilitas. Thompson et al. (2024) mencontohkan Microsoft yang terbiasa memindahkan ratusan pemrogram ke inisiatif prioritas tinggi dalam hitungan hari sampai minggu, serta keputusan Google pada tahun 2013 menghentikan kebijakan <em>20 percent time</em> agar sumber daya lebih terkonsentrasi pada proyek yang dekat dengan inti misinya. Perkembangan pasar yang cepat juga mendorong banyak perusahaan meninggalkan siklus anggaran tahunan tradisional dan beralih ke proses alokasi sumber daya yang memungkinkan penyesuaian strategi secara lebih cepat. Dalam konteks Indonesia, Telkom Indonesia mengalihkan belanja modalnya dari bisnis <em>legacy</em> seperti telepon tetap ke infrastruktur digital berupa pusat data, konektivitas <em>broadband</em> dan platform digital sejalan dengan strategi transformasinya, yang menunjukkan bahwa realokasi sumber daya merupakan wujud paling konkret dari perubahan prioritas strategis.</p>
      <p>Namun, tidak semua situasi menuntut pergeseran sumber daya berskala besar. Penyempurnaan eksekusi atas strategi yang sudah berjalan jarang memerlukan perpindahan dana yang besar antarunit, sedangkan inisiatif strategis baru umumnya menuntut pergeseran sekaligus penambahan alokasi sumber daya. Terdapat pula keadaan ketika perubahan strategi harus dilakukan tanpa menambah total biaya perusahaan, sehingga manajer harus menelusuri anggaran baris demi baris dan aktivitas demi aktivitas untuk menemukan penghematan yang dapat dialihkan ke aktivitas berprioritas lebih tinggi. Implikasi manajerialnya adalah bahwa kemampuan melakukan lebih banyak hal dengan sumber daya yang lebih sedikit menjadi bagian tidak terpisahkan dari eksekusi strategi, karena dorongan eksekusi yang baik sering diarahkan sekaligus pada efisiensi operasi yang lebih tinggi dan efektivitas aktivitas rantai nilai yang paling penting.</p>`
    },
    {
      no: "10.3",
      title: "Kebijakan dan Prosedur yang Memfasilitasi Eksekusi Strategi",
      body: `<p>Kebijakan dan prosedur perusahaan dapat mendukung ataupun menghambat eksekusi strategi yang baik. Setiap kali perusahaan memasang elemen strategi baru atau berupaya memperbaiki kapabilitas eksekusinya, biasanya diperlukan perubahan dalam praktik kerja, sehingga manajer perlu menilai apakah kebijakan dan prosedur yang ada sepenuhnya mendukung perubahan tersebut, lalu merevisi atau membuang aturan yang tidak mendukung (Thompson et al., 2024). Dengan demikian, kebijakan dan prosedur bukan sekadar kelengkapan administratif, melainkan instrumen manajerial yang mengarahkan perilaku sehari-hari personel agar sejalan dengan tuntutan strategi.</p>
      <p>Menurut Thompson et al. (2024), kebijakan dan prosedur yang dirancang dengan baik memfasilitasi eksekusi strategi melalui dua cara utama. Pertama, kebijakan memberikan panduan dari atas ke bawah mengenai bagaimana pekerjaan harus dilakukan. Panduan tersebut mengurangi ketidakpastian mengenai cara bertindak, menyelaraskan tindakan dan perilaku personel dengan persyaratan eksekusi strategi yang baik, membatasi tindakan independen yang tidak efektif, serta membantu mengatasi resistensi terhadap perubahan karena orang pada umumnya enggan melanggar kebijakan perusahaan tanpa izin atau justifikasi yang kuat. Kedua, kebijakan dan prosedur membantu memastikan konsistensi dalam pelaksanaan aktivitas yang kritikal bagi eksekusi. Prosedur menstandarkan cara kerja dan pada hakikatnya merupakan simpanan pengetahuan organisasi tentang cara kerja yang efisien dan efektif, berupa serangkaian rutinitas yang teruji untuk menjalankan perusahaan. Konsistensi tersebut sangat bernilai bagi perusahaan yang unit operasinya tersebar secara geografis, karena kualitas produk dan layanan pelanggan harus dapat direplikasi di setiap lokasi agar citra perusahaan tidak kabur dan kepuasan pelanggan tidak menurun.</p>
      <p>Contoh klasik yang dikemukakan Thompson et al. (2024) adalah manual kebijakan McDonald's yang merinci prosedur operasi setiap gerai, mulai dari cara membalik daging burger, batas waktu penyajian produk setelah dimasak, hingga keharusan kasir melakukan kontak mata dan tersenyum kepada pelanggan, semuanya demi konsistensi mutu produk dan pola perilaku layanan. Fenomena serupa dapat diamati pada jaringan ritel dan restoran di Indonesia. Indomaret dan Alfamart menstandarkan tata letak toko, prosedur kasir dan salam pelayanan di puluhan ribu gerai melalui pedoman operasi baku, sedangkan jaringan kedai seperti Kopi Kenangan menstandarkan resep, takaran dan alur penyajian agar rasa dan kecepatan layanan konsisten antargerai. Konsistensi semacam ini merupakan prasyarat strategi ekspansi berbasis jaringan, karena pelanggan menuntut pengalaman yang sama di lokasi mana pun.</p>
      <p>Di sisi lain, manajer perlu menghindari kebijakan yang berlebihan. Terlalu banyak kebijakan dapat mengekang kreativitas, memperlambat pengambilan keputusan dan menimbulkan birokrasi yang justru menghambat eksekusi, sementara terlalu sedikit kebijakan dapat menimbulkan kebingungan dan inkonsistensi. Beberapa perusahaan dengan sengaja memilih kebijakan yang longgar untuk memberdayakan karyawannya, sebagaimana Netflix yang menghindari prosedur formal yang kaku dan menggantinya dengan pedoman umum agar karyawan bertindak demi kepentingan terbaik perusahaan (Thompson et al., 2024). Oleh karena itu, isu manajerial yang sesungguhnya bukanlah banyak atau sedikitnya kebijakan, melainkan kesesuaian kebijakan dengan kebutuhan eksekusi strategi, yaitu cukup preskriptif pada aktivitas yang menuntut konsistensi dan cukup longgar pada aktivitas yang menuntut kreativitas dan penilaian mandiri.</p>`
    },
    {
      no: "10.4",
      title: "Perangkat Manajemen Proses Bisnis untuk Perbaikan Berkelanjutan",
      body: `<p>Eksekusi strategi yang unggul menuntut perusahaan terus memperbaiki cara pelaksanaan aktivitas rantai nilainya. Thompson et al. (2024) mengemukakan bahwa proses bisnis menopang kapabilitas organisasi, dan kapabilitas menopang eksekusi strategi, sehingga keunggulan operasi harus dikejar secara sistematis melalui perangkat manajemen proses. Terdapat tiga perangkat utama yang lazim digunakan untuk mendorong keunggulan operasi, yaitu <em>business process reengineering</em>, <em>total quality management</em> dan program <em>Six Sigma</em>, yang ketiganya biasanya diawali dengan aktivitas <em>benchmarking</em> untuk menemukan praktik terbaik.</p>
      <h5>10.4.1 Benchmarking dan Adopsi Best Practices</h5>
      <p><em>Benchmarking</em> adalah proses membandingkan cara perusahaan melaksanakan suatu aktivitas dengan cara pelaksanaan aktivitas serupa oleh perusahaan lain yang berkinerja terbaik, dengan tujuan mengidentifikasi kesenjangan kinerja dan cara menutupnya. Adapun <em>best practice</em> merupakan metode pelaksanaan suatu aktivitas yang secara konsisten memberikan hasil yang lebih unggul dibandingkan metode lain (Thompson et al., 2024). Mekanisme penggunaannya dimulai dengan mengukur kinerja aktivitas internal, mencari pembanding eksternal terbaik melalui studi banding, publikasi, konsultan atau organisasi seperti dewan produktivitas, kemudian mengadaptasi praktik terbaik tersebut ke dalam konteks perusahaan. Perlu ditekankan bahwa praktik terbaik jarang dapat disalin mentah-mentah, sehingga tugas manajer adalah menyesuaikan gagasan pokoknya dengan situasi spesifik perusahaan, lalu menanamkannya menjadi rutinitas baru. Dengan demikian, <em>benchmarking</em> berfungsi sebagai pintu masuk bagi ketiga perangkat perbaikan proses yang dibahas berikutnya.</p>
      <h5>10.4.2 Business Process Reengineering</h5>
      <p><em>Business process reengineering</em> adalah perancangan ulang secara radikal atas suatu proses bisnis dengan cara menyatukan pekerjaan yang semula terpecah di berbagai departemen ke dalam satu alur proses lintas fungsi, dengan sasaran perbaikan kinerja yang bersifat lompatan besar dalam biaya, mutu dan kecepatan (Thompson et al., 2024). Mekanismenya adalah memetakan proses dari ujung ke ujung, mempertanyakan alasan keberadaan setiap tahap, menghapus tahap yang tidak menambah nilai, lalu menata ulang pekerjaan dalam tim proses yang utuh dan sering kali didukung otomatisasi teknologi informasi. Sasaran perbaikan yang dikejar bukan perbaikan kecil bertahap, melainkan peningkatan dramatis, misalnya pemangkasan waktu siklus atau biaya proses hingga separuh atau lebih. Contoh penerapan di Indonesia adalah Bank BRI yang merekayasa ulang proses pemrakarsaan kredit mikro dari alur berkas manual berlapis menjadi proses digital melalui aplikasi BRISPOT, sehingga waktu persetujuan kredit yang semula berhari-hari dapat dipangkas menjadi hitungan jam. Implikasi manajerialnya adalah bahwa <em>reengineering</em> cocok digunakan ketika proses yang ada sudah usang secara mendasar dan perbaikan bertahap tidak lagi memadai.</p>
      <h5>10.4.3 Total Quality Management</h5>
      <p><em>Total quality management</em> (TQM) adalah filosofi pengelolaan seperangkat praktik bisnis yang menekankan perbaikan berkesinambungan pada semua fase operasi, ketepatan seratus persen dalam pelaksanaan tugas, pelibatan dan pemberdayaan karyawan di semua tingkat, desain kerja berbasis tim, penetapan tolok ukur terhadap praktik terbaik, serta pemenuhan ekspektasi pelanggan secara total (Thompson et al., 2024). Berbeda dengan <em>reengineering</em> yang mengejar lompatan sekali waktu, TQM menumbuhkan budaya perbaikan kecil yang terus-menerus, sebagaimana tercermin dalam konsep <em>kaizen</em> pada sistem produksi Jepang. Keberhasilan TQM memerlukan waktu panjang karena menuntut perubahan budaya, yaitu tumbuhnya obsesi terhadap mutu pada seluruh karyawan dan kesediaan setiap orang mencari cara kerja yang lebih baik setiap hari. Di Indonesia, Grup Astra melembagakan filosofi perbaikan berkesinambungan melalui sistem manajemen internal dan konvensi inovasi tahunan InnovAstra yang mendorong karyawan lini depan mengajukan proyek perbaikan mutu dan efisiensi, yang menunjukkan bahwa TQM berkembang subur apabila didukung mekanisme partisipasi karyawan yang melembaga.</p>
      <h5>10.4.4 Six Sigma</h5>
      <p>Program <em>Six Sigma</em> adalah metode peningkatan mutu berbasis statistik yang bertujuan menekan cacat hingga tidak lebih dari 3,4 cacat per satu juta kesempatan dengan cara mengurangi variabilitas proses (Thompson et al., 2024). Untuk memperbaiki proses yang sudah ada digunakan kerangka DMAIC, yaitu <em>define</em> (mendefinisikan masalah dan kebutuhan pelanggan), <em>measure</em> (mengukur kinerja proses saat ini), <em>analyze</em> (menganalisis akar penyebab variasi dan cacat), <em>improve</em> (memperbaiki proses dengan menghilangkan akar penyebab) dan <em>control</em> (mengendalikan proses agar perbaikan bertahan). Adapun untuk merancang proses atau produk baru digunakan kerangka DMADV, yaitu <em>define</em>, <em>measure</em>, <em>analyze</em>, <em>design</em> dan <em>verify</em>. Prinsip dasarnya adalah bahwa seluruh pekerjaan merupakan proses, seluruh proses memiliki variabilitas, dan seluruh proses menghasilkan data yang menjelaskan variabilitas tersebut, sehingga keputusan perbaikan harus berbasis data dan bukan dugaan. Thompson et al. (2024) mengilustrasikan penerapannya pada Charleston Area Medical Center yang menggunakan <em>Six Sigma</em> untuk mengendalikan biaya persediaan medis dan memperbaiki mutu layanan. Namun, manajer perlu menyadari bahwa disiplin <em>Six Sigma</em> yang menekan variasi dapat menghambat inovasi yang justru memerlukan eksperimen dan toleransi terhadap kegagalan, sehingga perusahaan yang strateginya bertumpu pada inovasi harus menerapkannya secara selektif pada proses rutin dan memberi ruang longgar pada aktivitas kreatif.</p>
      <h5>10.4.5 Perbandingan Perangkat dan Penangkapan Manfaat Inisiatif</h5>
      <p>Ketiga perangkat tersebut memiliki kesamaan tujuan, yaitu keunggulan operasi, dengan perbedaan pokok terletak pada skala dan ritme perbaikannya. Perbandingan ketiganya disajikan pada Tabel 10.1 sebagai berikut:</p>
      <table class="bk-table">
        <caption>Tabel 10.1 Perbandingan Business Process Reengineering, TQM dan Six Sigma</caption>
        <thead><tr><th>Aspek</th><th>Business Process Reengineering</th><th>Total Quality Management</th><th>Six Sigma</th></tr></thead>
        <tbody>
          <tr><td>Sifat perbaikan</td><td>Lompatan besar sekali waktu (radikal)</td><td>Bertahap dan berkesinambungan</td><td>Bertahap, berbasis proyek terstruktur</td></tr>
          <tr><td>Sasaran</td><td>Perbaikan dramatis biaya, mutu dan kecepatan proses</td><td>Budaya mutu total dan kepuasan pelanggan</td><td>Pengurangan cacat dan variabilitas proses</td></tr>
          <tr><td>Pendekatan</td><td>Desain ulang proses lintas fungsi dari nol</td><td>Pelibatan seluruh karyawan dalam perbaikan harian</td><td>Analisis statistik melalui DMAIC dan DMADV</td></tr>
          <tr><td>Jangka waktu</td><td>Proyek besar berdurasi terbatas</td><td>Berjalan terus tanpa titik akhir</td><td>Rangkaian proyek berkelanjutan</td></tr>
          <tr><td>Risiko utama</td><td>Gangguan besar dan resistensi organisasi</td><td>Hasil lambat terlihat</td><td>Dapat menghambat inovasi bila diterapkan berlebihan</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Thompson, Peteraf, Gamble dan Strickland (2024)</td></tr></tfoot>
      </table>
      <p>Urutan penggunaan yang lazim adalah menjalankan <em>reengineering</em> terlebih dahulu untuk menghasilkan desain proses yang baik, kemudian menggunakan TQM dan <em>Six Sigma</em> untuk menyempurnakan dan menjaga proses tersebut secara berkelanjutan. Selain itu, Thompson et al. (2024) menegaskan bahwa manfaat inisiatif perbaikan proses hanya dapat ditangkap secara penuh apabila inisiatif tersebut dikaitkan dengan prioritas strategis, bukan dijalankan sebagai program yang berdiri sendiri. Syarat keberhasilannya mencakup komitmen nyata manajemen puncak, penetapan indikator dan target perbaikan yang terukur, pemberian pelatihan dan wewenang kepada karyawan, pengakuan atas keberhasilan tim, serta penanaman hasil perbaikan ke dalam budaya keunggulan operasi. Tanpa keterkaitan dengan strategi, program mutu berisiko menjadi ritual administratif yang menyerap biaya tanpa memperkuat posisi bersaing perusahaan.</p>`
    },
    {
      no: "10.5",
      title: "Sistem Informasi dan Sistem Operasi Pendukung Strategi",
      body: `<p>Strategi perusahaan tidak dapat dieksekusi dengan baik tanpa sejumlah sistem pendukung bagi operasi bisnis. Sistem operasi yang canggih dan mutakhir tidak hanya memperkuat kapabilitas organisasi, melainkan juga dapat menjadi basis keunggulan kompetitif apabila memberi kemampuan yang tidak dapat ditandingi pesaing (Thompson et al., 2024). Contoh yang dikemukakan dalam buku antara lain sistem pelacakan paket pada perusahaan jasa kurir yang memungkinkan pemantauan kiriman secara waktu nyata, sistem reservasi dan penjadwalan pada maskapai, serta sistem pemantauan operasi berbasis data pada peritel daring. Dalam konteks Indonesia, aplikasi BRISPOT milik Bank BRI dan sistem pemantauan armada pada perusahaan logistik seperti J&T Express menunjukkan bahwa sistem operasi digital telah menjadi tulang punggung eksekusi strategi pada industri jasa yang padat transaksi.</p>
      <h5>10.5.1 Sistem Informasi, Pelacakan Kinerja dan Pengendalian</h5>
      <p>Informasi yang akurat dan tepat waktu merupakan prasyarat bagi manajer untuk memantau kemajuan eksekusi strategi dan melakukan tindakan korektif secara dini. Menurut Thompson et al. (2024), sistem informasi perusahaan perlu mencakup lima bidang data yang luas, yaitu data pelanggan, data operasi, data karyawan, data pemasok dan mitra, serta data kinerja keuangan. Kelima jenis data tersebut idealnya tersedia secara <em>real time</em> agar manajer dapat memantau indikator kinerja utama, mendeteksi penyimpangan dari target, dan turun tangan sebelum masalah membesar. Mekanisme pemantauan kinerja yang baik mengikuti prinsip bahwa apa yang diukur akan dikelola, sehingga indikator yang dipantau harus diturunkan dari sasaran strategis, dipantau pada frekuensi yang memadai, dan ditautkan dengan tanggung jawab manajer tertentu. Selain itu, sistem informasi juga berfungsi sebagai alat pengendalian, karena data kinerja yang transparan memungkinkan deteksi dini atas perilaku menyimpang, pemborosan biaya dan penurunan mutu di unit mana pun.</p>
      <h5>10.5.2 Pengendalian atas Karyawan yang Diberdayakan</h5>
      <p>Pemberdayaan karyawan menimbulkan dilema pengendalian, yaitu bagaimana memastikan keputusan karyawan yang diberi keleluasaan tetap sejalan dengan kepentingan perusahaan tanpa mengembalikan pengawasan hierarkis yang kaku. Thompson et al. (2024) menjelaskan bahwa pemantauan data kinerja secara berkala merupakan cara utama manajemen mengendalikan karyawan yang diberdayakan, karena hasil kerja yang terukur menggantikan pengawasan langsung atas cara kerja. Selain pemantauan hasil, pengendalian juga dapat dilakukan melalui tekanan sebaya dalam tim kerja, karena rekan satu tim yang kinerjanya saling bergantung akan saling mengoreksi, serta melalui penetapan batas kewenangan yang jelas mengenai keputusan apa yang boleh diambil sendiri dan keputusan apa yang memerlukan persetujuan. Dengan demikian, kombinasi antara sistem informasi yang transparan, norma tim yang kuat dan batas kewenangan yang tegas memungkinkan perusahaan menikmati manfaat kecepatan dan kreativitas dari pemberdayaan tanpa kehilangan kendali atas risiko. Implikasi manajerialnya adalah bahwa investasi pada sistem informasi bukan sekadar keputusan teknologi, melainkan keputusan desain organisasi yang menentukan seberapa jauh wewenang dapat didelegasikan secara aman.</p>`
    },
    {
      no: "10.6",
      title: "Penghargaan dan Insentif untuk Mendorong Eksekusi Strategi",
      body: `<p>Sistem penghargaan dan insentif merupakan alat manajemen yang paling ampuh untuk memperoleh komitmen karyawan terhadap eksekusi strategi yang unggul (Thompson et al., 2024). Logikanya sederhana, yaitu bahwa orang cenderung mengerahkan upaya terbaiknya pada hal-hal yang diukur dan dihargai, sehingga apabila imbalan dikaitkan secara langsung dengan pencapaian sasaran strategis dan finansial, kepentingan pribadi karyawan menjadi selaras dengan kepentingan strategi. Sebaliknya, sistem imbalan yang tidak terkait dengan sasaran strategis akan mengarahkan energi organisasi ke aktivitas yang keliru. Peringatan klasik Malcolm Forbes yang dikutip dalam buku menyatakan "bayarlah orang Anda serendah mungkin dan Anda akan memperoleh hasil yang setimpal dari mereka" (Thompson et al., 2024), yang menegaskan bahwa penghematan berlebihan pada imbalan justru merugikan eksekusi strategi.</p>
      <h5>10.6.1 Insentif Moneter dan Praktik Motivasi Nonmoneter</h5>
      <p>Paket imbalan yang efektif memadukan insentif moneter dan nonmoneter. Insentif moneter mencakup kenaikan gaji, bonus kinerja, opsi saham, kepemilikan saham karyawan, tunjangan pensiun dan promosi, sedangkan praktik motivasi nonmoneter mencakup fasilitas dan tunjangan yang menarik, pemberian tanggung jawab dan otonomi yang lebih besar, kebijakan promosi dari dalam, pengakuan publik atas prestasi, keterbukaan informasi mengenai kinerja perusahaan, lingkungan kerja yang menyenangkan, serta fleksibilitas waktu dan tempat kerja (Thompson et al., 2024). Buku mengilustrasikan Wegmans Food Markets yang secara konsisten masuk daftar perusahaan tempat kerja terbaik karena memadukan imbalan finansial dengan kepedulian tulus terhadap kesejahteraan dan pengembangan karyawannya, dan hal tersebut berbuah layanan pelanggan yang unggul. Di Indonesia, praktik serupa terlihat pada perusahaan seperti Bank BCA yang menekankan promosi dari dalam, program pengembangan karier dan penghargaan layanan, sehingga tingkat keterikatan karyawan yang tinggi menopang reputasi mutu layanannya. Dari uraian tersebut dapat disimpulkan bahwa motivasi eksekusi strategi tidak dapat dibeli hanya dengan uang, melainkan dibangun melalui bauran imbalan finansial dan pengalaman kerja yang bermakna.</p>
      <h5>10.6.2 Keseimbangan antara Penghargaan dan Hukuman</h5>
      <p>Manajer perlu menimbang seberapa besar tekanan dan konsekuensi negatif digunakan berdampingan dengan imbalan positif. Sejumlah perusahaan menganut budaya berkinerja tinggi yang menuntut target menantang dan memberlakukan konsekuensi tegas bagi kinerja yang buruk, sementara perusahaan lain mengandalkan hampir sepenuhnya dorongan positif. Menurut Thompson et al. (2024), unsur tekanan dan ketegangan tertentu memang bermanfaat karena target yang menantang mencegah rasa puas diri, namun praktik yang berimbang dan didominasi unsur positif umumnya lebih unggul, karena ketakutan akan hukuman menumbuhkan kecemasan, perilaku defensif dan keengganan mengambil risiko yang justru merusak eksekusi strategi. Oleh karena itu, konsekuensi negatif sebaiknya dicadangkan bagi kinerja buruk yang berulang dan pelanggaran serius, sedangkan pengelolaan kinerja sehari-hari bertumpu pada sasaran yang jelas, umpan balik dan penghargaan atas pencapaian.</p>
      <h5>10.6.3 Mengaitkan Imbalan dengan Hasil Kinerja yang Tepat</h5>
      <p>Prinsip pertama dalam merancang sistem kompensasi insentif adalah mengaitkan imbalan dengan hasil kinerja yang terkait langsung dengan eksekusi strategi yang baik dan pencapaian sasaran finansial serta strategis, bukan dengan kesibukan atau upaya semata (Thompson et al., 2024). Ukuran hasil yang dipilih harus merupakan hasil yang benar-benar dikejar strategi, misalnya pertumbuhan pangsa pasar, kepuasan pelanggan, ketepatan waktu pengiriman, biaya per unit atau tingkat cacat, dan bukan sekadar kehadiran atau lamanya jam kerja. Buku mencontohkan Nucor yang membayar pekerja baja berdasarkan bonus kelompok atas produksi yang memenuhi standar mutu, sehingga produktivitas tenaga kerjanya jauh melampaui rata-rata industri. Pedoman perancangan sistem insentif yang efektif dirangkum pada Tabel 10.2 sebagai berikut:</p>
      <table class="bk-table">
        <caption>Tabel 10.2 Pedoman Perancangan Sistem Kompensasi Insentif yang Efektif</caption>
        <thead><tr><th>No</th><th>Pedoman</th><th>Penjelasan Singkat</th></tr></thead>
        <tbody>
          <tr><td>1</td><td>Jadikan insentif kinerja komponen utama kompensasi</td><td>Porsi insentif harus cukup besar agar bermakna, bukan sekadar tambahan kecil di atas gaji tetap</td></tr>
          <tr><td>2</td><td>Berlakukan insentif bagi seluruh karyawan</td><td>Insentif tidak dibatasi pada manajemen puncak agar seluruh organisasi terdorong mengeksekusi strategi</td></tr>
          <tr><td>3</td><td>Kelola sistem dengan objektivitas dan keadilan</td><td>Standar kinerja ditetapkan jelas dan penilaian dilakukan konsisten agar sistem dipercaya</td></tr>
          <tr><td>4</td><td>Kaitkan insentif dengan target dalam rencana strategis</td><td>Ukuran kinerja diturunkan dari sasaran strategis dan finansial perusahaan</td></tr>
          <tr><td>5</td><td>Pastikan target dapat dicapai dengan upaya nyata</td><td>Target menantang namun realistis, dan setiap karyawan memiliki peluang memperoleh imbalan</td></tr>
          <tr><td>6</td><td>Hargai hasil, bukan sekadar upaya</td><td>Imbalan diberikan atas pencapaian hasil, dan alasan pemakluman atas kegagalan dibatasi</td></tr>
          <tr><td>7</td><td>Hindari celah manipulasi</td><td>Sistem dirancang agar imbalan tidak dapat diperoleh melalui cara yang menyimpang dari maksud strategi</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Thompson, Peteraf, Gamble dan Strickland (2024)</td></tr></tfoot>
      </table>
      <p>Perancang sistem insentif juga harus mewaspadai konsekuensi yang tidak diinginkan dari ukuran kinerja yang keliru. Apabila imbalan dikaitkan dengan volume penjualan semata tanpa memperhatikan mutu dan kepatuhan, tenaga penjual dapat terdorong melakukan penjualan yang merugikan pelanggan dan reputasi perusahaan, sebagaimana terjadi pada sejumlah skandal penjualan produk keuangan. Oleh karena itu, ukuran hasil perlu dilengkapi rambu mutu, kepatuhan dan kepuasan pelanggan. Dengan demikian, sistem insentif yang dirancang dengan baik berfungsi ganda, yaitu sebagai mesin motivasi yang menyalakan upaya karyawan dan sebagai kompas yang mengarahkan upaya tersebut tepat ke sasaran strategis perusahaan.</p>`
    },
    {
      no: "10.7",
      title: "Rangkuman",
      body: `<p>Sesi ini menguraikan lima tindakan manajerial dalam mengelola operasi internal yang mendorong eksekusi strategi yang baik. Pertama, alokasi sumber daya harus selalu mengikuti prioritas strategis, dalam arti unit dan aktivitas yang kritikal bagi strategi memperoleh pendanaan dan orang yang memadai, sedangkan proyek yang tidak lagi terjustifikasi dihentikan. Kedua, kebijakan dan prosedur yang dirancang dengan baik memfasilitasi eksekusi melalui panduan dari atas ke bawah dan konsistensi pelaksanaan aktivitas kritikal, dengan tetap menjaga keseimbangan antara standardisasi dan ruang kreativitas. Ketiga, perangkat manajemen proses berupa <em>benchmarking</em>, <em>business process reengineering</em>, <em>total quality management</em> dan <em>Six Sigma</em> menyediakan jalur sistematis menuju keunggulan operasi, dengan <em>reengineering</em> mengejar lompatan besar sekali waktu dan TQM serta <em>Six Sigma</em> mengejar perbaikan berkesinambungan.</p>
      <p>Keempat, sistem informasi dan sistem operasi yang mencakup data pelanggan, operasi, karyawan, pemasok dan kinerja keuangan secara <em>real time</em> memampukan personel menjalankan peran strategisnya, sekaligus menjadi mekanisme pengendalian yang memungkinkan pemberdayaan karyawan tanpa kehilangan kendali. Kelima, sistem penghargaan dan insentif yang mengaitkan imbalan moneter dan nonmoneter dengan hasil kinerja yang tepat merupakan alat paling ampuh untuk membangun komitmen karyawan terhadap eksekusi strategi, dengan syarat insentif berlaku bagi seluruh karyawan, dikelola secara adil, ditautkan dengan target rencana strategis, dan menghargai hasil serta bukan sekadar upaya.</p>
      <p>Benang merah kelima tindakan tersebut adalah keselarasan, yaitu bahwa anggaran, aturan kerja, proses, sistem informasi dan imbalan harus menunjuk ke arah strategis yang sama. Perusahaan yang mampu menyelaraskan kelima tuas tersebut, sebagaimana ditunjukkan contoh Microsoft, McDonald's, Nucor dan Wegmans, serta Telkom Indonesia, BRI dan Grup Astra dalam konteks Indonesia, akan mengubah rumusan strategi menjadi keunggulan operasi yang nyata. Dengan demikian, mengelola operasi internal bukan pekerjaan administratif rutin, melainkan inti dari kepemimpinan eksekusi strategi.</p>`
    },
    {
      no: "10.8",
      title: "Daftar Pustaka",
      body: `<p>Thompson, A. A., Peteraf, M. A., Gamble, J. E. dan Strickland, A. J. (2024). <em>Crafting and Executing Strategy: The Quest for Competitive Advantage, Concepts and Cases</em>. 2024 Release. New York: McGraw Hill.</p>
      <p>Wheelen, T. L., Hunger, J. D., Hoffman, A. N. dan Bamford, C. E. (2018). <em>Strategic Management and Business Policy: Globalization, Innovation and Sustainability</em>. Edisi 15. Harlow: Pearson Education.</p>
      <p>David, F. R. dan David, F. R. (2017). <em>Strategic Management: A Competitive Advantage Approach, Concepts and Cases</em>. Edisi 16. Harlow: Pearson Education.</p>`
    }
  ]
};
