window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.sm = window.MBA_BOOK.sm || {};
window.MBA_BOOK.sm[11] = {
  bab: 11,
  judul: "BAB 11 BUDAYA KORPORAT DAN KEPEMIMPINAN: KUNCI EKSEKUSI STRATEGI YANG BAIK",
  sumber: "Thompson, Peteraf, Gamble dan Strickland (2024), Crafting and Executing Strategy, 2024 Release, McGraw Hill",
  lo: [
    "LO 12-1 Memahami ciri-ciri utama budaya korporat suatu perusahaan serta peran nilai inti dan standar etika perusahaan dalam membangun budaya korporat.",
    "LO 12-2 Menjelaskan bagaimana dan mengapa budaya perusahaan dapat mendukung upaya eksekusi strategi yang cakap.",
    "LO 12-3 Mengidentifikasi jenis-jenis tindakan yang dapat diambil manajemen untuk mengubah budaya korporat yang bermasalah.",
    "LO 12-4 Mengenali unsur-unsur kepemimpinan manajerial yang efektif dalam mencapai eksekusi strategi yang unggul."
  ],
  sections: [
    {
      no: "11.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi ini membahas dua tugas manajerial terakhir dari sepuluh tugas yang menentukan keberhasilan eksekusi strategi, yaitu membangun budaya korporat yang mendukung strategi dan memimpin proses eksekusi strategi itu sendiri. Pada dua sesi sebelumnya telah dibahas delapan tugas manajerial lain seperti penataan struktur organisasi, alokasi sumber daya, penetapan kebijakan, penggunaan alat manajemen proses, pemasangan sistem operasi, dan pemberian insentif yang tepat. Dengan demikian, sesi ini menutup rangkaian pembahasan mengenai eksekusi strategi dengan menyoroti dimensi lunak organisasi, yaitu nilai, norma, perilaku, dan kepemimpinan. Setelah mengikuti sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p><strong>LO 12-1.</strong> Memahami ciri-ciri utama budaya korporat suatu perusahaan serta peran nilai inti dan standar etika perusahaan dalam membangun budaya korporat.</p>
<p><strong>LO 12-2.</strong> Menjelaskan bagaimana dan mengapa budaya perusahaan dapat mendukung upaya eksekusi strategi yang cakap.</p>
<p><strong>LO 12-3.</strong> Mengidentifikasi jenis-jenis tindakan yang dapat diambil manajemen untuk mengubah budaya korporat yang bermasalah.</p>
<p><strong>LO 12-4.</strong> Mengenali unsur-unsur kepemimpinan manajerial yang efektif dalam mencapai eksekusi strategi yang unggul.</p>`
    },
    {
      no: "11.2",
      title: "Budaya Korporat dan Ciri-Ciri Utamanya",
      body: `<p>Setiap perusahaan memiliki iklim kerja internal yang khas dan tidak mudah ditiru oleh perusahaan lain, dan iklim tersebut dibentuk oleh budaya korporatnya. Menurut Thompson et al. (2024), <em>corporate culture</em> adalah nilai-nilai bersama, sikap yang mengakar, keyakinan inti, dan tradisi perusahaan yang menentukan norma perilaku, praktik kerja yang diterima, serta gaya beroperasi organisasi. Budaya korporat sering diibaratkan sebagai sistem operasi organisasi yang bekerja secara otomatis dan mereplikasi dirinya sendiri, atau sebagai DNA organisasi yang mendefinisikan cara segala sesuatu dikerjakan di dalam perusahaan. Dari definisi tersebut dapat disimpulkan bahwa budaya korporat merupakan perangkat lunak organisasi yang mengarahkan perilaku anggota organisasi tanpa harus selalu diperintahkan secara formal. Oleh karena itu, budaya berpengaruh besar terhadap iklim kerja internal, tindakan organisasi, pendekatan dalam menjalankan bisnis, dan pada akhirnya terhadap kinerja perusahaan.</p>
<h5>11.2.1 Ciri-Ciri Utama Budaya Korporat</h5>
<p>Budaya korporat tercermin dalam karakter atau kepribadian lingkungan kerja perusahaan. Sebagian ciri budaya tampak jelas, sedangkan sebagian lainnya bekerja secara halus dan tersirat. Thompson et al. (2024) mengidentifikasi sejumlah ciri utama yang perlu diamati untuk mengenali budaya suatu perusahaan, yaitu:</p>
<p>(1) nilai, prinsip bisnis, dan standar etika yang dianut dan dipraktikkan manajemen; (2) pendekatan perusahaan dalam mengelola sumber daya manusia beserta kebijakan dan prosedur resminya; (3) atmosfer dan semangat yang mewarnai iklim kerja, misalnya kompetitif atau kooperatif, inovatif atau resisten terhadap perubahan; (4) pola interaksi antara manajer dan karyawan, termasuk derajat kolaborasi, keterbukaan komunikasi, dan pemberdayaan inisiatif; (5) kekuatan tekanan rekan sejawat untuk mematuhi norma yang berlaku; (6) tindakan dan perilaku yang secara eksplisit didorong, dihargai, atau justru dicela oleh manajemen; (7) tradisi yang dihormati dan kisah-kisah yang berulang kali diceritakan sebagai teladan budaya; serta (8) cara perusahaan memperlakukan pemangku kepentingan eksternal seperti pemasok, masyarakat, dan lingkungan.</p>
<p>Ragam budaya antarperusahaan sangat luas. Sebagai ilustrasi, budaya Walmart berakar pada dedikasi terhadap kepuasan pelanggan, pengejaran biaya rendah, praktik operasi yang hemat, dan etos kerja yang kuat, sedangkan budaya Apple berpusat pada pelanggan, mendukung inovasi dan kreativitas, sekaligus sangat menjaga kerahasiaan teknologi yang dikembangkannya (Thompson et al., 2024). Di Indonesia, PT Astra International memiliki filosofi Catur Dharma yang menekankan manfaat bagi bangsa, pelayanan terbaik kepada pelanggan, penghargaan kepada individu, dan kerja sama, dan filosofi tersebut menjadi rujukan perilaku di seluruh anak perusahaannya. Contoh tersebut menunjukkan bahwa budaya yang khas dapat menjadi identitas sekaligus mekanisme koordinasi informal yang efektif.</p>
<h5>11.2.2 Peran Nilai Inti dan Standar Etika</h5>
<p>Fondasi budaya korporat hampir selalu terletak pada dedikasi perusahaan terhadap nilai-nilai inti tertentu dan standar perilaku etis yang ditetapkannya. Kesadaran akan hal ini mendorong banyak perusahaan menyusun pernyataan nilai formal dan kode etik tertulis. Menurut Thompson et al. (2024), nilai inti dan prinsip etika yang dinyatakan perusahaan memainkan dua peran dalam proses pembangunan budaya. Pertama, nilai dan etika menumbuhkan iklim kerja di mana seluruh personel berbagi keyakinan yang kuat dan seragam mengenai cara bisnis perusahaan harus dijalankan. Kedua, nilai dan etika memberikan panduan bagi personel mengenai cara melaksanakan pekerjaan, yaitu perilaku mana yang disetujui dan diharapkan serta perilaku mana yang terlarang. Dengan demikian, norma berbasis nilai dan etika berfungsi sebagai tolok ukur untuk menilai kepantasan suatu tindakan sehingga mengarahkan personel untuk mengerjakan sesuatu dengan benar sekaligus mengerjakan sesuatu yang benar. Selain itu, nilai dan etika yang tertanam kuat mengurangi kemungkinan terjadinya pelanggaran etis yang dapat merusak citra publik dan membahayakan kinerja keuangan perusahaan.</p>
<h5>11.2.3 Penanaman Norma Perilaku dan Pelestarian Budaya</h5>
<p>Setelah nilai dan standar etika diadopsi secara formal, keduanya harus dilembagakan dalam kebijakan dan praktik perusahaan serta ditanamkan dalam perilaku personel. Thompson et al. (2024) mengemukakan sejumlah teknik yang lazim digunakan, yaitu: penyaringan pelamar kerja dan perekrutan orang yang cocok dengan budaya, penanaman nilai secara sistematis kepada karyawan baru melalui orientasi dan pelatihan, penegasan berulang oleh eksekutif senior mengenai pentingnya nilai dan etika dalam komunikasi internal, keteladanan nyata dari para manajer, pemberian penghargaan kepada karyawan yang menampilkan perilaku sesuai nilai, dan pemberian sanksi tegas kepada pelanggar norma. Selain itu, perusahaan yang kaya tradisi mengandalkan indoktrinasi dari mulut ke mulut dan kekuatan cerita untuk menegakkan nilai. Dalam jangka panjang, budaya juga dilestarikan melalui seleksi alami, yaitu karyawan yang tidak cocok dengan budaya cenderung keluar, sedangkan yang cocok bertahan dan naik jabatan.</p>
<p>Meskipun budaya cenderung stabil, budaya tetap dapat berevolusi. Kekuatan internal dan eksternal seperti krisis, pergantian pemimpin puncak, teknologi disruptif, pergeseran pasar, diversifikasi ke bisnis baru, ekspansi internasional, dan merger atau akuisisi dapat memicu perubahan budaya. Perusahaan besar yang beroperasi di banyak negara juga umumnya memiliki beragam subkultur, yaitu variasi budaya antarunit bisnis, antarfungsi, atau antarnegara. Keberadaan subkultur tidak selalu merugikan sepanjang subkultur tersebut selaras dengan nilai inti perusahaan, akan menjadi masalah apabila subkultur saling bertentangan dan menghambat kerja sama lintas unit (Thompson et al., 2024). Implikasi manajerialnya adalah manajemen perlu secara aktif mengelola integrasi budaya, terutama pasca akuisisi, agar perbedaan subkultur tidak mengganggu eksekusi strategi.</p>`
    },
    {
      no: "11.3",
      title: "Budaya Kuat versus Budaya Lemah",
      body: `<p>Budaya korporat berbeda-beda dalam hal kedalaman pengaruhnya terhadap perilaku anggota organisasi. Menurut Thompson et al. (2024), perusahaan dengan <em>strong culture</em> memiliki nilai dan norma perilaku yang dianut secara luas, tertanam dalam, dan secara konsisten memengaruhi cara bisnis dijalankan, sedangkan perusahaan dengan <em>weak culture</em> tidak memiliki nilai bersama yang dipegang teguh sehingga hanya memberikan sedikit arahan perilaku. Dalam perusahaan berbudaya kuat, nilai dan norma bertahan lintas waktu dan lintas pergantian pemimpin, manajemen senior secara konsisten menegaskan nilai tersebut, dan karyawan menghadapi tekanan kuat dari rekan kerja untuk mematuhinya. Sebaliknya, dalam perusahaan berbudaya lemah, ikatan emosional karyawan terhadap perusahaan rendah, loyalitas tipis, dan perilaku lebih banyak diarahkan oleh aturan formal daripada oleh keyakinan bersama.</p>
<p>Terdapat tiga faktor yang umumnya melahirkan budaya kuat. Pertama, adanya pendiri atau pemimpin kuat yang menetapkan nilai, prinsip, dan praktik yang konsisten serta dipandang berkontribusi terhadap keberhasilan perusahaan. Kedua, komitmen tulus perusahaan untuk menjalankan bisnis sesuai dengan tradisi dan nilai yang telah mapan sehingga nilai tersebut dihidupi, bukan sekadar dipajang. Ketiga, kepedulian nyata terhadap kesejahteraan pelanggan, karyawan, dan pemegang saham yang menumbuhkan rasa memiliki di kalangan personel (Thompson et al., 2024). Contoh di Indonesia dapat dilihat pada Bank Central Asia yang selama puluhan tahun menanamkan budaya pelayanan prima dan kehati-hatian operasional sehingga norma layanan tersebut tetap konsisten meskipun terjadi pergantian generasi manajemen.</p>
<p>Perlu digarisbawahi bahwa budaya kuat tidak otomatis baik bagi eksekusi strategi. Budaya kuat merupakan aset apabila isi budayanya cocok dengan kebutuhan strategi, sebaliknya menjadi beban apabila norma yang tertanam justru bertentangan dengan arah strategi baru. Semakin kuat suatu budaya, semakin sulit pula budaya tersebut diubah. Oleh karena itu, penilaian manajerial yang tepat bukan sekadar menanyakan apakah budaya perusahaan kuat, melainkan apakah budaya tersebut selaras dengan strategi yang sedang dieksekusi.</p>`
    },
    {
      no: "11.4",
      title: "Mengapa Budaya Korporat Penting bagi Eksekusi Strategi",
      body: `<p>Kesesuaian antara budaya dan strategi merupakan salah satu penentu utama keberhasilan eksekusi. Budaya yang selaras dengan kebutuhan strategi akan memfokuskan perhatian, energi, dan perilaku karyawan pada aktivitas yang penting bagi strategi, sedangkan budaya yang berlawanan dengan strategi akan menimbulkan gesekan, resistensi, dan perilaku yang menyimpang dari kebutuhan eksekusi. Thompson et al. (2024) menegaskan bahwa ketidaksesuaian antara budaya dan strategi memaksa manajemen memilih salah satu dari dua opsi, yaitu mengubah strategi agar cocok dengan budaya atau mengubah budaya agar cocok dengan strategi, dan opsi kedua umumnya lebih tepat apabila strategi tersebut memang dibutuhkan untuk bersaing.</p>
<p>Budaya yang mendukung strategi berkontribusi pada eksekusi melalui dua mekanisme utama. Pertama, budaya yang selaras dengan strategi memberikan tekanan kelompok dan norma informal yang mengarahkan personel untuk berperilaku sesuai kebutuhan eksekusi sehingga mengurangi kebutuhan akan pengawasan formal yang mahal. Karyawan yang meyakini nilai perusahaan akan mengerjakan hal yang benar meskipun tidak diawasi dan tidak diberikan imbalan khusus. Kedua, budaya yang kuat dan selaras dengan strategi menumbuhkan identifikasi emosional karyawan terhadap visi dan target kinerja perusahaan sehingga meningkatkan komitmen, semangat, dan produktivitas dalam melaksanakan strategi. Dengan demikian, budaya berfungsi sebagai bahan bakar motivasional sekaligus sistem kendali informal bagi eksekusi strategi.</p>
<p>Implikasi manajerialnya jelas, yaitu penyusun strategi perlu memperlakukan budaya sebagai variabel yang dikelola, bukan sebagai kondisi yang diterima apa adanya. Pada saat merumuskan strategi, manajemen sebaiknya mempertimbangkan sejauh mana budaya yang ada mampu menopang strategi tersebut. Pada saat mengeksekusi strategi, manajemen perlu terus menyelaraskan praktik pengelolaan sumber daya manusia, sistem imbalan, dan komunikasi internal dengan perilaku yang dituntut oleh strategi. Selain itu, semakin cepat lingkungan bisnis berubah, semakin penting kelenturan budaya sebagai penopang penyesuaian strategi.</p>`
    },
    {
      no: "11.5",
      title: "Budaya Sehat yang Mendukung Eksekusi Strategi",
      body: `<p>Tidak semua budaya memiliki dampak yang sama terhadap eksekusi strategi. Thompson et al. (2024) mengidentifikasi dua tipe budaya sehat yang secara khusus membantu eksekusi strategi yang baik, yaitu <em>high-performance culture</em> dan <em>adaptive culture</em>. Kedua tipe budaya tersebut sama-sama menempatkan hasil dan kemajuan organisasi sebagai norma bersama, namun menekankan aspek yang berbeda.</p>
<h5>11.5.1 Budaya Kinerja Tinggi</h5>
<p>Budaya kinerja tinggi ditandai oleh semangat berprestasi yang menyala, orientasi pada hasil, dan norma kerja yang menuntut setiap orang memberikan upaya terbaiknya. Ciri menonjol budaya ini meliputi standar kinerja yang menantang, penggunaan tolok ukur dan target yang jelas, rasa tanggung jawab yang kuat pada setiap individu, inisiatif karyawan yang tinggi, serta iklim yang konstruktif dan berorientasi pada pencapaian. Dalam budaya semacam ini, manajer memperlakukan karyawan sebagai mitra yang dihormati, memberikan otonomi untuk berprestasi, dan menuntut akuntabilitas atas hasil. Tantangan dalam membangun budaya kinerja tinggi adalah menumbuhkan dedikasi personel terhadap keunggulan operasional tanpa menimbulkan tekanan berlebihan yang merusak kesejahteraan karyawan. Oleh karena itu, budaya kinerja tinggi yang sehat selalu memadukan tuntutan hasil dengan penghargaan yang adil dan dukungan pengembangan kompetensi.</p>
<h5>11.5.2 Budaya Adaptif</h5>
<p>Budaya adaptif merupakan budaya yang paling cocok bagi perusahaan yang beroperasi di lingkungan yang berubah cepat. Dalam budaya adaptif, anggota organisasi memiliki keyakinan bersama bahwa perusahaan harus menyambut perubahan, berani bereksperimen, berinovasi, dan mengubah praktik lama apabila diperlukan demi kepentingan jangka panjang pemangku kepentingan. Kesediaan menerima perubahan tersebut tumbuh karena perubahan dijalankan dengan cara yang adil, yaitu kepentingan sah karyawan, pelanggan, pemegang saham, dan pihak lain dipertimbangkan secara seimbang sehingga karyawan menilai perubahan sebagai sesuatu yang aman dan bermakna (Thompson et al., 2024). Contoh yang relevan di Indonesia adalah GoTo yang secara berulang mengubah model layanan, struktur organisasi, dan portofolio produknya mengikuti dinamika ekonomi digital, dan kemampuan tersebut ditopang oleh norma internal yang menghargai eksperimen dan pembelajaran cepat. Implikasi manajerialnya adalah pemimpin perlu melembagakan proses yang membuat perubahan menjadi rutinitas, misalnya melalui uji coba terkendali, tinjauan pasca proyek, dan komunikasi transparan mengenai alasan setiap perubahan.</p>
<table class="bk-table">
<caption>Tabel 11.1 Perbandingan Budaya Kinerja Tinggi dan Budaya Adaptif</caption>
<thead><tr><th>Aspek</th><th>Budaya Kinerja Tinggi</th><th>Budaya Adaptif</th></tr></thead>
<tbody>
<tr><td>Fokus utama</td><td>Pencapaian hasil dan keunggulan operasional</td><td>Kecepatan menyesuaikan diri terhadap perubahan lingkungan</td></tr>
<tr><td>Norma dominan</td><td>Standar tinggi, akuntabilitas individu, inisiatif</td><td>Eksperimen, inovasi, kesediaan mengubah praktik lama</td></tr>
<tr><td>Peran manajer</td><td>Menetapkan target menantang dan menuntut akuntabilitas</td><td>Memfasilitasi perubahan yang adil bagi semua pemangku kepentingan</td></tr>
<tr><td>Kondisi lingkungan yang cocok</td><td>Industri yang menuntut efisiensi dan konsistensi hasil</td><td>Industri yang bergejolak dan berubah cepat</td></tr>
<tr><td>Risiko bila berlebihan</td><td>Tekanan kerja berlebihan dan kelelahan karyawan</td><td>Perubahan terus-menerus tanpa arah yang konsisten</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot>
</table>`
    },
    {
      no: "11.6",
      title: "Budaya Tidak Sehat yang Menghambat Eksekusi Strategi",
      body: `<p>Berlawanan dengan budaya sehat, terdapat budaya tidak sehat yang ciri-cirinya justru merusak iklim kerja dan kinerja perusahaan. Thompson et al. (2024) mengidentifikasi lima tipe budaya tidak sehat yang paling sering dijumpai, yaitu budaya yang resisten terhadap perubahan, budaya yang sarat politik, budaya yang berwawasan sempit ke dalam, budaya yang tidak etis dan digerakkan keserakahan, serta budaya yang terpecah oleh subkultur yang saling bertentangan. Kelima tipe tersebut diuraikan sebagai berikut.</p>
<p>Pertama, <em>change-resistant culture</em> menempatkan keamanan dan kemapanan di atas segalanya sehingga anggota organisasi menghindari risiko, enggan bereksperimen, dan cenderung mempertahankan status quo. Budaya semacam ini berbahaya karena membuat perusahaan lamban mengenali dan merespons perkembangan pasar, seperti yang dialami banyak peritel konvensional ketika perdagangan elektronik tumbuh pesat. Kedua, <em>politicized culture</em> ditandai oleh manuver politik internal di mana manajer membangun kerajaan kekuasaan masing-masing dan keputusan diambil berdasarkan kepentingan pribadi atau kelompok, bukan berdasarkan kepentingan perusahaan. Akibatnya, kolaborasi lintas unit melemah dan energi organisasi terkuras untuk persaingan internal.</p>
<p>Ketiga, <em>insular and inwardly focused culture</em> muncul ketika keberhasilan masa lalu membuat organisasi terlalu percaya diri sehingga meremehkan pesaing, mengabaikan pelanggan, dan menganggap jawaban terbaik selalu berasal dari dalam perusahaan. Sindrom semacam ini menumpulkan kepekaan terhadap sinyal eksternal dan menghambat pembelajaran dari praktik terbaik pihak lain. Keempat, <em>unethical and greed-driven culture</em> terbentuk apabila manajemen menoleransi atau bahkan mencontohkan perilaku melanggar etika demi target keuangan jangka pendek, dan budaya semacam ini sering berujung pada skandal yang menghancurkan reputasi perusahaan. Kasus manipulasi laporan keuangan pada beberapa perusahaan di Indonesia menunjukkan bahwa tekanan mencapai target tanpa penegakan etika dapat merusak kepercayaan publik dalam waktu singkat. Kelima, budaya yang berisi subkultur yang saling bertentangan menimbulkan inkonsistensi perilaku antarunit, memicu konflik internal, dan menghambat integrasi, dan masalah ini paling sering muncul setelah merger atau akuisisi yang tidak dikelola dengan baik.</p>
<p>Implikasi manajerial dari pembahasan ini adalah manajemen perlu melakukan diagnosis budaya secara jujur dan berkala. Gejala seperti menurunnya inisiatif karyawan, meningkatnya politik kantor, seringnya pelanggaran etika, atau resistensi kronis terhadap program perubahan merupakan indikator awal budaya tidak sehat. Semakin lama gejala tersebut dibiarkan, semakin dalam akar masalahnya dan semakin mahal biaya perbaikannya.</p>`
    },
    {
      no: "11.7",
      title: "Mengubah Budaya yang Bermasalah",
      body: `<p>Mengubah budaya bermasalah merupakan salah satu tugas manajemen yang paling sulit karena budaya telah mengakar dalam keyakinan, kebiasaan, dan ikatan emosional personel. Perubahan budaya menuntut kepemimpinan yang kompeten dari puncak organisasi karena hanya manajemen puncak yang memiliki kekuatan dan legitimasi untuk membongkar norma lama dan menggantinya dengan norma baru (Thompson et al., 2024). Proses perubahan budaya dimulai dengan tiga langkah diagnostik, yaitu: pertama, mengidentifikasi sisi-sisi budaya saat ini yang mendukung dan yang menghambat eksekusi strategi; kedua, menetapkan secara jelas tindakan, perilaku, dan praktik kerja baru yang harus menonjol dalam budaya baru; ketiga, berbicara secara terbuka dan persuasif kepada seluruh personel mengenai alasan perilaku lama harus ditinggalkan, termasuk manfaat budaya baru bagi pemangku kepentingan. Kredibilitas argumen manajemen sangat menentukan kesediaan karyawan meninggalkan kebiasaan lama.</p>
<h5>11.7.1 Tindakan Substantif Pengubah Budaya</h5>
<p>Langkah persuasif harus segera diikuti oleh tindakan substantif yang nyata dan tegas agar karyawan yakin bahwa manajemen bersungguh-sungguh. Tindakan substantif yang lazim dilakukan meliputi: mengganti eksekutif kunci yang menjadi penghalang perubahan, mempromosikan dan merekrut orang-orang yang memiliki nilai budaya baru ke posisi berpengaruh, merevisi kebijakan dan prosedur yang menghambat perilaku baru, merombak sistem kompensasi dan insentif agar memberi imbalan kepada perilaku yang diinginkan, serta mengalokasikan sumber daya secara nyata kepada inisiatif yang mencerminkan budaya baru. Menurut Thompson et al. (2024), tindakan yang paling meyakinkan adalah tindakan yang menunjukkan keberanian manajemen menanggung biaya demi nilai baru, misalnya memberhentikan manajer berkinerja tinggi yang melanggar norma budaya baru. Konsistensi antara ucapan dan tindakan manajemen merupakan mata uang utama dalam proses ini.</p>
<h5>11.7.2 Tindakan Simbolik Pengubah Budaya</h5>
<p>Selain tindakan substantif, terdapat tempat penting bagi tindakan simbolik. Bentuk tindakan simbolik yang paling utama adalah keteladanan pemimpin, misalnya eksekutif yang menuntut penghematan biaya harus menunjukkan gaya kerja hemat dalam fasilitas dan perjalanan dinasnya sendiri. Bentuk lain meliputi upacara penghargaan bagi karyawan yang memperagakan perilaku budaya baru, penceritaan kisah keberhasilan pelaku budaya baru dalam forum perusahaan, serta perubahan simbol fisik seperti tata ruang kantor yang lebih terbuka untuk menandakan kolaborasi. Tindakan simbolik murah secara finansial namun besar maknanya karena karyawan membaca sinyal dari apa yang dihargai pemimpin. Contoh di Indonesia adalah transformasi budaya kerja di lingkungan badan usaha milik negara melalui nilai inti AKHLAK yang disertai perombakan pejabat, sistem penilaian kinerja, dan simbol-simbol korporat untuk menandai era perilaku baru.</p>
<p>Perlu dipahami bahwa perubahan budaya membutuhkan waktu yang tidak singkat. Pada perusahaan besar, penggantian budaya yang telah mengakar dapat memerlukan waktu dua sampai lima tahun, bahkan lebih, karena keyakinan tidak berubah hanya karena pengumuman. Oleh karena itu, manajemen harus menjaga tempo perubahan melalui rangkaian kemenangan kecil yang terlihat, komunikasi berulang, dan penegakan norma yang konsisten sampai perilaku baru menjadi kebiasaan yang menggantikan kebiasaan lama.</p>`
    },
    {
      no: "11.8",
      title: "Memimpin Proses Eksekusi Strategi",
      body: `<p>Eksekusi strategi yang unggul tidak berjalan dengan sendirinya meskipun struktur, sistem, dan budaya telah ditata. Diperlukan kepemimpinan manajerial yang aktif untuk mendorong proses eksekusi berjalan pada standar tertinggi. Menurut Thompson et al. (2024), memimpin dorongan menuju eksekusi strategi yang baik menuntut manajer melakukan tiga tindakan utama, yaitu tetap mengetahui kondisi lapangan secara langsung, memobilisasi upaya menuju keunggulan operasi, dan memimpin proses pengambilan tindakan korektif. Ketiga tindakan tersebut diuraikan pada sub-sub-bab berikut.</p>
<h5>11.8.1 Memantau Kemajuan Secara Langsung</h5>
<p>Pemimpin yang efektif tidak boleh menggantungkan pemahamannya semata-mata pada laporan tertulis dan angka statistik. Salah satu teknik yang paling dikenal adalah <em>managing by walking around</em> (MBWA), yaitu praktik manajer turun langsung ke lapangan, mengunjungi fasilitas, berbicara dengan karyawan berbagai jenjang, dan mendengarkan pelanggan untuk memperoleh informasi tangan pertama mengenai kemajuan eksekusi (Thompson et al., 2024). Melalui MBWA, manajer dapat mendeteksi masalah lebih awal, menilai semangat kerja secara langsung, dan sekaligus menunjukkan kepedulian yang memotivasi karyawan. Di Indonesia, praktik serupa dikenal luas melalui kebiasaan blusukan sejumlah pemimpin organisasi publik dan swasta yang mengunjungi unit operasional tanpa protokol berlebihan untuk memahami masalah riil di lapangan. Informasi tangan pertama semacam ini menjadi dasar yang lebih akurat bagi keputusan korektif dibandingkan laporan berjenjang yang rawan penyaringan.</p>
<h5>11.8.2 Memobilisasi Upaya Menuju Keunggulan Operasi</h5>
<p>Tindakan kedua adalah membangun tekanan konstruktif agar organisasi terus mengejar keunggulan operasi dan eksekusi kelas satu. Pemimpin melakukannya dengan beberapa cara, yaitu: memperlakukan karyawan dengan bermartabat dan hormat sehingga tumbuh komitmen timbal balik; mendorong karyawan menggunakan inisiatif dan kreativitas dalam melaksanakan pekerjaan; menetapkan target regangan yang menantang namun dapat dicapai dan mengomunikasikan harapan yang jelas; menggunakan tolok ukur, praktik terbaik, dan alat perbaikan proses seperti <em>benchmarking</em>, <em>total quality management</em>, dan <em>Six Sigma</em> untuk memacu perbaikan berkelanjutan; serta menggunakan imbalan dan pengakuan untuk merayakan pencapaian dan memperkuat perilaku unggul (Thompson et al., 2024). Selain itu, pemimpin perlu memastikan karyawan memiliki sumber daya dan wewenang yang memadai agar tuntutan kinerja tinggi tidak berubah menjadi tekanan yang melumpuhkan. Dengan demikian, tekanan yang dibangun bersifat konstruktif karena disertai dukungan, bukan sekadar tuntutan.</p>
<h5>11.8.3 Memimpin Tindakan Korektif</h5>
<p>Tindakan ketiga adalah memimpin proses penyesuaian korektif ketika eksekusi tidak berjalan sesuai rencana atau ketika kondisi berubah. Pemimpin harus memutuskan kapan penyesuaian diperlukan dan penyesuaian seperti apa yang harus dilakukan, baik berupa perbaikan cara eksekusi maupun revisi atas strategi itu sendiri. Proses korektif yang baik umumnya berlangsung iteratif, yaitu pemimpin mengumpulkan informasi, mengembangkan alternatif, membangun konsensus di antara manajer kunci, memutuskan, dan mengawal pelaksanaan keputusan tersebut. Kecepatan menjadi penting dalam situasi krisis, sedangkan dalam situasi normal penyesuaian dapat dilakukan secara bertahap melalui proses evaluasi berkala. Hal yang membedakan pemimpin unggul adalah kesediaannya bertindak tegas atas dasar fakta tanpa menunda keputusan yang tidak populer, sekaligus kesabarannya menjaga arah jangka panjang agar organisasi tidak terombang-ambing oleh perubahan sesaat.</p>
<table class="bk-table">
<caption>Tabel 11.2 Tiga Peran Kepemimpinan dalam Proses Eksekusi Strategi</caption>
<thead><tr><th>Peran</th><th>Aktivitas Kunci</th><th>Hasil yang Diharapkan</th></tr></thead>
<tbody>
<tr><td>Memantau kemajuan secara langsung</td><td>MBWA, kunjungan lapangan, dialog dengan karyawan dan pelanggan</td><td>Informasi tangan pertama dan deteksi dini masalah eksekusi</td></tr>
<tr><td>Memobilisasi upaya keunggulan operasi</td><td>Target menantang, pemberdayaan, benchmarking, imbalan dan pengakuan</td><td>Tekanan konstruktif dan budaya semangat berprestasi</td></tr>
<tr><td>Memimpin tindakan korektif</td><td>Analisis penyimpangan, pembangunan konsensus, keputusan penyesuaian</td><td>Strategi dan eksekusi yang terus selaras dengan kondisi terkini</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot>
</table>`
    },
    {
      no: "11.9",
      title: "Catatan Akhir tentang Memimpin Perumusan dan Eksekusi Strategi",
      body: `<p>Sebagai penutup rangkaian pembahasan manajemen strategik, perlu ditegaskan bahwa perumusan dan eksekusi strategi bukanlah dua tahap yang terpisah dan berurutan secara kaku, melainkan proses yang berkelanjutan dan saling terkait. Strategi yang unggul di atas kertas tidak akan menghasilkan kinerja unggul tanpa eksekusi yang cakap, dan eksekusi yang rajin tidak akan menyelamatkan strategi yang keliru arah. Thompson et al. (2024) menegaskan bahwa ukuran sejati keunggulan manajerial adalah kemampuan merumuskan strategi yang baik sekaligus mengeksekusinya secara kompeten sehingga perusahaan mencapai kinerja yang ditargetkan.</p>
<p>Oleh karena itu, agenda pemimpin strategik bersifat menyeluruh, yaitu memastikan kesesuaian antara strategi dengan lingkungan eksternal dan sumber daya internal, membangun organisasi yang mampu, menata sistem dan kebijakan pendukung, menumbuhkan budaya yang selaras, dan terus melakukan penyesuaian ketika kondisi berubah. Kepemimpinan strategik yang baik juga menuntut integritas karena budaya etis dibangun dari teladan puncak. Dengan demikian, mahasiswa program MBA diharapkan memandang manajemen strategik sebagai disiplin praktik yang menuntut keterpaduan antara kecerdasan analitis dalam merumuskan strategi dan kecakapan kepemimpinan dalam menggerakkan manusia untuk mewujudkannya.</p>`
    },
    {
      no: "11.10",
      title: "Rangkuman",
      body: `<p>Budaya korporat adalah nilai bersama, sikap yang mengakar, keyakinan inti, dan tradisi perusahaan yang menentukan norma perilaku dan gaya beroperasi organisasi. Budaya berakar pada nilai inti dan standar etika yang memainkan dua peran, yaitu menumbuhkan keyakinan bersama mengenai cara berbisnis dan memandu perilaku personel dalam bekerja. Budaya ditanamkan melalui seleksi karyawan, orientasi, keteladanan manajemen, sistem imbalan, dan tradisi, serta dapat berevolusi karena krisis, pergantian pemimpin, atau merger. Budaya kuat memberikan pengaruh perilaku yang dalam dan konsisten, namun budaya kuat hanya menjadi aset apabila isinya selaras dengan strategi. Budaya yang selaras mendukung eksekusi melalui tekanan norma yang mengarahkan perilaku dan melalui komitmen emosional karyawan terhadap tujuan perusahaan.</p>
<p>Dua tipe budaya sehat yang menopang eksekusi adalah budaya kinerja tinggi yang berorientasi hasil dan budaya adaptif yang menyambut perubahan. Sebaliknya, lima tipe budaya tidak sehat, yaitu resisten terhadap perubahan, sarat politik, berwawasan sempit ke dalam, tidak etis, dan terpecah oleh subkultur yang bertentangan, menghambat eksekusi dan merusak kinerja. Mengubah budaya bermasalah menuntut diagnosis yang jujur, komunikasi persuasif, tindakan substantif seperti penggantian orang kunci dan perombakan insentif, tindakan simbolik seperti keteladanan pemimpin, serta kesabaran karena perubahan budaya memerlukan waktu bertahun-tahun.</p>
<p>Kepemimpinan eksekusi strategi mencakup tiga peran, yaitu memantau kemajuan secara langsung melalui praktik seperti MBWA, memobilisasi tekanan konstruktif menuju keunggulan operasi melalui target menantang, pemberdayaan, dan imbalan, serta memimpin tindakan korektif ketika hasil menyimpang dari rencana. Pada akhirnya, keunggulan manajerial diukur dari kemampuan memadukan perumusan strategi yang tepat dengan eksekusi yang kompeten secara berkelanjutan.</p>`
    },
    {
      no: "11.11",
      title: "Daftar Pustaka",
      body: `<p>Thompson, A. A., Peteraf, M. A., Gamble, J. E. dan Strickland, A. J. (2024). <em>Crafting and Executing Strategy: The Quest for Competitive Advantage, Concepts and Cases</em>. 2024 Release. McGraw Hill.</p>
<p>Wheelen, T. L., Hunger, J. D., Hoffman, A. N. dan Bamford, C. E. (2018). <em>Strategic Management and Business Policy: Globalization, Innovation and Sustainability</em>. Edisi 15. Pearson.</p>
<p>David, F. R. dan David, F. R. (2017). <em>Strategic Management: A Competitive Advantage Approach, Concepts and Cases</em>. Edisi 16. Pearson.</p>`
    }
  ]
};
