window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.sm = window.MBA_BOOK.sm || {};
window.MBA_BOOK.sm[4] = {
  bab: 4,
  judul: "BAB 4 ANALISIS LINGKUNGAN EKSTERNAL PERUSAHAAN",
  sumber: "Thompson, Peteraf, Gamble dan Strickland (2024), Crafting and Executing Strategy, 2024 Release, McGraw Hill",
  lo: [
    "LO 3-1 Mengenali faktor-faktor dalam lingkungan makro perusahaan yang berpotensi memiliki signifikansi strategis.",
    "LO 3-2 Mengenali faktor-faktor yang menyebabkan persaingan dalam suatu industri menjadi sengit, normal, atau relatif lemah.",
    "LO 3-3 Memetakan posisi pasar kelompok-kelompok utama pesaing dalam industri.",
    "LO 3-4 Menentukan apakah prospek suatu industri menawarkan peluang pertumbuhan dan profitabilitas yang cukup menarik bagi perusahaan."
  ],
  sections: [
    {
      no: "4.1",
      title: "Capaian Pembelajaran",
      body: `<p>Perumusan strategi yang unggul selalu diawali dengan diagnosis yang cermat atas situasi perusahaan. Dua sisi situasi tersebut adalah lingkungan eksternal, khususnya kondisi persaingan industri tempat perusahaan beroperasi, dan lingkungan internal berupa sumber daya serta kapabilitas organisasi. Sesi ini memusatkan perhatian pada sisi eksternal, yaitu konsep dan alat analisis untuk menilai lingkungan makro, intensitas kekuatan persaingan, dinamika perubahan industri, posisi para pesaing, faktor kunci keberhasilan, dan prospek profitabilitas industri secara keseluruhan (Thompson et al., 2024). Pemahaman yang utuh atas materi ini menjadi prasyarat bagi manajer untuk menyusun strategi yang benar-benar sesuai dengan situasi eksternal perusahaan.</p>
<p>Setelah mempelajari materi pada sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p>1. Mengenali faktor-faktor dalam lingkungan makro perusahaan yang berpotensi memiliki signifikansi strategis. 2. Mengenali faktor-faktor yang menyebabkan persaingan dalam suatu industri menjadi sengit, normal, atau relatif lemah. 3. Memetakan posisi pasar kelompok-kelompok utama pesaing dalam industri. 4. Menentukan apakah prospek suatu industri menawarkan peluang pertumbuhan dan profitabilitas yang cukup menarik bagi perusahaan.</p>
<p>Untuk mencapai keempat capaian tersebut, berpikir strategis mengenai lingkungan industri dan persaingan menuntut jawaban atas tujuh pertanyaan analitis, yaitu: apakah faktor lingkungan makro dan karakteristik industri menawarkan peluang pertumbuhan dan laba yang menarik; kekuatan persaingan apa yang dihadapi anggota industri dan seberapa kuat masing-masing; kekuatan apa yang mendorong perubahan industri dan bagaimana dampaknya; posisi pasar apa yang diduduki para pesaing; langkah strategis apa yang kemungkinan diambil pesaing berikutnya; apa saja faktor kunci keberhasilan bersaing; dan apakah prospek industri menawarkan peluang laba yang baik (Thompson et al., 2024). Ketujuh pertanyaan tersebut menjadi kerangka penyajian seluruh sub-bab dalam sesi ini.</p>`
    },
    {
      no: "4.2",
      title: "Analisis Lingkungan Makro dengan Kerangka PESTEL",
      body: `<p>Lingkungan eksternal perusahaan terdiri atas dua lapisan, yaitu lingkungan industri dan persaingan yang bersifat langsung serta lingkungan makro yang lebih luas. Menurut Thompson et al. (2024), lingkungan makro (<em>macro-environment</em>) mencakup konteks lingkungan luas tempat industri suatu perusahaan berada dan terdiri atas enam komponen utama, yaitu faktor politik, kondisi ekonomi, kekuatan sosiokultural, faktor teknologi, faktor lingkungan alam, dan kondisi hukum atau regulasi. Analisis atas keenam komponen tersebut dikenal dengan sebutan analisis PESTEL, sebuah akronim dari <em>Political, Economic, Sociocultural, Technological, Environmental,</em> dan <em>Legal/regulatory</em>. Dari uraian tersebut dapat disimpulkan bahwa analisis PESTEL merupakan alat penyaring untuk menentukan faktor luar industri mana yang paling relevan secara strategis bagi perusahaan.</p>
<p>Suatu faktor dikatakan relevan secara strategis (<em>strategically relevant</em>) apabila faktor tersebut cukup penting untuk memengaruhi keputusan perusahaan mengenai arah jangka panjang, tujuan, strategi, dan model bisnisnya. Dampak setiap komponen makro terhadap industri berbeda-beda, sehingga manajer perlu memberi perhatian terbesar pada faktor yang berdampak besar, sambil tetap memantau faktor berdampak kecil karena tingkat dampaknya dapat berubah sewaktu-waktu. Sebagai contoh, industri perbankan harus segera menyesuaikan praktik penyalurannya ketika regulasi perbankan baru diberlakukan, sedangkan industri rokok harus beradaptasi terhadap kenaikan cukai, stigma budaya terhadap perilaku merokok, dan kemunculan teknologi rokok elektrik (Thompson et al., 2024). Dalam konteks Indonesia, perusahaan teknologi finansial harus mencermati ketentuan Otoritas Jasa Keuangan mengenai pinjaman daring, sementara produsen kendaraan bermotor mencermati kebijakan insentif kendaraan listrik dari pemerintah yang mengubah struktur permintaan pasar otomotif nasional.</p>
<p>Untuk memperjelas cakupan masing-masing komponen, Tabel 4.1 menyajikan sintesis enam komponen lingkungan makro beserta contoh isu yang relevan.</p>
<table class="bk-table"><caption>Tabel 4.1 Enam Komponen Lingkungan Makro dalam Analisis PESTEL</caption>
<thead><tr><th>Komponen</th><th>Cakupan</th><th>Contoh Isu Strategis</th></tr></thead>
<tbody>
<tr><td>Politik</td><td>Kebijakan dan proses politik, termasuk derajat intervensi pemerintah dalam perekonomian</td><td>Kebijakan pajak, kebijakan fiskal, tarif perdagangan, iklim politik, kebijakan energi</td></tr>
<tr><td>Ekonomi</td><td>Iklim ekonomi umum pada tingkat lokal, nasional, regional, dan global</td><td>Suku bunga, nilai tukar, inflasi, pengangguran, laju pertumbuhan ekonomi</td></tr>
<tr><td>Sosiokultural</td><td>Nilai, sikap, gaya hidup, dan faktor demografis masyarakat</td><td>Perubahan gaya hidup sehat, urbanisasi, struktur usia penduduk, preferensi konsumsi</td></tr>
<tr><td>Teknologi</td><td>Laju perubahan teknologi dan aktivitas pengembangan teknologi baru</td><td>Kecerdasan buatan, komputasi awan, otomasi, teknologi genetika</td></tr>
<tr><td>Lingkungan alam</td><td>Kekuatan ekologis dan lingkungan hidup</td><td>Perubahan iklim, cuaca ekstrem, kelangkaan air, regulasi emisi karbon</td></tr>
<tr><td>Hukum dan regulasi</td><td>Peraturan dan proses hukum yang wajib dipatuhi perusahaan</td><td>Undang-undang ketenagakerjaan, perlindungan konsumen, keamanan data pribadi</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot>
</table>
<p>Cara menggunakan analisis PESTEL dilakukan melalui tiga tahap. Pertama, manajer mengidentifikasi faktor pada setiap komponen yang berpotensi memengaruhi industri. Kedua, manajer menilai arah dan besaran dampak setiap faktor terhadap permintaan, biaya, dan intensitas persaingan. Ketiga, manajer menyaring faktor yang relevan secara strategis untuk dijadikan masukan dalam perumusan strategi. Dengan demikian, analisis PESTEL bukan sekadar daftar faktor eksternal, melainkan sarana untuk menghubungkan perkembangan lingkungan luas dengan pilihan strategi perusahaan. Implikasi manajerialnya adalah manajer yang mengabaikan sinyal lingkungan makro berisiko terlambat menyesuaikan strategi ketika perubahan besar terjadi.</p>`
    },
    {
      no: "4.3",
      title: "Analisis Lima Kekuatan Persaingan",
      body: `<p>Kekuatan persaingan dalam suatu industri menentukan tekanan terhadap harga, biaya, dan investasi yang pada akhirnya membentuk potensi laba industri. Kerangka yang paling banyak digunakan untuk mendiagnosis kondisi tersebut adalah model lima kekuatan (<em>Five Forces Framework</em>) yang dikembangkan oleh Michael Porter dan diadopsi oleh Thompson et al. (2024) sebagai alat utama analisis industri. Kelima kekuatan tersebut adalah persaingan antarpenjual yang sudah ada, ancaman pendatang baru, tekanan dari produk substitusi, daya tawar pemasok, dan daya tawar pembeli. Penggunaan kerangka ini dilakukan dalam tiga langkah, yaitu mengidentifikasi pelaku pada setiap kekuatan, menilai kuat lemahnya tekanan setiap kekuatan berdasarkan faktor penentunya, dan menyimpulkan kekuatan kolektif kelimanya terhadap prospek laba industri.</p>
<h5>4.3.1 Persaingan antar Penjual yang Bersaing</h5>
<p>Persaingan antarpenjual (<em>rivalry among competing sellers</em>) biasanya merupakan kekuatan yang paling besar di antara kelimanya. Intensitas persaingan meningkat apabila permintaan pembeli tumbuh lambat atau menurun, biaya perpindahan pembeli antarmerek rendah, produk para penjual cenderung terstandardisasi, kapasitas industri berlebih, jumlah pesaing bertambah dan berukuran relatif setara, serta hambatan keluar dari industri tinggi (Thompson et al., 2024). Sebaliknya, persaingan melemah pada kondisi kebalikannya, misalnya ketika permintaan tumbuh cepat dan produk terdiferensiasi kuat. Para pesaing menggunakan beragam senjata bersaing (<em>competitive weapons</em>) seperti diskon harga, promosi, inovasi produk, perbaikan kualitas, perluasan jaringan dealer, dan peningkatan layanan purnajual. Contoh yang relevan di Indonesia adalah persaingan sengit antara Gojek dan Grab pada jasa transportasi daring, ketika subsidi tarif dan promosi agresif menekan profitabilitas kedua belah pihak karena biaya perpindahan konsumen antaraplikasi sangat rendah.</p>
<h5>4.3.2 Ancaman Pendatang Baru</h5>
<p>Ancaman pendatang baru (<em>threat of new entrants</em>) menimbulkan tekanan karena pendatang membawa kapasitas produksi tambahan dan keinginan merebut pangsa pasar. Kuat lemahnya ancaman ini ditentukan oleh dua hal, yaitu tinggi rendahnya hambatan masuk (<em>entry barriers</em>) dan reaksi yang diperkirakan dari perusahaan yang sudah mapan. Hambatan masuk yang umum meliputi skala ekonomi yang besar, keunggulan biaya petahana akibat efek kurva pembelajaran, loyalitas merek yang kuat, kebutuhan modal yang tinggi, akses terbatas ke jaringan distribusi, kebijakan pemerintah yang restriktif, dan efek jaringan (Thompson et al., 2024). Ancaman masuk juga dinilai dari kandidat pendatang yang ada; ancaman menjadi serius apabila terdapat perusahaan besar dengan sumber daya kuat yang menganggap industri tersebut menarik. Oleh karena itu, manajer perlu menilai bukan hanya hambatan masuk saat ini, melainkan juga daya tarik industri di mata calon pendatang potensial.</p>
<h5>4.3.3 Tekanan dari Produk Substitusi</h5>
<p>Tekanan persaingan dari produk substitusi berasal dari perusahaan di industri lain yang menawarkan produk pemenuh kebutuhan yang sama. Tekanan ini menguat apabila substitusi tersedia dengan mudah, harganya menarik dibandingkan kinerjanya, dan biaya perpindahan pembeli ke produk substitusi rendah (Thompson et al., 2024). Sebagai contoh, layanan konferensi video menjadi substitusi bagi perjalanan dinas, sementara di Indonesia dompet digital seperti GoPay dan OVO menjadi substitusi yang menekan penggunaan uang tunai dan kartu debit pada transaksi ritel. Keberadaan substitusi yang kuat secara efektif menetapkan batas atas harga yang dapat dikenakan anggota industri tanpa mendorong pembeli berpindah. Dengan demikian, manajer wajib memantau perkembangan industri lain yang produknya berpotensi memenuhi kebutuhan pelanggan yang sama.</p>
<h5>4.3.4 Daya Tawar Pemasok</h5>
<p>Daya tawar pemasok (<em>supplier bargaining power</em>) menjadi kuat apabila input yang dipasok langka atau terdiferensiasi, biaya berpindah ke pemasok lain tinggi, jumlah pemasok sedikit sedangkan pembelinya banyak, tidak tersedia input pengganti yang baik, dan pemasok memiliki ancaman kredibel untuk melakukan integrasi maju ke industri pembelinya (Thompson et al., 2024). Pemasok yang kuat dapat menekan laba industri dengan menaikkan harga input atau menurunkan kualitas pasokan. Contohnya, produsen cip berkinerja tinggi memiliki daya tawar besar terhadap produsen komputer dan otomotif ketika pasokan cip global langka. Dalam konteks Indonesia, maskapai penerbangan menghadapi daya tawar pemasok avtur yang tinggi karena pasokan bahan bakar penerbangan di bandara domestik didominasi oleh satu penyedia utama, sehingga struktur biaya maskapai sangat dipengaruhi keputusan harga pemasok tersebut.</p>
<h5>4.3.5 Daya Tawar Pembeli dan Sensitivitas Harga</h5>
<p>Tekanan dari sisi pembeli ditentukan oleh dua unsur, yaitu daya tawar (<em>bargaining power</em>) dan sensitivitas harga (<em>price sensitivity</em>). Daya tawar pembeli menguat apabila biaya berpindah ke merek lain rendah, jumlah pembeli sedikit atau pembelian dilakukan dalam volume besar, permintaan pembeli lemah, pembeli memiliki informasi yang baik mengenai harga dan biaya penjual, serta pembeli mampu melakukan integrasi mundur (Thompson et al., 2024). Sementara itu, pembeli menjadi sensitif terhadap harga apabila pendapatannya rendah, produk yang dibeli merupakan porsi besar dari pengeluarannya, atau kualitas antarmerek tidak jauh berbeda. Peritel besar seperti jaringan hipermarket memiliki daya tawar tinggi terhadap produsen barang konsumsi karena volume pembeliannya besar dan mengendalikan akses ke rak penjualan. Implikasi manajerialnya, perusahaan perlu membangun diferensiasi dan meningkatkan biaya perpindahan agar posisi tawarnya terhadap pembeli membaik.</p>
<h5>4.3.6 Kekuatan Kolektif Lima Kekuatan dan Penyesuaian Strategi</h5>
<p>Langkah terakhir adalah menilai apakah kekuatan kolektif kelima kekuatan tersebut kondusif bagi profitabilitas. Industri dikatakan tidak menarik secara kompetitif apabila persaingan antarpenjual sangat kuat, hambatan masuk rendah, tekanan substitusi kuat, serta pemasok dan pembeli memiliki daya tawar besar; kondisi ekstrem semacam ini dapat menimbulkan struktur yang merusak laba semua pihak. Sebaliknya, lingkungan paling ideal terjadi apabila kelima kekuatan berada pada tingkat lemah hingga moderat. Menghadapi hasil analisis tersebut, tugas pembuat strategi adalah merancang strategi yang melindungi perusahaan dari tekanan kekuatan yang paling kuat, memanfaatkan persaingan untuk keuntungannya, dan bila memungkinkan mengubah kekuatan persaingan agar lebih menguntungkan perusahaan (Thompson et al., 2024). Dengan demikian, analisis lima kekuatan tidak berhenti pada diagnosis, melainkan menjadi dasar pemilihan posisi bersaing yang paling dapat dipertahankan.</p>`
    },
    {
      no: "4.4",
      title: "Komplementor dan Kerangka Value Net",
      body: `<p>Analisis lima kekuatan memandang hubungan antarpelaku industri terutama sebagai hubungan persaingan, padahal tidak semua interaksi bersifat menekan laba. Kerangka <em>value net</em> yang diperkenalkan Brandenburger dan Nalebuff memperluas analisis dengan memasukkan pihak yang bekerja sama menciptakan nilai, yaitu komplementor (Thompson et al., 2024). Komplementor (<em>complementors</em>) adalah produsen produk atau jasa pelengkap yang meningkatkan nilai produk perusahaan ketika keduanya digunakan bersama. Sebagai contoh, pengembang aplikasi merupakan komplementor bagi produsen telepon pintar, karena semakin kaya ekosistem aplikasi maka semakin tinggi nilai perangkat di mata konsumen.</p>
<p>Dalam kerangka <em>value net</em>, perusahaan berada di tengah jaringan yang terdiri atas pelanggan, pemasok, substitutor (pesaing dan penyedia substitusi), dan komplementor. Perbedaan mendasar dengan lima kekuatan terletak pada perspektifnya; <em>value net</em> menyoroti peluang kerja sama (<em>cooperative</em>) di samping ancaman kompetitif, sehingga manajer dapat melihat pemasok dan pelanggan bukan hanya sebagai penekan laba, melainkan juga sebagai mitra penciptaan nilai. Di Indonesia, hubungan antara platform lokapasar seperti Tokopedia dengan perusahaan logistik dan penyedia pembayaran digital menggambarkan pola komplementer tersebut, karena keandalan pengiriman dan kemudahan pembayaran meningkatkan nilai platform bagi penjual maupun pembeli. Oleh karena itu, analisis industri yang lengkap sebaiknya memadukan diagnosis tekanan kompetitif dari lima kekuatan dengan identifikasi peluang kolaborasi dari <em>value net</em>.</p>`
    },
    {
      no: "4.5",
      title: "Dinamika Industri dan Analisis Kekuatan Pendorong Perubahan",
      body: `<p>Intensitas kekuatan persaingan tidak bersifat tetap, melainkan berubah seiring perkembangan industri. Kondisi industri berubah karena adanya kekuatan pendorong (<em>driving forces</em>), yaitu agen perubahan yang memiliki pengaruh terbesar dalam membentuk ulang struktur industri dan kondisi persaingan (Thompson et al., 2024). Sebagian kekuatan pendorong berasal dari lingkaran luar lingkungan makro dan sebagian lainnya berasal dari dalam industri itu sendiri. Hipotesis daur hidup industri yang bergerak dari fase perkenalan, pertumbuhan cepat, kedewasaan, hingga penurunan hanyalah salah satu aspek perubahan industri, karena banyak perkembangan lain yang juga mengubah peta persaingan.</p>
<p>Analisis kekuatan pendorong dilakukan melalui tiga langkah, yaitu: (1) mengidentifikasi kekuatan pendorong yang sedang bekerja; (2) menilai apakah dampak kolektifnya membuat permintaan industri naik atau turun, persaingan lebih atau kurang intens, dan profitabilitas lebih tinggi atau lebih rendah; dan (3) menentukan penyesuaian strategi yang diperlukan untuk mengantisipasi dampak tersebut (Thompson et al., 2024). Kekuatan pendorong yang umum meliputi perubahan laju pertumbuhan jangka panjang industri, perubahan komposisi pembeli, inovasi produk dan proses, perubahan teknologi, masuk atau keluarnya perusahaan besar, globalisasi, difusi pengetahuan teknis, perubahan biaya dan efisiensi, pergeseran preferensi pembeli dari produk terdiferensiasi ke produk standar atau sebaliknya, perubahan regulasi dan kebijakan pemerintah, serta pergeseran perhatian masyarakat, sikap, dan gaya hidup. Dari daftar panjang tersebut, biasanya hanya tiga sampai empat faktor yang benar-benar berperan sebagai kekuatan pendorong utama pada satu industri.</p>
<p>Sebagai ilustrasi, industri ritel Indonesia mengalami perubahan struktural ketika penetrasi internet, adopsi pembayaran digital, dan perubahan preferensi belanja generasi muda mendorong migrasi transaksi dari gerai fisik ke lokapasar daring, sehingga peritel konvensional harus mengembangkan strategi omnikanal. Implikasi manajerialnya jelas, yaitu nilai sesungguhnya dari analisis kekuatan pendorong terletak pada langkah ketiga; tanpa penyesuaian strategi, identifikasi perubahan hanya menjadi latihan deskriptif yang tidak memberikan manfaat kompetitif. Dengan demikian, manajer dituntut menyusun strategi yang bersifat antisipatif terhadap arah perubahan industri, bukan sekadar reaktif terhadap kondisi saat ini.</p>`
    },
    {
      no: "4.6",
      title: "Analisis Kelompok Strategis dan Pemetaan Posisi Pesaing",
      body: `<p>Dalam satu industri, para penjual umumnya berbeda dalam rentang harga dan kualitas, tipe pembeli yang dilayani, cakupan geografis, dan pendekatan bersaing lainnya, sehingga sebagian perusahaan menempati posisi yang lebih menarik daripada yang lain. Menurut Thompson et al. (2024), kelompok strategis (<em>strategic group</em>) adalah sekumpulan anggota industri yang memiliki pendekatan bersaing dan posisi pasar yang serupa. Teknik terbaik untuk mengungkap posisi pasar para pesaing adalah pemetaan kelompok strategis (<em>strategic group mapping</em>), yaitu penyajian posisi setiap kelompok pada peta dua dimensi berdasarkan variabel bersaing yang relevan.</p>
<p>Prosedur penyusunan peta kelompok strategis terdiri atas empat langkah. Pertama, mengidentifikasi karakteristik bersaing yang membedakan perusahaan dalam industri, misalnya rentang harga dan kualitas, cakupan geografis, keluasan lini produk, saluran distribusi, dan tingkat layanan. Kedua, memetakan setiap perusahaan pada diagram dua variabel yang dipilih; kedua variabel tidak boleh berkorelasi tinggi agar peta memberikan informasi yang bermakna. Ketiga, mengelompokkan perusahaan yang posisinya berdekatan ke dalam satu kelompok strategis. Keempat, menggambar lingkaran setiap kelompok dengan ukuran proporsional terhadap pangsa penjualan kelompok tersebut. Sebagai contoh di Indonesia, peta industri kopi bergerai dapat disusun dengan sumbu harga per cangkir dan keluasan jaringan gerai, sehingga terlihat kelompok premium seperti Starbucks terpisah dari kelompok kopi kekinian harga terjangkau seperti Kopi Kenangan dan Janji Jiwa.</p>
<p>Peta kelompok strategis memberikan dua pelajaran penting. Pertama, tekanan persaingan paling kuat terjadi antarperusahaan dalam kelompok yang sama atau antarkelompok yang posisinya berdekatan, sedangkan kelompok yang berjauhan hampir tidak bersaing secara langsung. Kedua, potensi laba antar kelompok strategis dapat berbeda karena setiap kelompok menghadapi derajat persaingan internal, ancaman pendatang, tekanan substitusi, dan daya tawar pemasok serta pembeli yang berbeda pula (Thompson et al., 2024). Perpindahan antarkelompok sering kali sulit karena adanya hambatan mobilitas (<em>mobility barriers</em>) yang serupa dengan hambatan masuk industri. Oleh karena itu, manajer dapat menggunakan peta ini untuk menilai apakah posisi perusahaan saat ini menguntungkan, apakah perlu berpindah ke posisi yang lebih atraktif, dan dari arah mana ancaman persaingan paling mungkin datang.</p>`
    },
    {
      no: "4.7",
      title: "Analisis Pesaing dengan Kerangka SOAR",
      body: `<p>Perusahaan yang tidak memperhatikan strategi dan situasi para pesaingnya ibarat memasuki pertempuran tanpa mengenali lawan. Pengumpulan intelijen kompetitif mengenai arah strategis dan kemungkinan langkah pesaing memungkinkan perusahaan menyiapkan langkah bertahan, merancang langkah strategisnya sendiri dengan keyakinan yang lebih baik, dan memanfaatkan celah yang timbul dari kesalahan pesaing (Thompson et al., 2024). Namun, para pesaing jarang mengungkapkan niat strategisnya secara terbuka, sehingga diperlukan indikator tidak langsung yang dapat diandalkan untuk memprediksi perilaku mereka.</p>
<p>Kerangka SOAR untuk analisis pesaing yang dikembangkan Michael Porter menunjuk empat indikator langkah strategis pesaing, yaitu strategi saat ini (<em>Strategy</em>), tujuan (<em>Objectives</em>), asumsi mengenai dirinya dan industrinya (<em>Assumptions</em>), serta sumber daya dan kapabilitas (<em>Resources and capabilities</em>). Cara menggunakannya adalah menyusun profil setiap pesaing utama berdasarkan keempat dimensi tersebut untuk memperkirakan kecenderungan perilakunya, yaitu langkah kompetitif apa yang kemungkinan diambil dan bagaimana pesaing akan bereaksi terhadap langkah perusahaan. Strategi pesaing dapat dibaca dari tindakan pasarnya dan pernyataan manajemennya; tujuan mencakup sasaran kinerja keuangan dan ambisi pasarnya; asumsi mencerminkan cara pandang pesaing yang dapat mengandung titik buta; sedangkan sumber daya dan kapabilitas menentukan kemampuan pesaing untuk merealisasikan niatnya. Implikasi manajerialnya, profil SOAR yang disusun secara disiplin membantu perusahaan menghindari perang harga yang tidak perlu, mengantisipasi serangan pesaing pada segmen tertentu, dan memilih arena bersaing tempat pesaing paling lemah untuk merespons.</p>`
    },
    {
      no: "4.8",
      title: "Faktor Kunci Keberhasilan Industri",
      body: `<p>Setiap industri memiliki sejumlah kecil faktor yang paling menentukan kemampuan anggotanya untuk bertahan dan berkembang. Menurut Thompson et al. (2024), faktor kunci keberhasilan (<em>key success factors</em> atau KSF) adalah elemen strategi, atribut produk dan jasa, pendekatan operasional, sumber daya, dan kapabilitas bersaing yang esensial untuk bertahan dan berkembang dalam industri. Faktor-faktor ini demikian penting sehingga seluruh perusahaan dalam industri wajib memperhatikannya; kegagalan memenuhi KSF membuat perusahaan tertinggal atau bahkan tersingkir dari industri. Dari definisi tersebut dapat disimpulkan bahwa KSF merupakan standar minimum kompetitif yang membedakan pesaing kuat dari pesaing lemah, sekaligus membedakan kondisi laba dari kondisi rugi.</p>
<p>Identifikasi KSF dilakukan dengan menjawab tiga pertanyaan, yaitu: atas dasar apa pembeli memilih di antara merek-merek yang bersaing; sumber daya dan kapabilitas apa yang dibutuhkan perusahaan agar berhasil secara kompetitif; dan kekurangan apa yang hampir pasti menempatkan perusahaan pada kerugian kompetitif yang signifikan. Jumlah KSF pada umumnya terbatas, biasanya tiga sampai lima faktor, sehingga manajer harus menahan diri dari membuat daftar yang terlalu panjang yang justru mengaburkan faktor yang benar-benar menentukan. Sebagai contoh, pada industri air minum dalam kemasan di Indonesia, KSF meliputi akses ke sumber air berkualitas, jaringan distribusi yang menjangkau warung hingga pelosok, kekuatan merek, dan efisiensi biaya produksi; keunggulan Aqua selama puluhan tahun sebagian besar dapat dijelaskan oleh penguasaannya atas faktor-faktor tersebut. Implikasi manajerialnya, KSF menjadi jembatan antara analisis eksternal dan perumusan strategi karena strategi yang baik harus dirancang unggul pada satu atau lebih KSF industri.</p>`
    },
    {
      no: "4.9",
      title: "Menilai Prospek Industri untuk Profitabilitas",
      body: `<p>Langkah terakhir dalam evaluasi lingkungan eksternal adalah menyimpulkan apakah industri menawarkan prospek yang menarik bagi pertumbuhan dan laba perusahaan. Setiap kerangka yang telah dibahas, yaitu PESTEL, lima kekuatan, kekuatan pendorong, kelompok strategis, analisis pesaing, dan faktor kunci keberhasilan, memberikan sudut pandang tersendiri, dan penggabungan seluruh hasil analisis menghasilkan gambaran yang lebih kaya mengenai daya tarik industri (Thompson et al., 2024). Faktor penting yang perlu dipertimbangkan meliputi potensi pertumbuhan industri, pengaruh kekuatan persaingan dan kekuatan pendorong terhadap profitabilitas masa depan, posisi perusahaan relatif terhadap pesaing, serta kesesuaian kapabilitas perusahaan dengan faktor kunci keberhasilan industri.</p>
<p>Penilaian daya tarik industri bersifat relatif, bukan absolut, karena industri yang sama dapat menarik bagi satu perusahaan dan tidak menarik bagi perusahaan lain. Perusahaan yang berposisi kuat, memiliki kapabilitas yang cocok dengan KSF, dan mampu memanfaatkan kelemahan pesaing dapat memperoleh laba yang baik bahkan pada industri yang secara umum kurang menarik. Sebaliknya, perusahaan yang berposisi lemah pada industri yang atraktif belum tentu menikmati laba yang memadai. Apabila kesimpulan analisis menunjukkan industri menarik, maka strategi agresif untuk memperluas penjualan dan investasi menjadi masuk akal; apabila industri dinilai kurang menarik, maka pilihan strategisnya meliputi berinvestasi secara hati-hati, mencari cara melindungi posisi, atau melakukan diversifikasi ke industri yang lebih menjanjikan. Dengan demikian, hasil akhir analisis lingkungan eksternal adalah keputusan alokasi sumber daya yang berpijak pada bukti, bukan pada intuisi semata.</p>`
    },
    {
      no: "4.10",
      title: "Rangkuman",
      body: `<p>Analisis lingkungan eksternal merupakan fondasi perumusan strategi yang sesuai dengan situasi perusahaan. Analisis dimulai dari lingkungan makro melalui kerangka PESTEL yang menyaring faktor politik, ekonomi, sosiokultural, teknologi, lingkungan alam, dan hukum yang relevan secara strategis. Selanjutnya, kondisi persaingan industri didiagnosis dengan model lima kekuatan yang menilai intensitas persaingan antarpenjual, ancaman pendatang baru, tekanan substitusi, daya tawar pemasok, dan daya tawar pembeli, serta dilengkapi kerangka <em>value net</em> yang menyoroti peran komplementor sebagai mitra penciptaan nilai. Kekuatan kolektif kelima kekuatan tersebut menentukan apakah struktur industri kondusif bagi profitabilitas.</p>
<p>Karena kondisi industri bersifat dinamis, manajer perlu melakukan analisis kekuatan pendorong untuk mengidentifikasi agen perubahan utama, menilai dampak kolektifnya, dan merumuskan penyesuaian strategi. Peta kelompok strategis membantu memetakan posisi para pesaing dan mengungkap perbedaan potensi laba antarkelompok, sedangkan kerangka SOAR menyediakan cara sistematis untuk memprediksi langkah pesaing berdasarkan strategi, tujuan, asumsi, serta sumber daya dan kapabilitasnya. Identifikasi faktor kunci keberhasilan kemudian menetapkan standar kompetitif yang wajib dipenuhi setiap anggota industri.</p>
<p>Pada akhirnya, seluruh alat analisis tersebut bermuara pada satu kesimpulan, yaitu apakah industri menawarkan prospek laba yang menarik bagi perusahaan dengan posisi dan kapabilitas tertentu. Kesimpulan tersebut menjadi masukan langsung bagi pemilihan arah jangka panjang, model bisnis, dan strategi bersaing yang akan dibahas pada sesi berikutnya mengenai analisis lingkungan internal perusahaan. Dengan demikian, penguasaan alat analisis eksternal merupakan kompetensi dasar yang tidak dapat ditawar bagi setiap pembuat strategi.</p>`
    },
    {
      no: "4.11",
      title: "Daftar Pustaka",
      body: `<p>Thompson, A. A., Peteraf, M. A., Gamble, J. E. dan Strickland, A. J. (2024). <em>Crafting and Executing Strategy: The Quest for Competitive Advantage, Concepts and Cases</em>. 2024 Release. McGraw Hill.</p>
<p>Porter, M. E. (2008). The Five Competitive Forces That Shape Strategy. <em>Harvard Business Review</em>, 86(1), 78-93.</p>
<p>Brandenburger, A. M. dan Nalebuff, B. J. (1996). <em>Co-opetition</em>. Currency Doubleday.</p>`
    }
  ]
};
