window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.sm = window.MBA_BOOK.sm || {};
window.MBA_BOOK.sm[7] = {
  bab: 7,
  judul: "BAB 7 MEMPERKUAT POSISI KOMPETITIF DAN BERSAING DI PASAR INTERNASIONAL",
  sumber: "Thompson, Peteraf, Gamble dan Strickland (2024), Crafting and Executing Strategy, 2024 Release, McGraw Hill",
  lo: [
    "LO 6-1 Memahami apakah, bagaimana, dan kapan perusahaan perlu menjalankan langkah strategis ofensif atau defensif.",
    "LO 6-2 Mengidentifikasi kapan posisi sebagai first mover, fast follower, atau late mover dapat menghasilkan keunggulan kompetitif.",
    "LO 6-3 Menjelaskan manfaat strategis dan risiko perluasan cakupan horizontal perusahaan melalui merger dan akuisisi.",
    "LO 6-4 Memahami keuntungan dan kerugian perluasan cakupan operasi perusahaan melalui integrasi vertikal.",
    "LO 6-5 Mengenali kondisi yang mendukung penyerahan aktivitas rantai nilai tertentu kepada pihak luar (outsourcing).",
    "LO 6-6 Memahami cara menangkap manfaat dan meminimalkan kelemahan aliansi strategis dan kemitraan.",
    "LO 7-1 Mengidentifikasi alasan utama perusahaan memilih bersaing di pasar internasional.",
    "LO 7-2 Memahami bagaimana dan mengapa perbedaan kondisi pasar antarnegara memengaruhi pilihan strategi perusahaan di pasar internasional.",
    "LO 7-3 Mengidentifikasi lima moda utama masuk ke pasar luar negeri.",
    "LO 7-4 Mengidentifikasi tiga pendekatan strategis utama dalam bersaing secara internasional.",
    "LO 7-5 Menjelaskan bagaimana perusahaan multinasional memanfaatkan operasi internasional untuk meningkatkan daya saing keseluruhan.",
    "LO 7-6 Mengenali karakteristik unik persaingan di pasar negara berkembang."
  ],
  sections: [
    {
      no: "7.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi ketujuh mata kuliah Strategic Management membahas dua tema yang saling melengkapi, yaitu langkah-langkah untuk memperkuat posisi kompetitif perusahaan serta strategi bersaing di pasar internasional. Setelah perusahaan menetapkan salah satu dari lima strategi kompetitif generik, perhatian manajemen beralih pada tindakan pelengkap yang dapat memaksimalkan kekuatan strategi tersebut, mencakup keputusan ofensif dan defensif, penentuan waktu langkah strategis, serta pengaturan cakupan operasi melalui merger dan akuisisi, integrasi vertikal, <em>outsourcing</em>, dan aliansi strategis (Thompson et al., 2024). Selain itu, sesi ini menelaah pilihan strategi ketika perusahaan memperluas arena persaingannya melintasi batas negara, mulai dari motif internasionalisasi, moda masuk, hingga pendekatan multidomestik, global, dan transnasional.</p>
      <p>Melalui pembelajaran pada sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <p><strong>Dari Bab 6:</strong> (1) memahami apakah, bagaimana, dan kapan menjalankan langkah ofensif atau defensif; (2) mengidentifikasi kapan menjadi <em>first mover</em>, <em>fast follower</em>, atau <em>late mover</em> menghasilkan keunggulan kompetitif; (3) menjelaskan manfaat dan risiko merger dan akuisisi horizontal; (4) memahami keuntungan dan kerugian integrasi vertikal; (5) mengenali kondisi yang mendukung <em>outsourcing</em>; serta (6) memahami cara mengelola aliansi strategis dan kemitraan.</p>
      <p><strong>Dari Bab 7:</strong> (1) mengidentifikasi alasan utama perusahaan bersaing di pasar internasional; (2) memahami pengaruh perbedaan kondisi antarnegara terhadap pilihan strategi; (3) mengidentifikasi lima moda masuk ke pasar luar negeri; (4) mengidentifikasi tiga pendekatan strategis bersaing internasional; (5) menjelaskan pemanfaatan operasi internasional untuk keunggulan kompetitif; serta (6) mengenali karakteristik persaingan di pasar negara berkembang (Thompson et al., 2024).</p>`
    },
    {
      no: "7.2",
      title: "Strategi Ofensif untuk Memperbaiki Posisi Pasar",
      body: `<p>Persaingan bisnis tidak selalu dapat dimenangkan hanya dengan bertahan pada posisi yang ada. Menurut Thompson et al. (2024), strategi ofensif diperlukan ketika perusahaan melihat peluang untuk merebut pangsa pasar yang menguntungkan dari pesaing, atau ketika perusahaan tidak memiliki pilihan lain selain menggerus keunggulan kompetitif pesaing yang kuat. Ofensif yang baik dibangun di atas empat prinsip, yaitu berfokus pada pembangunan keunggulan kompetitif yang berkelanjutan, mengerahkan sumber daya pada wilayah di mana pesaing paling lemah dalam bertahan, memanfaatkan unsur kejutan, serta menunjukkan kapasitas bertindak cepat dan tegas. Dengan demikian, serangan strategis seharusnya bertumpu pada aset kompetitif terkuat perusahaan, seperti merek yang lebih dikenal, sistem distribusi yang lebih efisien, atau kapabilitas teknologi yang lebih unggul, dan diarahkan pada titik kelemahan pesaing.</p>
      <h5>7.2.1 Pilihan Utama Strategi Ofensif</h5>
      <p>Terdapat beberapa opsi utama serangan strategis yang lazim digunakan perusahaan, yaitu: (1) menawarkan produk yang sama baik atau lebih baik dengan harga lebih rendah, yang hanya layak dilakukan oleh perusahaan yang telah lebih dahulu mencapai keunggulan biaya; (2) melompati pesaing dengan menjadi yang pertama memasarkan produk generasi berikutnya; (3) melakukan inovasi produk berkelanjutan untuk menarik penjualan dari pesaing yang kurang inovatif; (4) mengejar inovasi disruptif guna menciptakan pasar baru; (5) mengadopsi dan menyempurnakan gagasan baik dari perusahaan lain; (6) menggunakan taktik gerilya untuk merebut pangsa pasar dari pesaing yang lengah; serta (7) melancarkan serangan preemptif untuk menguasai sumber daya langka atau posisi yang sulit ditiru pesaing (Thompson et al., 2024). Dalam konteks Indonesia, langkah Gojek pada awal pertumbuhannya dapat dibaca sebagai kombinasi inovasi disruptif dan taktik promosi agresif, karena perusahaan tersebut menciptakan pasar transportasi daring baru sekaligus menawarkan subsidi tarif untuk menarik pelanggan dari moda transportasi konvensional.</p>
      <h5>7.2.2 Memilih Pesaing yang Diserang</h5>
      <p>Perusahaan ofensif perlu menetapkan sasaran serangan secara cermat. Sasaran terbaik meliputi pemimpin pasar yang rentan karena tidak lagi melayani pasar dengan baik, perusahaan peringkat kedua yang lemah pada bidang di mana penantang justru kuat, perusahaan yang sedang kesulitan dan hampir keluar dari pasar, serta perusahaan kecil lokal dengan kapabilitas terbatas (Thompson et al., 2024). Namun, menyerang pemimpin pasar yang kuat mengandung risiko pemborosan sumber daya dan dapat memicu perang harga yang merugikan seluruh industri. Oleh karena itu, keputusan menyerang harus didahului analisis kekuatan relatif dan kemungkinan balasan dari pihak yang diserang. Selain itu, perusahaan dapat menghindari konfrontasi langsung melalui strategi <em>blue ocean</em>, yaitu menciptakan ruang pasar baru yang belum diperebutkan sehingga persaingan menjadi tidak relevan untuk sementara waktu, sebagaimana dilakukan Cirque du Soleil ketika meredefinisi industri hiburan sirkus.</p>`
    },
    {
      no: "7.3",
      title: "Strategi Defensif untuk Melindungi Posisi Pasar",
      body: `<p>Di sisi lain, setiap perusahaan yang memiliki posisi pasar yang baik akan menjadi sasaran serangan pesaing, sehingga strategi defensif diperlukan untuk menurunkan risiko diserang, memperlemah dampak serangan yang terjadi, dan mengarahkan penantang ke sasaran lain (Thompson et al., 2024). Strategi defensif memang jarang menjadi sumber keunggulan kompetitif baru, namun berperan penting dalam mempertahankan keunggulan yang telah dimiliki. Terdapat dua bentuk utama pendekatan defensif yang dapat dijalankan secara bersamaan maupun terpisah.</p>
      <h5>7.3.1 Memblokir Jalur Serangan Penantang</h5>
      <p>Bentuk pertama adalah menutup celah yang dapat dimanfaatkan penantang. Caranya antara lain memperkenalkan fitur baru dan memperluas lini produk untuk menutup ceruk yang kosong, mempertahankan harga yang wajar dan kualitas yang menarik, menawarkan pelatihan dan dukungan purnajual yang lebih baik, memberikan diskon volume kepada penyalur agar tidak berpaling ke pemasok lain, serta mengikat pembeli dengan garansi yang lebih panjang. Dengan menutup jalur-jalur tersebut, ruang gerak penantang menjadi sempit dan biaya serangannya meningkat. Sebagai contoh di Indonesia, produsen mi instan yang dominan secara konsisten memperluas varian rasa dan menjaga kedalaman distribusi hingga warung kecil sehingga pendatang baru sulit menemukan celah pasar yang berarti.</p>
      <h5>7.3.2 Memberi Sinyal Kemungkinan Pembalasan</h5>
      <p>Bentuk kedua adalah memberi sinyal kepada calon penantang bahwa serangan akan dibalas dengan keras, dengan tujuan membuat penantang mengurungkan niat atau mengalihkan serangan ke sasaran lain. Sinyal tersebut dapat berupa pengumuman komitmen manajemen untuk mempertahankan pangsa pasar, pengumuman rencana penambahan kapasitas produksi yang memadai untuk memenuhi pertumbuhan permintaan, publikasi informasi tentang produk baru atau teknologi baru yang akan diluncurkan, serta pembalasan sesekali yang tegas terhadap langkah pesaing kecil untuk membangun reputasi sebagai pemain yang keras (Thompson et al., 2024). Dengan demikian, efektivitas strategi defensif sangat bergantung pada kredibilitas sinyal, karena ancaman yang tidak dipercaya justru dapat mengundang serangan.</p>`
    },
    {
      no: "7.4",
      title: "Penentuan Waktu Langkah Strategis",
      body: `<p>Kapan sebuah langkah strategis dilakukan sering kali sama pentingnya dengan langkah apa yang dilakukan. Menurut Thompson et al. (2024), keunggulan <em>first mover</em> muncul ketika menjadi pelopor memberikan posisi yang tidak mudah ditiru, sedangkan pada kondisi lain justru pengikut yang memperoleh hasil lebih baik dengan biaya lebih rendah. Oleh karena itu, manajemen perlu menilai kondisi pasar sebelum memutuskan menjadi pelopor, pengikut cepat, atau pendatang belakangan.</p>
      <h5>7.4.1 Potensi Keunggulan First Mover</h5>
      <p>Keunggulan penggerak pertama cenderung besar ketika: (1) menjadi pelopor membantu membangun reputasi dan citra merek yang kuat di mata pembeli; (2) komitmen awal terhadap bahan baku, teknologi baru, atau saluran distribusi menghasilkan keunggulan biaya absolut; (3) pelanggan pertama menjadi sangat loyal karena adanya biaya berpindah (<em>switching costs</em>); serta (4) langkah awal merupakan serangan preemptif yang menjadikan peniruan sulit atau tidak menarik. Contoh klasik adalah Amazon yang membangun keunggulan berkelanjutan dari posisinya sebagai pelopor ritel daring. Di Indonesia, Gojek menikmati keunggulan penggerak pertama pada layanan ojek daring karena berhasil membangun basis mitra pengemudi dan pelanggan dalam skala besar sebelum pesaing regional masuk secara agresif.</p>
      <h5>7.4.2 Potensi Keunggulan Late Mover dan Risiko First Mover</h5>
      <p>Sebaliknya, keunggulan pendatang belakangan atau kerugian pelopor muncul ketika biaya merintis pasar jauh lebih besar daripada manfaatnya dan loyalitas pembeli terhadap pelopor lemah, ketika produk pelopor masih primitif sehingga mudah dilampaui oleh pengikut, ketika teknologi berkembang cepat sehingga pengikut dapat melompat ke generasi berikutnya yang lebih baik, serta ketika ketidakpastian pasar memungkinkan pengikut belajar dari kesalahan pelopor (Thompson et al., 2024). Dengan demikian, keputusan waktu bergantung pada apakah perlombaan pasar bersifat maraton atau lari cepat. Apabila pasar berkembang lambat sementara teknologi berubah cepat, bergerak paling awal bukan jaminan keberhasilan, sehingga menjadi <em>fast follower</em> dengan sumber daya yang lebih besar sering kali merupakan pilihan yang lebih bijaksana. Implikasi manajerialnya, perusahaan harus menimbang kesiapan pasar, kecepatan perubahan teknologi, dan kekuatan sumber dayanya sendiri sebelum menetapkan waktu bergerak.</p>`
    },
    {
      no: "7.5",
      title: "Memperkuat Posisi melalui Cakupan Operasi serta Merger dan Akuisisi Horizontal",
      body: `<p>Selain langkah ofensif, defensif, dan penentuan waktu, kekuatan posisi pasar juga ditentukan oleh cakupan operasi perusahaan, yaitu luasnya aktivitas dan segmen pasar yang dijangkau. Thompson et al. (2024) membedakan cakupan horizontal, yaitu rentang segmen produk dan jasa yang dilayani dalam pasar fokusnya, dengan cakupan vertikal, yaitu sejauh mana perusahaan terlibat dalam berbagai tahap sistem rantai nilai industri. Keputusan mengenai cakupan menentukan batas-batas perusahaan serta memengaruhi struktur biaya dan kekuatan tawar terhadap pemasok dan pembeli.</p>
      <h5>7.5.1 Tujuan Strategis Merger dan Akuisisi Horizontal</h5>
      <p>Merger adalah penggabungan dua atau lebih perusahaan menjadi satu entitas, sedangkan akuisisi adalah tindakan satu perusahaan membeli dan menyerap operasi perusahaan lain. Merger dan akuisisi horizontal, yang melibatkan perusahaan dalam industri yang sama, umumnya diarahkan pada lima tujuan strategis, yaitu: (1) menciptakan operasi yang lebih efisien biaya melalui skala ekonomi dan penghapusan duplikasi aktivitas; (2) memperluas cakupan geografis perusahaan; (3) memperluas bisnis ke kategori produk baru; (4) memperoleh akses cepat terhadap teknologi baru atau sumber daya dan kapabilitas komplementer; serta (5) memimpin konvergensi industri yang batasnya sedang bergeser (Thompson et al., 2024). Contoh di Indonesia adalah penggabungan Gojek dan Tokopedia menjadi GoTo yang menyatukan kapabilitas transportasi, pembayaran, dan lokapasar dalam satu ekosistem, serta akuisisi Thang Long Cement di Vietnam oleh Semen Indonesia untuk memperluas jangkauan geografis regional.</p>
      <h5>7.5.2 Mengapa Merger dan Akuisisi Sering Gagal</h5>
      <p>Namun, banyak merger dan akuisisi tidak menghasilkan nilai yang diharapkan. Kegagalan umumnya bersumber dari penghematan biaya yang lebih kecil daripada perkiraan, perolehan kapabilitas yang lebih lama dari rencana, benturan budaya organisasi dua perusahaan, resistensi karyawan kunci, serta harga akuisisi yang terlalu mahal sehingga sinergi yang tercipta tidak menutup premi yang dibayarkan (Thompson et al., 2024). Oleh karena itu, implikasi manajerialnya adalah uji tuntas (<em>due diligence</em>) yang cermat, perencanaan integrasi pascamerger yang disiplin, dan penilaian realistis atas sinergi menjadi prasyarat keberhasilan strategi pertumbuhan anorganik.</p>`
    },
    {
      no: "7.6",
      title: "Strategi Integrasi Vertikal",
      body: `<p>Integrasi vertikal memperluas cakupan kompetitif perusahaan ke tahap-tahap lain dalam sistem rantai nilai industri yang sama. Menurut Thompson et al. (2024), perusahaan terintegrasi vertikal adalah perusahaan yang berpartisipasi dalam beberapa segmen atau tahap rantai nilai industri secara keseluruhan. Integrasi ke belakang (<em>backward integration</em>) berarti memasuki aktivitas yang sebelumnya dilakukan pemasok, sedangkan integrasi ke depan (<em>forward integration</em>) berarti memasuki aktivitas yang lebih dekat ke pengguna akhir, seperti distribusi dan ritel. Integrasi dapat bersifat penuh, parsial, atau berbentuk <em>tapered integration</em> yang menggabungkan produksi internal dengan pembelian dari pihak luar.</p>
      <h5>7.6.1 Keuntungan Integrasi Vertikal</h5>
      <p>Integrasi ke belakang menghasilkan penghematan hanya apabila volume kebutuhan perusahaan cukup besar untuk mencapai skala ekonomi pemasok dan efisiensi produksi pemasok dapat disamai atau dilampaui. Integrasi ke belakang juga bermanfaat ketika perusahaan perlu melindungi kepastian pasokan, menjaga kualitas masukan yang menentukan diferensiasi produk, atau melindungi pengetahuan kepemilikan dari kebocoran melalui pemasok. Sementara itu, integrasi ke depan memperkuat akses ke pelanggan akhir, memperbaiki visibilitas permintaan, dan memungkinkan kendali atas pengalaman pembeli (Thompson et al., 2024). Contoh di Indonesia adalah Grup Indofood yang terintegrasi dari produksi tepung terigu melalui Bogasari, manufaktur makanan olahan, hingga jaringan distribusi sendiri, sehingga mampu mengendalikan biaya, kualitas, dan ketersediaan produk di seluruh nusantara.</p>
      <h5>7.6.2 Kerugian Integrasi Vertikal</h5>
      <p>Di sisi lain, integrasi vertikal meningkatkan kebutuhan investasi modal dan risiko bisnis, memperlambat fleksibilitas perusahaan dalam mengganti teknologi atau pemasok ketika selera pembeli berubah, menimbulkan masalah penyeimbangan kapasitas antartahap rantai nilai, serta menuntut kapabilitas dan keterampilan yang sangat berbeda pada setiap tahap. Selain itu, unit internal yang terjamin pasarnya cenderung kehilangan disiplin biaya karena tidak menghadapi tekanan persaingan. Dari uraian tersebut dapat disimpulkan bahwa integrasi vertikal layak dipilih hanya apabila nilai strategis yang diciptakan melebihi tambahan biaya, risiko, dan kompleksitas administratifnya, sehingga manajemen perlu membandingkan opsi integrasi dengan alternatif kontrak jangka panjang atau kemitraan yang lebih longgar (Thompson et al., 2024).</p>`
    },
    {
      no: "7.7",
      title: "Strategi Outsourcing dalam Rantai Nilai",
      body: `<p>Berlawanan arah dengan integrasi vertikal, <em>outsourcing</em> mempersempit cakupan operasi perusahaan. Menurut Thompson et al. (2024), <em>outsourcing</em> adalah mengontrakkan aktivitas rantai nilai tertentu yang biasanya dilakukan sendiri kepada vendor luar. Keputusan ini pada hakikatnya merupakan keputusan <em>make or buy</em>, yaitu memilih antara memproduksi sendiri atau membeli dari pihak yang lebih kompeten dan lebih efisien.</p>
      <p><em>Outsourcing</em> masuk akal secara strategis apabila: (1) suatu aktivitas dapat dilakukan pihak luar dengan biaya lebih rendah atau kualitas lebih baik; (2) aktivitas tersebut bukan aktivitas krusial bagi keunggulan kompetitif dan tidak mengosongkan kapabilitas inti perusahaan; (3) <em>outsourcing</em> memperbaiki fleksibilitas organisasi dan mempercepat waktu ke pasar; (4) <em>outsourcing</em> mengurangi eksposur risiko terhadap perubahan teknologi dan preferensi pembeli; serta (5) penyerahan aktivitas memungkinkan perusahaan memusatkan energi dan sumber daya pada aktivitas inti yang paling dikuasainya (Thompson et al., 2024). Sebagai contoh, Apple menyerahkan perakitan produknya kepada mitra manufaktur kontrak agar dapat berfokus pada desain, perangkat lunak, dan pemasaran. Di Indonesia, banyak merek pakaian lokal dan jenama kecantikan menggunakan jasa produsen maklon sehingga mereka dapat berkonsentrasi pada pengembangan merek dan pemasaran digital tanpa investasi pabrik.</p>
      <p>Namun, <em>outsourcing</em> mengandung bahaya yang serius apabila perusahaan menyerahkan terlalu banyak aktivitas yang salah. Risiko terbesarnya adalah pengosongan kapabilitas internal (<em>hollowing out</em>), yaitu hilangnya keahlian dan pengetahuan yang dalam jangka panjang menentukan kesuksesan pasar, serta berkurangnya kendali atas kualitas dan ketepatan waktu pasokan. Selain itu, ketergantungan berlebihan pada pemasok tertentu dapat memberi pemasok kekuatan tawar yang besar, dan koordinasi lintas organisasi menuntut kapabilitas manajemen relasi yang baik. Oleh karena itu, aktivitas yang menjadi sumber keunggulan kompetitif tidak boleh diserahkan kepada pihak luar, dan perusahaan perlu memelihara kemampuan pengawasan teknis atas aktivitas yang dialihdayakan.</p>`
    },
    {
      no: "7.8",
      title: "Aliansi Strategis dan Kemitraan",
      body: `<p>Aliansi strategis merupakan jalan tengah antara mengerjakan sendiri dan mengakuisisi. Menurut Thompson et al. (2024), aliansi strategis adalah kesepakatan formal antara dua perusahaan atau lebih yang di dalamnya terdapat kolaborasi yang relevan secara strategis, kontribusi sumber daya bersama, pembagian risiko dan kendali, serta saling ketergantungan. Salah satu bentuk khususnya adalah <em>joint venture</em>, yaitu kemitraan yang melahirkan entitas korporasi baru yang dimiliki bersama para mitra. Aliansi dianggap strategis apabila membantu membangun, mempertahankan, atau memperkuat kompetensi inti dan keunggulan kompetitif, memblokir ancaman kompetitif, membuka peluang pasar baru, memitigasi risiko signifikan, atau memperkuat posisi tawar perusahaan.</p>
      <p>Manfaat aliansi paling besar dirasakan ketika perusahaan perlu mempercepat pengembangan teknologi atau produk baru yang menjanjikan, mengatasi ketertinggalan keahlian teknis, menghimpun kapabilitas komplementer, mempercepat masuk ke pasar geografis baru, serta berbagi biaya dan risiko proyek yang besar. Aliansi memberikan fleksibilitas yang tidak dimiliki merger karena hubungan dapat diakhiri ketika tujuannya tercapai. Contoh yang relevan di Indonesia adalah kemitraan panjang Astra International dengan Toyota Motor Corporation melalui Toyota Astra Motor, yang memadukan kapabilitas manufaktur dan jaringan distribusi lokal Astra dengan teknologi produk Toyota. Namun, aliansi juga rawan gagal karena perbedaan tujuan dan prioritas mitra, ketidakmampuan bekerja sama secara harmonis, munculnya rute teknologi yang lebih menarik, serta risiko mitra berubah menjadi pesaing setelah menyerap pengetahuan perusahaan (Thompson et al., 2024).</p>
      <p>Agar aliansi berhasil, perusahaan perlu memilih mitra yang cocok secara strategis dan budaya, peka terhadap perbedaan kebiasaan antarorganisasi, memastikan kedua pihak memperoleh manfaat yang seimbang, membangun komitmen yang kredibel, menciptakan mekanisme pengambilan keputusan yang cepat, serta mengelola proses pembelajaran dan menyesuaikan perjanjian seiring perubahan keadaan. Dengan demikian, kapabilitas mengelola aliansi itu sendiri dapat menjadi sumber keunggulan kompetitif, sebagaimana ditunjukkan perusahaan yang memiliki banyak kemitraan sekaligus dan mampu memetik nilai dari masing-masing hubungan tersebut.</p>`
    },
    {
      no: "7.9",
      title: "Alasan Perusahaan Memasuki Pasar Internasional",
      body: `<p>Bagian kedua sesi ini beralih pada persaingan lintas negara. Perusahaan yang bercita-cita menjadi pemimpin industri pada abad ke-21 dituntut berpikir dalam kerangka pasar global, bukan sekadar pasar domestik. Menurut Thompson et al. (2024), terdapat lima alasan utama perusahaan memperluas operasinya ke luar pasar dalam negeri, yaitu sebagai berikut:</p>
      <p>Pertama, memperoleh akses ke pelanggan baru. Ekspansi internasional menawarkan potensi pendapatan, laba, dan pertumbuhan jangka panjang, terutama ketika peluang pertumbuhan di pasar domestik mulai menipis, serta memungkinkan perusahaan memperpanjang siklus hidup produknya. Kedua, mencapai biaya yang lebih rendah melalui skala ekonomi, efek pengalaman, dan peningkatan daya beli gabungan, karena volume penjualan domestik saja sering tidak cukup untuk menangkap skala ekonomi dalam pengembangan produk, manufaktur, dan pemasaran. Ketiga, memperoleh akses ke masukan produksi berbiaya rendah, baik berupa sumber daya alam yang letaknya tersebar di berbagai negara maupun sumber daya manusia yang lebih murah. Keempat, mengeksploitasi lebih jauh kompetensi inti perusahaan dengan mereplikasi model bisnis yang sukses ke pasar baru, sebagaimana dilakukan Starbucks dan McDonald's. Kelima, memperoleh akses ke sumber daya dan kapabilitas yang berada di pasar asing, misalnya melalui akuisisi lintas negara atau aliansi untuk menyerap teknologi dan keahlian lokal (Thompson et al., 2024). Selain itu, perusahaan pemasok sering mengikuti pelanggan utamanya yang berekspansi ke luar negeri demi mempertahankan posisinya dalam rantai pasokan.</p>
      <p>Fenomena serupa dapat diamati pada perusahaan Indonesia. Indofood mengekspor dan memproduksi Indomie di berbagai negara Afrika dan Timur Tengah untuk menjangkau pelanggan baru dan memperpanjang siklus hidup produknya, sedangkan Kalbe Farma berekspansi ke pasar ASEAN untuk memanfaatkan kompetensi intinya di bidang farmasi dan produk kesehatan. Implikasi manajerialnya, motif internasionalisasi harus dirumuskan secara eksplisit karena motif tersebut menentukan pilihan negara tujuan, moda masuk, dan konfigurasi rantai nilai yang tepat.</p>`
    },
    {
      no: "7.10",
      title: "Kompleksitas Penyusunan Strategi Lintas Negara",
      body: `<p>Menyusun strategi untuk bersaing di banyak negara jauh lebih kompleks daripada bersaing di dalam negeri karena lima alasan, yaitu perbedaan keunggulan negara asal pada industri tertentu, adanya keunggulan berbasis lokasi dalam menjalankan aktivitas rantai nilai, perbedaan kondisi politik dan ekonomi antarnegara, risiko pergeseran nilai tukar mata uang, serta perbedaan selera pembeli yang menimbulkan dilema antara kustomisasi dan standardisasi (Thompson et al., 2024).</p>
      <h5>7.10.1 Model Berlian Keunggulan Kompetitif Nasional</h5>
      <p>Negara-negara tertentu dikenal kuat pada industri tertentu, dan kekuatan tersebut dijelaskan oleh kerangka <em>Diamond of National Competitive Advantage</em> dari Michael Porter. Kerangka ini terdiri atas empat faktor yang saling memperkuat, yaitu: (1) kondisi permintaan (<em>demand conditions</em>), mencakup ukuran, pertumbuhan, dan kecanggihan pembeli di pasar dalam negeri; (2) kondisi faktor (<em>factor conditions</em>), yaitu ketersediaan dan harga relatif masukan produksi seperti tenaga kerja, bahan baku, modal, dan infrastruktur; (3) industri terkait dan pendukung, yaitu kedekatan pemasok, pengguna akhir, dan industri komplementer yang menciptakan klaster; serta (4) strategi, struktur, dan persaingan perusahaan, termasuk intensitas persaingan domestik yang menempa daya saing. Cara menggunakan kerangka ini ada dua, yaitu untuk memprediksi dari negara mana pesaing asing yang tangguh kemungkinan muncul, dan untuk memilih lokasi aktivitas rantai nilai yang paling menguntungkan (Thompson et al., 2024).</p>
      <h5>7.10.2 Lokasi, Risiko Politik, Risiko Nilai Tukar, dan Perbedaan Permintaan</h5>
      <p>Keunggulan berbasis lokasi mendorong perusahaan menempatkan aktivitas tertentu di negara dengan biaya masukan rendah atau kapabilitas khusus, misalnya perakitan padat karya di negara berupah rendah dan riset di negara dengan talenta ilmiah melimpah. Selain itu, perusahaan menghadapi risiko politik berupa ketidakstabilan kebijakan, regulasi yang memberatkan, hingga kemungkinan nasionalisasi aset, serta risiko ekonomi seperti lemahnya penegakan hak kekayaan intelektual. Risiko nilai tukar juga penting karena pergeseran kurs dapat mengubah keunggulan biaya suatu lokasi produksi; pelemahan mata uang negara produsen membuat ekspor dari negara tersebut lebih kompetitif, sedangkan penguatannya menggerus daya saing. Terakhir, perbedaan demografi, budaya, dan preferensi pasar antarnegara memaksa perusahaan memilih antara menyesuaikan produk untuk setiap negara dengan konsekuensi biaya lebih tinggi, atau menstandarkan produk demi efisiensi dengan risiko kurang diterima pembeli lokal. Dilema inilah yang menjadi dasar pilihan pendekatan strategi internasional pada sub-bab 7.12.</p>`
    },
    {
      no: "7.11",
      title: "Lima Moda Masuk ke Pasar Internasional",
      body: `<p>Perusahaan yang memutuskan berekspansi ke luar negeri harus memilih moda masuk yang sesuai dengan sumber daya, tingkat risiko yang dapat ditanggung, dan derajat kendali yang diinginkan. Thompson et al. (2024) mengidentifikasi lima moda utama, yaitu ekspor, lisensi, waralaba, anak perusahaan asing, serta aliansi dan <em>joint venture</em>. Perbandingan kelima moda tersebut disajikan pada Tabel 7.1.</p>
      <table class="bk-table"><caption>Tabel 7.1 Perbandingan Moda Masuk Pasar Internasional</caption>
      <thead><tr><th>Moda Masuk</th><th>Keunggulan Utama</th><th>Kelemahan Utama</th></tr></thead>
      <tbody>
      <tr><td>Ekspor</td><td>Investasi dan risiko rendah; memanfaatkan skala pabrik domestik</td><td>Biaya pengiriman dan tarif; rentan pergeseran kurs; kendali pemasaran terbatas</td></tr>
      <tr><td>Lisensi</td><td>Menghasilkan royalti tanpa investasi besar di negara tujuan</td><td>Risiko kebocoran pengetahuan teknologi; kendali atas mutu lemah</td></tr>
      <tr><td>Waralaba</td><td>Ekspansi cepat untuk bisnis jasa dengan modal terwaralaba</td><td>Pengendalian kualitas lintas negara sulit; ketergantungan pada mitra lokal</td></tr>
      <tr><td>Anak perusahaan asing (akuisisi atau greenfield)</td><td>Kendali penuh atas operasi dan strategi; kehadiran pasar yang kuat</td><td>Kebutuhan modal terbesar; risiko tertinggi; proses pembangunan atau integrasi lama</td></tr>
      <tr><td>Aliansi dan joint venture</td><td>Berbagi risiko dan biaya; akses pengetahuan dan jaringan mitra lokal</td><td>Potensi konflik tujuan; risiko mitra menjadi pesaing; kendali terbagi</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot></table>
      <p>Strategi ekspor menggunakan pabrik domestik sebagai basis produksi dan cocok sebagai langkah awal berbiaya rendah untuk menguji pasar asing. Strategi lisensi tepat ketika perusahaan memiliki pengetahuan teknis atau paten yang bernilai namun tidak memiliki kapabilitas atau keinginan berinvestasi langsung di luar negeri. Strategi waralaba lazim digunakan perusahaan jasa dan restoran, sebagaimana dilakukan McDonald's dan juga jenama Indonesia seperti Kopi Kenangan dan Es Teh Indonesia ketika memasuki pasar Asia Tenggara. Strategi anak perusahaan asing dapat ditempuh melalui akuisisi perusahaan lokal yang memberikan kecepatan masuk, atau melalui <em>greenfield venture</em>, yaitu pendirian anak perusahaan baru dari nol yang memberikan kendali penuh atas kapabilitas yang dibangun. <em>Greenfield</em> menarik ketika perusahaan telah memahami pasar tujuan, volume pasar cukup besar, dan waktu bukan kendala utama. Terakhir, aliansi dan <em>joint venture</em> memungkinkan perusahaan berbagi risiko serta memperoleh pengetahuan pasar lokal, dan di sejumlah negara bahkan menjadi keharusan regulasi bagi investor asing. Dengan demikian, pilihan moda masuk merupakan pertukaran (<em>trade-off</em>) antara tingkat investasi, tingkat risiko, kecepatan masuk, dan derajat kendali.</p>`
    },
    {
      no: "7.12",
      title: "Tiga Pendekatan Strategis Bersaing Internasional",
      body: `<p>Setelah menentukan moda masuk, perusahaan harus memilih pendekatan strategis menyeluruh yang menyeimbangkan dua tekanan yang saling berlawanan, yaitu tekanan untuk responsif terhadap kebutuhan lokal dan tekanan untuk mencapai efisiensi melalui integrasi global. Thompson et al. (2024) membedakan tiga pendekatan utama sebagaimana diringkas pada Tabel 7.2.</p>
      <table class="bk-table"><caption>Tabel 7.2 Perbandingan Strategi Multidomestik, Global, dan Transnasional</caption>
      <thead><tr><th>Aspek</th><th>Multidomestik</th><th>Global</th><th>Transnasional</th></tr></thead>
      <tbody>
      <tr><td>Slogan pendekatan</td><td>Think local, act local</td><td>Think global, act global</td><td>Think global, act local</td></tr>
      <tr><td>Produk dan pemasaran</td><td>Disesuaikan penuh per negara</td><td>Terstandar di seluruh dunia dengan penyesuaian minimal</td><td>Standar inti dengan adaptasi lokal terpilih</td></tr>
      <tr><td>Keunggulan utama</td><td>Memenuhi kebutuhan spesifik tiap pasar</td><td>Biaya rendah dari skala dan ruang lingkup ekonomi</td><td>Menggabungkan responsivitas lokal dan efisiensi global</td></tr>
      <tr><td>Kelemahan utama</td><td>Menghambat berbagi sumber daya antarnegara dan menaikkan biaya</td><td>Kurang mampu menjawab kebutuhan lokal secara presisi</td><td>Lebih kompleks dan lebih sulit diimplementasikan</td></tr>
      <tr><td>Kondisi yang cocok</td><td>Perbedaan antarnegara besar</td><td>Preferensi pembeli relatif seragam</td><td>Kedua tekanan sama-sama kuat</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot></table>
      <p>Strategi multidomestik memberikan otonomi luas kepada manajer di setiap negara untuk menyesuaikan produk, pemasaran, dan operasi dengan kondisi setempat. Pendekatan ini tepat ketika perbedaan selera, budaya, dan regulasi antarnegara besar, namun mengorbankan efisiensi karena duplikasi aktivitas dan menghambat transfer kapabilitas antarunit. Strategi global memperlakukan dunia sebagai satu pasar dengan produk dan pendekatan kompetitif yang pada dasarnya sama di semua negara, sehingga memaksimalkan skala ekonomi, efek kurva pembelajaran, dan koordinasi terpusat, namun kurang lentur terhadap kebutuhan lokal. Strategi transnasional berupaya menggabungkan keduanya dengan menstandarkan elemen inti sambil mengadaptasi elemen yang sensitif secara lokal, dengan konsekuensi kompleksitas organisasi yang paling tinggi (Thompson et al., 2024).</p>
      <p>Contoh penerapannya dapat diamati pada industri makanan. Indomie menerapkan corak multidomestik ketika mengembangkan varian rasa yang berbeda untuk pasar Nigeria dan Arab Saudi sesuai selera lokal, sementara produsen komponen elektronik cenderung memakai strategi global karena spesifikasi produknya seragam di seluruh dunia. Unilever, termasuk operasinya di Indonesia, sering dirujuk sebagai contoh pendekatan transnasional karena memadukan merek dan riset global dengan adaptasi produk serta distribusi yang sangat lokal. Implikasi manajerialnya, pilihan pendekatan harus konsisten dengan struktur organisasi, sistem insentif, dan lokasi pengambilan keputusan perusahaan.</p>`
    },
    {
      no: "7.13",
      title: "Operasi Internasional dan Pencarian Keunggulan Kompetitif",
      body: `<p>Bersaing di banyak negara membuka tiga jalan tambahan untuk membangun keunggulan kompetitif yang tidak tersedia bagi perusahaan yang hanya beroperasi di satu negara (Thompson et al., 2024). Ketiganya perlu dikelola secara sadar agar kehadiran internasional benar-benar meningkatkan daya saing keseluruhan, bukan sekadar memperluas penjualan.</p>
      <h5>7.13.1 Memanfaatkan Lokasi</h5>
      <p>Jalan pertama adalah menggunakan lokasi untuk menurunkan biaya atau mencapai diferensiasi yang lebih besar. Keputusan kuncinya adalah apakah memusatkan setiap aktivitas pada sedikit negara atau menyebarkannya ke banyak negara. Pemusatan tepat ketika skala ekonomi signifikan, efek kurva pembelajaran kuat, atau lokasi tertentu memiliki sumber daya unggul, misalnya pemusatan produksi cip semikonduktor di Taiwan. Sebaliknya, penyebaran aktivitas lebih tepat untuk aktivitas yang harus dekat dengan pembeli seperti distribusi dan layanan purnajual, atau untuk mengurangi risiko gangguan pasokan dan fluktuasi kurs.</p>
      <h5>7.13.2 Berbagi dan Mentransfer Sumber Daya serta Kapabilitas Lintas Negara</h5>
      <p>Jalan kedua adalah membagikan dan mentransfer sumber daya serta kapabilitas bernilai kompetitif antarunit di berbagai negara, misalnya mereplikasi merek yang kuat, sistem operasi yang teruji, atau keahlian pemasaran dari satu pasar ke pasar lain. Transfer semacam ini menurunkan biaya membangun kapabilitas dari nol di setiap negara dan mempercepat penguatan posisi di pasar baru. Perusahaan multinasional yang efektif juga belajar dari operasi asingnya dan membawa pengetahuan baru tersebut kembali ke seluruh jaringan perusahaan.</p>
      <h5>7.13.3 Koordinasi Lintas Negara dan Manuver Lintas Batas</h5>
      <p>Jalan ketiga adalah manfaat koordinasi lintas negara, seperti memindahkan produksi antarpabrik ketika kurs atau biaya berubah, menyalurkan keahlian terbaik ke lokasi yang paling membutuhkan, dan menyinkronkan peluncuran produk global. Selain itu, perusahaan multinasional dapat memanfaatkan <em>profit sanctuaries</em>, yaitu pasar negara tertentu di mana perusahaan memiliki posisi terlindungi dan menuai laba besar, sebagai sumber dana untuk mendukung ofensif strategis di pasar lain melalui praktik subsidi silang (<em>cross-market subsidization</em>). Kemampuan ini juga penting untuk bertahan, karena perusahaan yang memiliki kehadiran di pasar asal pesaing dapat melakukan serangan balasan langsung ke sumber laba pesaing tersebut sehingga menciptakan efek gentar. Oleh karena itu, perusahaan domestik yang menghadapi rival internasional perlu memperhitungkan kemungkinan subsidi silang semacam ini dalam merancang pertahanannya (Thompson et al., 2024).</p>`
    },
    {
      no: "7.14",
      title: "Bersaing di Pasar Negara Berkembang",
      body: `<p>Pasar negara berkembang seperti Tiongkok, India, Brasil, Indonesia, dan negara-negara Afrika menawarkan potensi pertumbuhan yang sangat besar sekaligus tantangan yang khas, antara lain daya beli konsumen yang terbatas dan sensitif harga, infrastruktur distribusi yang belum merata, lemahnya perlindungan kekayaan intelektual, serta campur tangan pemerintah yang lebih besar (Thompson et al., 2024). Oleh karena itu, strategi yang berhasil di negara maju jarang dapat dipindahkan begitu saja ke pasar berkembang.</p>
      <p>Pilihan strategi bagi perusahaan multinasional yang memasuki pasar berkembang meliputi: (1) bersaing dengan harga sangat rendah melalui perancangan ulang produk agar sesuai kemampuan beli lokal; (2) memodifikasi model bisnis atau produk untuk mengakomodasi keadaan lokal, misalnya kemasan sachet kecil untuk produk konsumen yang memungkinkan pembelian harian oleh konsumen berpendapatan rendah, praktik yang justru dipelopori operasi Unilever di Asia Tenggara termasuk Indonesia; (3) berupaya mengubah pasar lokal agar lebih sesuai dengan cara perusahaan berbisnis di tempat lain, misalnya dengan membangun sendiri jaringan rantai dingin atau logistik; atau (4) menjauhi pasar yang biaya adaptasinya terlalu tinggi dibandingkan potensinya (Thompson et al., 2024). Kuncinya adalah kesabaran, kesediaan berinvestasi jangka panjang, dan penghormatan terhadap konteks lokal.</p>
      <p>Sebaliknya, perusahaan lokal di negara berkembang tidak selalu kalah menghadapi raksasa global. Strategi bertahan dan menyerang bagi perusahaan lokal mencakup: (1) mengembangkan model bisnis yang mengeksploitasi kelemahan pesaing global, misalnya penguasaan jaringan distribusi tradisional; (2) memanfaatkan pemahaman superior atas kebutuhan dan kebiasaan pelanggan lokal untuk menciptakan produk yang lebih sesuai; (3) memanfaatkan keunggulan tenaga kerja berbiaya rendah dan aset lokal lainnya; (4) menggunakan strategi akuisisi dan pertumbuhan cepat untuk membendung ekspansi pesaing asing; serta (5) memindahkan keahlian perusahaan ke pasar lintas batas dan mulai bersaing pada level internasional. Contoh di Indonesia adalah keberhasilan merek kosmetik Wardah membaca kebutuhan konsumen muslimah lokal sehingga mampu bersaing dengan merek multinasional, serta ekspansi J&T Express dari basis Asia Tenggara menuju pasar global logistik. Dengan demikian, keunggulan berbasis pengetahuan lokal dapat menjadi batu loncatan menuju daya saing internasional.</p>`
    },
    {
      no: "7.15",
      title: "Rangkuman",
      body: `<p>Sesi ini menegaskan bahwa kekuatan strategi kompetitif perusahaan dapat ditingkatkan melalui serangkaian keputusan pelengkap. Strategi ofensif digunakan untuk merebut posisi pasar dengan bertumpu pada kekuatan terbesar perusahaan dan diarahkan pada kelemahan pesaing, sedangkan strategi defensif melindungi posisi melalui pemblokiran jalur serangan dan pemberian sinyal pembalasan. Penentuan waktu langkah strategis menuntut penilaian cermat atas kondisi yang menguntungkan <em>first mover</em>, <em>fast follower</em>, atau <em>late mover</em>. Selanjutnya, cakupan operasi dapat diperluas melalui merger dan akuisisi horizontal serta integrasi vertikal, atau dipersempit melalui <em>outsourcing</em>, sementara aliansi strategis menawarkan jalan tengah kolaboratif untuk mengakses sumber daya dan kapabilitas mitra tanpa kehilangan fleksibilitas (Thompson et al., 2024).</p>
      <p>Pada arena internasional, perusahaan berekspansi untuk memperoleh pelanggan baru, menurunkan biaya, mengakses masukan murah, mengeksploitasi kompetensi inti, dan menyerap kapabilitas asing. Penyusunan strategi lintas negara lebih kompleks karena perbedaan keunggulan negara asal yang dijelaskan model berlian Porter, keunggulan berbasis lokasi, risiko politik dan nilai tukar, serta perbedaan preferensi pembeli. Perusahaan memilih di antara lima moda masuk, yaitu ekspor, lisensi, waralaba, anak perusahaan asing, serta aliansi dan <em>joint venture</em>, kemudian menetapkan pendekatan multidomestik, global, atau transnasional sesuai keseimbangan tekanan responsivitas lokal dan efisiensi global.</p>
      <p>Akhirnya, operasi internasional membuka sumber keunggulan tambahan melalui pemanfaatan lokasi, transfer sumber daya lintas negara, koordinasi lintas batas, dan subsidi silang dari <em>profit sanctuaries</em>. Pasar negara berkembang menuntut adaptasi model bisnis yang mendalam, sementara perusahaan lokal dapat memanfaatkan pengetahuan pasar setempat sebagai basis pertahanan sekaligus batu loncatan internasionalisasi. Dengan demikian, manajer strategis dituntut memadukan keputusan cakupan, waktu, dan arena geografis secara koheren agar keunggulan kompetitif perusahaan bersifat berkelanjutan.</p>`
    },
    {
      no: "7.16",
      title: "Daftar Pustaka",
      body: `<p>Thompson, A. A., Peteraf, M. A., Gamble, J. E. dan Strickland, A. J. (2024). <em>Crafting and Executing Strategy: The Quest for Competitive Advantage, Concepts and Cases</em>. 2024 Release. New York: McGraw Hill.</p>
      <p>Porter, M. E. (1990). The Competitive Advantage of Nations. <em>Harvard Business Review</em>, Maret-April 1990, hlm. 73-93.</p>
      <p>Kim, W. C. dan Mauborgne, R. (2015). <em>Blue Ocean Strategy</em>. Edisi Diperluas. Boston: Harvard Business Review Press.</p>`
    }
  ]
};
