window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.sm = window.MBA_BOOK.sm || {};
window.MBA_BOOK.sm[3] = {
  bab: 3,
  judul: "BAB 3 MENETAPKAN ARAH PERUSAHAAN: VISI, MISI, TUJUAN, DAN STRATEGI",
  sumber: "Thompson, Peteraf, Gamble dan Strickland (2024), Crafting and Executing Strategy, 2024 Release, McGraw Hill",
  lo: [
    "LO 2-1 Memahami mengapa manajer sangat perlu memiliki visi strategis yang jelas mengenai arah yang hendak dituju perusahaan.",
    "LO 2-2 Menjelaskan pentingnya penetapan tujuan strategis dan tujuan keuangan secara bersamaan.",
    "LO 2-3 Menjelaskan mengapa inisiatif strategis yang diambil pada berbagai tingkat organisasi harus dikoordinasikan secara erat.",
    "LO 2-4 Mengenali hal-hal yang harus dilakukan perusahaan untuk mencapai keunggulan operasi dan mengeksekusi strategi secara cakap.",
    "LO 2-5 Memahami peran dan tanggung jawab dewan direksi perusahaan dalam mengawasi proses manajemen strategik."
  ],
  sections: [
    {
      no: "3.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi ketiga mata kuliah Manajemen Strategik membahas proses penetapan arah perusahaan yang mencakup pengembangan visi strategis, perumusan misi, penetapan nilai inti, penetapan tujuan, perumusan strategi, eksekusi strategi, serta evaluasi kinerja dan tata kelola korporat. Materi sesi ini bersumber dari Bab 2 buku Thompson, Peteraf, Gamble dan Strickland (2024) yang menempatkan penetapan arah sebagai tanggung jawab paling mendasar dari manajemen puncak. Pemahaman atas proses ini menjadi fondasi bagi seluruh pembahasan analisis lingkungan eksternal dan internal pada sesi-sesi berikutnya.</p>
      <p>Setelah mengikuti sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
      <p>Pertama, memahami mengapa manajer sangat perlu memiliki visi strategis yang jelas mengenai arah yang hendak dituju perusahaan. Kedua, menjelaskan pentingnya penetapan tujuan strategis dan tujuan keuangan secara bersamaan. Ketiga, menjelaskan mengapa inisiatif strategis yang diambil pada berbagai tingkat organisasi harus dikoordinasikan secara erat. Keempat, mengenali hal-hal yang harus dilakukan perusahaan untuk mencapai keunggulan operasi dan mengeksekusi strategi secara cakap. Kelima, memahami peran dan tanggung jawab dewan direksi dalam mengawasi proses manajemen strategik.</p>`
    },
    {
      no: "3.2",
      title: "Proses Perumusan dan Eksekusi Strategi",
      body: `<p>Setiap perusahaan yang ingin bertumbuh secara berkelanjutan memerlukan kejelasan mengenai arah jangka panjang yang hendak dituju. Menurut Thompson, Peteraf, Gamble dan Strickland (2024), perumusan dan eksekusi strategi merupakan proses berkelanjutan yang terdiri atas lima tahap yang saling berkaitan. Kelima tahap tersebut bukan merupakan urutan yang berjalan satu kali selesai, melainkan siklus yang terus berulang seiring perubahan kondisi lingkungan bisnis. Oleh karena itu, manajemen tidak dapat memandang strategi sebagai dokumen statis yang disusun sekali dalam beberapa tahun.</p>
      <p>Kelima tahap dalam proses perumusan dan eksekusi strategi tersebut adalah sebagai berikut:</p>
      <p>Tahap pertama adalah mengembangkan visi strategis yang memetakan arah jangka panjang perusahaan, pernyataan misi yang menggambarkan tujuan keberadaan perusahaan, serta seperangkat nilai inti yang memandu pencapaian visi dan misi. Tahap kedua adalah menetapkan tujuan sebagai tolok ukur kinerja dan kemajuan perusahaan. Tahap ketiga adalah merumuskan strategi untuk mencapai tujuan dan menggerakkan perusahaan pada lintasan yang telah ditetapkan. Tahap keempat adalah mengeksekusi strategi terpilih secara efisien dan efektif. Tahap kelima adalah memantau perkembangan, mengevaluasi kinerja, dan melakukan penyesuaian korektif terhadap visi, misi, tujuan, strategi, maupun pendekatan eksekusi berdasarkan pengalaman aktual, perubahan kondisi, gagasan baru, dan peluang baru.</p>
      <p>Tiga tahap pertama dari proses tersebut menghasilkan sebuah <em>strategic plan</em> atau rencana strategis. Rencana strategis memetakan ke mana perusahaan menuju, menetapkan target strategis dan keuangan, serta menguraikan model bisnis dasar dan langkah kompetitif yang akan digunakan untuk mencapai hasil bisnis yang diinginkan (Thompson et al., 2024). Dengan demikian, rencana strategis merupakan wujud terdokumentasi dari komitmen arah yang telah disepakati manajemen puncak dan menjadi acuan bagi seluruh unit organisasi.</p>
      <p>Keputusan-keputusan dalam proses manajemen strategik harus dibentuk oleh pertimbangan eksternal dan internal. Pertimbangan eksternal mencakup daya tarik peluang pertumbuhan pada lintasan strategis saat ini, kekuatan persaingan industri, faktor pendorong perubahan industri, posisi dan kemungkinan langkah pesaing, serta faktor kunci keberhasilan kompetitif masa depan. Di sisi lain, pertimbangan internal mencakup daya tarik proposisi nilai pelanggan, kekuatan sumber daya dan kapabilitas kompetitif, kemampuan menangkap peluang pasar, daya saing biaya, serta posisi kekuatan relatif terhadap pesaing utama. Kedua kelompok pertimbangan tersebut akan dibahas secara mendalam melalui alat analisis lingkungan eksternal dan internal pada bab-bab berikutnya.</p>
      <p>Konsep penting yang melekat pada tahap evaluasi adalah <em>strategic inflection point</em>, yaitu titik ketika besarnya perubahan industri menuntut manajemen mempertimbangkan perubahan visi strategis perusahaan (Thompson et al., 2024). Pada titik tersebut manajemen menghadapi keputusan sulit karena meninggalkan lintasan yang sudah mapan mengandung risiko besar, sementara bertahan pada lintasan lama berpotensi menjebak perusahaan dalam bisnis yang stagnan atau menurun. Contoh di Indonesia dapat dilihat pada industri media cetak yang menghadapi disrupsi digital, di mana kelompok usaha seperti Kompas Gramedia harus mengubah visi dari perusahaan penerbitan menjadi kelompok media dan digital yang terdiversifikasi. Implikasi manajerialnya adalah manajemen harus secara berkala menguji apakah asumsi yang mendasari visi dan strategi masih relevan dengan realitas pasar.</p>`
    },
    {
      no: "3.3",
      title: "Tahap 1: Mengembangkan Visi Strategis, Misi, dan Nilai Inti",
      body: `<p>Pada tahap paling awal dari proses perumusan strategi, manajemen puncak harus bergulat dengan pertanyaan mengenai lintasan arah yang sebaiknya ditempuh perusahaan. Pertanyaan tersebut mencakup apakah prospek perusahaan dapat ditingkatkan dengan mengubah penawaran produk, pasar yang dilayani, atau pelanggan yang dituju. Jawaban atas pertanyaan tersebut dituangkan dalam tiga instrumen penetapan arah, yaitu visi strategis, pernyataan misi, dan nilai inti.</p>
      <h5>3.3.1 Mengembangkan Visi Strategis</h5>
      <p>Visi strategis merupakan pandangan manajemen puncak mengenai arah jangka panjang perusahaan dan bauran produk, pasar, dan pelanggan yang dinilai optimal untuk masa depan. Menurut Thompson, Peteraf, Gamble dan Strickland (2024), visi strategis menggambarkan aspirasi manajemen bagi masa depan perusahaan beserta lintasan dan arah yang ditetapkan untuk mencapainya. Dari definisi tersebut dapat disimpulkan bahwa visi strategis menjawab pertanyaan mendasar mengenai ke mana perusahaan akan menuju, sekaligus memberikan alasan bisnis yang meyakinkan mengapa arah tersebut masuk akal. Visi yang jelas mengarahkan organisasi pada arah tertentu, membangun komitmen terhadap tindakan masa depan, dan membentuk identitas organisasi.</p>
      <p>Visi yang dirumuskan dengan baik bersifat khas dan spesifik bagi organisasi tertentu, bukan pernyataan generik yang dapat berlaku bagi perusahaan mana pun. Buku teks mencontohkan visi Google, yaitu <em>"to organize the world's information and make it universally accessible and useful"</em> (Thompson et al., 2024), yang berhasil menjadi dasar perumusan tindakan strategis dan penggerak mobilisasi sumber daya internal. Sebaliknya, pernyataan yang bombastis dan hampa seperti menjadi pemimpin global pilihan pertama pelanggan di setiap pasar tidak memberikan panduan arah yang berarti. Karakteristik visi yang efektif antara lain bersifat grafis, berorientasi ke depan, terfokus, fleksibel terhadap perubahan, layak dicapai, masuk akal secara bisnis, dan mudah dikomunikasikan. Sebagai contoh Indonesia, visi GoTo untuk mendorong kemajuan dengan memberdayakan konsumen, mitra pengemudi, dan pedagang dalam satu ekosistem digital memberikan arah yang spesifik bagi keputusan pengembangan layanan dari transportasi, perdagangan elektronik, hingga layanan keuangan.</p>
      <h5>3.3.2 Mengomunikasikan Visi Strategis</h5>
      <p>Visi strategis hanya memberikan nilai apabila dikomunikasikan secara efektif ke seluruh jenjang organisasi hingga memperoleh penerimaan yang luas dari karyawan. Komunikasi visi yang efektif menuntut manajemen menjelaskan alasan di balik pilihan arah, menjawab kekhawatiran karyawan mengenai dampak perubahan, dan menggunakan bahasa yang membangkitkan semangat. Banyak perusahaan meringkas esensi visinya dalam slogan yang mudah diingat agar dapat berfungsi sebagai pengingat arah bersama. Menurut Thompson et al. (2024), visi yang dikomunikasikan dengan baik memberikan sejumlah manfaat, yaitu mengkristalkan pandangan eksekutif mengenai arah jangka panjang, mengurangi risiko keputusan yang tidak berarah, memperoleh dukungan karyawan, menjadi mercusuar bagi manajer tingkat bawah dalam menyusun tujuan dan strategi unit, serta membantu organisasi mempersiapkan diri menghadapi masa depan. Implikasi manajerialnya adalah komunikasi visi merupakan investasi kepemimpinan, bukan sekadar aktivitas hubungan masyarakat.</p>
      <h5>3.3.3 Merumuskan Pernyataan Misi</h5>
      <p>Pernyataan misi berbeda dengan visi strategis meskipun keduanya sering dipertukarkan dalam praktik. Visi menggambarkan arah masa depan perusahaan, sedangkan misi menggambarkan tujuan keberadaan dan lingkup bisnis perusahaan pada saat ini (Thompson et al., 2024). Pernyataan misi yang dirumuskan dengan baik mengidentifikasi produk atau jasa perusahaan, menspesifikasi kebutuhan pembeli yang dipenuhi dan kelompok pelanggan yang dilayani, serta memberikan identitas yang membedakan perusahaan dari pesaing. Idealnya pernyataan misi cukup deskriptif sehingga pembaca dapat mengenali bisnis perusahaan hanya dari pernyataan tersebut. Perlu dicatat bahwa misi jarang menyebut laba secara eksplisit karena laba merupakan hasil dari pemenuhan misi, bukan misi itu sendiri; perusahaan yang menyatakan misinya sekadar menghasilkan laba belum menjelaskan bisnis apa yang dijalankan untuk menghasilkan laba tersebut.</p>
      <h5>3.3.4 Menautkan Visi dan Misi dengan Nilai Inti</h5>
      <p>Nilai inti atau <em>core values</em> adalah keyakinan, sifat, dan norma perilaku yang diharapkan manajemen ditampilkan karyawan dalam menjalankan bisnis dan mengejar visi serta misi perusahaan. Nilai inti umumnya berjumlah empat sampai delapan butir dan mencakup hal-hal seperti integritas, perilaku etis, inovasi, kerja tim, kualitas unggul, layanan pelanggan, dan tanggung jawab sosial. Pada perusahaan yang menerapkannya secara sungguh-sungguh, nilai inti menjadi budaya nyata yang membentuk keputusan sehari-hari, sedangkan pada perusahaan lain nilai hanya menjadi hiasan jendela tanpa pengaruh perilaku. Buku teks mengilustrasikan keterpaduan visi, misi, dan nilai pada IKEA yang menautkan visi menciptakan kehidupan sehari-hari yang lebih baik bagi banyak orang dengan nilai kesederhanaan, kebersamaan, dan kesadaran biaya (Thompson et al., 2024). Perbandingan ketiga instrumen arah tersebut disajikan pada Tabel 3.1 berikut.</p>
      <table class="bk-table"><caption>Tabel 3.1 Perbandingan Visi Strategis, Pernyataan Misi, dan Nilai Inti</caption>
      <thead><tr><th>Aspek</th><th>Visi Strategis</th><th>Pernyataan Misi</th><th>Nilai Inti</th></tr></thead>
      <tbody>
      <tr><td>Pertanyaan yang dijawab</td><td>Ke mana perusahaan akan menuju</td><td>Siapa kami dan apa yang kami lakukan saat ini</td><td>Bagaimana kami berperilaku dalam menjalankan bisnis</td></tr>
      <tr><td>Orientasi waktu</td><td>Masa depan jangka panjang</td><td>Masa kini</td><td>Berlaku sepanjang waktu</td></tr>
      <tr><td>Isi utama</td><td>Aspirasi arah dan bauran produk, pasar, dan pelanggan masa depan</td><td>Produk atau jasa, kebutuhan pembeli, kelompok pelanggan, dan identitas perusahaan</td><td>Keyakinan, sifat, dan norma perilaku yang diharapkan</td></tr>
      <tr><td>Fungsi manajerial</td><td>Mengarahkan alokasi sumber daya dan membangun komitmen</td><td>Memberi batasan lingkup bisnis dan identitas</td><td>Memandu perilaku dan membentuk budaya organisasi</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Thompson, Peteraf, Gamble dan Strickland (2024)</td></tr></tfoot></table>`
    },
    {
      no: "3.4",
      title: "Tahap 2: Menetapkan Tujuan",
      body: `<p>Tahap kedua dari proses manajemen strategik adalah mengubah visi dan misi menjadi tujuan kinerja yang spesifik. Tujuan atau <em>objectives</em> adalah target kinerja organisasi, yaitu hasil spesifik yang ingin dicapai manajemen dalam kurun waktu tertentu. Tujuan yang dirumuskan dengan baik harus spesifik, terukur atau dapat dikuantifikasi, memiliki tenggat waktu, dan menantang namun dapat dicapai. Fungsi manajerial dari penetapan tujuan adalah menjadikan visi operasional, memfokuskan energi organisasi, menjadi tolok ukur evaluasi kinerja, dan mendorong perusahaan berkinerja pada potensi penuhnya. Tanpa tujuan yang terukur, pernyataan visi hanya akan menjadi retorika yang tidak dapat diverifikasi pencapaiannya.</p>
      <h5>3.4.1 Tujuan Strategis dan Tujuan Keuangan</h5>
      <p>Menurut Thompson, Peteraf, Gamble dan Strickland (2024), terdapat dua jenis tujuan yang harus ditetapkan setiap perusahaan, yaitu tujuan keuangan dan tujuan strategis. Tujuan keuangan berkaitan dengan target kinerja keuangan seperti pertumbuhan pendapatan, margin laba, imbal hasil atas investasi, arus kas internal, dan kekuatan neraca. Di sisi lain, tujuan strategis berkaitan dengan posisi pemasaran dan vitalitas kompetitif perusahaan, misalnya peningkatan pangsa pasar, kualitas produk yang lebih unggul dari pesaing, biaya yang lebih rendah dari pesaing, cakupan geografis yang lebih luas, dan keunggulan teknologi. Perbandingan kedua jenis tujuan disajikan pada Tabel 3.2.</p>
      <table class="bk-table"><caption>Tabel 3.2 Perbandingan Tujuan Keuangan dan Tujuan Strategis</caption>
      <thead><tr><th>Aspek</th><th>Tujuan Keuangan</th><th>Tujuan Strategis</th></tr></thead>
      <tbody>
      <tr><td>Fokus</td><td>Hasil kinerja keuangan perusahaan</td><td>Posisi pasar dan vitalitas kompetitif</td></tr>
      <tr><td>Sifat indikator</td><td><em>Lagging indicators</em>, mencerminkan hasil keputusan masa lalu</td><td><em>Leading indicators</em>, meramalkan kinerja keuangan masa depan</td></tr>
      <tr><td>Contoh ukuran</td><td>Pertumbuhan pendapatan tahunan, margin laba bersih, <em>return on equity</em>, arus kas operasi, peringkat kredit</td><td>Pangsa pasar, waktu peluncuran produk baru, tingkat kepuasan pelanggan, keunggulan biaya relatif, cakupan distribusi</td></tr>
      <tr><td>Risiko bila diabaikan</td><td>Kesulitan pendanaan dan hilangnya kepercayaan investor</td><td>Erosi daya saing yang menggerus kinerja keuangan jangka panjang</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Thompson, Peteraf, Gamble dan Strickland (2024)</td></tr></tfoot></table>
      <p>Kedua jenis tujuan tersebut harus ditetapkan secara berimbang karena kinerja keuangan yang baik saat ini tidak menjamin daya saing masa depan. Tujuan keuangan pada dasarnya merupakan indikator tertinggal yang mencerminkan hasil keputusan masa lalu, sedangkan tujuan strategis merupakan indikator penuntun yang menandakan prospek kinerja masa depan. Perusahaan yang mengorbankan penguatan posisi kompetitif demi hasil keuangan jangka pendek berisiko mengalami kemunduran daya saing yang sulit dipulihkan. Oleh karena itu, apabila terjadi pertukaran antara pencapaian tujuan jangka panjang dan jangka pendek, prioritas selayaknya diberikan pada tujuan jangka panjang, kecuali dalam kondisi luar biasa seperti krisis likuiditas.</p>
      <h5>3.4.2 Tujuan yang Menantang atau Stretch Objectives</h5>
      <p>Perusahaan berkinerja tinggi lazim menetapkan <em>stretch objectives</em>, yaitu target yang berada di atas jangkauan kemampuan saat ini sehingga memaksa organisasi berinovasi dan meningkatkan kinerja secara substansial. Thompson et al. (2024) membedakan antara target menantang yang masih dapat dicapai dengan upaya keras dan <em>extreme stretch goals</em> yang nyaris mustahil dicapai dengan sumber daya dan kapabilitas yang ada. Target ekstrem semacam itu hanya layak ditetapkan dalam kondisi tertentu, misalnya ketika perusahaan memiliki sumber daya berlimpah dan momentum kinerja yang kuat; pada kondisi normal target yang terus-menerus tidak tercapai justru menurunkan moral dan kredibilitas manajemen. Implikasi manajerialnya adalah manajer harus mengkalibrasi tingkat kesulitan target sesuai kondisi sumber daya, kapabilitas, dan posisi kompetitif perusahaan.</p>
      <h5>3.4.3 Pendekatan Berimbang dan Balanced Scorecard</h5>
      <p>Kerangka yang paling banyak digunakan untuk menyeimbangkan tujuan keuangan dan tujuan strategis adalah <em>balanced scorecard</em> yang dikembangkan oleh Kaplan dan Norton. Kerangka ini mengukur kinerja perusahaan pada empat dimensi, yaitu: (1) dimensi keuangan yang memuat ukuran hasil keuangan; (2) dimensi pelanggan yang memuat ukuran kepuasan, retensi, dan akuisisi pelanggan; (3) dimensi proses internal yang memuat ukuran produktivitas dan kualitas; dan (4) dimensi pembelajaran dan pertumbuhan organisasi yang memuat ukuran pengembangan sumber daya manusia dan kapabilitas. Cara menggunakan kerangka ini adalah menurunkan visi dan strategi perusahaan menjadi sasaran, ukuran, target, dan inisiatif pada keempat dimensi tersebut sehingga tercipta peta hubungan sebab akibat dari kapabilitas organisasi menuju hasil keuangan. Di Indonesia, badan usaha milik negara seperti PT Bank Rakyat Indonesia Tbk telah lama menerapkan <em>balanced scorecard</em> sebagai dasar kontrak manajemen dan indikator kinerja utama dari tingkat direksi hingga unit kerja operasional, sehingga target keuangan konsolidasi tersambung dengan target layanan nasabah mikro di tingkat unit desa.</p>
      <h5>3.4.4 Tujuan untuk Setiap Tingkat Organisasi</h5>
      <p>Penetapan tujuan tidak berhenti pada tingkat korporat. Agar tujuan perusahaan tercapai, target kinerja harus dipecah dan diturunkan ke setiap unit bisnis, lini produk, departemen fungsional, dan unit operasi. Proses penurunan tujuan yang ideal berlangsung dari atas ke bawah sehingga tujuan unit yang lebih rendah mendukung secara langsung pencapaian tujuan pada tingkat di atasnya. Dengan demikian, penetapan tujuan menjadi mekanisme integrasi yang menyatukan upaya seluruh bagian organisasi pada arah yang sama dan mencegah setiap unit menetapkan target yang saling bertentangan.</p>`
    },
    {
      no: "3.5",
      title: "Tahap 3: Merumuskan Strategi",
      body: `<p>Tahap ketiga adalah merumuskan strategi untuk mencapai tujuan yang telah ditetapkan dan menggerakkan perusahaan pada lintasan visi. Perumusan strategi menuntut jawaban atas serangkaian pertanyaan bagaimana, misalnya bagaimana menumbuhkan bisnis, bagaimana memuaskan pelanggan, bagaimana mengungguli pesaing, bagaimana merespons perubahan kondisi pasar, dan bagaimana mencapai target strategis dan keuangan. Perumusan strategi yang baik tidak lahir dari intuisi semata, melainkan dari analisis lingkungan eksternal dan internal yang cermat sebagaimana akan dibahas pada bab-bab berikutnya.</p>
      <h5>3.5.1 Perumusan Strategi Melibatkan Manajer di Semua Tingkat</h5>
      <p>Menurut Thompson, Peteraf, Gamble dan Strickland (2024), perumusan strategi bukan hanya tugas eksekutif puncak, melainkan upaya tim yang melibatkan manajer di seluruh jenjang organisasi. Semakin besar dan terdiversifikasi sebuah perusahaan, semakin tidak mungkin segelintir eksekutif di kantor pusat menguasai seluruh detail pasar, produk, dan operasi yang diperlukan untuk merumuskan setiap langkah strategis. Manajer tingkat menengah dan bawah memiliki pengetahuan lapangan yang lebih dekat dengan pelanggan dan operasi sehingga posisi mereka lebih tepat untuk merumuskan detail strategi pada wilayah tanggung jawabnya. Selain itu, keterlibatan manajer dalam perumusan strategi meningkatkan rasa kepemilikan dan komitmen mereka pada saat eksekusi.</p>
      <h5>3.5.2 Hirarki Perumusan Strategi</h5>
      <p>Pada perusahaan yang terdiversifikasi, strategi tersusun dalam empat tingkat yang membentuk hirarki perumusan strategi. Tingkat pertama adalah <em>corporate strategy</em>, yaitu strategi multibisnis yang menetapkan cara memperoleh keunggulan dari pengelolaan sekumpulan bisnis dan menjadi tanggung jawab eksekutif korporat. Tingkat kedua adalah <em>business strategy</em>, yaitu strategi satu lini bisnis untuk memperkuat posisi pasar dan membangun keunggulan bersaing, yang menjadi tanggung jawab manajer umum unit bisnis. Tingkat ketiga adalah <em>functional-area strategies</em>, yaitu pendekatan pada fungsi-fungsi seperti pemasaran, produksi, keuangan, dan sumber daya manusia untuk mendukung strategi bisnis. Tingkat keempat adalah <em>operating strategies</em>, yaitu inisiatif yang relatif sempit untuk mengelola unit operasi kunci seperti pabrik, pusat distribusi, dan pusat pembelian. Pada perusahaan bisnis tunggal, tingkat korporat dan tingkat bisnis melebur menjadi satu. Struktur hirarki tersebut dirangkum pada Tabel 3.3.</p>
      <table class="bk-table"><caption>Tabel 3.3 Hirarki Perumusan Strategi Perusahaan Terdiversifikasi</caption>
      <thead><tr><th>Tingkat Strategi</th><th>Penanggung Jawab Utama</th><th>Persoalan Pokok yang Dijawab</th></tr></thead>
      <tbody>
      <tr><td><em>Corporate strategy</em></td><td>CEO dan eksekutif korporat, disetujui dewan</td><td>Bisnis apa yang dimasuki, bagaimana mengalokasikan sumber daya lintas bisnis, dan bagaimana menciptakan sinergi antarbisnis</td></tr>
      <tr><td><em>Business strategy</em></td><td>Manajer umum tiap unit bisnis</td><td>Bagaimana bersaing dan membangun keunggulan bersaing pada satu arena bisnis tertentu</td></tr>
      <tr><td><em>Functional-area strategies</em></td><td>Kepala fungsi dalam unit bisnis</td><td>Bagaimana tiap fungsi mendukung strategi bisnis dan memperkuat kapabilitas yang dibutuhkan</td></tr>
      <tr><td><em>Operating strategies</em></td><td>Manajer merek, manajer pabrik, manajer unit operasi</td><td>Bagaimana mengelola aktivitas operasi kunci secara konsisten dengan strategi fungsional dan bisnis</td></tr>
      </tbody>
      <tfoot><tr><td colspan="99">Sumber: diolah dari Thompson, Peteraf, Gamble dan Strickland (2024)</td></tr></tfoot></table>
      <p>Sebagai ilustrasi konteks Indonesia, PT Astra International Tbk merumuskan strategi korporat mengenai komposisi portofolio pada segmen otomotif, jasa keuangan, alat berat, agribisnis, infrastruktur, dan teknologi informasi, sementara strategi bisnis dirumuskan pada tingkat anak usaha seperti strategi bersaing Toyota Astra Motor di pasar kendaraan penumpang. Strategi fungsional dan operasi kemudian dirumuskan oleh manajemen pabrik dan jaringan distribusi masing-masing anak usaha.</p>
      <h5>3.5.3 Menyatukan Hirarki Strategi dan Rencana Strategis</h5>
      <p>Keempat tingkat strategi tersebut harus dikoordinasikan secara erat agar membentuk satu kesatuan tindakan yang kohesif. Arah dan pedoman mengalir dari tingkat korporat ke tingkat bisnis lalu ke tingkat fungsional dan operasi, sementara informasi pasar dan usulan inisiatif mengalir dari bawah ke atas, sehingga terjadi pengaruh dua arah antarjenjang. Strategi yang saling bertentangan antartingkat akan melemahkan strategi keseluruhan seperti anyaman yang benangnya tidak terjalin. Ketika visi strategis, tujuan, dan strategi telah tersatukan, perusahaan memiliki rencana strategis yang utuh, yaitu peta arah yang menyatakan ke mana perusahaan menuju, target apa yang hendak dicapai, dan bagaimana cara mencapainya. Implikasi manajerialnya adalah manajemen puncak wajib membangun proses komunikasi dan penyelarasan yang disiplin, misalnya melalui siklus perencanaan tahunan yang mempertemukan target korporat dengan rencana kerja unit.</p>`
    },
    {
      no: "3.6",
      title: "Tahap 4: Mengeksekusi Strategi",
      body: `<p>Strategi yang unggul di atas kertas tidak memiliki nilai apabila tidak dieksekusi dengan baik. Eksekusi strategi merupakan kegiatan yang berorientasi operasi dan paling menuntut waktu dalam proses manajemen strategik karena mencakup pengubahan rencana menjadi tindakan nyata sehari-hari. Menurut Thompson et al. (2024), mengelola eksekusi strategi mencakup upaya membangun kesesuaian antara cara organisasi menjalankan aktivitasnya dan tuntutan eksekusi strategi yang cakap.</p>
      <p>Agenda tindakan manajemen dalam eksekusi strategi mencakup beberapa aspek utama, yaitu: (1) merekrut dan mengembangkan staf dengan keterampilan dan keahlian yang dibutuhkan; (2) mengalokasikan sumber daya yang memadai bagi aktivitas yang kritikal terhadap keberhasilan strategi; (3) memastikan kebijakan dan prosedur mendukung eksekusi; (4) memasang sistem informasi dan sistem operasi yang memungkinkan personel menjalankan peran secara efektif; (5) mendorong perbaikan berkelanjutan atas proses pelaksanaan; (6) mengaitkan imbalan dengan pencapaian target kinerja; (7) menciptakan budaya perusahaan yang kondusif bagi eksekusi; dan (8) menunjukkan kepemimpinan internal yang mendorong pelaksanaan maju terus dan terus membaik.</p>
      <p>Keunggulan operasi atau <em>operating excellence</em> tercapai apabila seluruh aspek tersebut dikelola secara konsisten sehingga pelaksanaan strategi mendekati sempurna pada aktivitas rantai nilai yang penting. Eksekusi dinilai berhasil apabila perusahaan mencapai target kinerja strategis dan keuangan yang ditetapkan serta menunjukkan kemajuan nyata menuju visi jangka panjang. Dengan demikian, kualitas eksekusi merupakan penentu akhir apakah perusahaan sekadar memiliki strategi yang bagus atau benar-benar berkinerja unggul; hal ini menegaskan bahwa kapabilitas implementasi merupakan sumber keunggulan bersaing tersendiri yang sulit ditiru pesaing.</p>`
    },
    {
      no: "3.7",
      title: "Tahap 5: Mengevaluasi Kinerja dan Melakukan Penyesuaian Korektif",
      body: `<p>Tahap kelima merupakan titik pemicu bagi peninjauan kembali seluruh tahap sebelumnya. Manajemen berkewajiban memantau perkembangan eksternal, mengevaluasi kemajuan perusahaan, dan memutuskan apakah visi, misi, tujuan, strategi, atau metode eksekusi perlu dipertahankan atau diubah. Selama strategi yang berjalan masih lulus tiga uji strategi unggul, yaitu uji kesesuaian, uji keunggulan bersaing, dan uji kinerja, manajemen dapat berfokus pada penyempurnaan eksekusi. Namun, apabila kinerja aktual berada di bawah target, manajemen harus menelusuri akar masalahnya secara sistematis, dimulai dari kualitas eksekusi, kemudian kelayakan strategi dan model bisnis, hingga kewajaran target yang ditetapkan.</p>
      <p>Penyesuaian korektif merupakan hal yang normal dan diperlukan dalam proses manajemen strategik karena kondisi pasar terus berubah. Proses perumusan dan eksekusi strategi dengan demikian tidak pernah benar-benar selesai; evaluasi kinerja menjadi umpan balik yang menghidupkan siklus lima tahap secara terus-menerus. Perusahaan yang disiplin melakukan evaluasi berkala akan lebih cepat mendeteksi gejala <em>strategic inflection point</em> dan lebih siap menyesuaikan arah sebelum posisi kompetitifnya tergerus. Implikasi manajerialnya adalah perusahaan perlu membangun sistem pemantauan kinerja yang objektif, berbasis indikator penuntun dan indikator tertinggal, serta budaya yang tidak menghukum penyampaian kabar buruk sehingga masalah muncul ke permukaan lebih awal.</p>`
    },
    {
      no: "3.8",
      title: "Tata Kelola Korporat: Peran Dewan Direksi dalam Proses Strategi",
      body: `<p>Meskipun tanggung jawab utama perumusan dan eksekusi strategi berada pada manajemen, dewan direksi memiliki kewajiban mengawasi agar seluruh proses tersebut dijalankan demi kepentingan terbaik pemegang saham dan pemangku kepentingan lainnya. Menurut Thompson, Peteraf, Gamble dan Strickland (2024), terdapat empat kewajiban utama dewan dalam tata kelola korporat. Pertama, mengawasi praktik akuntansi dan pelaporan keuangan perusahaan agar laporan yang diterbitkan akurat dan tidak menyesatkan, antara lain melalui komite audit yang beranggotakan direktur independen. Kedua, menilai secara kritis arah, strategi, dan pendekatan bisnis yang diusulkan manajemen dengan mengajukan pertanyaan yang tajam dan menantang, bukan sekadar menyetujui. Ketiga, mengevaluasi keterampilan kepemimpinan strategik eksekutif puncak, termasuk menilai kinerja CEO dan menyiapkan rencana suksesi. Keempat, menetapkan skema kompensasi eksekutif yang memberi imbalan atas tindakan yang selaras dengan kepentingan jangka panjang pemegang saham.</p>
      <p>Efektivitas pengawasan menuntut komposisi dewan yang memadai antara direktur dalam atau <em>inside directors</em> dan direktur luar yang independen atau <em>outside directors</em>. Direktur independen diperlukan karena mereka dapat menilai kinerja manajemen secara objektif tanpa benturan kepentingan, sedangkan dewan yang pasif dan terlalu dekat dengan manajemen terbukti gagal mencegah skandal korporasi besar. Pengalaman krisis tata kelola pada berbagai perusahaan global menunjukkan bahwa skema kompensasi yang terlalu menekankan kinerja jangka pendek dapat mendorong eksekutif mengambil risiko berlebihan atau memanipulasi laba demi bonus.</p>
      <p>Dalam konteks Indonesia, fungsi pengawasan tersebut dijalankan melalui struktur dua dewan atau <em>two-tier board</em>, yaitu direksi sebagai organ pengelola dan dewan komisaris sebagai organ pengawas sebagaimana diatur dalam Undang-Undang Perseroan Terbatas. Regulasi Otoritas Jasa Keuangan mewajibkan emiten memiliki komisaris independen dan komite audit, sehingga substansi kewajiban pengawasan strategi, pelaporan keuangan, evaluasi direksi, dan remunerasi pada praktiknya melekat pada dewan komisaris beserta komite-komitenya. Oleh karena itu, mahasiswa perlu memahami bahwa prinsip tata kelola yang diuraikan buku teks bersifat universal meskipun bentuk kelembagaannya berbeda antara model satu dewan di Amerika Serikat dan model dua dewan di Indonesia. Dewan yang menjalankan perannya dengan kuat dan aktif menjadi penjaga akhir agar arah perusahaan yang ditetapkan manajemen benar-benar menciptakan nilai jangka panjang.</p>`
    },
    {
      no: "3.9",
      title: "Rangkuman",
      body: `<p>Proses perumusan dan eksekusi strategi terdiri atas lima tahap yang saling berkaitan dan berlangsung terus-menerus, yaitu mengembangkan visi strategis, misi, dan nilai inti; menetapkan tujuan; merumuskan strategi; mengeksekusi strategi; serta mengevaluasi kinerja dan melakukan penyesuaian korektif. Visi strategis menjelaskan arah jangka panjang perusahaan, misi menjelaskan tujuan keberadaan perusahaan saat ini, dan nilai inti memandu perilaku organisasi dalam mengejar keduanya. Visi hanya bernilai apabila khas, spesifik, dan dikomunikasikan secara efektif sehingga menggerakkan energi seluruh anggota organisasi ke arah yang sama.</p>
      <p>Penetapan tujuan mengubah visi menjadi target kinerja yang spesifik, terukur, dan bertenggat. Perusahaan memerlukan keseimbangan antara tujuan keuangan sebagai indikator tertinggal dan tujuan strategis sebagai indikator penuntun, yang dapat difasilitasi melalui kerangka <em>balanced scorecard</em> dan diturunkan ke seluruh tingkat organisasi. Perumusan strategi merupakan upaya kolektif yang tersusun dalam hirarki strategi korporat, strategi bisnis, strategi fungsional, dan strategi operasi yang harus saling terkoordinasi hingga membentuk rencana strategis yang utuh.</p>
      <p>Eksekusi strategi menuntut keunggulan operasi melalui pengelolaan sumber daya manusia, alokasi sumber daya, kebijakan, sistem, insentif, budaya, dan kepemimpinan yang saling mendukung. Evaluasi kinerja menutup siklus dengan memicu penyesuaian korektif ketika hasil aktual menyimpang dari target atau ketika perusahaan menghadapi <em>strategic inflection point</em>. Pada akhirnya, dewan direksi, atau dewan komisaris dalam struktur tata kelola Indonesia, bertanggung jawab mengawasi keseluruhan proses tersebut agar arah dan strategi perusahaan sungguh-sungguh melindungi kepentingan pemegang saham dan menciptakan nilai jangka panjang.</p>`
    },
    {
      no: "3.10",
      title: "Daftar Pustaka",
      body: `<p>Thompson, A. A., Peteraf, M. A., Gamble, J. E. dan Strickland, A. J. (2024). <em>Crafting and Executing Strategy: The Quest for Competitive Advantage, Concepts and Cases</em>. 2024 Release. New York: McGraw Hill.</p>
      <p>Kaplan, R. S. dan Norton, D. P. (1996). <em>The Balanced Scorecard: Translating Strategy into Action</em>. Boston: Harvard Business School Press.</p>`
    }
  ]
};
