window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.sm = window.MBA_BOOK.sm || {};
window.MBA_BOOK.sm[6] = {
  bab: 6,
  judul: "BAB 6 LIMA STRATEGI KOMPETITIF GENERIK",
  sumber: "Thompson, Peteraf, Gamble dan Strickland (2024), Crafting and Executing Strategy, 2024 Release, McGraw Hill",
  lo: [
    "LO 6-1 Memahami hal yang membedakan masing-masing dari lima strategi generik dan menjelaskan alasan sebagian strategi tersebut bekerja lebih baik pada kondisi persaingan tertentu dibandingkan pada kondisi lainnya.",
    "LO 6-2 Mengenali jalur-jalur utama untuk mencapai keunggulan kompetitif yang didasarkan pada biaya yang lebih rendah.",
    "LO 6-3 Mengidentifikasi jalur-jalur utama menuju keunggulan kompetitif yang didasarkan pada diferensiasi produk atau jasa perusahaan dari penawaran para pesaing.",
    "LO 6-4 Menjelaskan atribut strategi biaya terbaik (best-cost strategy) sebagai strategi hibrida yang memadukan strategi biaya rendah dan strategi diferensiasi."
  ],
  sections: [
    {
      no: "6.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi ini membahas pilihan mendasar yang harus diambil setiap perusahaan dalam merumuskan strategi kompetitifnya, yaitu memilih satu dari lima strategi kompetitif generik. Pemilihan strategi generik merupakan keputusan pertama dan paling utama dalam menyusun strategi keseluruhan karena keputusan ini menentukan arah seluruh upaya perusahaan dalam membangun keunggulan kompetitif atas para pesaingnya (Thompson et al., 2024). Pembahasan dalam sesi ini mencakup pengertian dan tipologi strategi generik, jalur-jalur pencapaian keunggulan biaya, jalur-jalur pencapaian keunggulan diferensiasi, strategi fokus pada ceruk pasar, strategi biaya terbaik, serta perbandingan fitur kelima strategi tersebut melalui kerangka nilai, harga, dan biaya.</p>
<p>Setelah mengikuti sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p><strong>LO 6-1</strong> Memahami hal yang membedakan masing-masing dari lima strategi generik dan menjelaskan alasan sebagian strategi tersebut bekerja lebih baik pada kondisi persaingan tertentu dibandingkan pada kondisi lainnya. <strong>LO 6-2</strong> Mengenali jalur-jalur utama untuk mencapai keunggulan kompetitif yang didasarkan pada biaya yang lebih rendah. <strong>LO 6-3</strong> Mengidentifikasi jalur-jalur utama menuju keunggulan kompetitif yang didasarkan pada diferensiasi produk atau jasa perusahaan dari penawaran para pesaing. <strong>LO 6-4</strong> Menjelaskan atribut strategi biaya terbaik sebagai strategi hibrida yang memadukan elemen strategi biaya rendah dan strategi diferensiasi.</p>`
    },
    {
      no: "6.2",
      title: "Tipe-Tipe Strategi Kompetitif Generik",
      body: `<p>Setiap perusahaan yang bersaing di suatu industri pada dasarnya berupaya memberikan nilai yang lebih besar kepada pelanggan dibandingkan pesaing, atau memberikan nilai yang setara dengan cara yang lebih efisien, atau keduanya sekaligus. Nilai yang lebih besar dapat berwujud produk yang baik dengan harga lebih murah, produk superior yang layak dibayar lebih mahal, atau kombinasi menarik antara harga, fitur, dan layanan. Menurut Thompson, Peteraf, Gamble dan Strickland (2024), strategi kompetitif berkenaan dengan kekhususan rencana permainan manajemen untuk memperkuat posisi pasar dan mengamankan keunggulan kompetitif atas para pesaing di dalam industri. Dari definisi tersebut dapat disimpulkan bahwa strategi kompetitif bersifat lebih sempit daripada strategi korporat karena hanya menyangkut cara perusahaan bersaing di satu arena bisnis tertentu.</p>
<p>Meskipun rincian strategi setiap perusahaan hampir tidak pernah identik, terdapat dua faktor besar yang membedakan satu strategi kompetitif dari strategi lainnya. Faktor pertama adalah apakah target pasar perusahaan bersifat luas atau sempit. Faktor kedua adalah apakah keunggulan kompetitif yang dikejar bertumpu pada biaya yang lebih rendah atau pada diferensiasi. Kombinasi kedua dimensi tersebut menghasilkan empat pilihan strategi yang berbeda ditambah satu pilihan hibrida, sehingga secara keseluruhan terdapat lima strategi kompetitif generik, yaitu: <em>broad low-cost strategy</em>, <em>broad differentiation strategy</em>, <em>focused low-cost strategy</em>, <em>focused differentiation strategy</em>, dan <em>best-cost strategy</em> (Thompson et al., 2024). Kerangka ini merupakan perluasan dari klasifikasi tiga strategi generik yang mula-mula dikemukakan oleh Porter (1980). Sebagaimana ditegaskan Porter, "<em>strategic positioning</em> berarti melakukan aktivitas yang berbeda dari pesaing atau melakukan aktivitas serupa dengan cara yang berbeda" (dikutip dalam Thompson et al., 2024).</p>
<table class="bk-table"><caption>Tabel 6.1 Peta Lima Strategi Kompetitif Generik</caption>
<thead><tr><th>Target Pasar</th><th>Keunggulan Berbasis Biaya Rendah</th><th>Keunggulan Berbasis Diferensiasi</th></tr></thead>
<tbody>
<tr><td>Spektrum pembeli yang luas</td><td>Strategi biaya rendah luas: menekan biaya keseluruhan di bawah pesaing untuk produk sebanding, umumnya dengan harga di bawah pesaing</td><td>Strategi diferensiasi luas: membedakan penawaran dengan atribut yang menarik bagi banyak segmen pembeli</td></tr>
<tr><td>Segmen pembeli yang sempit (ceruk pasar)</td><td>Strategi fokus biaya rendah: melayani kebutuhan ceruk dengan biaya dan harga lebih rendah daripada pesaing</td><td>Strategi fokus diferensiasi: menawarkan atribut yang disesuaikan dengan selera anggota ceruk secara lebih baik daripada pesaing</td></tr>
<tr><td>Luas atau sempit</td><td colspan="2">Strategi biaya terbaik: memadukan atribut produk kelas atas dengan biaya yang lebih rendah daripada pesaing yang produknya sebanding</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot></table>
<p>Kelima strategi tersebut menempatkan perusahaan pada posisi pasar yang berbeda secara mendasar. Oleh karena itu, pemilihan salah satu di antaranya menuntut konsistensi seluruh aktivitas rantai nilai, sumber daya, dan kapabilitas perusahaan dengan logika strategi yang dipilih. Apapun pendekatan yang diambil, keunggulan kompetitif yang tahan lama hampir selalu mensyaratkan pelaksanaan aktivitas rantai nilai secara berbeda dari pesaing serta pembangunan sumber daya dan kapabilitas yang sulit ditiru atau dilampaui oleh pesaing (Thompson et al., 2024).</p>`
    },
    {
      no: "6.3",
      title: "Strategi Biaya Rendah untuk Pasar Luas",
      body: `<p>Strategi biaya rendah luas, yang disebut juga <em>low-cost leadership</em>, adalah upaya menghasilkan barang atau jasa bagi basis pembeli yang luas dengan biaya yang lebih rendah daripada pesaing (Thompson et al., 2024). Perusahaan dikatakan mencapai kepemimpinan biaya apabila menjadi produsen berbiaya terendah di industrinya, bukan sekadar salah satu dari beberapa pesaing yang biayanya relatif rendah. Namun, sasaran strategisnya adalah biaya yang secara berarti lebih rendah daripada pesaing, bukan biaya serendah mungkin secara absolut, karena produk yang terlalu minim fitur dapat dipersepsikan tidak bernilai oleh pembeli berapapun harganya. Dengan demikian, penekanan biaya harus tetap mempertahankan fitur dan layanan yang dianggap esensial oleh pembeli.</p>
<p>Perusahaan yang berhasil membangun keunggulan biaya memiliki dua opsi untuk menerjemahkannya menjadi kinerja laba yang superior. Opsi pertama adalah menggunakan keunggulan biaya untuk menetapkan harga di bawah pesaing dan menarik pembeli yang sensitif terhadap harga dalam jumlah besar sehingga total laba meningkat melalui volume. Opsi kedua adalah mempertahankan harga saat ini dan menikmati margin laba per unit yang lebih tinggi. Opsi pertama mengandung risiko memicu perang harga apabila pesaing membalas dengan pemotongan harga tandingan, sehingga semakin besar kemungkinan pembalasan pesaing, semakin menarik opsi kedua bagi perusahaan (Thompson et al., 2024). Contoh klasik di Indonesia adalah persaingan maskapai berbiaya rendah seperti Lion Air dan Citilink yang menawarkan tarif rendah kepada spektrum penumpang yang luas dengan menekan biaya melalui armada seragam, utilisasi pesawat yang tinggi, dan layanan tanpa embel-embel.</p>
<h5>6.3.1 Dua Jalur Utama Mencapai Keunggulan Biaya</h5>
<p>Agar unggul dalam biaya, biaya kumulatif perusahaan di sepanjang keseluruhan rantai nilainya harus lebih rendah daripada biaya kumulatif pesaing. Terdapat dua jalur utama untuk mencapainya, yaitu: (1) melaksanakan aktivitas rantai nilai internal dan aktivitas sistem rantai nilai secara lebih hemat biaya daripada pesaing, dan (2) merombak keseluruhan rantai nilai perusahaan untuk menghilangkan atau melewati sejumlah aktivitas yang menimbulkan biaya (Thompson et al., 2024).</p>
<p>Pada jalur pertama, manajer harus dengan tekun mencari peluang penghematan pada setiap bagian rantai nilai dengan memanfaatkan faktor-faktor yang disebut <em>cost drivers</em>, yaitu faktor yang berpengaruh kuat terhadap biaya perusahaan dan dapat digunakan sebagai tuas untuk menurunkan biaya. Penggerak biaya yang utama mencakup skala ekonomi (<em>economies of scale</em>), efek pembelajaran dan pengalaman (<em>learning and experience</em>), pemanfaatan kapasitas (<em>capacity utilization</em>), efisiensi rantai pasokan, biaya input, daya tawar terhadap pemasok, teknologi produksi dan desain produk, sistem komunikasi dan teknologi informasi, keputusan <em>outsourcing</em> atau integrasi vertikal, serta sistem insentif dan budaya perusahaan (Thompson et al., 2024). Sebagai ilustrasi, skala ekonomi memungkinkan biaya iklan yang sangat besar disebar ke jutaan unit penjualan, sedangkan efek pengalaman menurunkan biaya per unit seiring akumulasi volume produksi karena proses menjadi semakin terampil dan efisien.</p>
<p>Pada jalur kedua, perusahaan tidak sekadar mengefisienkan aktivitas yang ada, melainkan mengonfigurasi ulang rantai nilai itu sendiri. Cara-cara yang lazim ditempuh antara lain menjual langsung kepada konsumen akhir sehingga memangkas aktivitas dan margin distributor, mengganti proses konvensional dengan teknologi yang lebih murah seperti penjualan daring, menyederhanakan lini produk, serta merelokasi fasilitas untuk mengurangi biaya logistik. Model bisnis Gojek dan Tokopedia pada tahap awal pertumbuhannya di Indonesia memperlihatkan perombakan rantai nilai semacam ini, yaitu mempertemukan penjual dan pembeli secara langsung melalui platform digital tanpa jaringan toko fisik yang mahal.</p>
<h5>6.3.2 Kunci Keberhasilan dan Kondisi yang Mendukung</h5>
<p>Keberhasilan strategi biaya rendah menuntut manajer menelaah setiap aktivitas yang menimbulkan biaya dan menetapkan penggerak biayanya, kemudian menggunakan pengetahuan tersebut untuk menekan biaya pada setiap mata rantai secara berkelanjutan. Budaya organisasi yang hemat, keteladanan manajemen, anggaran yang ketat, dan partisipasi luas karyawan dalam upaya perbaikan biaya merupakan prasyarat keberhasilan. Strategi ini bekerja paling baik pada kondisi berikut: persaingan harga antar penjual sangat kuat, produk para penjual pada dasarnya identik dan tersedia dari banyak penjual, hanya ada sedikit cara melakukan diferensiasi yang bernilai bagi pembeli, biaya berpindah pemasok bagi pembeli rendah, pembeli berukuran besar dan berdaya tawar kuat, serta pendatang baru menggunakan harga perkenalan yang rendah untuk menarik pembeli (Thompson et al., 2024). Kondisi-kondisi tersebut banyak dijumpai pada industri komoditas, semen, penerbangan berbiaya rendah, dan ritel modern.</p>
<h5>6.3.3 Jebakan Strategi Biaya Rendah</h5>
<p>Kesalahan terbesar dalam strategi ini adalah terlalu agresif memotong harga sehingga penurunan harga tidak diimbangi tambahan volume yang memadai dan total laba justru menurun. Pemotongan harga hanya meningkatkan laba apabila keunggulan biaya perusahaan cukup besar atau tambahan unit yang terjual cukup banyak untuk menutup margin yang hilang. Jebakan kedua adalah mengandalkan pendekatan penghematan yang mudah ditiru pesaing, karena keunggulan biaya hanya tahan lama apabila bersumber dari kapabilitas yang sulit direplikasi. Jebakan ketiga adalah terobsesi pada penurunan biaya hingga produk menjadi terlalu sederhana dan kehilangan atribut yang diinginkan pembeli. Selain itu, keunggulan biaya dapat lenyap seketika apabila muncul inovasi teknologi pesaing yang menurunkan struktur biaya industri secara drastis. Oleh karena itu, pemimpin biaya tetap harus memantau perubahan teknologi dan preferensi pembeli secara berkesinambungan (Thompson et al., 2024).</p>`
    },
    {
      no: "6.4",
      title: "Strategi Diferensiasi untuk Pasar Luas",
      body: `<p>Strategi diferensiasi luas adalah upaya membedakan penawaran produk atau jasa perusahaan dari penawaran pesaing melalui atribut-atribut yang menarik bagi spektrum pembeli yang luas (Thompson et al., 2024). Esensi strategi ini adalah menawarkan keunikan yang bersedia dibayar oleh pembeli dengan harga premium, yang meningkatkan penjualan unit, dan yang menumbuhkan loyalitas pembeli terhadap merek. Diferensiasi dikatakan berhasil apabila harga premium yang dapat dikenakan melebihi biaya tambahan untuk menciptakan keunikan tersebut. Dengan demikian, diferensiasi bukan sekadar membuat produk berbeda, melainkan membuat perbedaan yang bernilai di mata pembeli dan menguntungkan bagi perusahaan.</p>
<h5>6.4.1 Mengelola Rantai Nilai untuk Menciptakan Diferensiasi</h5>
<p>Sebagaimana biaya memiliki penggeraknya, keunikan juga memiliki penggeraknya. <em>Value drivers</em> adalah faktor-faktor yang berpengaruh kuat terhadap nilai yang dipersepsikan pelanggan dan dapat digunakan sebagai tuas untuk menciptakan keunggulan diferensiasi. Penggerak nilai yang utama meliputi fitur dan kinerja produk, proses pengendalian mutu, layanan pelanggan, aktivitas penjualan dan pemasaran, riset dan pengembangan produksi, kualitas input, teknologi dan inovasi, serta keterampilan, pelatihan, dan pengalaman karyawan (Thompson et al., 2024). Manajer dapat meningkatkan diferensiasi melalui empat cara dasar, yaitu: menciptakan atribut yang menurunkan biaya total pembeli dalam menggunakan produk, menciptakan atribut yang meningkatkan kinerja yang diperoleh pembeli, menciptakan atribut yang meningkatkan kepuasan pembeli secara nonekonomis atau tidak berwujud, dan menyampaikan nilai kepada pelanggan melalui kapabilitas kompetitif yang tidak dimiliki pesaing.</p>
<p>Peluang diferensiasi dapat muncul di setiap mata rantai sistem rantai nilai, mulai dari pengadaan input berkualitas tinggi, aktivitas riset dan pengembangan, proses manufaktur yang menjamin konsistensi mutu, hingga aktivitas distribusi dan layanan purnajual. Sebagai contoh, Apple mendiferensiasikan diri melalui integrasi desain perangkat keras, perangkat lunak, dan ekosistem layanan, sedangkan di Indonesia Garuda Indonesia mendiferensiasikan diri dari maskapai berbiaya rendah melalui layanan penuh, ketepatan waktu, dan pengalaman kabin yang khas, yang memungkinkan tarif lebih tinggi pada segmen penumpang bisnis.</p>
<h5>6.4.2 Menyampaikan Nilai Superior dan Persepsi Nilai</h5>
<p>Nilai yang dipersepsikan pembeli tidak selalu sama dengan nilai aktual yang dihantarkan produk. Pembeli jarang mengetahui nilai sebenarnya sebelum pembelian, sehingga mereka menilai berdasarkan sinyal nilai seperti harga, kemasan yang menarik, kampanye iklan, kualitas materi promosi, profesionalisme penampilan penjual, dan daftar pelanggan terkemuka. Oleh karena itu, perusahaan pendiferensiasi harus mengelola sinyal nilai (<em>signaling value</em>) sama seriusnya dengan mengelola nilai intrinsik produknya, terutama apabila sifat diferensiasi bersifat subjektif atau sulit dikuantifikasi dan pembeli melakukan pembelian untuk pertama kali (Thompson et al., 2024). Implikasi manajerialnya, investasi pada merek, komunikasi pemasaran, dan pengalaman pelanggan merupakan bagian integral dari strategi diferensiasi, bukan sekadar pelengkap.</p>
<h5>6.4.3 Kondisi yang Mendukung dan Jebakan Diferensiasi</h5>
<p>Strategi diferensiasi bekerja paling baik pada pasar dengan kebutuhan dan penggunaan produk yang beragam, ketika terdapat banyak cara untuk membedakan produk yang bernilai bagi pembeli, ketika hanya sedikit pesaing yang mengikuti pendekatan diferensiasi serupa, dan ketika perubahan teknologi serta inovasi produk berlangsung cepat sehingga persaingan berpusat pada fitur yang terus berkembang (Thompson et al., 2024). Sebaliknya, terdapat sejumlah jebakan yang harus dihindari. Pertama, mendiferensiasikan atribut yang tidak menurunkan biaya pembeli atau tidak meningkatkan kesejahteraan pembeli, sehingga pembeli tidak bersedia membayar premium. Kedua, berlebihan dalam diferensiasi sehingga harga jauh melampaui kesediaan membayar pembeli atau kualitas melampaui kebutuhan pembeli. Ketiga, menetapkan premium harga yang terlalu tinggi sehingga pembeli beralih ke pesaing yang lebih murah. Keempat, mengandalkan atribut yang mudah ditiru, karena fitur yang cepat direplikasi pesaing tidak pernah menghasilkan keunggulan yang tahan lama. Diferensiasi yang paling awet umumnya bersumber dari inovasi berkelanjutan, keunggulan mutu, dan kapabilitas organisasi yang kompleks, bukan dari fitur tunggal yang kasat mata.</p>`
    },
    {
      no: "6.5",
      title: "Strategi Fokus pada Ceruk Pasar",
      body: `<p>Berbeda dari strategi berbasis pasar luas, strategi fokus memusatkan perhatian pada satu segmen pembeli yang sempit atau ceruk pasar (<em>market niche</em>). Ceruk dapat didefinisikan berdasarkan keunikan geografis, kebutuhan khusus dalam penggunaan produk, atau atribut khusus yang hanya menarik bagi anggota ceruk. Keunggulan bersaing perusahaan fokus bersumber dari kemampuannya melayani anggota ceruk secara lebih baik atau lebih murah daripada pesaing yang melayani pasar secara luas (Thompson et al., 2024).</p>
<h5>6.5.1 Strategi Fokus Biaya Rendah</h5>
<p>Strategi fokus biaya rendah mengarahkan upaya penghematan biaya pada pelayanan kebutuhan segmen sempit sehingga perusahaan dapat menetapkan harga lebih rendah daripada pesaing bagi anggota ceruk tersebut. Jalur pencapaian keunggulan biayanya sama dengan strategi biaya rendah luas, yaitu mengelola penggerak biaya secara lebih efektif dan merombak rantai nilai, hanya saja diterapkan pada lingkup segmen yang terbatas. Strategi ini lazim dijumpai pada segmen pembeli yang kebutuhannya lebih sederhana sehingga dapat dilayani dengan struktur biaya yang lebih ramping. Contoh di Indonesia adalah hotel bujet seperti jaringan RedDoorz yang melayani ceruk pelancong hemat dengan fasilitas dasar terstandar dan biaya operasi yang jauh lebih rendah daripada hotel berbintang, sehingga mampu menawarkan tarif kamar yang sangat bersaing pada segmen tersebut.</p>
<h5>6.5.2 Strategi Fokus Diferensiasi</h5>
<p>Strategi fokus diferensiasi berupaya menawarkan atribut yang dirancang khusus agar memenuhi selera dan persyaratan anggota ceruk secara lebih baik daripada produk pesaing. Keberhasilannya bergantung pada keberadaan segmen pembeli yang menghendaki atribut produk istimewa serta pada kapabilitas perusahaan untuk memenuhinya secara menonjol. Merek-merek mewah global seperti Louis Vuitton dan Rolls-Royce menempuh strategi ini dengan melayani ceruk konsumen berpenghasilan sangat tinggi (Thompson et al., 2024). Dalam konteks Indonesia, rumah mode batik premium seperti Iwan Tirta serta resor mewah seperti Ayana di Bali melayani ceruk pelanggan yang menuntut keaslian, kemewahan, dan eksklusivitas, dan bersedia membayar harga yang jauh di atas rata-rata pasar.</p>
<h5>6.5.3 Daya Tarik dan Risiko Strategi Fokus</h5>
<p>Strategi fokus, baik biaya rendah maupun diferensiasi, menjadi menarik apabila beberapa kondisi terpenuhi, yaitu: ceruk sasaran cukup besar untuk menguntungkan dan menawarkan potensi pertumbuhan yang baik, pemimpin industri tidak menganggap kehadiran di ceruk tersebut penting bagi keberhasilan mereka sehingga tekanan persaingan berkurang, melayani banyak ceruk sekaligus merupakan hal yang mahal atau sulit bagi pesaing multisegmen, industri memiliki banyak ceruk yang memungkinkan setiap perusahaan fokus memilih ceruk yang sesuai dengan kekuatannya, dan hanya sedikit pesaing lain yang berspesialisasi pada ceruk yang sama (Thompson et al., 2024). Namun, strategi fokus mengandung tiga risiko utama. Pertama, pesaing berbasis pasar luas dapat menemukan cara efektif untuk menandingi kemampuan perusahaan fokus dalam melayani ceruk. Kedua, preferensi anggota ceruk dapat bergeser mendekati preferensi pasar umum sehingga keunikan ceruk memudar dan pesaing arus utama lebih mudah masuk. Ketiga, ceruk yang menarik dapat mengundang banyak pendatang sehingga ceruk menjadi sesak dan laba terpecah. Oleh karena itu, perusahaan fokus perlu terus memperdalam kapabilitas khasnya agar tetap menjadi pilihan terbaik bagi anggota ceruk.</p>`
    },
    {
      no: "6.6",
      title: "Strategi Biaya Terbaik (Best-Cost Strategy)",
      body: `<p>Strategi biaya terbaik adalah upaya menyediakan produk dengan atribut diferensiasi kelas atas pada biaya yang lebih rendah daripada pesaing yang produknya memiliki atribut sebanding. Menurut Thompson, Peteraf, Gamble dan Strickland (2024), strategi ini merupakan strategi hibrida yang memadukan elemen strategi biaya rendah dan strategi diferensiasi dengan cara yang khas, dan dapat diterapkan pada target pasar luas maupun sempit. Menjadi produsen berbiaya terbaik untuk produk yang superior memungkinkan perusahaan memberikan nilai uang yang lebih besar kepada pelanggan dengan menetapkan harga di bawah pesaing yang atribut produknya setara. Posisi ini sering disebut menyasar pembeli yang mencari nilai (<em>value-conscious buyers</em>), yaitu pembeli yang menginginkan produk berkualitas menengah ke atas dengan harga yang wajar.</p>
<p>Keberhasilan strategi biaya terbaik mensyaratkan kapabilitas ganda yang tidak mudah dimiliki, yaitu kemampuan menghadirkan atribut menarik sekaligus kemampuan mengelola biaya lebih efisien daripada pesaing yang menawarkan atribut serupa. Sumber kapabilitas tersebut umumnya adalah efisiensi rantai nilai, skala, dan inovasi proses yang memungkinkan penambahan fitur tanpa lonjakan biaya. Strategi ini bekerja paling baik di pasar yang diferensiasi produknya menjadi norma dan terdapat jumlah pembeli sadar nilai yang besar, terutama pada kondisi ekonomi yang menekan daya beli sehingga banyak pembeli kelas menengah menghendaki kualitas baik dengan harga hemat (Thompson et al., 2024). Contoh yang sering dirujuk adalah Trader Joe's di Amerika Serikat yang menawarkan produk khas bermutu dengan harga terjangkau. Dalam konteks Indonesia, merek ponsel seperti Xiaomi dan merek kopi seperti Kopi Kenangan menempuh logika serupa, yaitu menawarkan spesifikasi atau pengalaman yang mendekati merek premium dengan harga yang jauh lebih rendah, sehingga menarik konsumen kelas menengah yang sadar nilai.</p>
<p>Risiko terbesar strategi biaya terbaik adalah terjepit di antara perusahaan berbiaya rendah dan perusahaan pendiferensiasi kelas atas. Pemimpin biaya dapat merebut pelanggan dengan harga yang lebih murah, sedangkan pendiferensiasi premium dapat merebut pelanggan dengan atribut yang lebih istimewa. Agar berhasil, perusahaan biaya terbaik harus menawarkan atribut yang secara berarti lebih baik daripada produk murah sekaligus harga yang secara berarti lebih rendah daripada produk premium, sehingga posisinya di tengah tetap unggul pada kedua dimensi relatif terhadap pesaing rata-rata (Thompson et al., 2024). Implikasi manajerialnya, strategi ini sebaiknya hanya dipilih oleh perusahaan yang benar-benar memiliki sumber daya dan kapabilitas untuk menghadirkan mutu di atas rata-rata dengan biaya di bawah rata-rata secara bersamaan.</p>`
    },
    {
      no: "6.7",
      title: "Perbandingan Fitur Kelima Strategi Generik",
      body: `<p>Kelima strategi generik memposisikan perusahaan secara berbeda di pasar dan menuntut pendekatan yang berbeda dalam mengelola rantai nilai. Perbedaan tersebut mencakup sasaran pasar, basis keunggulan kompetitif, lini produk, penekanan produksi, penekanan pemasaran, dan sumber daya serta kapabilitas yang dibutuhkan. Tabel 6.2 menyajikan sintesis perbandingan fitur yang kontras dari kelima strategi tersebut.</p>
<table class="bk-table"><caption>Tabel 6.2 Fitur Kontras Lima Strategi Kompetitif Generik</caption>
<thead><tr><th>Fitur</th><th>Biaya Rendah Luas</th><th>Diferensiasi Luas</th><th>Fokus Biaya Rendah</th><th>Fokus Diferensiasi</th><th>Biaya Terbaik</th></tr></thead>
<tbody>
<tr><td>Target pasar</td><td>Lintas segmen yang luas</td><td>Lintas segmen yang luas</td><td>Ceruk sempit dengan kebutuhan sederhana</td><td>Ceruk sempit dengan selera khusus</td><td>Pembeli sadar nilai, luas atau sempit</td></tr>
<tr><td>Basis keunggulan</td><td>Biaya keseluruhan terendah</td><td>Atribut yang berbeda dan bernilai</td><td>Biaya terendah dalam melayani ceruk</td><td>Atribut yang paling sesuai selera ceruk</td><td>Atribut kelas atas dengan biaya lebih rendah</td></tr>
<tr><td>Lini produk</td><td>Produk dasar yang baik dengan fitur esensial</td><td>Banyak variasi dan fitur yang membedakan</td><td>Fitur terbatas sesuai kebutuhan ceruk</td><td>Fitur yang disesuaikan dengan ceruk</td><td>Fitur menarik dengan mutu di atas rata-rata</td></tr>
<tr><td>Penekanan produksi</td><td>Penurunan biaya berkelanjutan tanpa mengorbankan mutu esensial</td><td>Penciptaan nilai tambah dan mutu unggul</td><td>Biaya rendah untuk atribut yang dibutuhkan ceruk</td><td>Produksi khusus berskala kecil sesuai ceruk</td><td>Fitur unggul dengan biaya rendah</td></tr>
<tr><td>Penekanan pemasaran</td><td>Harga murah dan nilai ekonomis</td><td>Atribut pembeda dan harga premium yang wajar</td><td>Harga murah bagi anggota ceruk</td><td>Kesesuaian dengan kebutuhan unik ceruk</td><td>Nilai terbaik untuk uang yang dibayarkan</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot></table>
<h5>6.7.1 Strategi Generik yang Berhasil Bersifat Berbasis Sumber Daya</h5>
<p>Agar suatu strategi generik berhasil dari waktu ke waktu, strategi tersebut harus ditopang oleh sumber daya dan kapabilitas yang sesuai. Strategi biaya rendah menuntut kapabilitas manajemen biaya, proses operasi yang efisien, dan budaya hemat. Strategi diferensiasi menuntut kapabilitas inovasi, pemasaran, dan penjaminan mutu. Strategi fokus menuntut pemahaman mendalam atas ceruk dan kapabilitas melayaninya secara khas, sedangkan strategi biaya terbaik menuntut kombinasi kapabilitas efisiensi dan diferensiasi sekaligus. Tanpa dukungan sumber daya yang sulit ditiru, posisi strategis apa pun akan mudah dikikis oleh pesaing (Thompson et al., 2024). Dengan demikian, pemilihan strategi generik harus selaras dengan hasil analisis internal perusahaan yang dibahas pada sesi sebelumnya.</p>
<h5>6.7.2 Kerangka Nilai, Harga, dan Biaya (Value-Price-Cost Framework)</h5>
<p>Ketiga pendekatan keunggulan kompetitif dapat dijelaskan secara ringkas melalui kerangka nilai, harga, dan biaya. Dalam kerangka ini, V adalah nilai yang dipersepsikan pembeli atas produk, P adalah harga yang dibayarkan pembeli, dan C adalah biaya per unit perusahaan. Selisih V dikurangi P merupakan proposisi nilai bagi pelanggan (<em>customer value proposition</em>), selisih P dikurangi C merupakan formula laba perusahaan (<em>profit formula</em>), dan selisih V dikurangi C merupakan total nilai ekonomi yang diciptakan. Perusahaan memiliki keunggulan kompetitif apabila total nilai ekonomi yang diciptakannya, yaitu V dikurangi C, lebih besar daripada total nilai ekonomi pesaing rata-rata (Thompson et al., 2024). Cara menggunakan kerangka ini adalah membandingkan posisi V, P, dan C perusahaan terhadap pesaing rata-rata untuk menilai keunggulan setiap strategi.</p>
<p>Strategi biaya rendah menurunkan C jauh di bawah pesaing meskipun V sedikit berkurang, sehingga selama penurunan biaya lebih besar daripada penurunan nilai yang dipersepsikan, total nilai ekonomi tetap lebih besar dan perusahaan dapat menawarkan harga lebih murah sambil menikmati laba yang lebih baik. Strategi diferensiasi justru dapat menanggung C yang lebih tinggi daripada pesaing, namun kenaikan V yang jauh lebih besar memungkinkan harga premium yang menghasilkan proposisi nilai pelanggan dan formula laba yang sama-sama lebih besar. Strategi biaya terbaik menempuh jalan tengah dengan V yang lebih tinggi dan C yang lebih rendah daripada pesaing rata-rata sekaligus, sehingga menghasilkan total nilai ekonomi yang unggul. Perlu ditekankan bahwa keberhasilan strategi generik tidak hanya bergantung pada pemosisian, melainkan juga pada konteks persaingan eksternal, situasi internal perusahaan, dan mutu eksekusi strategi (Thompson et al., 2024).</p>`
    },
    {
      no: "6.8",
      title: "Rangkuman",
      body: `<p>Strategi kompetitif suatu perusahaan pada hakikatnya ditentukan oleh dua pilihan mendasar, yaitu luas sempitnya target pasar dan jenis keunggulan kompetitif yang dikejar, apakah biaya rendah atau diferensiasi. Kombinasi kedua dimensi tersebut menghasilkan lima strategi generik, yaitu strategi biaya rendah luas, diferensiasi luas, fokus biaya rendah, fokus diferensiasi, dan strategi biaya terbaik sebagai hibrida. Keunggulan biaya dicapai melalui pengelolaan penggerak biaya yang lebih efektif dan perombakan rantai nilai, sedangkan keunggulan diferensiasi dicapai melalui pengelolaan penggerak nilai di sepanjang rantai nilai serta pengelolaan sinyal nilai yang membentuk persepsi pembeli. Setiap strategi memiliki kondisi pasar yang paling sesuai serta jebakan khas yang harus dihindari, seperti perang harga bagi pemimpin biaya, premium berlebihan bagi pendiferensiasi, pergeseran preferensi ceruk bagi perusahaan fokus, dan posisi terjepit bagi penganut strategi biaya terbaik.</p>
<p>Kerangka nilai, harga, dan biaya menegaskan bahwa keunggulan kompetitif bermuara pada kemampuan menciptakan total nilai ekonomi, yaitu selisih nilai yang dipersepsikan pembeli dengan biaya perusahaan, yang lebih besar daripada pesaing. Strategi apa pun yang dipilih hanya akan berhasil apabila ditopang oleh sumber daya dan kapabilitas yang sulit ditiru serta dieksekusi secara konsisten pada seluruh aktivitas rantai nilai. Oleh karena itu, tugas manajerial yang utama adalah memastikan keselarasan antara pilihan strategi generik, kondisi eksternal industri, kekuatan internal perusahaan, dan konfigurasi rantai nilai yang mendukungnya. Dengan pemahaman tersebut, mahasiswa diharapkan mampu menganalisis pilihan strategi perusahaan nyata dan menilai kesesuaiannya dengan kondisi persaingan yang dihadapi.</p>`
    },
    {
      no: "6.9",
      title: "Daftar Pustaka",
      body: `<p>Thompson, A. A., Peteraf, M. A., Gamble, J. E. dan Strickland, A. J. (2024). <em>Crafting and Executing Strategy: The Quest for Competitive Advantage, Concepts and Cases</em>. 2024 Release. New York: McGraw Hill.</p>
<p>Porter, M. E. (1980). <em>Competitive Strategy: Techniques for Analyzing Industries and Competitors</em>. New York: Free Press.</p>
<p>Porter, M. E. (1985). <em>Competitive Advantage: Creating and Sustaining Superior Performance</em>. New York: Free Press.</p>`
    }
  ]
};
