window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.sm = window.MBA_BOOK.sm || {};
window.MBA_BOOK.sm[9] = {
  bab: 9,
  judul: "BAB 9 MEMBANGUN ORGANISASI YANG MAMPU MELAKSANAKAN STRATEGI DENGAN BAIK",
  sumber: "Thompson, Peteraf, Gamble dan Strickland (2024), Crafting and Executing Strategy, 2024 Release, McGraw Hill",
  lo: [
    "LO 10-1 Memahami apa yang harus dilakukan manajer untuk melaksanakan strategi secara berhasil.",
    "LO 10-2 Menjelaskan mengapa perekrutan, pelatihan, dan retensi orang yang tepat merupakan komponen kunci dari proses eksekusi strategi.",
    "LO 10-3 Menyadari bahwa eksekusi strategi yang baik menuntut pembangunan dan peningkatan sumber daya serta kapabilitas organisasi secara berkelanjutan.",
    "LO 10-4 Mengidentifikasi dan menetapkan struktur organisasi yang mendukung strategi serta mengorganisasikan upaya kerja.",
    "LO 10-5 Memahami kelebihan dan kekurangan pengambilan keputusan yang tersentralisasi dan terdesentralisasi dalam mengimplementasikan strategi yang dipilih."
  ],
  sections: [
    {
      no: "9.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi ini membahas tahap eksekusi strategi, yaitu tahap yang mengubah rencana strategis menjadi tindakan nyata dan hasil yang terukur. Apabila sesi sebelumnya menitikberatkan pada perumusan strategi yang bersifat analitis dan berorientasi pasar, sesi ini menitikberatkan pada aspek operasional dan keorganisasian, yaitu bagaimana manajemen menata sumber daya manusia, kapabilitas organisasi, dan struktur organisasi agar strategi dapat dijalankan dengan tingkat kecakapan yang tinggi. Pembahasan mengacu pada Bab 10 buku Thompson, Peteraf, Gamble dan Strickland (2024) yang berjudul <em>Building an Organization Capable of Good Strategy Execution: People, Capabilities, and Structure</em>.</p>
<p>Setelah menyelesaikan sesi ini, mahasiswa diharapkan mampu mencapai capaian pembelajaran sebagai berikut:</p>
<p>Pertama, memahami apa yang harus dilakukan oleh para manajer agar strategi dapat dilaksanakan dengan berhasil. Kedua, menjelaskan alasan mengapa perekrutan, pelatihan, dan retensi orang yang tepat merupakan komponen kunci dalam proses eksekusi strategi. Ketiga, menyadari bahwa eksekusi strategi yang baik menuntut pembangunan dan peningkatan sumber daya serta kapabilitas organisasi secara terus menerus. Keempat, mengidentifikasi dan menetapkan struktur organisasi yang mendukung strategi serta mengorganisasikan upaya kerja secara tepat. Kelima, memahami kelebihan dan kekurangan pengambilan keputusan yang tersentralisasi maupun terdesentralisasi dalam mengimplementasikan strategi yang telah dipilih.</p>`
    },
    {
      no: "9.2",
      title: "Kerangka Umum Eksekusi Strategi",
      body: `<p>Merumuskan strategi yang baik baru merupakan separuh dari pekerjaan manajemen strategik, sedangkan separuh lainnya adalah membangun organisasi yang mampu menjalankan strategi tersebut. Menurut Thompson et al. (2024), perumusan strategi merupakan aktivitas yang digerakkan oleh analisis terhadap kondisi pasar serta sumber daya dan kapabilitas perusahaan, sedangkan eksekusi strategi merupakan aktivitas yang digerakkan oleh operasi, yang berpusat pada pengelolaan orang, sumber daya, proses bisnis, dan struktur organisasi. Dengan demikian, keterampilan manajerial yang dibutuhkan pada kedua tahap tersebut tidak sama, dan banyak eksekutif mengakui bahwa menjalankan strategi jauh lebih sulit daripada merumuskannya. Sebuah survei terhadap 400 CEO di Amerika Serikat, Eropa, dan Asia bahkan menemukan bahwa keunggulan eksekusi merupakan tantangan nomor satu yang dihadapi perusahaan mereka (Thompson et al., 2024).</p>
<p>Eksekusi strategi merupakan pekerjaan bagi seluruh tim manajemen, bukan hanya bagi segelintir eksekutif senior. Setiap manajer memiliki tanggung jawab eksekusi strategi di wilayah kewenangannya masing-masing, dan seluruh karyawan merupakan partisipan aktif dalam proses eksekusi tersebut. Manajer puncak harus mengandalkan dukungan aktif manajer madya dan manajer lini bawah untuk menerapkan praktik operasi baru di berbagai unit, sedangkan manajer madya dan lini bawah harus memastikan karyawan garis depan melaksanakan aktivitas rantai nilai yang kritikal bagi strategi dengan tingkat kecakapan yang memadai. Oleh karena itu, semakin besar organisasi, semakin besar pula ketergantungan keberhasilan eksekusi pada kerja sama dan keterampilan implementasi para manajer operasional di tingkat bawah.</p>
<p>Meskipun pendekatan eksekusi harus disesuaikan dengan situasi masing-masing perusahaan, terdapat sepuluh tugas manajerial dasar yang harus dipenuhi dalam setiap proses eksekusi strategi, yaitu:</p>
<p>(1) mengisi organisasi dengan manajer dan karyawan yang mampu melaksanakan strategi dengan baik; (2) mengembangkan sumber daya dan kapabilitas organisasi yang dibutuhkan bagi keberhasilan eksekusi; (3) menciptakan struktur organisasi yang mendukung strategi; (4) mengalokasikan sumber daya yang memadai, baik anggaran maupun nonanggaran, bagi upaya eksekusi; (5) menetapkan kebijakan dan prosedur yang memfasilitasi eksekusi strategi; (6) mengadopsi proses manajemen bisnis yang mendorong perbaikan berkelanjutan dalam pelaksanaan aktivitas rantai nilai; (7) memasang sistem informasi dan sistem operasi yang memungkinkan personel menjalankan aktivitas esensial; (8) mengaitkan imbalan secara langsung dengan pencapaian sasaran kinerja; (9) menumbuhkan budaya korporat yang mendorong eksekusi strategi yang baik; serta (10) menjalankan kepemimpinan yang diperlukan untuk mendorong proses eksekusi ke depan (Thompson et al., 2024).</p>
<p>Dari kesepuluh tugas tersebut, terdapat dua indikator utama yang menandai eksekusi strategi yang baik, yaitu apakah perusahaan mencapai target kinerjanya dan apakah perusahaan telah mencapai kecakapan nyata dalam melaksanakan aktivitas rantai nilai yang kritikal bagi strategi. Ketika strategi gagal, kegagalan tersebut sering kali bersumber dari eksekusi yang buruk, bukan dari rumusan strategi itu sendiri. Dengan demikian, manajer perlu memulai agenda tindakannya dengan menilai secara mendalam apa yang harus dilakukan organisasi secara berbeda, kemudian menentukan bagaimana perubahan internal tersebut diwujudkan secara tepat waktu.</p>`
    },
    {
      no: "9.3",
      title: "Tiga Tindakan Kunci Membangun Organisasi yang Mampu Mengeksekusi Strategi",
      body: `<p>Bab ini memusatkan perhatian pada tiga tugas pertama dari sepuluh tugas eksekusi strategi, karena ketiganya merupakan fondasi keorganisasian yang menentukan kelancaran tugas-tugas lainnya. Menurut Thompson et al. (2024), membangun organisasi yang mampu melaksanakan strategi dengan baik bertumpu pada tiga tindakan kunci, yaitu: (1) penataan staf organisasi atau <em>staffing the organization</em>, yang mencakup pembentukan tim manajemen yang kuat serta perekrutan, pelatihan, dan retensi karyawan yang berbakat; (2) pengembangan sumber daya dan kapabilitas organisasi atau <em>acquiring, developing, and strengthening key resources and capabilities</em>, yang mencakup pembangunan kapabilitas yang selaras dengan strategi dan pemutakhirannya seiring perubahan kondisi eksternal; serta (3) penataan struktur organisasi dan upaya kerja atau <em>structuring the organization and work effort</em>, yang mencakup perancangan struktur organisasi, penentuan derajat kewenangan pengambilan keputusan, dan pengelolaan hubungan kerja lintas unit maupun dengan mitra eksternal.</p>
<p>Ketiga tindakan tersebut saling berkaitan dan bersifat kumulatif. Tanpa orang yang tepat, kapabilitas organisasi tidak dapat dibangun; tanpa kapabilitas yang memadai, aktivitas rantai nilai yang kritikal bagi strategi tidak dapat dilaksanakan dengan cakap; dan tanpa struktur yang sesuai, orang dan kapabilitas yang telah tersedia tidak dapat dikoordinasikan secara efektif. Oleh karena itu, ketiganya harus dikelola sebagai satu paket keputusan keorganisasian yang koheren, bukan sebagai inisiatif yang terpisah-pisah. Sub-bab berikut membahas masing-masing tindakan kunci tersebut secara berurutan.</p>`
    },
    {
      no: "9.4",
      title: "Penataan Staf Organisasi",
      body: `<p>Tindakan kunci pertama adalah memastikan organisasi diisi oleh orang-orang yang tepat, baik pada jajaran manajemen maupun pada seluruh lini karyawan. Dalam banyak industri, penambahan modal intelektual yang tepat jauh lebih menentukan keberhasilan eksekusi strategi daripada sekadar penambahan modal finansial atau aset fisik (Thompson et al., 2024).</p>
<h5>9.4.1 Membentuk Tim Manajemen yang Kuat</h5>
<p>Langkah awal penataan staf adalah menyusun tim manajemen yang kapabel. Tujuan utamanya adalah merakit tim yang memiliki bauran keterampilan, pengalaman, cara berpikir, dan gaya kepemimpinan yang sesuai dengan tuntutan strategi yang akan dijalankan. Tim manajemen yang berbakat merupakan aset yang sulit ditiru pesaing, karena kualitas kolektifnya terbentuk dari proses seleksi, pengembangan, dan pengalaman bersama yang panjang. Namun, susunan tim juga harus dievaluasi ulang setiap kali strategi berubah, karena strategi baru sering menuntut kompetensi manajerial yang berbeda. Apabila terdapat kesenjangan kompetensi, manajemen puncak perlu memutuskan apakah kesenjangan tersebut ditutup melalui promosi internal, yang berkeunggulan pada pemahaman konteks perusahaan, atau melalui perekrutan eksternal, yang berkeunggulan pada masuknya perspektif dan keahlian baru. Dengan demikian, komposisi tim manajemen merupakan keputusan strategis, bukan sekadar keputusan administrasi kepegawaian.</p>
<h5>9.4.2 Merekrut, Melatih, dan Mempertahankan Karyawan yang Kapabel</h5>
<p>Tim manajemen yang baik tidak akan berdaya tanpa dukungan karyawan yang cakap pada setiap aktivitas rantai nilai. Oleh karena itu, perusahaan yang unggul dalam eksekusi umumnya menjadikan perekrutan, pelatihan, dan retensi talenta sebagai prioritas strategis, antara lain melalui proses seleksi yang ketat dan selektif, program pelatihan yang berkesinambungan, penugasan yang menantang dan rotasi lintas fungsi untuk memperluas wawasan, kompensasi yang menarik, serta lingkungan kerja yang membuat karyawan terbaik betah dan berkembang. Sebagai ilustrasi, Deloitte membangun program pengembangan manajemen yang sistematis, termasuk universitas korporat, untuk menumbuhkan pemimpin dari dalam, sementara Cisco secara sengaja berupaya mempertahankan orang-orang kunci dari perusahaan yang diakuisisinya karena meyakini bahwa nilai akuisisi melekat pada manusianya (Thompson et al., 2024).</p>
<p>Dalam konteks Indonesia, praktik serupa dapat diamati pada Telkom Indonesia yang mengoperasikan Telkom Corporate University sebagai wahana pengembangan pemimpin dan talenta digital secara terstruktur, serta pada program <em>management trainee</em> Astra International yang telah puluhan tahun menjadi pipa talenta manajerial bagi berbagai lini bisnis grup tersebut. Implikasi manajerialnya, manajemen sumber daya manusia tidak boleh diperlakukan sebagai fungsi pendukung semata, melainkan sebagai instrumen langsung eksekusi strategi. Perusahaan yang memenangkan persaingan talenta pada umumnya lebih siap memenangkan persaingan pasar, karena kualitas eksekusi pada akhirnya ditentukan oleh kualitas orang yang menjalankannya.</p>`
    },
    {
      no: "9.5",
      title: "Membangun Sumber Daya dan Kapabilitas Organisasi yang Kritikal",
      body: `<p>Tindakan kunci kedua adalah memastikan perusahaan memiliki sumber daya dan kapabilitas organisasi yang dibutuhkan strategi. Eksekusi yang cakap mensyaratkan kapabilitas yang tepat, dan apabila strategi baru menuntut kapabilitas yang belum dimiliki, manajemen harus memperolehnya, memperluasnya, atau memperdalamnya. Selain itu, kapabilitas yang ada harus terus dimutakhirkan seiring berubahnya kondisi eksternal, karena kapabilitas yang relevan pada masa lalu belum tentu relevan pada masa depan (Thompson et al., 2024).</p>
<h5>9.5.1 Tiga Pendekatan Membangun dan Memperkuat Kapabilitas</h5>
<p>Menurut Thompson et al. (2024), terdapat tiga pendekatan utama untuk membangun dan memperkuat kapabilitas organisasi, yaitu pengembangan internal, akuisisi atau merger, dan kemitraan kolaboratif. Pertama, pengembangan internal atau <em>internal development</em> dilakukan dengan melatih orang, mengakumulasi pengalaman melalui pengulangan dan pembelajaran, serta menyempurnakan proses secara bertahap hingga aktivitas dapat dilakukan secara andal dengan biaya yang wajar. Kapabilitas pada hakikatnya merupakan hasil kombinasi keterampilan banyak orang dan rutinitas organisasi, sehingga pembangunannya memerlukan waktu, kesabaran, dan latihan berulang, serta sering kali menuntut kapabilitas dijalankan lintas fungsi, bukan terkurung dalam satu departemen. Kedua, akuisisi kapabilitas melalui merger dan akuisisi dilakukan dengan membeli perusahaan yang telah memiliki kapabilitas yang diinginkan. Keunggulan utamanya adalah kecepatan, karena membangun kapabilitas secara internal dapat memakan waktu bertahun-tahun. Namun, pendekatan ini mengandung kesulitan, karena kapabilitas melekat pada orang dan budaya perusahaan yang diakuisisi, sehingga integrasi yang buruk atau kepergian orang-orang kunci dapat membuat kapabilitas yang dibeli tidak seproduktif sebelumnya. Ketiga, akses kapabilitas melalui kemitraan kolaboratif atau <em>collaborative partnerships</em> dilakukan melalui alih daya, aliansi strategis, maupun kerja sama pembelajaran yang memungkinkan perusahaan menginternalisasi metode mitranya. Pendekatan ini relatif hemat sumber daya, namun menimbulkan ketergantungan pada mitra dan risiko kebocoran pengetahuan.</p>
<table class="bk-table"><caption>Tabel 9.1 Perbandingan Tiga Pendekatan Membangun Kapabilitas Organisasi</caption>
<thead><tr><th>Aspek</th><th>Pengembangan Internal</th><th>Merger dan Akuisisi</th><th>Kemitraan Kolaboratif</th></tr></thead>
<tbody>
<tr><td>Mekanisme</td><td>Pelatihan, pembelajaran berulang, penyempurnaan proses lintas fungsi</td><td>Membeli perusahaan yang telah memiliki kapabilitas</td><td>Alih daya, aliansi, pembelajaran dari mitra</td></tr>
<tr><td>Kecepatan</td><td>Lambat, bertahap</td><td>Cepat</td><td>Sedang</td></tr>
<tr><td>Kendali atas kapabilitas</td><td>Penuh</td><td>Tinggi, tergantung keberhasilan integrasi</td><td>Terbatas, kapabilitas berada pada mitra</td></tr>
<tr><td>Risiko utama</td><td>Waktu lama dan biaya pembelajaran</td><td>Kegagalan integrasi budaya dan kepergian orang kunci</td><td>Ketergantungan pada mitra dan kebocoran pengetahuan</td></tr>
<tr><td>Kesesuaian situasi</td><td>Kapabilitas inti jangka panjang</td><td>Kebutuhan mendesak akan kapabilitas baru</td><td>Kapabilitas pelengkap atau teknologi yang berubah cepat</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson, Peteraf, Gamble dan Strickland (2024)</td></tr></tfoot></table>
<p>Contoh penerapan ketiga pendekatan tersebut dapat diamati pada berbagai perusahaan. Beberapa perusahaan teknologi global membelanjakan puluhan miliar dolar untuk mengakuisisi perusahaan rintisan demi memperoleh kapabilitas baru secara cepat (Thompson et al., 2024). Di Indonesia, pembentukan GoTo melalui penggabungan Gojek dan Tokopedia dapat dibaca sebagai upaya menggabungkan kapabilitas transportasi dan pembayaran digital dengan kapabilitas perdagangan elektronik dalam satu ekosistem, sedangkan kemitraan bank-bank nasional dengan perusahaan teknologi finansial menunjukkan pola akses kapabilitas digital melalui kolaborasi tanpa harus membangun semuanya sendiri.</p>
<h5>9.5.2 Peran Strategis Pelatihan Karyawan</h5>
<p>Pelatihan dan pelatihan ulang karyawan memegang peran strategis ketika perusahaan mengganti strategi, ketika strategi menuntut keterampilan atau kapabilitas baru, dan ketika teknologi maupun praktik operasi berubah cepat. Dalam industri yang berbasis pengetahuan dan bergerak dinamis, pelatihan berkesinambungan menjadi prasyarat agar keterampilan tenaga kerja tidak usang. Oleh karena itu, pelatihan sebaiknya diperlakukan sebagai butir agenda strategis yang dianggarkan secara memadai, bukan sebagai pos biaya yang pertama dipangkas ketika kinerja menurun. Perusahaan terkemuka umumnya melembagakan pelatihan melalui universitas korporat, pembelajaran daring, penugasan pengembangan, dan bimbingan oleh manajer senior.</p>
<h5>9.5.3 Kapabilitas Eksekusi Strategi dan Keunggulan Bersaing</h5>
<p>Kecakapan dalam mengeksekusi strategi dapat menjadi sumber keunggulan bersaing tersendiri. Kapabilitas eksekusi yang superior sulit ditiru karena terbentuk dari rutinitas organisasi, pengetahuan kolektif, dan koordinasi lintas aktivitas yang berkembang dalam waktu lama, sehingga memenuhi kriteria sumber daya yang bernilai dan sulit direplikasi. Thompson et al. (2024) mencontohkan Zara yang mampu merancang, memproduksi dalam lot kecil, dan mendistribusikan busana baru ke gerai-gerainya dalam hitungan minggu, jauh lebih cepat daripada pesaingnya, sehingga kecepatan eksekusi rantai nilainya menjadi basis keunggulan bersaing yang berkelanjutan. Dengan demikian, perusahaan yang unggul dalam eksekusi dapat mengungguli pesaing yang strateginya serupa, karena keunggulan tidak lagi terletak pada apa yang direncanakan, melainkan pada seberapa cakap rencana tersebut dijalankan.</p>`
    },
    {
      no: "9.6",
      title: "Menyesuaikan Struktur Organisasi dengan Strategi",
      body: `<p>Tindakan kunci ketiga adalah menata struktur organisasi dan upaya kerja agar selaras dengan strategi. Struktur organisasi menetapkan pembagian kerja, garis pelaporan, kewenangan pengambilan keputusan, dan mekanisme koordinasi. Struktur yang selaras dengan strategi memperlancar eksekusi, sedangkan struktur yang tidak selaras menimbulkan friksi, kelambanan, dan kebingungan tanggung jawab. Menurut Thompson et al. (2024), penataan upaya kerja mencakup lima keputusan utama, yaitu menentukan aktivitas rantai nilai mana yang dikerjakan sendiri dan mana yang dialihdayakan, menyelaraskan struktur organisasi dengan strategi, menentukan derajat sentralisasi kewenangan, menyediakan mekanisme koordinasi lintas unit, dan memfasilitasi kolaborasi dengan mitra eksternal.</p>
<h5>9.6.1 Keputusan Aktivitas yang Dikerjakan Sendiri atau Dialihdayakan</h5>
<p>Keputusan pertama adalah menentukan aktivitas rantai nilai mana yang dilaksanakan secara internal dan mana yang dialihdayakan kepada pihak luar. Prinsip umumnya, aktivitas yang kritikal bagi strategi dan menjadi basis keunggulan bersaing sebaiknya dikerjakan sendiri agar kendali dan pembelajaran tetap berada di dalam perusahaan, sedangkan aktivitas yang bukan merupakan kompetensi inti dapat dialihdayakan kepada spesialis yang mampu mengerjakannya dengan lebih baik atau lebih murah. Alih daya yang tepat memungkinkan perusahaan memusatkan energi pada aktivitas yang paling bernilai, mengurangi birokrasi internal, dan meningkatkan fleksibilitas. Thompson et al. (2024) mencontohkan Apple yang memusatkan diri pada desain produk, perangkat lunak, dan pemasaran, sementara perakitan diserahkan kepada mitra manufaktur seperti Foxconn. Namun, alih daya mengandung risiko apabila perusahaan kehilangan kendali atas aktivitas yang ternyata penting, menjadi terlalu bergantung pada pemasok, atau tanpa sengaja memampukan mitranya menjadi pesaing di kemudian hari. Oleh karena itu, keputusan alih daya harus didasarkan pada analisis strategis, bukan semata perhitungan biaya jangka pendek.</p>
<h5>9.6.2 Menjadikan Aktivitas Kritikal bagi Strategi sebagai Blok Bangunan Utama Struktur</h5>
<p>Prinsip perancangan struktur yang paling mendasar adalah menjadikan aktivitas rantai nilai yang kritikal bagi strategi sebagai blok bangunan utama struktur organisasi. Aktivitas yang menentukan keberhasilan strategi harus menempati posisi sentral, memperoleh sumber daya yang memadai, dipimpin oleh manajer yang berpengaruh, dan tidak terfragmentasi ke banyak unit yang koordinasinya lemah. Sebaliknya, apabila aktivitas kritikal ditempatkan sebagai subordinat dari aktivitas rutin, perhatian manajerial dan anggaran akan mengalir ke tempat yang salah. Dengan demikian, struktur harus mengikuti strategi, bukan sebaliknya, sebagaimana tesis klasik yang dirujuk dalam literatur manajemen strategik.</p>
<h5>9.6.3 Jenis-Jenis Struktur Organisasi</h5>
<p>Thompson et al. (2024) mengidentifikasi empat jenis struktur organisasi dasar yang lazim dipadankan dengan strategi, yaitu struktur sederhana, struktur fungsional, struktur multidivisional, dan struktur matriks. Struktur sederhana atau <em>simple structure</em> menempatkan seorang eksekutif sentral, biasanya pemilik, yang mengambil hampir seluruh keputusan penting dan mengarahkan langsung sedikit karyawan; struktur ini cocok bagi usaha kecil dan perusahaan rintisan. Struktur fungsional atau <em>functional structure</em> mengelompokkan pekerjaan berdasarkan fungsi seperti produksi, pemasaran, dan keuangan; struktur ini mendorong spesialisasi dan efisiensi, sehingga sesuai bagi perusahaan dengan satu lini bisnis, meskipun rentan menimbulkan sekat antarfungsi. Struktur multidivisional atau <em>multidivisional structure</em> terdiri atas divisi-divisi yang relatif mandiri berdasarkan produk, pasar, atau wilayah, dengan kantor pusat korporat yang mengawasi; struktur ini sesuai bagi perusahaan terdiversifikasi. Struktur matriks atau <em>matrix structure</em> mengombinasikan dua garis pelaporan, misalnya fungsi dan proyek, untuk meningkatkan kolaborasi dan pemanfaatan sumber daya lintas unit, meskipun berisiko menimbulkan dualisme komando. Sebagai contoh Indonesia, Astra International menerapkan pola multidivisional dengan lini bisnis otomotif, jasa keuangan, alat berat, dan agribisnis yang masing-masing dikelola relatif otonom di bawah arahan korporat.</p>
<table class="bk-table"><caption>Tabel 9.2 Padanan Jenis Struktur Organisasi dengan Situasi Strategi</caption>
<thead><tr><th>Jenis Struktur</th><th>Ciri Utama</th><th>Keunggulan</th><th>Kelemahan</th><th>Kesesuaian Strategi</th></tr></thead>
<tbody>
<tr><td>Sederhana</td><td>Keputusan terpusat pada satu eksekutif</td><td>Cepat, luwes, murah</td><td>Terbatas pada skala kecil</td><td>Usaha kecil dan rintisan</td></tr>
<tr><td>Fungsional</td><td>Departementalisasi menurut fungsi</td><td>Spesialisasi dan efisiensi</td><td>Sekat antarfungsi, koordinasi lintas fungsi sulit</td><td>Bisnis tunggal</td></tr>
<tr><td>Multidivisional</td><td>Divisi mandiri per produk, pasar, atau wilayah</td><td>Fokus divisi, akuntabilitas jelas</td><td>Duplikasi sumber daya, potensi rivalitas antardivisi</td><td>Perusahaan terdiversifikasi atau multinasional</td></tr>
<tr><td>Matriks</td><td>Dua garis pelaporan sekaligus</td><td>Kolaborasi dan pemanfaatan sumber daya lintas unit</td><td>Dualisme komando, konflik prioritas</td><td>Organisasi berbasis proyek dan inovasi lintas fungsi</td></tr>
</tbody>
<tfoot><tr><td colspan="99">Sumber: diolah dari Thompson, Peteraf, Gamble dan Strickland (2024)</td></tr></tfoot></table>
<h5>9.6.4 Sentralisasi versus Desentralisasi Pengambilan Keputusan</h5>
<p>Keputusan struktural berikutnya adalah menentukan seberapa besar kewenangan dipusatkan di tingkat atas dan seberapa besar didelegasikan ke bawah. Dalam organisasi yang tersentralisasi, eksekutif puncak memegang kendali atas sebagian besar keputusan penting. Kelebihannya adalah kendali yang ketat, akuntabilitas yang jelas, dan konsistensi tindakan lintas unit, sehingga sesuai untuk situasi krisis atau ketika keputusan lintas unit harus seragam. Kekurangannya, hierarki yang panjang memperlambat respons, membebani manajemen puncak dengan informasi yang belum tentu dikuasainya, dan mematikan inisiatif karyawan. Sebaliknya, dalam organisasi yang terdesentralisasi, kewenangan didelegasikan kepada mereka yang paling dekat dengan situasi, dengan pelatihan dan batas kebijakan yang memadai. Kelebihannya adalah keputusan yang lebih cepat dan lebih terinformasi, motivasi serta rasa memiliki karyawan yang lebih tinggi, dan berkurangnya lapisan birokrasi. Kekurangannya adalah risiko keputusan yang saling bertentangan antarunit, koordinasi lintas unit yang lebih sulit, dan potensi kerugian apabila karyawan mengambil keputusan yang keliru. Menurut Thompson et al. (2024), tujuan akhir desentralisasi adalah menempatkan kewenangan pada orang atau tim yang paling dekat dan paling memahami situasi, disertai pertanggungjawaban atas hasil. Dalam praktik, perusahaan perlu menemukan titik keseimbangan; keputusan yang menyangkut arah korporat dan risiko besar tetap dipusatkan, sedangkan keputusan operasional didelegasikan. Restrukturisasi Pertamina menjadi induk dan subinduk usaha dapat dibaca sebagai upaya mendelegasikan keputusan operasional kepada subinduk agar lebih tangkas, sementara arah strategis tetap dipegang induk perusahaan.</p>
<h5>9.6.5 Koordinasi Lintas Unit Internal</h5>
<p>Struktur apa pun yang dipilih, perusahaan tetap memerlukan mekanisme koordinasi lintas unit, karena banyak kapabilitas strategis bersifat lintas fungsi dan tidak dapat dihasilkan oleh satu unit saja. Mekanisme koordinasi tersebut antara lain penunjukan manajemen di atas unit-unit yang saling terkait, tim lintas fungsi, gugus tugas, manajer penghubung, sistem insentif yang menghargai kerja sama, serta jejaring komunikasi dan sistem informasi bersama. Tanpa mekanisme tersebut, unit-unit cenderung mengoptimalkan kepentingannya sendiri sehingga terjadi fenomena silo yang merugikan eksekusi strategi secara keseluruhan. Oleh karena itu, manajer perlu memastikan bahwa ukuran kinerja dan imbalan tidak semata dinilai per unit, melainkan juga atas kontribusi terhadap hasil bersama.</p>
<h5>9.6.6 Kolaborasi dengan Mitra Eksternal dan Struktur Jejaring</h5>
<p>Batas organisasi modern semakin cair karena banyak aktivitas dilakukan bersama pemasok, distributor, penyedia jasa alih daya, dan mitra aliansi. Perusahaan memerlukan manajer penghubung atau tim antarmuka yang bertugas menjaga hubungan, menyelaraskan sasaran, dan memastikan aliran informasi dengan para mitra tersebut. Bentuk paling maju dari pola ini adalah struktur jejaring atau <em>network structure</em>, yaitu konfigurasi beberapa organisasi independen yang aktivitasnya diorganisasikan oleh satu perusahaan inti untuk menghasilkan produk atau jasa bersama (Thompson et al., 2024). Dalam struktur jejaring yang dikelola dengan baik, perusahaan inti memusatkan diri pada kapabilitas yang paling bernilai dan mengorkestrasi kontribusi para mitra. Implikasinya, kemampuan mengelola hubungan antarorganisasi kini menjadi kapabilitas manajerial yang sama pentingnya dengan kemampuan mengelola unit internal.</p>`
    },
    {
      no: "9.7",
      title: "Rangkuman",
      body: `<p>Eksekusi strategi merupakan aktivitas yang digerakkan oleh operasi dan menuntut keterampilan manajerial yang berbeda dari perumusan strategi. Proses eksekusi mencakup sepuluh tugas manajerial dasar yang melibatkan seluruh jajaran manajemen dan karyawan, dan keberhasilannya ditandai oleh tercapainya target kinerja serta kecakapan nyata dalam melaksanakan aktivitas rantai nilai yang kritikal bagi strategi. Fondasi dari seluruh tugas tersebut adalah membangun organisasi yang mampu mengeksekusi strategi melalui tiga tindakan kunci, yaitu menata staf organisasi, membangun sumber daya dan kapabilitas, serta menyesuaikan struktur organisasi dengan strategi.</p>
<p>Penataan staf mencakup pembentukan tim manajemen yang kuat serta perekrutan, pelatihan, dan retensi karyawan berbakat, karena modal intelektual merupakan penentu utama kualitas eksekusi. Kapabilitas organisasi dapat dibangun melalui tiga jalur, yaitu pengembangan internal, merger dan akuisisi, serta kemitraan kolaboratif, dan masing-masing jalur memiliki keunggulan serta risiko yang berbeda. Kapabilitas eksekusi yang superior, sebagaimana ditunjukkan Zara, dapat menjadi sumber keunggulan bersaing tersendiri karena sulit ditiru pesaing.</p>
<p>Penataan struktur menuntut keputusan mengenai aktivitas yang dialihdayakan, penempatan aktivitas kritikal sebagai blok bangunan utama struktur, pemilihan jenis struktur yang sesuai di antara struktur sederhana, fungsional, multidivisional, dan matriks, penentuan keseimbangan sentralisasi dan desentralisasi kewenangan, serta penyediaan mekanisme koordinasi lintas unit dan kolaborasi dengan mitra eksternal. Dengan demikian, struktur harus mengikuti strategi, dan manajer yang efektif memperlakukan orang, kapabilitas, dan struktur sebagai satu kesatuan rancangan keorganisasian yang menopang keberhasilan eksekusi strategi.</p>`
    },
    {
      no: "9.8",
      title: "Daftar Pustaka",
      body: `<p>Thompson, A. A., Peteraf, M. A., Gamble, J. E. dan Strickland, A. J. (2024). <em>Crafting and Executing Strategy: The Quest for Competitive Advantage, Concepts and Cases</em>. 2024 Release. McGraw Hill.</p>
<p>Wheelen, T. L., Hunger, J. D., Hoffman, A. N. dan Bamford, C. E. (2018). <em>Strategic Management and Business Policy: Globalization, Innovation and Sustainability</em>. Edisi 15. Pearson.</p>
<p>David, F. R. dan David, F. R. (2017). <em>Strategic Management: A Competitive Advantage Approach, Concepts and Cases</em>. Edisi 16. Pearson.</p>`
    }
  ]
};
