window.MBA_BOOK = window.MBA_BOOK || {};
window.MBA_BOOK.sm = window.MBA_BOOK.sm || {};
window.MBA_BOOK.sm[2] = {
  bab: 2,
  judul: "BAB 2 KONSEP STRATEGI DAN URGENSINYA BAGI PERUSAHAAN",
  sumber: "Thompson, Peteraf, Gamble dan Strickland (2024), Crafting and Executing Strategy, 2024 Release, McGraw Hill",
  lo: [
    "LO 1-1 Memahami apa yang dimaksud dengan strategi perusahaan dan mengapa strategi tersebut perlu berbeda dari strategi para pesaing.",
    "LO 1-2 Memahami konsep keunggulan kompetitif yang berkelanjutan (sustainable competitive advantage).",
    "LO 1-3 Menjelaskan bagaimana lima pendekatan strategis yang paling mendasar dapat membedakan perusahaan dari para pesaingnya.",
    "LO 1-4 Memahami mengapa strategi perusahaan cenderung berevolusi dari waktu ke waktu.",
    "LO 1-5 Mengidentifikasi unsur-unsur yang membentuk model bisnis yang layak (viable business model).",
    "LO 1-6 Menyebutkan tiga uji strategi pemenang (three tests of a winning strategy)."
  ],
  sections: [
    {
      no: "2.1",
      title: "Capaian Pembelajaran",
      body: `<p>Sesi ini membahas konsep paling mendasar dalam manajemen stratejik, yaitu pengertian strategi perusahaan dan alasan mengapa strategi menjadi penentu utama keberhasilan organisasi dalam jangka panjang. Lingkungan bisnis dalam satu dekade terakhir mengalami perubahan yang sangat cepat akibat perkembangan teknologi digital, kecerdasan buatan, perubahan perilaku konsumen, tuntutan keberlanjutan lingkungan, serta gangguan rantai pasok global. Namun, prinsip-prinsip manajemen stratejik tetap relevan karena keberhasilan yang bertahan lama hanya dapat dijelaskan oleh strategi yang dirumuskan dengan baik, dieksekusi dengan baik, dan terus disesuaikan dengan keadaan (Thompson et al., 2024). Oleh karena itu, pemahaman yang utuh mengenai hakikat strategi merupakan fondasi bagi seluruh pembahasan pada sesi-sesi berikutnya.</p>
      <p>Setelah mengikuti sesi ini, mahasiswa diharapkan memiliki capaian pembelajaran sebagai berikut:</p>
      <p><strong>1)</strong> Memahami apa yang dimaksud dengan strategi perusahaan dan mengapa strategi tersebut perlu berbeda dari strategi para pesaing. <strong>2)</strong> Memahami konsep keunggulan kompetitif yang berkelanjutan (<em>sustainable competitive advantage</em>). <strong>3)</strong> Menjelaskan bagaimana lima pendekatan strategis yang paling mendasar dapat membedakan perusahaan dari para pesaingnya. <strong>4)</strong> Memahami mengapa strategi perusahaan cenderung berevolusi dari waktu ke waktu. <strong>5)</strong> Mengidentifikasi unsur-unsur yang membentuk model bisnis yang layak (<em>viable business model</em>). <strong>6)</strong> Menyebutkan tiga uji strategi pemenang (<em>three tests of a winning strategy</em>) beserta uji kelayakan moralnya.</p>`
    },
    {
      no: "2.2",
      title: "Pengertian Strategi Perusahaan",
      body: `<p>Setiap perusahaan yang beroperasi dalam lingkungan persaingan dituntut untuk menentukan cara memenangkan pelanggan dan mengungguli para pesaingnya. Menurut Thompson et al. (2024), strategi perusahaan adalah serangkaian tindakan terkoordinasi yang diambil oleh para manajer untuk mengungguli pesaing dan mencapai profitabilitas yang superior. Definisi tersebut menegaskan bahwa strategi bukan sekadar dokumen perencanaan, melainkan komitmen manajerial terhadap sekumpulan pilihan yang koheren mengenai cara bersaing. Tujuan dari strategi yang dirumuskan dengan baik bukan keberhasilan kompetitif yang bersifat sementara, melainkan keberhasilan yang bertahan lama sehingga mampu menopang pertumbuhan dan mengamankan masa depan perusahaan. Dengan demikian, strategi dapat dipahami sebagai jawaban manajemen atas pertanyaan mendasar mengenai bagaimana perusahaan akan bersaing dan berkembang.</p>
      <p>Pilihan-pilihan mengenai cara bersaing tersebut mencakup sejumlah keputusan pokok yang saling berkaitan, yaitu: bagaimana memosisikan perusahaan di pasar, bagaimana menarik pelanggan, bagaimana bersaing melawan para rival, bagaimana mencapai target kinerja perusahaan, bagaimana memanfaatkan peluang untuk menumbuhkan bisnis, serta bagaimana merespons perubahan kondisi ekonomi dan pasar (Thompson et al., 2024). Pada sebagian besar industri, perusahaan memiliki keleluasaan yang cukup besar dalam memilih kombinasi jawaban atas pertanyaan-pertanyaan tersebut. Sebagian perusahaan berupaya mencapai biaya yang lebih rendah daripada pesaing, sedangkan sebagian lainnya mengejar keunggulan produk atau layanan pelanggan yang lebih personal. Sebagian perusahaan memilih lini produk yang luas, sementara yang lain memusatkan energi pada lini produk yang sempit, dan cakupan geografis dapat berkisar dari pasar lokal hingga pasar global. Oleh karena itu, pilihan cara bersaing harus dibuat dengan mempertimbangkan sumber daya dan kapabilitas perusahaan serta pendekatan kompetitif yang sedang dijalankan oleh para pesaing.</p>
      <h5>2.2.1 Strategi sebagai Cara Bersaing yang Berbeda</h5>
      <p>Inti dari strategi adalah bersaing secara berbeda dari para rival. Meniru strategi pesaing yang berhasil, baik melalui produk tiruan maupun perebutan posisi pasar yang sama, jarang membuahkan hasil karena tidak memberikan alasan yang kuat bagi pelanggan untuk berpindah (Thompson et al., 2024). Strategi yang baik harus memuat elemen pembeda yang menarik pelanggan dan menghasilkan tepi kompetitif, yaitu melakukan apa yang tidak dilakukan pesaing atau, lebih baik lagi, melakukan apa yang tidak mampu dilakukan pesaing. Hal tersebut tidak berarti seluruh elemen strategi harus berbeda seratus persen, melainkan cukup berbeda pada beberapa aspek yang penting bagi pembeli. Peluang keberhasilan strategi menjadi lebih besar apabila strategi tersebut diarahkan pada dua hal, yaitu menarik pembeli dengan cara yang membedakan perusahaan dari pesaing dan menempati posisi pasar yang tidak dipadati oleh pesaing kuat.</p>
      <p>Selain memberikan arah mengenai apa yang harus dilakukan, strategi juga memberikan panduan mengenai apa yang tidak boleh dilakukan oleh perusahaan. Mengetahui apa yang tidak perlu dikerjakan sama pentingnya dengan mengetahui apa yang harus dikerjakan, karena langkah stratejik yang keliru paling ringan akan memboroskan sumber daya dan paling berat dapat membahayakan kelangsungan hidup perusahaan (Thompson et al., 2024). Strategi perusahaan dapat dikenali dari pola tindakannya di pasar, antara lain tindakan untuk merebut pangsa pasar melalui fitur, desain, mutu, atau harga; tindakan memasuki atau keluar dari pasar produk dan geografis tertentu; tindakan membangun sumber daya dan kapabilitas yang penting secara kompetitif; tindakan menjalin aliansi, merger, atau akuisisi; serta tindakan memperkuat reputasi melalui program tanggung jawab sosial dan keberlanjutan lingkungan. Sebagai contoh di Indonesia, strategi PT Indofood CBP dapat dikenali dari pola tindakannya berupa penguasaan jaringan distribusi hingga ke warung-warung kecil, portofolio merek yang luas, dan integrasi vertikal ke bahan baku, sedangkan pesaing yang lebih kecil memilih fokus pada segmen premium yang sempit. Implikasi manajerialnya adalah manajer harus mampu membaca pola tindakan tersebut, baik pada perusahaannya sendiri maupun pada pesaing, sebagai langkah awal analisis stratejik.</p>`
    },
    {
      no: "2.3",
      title: "Strategi dan Keunggulan Kompetitif Berkelanjutan",
      body: `<p>Jantung dari setiap strategi adalah tindakan di pasar yang diambil manajer untuk memperoleh keunggulan kompetitif atas para pesaing. Menurut Thompson et al. (2024), perusahaan memiliki <em>competitive advantage</em> apabila perusahaan tersebut mempunyai keunggulan tertentu atas pesaing dalam menarik pembeli dan menghadapi kekuatan-kekuatan persaingan. Keunggulan kompetitif merupakan syarat untuk meraih keberhasilan pasar yang lebih besar dan profitabilitas yang lebih tinggi dalam jangka panjang. Dari definisi tersebut dapat disimpulkan bahwa strategi dan keunggulan kompetitif memiliki keterkaitan yang sangat erat, karena strategi pada dasarnya adalah kendaraan yang digunakan perusahaan untuk membangun dan mempertahankan keunggulan tersebut.</p>
      <p>Terdapat banyak jalan menuju keunggulan kompetitif, namun seluruhnya bermuara pada salah satu dari dua mekanisme dasar. Mekanisme pertama adalah memberikan produk atau jasa yang dinilai pembeli memiliki nilai lebih tinggi dibandingkan tawaran pesaing (<em>higher perceived value</em>). Mekanisme kedua adalah menghasilkan produk atau jasa secara lebih efisien sehingga biaya per unit menjadi lebih rendah (<em>lower costs</em>). Apapun bentuknya, penyampaian nilai yang superior atau penyampaian nilai yang lebih efisien hampir selalu menuntut perusahaan menjalankan aktivitas rantai nilai secara berbeda dari pesaing dan membangun kapabilitas yang tidak mudah ditandingi (Thompson et al., 2024). Sebagai ilustrasi, Apple membangun keunggulan melalui produk yang dirancang indah, canggih, dan mudah digunakan, sedangkan peritel diskon membangun keunggulan melalui efisiensi logistik dan skala pembelian yang menekan biaya.</p>
      <p>Keunggulan kompetitif baru benar-benar bernilai apabila bersifat berkelanjutan. Keunggulan kompetitif dikatakan <em>sustainable</em> apabila keunggulan tersebut mampu bertahan dari upaya peniruan maupun penyaingan oleh kompetitor, sehingga elemen pembeda strategi tetap memberikan tepi kompetitif dalam jangka waktu yang lama (Thompson et al., 2024). Sumber keberlanjutan tersebut umumnya berasal dari kapabilitas dan sumber daya yang sulit ditiru, misalnya reputasi merek yang kuat, jaringan distribusi yang mengakar, teknologi yang dipatenkan, budaya organisasi, atau efek jaringan antar pengguna. Di Indonesia, keunggulan Gojek pada masa awal pertumbuhannya bersumber dari efek jaringan dua sisi antara mitra pengemudi dan konsumen serta ekosistem layanan yang saling memperkuat, sehingga tidak mudah disamai oleh pendatang baru sekalipun memiliki modal besar. Implikasi manajerialnya adalah manajer tidak cukup hanya menciptakan keunggulan sesaat, melainkan harus secara sadar membangun penghalang peniruan agar keunggulan tersebut awet.</p>`
    },
    {
      no: "2.4",
      title: "Lima Pendekatan Stratejik yang Paling Mendasar",
      body: `<p>Meskipun variasi strategi antarperusahaan sangat banyak, Thompson et al. (2024) mengidentifikasi lima pendekatan stratejik generik yang paling sering digunakan dan paling andal dalam membedakan perusahaan dari pesaingnya. Kelima pendekatan tersebut merupakan kombinasi dari dua dimensi pilihan, yaitu basis keunggulan yang dikejar (biaya rendah atau diferensiasi) dan cakupan pasar yang dilayani (pasar luas atau ceruk pasar yang sempit). Pemahaman atas kelima pendekatan ini penting karena setiap pendekatan menuntut konfigurasi sumber daya, kapabilitas, dan aktivitas rantai nilai yang berbeda. Kelima pendekatan tersebut adalah sebagai berikut:</p>
      <p><strong>Pertama</strong>, strategi penyedia biaya rendah (<em>low-cost provider strategy</em>), yaitu berupaya mencapai biaya keseluruhan yang lebih rendah daripada pesaing pada produk yang menarik bagi spektrum pembeli yang luas. Biaya rendah memungkinkan perusahaan menetapkan harga lebih murah daripada pesaing atau menikmati margin lebih tebal pada harga yang setara. Contoh klasik adalah Walmart dan Southwest Airlines, sedangkan pada konteks Indonesia strategi ini tampak pada maskapai Citilink dan peritel seperti toko grosir modern yang menekan biaya operasi. <strong>Kedua</strong>, strategi diferensiasi luas (<em>broad differentiation strategy</em>), yaitu berupaya membedakan penawaran perusahaan dari penawaran pesaing melalui atribut yang menarik bagi kalangan pembeli yang luas, misalnya mutu, fitur, desain, layanan, atau citra merek, sebagaimana dilakukan Apple dan Rolex.</p>
      <p><strong>Ketiga</strong>, strategi fokus biaya rendah (<em>focused low-cost strategy</em>), yaitu memusatkan diri pada segmen pembeli yang sempit atau ceruk pasar dan mengungguli pesaing dengan biaya yang lebih rendah dalam melayani ceruk tersebut. <strong>Keempat</strong>, strategi fokus diferensiasi (<em>focused differentiation strategy</em>), yaitu memusatkan diri pada ceruk pasar yang sempit dan mengungguli pesaing dengan menawarkan atribut khusus yang paling sesuai dengan selera dan kebutuhan anggota ceruk tersebut. Di Indonesia, produsen kosmetik halal yang membidik segmen konsumen muslimah tertentu dapat dipandang menjalankan fokus diferensiasi. <strong>Kelima</strong>, strategi penyedia biaya terbaik (<em>best-cost provider strategy</em>), yaitu memberikan nilai lebih kepada pelanggan dengan memadukan atribut produk kelas menengah ke atas dengan harga yang lebih rendah daripada pesaing berkualitas setara. Pendekatan kelima ini merupakan strategi hibrida yang menuntut perusahaan mampu memasukkan atribut menarik pada biaya yang lebih rendah dibandingkan rival dengan atribut serupa (Thompson et al., 2024).</p>
      <table class="bk-table">
        <caption>Tabel 2.1 Lima Pendekatan Stratejik Generik dan Karakteristiknya</caption>
        <thead>
          <tr><th>Pendekatan Stratejik</th><th>Basis Keunggulan</th><th>Cakupan Pasar</th><th>Tuntutan Kapabilitas Utama</th><th>Contoh</th></tr>
        </thead>
        <tbody>
          <tr><td>Penyedia biaya rendah</td><td>Biaya total terendah</td><td>Luas</td><td>Efisiensi operasi, skala ekonomi, disiplin biaya</td><td>Walmart; Citilink</td></tr>
          <tr><td>Diferensiasi luas</td><td>Atribut pembeda bernilai</td><td>Luas</td><td>Inovasi, mutu, pemasaran merek</td><td>Apple; Aqua</td></tr>
          <tr><td>Fokus biaya rendah</td><td>Biaya terendah pada ceruk</td><td>Sempit</td><td>Efisiensi yang disesuaikan dengan ceruk</td><td>Maskapai carter regional</td></tr>
          <tr><td>Fokus diferensiasi</td><td>Atribut khusus bagi ceruk</td><td>Sempit</td><td>Pemahaman mendalam kebutuhan ceruk</td><td>Rolex; kosmetik halal premium</td></tr>
          <tr><td>Penyedia biaya terbaik</td><td>Nilai lebih: mutu menengah-atas dengan harga lebih rendah</td><td>Luas hingga menengah</td><td>Kemampuan hibrida menekan biaya sekaligus menaikkan atribut</td><td>Toyota Camry; Kopi Kenangan</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot>
      </table>
      <p>Cara menggunakan kerangka ini adalah dengan terlebih dahulu menetapkan dua pilihan mendasar, yaitu apakah keunggulan akan dibangun di atas biaya atau diferensiasi, dan apakah perusahaan akan melayani pasar luas atau ceruk tertentu. Setelah pilihan ditetapkan, seluruh aktivitas rantai nilai, alokasi sumber daya, dan indikator kinerja harus diselaraskan dengan pendekatan yang dipilih agar strategi tidak terjebak di posisi tengah yang tidak jelas. Implikasi manajerialnya adalah konsistensi; perusahaan yang mencoba menjadi segalanya bagi semua orang umumnya kalah dari pesaing yang fokus pada satu pendekatan yang dieksekusi dengan disiplin.</p>`
    },
    {
      no: "2.5",
      title: "Evolusi Strategi: Unsur Proaktif dan Reaktif",
      body: `<p>Strategi perusahaan tidak bersifat statis, melainkan berevolusi dari waktu ke waktu. Perubahan kondisi pasar, kemajuan teknologi, langkah baru para pesaing, pergeseran kebutuhan pembeli, serta munculnya peluang dan gagasan baru untuk memperbaiki strategi menuntut manajemen melakukan penyesuaian secara berkala (Thompson et al., 2024). Selain itu, sebagian elemen strategi dapat gagal di lapangan sehingga perlu ditinggalkan. Oleh karena itu, merumuskan strategi merupakan proses yang berkelanjutan, bukan peristiwa satu kali, dan kemampuan beradaptasi menjadi bagian tidak terpisahkan dari manajemen stratejik.</p>
      <p>Strategi yang terealisasi (<em>realized strategy</em>) pada dasarnya merupakan perpaduan dua unsur. Unsur pertama adalah strategi terencana atau <em>deliberate strategy</em>, yaitu elemen strategi proaktif yang direncanakan secara sengaja, terdiri atas inisiatif baru yang dirancang manajemen ditambah elemen strategi lama yang berlanjut karena terbukti berjalan baik. Unsur kedua adalah strategi yang muncul atau <em>emergent strategy</em>, yaitu elemen strategi reaktif yang lahir sebagai tanggapan yang tidak direncanakan atas perkembangan yang tidak terduga, misalnya krisis, langkah mengejutkan pesaing, atau peluang yang tiba-tiba terbuka (Thompson et al., 2024). Dengan demikian, strategi terealisasi dapat dirumuskan secara sederhana sebagai berikut: strategi terealisasi = elemen strategi terencana yang berlanjut + inisiatif baru yang direncanakan + elemen strategi <em>emergent</em>, dikurangi elemen strategi lama yang ditinggalkan (<em>abandoned strategy elements</em>).</p>
      <p>Contoh evolusi strategi dapat diamati pada banyak perusahaan Indonesia selama pandemi COVID-19. Sejumlah restoran dan peritel yang semula mengandalkan penjualan gerai fisik secara cepat mengembangkan kanal pesan-antar digital dan bermitra dengan platform seperti GoFood dan GrabFood; respons yang semula bersifat darurat tersebut kemudian menjadi elemen permanen strategi omnikanal mereka. Demikian pula Gojek yang bermula dari layanan ojek panggilan berevolusi menjadi ekosistem pembayaran dan logistik seiring terbukanya peluang baru. Implikasi manajerialnya adalah manajer perlu menyeimbangkan disiplin perencanaan dengan kepekaan terhadap sinyal pasar, karena strategi yang seluruhnya kaku akan tertinggal oleh perubahan, sedangkan strategi yang seluruhnya reaktif akan kehilangan arah jangka panjang.</p>`
    },
    {
      no: "2.6",
      title: "Strategi dan Model Bisnis Perusahaan",
      body: `<p>Konsep yang berkaitan erat dengan strategi adalah model bisnis. Menurut Thompson et al. (2024), <em>business model</em> menjelaskan logika perusahaan dalam menghasilkan uang, yaitu bagaimana strategi yang dijalankan akan menciptakan nilai bagi pelanggan sekaligus menghasilkan pendapatan yang memadai untuk menutup biaya dan menghasilkan laba yang menarik. Apabila strategi menjawab pertanyaan mengenai bagaimana perusahaan bersaing, model bisnis menjawab pertanyaan mengenai bagaimana perusahaan akan memperoleh keuntungan dari cara bersaing tersebut. Dari kedua pengertian tersebut dapat disimpulkan bahwa strategi dan model bisnis saling melengkapi; strategi yang menarik tidak akan bertahan apabila tidak ditopang model bisnis yang layak secara ekonomi.</p>
      <p>Model bisnis yang layak dibangun di atas dua elemen pokok. Elemen pertama adalah proposisi nilai pelanggan (<em>customer value proposition</em>), yaitu rencana perusahaan untuk memuaskan keinginan dan kebutuhan pelanggan pada harga yang dianggap pelanggan sepadan dengan nilai yang diterima. Semakin besar nilai yang diberikan dan semakin rendah harganya, semakin menarik proposisi nilai tersebut bagi pelanggan. Elemen kedua adalah formula laba (<em>profit formula</em>), yaitu rencana perusahaan mengenai struktur biaya yang memungkinkan penciptaan nilai tersebut tetap menghasilkan laba yang memadai. Secara sederhana kerangka ini dapat dituliskan dengan tiga notasi, yaitu V sebagai nilai yang diterima pelanggan, P sebagai harga, dan C sebagai biaya; proposisi nilai semakin kuat apabila selisih V dikurangi P semakin besar, sedangkan formula laba semakin sehat apabila selisih P dikurangi C semakin besar (Thompson et al., 2024). Model bisnis yang layak menuntut kedua selisih tersebut positif secara bersamaan dalam jangka panjang.</p>
      <p>Beragam contoh memperlihatkan bagaimana model bisnis membedakan perusahaan sekalipun produknya serupa. Media penyiaran gratis mengandalkan pendapatan iklan, sedangkan layanan alir digital berlangganan seperti Netflix mengandalkan iuran bulanan pelanggan; keduanya menyampaikan hiburan namun dengan formula laba yang sangat berbeda. Produsen pisau cukur menerapkan model umpan dan kail dengan menjual gagang murah dan mengambil laba dari isi ulang. Pada konteks Indonesia, model bisnis GoPay dan dompet digital lain pada awalnya membakar dana promosi untuk membangun basis pengguna, kemudian memonetisasi melalui biaya layanan pedagang dan produk keuangan; kelayakan model tersebut diuji dari kemampuannya menutup biaya akuisisi pelanggan dalam jangka panjang. Implikasi manajerialnya adalah manajer senior harus menguji secara berkala apakah proposisi nilai masih relevan dan apakah formula laba masih berkelanjutan, karena perubahan teknologi dapat meruntuhkan model bisnis yang semula kokoh.</p>`
    },
    {
      no: "2.7",
      title: "Tiga Uji Strategi Pemenang dan Uji Kelayakan Moral",
      body: `<p>Tidak semua strategi layak disebut strategi pemenang. Thompson et al. (2024) mengajukan tiga uji yang harus dilalui suatu strategi agar dapat digolongkan sebagai <em>winning strategy</em>, dan ketiganya digunakan baik untuk menilai strategi yang sedang berjalan maupun untuk memilih di antara alternatif strategi yang diusulkan. Strategi yang gagal pada salah satu uji patut diragukan kelayakannya dan perlu diperbaiki sebelum dieksekusi lebih lanjut. Ketiga uji tersebut diuraikan sebagai berikut.</p>
      <p><strong>Uji pertama adalah uji kesesuaian (<em>the fit test</em>)</strong>, yaitu seberapa baik strategi cocok dengan situasi perusahaan. Kesesuaian tersebut mencakup tiga dimensi, yaitu kesesuaian eksternal dengan kondisi industri, persaingan, dan peluang pasar; kesesuaian internal dengan sumber daya, kapabilitas, dan kekuatan kompetitif perusahaan; serta kesesuaian dinamis, dalam arti strategi tetap selaras dengan situasi yang terus berubah dari waktu ke waktu. <strong>Uji kedua adalah uji keunggulan kompetitif (<em>the competitive advantage test</em>)</strong>, yaitu apakah strategi mampu menghasilkan keunggulan kompetitif yang cukup besar (<em>sizable</em>) dan tahan lama (<em>durable</em>); semakin besar dan semakin awet keunggulan yang dihasilkan, semakin kuat strategi tersebut. <strong>Uji ketiga adalah uji kinerja (<em>the performance test</em>)</strong>, yaitu apakah strategi menghasilkan kinerja perusahaan yang baik, yang ditandai oleh dua indikator utama berupa profitabilitas dan kekuatan finansial serta kekuatan kompetitif dan posisi pasar perusahaan (Thompson et al., 2024).</p>
      <table class="bk-table">
        <caption>Tabel 2.2 Tiga Uji Strategi Pemenang dan Pertanyaan Kuncinya</caption>
        <thead>
          <tr><th>Uji</th><th>Pertanyaan Kunci</th><th>Indikator Penilaian</th></tr>
        </thead>
        <tbody>
          <tr><td>Uji kesesuaian (fit test)</td><td>Seberapa baik strategi cocok dengan situasi eksternal dan internal perusahaan serta perubahannya?</td><td>Kesesuaian eksternal, kesesuaian internal, kesesuaian dinamis</td></tr>
          <tr><td>Uji keunggulan kompetitif</td><td>Apakah strategi menghasilkan keunggulan atas pesaing yang besar dan tahan lama?</td><td>Ukuran keunggulan dan daya tahannya terhadap peniruan</td></tr>
          <tr><td>Uji kinerja</td><td>Apakah strategi menghasilkan kinerja perusahaan yang baik?</td><td>Profitabilitas dan kekuatan finansial; kekuatan kompetitif dan posisi pasar</td></tr>
        </tbody>
        <tfoot><tr><td colspan="99">Sumber: diolah dari Thompson et al. (2024)</td></tr></tfoot>
      </table>
      <p>Cara menggunakan kerangka ini dalam praktik adalah menjadikannya daftar periksa evaluasi berkala. Manajemen menilai strategi berjalan terhadap ketiga uji tersebut; apabila kesesuaian menurun karena perubahan lingkungan, keunggulan menipis karena peniruan pesaing, atau kinerja finansial melemah, strategi perlu direvisi. Sebagai contoh, strategi sejumlah peritel departemen di Indonesia yang lambat beradaptasi terhadap perdagangan elektronik gagal pada uji kesesuaian dinamis, dan hal tersebut tercermin pada penutupan gerai serta penurunan kinerja mereka.</p>
      <h5>2.7.1 Uji Kelayakan Moral</h5>
      <p>Selain ketiga uji tersebut, strategi pemenang juga harus lulus uji penilaian moral (<em>test of moral scrutiny</em>). Strategi tidak dapat dianggap berhasil apabila keberhasilannya diperoleh melalui cara yang tidak etis, melanggar hukum, atau merugikan pemangku kepentingan secara tidak wajar, karena praktik semacam itu pada akhirnya menghancurkan reputasi dan nilai perusahaan (Thompson et al., 2024). Kasus manipulasi laporan keuangan pada beberapa emiten menunjukkan bahwa kinerja yang tampak baik namun diperoleh dengan cara tidak etis tidak pernah berkelanjutan. Oleh karena itu, pertimbangan etika, tanggung jawab sosial, dan keberlanjutan lingkungan harus melekat pada perumusan strategi, bukan sekadar pelengkap.</p>`
    },
    {
      no: "2.8",
      title: "Urgensi Perumusan dan Eksekusi Strategi",
      body: `<p>Perumusan dan eksekusi strategi merupakan tugas manajerial yang paling utama karena dua alasan mendasar. Alasan pertama, strategi yang jelas dan berdaya saing merupakan resep yang paling dapat diandalkan untuk menciptakan pelanggan, memenangkan persaingan, dan membangun keunggulan kompetitif; tanpa strategi yang jelas, keputusan-keputusan organisasi menjadi tidak terarah dan sumber daya terbuang pada inisiatif yang saling bertentangan. Alasan kedua, perusahaan yang berfokus pada eksekusi strategi cenderung menyatukan seluruh bagian organisasi; strategi yang dieksekusi dengan baik menjadi cetak biru operasional yang menyelaraskan keputusan setiap departemen dan setiap manajer menuju arah yang sama (Thompson et al., 2024). Dengan demikian, strategi bukan hanya urusan direksi, melainkan kerangka kerja bagi seluruh lapisan manajemen.</p>
      <p>Lebih lanjut, kinerja jangka panjang perusahaan sangat ditentukan oleh mutu gabungan antara perumusan dan eksekusi. Thompson et al. (2024) menegaskan bahwa "seberapa baik sebuah perusahaan berkinerja ditentukan sebagian besar oleh kualitas strateginya dan kecakapan dalam mengeksekusi strategi tersebut". Strategi yang cemerlang namun dieksekusi dengan buruk hanya menghasilkan kinerja biasa-biasa saja, sebaliknya eksekusi yang rapi atas strategi yang keliru juga tidak akan menyelamatkan perusahaan. Oleh karena itu, eksekusi yang unggul atas strategi yang unggul merupakan resep paling andal untuk menjadikan perusahaan berkinerja menonjol dalam jangka panjang, sekaligus menjadi ukuran paling meyakinkan atas keunggulan manajerialnya. Bagi mahasiswa MBA, hal ini menegaskan bahwa kompetensi stratejik mencakup dua sisi yang tidak terpisahkan, yaitu kemampuan analitis dalam merumuskan dan kemampuan kepemimpinan dalam mengeksekusi.</p>`
    },
    {
      no: "2.9",
      title: "Rangkuman",
      body: `<p>Strategi perusahaan adalah serangkaian tindakan terkoordinasi yang diambil manajer untuk mengungguli pesaing dan mencapai profitabilitas superior, dan hakikat strategi adalah bersaing secara berbeda dari para rival. Strategi yang berhasil bertumpu pada keunggulan kompetitif yang diperoleh melalui salah satu dari dua mekanisme dasar, yaitu nilai yang dipersepsikan lebih tinggi atau biaya yang lebih rendah, dan keunggulan tersebut menjadi berkelanjutan apabila dilindungi oleh kapabilitas yang sulit ditiru. Lima pendekatan stratejik generik, yaitu penyedia biaya rendah, diferensiasi luas, fokus biaya rendah, fokus diferensiasi, dan penyedia biaya terbaik, menyediakan pilihan dasar bagi perusahaan untuk membedakan diri dari pesaing.</p>
      <p>Strategi senantiasa berevolusi sebagai perpaduan antara elemen terencana (<em>deliberate</em>) dan elemen yang muncul dari respons atas keadaan tidak terduga (<em>emergent</em>), sehingga perumusan strategi merupakan proses berkelanjutan. Strategi juga harus ditopang model bisnis yang layak, yang memadukan proposisi nilai pelanggan dengan formula laba yang sehat. Sebuah strategi disebut strategi pemenang apabila lulus tiga uji, yaitu uji kesesuaian, uji keunggulan kompetitif, dan uji kinerja, serta lulus uji kelayakan moral. Pada akhirnya, perumusan dan eksekusi strategi merupakan fungsi manajemen yang paling menentukan, karena eksekusi yang unggul atas strategi yang unggul adalah resep paling andal bagi kinerja perusahaan yang menonjol dalam jangka panjang.</p>`
    },
    {
      no: "2.10",
      title: "Daftar Pustaka",
      body: `<p>Thompson, A. A., Peteraf, M. A., Gamble, J. E. dan Strickland, A. J. (2024). <em>Crafting and Executing Strategy: The Quest for Competitive Advantage, Concepts and Cases</em>. 2024 Release. McGraw Hill.</p>
      <p>Mintzberg, H. dan Waters, J. A. (1985). Of Strategies, Deliberate and Emergent. <em>Strategic Management Journal</em>, 6(3), 257-272.</p>
      <p>Porter, M. E. (1996). What Is Strategy? <em>Harvard Business Review</em>, 74(6), 61-78.</p>`
    }
  ]
};
